- Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/README.md
- Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.py
- Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/SailPointIdentityIQ.yml
- Packs/SailPointIdentityIQ/ReleaseNotes/1_0_2.md
- Packs/SailPointIdentityIQ/pack_metadata.json
- Corrected the documented integration outputs to match the actual outputs.
- Added proper error handling for failed auth
- Further details: the actual output didn't change, but it'll be recognized as failed due to changes in the yaml.
> SailPoint IdentityIQ correct yaml outputs

- Packs/GmailSingleUser/Integrations/GmailSingleUser/.pylintrc
- Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/.pylintrc
- Packs/GooglePubSub/Integrations/GooglePubSub/.pylintrc
- Packs/GoogleVisionAPI/Integrations/GoogleVisionAPI/.pylintrc
None
Ignores `Resource` class in pylint.
> Google pylintrc

- Packs/ServiceNow/TestPlaybooks/playbook-Create_ServiceNow_Ticket_and_Mirror_Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/30587
unskip Create ServiceNow Ticket and Mirror Test
Passed locally and also passed in the build
> unskip Create ServiceNow Ticket and Mirror Test

- Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
- Packs/GSuiteAdmin/TestPlaybooks/playbook-GSuiteAdmin-Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/34784
Unskip Gsuite admin TPB.
> unskip GSuiteAdmin TPB

- Packs/Base/ReleaseNotes/1_12_9.md
- Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
- Packs/Base/pack_metadata.json
- Packs/F5Silverline/.pack-ignore
> IF100 + pylint ignores

- Packs/EWS/Integrations/SecurityAndCompliance/README.md
- Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Delete_README.md
- Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAction-Preview_README.md
- Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete_README.md
- Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-Search_README.md
- Packs/EWS/Playbooks/playbook-Office_365_Search_and_Delete_README.md
related: https://github.com/demisto/etc/issues/35537
> O365 SC limitations

- Packs/FireEyeNX/TestPlaybooks/playbook-FireEyeNX-test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33216
unskip FireEyeNX-Test
passed locally
> unskip FireEyeNX-Test

- Packs/FortiGate/Integrations/FortiGate/FortiGate.py
- Packs/FortiGate/ReleaseNotes/1_0_2.md
- Packs/FortiGate/pack_metadata.json
> FotiGate - rm logs

- Packs/FireEyeEX/pack_metadata.json
- Packs/FireEyeNX/pack_metadata.json
> Updated namings

- Packs/GitHub/README.md
- [ x ] Ready
Added "Create a release" to the list of what this pack does.
> Update GitHub pack README.md

- Packs/CommonScripts/.pack-ignore
ignore RM106 for README.md in CommonScripts
> ignore RM106 for README.md in CommonScripts

- Packs/Slack/Integrations/Slack_IAM/Slack_IAM.yml
- Packs/Slack/ReleaseNotes/1_3_21.md
- Packs/Slack/pack_metadata.json
Changed the ***Access Token*** parameter type to encrypted.
> Slack IAM small fix

- Packs/PAN-OS/IncidentTypes/incidenttype-PanoramaThreatCoverage.json
- Packs/PAN-OS/ReleaseNotes/1_6_19.md
- Packs/PAN-OS/pack_metadata.json
Added Panorama Threat Coverage Layout to PanoramaThreatCoverage incident type
> PAN-OS: Fix PanoramaThreatCoverage type

- dev-requirements-py3.txt
> 1.4.0 sdk release

- Packs/qualys/README.md
- [x ] Ready
Created content for the Qualys Pack README. This content will appear in Marketplace.
> Create Qualys Pack README

- Packs/Thycotic/Integrations/Thycotic/README.md
Fix RM106 error for README.md in Packs/Thycotic/Integrations/Thycotic
> Fix RM106 error for README.md in Packs/Thycotic/Integrations/Thycotic

- Packs/Carbon_Black_Enterprise_Response/README.md
Create CB Enterprise Response Pack README that will appear in Marketplace.
> Create CB Enterprise Response Pack README

- Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-Prisma_Cloud.json
- Packs/PrismaCloud/Classifiers/classifier-mapper-incoming-prismaCloud_app.json
- Packs/PrismaCloud/Playbooks/playbook-PCR_-_Azure_Network_Security_Group_Misconfig.yml
- Packs/PrismaCloud/ReleaseNotes/1_8_0.md
- Packs/PrismaCloud/pack_metadata.json
fixes: Prisma Cloud Azure Playbook
* Fixes a key/name issue with the Azure_Network_Security_Group_Misconfig Prisma Cloud playbook.
* Updates Azure playbook mapper fields.
> prisma azure playbook fix

- Packs/AzureSentinel/pack_metadata.json
> Azure Sentinel - added "beta" flag to pack name

- Packs/Thycotic/pack_metadata.json
> Change name to Thycotic Secret Server

- Packs/Base/TestPlaybooks/SupportMultithreadingTest.yml
fixes: https://github.com/demisto/etc/issues/38327
> SupportMultithreading Test - increase pool size to 20 and add iterations

- Packs/Base/ReleaseNotes/1_12_13.md
- Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.py
- Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.yml
- Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship_test.py
- Packs/Base/pack_metadata.json
added deep copy of the entity_b argument before removing values that already appear in the db .
> Create relationships Fix for reference

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/27943
probably the index service in the EWS server didn’t work and should work now (https://github.com/demisto/etc/issues/38073).
> unskip EWS search-mailbox test

- Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
- Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md
- Packs/Microsoft365Defender/ReleaseNotes/1_0_2.md
- Packs/Microsoft365Defender/pack_metadata.json
- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
added the required permissions to the description and readme
> added required permissions to the description and readme

- .circleci/config.yml
- .gitlab/ci/global.yml
related: https://github.com/demisto/etc/issues/22899
after adding the coverage report new we add them to the build artifacts.
[circle build](https://app.circleci.com/pipelines/github/demisto/content/95509/workflows/c60f7453-ad08-4c9c-9db7-146b3334fd5d/jobs/387518)
> add coverage report to build artifacts

- Packs/VirusTotal/Integrations/VirusTotalV3/README.md
> vt: fixed readme

- Packs/ContentManagement/README.md
> Content management readme link fix

- Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md
- Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.py
- Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex.yml
- Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex_description.md
- Packs/TrendMicroApex/Integrations/TrendMicroApex/TrendMicroApex_test.py
- Packs/TrendMicroApex/ReleaseNotes/2_0_1.md
- Packs/TrendMicroApex/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/38256
> rebranding - apex -> apex one

- Tests/scripts/collect_tests_and_content_packs.py
- Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Added the Sanity tests in case of CommonServer changed
> Infra changes: collect tests - Added the Sanity tests in case of CommonServer changed

- Packs/Base/ReleaseNotes/1_12_14.md
- Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
- Packs/Base/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/38442
Fix a bug when the range is
> Train clustering fix ranges

- Packs/Ansible_Powered_Integrations/Integrations/MicrosoftWindows/MicrosoftWindows.yml
- Packs/Ansible_Powered_Integrations/ReleaseNotes/1_0_2.md
- Packs/Ansible_Powered_Integrations/pack_metadata.json
Fixing an issue with Ansible powered Windows integration.
> updating docker image for windows ansible integration

- dev-requirements-py3.txt
> 1.4.1 sdk release

- Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/Pipfile
- Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/Pipfile.lock
- Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/SymantecEndpointProtection_V2.py
- Packs/SymantecEndpointProtection/ReleaseNotes/1_0_3.md
- Packs/SymantecEndpointProtection/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/38509
> Fix Symantec Endpoint Protection error message

- Packs/EWS/TestPlaybooks/playbook-Get_Original_Email_-_EWS_-_Test.yml
- Packs/Phishing/Playbooks/Get_Original_Email_-_EWS.yml
- Packs/Phishing/ReleaseNotes/2_2_4.md
- Packs/Phishing/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/27571
improved the process for the search command in `Get Original Email - EWS` playbook and fixed the values in the test playbook.
> fix get original email test

- Packs/Alexa/Integrations/Alexa/Alexa.py
- Packs/Alexa/ReleaseNotes/1_1_4.md
- Packs/Alexa/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/38586
> Alexa - set default source reliability properly

- Packs/qualys/Integrations/Qualysv2/README.md
Removed unnecessary information from readme.
> Fixed readme issues

- Packs/PowershellRemoting/README.md
> pwsh remoting: fix link to xsoar.pan.dev

- Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
related: https://github.com/demisto/etc/issues/38344
> fix pytest warning for microsoft

- .gitlab/ci/global.yml
- .gitlab/ci/on-push.yml
- Utils/update_contribution_pack_in_base_branch.py
related: https://github.com/demisto/etc/issues/35481
adding the build logic to match the contribution build requirements.
build example: https://code.pan.run/xsoar/content/-/pipelines/1288325.
> adding contributions pack checkout

- Packs/PowershellRemoting/README.md
> PS Readme improvements

- Packs/VirusTotal/README.md
- Packs/VirusTotal/ReleaseNotes/2_1_2.md
- Packs/VirusTotal/pack_metadata.json
> Start partner adoption process for the VirusTotal pack

- Tests/Marketplace/upload_packs.py
- Tests/private_build/upload_packs_private.py
Fixing the logic of updating private packs in index.json
> Fixing index.json private packs list creation

- Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
- Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
- Packs/McAfee_ESM/ReleaseNotes/1_1_9.md
- Packs/McAfee_ESM/pack_metadata.json
https://github.com/demisto/etc/issues/37244
> McAfee ESM v2 - handle no user properly when fetching alarms

- Packs/BPA/Integrations/BPA/BPA.yml
- Packs/BPA/Integrations/BPA/README.md
- Packs/BPA/ReleaseNotes/1_2_8.md
- Packs/BPA/pack_metadata.json
fixes: https://panw-global.slack.com/archives/C011J0AP7J8/p1624880044197100
> BPA - Updated the *Server URL* parameter description

- Tests/Marketplace/landingPage_sections.json
This is the marketplace storefront. @glicht @Itay4 Please review and update it thanks.
> Updated storefront for June-July end

- Packs/Base/ReleaseNotes/1_12_15.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
- improved `CommonServerPython.py` to be future-proof.
- removed pytest warnings.
> common server urllib breaking changes fix

- Packs/FeedCofense/README.md
- Packs/FeedCofense/ReleaseNotes/1_0_9.md
- Packs/FeedCofense/pack_metadata.json
> Cofense Feed - Start Adopt Process

- Tests/scripts/collect_tests_and_content_packs.py
fixed the path of the conf.json file in the collect tests script.
> collect tests: fixed conf.json file path

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/32364
fixes: https://github.com/demisto/etc/issues/34482
Increased docker memory threshold
> SecurityAndCompliance: Increase docker memory

- Packs/CommonScripts/ReleaseNotes/1_3_66.md
- Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
- Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.py
- Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
- Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2_test.py
- Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
- Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
- Packs/CommonScripts/Scripts/WordTokenizeTest/WordTokenizeTest.yml
- Packs/CommonScripts/pack_metadata.json
> CommonScripts: removed pytest warnings

- Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
- Packs/TAXIIServer/ReleaseNotes/1_0_8.md
- Packs/TAXIIServer/pack_metadata.json
> TAXII Server: update docker tag

- Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule_test.py
fixed the unit test to avoid the pytest warning.
> NGINXApiModule: fixed tests

- Utils/update_contribution_pack_in_base_branch.py
> fix contrib checkout process

- Packs/TOPdesk/Integrations/TOPdesk/TOPdesk.py
- Packs/TOPdesk/ReleaseNotes/1_0_3.md
- Packs/TOPdesk/pack_metadata.json
> TOPdesk: improved code to avoid pytest warning

- dev-requirements-py3.txt
> sdk-release-1.4.2

- Packs/Tidy/Integrations/Tidy/Tidy.yml
- Packs/Tidy/ReleaseNotes/1_0_6.md
- Packs/Tidy/pack_metadata.json
> Updating docker image

- Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.py
- Packs/ARIAPacketIntelligence/ReleaseNotes/2_0_4.md
- Packs/ARIAPacketIntelligence/pack_metadata.json
- Packs/CarbonBlackDefense/Integrations/CarbonBlackLiveResponseCloud/CarbonBlackLiveResponseCloud.py
- Packs/CarbonBlackDefense/ReleaseNotes/3_0_2.md
- Packs/CarbonBlackDefense/pack_metadata.json
- Packs/F5Silverline/Integrations/F5Silverline/F5Silverline.py
- Packs/F5Silverline/ReleaseNotes/1_0_1.md
- Packs/F5Silverline/pack_metadata.json
- Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.py
- Packs/FeedAzureADConnectHealth/Integrations/AzureADConnectHealthFeed/AzureADConnectHealthFeed.yml
- Packs/FeedAzureADConnectHealth/ReleaseNotes/1_0_2.md
- Packs/FeedAzureADConnectHealth/pack_metadata.json
- Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test.py
- Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
- Packs/GoogleKeyManagementService/ReleaseNotes/1_0_3.md
- Packs/GoogleKeyManagementService/pack_metadata.json
- Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine_test.py
- Packs/Phishing/ReleaseNotes/2_2_6.md
- Packs/Phishing/Scripts/PhishingDedupPreprocessingRule/PhishingDedupPreprocessingRule.py
- Packs/Phishing/pack_metadata.json
- Packs/ReplaceMatchGroup/Scripts/ReplaceMatchGroup/ReplaceMatchGroup_test.py
- Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
- Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot_test.py
> pytest warnings

- Packs/Base/ReleaseNotes/1_12_17.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
- Packs/Troubleshoot/ReleaseNotes/2_0_2.md
- Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.py
- Packs/Troubleshoot/Scripts/TroubleshootExecuteCommand/TroubleshootExecuteCommand.yml
- Packs/Troubleshoot/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/33327
added the execute_command function
> CommonServerPython: added the execute_command function

- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
- Packs/CortexXDR/ReleaseNotes/3_0_17.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/28925, https://github.com/demisto/etc/issues/38855
> Cortex XDR - Improved error message for the test-module

- .gitignore
> added envs to ignore

- Packs/Securonix/README.md
- Packs/Securonix/ReleaseNotes/1_1_6.md
- Packs/Securonix/pack_metadata.json
> Adopt Process for Securonix

- .gitignore
- Packs/EDL/Integrations/EDL/EDL.py
- Packs/EDL/ReleaseNotes/2_0_7.md
- Packs/EDL/pack_metadata.json
Support for ETag to support conditional requests. See: https://en.wikipedia.org/wiki/HTTP_ETag
> EDL: support ETag

- Packs/MajorBreachesInvestigationandResponse/README.md
Fix broken readme URL of printnightmare playbook
> Updated README printnightmare link

- Packs/GitHub/Integrations/GitHub/README.md
> github readme: format HR and esacape broken url

- Packs/EWS/Integrations/SecurityAndCompliance/README.md
- Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
- Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
- Packs/XForceExchange/ReleaseNotes/1_1_5.md
- Packs/XForceExchange/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/38873, https://github.com/demisto/etc/issues/38897
Fixed an issue where some ip got a response with missing data from api.
> Xforce ip command crashing for some ips bug fix

- Packs/SplunkPy/Integrations/SplunkPy/README.md
- [x ] Ready
Links to new graphics was incorrect.  Fixed the links.
> Fix links to new graphics in SplunkPy README

- Packs/MicrosoftECM/Integrations/MicrosoftECM/README.md
https://github.com/demisto/etc/issues/37654
> Microsoft ECM - add ssh to prerequisite

- Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_description.md
- Packs/AutoFocus/ReleaseNotes/1_3_4.md
- Packs/AutoFocus/pack_metadata.json
Update the description:
* Replace `<pre>` tag which isn't supported by the Server with proper code formatting
* Emphasise the daily feed deprecation
> autofocus feed: update description

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/32567
after the fix for: https://github.com/demisto/etc/issues/37588
> Unskip TAXII test

- Utils/update_contribution_pack_in_base_branch.py
> fix contrib checkout

- Packs/Base/ReleaseNotes/1_12_19.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
https://github.com/demisto/etc/issues/38549
https://github.com/demisto/dockerfiles/pull/5877
sane-pdf-reports content update
> PDF reports content release

- Packs/CommonScripts/ReleaseNotes/1_3_70.md
- Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml
- Packs/CommonScripts/pack_metadata.json
> VerifyJSON docker image update

- Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
- Packs/DeveloperTools/ReleaseNotes/1_1_5.md
- Packs/DeveloperTools/TestPlaybooks/script-PwshInvokeExpression.yml
- Packs/DeveloperTools/pack_metadata.json
> Developer Tools docker image update

- Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
- Packs/Infocyte/ReleaseNotes/1_0_3.md
- Packs/Infocyte/pack_metadata.json
> InfoCyte docker image update

- Packs/Base/ReleaseNotes/1_12_21.md
- Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
- Packs/Base/pack_metadata.json
> CS PWSH docker image update

- Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
- Packs/PowershellRemoting/ReleaseNotes/1_0_1.md
- Packs/PowershellRemoting/pack_metadata.json
> pwsh remoting docker image update

- Packs/MicrosoftTeams/ReleaseNotes/1_1_12.md
- Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.yml
- Packs/MicrosoftTeams/pack_metadata.json
> Teams docker image update

- .circleci/content_release_vars.sh
> bump version to 21.7.0

- Tests/conf.json
fixes: [29796](https://github.com/demisto/etc/issues/29796)
Test playbook fails few times on "concurrent update". Add test to parallel integrations to ensure update task will not happen on the same time.
> AWS Security Hub - add test playbook to parallel integrations

- Packs/Base/ReleaseNotes/1_12_24.md
- Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py
- Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml
- Packs/Base/Scripts/DBotFindSimilarIncidents/dbot_find_similar_incidents_test.py
- Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
- Packs/Base/pack_metadata.json
- Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.py
- Packs/CiscoWebExFeed/Integrations/CiscoWebExFeed/CiscoWebExFeed.yml
- Packs/CiscoWebExFeed/ReleaseNotes/1_1_3.md
- Packs/CiscoWebExFeed/pack_metadata.json
- Packs/Cyberint/Integrations/Cyberint/Cyberint_test.py
- Packs/DeHashed/Integrations/DeHashed/DeHashed_test.py
- Packs/EWS/Integrations/EWSO365/EWSO365.py
- Packs/EWS/ReleaseNotes/1_8_23.md
- Packs/EWS/pack_metadata.json
- Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
- Packs/FetchIndicatorsFromFile/ReleaseNotes/1_0_4.md
- Packs/FetchIndicatorsFromFile/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.py
- Packs/FetchIndicatorsFromFile/pack_metadata.json
- Packs/IntSight/Integrations/IntSight/IntSight_test.py
- Packs/MailListener/Integrations/MailListenerV2/MailListenerV2_test.py
- Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_test.py
- Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2_test.py
- Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2_test.py
- Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter_test.py
- Packs/Trello/Integrations/Trello/Trello_test.py
- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
> pytest warnings fix

- Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack.yml
- Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Kaseya_VSA__0-day_-_REvil_Ransomware_Supply_Chain_Attack_README.md
- Packs/MajorBreachesInvestigationandResponse/README.md
- Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_12.md
- Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Playbook enhancement with new XDR signatures.
> Kaseya breach enhancement

- Packs/VirusTotal-Private_API/README.md
- Packs/VirusTotal-Private_API/ReleaseNotes/1_0_9.md
- Packs/VirusTotal-Private_API/pack_metadata.json
> Start partner adoption process for the Virustotal Private API pack

- Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
- Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
- Packs/HatchingTriage/README.md
- Packs/HatchingTriage/ReleaseNotes/1_0_1.md
- Packs/HatchingTriage/pack_metadata.json
> Hatching Triage 1.0.1

- Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare.yml
- Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-1675_-_PrintNightmare_README.md
- Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_13.md
- Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
Added a reference to the newly Microsoft patch.
> Print nightmare | Microsoft patch

- Tests/conf.json
unmock prod instances of microsoft integrations to test oproxy
> Unmock oproxy prod microsoft tests

- Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData_test.py
> stabilizing fetch data testa

- Packs/QRadar/README.md
fixes: https://github.com/demisto/etc/issues/38768
> QRadar pack documentation

- Packs/ExtFilter/ReleaseNotes/1_1_5.md
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
- Packs/ExtFilter/pack_metadata.json
N/A
Fixed an issue where None returns as the result.
> Ext filter

- .github/workflows/check-contribution-form-filled.yml
fixes: https://github.com/demisto/etc/issues/39093
Checking for the PR title and aborting if needed.
https://github.com/demisto/content/pull/13626
> Contribution Form - MP contributions bugfix

- Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
- Packs/ContentManagement/ReleaseNotes/1_0_1.md
- Packs/ContentManagement/pack_metadata.json
> CM - PB inputs removal

- Packs/DeveloperTools/Integrations/XsoarPowershellTesting/XsoarPowershellTesting.yml
- Packs/DeveloperTools/ReleaseNotes/1_1_6.md
- Packs/DeveloperTools/pack_metadata.json
- Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
- Packs/PowershellRemoting/ReleaseNotes/1_0_2.md
- Packs/PowershellRemoting/pack_metadata.json
> upgraded docker image for pwsh ubuntu

- .vscode/extensions.json
> added xsoar extension

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/27164
LogRhythm-Test-Playbook failed recording mock files with the error:
`Test integration failed - server: https://localhost:4451.
Failure message: Script failed to run: Request to LogRhythm https://content.demisto.works:30083/LogRhythm.API/Services/AlarmServiceBasicAuth.svc failed, request status code: -1 and Body: . at sendRequest (script:123:23(119))`
Build workflow for example:
https://code.pan.run/xsoar/content/-/jobs/6476042
> Move LogRhythm to unmockable_integrations

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33216
Removed test from skipped.
> [Test] FireEyeNX-Test remove from skipped

- Packs/LogRhythmRest/.secrets-ignore
> update secrets ignore

- Packs/Sixgill-Darkfeed/.pack-ignore
related: https://github.com/demisto/demisto-sdk/pull/1338
added error to ignore.
> added error

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33219
Removed EmailRepIO-Test from skipped.
> [Test] Unskip EmailRepIO-Test

- .circleci/config.yml
fixes: https://github.com/demisto/etc/issues/32647
> added install sdk from ref

- Packs/GitHub/Integrations/GitHub/GitHub.py
- Packs/GitHub/ReleaseNotes/1_3_1.md
- Packs/GitHub/pack_metadata.json
This reverts commit c226982a7693b0083831accab1d6a4fc68eda7bd.
> Revert "added to commands http GitHub error message when applicable"

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/36486
Fixed AWS - EC2 credentials, and removed test from skipped.
> [Test] Fix AWS - EC2 credentials

- Packs/GitHub/Integrations/GitHub/GitHub.py
- Packs/GitHub/ReleaseNotes/1_3_1.md
- Packs/GitHub/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39150
Added to GitHub commands http error message when applicable.
> [Bug] Expand GitHub error message

- Packs/LogRhythmRest/.secrets-ignore
same as here: https://github.com/demisto/content/pull/12716
> added to ignore

- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md
fixes: https://github.com/demisto/etc/issues/38725
Added "Required permissions" section to `ad-disable-account` command docs.
> update AD Query docs

- .circleci/config.yml
related: https://github.com/demisto/content/pull/13674
fixed bash condition
> circleci/config.yml - Fix condition

- Tests/conf.json
Google PubSub increase test timeout
> [Test] Google PubSub increase test timeout

- Packs/PAN-OS/Integrations/Panorama/Panorama.py
- Packs/PAN-OS/Integrations/Panorama/Panorama.yml
- Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
- Packs/PAN-OS/ReleaseNotes/1_6_22.md
- Packs/PAN-OS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39200
> Palo Alto Networks PAN-OS - Fixed an issue where object with tag *None*

- .circleci/config.yml
- Tests/scripts/sdk_nightly_change_file_ids.py
- Tests/scripts/sdk_nightly_change_json_file_fields.py
fixes: https://github.com/demisto/etc/issues/39189
Temporary fix to SDK nightly build until this is handled: https://github.com/demisto/etc/issues/39188
> fixing sdk nightly

- Packs/Base/ReleaseNotes/1_13_3.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39234
> fix json chars obfuscation in debug-mode

- Packs/EWS/Integrations/EWSv2/EWSv2.yml
- Packs/EWS/Integrations/EWSv2/EWSv2_test.py
- Packs/EWS/ReleaseNotes/1_8_27.md
- Packs/EWS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39240
Fix the docker with the TZ issue.
> EWSv2: timezone fix

- Packs/CovalenceForSecurityProviders/pack_metadata.json
- Packs/CovalenceManagedSecurity/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39261
Changing support to partner, thus making the packs certified
> changing support to partner

- .gitlab/ci/sdk-nightly.yml
fixing sdk nightly on gitlab
same as https://github.com/demisto/content/pull/13718
> fixing sdk nightly on gitlab

- Packs/Infoblox/TestPlaybooks/playbook-Infoblox_Test.yml
- Tests/conf.json
> Fixed infoblox test-playbook

- Packs/GreyNoise/.pack-ignore
Was accidently ignoring for the other integration YML and not the community
> fixed the ignore to be from the correct YML file for GreyNoiseCommunity

- Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.yml
- Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/README.md
- Packs/HPEArubaClearPass/ReleaseNotes/1_0_1.md
- Packs/HPEArubaClearPass/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39329
Removed the port from the docs configuration as it is confusing customers and unnecessary.
> Fix aruba docs

- Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_8.md
- Packs/PANWComprehensiveInvestigation/Scripts/PanwIndicatorCreateQueries/PanwIndicatorCreateQueries.py
- Packs/PANWComprehensiveInvestigation/Scripts/PanwIndicatorCreateQueries/PanwIndicatorCreateQueries.yml
- Packs/PANWComprehensiveInvestigation/Scripts/PanwIndicatorCreateQueries/PanwIndicatorCreateQueries_test.py
- Packs/PANWComprehensiveInvestigation/pack_metadata.json
related: https://github.com/demisto/etc/issues/39321
> update AF query

- Tests/conf.json
> Remove pentera

- .circleci/content_release_vars.sh
> bump version 21.7.1

- Tests/conf.json
Skip azure security center test playbook until fixed.
> Skip Azure Scurity Center

- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
- Packs/CortexDataLake/Integrations/CortexDataLake/README.md
- Packs/CortexDataLake/ReleaseNotes/1_3_3.md
- Packs/CortexDataLake/pack_metadata.json
related: https://github.com/demisto/etc/issues/39384
> Cdl logging and README examples

- Packs/Edgescan/Integrations/Edgescan/Edgescan.yml
- Packs/Edgescan/ReleaseNotes/1_0_1.md
- Packs/Edgescan/pack_metadata.json
- Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
- Packs/qualys/ReleaseNotes/1_0_8.md
- Packs/qualys/pack_metadata.json
Removed duplicate arguments in Edgescan and QualysV2 integrations.
related to: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/10908/workflows/ca2b69f5-2b50-45d8-889f-2119b5c4b2a6/jobs/52922
> QualysV2 & Edgescan: remove duplicate args

- Packs/EWS/Integrations/EWSO365/EWSO365.py
- Packs/EWS/ReleaseNotes/1_8_29.md
- Packs/EWS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39521
Fixed fetch when second run lead to log which failed the integration.
> EWSO365 - fix issue when log failed when excluded.

- Packs/CommonTypes/.pack-ignore
- Packs/GreyNoise/.pack-ignore
- Packs/PaloAltoNetworksAutomaticSLR_Community/.pack-ignore
- Packs/TIM_Processing/.pack-ignore
Related to the new validation, ignore old entities with excluded words
https://github.com/demisto/demisto-sdk/pull/1480
> Add Ignore Pack For Name Validation

- Packs/AWS-AccessAnalyzer/.pack-ignore
- Packs/AzureSentinel/.pack-ignore
- Packs/CiscoEmailSecurity/Integrations/CiscoEmailSecurity/CiscoEmailSecurity.yml
- Packs/CiscoEmailSecurity/ReleaseNotes/1_0_4.md
- Packs/CiscoEmailSecurity/pack_metadata.json
- Packs/GmailSingleUser/.pack-ignore
- Packs/MailListener_-_POP3/.pack-ignore
- Packs/ProofpointThreatResponse/.pack-ignore
- Packs/QuestKace/.pack-ignore
- Packs/SymantecDLP/.pack-ignore
- Packs/WinRM/.pack-ignore
- Packs/Workday/Integrations/WorkdayIAMEventsGenerator/WorkdayIAMEventsGenerator.yml
- Packs/Workday/ReleaseNotes/1_2_1.md
- Packs/Workday/pack_metadata.json
- Packs/remedy_SR/.pack-ignore
related: https://github.com/demisto/demisto-sdk/pull/1511
related: https://github.com/demisto/etc/issues/39560
Ignoring beta integration errors to expand beta integration checks
> Ignoring and fixing beta integration errors

- .circleci/config.yml
Trying to extend docker client timeout when running on all files
> extending docker timeout for lint all

- .circleci/config.yml
demisto/etc#33527
demisto/etc#33528
Add a new step in **Demisto SDK Nightly - Run against Cortex XSOAR**  build to validate the upload zipped pack command
> New step for zip and upload pack in sdk nightly

- Packs/EWS/Playbooks/playbook-O365-SecurityAndCompliance-SearchAndDelete.yml
- Packs/EWS/ReleaseNotes/1_8_30.md
- Packs/EWS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39666
A task to check if an instance is enable was added (took from `O365 - Security And Compliance - Search`).
> O365 - Security And Compliance - Search And Delete is enabled

- Packs/UrlScan/Integrations/UrlScan/UrlScan.py
- Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
- Packs/UrlScan/ReleaseNotes/1_1_9.md
- Packs/UrlScan/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39709
> Urlscanio score fix

- Packs/CofenseIntelligenceV2/Integrations/CofenseIntelligenceV2/CofenseIntelligenceV2.yml
- Packs/CofenseIntelligenceV2/README.md
- Packs/CofenseIntelligenceV2/ReleaseNotes/1_0_1.md
- Packs/CofenseIntelligenceV2/pack_metadata.json
> Change listing category from Utilities to Data Enrichment & Threat Intelligence in yml file

- Packs/Polygon/Integrations/Polygon/Polygon.py
- Packs/Polygon/Integrations/Polygon/Polygon.yml
- Packs/Polygon/Integrations/Polygon/Polygon_description.md
- Packs/Polygon/Integrations/Polygon/README.md
- Packs/Polygon/Integrations/Polygon/test_data/results.json
- Packs/Polygon/Playbooks/playbook-Detonate_File_-_Group-IB_TDS_Polygon.yml
- Packs/Polygon/Playbooks/playbook-Detonate_File_-_Group-IB_TDS_Polygon_README.md
- Packs/Polygon/Playbooks/playbook-Detonate_URL_-_Group-IB_TDS_Polygon.yml
- Packs/Polygon/Playbooks/playbook-Detonate_URL_-_Group-IB_TDS_Polygon_README.md
- Packs/Polygon/README.md
- Packs/Polygon/ReleaseNotes/1_0_5.md
- Packs/Polygon/TestPlaybooks/playbook-Polygon-Test.yml
- Packs/Polygon/pack_metadata.json
TDS was renamed to THF where possible and the description was updated due to standards.
> Change product name and update pack information

- Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/README.md
- Packs/SumoLogic_Cloud_SIEM/Integrations/SumoLogicCloudSIEM/SumoLogicCloudSIEM_description.md
- Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_1.md
- Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
n/a
Update the docs to the proper TLD
n/a
> Net to com

- Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse.py
- Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse_test.py
- Packs/BitcoinAbuse/Integrations/BitcoinAbuse/test_data/get_indicators_command.json
- Packs/BitcoinAbuse/ReleaseNotes/1_0_9.md
- Packs/BitcoinAbuse/pack_metadata.json
related: https://github.com/demisto/etc/issues/40016
Fixed an issue where the *Tags* and *Traffic Light Protocol Color* integration parameters were not handled properly.
> BitcoinAbuse Tags & TLP bug

- Packs/NonSupported/Integrations/integration-VirusTotal_README.md
https://github.com/demisto/etc/issues/37523
> reworded and moved indicator score calculation

- dev-requirements-py3.txt
changing sdk to branch to check pwsh lint fix
> changing sdk to branch to check pwsh lint fix

- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.py
- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.yml
- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/test_data/results.json
- Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_1.md
- Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
> Fix rawJSON for indicators

- dev-requirements-py3.txt
hotfix: https://github.com/demisto/demisto-sdk/pull/1540
> hotfix - changing sdk version

- Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
- Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml
- Packs/Malwarebytes/ReleaseNotes/1_1_2.md
- Packs/Malwarebytes/pack_metadata.json
Fix for Suspicious activities incident creation in pagination logic.
> [malwarebytes-254] Fix for Suspicious activities incident creation.

- .circleci/content_release_vars.sh
- Tests/configure_and_test_integration_instances.py
- Tests/scripts/collect_tests_and_content_packs.py
reverted the `git diff` command change from https://github.com/demisto/content/pull/13973/files
master builds are failing as the git doesn't recognize the `HEAD` tag
> reverted git diff command

- .gitlab/ci/.gitlab-ci.yml
set git depth back to 0 to fetch all branches and tags
> GitLab CI - set git depth level to 0

- Packs/ANYRUN/Integrations/ANYRUN/README.md
- [ x] Ready
Added limitation for the anyrun-get-report command.
> Document Limitation for the anyrun-get-report command

- Packs/Kenna/TestPlaybooks/playbook-Kenna_Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33917
> kenna - fix tpb

- Packs/EWS/Playbooks/playbook-Office_365_Search_and_Delete_README.md
fixes:https://github.com/demisto/content-docs/issues/712
Add EWSv2 to dependency for Search/Delete playbook
> Update dependencies in O365 Search/Delete Docs.

- Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/README.md
fixes: https://github.com/demisto/content-docs/issues/744
Was missing a section regarding params. Added it and generated via sdk.
> Update Docs for Symantec Endpoint Protection.

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/17784
> unskipped zscaler TPB

- .github/CODEOWNERS
Added @Noy-Maimon as a code-owner on the Upload-Flow related files.
> Update Upload-Flow Codeowners

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40157
> Zscaler skip TPB

- Packs/MicrosoftTeams/.pack-ignore
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Packs/MicrosoftTeams/ReleaseNotes/1_1_15.md
- Packs/MicrosoftTeams/pack_metadata.json
Fixing master
Replaced the word "Demisto" with "XSOAR" in the yml descriptions
> Fixed validation for microsoftTeams

- Packs/CommonScripts/ReleaseNotes/1_4_20.md
- Packs/CommonScripts/Scripts/IPv4Blacklist/IPv4Blacklist.yml
- Packs/CommonScripts/Scripts/IPv4Whitelist/IPv4Whitelist.yml
- Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.yml
- Packs/CommonScripts/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40179
Updating all content that is using the old netutils image 
> netutils  - Update dockers

- Utils/github_workflow_scripts/handle_external_pr.py
> Changed contribution team

- Packs/PrismaCloud/README.md
Updated link to the new Prisma Cloud article in the readme file.
> Added link to new Prisma Cloud article in the pack's readme

- Packs/Campaign/README.md
Ready
Added a link to the campaign article in the campaign pack
> Added a link in the campaign pack readme to the article

- Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
- Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_3.md
- Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39904
Fixed all function that uses locals() to get parameters as locals() seems to be behaving different than expected on different servers.
> Carbon Black- change parameters transfer.

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40157
We won't get a license, TPB must be skipped.
> Zscaler Test - skip

- dev-requirements-py3.txt
> 1.4.7 sdk release

- Utils/github_workflow_scripts/handle_external_pr.py
> new-contrib-team

- Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.py
- Packs/LogRhythmRest/ReleaseNotes/1_0_6.md
- Packs/LogRhythmRest/TestPlaybooks/playbook-LogRhythm_REST_test.yml
- Packs/LogRhythmRest/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40358
did not add test as there seems to be an issue with our instance to run this api
> LogRhythm  - handle number_of_days arg

- Packs/Devo/Integrations/Devo_v2/Devo_v2.py
- Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
- Packs/Devo/Integrations/Devo_v2/README.md
- Packs/Devo/ReleaseNotes/1_1_3.md
- Packs/Devo/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/38552
- added the Port parameter as `443` is not always the right value
- improved docs around the writer json creds param
> Devo - add port param and improve writer json creds param doc

- Packs/EWS/Integrations/SecurityAndCompliance/README.md
- Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
- Packs/EWS/ReleaseNotes/1_9_1.md
- Packs/EWS/pack_metadata.json
Fixed an issue where the ***o365-sc-list-search*** command failed when no searches were found.
> SecurityAndCompliance: o365-sc-list-search bug fix

- Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md
- Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
small updates of integration names
> Update Microsoft READMEs

- Tests/Marketplace/copy_and_upload_packs.py
If we have only changed images the upload won't happen - this is a bug, and this pr is fixing this.
> Upload-Flow - fix verification statement

- Packs/PrismaCloud/Integrations/RedLock/RedLock.py
- Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
- Packs/PrismaCloud/ReleaseNotes/1_8_2.md
- Packs/PrismaCloud/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/24600
added casting and traceback
```
[2021-08-16 02:20:19] - [Thread-3] - [ERROR] - "RedLockTest" failed with error/s
[2021-08-16 02:20:20] - [Thread-3] - [ERROR] - Playbook "RedLockTest" has failed:
[2021-08-16 02:20:20] - [Thread-3] - [ERROR] - - Task ID: 38
[2021-08-16 02:20:20] - [Thread-3] - [ERROR] -   Command: !redlock-get-rql-response rql="config where api.name = 'aws-iam-list-access-keys'"
[2021-08-16 02:20:20] - [Thread-3] - [ERROR] -   Body:
can't concat str to bytes
```
> Prisma Cloud (RedLock) - Improved logging in case of an error.

- Tests/demistomock/demistomock.py
fixes: https://github.com/demisto/etc/issues/27068
changes in this file will be reflected in xsoar.pan.dev by the site build mechanism(within a day).
for whoever is interested, can be explained here: https://github.com/demisto/content-docs/blob/33a9c51897355e8c845a689c885d3b938a8c5afe/content-repo/create-docs.sh#L175
> add searchIndicators docs in demistomock

- Packs/CommonScripts/ReleaseNotes/1_4_22.md
- Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern.py
- Packs/CommonScripts/Scripts/ExtractAttackPattern/ExtractAttackPattern_test.py
- Packs/CommonScripts/pack_metadata.json
related: https://panw-global.slack.com/archives/C01DJNZUQ0G/p1628886654069300
Fixed an issue where the script extracted invalid *Attack Pattern* indicators.
Before the fix - 
After the fix - 
> Extract attack pattern fix

- Packs/FeedMalwareDomainList/Integrations/FeedMalwareDomainList/FeedMalwareDomainList.yml
- Packs/FeedMalwareDomainList/ReleaseNotes/1_1_4.md
- Packs/FeedMalwareDomainList/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/35843
> Deprecate malware domain

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
fixes: https://github.com/demisto/etc/issues/37811
> Microsoft Teams - add setup video

- Packs/VirusTotal/Integrations/VirusTotalV3/README.md
> added popularity ranks description + markdown formatting

- .circleci/content_release_vars.sh
> bump to 21.8.1

- Packs/Linkshadow/README.md
> Update Readme.md with some changes.

- Packs/Shodan/TestPlaybooks/playbook-Test_shodan_v2.yml
- Tests/conf.json
> Un-skip Shodan v2

- Packs/ANYRUN/Integrations/ANYRUN/ANYRUN.yml
- Packs/ANYRUN/ReleaseNotes/1_0_5.md
- Packs/ANYRUN/pack_metadata.json
- Packs/ARIAPacketIntelligence/Integrations/ARIAPacketIntelligence/ARIAPacketIntelligence.yml
- Packs/ARIAPacketIntelligence/ReleaseNotes/2_0_5.md
- Packs/ARIAPacketIntelligence/pack_metadata.json
- Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
- Packs/AbnormalSecurity/ReleaseNotes/1_0_1.md
- Packs/AbnormalSecurity/pack_metadata.json
- Packs/AcalvioShadowplex/Integrations/acalvioapp/acalvioapp.yml
- Packs/AcalvioShadowplex/ReleaseNotes/1_0_3.md
- Packs/AcalvioShadowplex/pack_metadata.json
- Packs/Accessdata/Integrations/Accessdata/Accessdata.yml
- Packs/Accessdata/ReleaseNotes/1_0_4.md
- Packs/Accessdata/pack_metadata.json
- Packs/AgariPhishingDefense/Integrations/AgariPhishingDefense/AgariPhishingDefense.yml
- Packs/AgariPhishingDefense/ReleaseNotes/1_0_4.md
- Packs/AgariPhishingDefense/pack_metadata.json
- Packs/AlienVault_USM_Anywhere/Integrations/AlienVault_USM_Anywhere/AlienVault_USM_Anywhere.yml
- Packs/AlienVault_USM_Anywhere/ReleaseNotes/1_0_5.md
- Packs/AlienVault_USM_Anywhere/pack_metadata.json
- Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.yml
- Packs/AlphaVantage/ReleaseNotes/1_0_3.md
- Packs/AlphaVantage/pack_metadata.json
- Packs/Arcanna/Integrations/ArcannaAI/ArcannaAI.yml
- Packs/Arcanna/ReleaseNotes/1_0_1.md
- Packs/Arcanna/pack_metadata.json
- Packs/Arduino/Integrations/Arduino/Arduino.yml
- Packs/Arduino/ReleaseNotes/1_0_2.md
- Packs/Arduino/pack_metadata.json
- ANY.RUN
- ARIA Packet Intelligence
- Abnormal Security
- Acalvio ShadowPlex
- Accessdata
- Agari Phishing Defense
- AlienVault USM Anywhere
- AlphaVantage
- Arcanna.AI
- Arduino
> Update Docker Image To demisto/python3 

- Packs/Respond/pack_metadata.json
- Packs/Zabbix/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39358
> fixed contribution urls

- Packs/rasterize/Integrations/rasterize/rasterize.py
- Packs/rasterize/ReleaseNotes/1_0_10.md
- Packs/rasterize/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40518
> Rasterize - update user agent

- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
- Packs/CortexXDR/ReleaseNotes/3_0_24.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/39643
> Fix handling closed incidents in mirror out

- dev-requirements-py3.txt
> SDK v1.4.8

- Packs/Base/ReleaseNotes/1_13_21.md
- Packs/Base/Scripts/script-CommonServer.yml
- Packs/Base/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40538
> CommonServer - fix oct and dec months mapping

- Tests/conf.json
skipped autofocus v2 for nightly build troubleshooting
> Skip AutoFocus v2

- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed.py
- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/GroupIB_TIA_Feed_test.py
- Packs/GroupIB_ThreatIntelligenceAttribution/Integrations/GroupIB_TIA_Feed/test_data/results.json
- Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_1_2.md
- Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json
Added more dates, tags, and TLP to feed integration.
> Add more dates, tags, and TLP to feed integration

- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py
- Packs/VirusTotal/ReleaseNotes/2_1_7.md
- Packs/VirusTotal/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40617
> fixed bug in pop ranks

- Tests/Marketplace/approved_tags.json
related: https://github.com/demisto/etc/issues/39543
Added a tag of "Iron Bank" to approved tags.
> Added Iron Bank approved tag

- Packs/QSS/README.md
fixes: https://github.com/demisto/content/pull/14445
update readme
> Qss new pr

- Packs/Base/ReleaseNotes/1_13_24.md
- Packs/Base/Scripts/StixParser/StixParser.py
- Packs/Base/Scripts/StixParser/StixParser.yml
- Packs/Base/Scripts/StixParser/StixParser_test.py
- Packs/Base/Scripts/StixParser/TestData/stix1/file-stix-ioc.xml
- Packs/Base/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40507
skipping ssdeep values
> StixParser - skip SSDEEP

- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
- Packs/QRadar/Integrations/QRadar_v3/README.md
- Packs/QRadar/ReleaseNotes/2_0_22.md
- Packs/QRadar/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40587
Adding arg of IP to abstract the filter logic for users
> QRadar enhance ip commands

- .gitlab/ci/global.yml
- Tests/Marketplace/marketplace_services.py
https://code.pan.run/xsoar/content/-/jobs/7089663
- Added login to GCP
- Fixed a default argument issue
> Login to GCP before downloading index.zip

- .gitlab/ci/global.yml
- .gitlab/ci/on-push.yml
- Tests/configure_and_test_integration_instances.py
- Tests/scripts/collect_tests_and_content_packs.py
- Utils/tests/update_contribution_pack_in_base_branch_test.py
- Utils/update_contribution_pack_in_base_branch.py
fixes the contrib checkout.
build example: https://code.pan.run/xsoar/content/-/pipelines/1411802
build example for new pack: https://code.pan.run/xsoar/content/-/jobs/6945137
> replaced the contrib checkout to use github api

- Tests/Marketplace/marketplace_constants.py
- Tests/Marketplace/marketplace_services.py
> fixing dups and attribute naming

- Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.py
- Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.yml
- Packs/FortiAuthenticator/Integrations/FortiAuthenticator/README.md
- Packs/FortiAuthenticator/ReleaseNotes/1.0.1.md
- Packs/FortiAuthenticator/ReleaseNotes/1_0_1.md
- Packs/FortiAuthenticator/pack_metadata.json
fixes: https://github.com/demisto/content-docs/issues/743
> Update FortiAuthenticator with fixes and enhancements

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40654
> unskip LogRhythm REST test

- Packs/SophosCentral/README.md
- Packs/SophosCentral/ReleaseNotes/1_0_6.md
- Packs/SophosCentral/pack_metadata.json
> Added pack adoption notice.

- .github/CODEOWNERS
Removed myself as the owner of the Upload-Flow files.
> [Upload-Flow] Remove Ownership

- Packs/DevSecOps/Integrations/GitLab/GitLab.py
- Packs/DevSecOps/Integrations/GitLab/GitLab.yml
- Packs/DevSecOps/Integrations/GitLab/GitLab_test.py
- Packs/DevSecOps/Integrations/GitLab/README.md
- Packs/DevSecOps/Integrations/GitLab/command_examples
- Packs/DevSecOps/Integrations/GitLab/test_data/commands_test_data.json
- Packs/DevSecOps/ReleaseNotes/1_0_2.md
- Packs/DevSecOps/pack_metadata.json
https://github.com/demisto/etc/issues/40503
> ironbank enhancements to GitLab integration

- Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.py
- Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP_test.py
- Packs/FireEyeETP/ReleaseNotes/1_0_4.md
- Packs/FireEyeETP/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/40949
> Fireeye ETP - handle unicode chars

- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
- Packs/SentinelOne/ReleaseNotes/2_0_3.md
- Packs/SentinelOne/pack_metadata.json
1. Fixed argument issue in following commands:
- sentinelone-reactivate-site
- sentinelone-create-white-list-item
2. Updated docker image version
> SentinelOne V2 

- Utils/github_workflow_scripts/delete_stale_non_contrib_branches.py
example: https://github.com/demisto/content/runs/3427705209?check_suite_focus=true
There are branches in the repository that were created but commits were never pushed to them. In those cases, we currently try to create a PR but an error is returned with a message similar to `"No commits between master and 9.9.8"` (where `9.9.8` is the name of the branch in this particular example). In those cases, we should delete the branch without trying to create a PR from the stale branch. I added the aforementioned functionality.
Actions run where you can see we encountered this problem,
> Improve stale branch deletion script

- Packs/SophosCentral/ReleaseNotes/1_0_6.md
> Sophos Central - update RN

- Packs/CommonTypes/IndicatorFields/incidentfield-description.json
- Packs/CommonTypes/ReleaseNotes/3_1_13.md
- Packs/CommonTypes/pack_metadata.json
> Description Indicator Field - associated with missing types

- Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.py
- Packs/XForceExchange/Integrations/XFE_v2/XFE_v2.yml
- Packs/XForceExchange/Integrations/XFE_v2/XFE_v2_test.py
- Packs/XForceExchange/ReleaseNotes/1_1_7.md
- Packs/XForceExchange/pack_metadata.json
handle file res with `family` set to `None`
> XFE - handle file with no family

- Packs/CommonScripts/ReleaseNotes/1_4_31.md
- Packs/CommonScripts/Scripts/LoadJSON/LoadJSON.py
- Packs/CommonScripts/Scripts/LoadJSON/LoadJSON.yml
- Packs/CommonScripts/Scripts/LoadJSON/LoadJSON_test.py
- Packs/CommonScripts/Scripts/LoadJSON/Pipfile
- Packs/CommonScripts/Scripts/LoadJSON/Pipfile.lock
- Packs/CommonScripts/Scripts/LoadJSON/README.md
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/41012
> Loadjson strict

- Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.py
- Packs/FeedTorExitAddresses/Integrations/FeedTorExitAddresses/FeedTorExitAddresses.yml
- Packs/FeedTorExitAddresses/ReleaseNotes/1_0_4.json
- Packs/FeedTorExitAddresses/ReleaseNotes/1_0_4.md
- Packs/FeedTorExitAddresses/pack_metadata.json
https://github.com/demisto/etc/issues/40957
fixes: https://github.com/demisto/etc/issues/41036
Removing field name from fetching because it causes bugs in server.
- Further details: Mentioned in description.
> Tor Feed Delete Name Indicator Field

- Packs/DeveloperTools/TestPlaybooks/playbook-Fetch_Incidents_Test.yml
Little bug, in playbook inputs.
> fixed a litle bug in Fetch Incidents test playbook

- Packs/TrendMicroDDA/Integrations/integration-TrendMicroDDA.yml
- Packs/TrendMicroDDA/ReleaseNotes/1_0_3.md
- Packs/TrendMicroDDA/pack_metadata.json
> TrendMicro DDA - replace risklevel direct key access with get

- Packs/AttivoBotsink/README.md
- Packs/AttivoBotsink/ReleaseNotes/1_0_3.md
- Packs/AttivoBotsink/pack_metadata.json
> Attivo Pack adoption

- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
- Packs/QRadar/ReleaseNotes/2_0_23.md
- Packs/QRadar/pack_metadata.json
- Added more log messages
- Improved a case where integration context was re-saved even for cases where no offenses were fetched.
> QRadar v3 Add More Log Msgs

- Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.py
- Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed_test.py
- Packs/Sixgill-Darkfeed/ReleaseNotes/2_0_5.md
- Packs/Sixgill-Darkfeed/pack_metadata.json
demisto/etc#40957
Removing field name from fetching because it causes bugs in server. Adding its value to tags field.
- Further details: Mentioned in description.
> Sixgill name field Move To Tags

- Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Test is skipped until a fix will be made next week,
Made a corresponding ticket for it
https://github.com/demisto/etc/issues/41189
> SDKNightlyFailureSkipTest

- Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.py
- Packs/FeedUnit42/ReleaseNotes/1_1_3.md
- Packs/FeedUnit42/pack_metadata.json
N/A
Unable to connect Unit42 server via a web proxy.
> Fixed an issue where proxy settings haven't been given in BasicClient.

- Tests/Marketplace/marketplace_services.py
Remove un-needed log statement which causes much noise
> Remove Log Statement From BC Version

- Packs/SafeNet_Trusted_Access/.secrets-ignore
> SafeNet - add secret ignore

- Packs/Shodan/Integrations/Shodan_v2/README.md
fixed Outputs mismatch between yml and README
> updated Shodan v2 README

- Packs/Active_Directory_Query/Classifiers/classifier-User_Profile_-_Active_Directory_(Outgoing).json
- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
- Packs/Active_Directory_Query/ReleaseNotes/1_3_3.md
- Packs/Active_Directory_Query/pack_metadata.json
> Active Directory IAM fix

- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
- Packs/Active_Directory_Query/ReleaseNotes/1_3_4.md
- Packs/Active_Directory_Query/pack_metadata.json
> AD - iam-update-user fix

- Packs/CommonWidgets/Scripts/RSSWidget/README.md
The domain https://test-article.com is currently available for registration at $8.88/year.  An attacker could register this domain and host a malicious site at this url, which our docs would then be linking too.
...Back to palo sites instead just in case :)
> Update RSS Widget readme example links

- Tests/scripts/collect_tests_and_content_packs.py
- Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Ready
fixes: https://github.com/demisto/etc/issues/41198
> Increase Log Level Of Skipped Tests Via Pack Ignore

- Packs/EWS/TestPlaybooks/playbook-EWS_O365_test.yml
fixes: https://github.com/demisto/etc/issues/25605
Update some items that have been archived.
> [Test Fix] EWS O365

- Tests/conf.json
> Added memory_threshold to MITRE v2

- Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
- Packs/Intezer/ReleaseNotes/1_2_3.md
- Packs/Intezer/pack_metadata.json
Docker version bump with fixes in the intezer analyze sdk
> bump(docker): bump docker version

- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
- Packs/SafeNet_Trusted_Access/Layouts/layoutscontainer-SafeNet_Trusted_Access_-_Incident_Layout.json
- Packs/SafeNet_Trusted_Access/Playbooks/SafeNet_Trusted_Access_–_Add_to_Unusual_Activity_Group.yml
- Packs/SafeNet_Trusted_Access/ReleaseNotes/1_0_1.md
- Packs/SafeNet_Trusted_Access/pack_metadata.json
The pack allows Cortex XSOAR to interact with SafeNet Trusted Access(STA) and applies security remediation actions on SafeNet Trusted Access alerts through Cortex XSOAR Security Orchestration Playbooks.
**Flow**
1. Cortex XSOAR listen to SafeNet Trusted Access Alert using Mail Listerner.
2. Cortex XSOAR creates an incident and invokes a playbook that executes the security remediation steps.
3. Playbook adds the user to a group for a configured amount of time on which STA policies with stronger authentication requirements are imposed.
**Configuration steps at Cortex XSOAR**
1. Install and configure SafeNet Trusted Access integration instance.
2. Install and configure Mail listener integration instance.
3. Add XSOAR lists for group and time duration.
4. Create a pre-process rule. …
> Thales-SafeNet_Trusted_Access(STA)

- .github/CODEOWNERS
added @David-BMS as code owner of the `SetGridField` script
> Update SetGridField CODEOWNERS

- Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
- Packs/FeedMitreAttackv2/ReleaseNotes/1_0_6.md
- Packs/FeedMitreAttackv2/pack_metadata.json
Skipping auto update for this image as this causes bug in this integration
> Auto Update Docker False Mitre V2

- Packs/CommonScripts/ReleaseNotes/1_4_37.md
- Packs/CommonScripts/Scripts/IPv4Blacklist/IPv4Blacklist.yml
- Packs/CommonScripts/Scripts/IPv4Whitelist/IPv4Whitelist.yml
- Packs/CommonScripts/Scripts/IsInCidrRanges/IsInCidrRanges.yml
- Packs/CommonScripts/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.yml
- Packs/CommonScripts/pack_metadata.json
- Packs/DeveloperTools/ReleaseNotes/1_2_3.md
- Packs/DeveloperTools/Scripts/CompareIndicators/CompareIndicators.yml
- Packs/DeveloperTools/pack_metadata.json
> Docker update netutils

- Packs/IntSight/Integrations/IntSight/IntSight_test.py
possible fix to the instability unit test failures from IntSight
> IntSightUnitTestsFix

- Packs/CommonDashboards/Dashboards/dashboard-CostOptimizationInstances.json
- Packs/CommonDashboards/ReleaseNotes/1_1_1.md
- Packs/CommonDashboards/pack_metadata.json
- Packs/CommonWidgets/ReleaseNotes/1_1_4.md
- Packs/CommonWidgets/Widgets/widget-CommandExecutionType.json
- Packs/CommonWidgets/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/41132
Changed the values format from percentage to regular.
> Change widget command execution type

- Packs/HealthCheck/ReleaseNotes/1_0_3.md
- Packs/HealthCheck/Scripts/HealthCheckAnalyzeLargeInvestigations/HealthCheckAnalyzeLargeInvestigations.yml
- Packs/HealthCheck/Scripts/HealthCheckCPU/HealthCheckCPU.yml
- Packs/HealthCheck/Scripts/HealthCheckCommonIndicators/HealthCheckCommonIndicators.yml
- Packs/HealthCheck/Scripts/HealthCheckContainersStatus/HealthCheckContainersStatus.yml
- Packs/HealthCheck/Scripts/HealthCheckDiskUsage/HealthCheckDiskUsage.yml
- Packs/HealthCheck/Scripts/HealthCheckDiskUsageLine/HealthCheckDiskUsageLine.yml
- Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml
- Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.yml
- Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml
- Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedDaily/HealthCheckIncidentsCreatedDaily.yml
- Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedMonthly/HealthCheckIncidentsCreatedMonthly.yml
- Packs/HealthCheck/Scripts/HealthCheckIncidentsCreatedWeekly/HealthCheckIncidentsCreatedWeekly.yml
- Packs/HealthCheck/Scripts/HealthCheckInstalledPacks/HealthCheckInstalledPacks.yml
- Packs/HealthCheck/Scripts/HealthCheckIntegrations/HealthCheckIntegrations.yml
- Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml
- Packs/HealthCheck/Scripts/HealthCheckMemory/HealthCheckMemory.yml
- Packs/HealthCheck/Scripts/HealthCheckNumberOfDroppedIncidents/HealthCheckNumberOfDroppedIncidents.yml
- Packs/HealthCheck/Scripts/HealthCheckNumberOfEngines/HealthCheckNumberOfEngines.yml
- Packs/HealthCheck/Scripts/HealthCheckOutdatedPacks/HealthCheckOutdatedPacks.yml
- Packs/HealthCheck/Scripts/HealthCheckPacksInstalled/HealthCheckPacksInstalled.yml
- Packs/HealthCheck/Scripts/HealthCheckPlaybookAnalysis/HealthCheckPlaybookAnalysis.yml
- Packs/HealthCheck/Scripts/HealthCheckReadConf/HealthCheckReadConf.yml
- Packs/HealthCheck/Scripts/HealthCheckReadTemeletryLog/HealthCheckReadTemeletryLog.yml
- Packs/HealthCheck/Scripts/HealthCheckReadVC/HealthCheckReadVC.yml
- Packs/HealthCheck/Scripts/HealthCheckServerConfiguration/HealthCheckServerConfiguration.yml
- Packs/HealthCheck/Scripts/HealthCheckServerLog/HealthCheckServerLog.yml
- Packs/HealthCheck/Scripts/HealthCheckUnpack/HealthCheckUnpack.yml
- Packs/HealthCheck/Scripts/HealthCheckWorkers/HealthCheckWorkers.yml
- Packs/HealthCheck/pack_metadata.json
> Python3 HealthCheck

- Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param1.json
- Packs/DeveloperTools/IndicatorFields/indicatorfield-DeveloperTools_Param2.json
- Packs/DeveloperTools/ReleaseNotes/1_2_6.md
- Packs/DeveloperTools/pack_metadata.json
related to: https://github.com/demisto/content/pull/14141
fixed indicator fields IDs
> DeveloperTools - fixed indicator fields IDs

- Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
> Fix RM 108 Broken Image In README

- Packs/BruteForce/.pack-ignore
- Packs/CommonPlaybooks/.pack-ignore
- Packs/Malware/.pack-ignore
- Packs/Phishing/.pack-ignore
- Packs/SANS/.secrets-ignore
This PR should be reverted after this dev-bug will be solved https://github.com/demisto/etc/issues/41538
> ignore PB110 on some playbooks

- .gitlab/ci/bucket-upload.yml
> update the allowed upload user list

- Packs/SafeNet_Trusted_Access/.secrets-ignore
- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess.py
- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_description.md
- Packs/SafeNet_Trusted_Access/README.md
- Packs/SafeNet_Trusted_Access/ReleaseNotes/1_0_2.md
- Packs/SafeNet_Trusted_Access/pack_metadata.json
The pack allows Cortex XSOAR to interact with SafeNet Trusted Access(STA) and applies security remediation actions on SafeNet Trusted Access alerts through Cortex XSOAR Security Orchestration Playbooks.
**Flow**
1. Cortex XSOAR listen to SafeNet Trusted Access Alert using Mail Listerner.
2. Cortex XSOAR creates an incident and invokes a playbook that executes the security remediation steps.
3. Playbook adds the user to a group for a configured amount of time on which STA policies with stronger authentication requirements are imposed.
fixes: Updated Guide Link.
Updated configuration guide staging link to production link.
> Updated guide link. Created new branch.

- .circleci/content_release_vars.sh
> bump version to 21.9.1

- Packs/GuardiCore/.pack-ignore
- Packs/SANS/.pack-ignore
fixes: master
PB110 - related to https://github.com/demisto/etc/issues/41538
RM104 - as a result of https://github.com/demisto/content/commit/0070d9b3bfb6a7747d8c0107d8ba9ccae13d91e7.
> updated pack-ignore files

- Packs/CortexXDR/README.md
Update XDR readme with link to XDR page to improve XDR Search engine optimization
> Update XDR readme with link

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/30930
> threat vault unskip

- Tests/conf.json
related: https://github.com/demisto/etc/issues/27846, https://github.com/demisto/etc/issues/32322
> Un skip Carbon Black Enterprise Protection V2 Test

- Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
- Packs/Malwarebytes/ReleaseNotes/1_1_3.md
- Packs/Malwarebytes/pack_metadata.json
> [malwarebytes-254] fixes for !malwarebytes-list-endpoint-info command

- Tests/scripts/collect_tests_and_content_packs.py
fixes: https://app.circleci.com/pipelines/github/demisto/content/119467/workflows/075c48b1-c281-43b2-a207-83182ba14e49/jobs/432117/parallel-runs/0/steps/0-114
added missing import
> collect_tests: added missing import

- Packs/Flashpoint/Integrations/Flashpoint/Flashpoint_test.py
- Packs/Flashpoint/ReleaseNotes/1_2_1.md
- Packs/Flashpoint/pack_metadata.json
Fix the UT that fails on SDK due to time issues.
> Flashpoint - fix UT

- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
#
Fix something should be part of the https://github.com/demisto/content/pull/14506
> remove confusing command param from AzureSentinel

- Tests/scripts/collect_tests_and_content_packs.py
> add import

- Packs/Infocyte/Integrations/Infocyte/Infocyte.Tests.ps1
- Packs/Infocyte/Integrations/Infocyte/Infocyte.ps1
- Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
- Packs/Infocyte/ReleaseNotes/1_0_4.md
- Packs/Infocyte/pack_metadata.json
Fixing the cause of the `Pwsh analyze` lint error which is failing our builds:
https://code.pan.run/xsoar/content/-/pipelines/1745216
https://code.pan.run/xsoar/content/-/pipelines/1741934
> Infocye lint fix

- Tests/scripts/collect_tests_and_content_packs.py
- dev-requirements-py3.txt
> change sdk to release

- Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
- Packs/Phishing/ReleaseNotes/2_4_4.md
- Packs/Phishing/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/41811
Fixing a typo in task 16 on **Phishing Investigation -Generic v2** playbook
> Reporter address typo

- Packs/Kenna/Integrations/KennaV2/KennaV2.py
- Packs/Kenna/ReleaseNotes/1_1_5.md
- Packs/Kenna/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/37009
fixed proxy parameter handling so it will be able to enable it.
will add separate PRs to the occurrences. 
> Fix kenna proxy

- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/ReleaseNotes/2_0_28.md
- Packs/QRadar/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/41840
> QRadar Bug Due To Failed Casting To Number

- Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
- Packs/GoogleVault/ReleaseNotes/1_0_5.md
- Packs/GoogleVault/pack_metadata.json
- Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
- Packs/IBMResilientSystems/ReleaseNotes/1_0_8.md
- Packs/IBMResilientSystems/pack_metadata.json
Note: validate will fail on this change so it will require force-push.
> fixed subtypes according to docker images

- Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
- [x ] Ready
https://github.com/demisto/etc/issues/41377
Added Mail.Send to the list of permissions.
> Added Missing Permission

- Packs/CommonScripts/ReleaseNotes/1_4_42.md
- Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.py
- Packs/CommonScripts/Scripts/JsonToTable/JsonToTable.yml
- Packs/CommonScripts/pack_metadata.json
added the `headers` argument to JsonToTable transformer.
> JsonToTable: added the headers argument

- Packs/SecurityAdvisor/README.md
> Update SecurityAdvisor README.md

- Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
- Packs/SentinelOne/ReleaseNotes/2_0_5.md
- Packs/SentinelOne/pack_metadata.json
This PR aims to add support for filtering by Site ID to the existing get-sentinelone-threats command as well as the fetch command for the SentinelOne integration.
> Add support for Sites to SentinelOne threat commands

- Packs/ThreatIntel/GenericDefinitions/genericdefinition-ThreatIntelReport.json
- Packs/ThreatIntel/ReleaseNotes/1_0_5.md
- Packs/ThreatIntel/pack_metadata.json
> Threat Intel Report - add RBAC support

- Packs/Devo/Integrations/Devo/Devo.yml
- Packs/Devo/Integrations/Devo/README.md
- Packs/Devo/ReleaseNotes/1_1_6.md
- Packs/Devo/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40997
Changes made in order to deprecate Devo due to v2.
> deprecate Devo integration

- .circleci/content_release_vars.sh
> bump version to 21.10.0

- Packs/PAN-OS/Integrations/Panorama/Panorama.yml
- Packs/PAN-OS/Integrations/Panorama/README.md
- Packs/PAN-OS/ReleaseNotes/1_7_2.md
- Packs/PAN-OS/pack_metadata.json
relates to: https://github.com/demisto/etc/issues/41980
> PAN-OS - Documentation and metadata improvements around push

- Packs/Axonius/Integrations/Axonius/Axonius.py
- Packs/Axonius/Integrations/Axonius/Axonius.yml
- Packs/Axonius/Integrations/Axonius/README.md
- Packs/Axonius/ReleaseNotes/1_0_4.md
- Packs/Axonius/pack_metadata.json
- [X ] Ready
Expanding functionality to allow searching via regex where possible.
- [ X] No
> Axonius regex hostname action

- Packs/Claroty/.secrets-ignore
- Packs/Claroty/README.md
Please contact james.s@claroty.com with any questions or concerns.
> Claroty Readme Update

- Packs/EmailCommunication/README.md
Added a link to the pack article in the pack readme.
> Updated Email Communication readme with pack article

- Packs/CommonScripts/ReleaseNotes/1_4_47.md
- Packs/CommonScripts/Scripts/GetEnabledInstances/GetEnabledInstances.py
- Packs/CommonScripts/Scripts/GetEnabledInstances/GetEnabledInstances.yml
- Packs/CommonScripts/Scripts/GetEnabledInstances/GetEnabledInstances_test.py
- Packs/CommonScripts/Scripts/GetEnabledInstances/README.md
- Packs/CommonScripts/pack_metadata.json
> added GetEnabledInstances script

- Packs/CommonScripts/ReleaseNotes/1_4_48.md
- Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.py
- Packs/CommonScripts/Scripts/UnzipFile/UnzipFile.yml
- Packs/CommonScripts/pack_metadata.json
Password syntax for the unrar command requires no space between the `-p` flag and the actual password.
> Unzip password protected rar files would timeout.

- Tests/demistomock/demistomock.py
> Fix mapObject demistomock

- Tests/Marketplace/core_packs_list.json
fixes: https://github.com/demisto/etc/issues/42508
> Threat Intel Report Core Pack

- Packs/PrismaSaasSecurity/Integrations/SaasSecurity/README.md
- Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.yml
- Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity_description.md
- Packs/PrismaSaasSecurity/ReleaseNotes/1_1_1.md
- Packs/PrismaSaasSecurity/pack_metadata.json
Improve SaaS Security mirroring docs
> Improve SaaS Security mirroring docs

- Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse.py
- Packs/BitcoinAbuse/ReleaseNotes/1_0_13.md
- Packs/BitcoinAbuse/pack_metadata.json
https://github.com/demisto/content/pull/14460
BitcoinAbuse failed to fetch indicators when using the latest version of `CSVFeedApiModule` script with noUpdate flag because the method `fetch_indicators_command` is now returns Tuple.
The issue solved by update the integration code to use the value of no_update flag from the method.
> BitcoinAbuse - fix indicators creation

- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/ReleaseNotes/2_1_5.md
- Packs/QRadar/pack_metadata.json
Added a safety check for OR incase the ctx had None value
> QRadar Maintenance Enhancement

- Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.py
- Packs/CrowdStrikeMalquery/ReleaseNotes/1_0_8.md
- Packs/CrowdStrikeMalquery/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/42143
Changed test to include actual access the API
> changed test to include actual access to api.

- Tests/Marketplace/core_packs_list.json
https://github.com/demisto/etc/issues/42508#issuecomment-958796503
> Remove TIR from core packs

- .gitlab/ci/global.yml
removed coverage enforcement from all scheduled pipelines.
> fix coverage anforcment failure on sdk nightly

- Packs/SplunkPy/ReleaseNotes/2_2_2.md
- Packs/SplunkPy/ReleaseNotes/2_3_0.md
- Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.py
- Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.yml
- Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.py
- Packs/SplunkPy/Scripts/SplunkShowDrilldown/SplunkShowDrilldown.yml
- Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.py
- Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.yml
- Packs/SplunkPy/TestPlaybooks/playbook-SplunkShowEnrichment.yml
- Packs/SplunkPy/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/41255
Improve splunk scripts  that are used to display data derived from the enrichments:
visualisation and errors for status in case no results are returned .
> improve visualisation in case no results are returned in splunk show enrichment scripts

- Packs/Anomali_ThreatStream/Integrations/integration-AnomaliThreatStream_README.md
fixes: https://github.com/demisto/content-docs/issues/842
Fix typo in Anomli readme
> fix typo in Anomali

- .circleci/config.yml
Related: https://github.com/demisto/etc/issues/40928
No need to authenticate to GCS Marketplace
> Don't authenticate to GCS Market

- Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
> update timeout for secrets run

- Tests/conf.json
fixes: build
both integrations should be deprecated soon and tests will be removed once again.
> Re-add Anomali old test playbooks

- Packs/Zscaler/Integrations/Zscaler/README.md
- Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
- Packs/Zscaler/ReleaseNotes/1_1_12.md
- Packs/Zscaler/pack_metadata.json
Changed the parameter ***Credentials*** to ***Username*** to better reflect its purpose.
> [Zscaler] Changed Credentials to Username

- .gitlab/ci/global.yml
restrict coverage stats upload to master nightly only.
> restrict coverage stats upload to master nightly only

- Tests/conf.json
> added timeout

- Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Fix Microsoft ATP test playbook
> Fix Microsoft ATP test playbook

- Packs/FeedTAXII/.pack-ignore
- Packs/Palo_Alto_Networks_WildFire/.pack-ignore
- Packs/SalesforceFusion/.pack-ignore
- Tests/configure_and_test_integration_instances.py
https://github.com/demisto/demisto-sdk/pull/1680
Add some packs to ignore error IN145
> add packs to ignore

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/37021
fixes: https://github.com/demisto/etc/issues/37023
fixes: https://github.com/demisto/etc/issues/37024
Replaced instance with a new working instance.
> Fixing test failures for PAN-OS playbooks

- Packs/HelloWorld/IncidentFields/incidentfield-Hello_World_ID.json
- Packs/HelloWorld/ReleaseNotes/1_2_9.md
- Packs/HelloWorld/pack_metadata.json
Changed the unsearchable field to true.
> Unsearchable field hello world

- Packs/CaseManagement-Generic/README.md
> Case MGMT - rm fin from readme

- .circleci/config.yml
- .gitlab/ci/global.yml
- .hooks/pre-commit
- Utils/upload_code_coverage_report.py
replaced the dir for the bucket from `code-coverage` to `code-coverage-reports`
> fix coverage url

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/37022
> remove centreon from skipped

- Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml
- Packs/FeedMitreAttack/Integrations/FeedMitreAttack/README.md
- Packs/FeedMitreAttack/ReleaseNotes/1_2_0.md
- Packs/FeedMitreAttack/pack_metadata.json
- Packs/FeedUnit42/Integrations/FeedUnit42/FeedUnit42.yml
- Packs/FeedUnit42/Integrations/FeedUnit42/README.md
- Packs/FeedUnit42/ReleaseNotes/1_2_0.md
- Packs/FeedUnit42/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/43582)
Deprecate MITRE ATT&CK Feed + Unit42 Feed
> [Deprecate] MITRE ATT&CK Feed + Unit42 Feed

- dev-requirements-py3.txt
> add egg to requirements-py3 for demisto-sdk

- Packs/Base/ReleaseNotes/1_15_1.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
fix lit to make marketplace upload run.
introduced here: https://github.com/demisto/content/pull/15646
> fix lint common server python

- Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md
fixes: https://github.com/demisto/content-docs/issues/856
> remove clickable links from threat vault README

- Packs/Jira/Integrations/JiraV2/README.md
fixes: https://github.com/demisto/content-docs/issues/841
make it clear that the username param is relevant also to the API key flow.
> enhance username param description

- Packs/FeedMISP/Integrations/FeedMISP/FeedMISP.py
- Packs/FeedMISP/Integrations/FeedMISP/FeedMISP_description.md
- Packs/FeedMISP/ReleaseNotes/1_0_1.md
- Packs/FeedMISP/pack_metadata.json
When getting the base url parameter from the user a \ will be added if necessary.
> Added / to base url if necessary

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/17471#issuecomment-968255706
> unskip redcanary

- Packs/UrlScan/Integrations/UrlScan/README.md
- Packs/UrlScan/Integrations/UrlScan/UrlScan.py
- Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
- Packs/UrlScan/ReleaseNotes/1_1_13.md
- Packs/UrlScan/pack_metadata.json
Added support for setting custom User Agent for whole integration (defined by API key) and for single requests.
> support for setting custom User Agent added

- Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_File_Indicators_With_File_Hash_Type.yml
- Packs/TIM_Processing/ReleaseNotes/1_1_9.md
- Packs/TIM_Processing/pack_metadata.json
fixes:https://github.com/demisto/etc/issues/43335
> Tim file processing fix

- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault_description.md
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
- Packs/HashiCorp-Vault/ReleaseNotes/1_0_3.md
- Packs/HashiCorp-Vault/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43496
> HashiCorp Vault - AppRole auth method

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/26464
Removed AutoFocus v2 from skipped.
> [Test Fix] AutoFocus V2

- Packs/Symantec_Advanced_Threat_Protection/README.md
fixes:https://github.com/demisto/etc/issues/43455
> add README to symantec advanced threat protection

- Packs/Lacework/Classifiers/classifier-Lacework_5_9_9.json
- Packs/Lacework/Classifiers/classifier-mapper-incoming-Lacework.json
- Packs/Lacework/Integrations/Lacework/Lacework.py
- Packs/Lacework/ReleaseNotes/1_1_1.md
- Packs/Lacework/pack_metadata.json
This PR fixes the severity mapping between Lacework and XSOAR.
> fix: transformed severity to match XSOAR

- Packs/Jira/ReleaseNotes/1_4_1.md
> fix rn in jira

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33216
Remove FireEye NX from skipped test.
> [Test Fail] Unskip FireEye NX Test

- Packs/LogRhythmRest/.pack-ignore
> LogRhythm REST: Update .pack-ignore

- Packs/MalwareBazaar/Integrations/MalwareBazaar/MalwareBazaar.yml
- Packs/MalwareBazaar/Integrations/MalwareBazaar/README.md
- Packs/MalwareBazaar/ReleaseNotes/1_0_1.md
- Packs/MalwareBazaar/pack_metadata.json
A bug was found in the yml file. It was fixed
> MalwareBazaar yml bug fix

- Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_1_2.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/43957)
Fixed command "!CreateNewIndicator" and added indicator type (IP).
This change helps enrichIndicators to better define the indicator to be enriched.
> Fixed command "!CreateNewIndicator" and added indicator type (IP) - For "Block IP - Generic V3"

- .gitlab/ci/on-push.yml
6.0 is EOL, no need to test it anymore.
> removed Server 6.0 from build

- Packs/DemistoRESTAPI/Integrations/integration-DemistoRESTAPI.yml
- Packs/DemistoRESTAPI/ReleaseNotes/1_2_1.md
- Packs/DemistoRESTAPI/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43665
HttpMultipart function expects the `fields` parameter (multi-form body fields) to be an object.
> fixed Demisto REST Api multipart command

- Packs/CommonScripts/ReleaseNotes/1_5_9.md
- Packs/CommonScripts/Scripts/DT/DT.py
- Packs/CommonScripts/Scripts/DT/DT.yml
- Packs/CommonScripts/Scripts/script-FailedInstances.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43128
fixed the structure of the FailedInstances script.
moved the DT transformer to python3
copied the release notes from older files - adding `docs-approved`.
> FailedInstances/DT: small fixes

- Packs/SecureWorks/README.md
This is a minor update to the pack README file to provide a bit more information about SecureWorks and what the pack includes, per request
> SecureWorks README update

- Packs/Censys/Integrations/Censys/Censys.py
- Packs/Censys/Integrations/Censys/Censys.yml
- Packs/Censys/ReleaseNotes/1_1_1.md
- Packs/Censys/pack_metadata.json
- Fix an issue where *page* argument was incompatible 
> Censys arg fix

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/43923
Skipped recorded future feed test because of quota issues. will be unskipped at the beginning of December.
> Skipped recorded future feed test because of quota issues

- Packs/OTRS/Integrations/OTRS/README.md
fixes: https://github.com/demisto/content-docs/issues/849
Added the note that the name of the template .yml file is crucial for its use.
> Update ORTS Readme

- .gitlab/ci/global.yml
related: [link to the issue](https://github.com/demisto/etc/issues/22899)
added coverage visualization based on GitLab.
> added coverage report to gitlab

- Tests/Marketplace/core_packs_list.json
fixes: https://github.com/demisto/etc/issues/44135
> Unit 42 Intel - set to core pack

- Tests/conf.json
relates: https://github.com/demisto/etc/issues/26741
Skipped recorded future test because of quota issues. will be unskipped at the beginning of December.
> Skipped RF duw to quota issues

- Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md
fixes: https://github.com/demisto/etc/issues/33382
> MS MGMT Activity - add note about fetch types

- Packs/Ransomware/Playbooks/playbook-Post_Intrusion_Ransomware_Investigation.yml
- Packs/Ransomware/ReleaseNotes/1_0_8.md
- Packs/Ransomware/pack_metadata.json
fixes: [#44018](https://github.com/demisto/etc/issues/44018)
Renamed 2 task's name(Task's number: 107&108)
**From:** _file_enrichment_-_file_reputation_
**To**: _File Enrichment - File reputation_
> Sub playbook rename file enrichment

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/ReleaseNotes/2_2_6.md
- Packs/SplunkPy/pack_metadata.json
- Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.py
- Packs/SplunkPyPreRelease/ReleaseNotes/1_0_4.md
- Packs/SplunkPyPreRelease/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/35550
- added the autologin argument.
- replace the \` with \\\` in the *splunk-search* command outputs.
> splunk add auto login and improve *splunk-search* command outputs

- Tests/conf.json
> skipped autofocus tags feed test

- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
- Packs/AzureSentinel/Integrations/AzureSentinel/README.md
- Packs/AzureSentinel/ReleaseNotes/1_2_3.md
- Packs/AzureSentinel/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44026
Added the `IncidentUrl` output to the `azure-sentinel-get-incident-by-id` command.
> Azure sentinel incident url

- Packs/SymantecDLP/Integrations/SymantecDLP/README.md
Added troubleshooting for cases when both Kerberos and Form type authentications are enabled.
fixes https://github.com/demisto/etc/issues/42300
> Symantec DLP - troubleshooting kerberos/form auth

- Packs/FeedCofense/IndicatorFields/incidentfield-Cofense-Threat-ID.json
> fixed feed Cofense indicator field type

- Packs/Forescout/Integrations/Forescout/Forescout.py
- Packs/Forescout/Integrations/Forescout/Forescout.yml
- Packs/Forescout/Integrations/Forescout/README.md
- Packs/Forescout/ReleaseNotes/1_0_6.md
- Packs/Forescout/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43556
added the *HTTP Timeout* parameter.
copied RN and description from a similar PR - setting *docs-approved*.
> Forescout: fixed an issue where the integration failed on an HTTP timeout.

- Packs/Base/ReleaseNotes/1_16_3.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
update sane report at base pack
> update sane report docker image

- .gitlab/ci/bucket-upload.yml
removed packs installation on server 6.0 in the upload CI flow.
> removed server 6.0 from the upload flow

- Tests/conf.json
> skip autofocus in nightly

- Packs/DeepInstinct/pack_metadata.json
> Removed user that does not exist

- Packs/ScheduleTaskAndPoll/.pack-ignore
ignore PA129 to fix upload flow
not sure why it failed the build - will check on Sunday.
> ScheduleTaskAndPoll: Update .pack-ignore

- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_2.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
added the agent parameter to the HTTP request
> WildFire Reports: added the agent parameter to the HTTP request

- Packs/ExtFilter/ReleaseNotes/1_1_8.md
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter_test.py
- Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json
- Packs/ExtFilter/pack_metadata.json
N/A
Fixed an issue where it parses DT syntax.
> Fixed an issue where it parses DT syntax.

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40157
> Zscaler Test - skip tpb

- Packs/MapPattern/ReleaseNotes/1_0_4.md
- Packs/MapPattern/Scripts/MapPattern/MapPattern.py
- Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
- Packs/MapPattern/Scripts/MapPattern/MapPattern_test.py
- Packs/MapPattern/Scripts/MapPattern/README.md
- Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
- Packs/MapPattern/pack_metadata.json
N/A
Thee feature has been added this Sunday, but changed it because of the specification mistake.
`comparison_fields` doesn't work any more. But the same mapping can be used for the fields comparison mode.
It will work with simply setting `true` to the new `compare_fields` argument.
> Changed the fields comparison feature.

- Utils/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
fixes: [link to the issue](https://github.com/demisto/etc/issues/44539)
removed the `.` in the URL investigation.
> secrets detection - minor fix to url in gold

- Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md
fixes: https://github.com/demisto/etc/issues/42638
Make the configuration process clear for external gmail addresses
> Update GmailSingleUser README.md

- Tests/demistomock/demistomock.py
updated the `get` function in the demisto_mock to include the defaultParam.
related build: https://circleci.com/gh/demisto/content/454203?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> updated the demistomock module

- Packs/TaniumThreatResponse/TestPlaybooks/playbook-Tanium_Threat_Response_V2_Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/44201
> Fix test playbook- Tanium TR v2 

- .github/CODEOWNERS
> parseEmailFiles_ownership

- Packs/HPE_Service_Manager/Integrations/README.md
fixes: https://github.com/demisto/content-docs/issues/876
Added documentation to Micro Focus Service Manager
> Micro Focus Service Manager - Added documentation

- Packs/Campaign/.pack-ignore
> add ignore of dbotRole in SetCampaignDetails

- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
- Packs/HashiCorp-Vault/ReleaseNotes/1_0_6.md
- Packs/HashiCorp-Vault/pack_metadata.json
> HashiCorp Vault - add the folder arg to the configure-engine cmd

- Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
- Packs/Tanium/Integrations/Tanium_v2/Tanium_v2_test.py
- Packs/Tanium/ReleaseNotes/1_0_13.md
- Packs/Tanium/pack_metadata.json
- Packs/TaniumThreatResponse/Integrations/TaniumThreatResponse/TaniumThreatResponse.py
- Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py
- Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2_test.py
- Packs/TaniumThreatResponse/ReleaseNotes/2_0_5.md
- Packs/TaniumThreatResponse/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44680
> Tanium - change http method to post on login

- Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
- Packs/FeedAzure/ReleaseNotes/1_0_11.md
- Packs/FeedAzure/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/44604)
Update services list options to fetch in Azure feed.
> Update services list options in Azure feed

- Packs/CommonScripts/ReleaseNotes/1_6_8.md
- Packs/CommonScripts/Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines.py
- Packs/CommonScripts/Scripts/PositiveDetectionsVSDetectionEngines/PositiveDetectionsVSDetectionEngines.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43995
fixed an issue where the script caused some console errors due to bad conversion.
> PositiveDetectionsVSDetectionEngines: Fix console issue

- Packs/CommonWidgets/ReleaseNotes/1_2_4.md
- Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.py
- Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
- Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget_test.py
- Packs/CommonWidgets/Scripts/RSSWidget/test_data/test_variables.py
- Packs/CommonWidgets/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44739
fixed the order of the feed entries to descending.
> RSSWidget: fix entries order

- Packs/CVE_2021_40444/pack_metadata.json
- Packs/CVE_2021_44228/pack_metadata.json
- Packs/MajorBreachesInvestigationandResponse/pack_metadata.json
- Tests/Marketplace/approved_usecases.json
- Tests/Marketplace/landingPage_sections.json
Added the "Rapid Breach Response" as a use case for marketplace, so customers can easily search for the relevant content.
> Added "Rapid Breach Response" as a use case for marketplace

- .github/CODEOWNERS
Added a code owner to XSOAR CI/CD Pack.
> CI/CD Pack Code Owner

- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_description.md
- Packs/CortexDataLake/ReleaseNotes/1_3_5.md
- Packs/CortexDataLake/pack_metadata.json
Improved CDL integration configuration instructions
Fixes: https://github.com/demisto/etc/issues/44787
Fixes: https://github.com/demisto/content-docs/issues/885
> Improve integration configuration instructions

- .circleci/config.yml
- Packs/Base/ReleaseNotes/1_17_2.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
- Packs/ProofpointServerProtection/.pack-ignore
- Packs/TIM_Processing/.pack-ignore
fixes: master build
* Fixed Mypy error in CommonServerPython
* Added validation errors to ignore as a workaround for SDK regression issues.
> Fix CommonServerPython Mypy errors

- Packs/Base/ReleaseNotes/1_17_3.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/ReleaseNotes/2_1_22.md
- Packs/QRadar/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44894
There's no `signal` in Windows OS.
> Use signal profiling dump only on non-Windows OS

- Packs/CommonScripts/.pack-ignore
- Tests/Marketplace/marketplace_services.py
related: https://github.com/demisto/etc/issues/44255
add item IDs to metadata files in the index.zip
@ytauman FYI
> upload flow: add item IDs to metadata files in the index.zip

- Packs/Devo/README.md
- Packs/Devo/ReleaseNotes/1_1_7.md
- Packs/Devo/pack_metadata.json
fixes: None
Finishing adopt-a-pack process. Updated the following, changelog, metadata json, readme with required text.
None
> Adopt Process For Devo

- Packs/ExtFilter/ReleaseNotes/1_1_9.md
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter_test.py
- Packs/ExtFilter/pack_metadata.json
- Fixed the test script where it didn't cover the entire test cases.
N/A
- Fixed an issue where it didn't parse DT syntax correctly.
- Fixed the test script where it didn't cover the entire test cases.
> - Fixed an issue where it didn't parse DT syntax correctly.

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/40654
> LogRhythmRest - unskip test

- Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/27164
Updates the condition when verify `lr-get-alarm-events-by-id` outputs
> fix lr test playbook

- .gitlab/ci/on-push.yml
- Utils/gitlab_triggers/trigger_build_with_ttl.sh
fixes: https://github.com/demisto/etc/issues/38241
Added the option to trigger a build with time to live in Gitlab.
> added trigger_build_with_ttl.sh to gitlab triggers

- Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
- Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
- Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/README.md
- Packs/ProofpointThreatResponse/ReleaseNotes/1_0_11.md
- Packs/ProofpointThreatResponse/pack_metadata.json
Add command to close PP Trap incidents
> Add Proofpoint TRAP Closure command

- Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_3_5.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
> MicrosoftDefenderForEndpoint - Set enc_key to support creds

- Packs/RemoveEmpty/ReleaseNotes/1_0_1.md
- Packs/RemoveEmpty/Scripts/RemoveEmpty/README.md
- Packs/RemoveEmpty/Scripts/RemoveEmpty/RemoveEmpty.js
- Packs/RemoveEmpty/Scripts/RemoveEmpty/RemoveEmpty.yml
- Packs/RemoveEmpty/pack_metadata.json
- Added a feature to remove keys whose values are empty from dictionaries.
- Added a feature to remove particular itema (such as 'None') as empty values.
N/A
- Fixed an issue where integer 0 was considered as an empty value.
- Added a feature to remove keys whose values are empty from dictionaries. 
- Added a feature to remove particular items (such as 'None') as empty values.
> - Fixed an issue where integer 0 was considered as an empty value.

- Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
- Packs/CovalenceForSecurityProviders/README.md
- Packs/CovalenceForSecurityProviders/ReleaseNotes/1_1_0.md
- Packs/CovalenceForSecurityProviders/pack_metadata.json
- Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.py
- Packs/CovalenceManagedSecurity/Integrations/CovalenceManagedSecurity/CovalenceManagedSecurity.yml
- Packs/CovalenceManagedSecurity/README.md
- Packs/CovalenceManagedSecurity/ReleaseNotes/1_1_0.md
- Packs/CovalenceManagedSecurity/pack_metadata.json
No issues
- Removed beta flag
- Displaying additional details when fetching incidents
> Fe covalence beta flag removed

- Packs/PrismaAccess/.pack-ignore
- Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.py
- Packs/PrismaAccess/Integrations/PrismaAccessEgressIPFeed/PrismaAccessEgressIPFeed.yml
- Packs/PrismaAccess/ReleaseNotes/1_0_10.md
- Packs/PrismaAccess/pack_metadata.json
> Prisma access egres creds

- Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStream/AnomaliThreatStream.yml
- Packs/Anomali_ThreatStream/ReleaseNotes/2_0_3.md
- Packs/Anomali_ThreatStream/pack_metadata.json
> Deprecate anomali threat stream

- Packs/Infoblox/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45004
Updated pack name according to the request in the issue
> Infoblox - Updated pack name

- Packs/ServiceNow/Integrations/ServiceNowv2/Pipfile
- Packs/ServiceNow/Integrations/ServiceNowv2/Pipfile.lock
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
- Packs/ServiceNow/ReleaseNotes/2_2_18.md
- Packs/ServiceNow/pack_metadata.json
fixed: https://github.com/demisto/etc/issues/44860
> Send the requested fields as param in the request

- Packs/CommonScripts/Scripts/SetGridField/README.md
Add a Troubleshooting section to address the "The following grid id was not found" error, which seems to be a common source of confusion.
N/A
Add a Troubleshooting section to address the "The following grid id was not found" error, which seems to be a common source of confusion.
(See changed file) 
> Add Troubleshooting section

- Packs/DomainTools/pack_metadata.json
- Packs/DomainTools_Iris/pack_metadata.json
N/A
Update DomainTools packs to help customers differentiate between the two on the marketplace.
N/A
> Rename the two DomainTools packs

- Packs/ParseHTMLTables/ReleaseNotes/1_0_1.md
- Packs/ParseHTMLTables/Scripts/ParseHTMLTables/ParseHTMLTables.py
- Packs/ParseHTMLTables/Scripts/ParseHTMLTables/ParseHTMLTables.yml
- Packs/ParseHTMLTables/Scripts/ParseHTMLTables/ParseHTMLTables_test.py
- Packs/ParseHTMLTables/pack_metadata.json
N/A
Improved to parse HTML tables which have rowspan and colspan attributes.
> Improved to parse tables which have rowspan and colspan attributes.

- Packs/PrismaCloud/Integrations/RedLock/RedLock.yml
- Packs/PrismaCloud/ReleaseNotes/2_0_6.md
- Packs/PrismaCloud/pack_metadata.json
https://github.com/demisto/etc/issues/45005
Update the description of `redlock-get-rql-respons` command
> Update command description in RedLock

- Packs/DomainTools/.pack-ignore
- Packs/DomainTools/Integrations/DomainTools/DomainTools.js
- Packs/DomainTools/Integrations/DomainTools/DomainTools.yml
- Packs/DomainTools/ReleaseNotes/1_1_1.md
- Packs/DomainTools/pack_metadata.json
> DomainTools - Set Key to support creds

- Packs/MergeDictArray/ReleaseNotes/1_0_1.md
- Packs/MergeDictArray/Scripts/MergeDictArray/MergeDictArray.js
- Packs/MergeDictArray/Scripts/MergeDictArray/MergeDictArray.yml
- Packs/MergeDictArray/pack_metadata.json
- Fixed unaligned indents
N/A
- Fixed an incorrect description in the argument parameters.
- Fixed unaligned indents
> - Fixed an incorrect description in the argument parameters.

- Packs/CommonWidgets/ReleaseNotes/1_2_5.md
- Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget.py
- Packs/CommonWidgets/Scripts/MyToDoTasksWidget/MyToDoTasksWidget_test.py
- Packs/CommonWidgets/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45008
handled the case where there are no todo tasks and the server returns `None` as `data`
> MyToDoTasksWidget - handle empty res

- Packs/McAfee_Advanced_Threat_Defense/.pack-ignore
- Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py
- Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.yml
- Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_15.md
- Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/12772
> Mcafee atd creds

- Packs/DigitalShadows/README.md
- Packs/DigitalShadows/ReleaseNotes/1_0_2.md
- Packs/DigitalShadows/pack_metadata.json
implementation of https://github.com/demisto/content/pull/16530
> DigitalShadows - update readme (#16530)

- Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
> fix impacted resources command documentation

- Packs/Orca/Integrations/Orca/Orca.py
- Packs/Orca/Integrations/Orca/Orca.yml
- Packs/Orca/Integrations/Orca/Orca_test.py
- Packs/Orca/ReleaseNotes/1_0_9.md
- Packs/Orca/pack_metadata.json
> Orca memory optimization

- Tests/conf.json
> unmock use_default_handler

- Packs/GenericWebhook/TestPlaybooks/Generic_Webhook_-_Test.yml
fixes: [link to the issue](https://github.com/demisto/etc/issues/30797#)
Added a sleep task before searching the incident in the playbook.
> update Generic_Webhook TPB

- Tests/conf.json
relates: https://github.com/demisto/etc/issues/26741
relates: https://github.com/demisto/etc/issues/43923
Will be unskipped next month
> Skipped RF tests due to quota

- Packs/Jira/Integrations/JiraV2/README.md
Our lab uses JIRA cloud, so no specific relevant version as Attlasian updates it as it see fit.
not tested on-prem.
fixes: [link to the issue](https://github.com/demisto/etc/issues/45147)
> JIRA updated support versions

- Packs/CortexXDR/IncidentFields/XDR_Status_v2.json
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
- Packs/CortexXDR/Integrations/CortexXDRIR/README.md
- Packs/CortexXDR/Playbooks/Cortex_XDR_Incident_Handling.yml
- Packs/CortexXDR/Playbooks/Cortex_XDR_incident_handling_v2.yml
- Packs/CortexXDR/ReleaseNotes/4_2_13.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45042
Removed the "resolved_threat_handled" status option from the integration + XDR status incident field + playbooks.
> Xdr status v2 - removed "resolved_threat_handled"

- Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
- Packs/ArcherRSA/ReleaseNotes/1_1_31.md
- Packs/ArcherRSA/pack_metadata.json
https://github.com/demisto/etc/issues/45043
Added the default value None to the line:
`next((f for f in field_data['ValuesList'] if f['Name'] == item), None)`
to avoid the error `StopIteration` when the item value is not in the list.
> RSA Archer v2 - Improved error handling

- Packs/CommonScripts/pack_metadata.json
> Fix Remote Access Dependency in Common Scripts

- Tests/Marketplace/marketplace_services.py
> fixed unassignment variable

- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Pipfile
- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Pipfile.lock
- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
- Packs/Active_Directory_Query/ReleaseNotes/1_4_2.md
- Packs/Active_Directory_Query/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45175
> AD query v2: not throw exception in case there are no results

- Tests/conf.json
Due to a bug in the content build, adding back Phishing - Core - Test - Actual Incident back to conf.json and skipping it until this the issue will be resolved - https://github.com/demisto/etc/issues/45227
> add Phishing - Core - Test - Actual Incident to conf.json

- Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
fixes: lint failure
ignore mypy warning
before:
after:
> MicrosoftAPIModule: fix mypy error

- .github/workflows/review-release-notes.yml
- Tests/known_words.txt
fixes: reoccurring failures
allow additional allowed words.
> Update review-release-notes workflow

- Packs/Pwned/Integrations/PwnedV2/README.md
Have I been pwned api usage update
fixes: customer feedback
> Have I been pwned api usage update

- Tests/conf.json
https://code.pan.run/xsoar/content/-/jobs/9818974
added `Process Email - Generic - Test - Actual Incident` to conf.json
> add Process Email - Generic - Test - Actual Incident to conf.json

- Packs/CommonTypes/ReleaseNotes/3_1_29.md
Fixed RN in CommonTypes pack in version 3.1.29
> Fixed release_notes in CommonTypes

- Packs/PANOSPolicyOptimizer/CONTRIBUTORS.md
- Packs/PANOSPolicyOptimizer/ReleaseNotes/1_0_4.md
- Packs/PANOSPolicyOptimizer/pack_metadata.json
per: https://xsoar.pan.dev/docs/packs/packs-format#contributorsmd
> add-contributor-policy-optimizer

- Packs/CommonScripts/.pack-ignore
fixes: build
related to: https://github.com/demisto/content/pull/16366
> Fix file name in .pack-ignore

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/26741#issuecomment-1001948677
Un-skipped the tests
> Un-skipped RF tests

- Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json
- Packs/ThreatIntelReports/ReleaseNotes/1_0_6.md
- Packs/ThreatIntelReports/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45346
Changed `Modified` index to 1
Before:
After:
> Update `modified` index - Malware Report

- Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.yml
- Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/README.md
- Packs/CheckpointFirewall/ReleaseNotes/2_1_10.md
- Packs/CheckpointFirewall/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/45313)
Fixed outputs in commands:
***checkpoint-show-objects***
***checkpoint-group-get***
***checkpoint-access-rule-list***
> Fix outputs in Checkpoint Firewall

- Packs/Base/ReleaseNotes/1_18_1.md
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
- Packs/Base/pack_metadata.json
- [x ] Ready
fixes: [link to the issue](https://github.com/demisto/etc/issues/45432)
Fix context key value
> Fix context name in DbotFindSimilarIncidentByIndicators

- Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
- Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.yml
- Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2_test.py
- Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/test_data/mitre_test_data.py
- Packs/FeedMitreAttackv2/ReleaseNotes/1_0_9.md
- Packs/FeedMitreAttackv2/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45399
> Feed mitre attackv2 links fix

- Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.py
- Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
- Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed_test.py
- Packs/AutoFocus/ReleaseNotes/2_0_7.md
- Packs/AutoFocus/pack_metadata.json
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_test.py
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_5.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
- Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.py
- Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects.yml
- Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects_test.py
- Packs/Unit42Intel/ReleaseNotes/1_0_1.md
- Packs/Unit42Intel/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45463
> Remove API key from logs

- .circleci/config.yml
Fixing the GCP_MARKET_BUCKET parameter for the circle ci build.
> Add GCP_MARKET_BUCKET build parameter

- Packs/Slack/TestPlaybooks/playbook-Slack_TestPlaybook.yml
- Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Enrichment_README.md
- Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation.yml
- Packs/SocialEngineeringDomainAnalysis/Playbooks/Social_Engineering_Domain_Investigation_README.md
fixes: https://app.circleci.com/pipelines/github/demisto/content/136673/workflows/cf3c93b9-f036-4ad4-babe-760e0d2d8c4d/jobs/466283
fix validation error in master
not adding RN as the pack was not released yet
> Fix validation errors

- Packs/Lastline/Integrations/Lastline_v2/README.md
fixes: https://github.com/demisto/etc/issues/44728
fixes: https://github.com/demisto/etc/issues/19919
added a note to the command description that csv are not supported due to lastline api bug
> lastline documentation

- dev-requirements-py3.txt
fixes: build
replaced the `parinx` version with currently latest version from pypi
> Update dev-requirements-py3.txt: replace parinx version

- Packs/Base/ReleaseNotes/1_18_2.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
fix a [test failure](https://code.pan.run/xsoar/content/-/jobs/10027628), syntax warning
> fix regex syntax

- Packs/PhishingURL/.pack-ignore
- Packs/PhishingURL/ReleaseNotes/1_0_1.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/README.md
- Packs/PhishingURL/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/40683#issuecomment-1008311156)
Changing runas to DBotRole in order to use extractIndicators
> runas DBotRole and add README.md

- Packs/AzureLogAnalytics/Integrations/AzureLogAnalytics/README.md
- Packs/XSOARContentUpdateNotifications/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45104
> Log analytics docs

- Packs/CommonScripts/ReleaseNotes/1_6_23.md
- Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45689
add DBotRole permission to ReadPDFFileV2 script
> Add Read PDF file v2 script DBot role

- Packs/CommonScripts/.pack-ignore
Ignored the rundbotas validation error
related https://github.com/demisto/content/pull/17054
> Ignored dbutrunas error

- Packs/ContentManagement/IncidentFields/incidentfield-CustomPacksSource.json
- Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
- Packs/ContentManagement/ReleaseNotes/1_0_12.md
- Packs/ContentManagement/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45705
Added AWS S3 support to Configuration Setup PB.
> Added AWS S3 support to Configuration Setup PB

- Packs/Wiz/README.md
- Packs/Wiz/ReleaseNotes/1_0_1.md
Fixing typo in content pack logo URL, in readme.
> typo in pack logo path in readme

- Packs/Zscaler/Integrations/Zscaler/README.md
- Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
- Packs/Zscaler/ReleaseNotes/1_1_16.md
- Packs/Zscaler/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45775
Change integration display name, readme and pack metadata
> Change integration display name

- dev-requirements-py3.txt
use a custom sdk branch with python 3.10 fixed
> python 3.10 quick fix

- Packs/Gmail/Integrations/Gmail/README.md
fixes: https://github.com/demisto/etc/issues/45760
> Gmail - add required scopes per func to README

- dev-requirements-py3.txt
> add python 3.10 support

- Packs/PhishingURL/ReleaseNotes/1_0_2.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
- Packs/PhishingURL/pack_metadata.json
> Fix error no urls

- Packs/TAXIIServer/Integrations/TAXII2Server/README.md
> taxii 2 typo

- .gitlab/ci/bucket-upload.yml
- Tests/Marketplace/configure_and_install_packs.py
- Tests/Marketplace/copy_and_upload_packs.py
- Tests/Marketplace/marketplace_constants.py
- Tests/scripts/collect_tests_and_content_packs.py
fixes: [upload flow](https://code.pan.run/xsoar/content/-/pipelines/2268663)
fixes: [upload flow](https://code.pan.run/xsoar/content/-/pipelines/2269186)
fixes: [collect tests](https://code.pan.run/xsoar/content/-/pipelines/2268943)
fixed the index path when installing packs in the upload flow.
working flow: https://code.pan.run/xsoar/content/-/pipelines/2269928
> UploadFlow: fix index path

- Packs/ThreatQ/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45893
change pack support to XSOAR
> change pack support

- Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager_description.md
- Packs/BluecatAddressManager/Integrations/BluecatAddressManager/README.md
- Packs/BluecatAddressManager/ReleaseNotes/1_0_9.md
- Packs/BluecatAddressManager/pack_metadata.json
fixes: (https://github.com/demisto/etc/issues/45765)
> bluecat fixed readme

- Packs/ContentManagement/pack_metadata.json
> XSOAR CI/CD Move to GA

- Packs/PAN-OS/ReleaseNotes/1_8_4.md
> PAN OS - updated release notes after doc review

- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_0_6.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
N/A
Fixed an issue where 'status' is referenced before assignment
> Fixed an issue where 'status' is referenced before assignment

- Packs/Gmail/Integrations/Gmail/Gmail_description.md
- Packs/Gmail/Integrations/Gmail/README.md
- Packs/Gmail/ReleaseNotes/1_1_14.md
- Packs/Gmail/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45760
> Gmail - remove non required scopes from doc

- Packs/CommonScripts/Scripts/ShowLocationOnMap/README.md
> README for ShowLocationOnMap

- .gitlab/ci/global.yml
replace npm install with npm link.
> replace npm install with npm link

- .gitlab/ci/on-push.yml
- Packs/CommonScripts/Scripts/ShowLocationOnMap/README.md
fixes: upload
disable the mp v2 upload
> disable mpv2 upload

- Packs/XSOARContentUpdateNotifications/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45593
Changed support to community
> Content manager | Change support to community

- Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
- Packs/Tanium/ReleaseNotes/1_0_16.md
- Packs/Tanium/pack_metadata.json
> Typo in Tanium v2

- Packs/Wiz/Classifiers/classifier-Wiz_Mapper.json
- Packs/Wiz/Classifiers/classifier-Wiz_Mapper_Webhook.json
- Packs/Wiz/IncidentFields/incidentfield-Wiz_Resource_Native_Type.json
- Packs/Wiz/Integrations/Wiz/Wiz.py
- Packs/Wiz/Integrations/Wiz/Wiz.yml
- Packs/Wiz/Integrations/Wiz/Wiz_description.md
- Packs/Wiz/README.md
- Packs/Wiz/ReleaseNotes/1_0_1.md
- Packs/Wiz/pack_metadata.json
- **Wiz Resource Type**
- Modified field to have Wiz resource type. Example: `VIRTUAL_MACHINE`.
- **Wiz Resource Native Type**
- New field with cloud resource native type. Example: `Microsoft.Compute/virtualMachineScaleSets/virtualMachines`,
- Added additional checks to the "test" button in the integration settings page.
- Updated the Docker image to: *demisto/python3:3.10.1.25933*.
- Update mapper to match the field type changes
- Update mapper to match the field type changes
----
- more tests on initial configuration (not just auth, but one API fetch to verify API endpoint
- fixed incident field "resource type" to have the right data entry for the layout.
**The …
> wiz additional tests and fixes

- .gitlab/ci/.gitlab-ci.yml
- .gitlab/ci/slack-notify.yml
related: https://github.com/demisto/content/pull/17245
[nightly build](https://code.pan.run/xsoar/content/-/pipelines/2294476)
> update gitlab-content-ci docker tag to `1.0.0.26243`

- Packs/EDL/Playbooks/playbook-PAN-OS_EDL_Service_Configuration.yml
- Packs/EDL/ReleaseNotes/3_0_1.md
- Packs/EDL/pack_metadata.json
- Packs/ExportIndicators/pack_metadata.json
Added description for deprecation in addition to playbook deprecation.
fixes: https://github.com/demisto/etc/issues/46012
FYI @ytauman
> Deprecate edl

- Packs/CortexXDR/Integrations/CortexXDRIR/README.md
N/A
I think it's important to add a note here to set the mappers because without mappers, mirroring won't work.
N/A
> Under Incident Mirroring, add steps to set mappers

- Packs/CreatePlbkDoc/.pack-ignore
- Packs/CreatePlbkDoc/Scripts/CreatePlbkDoc/CreatePlbkDoc.py
- Packs/CreatePlbkDoc/Scripts/CreatePlbkDoc/CreatePlbkDoc.yml
- Packs/CreatePlbkDoc/pack_metadata.json
- Packs/FortiManager/Integrations/FortiManager/FortiManager.py
Two issues were observed when the automation ran on XSOAR version 6.5. 
Issue #1
When the REST API was called to get the list of the Playbooks matching a certain name, the parameter 'query' was used in the body. It is supposed to give the playbook matching the exact name but it returns other playbooks matching partially the required name as well. Code was modified to make sure that only that playbook is chosen that matches the exact name of the parameter.
Issue #2
Old code was using the [] notation to access certain members of the dictionary …
> Code fixed to resolve the issues that showed up on the XSOAR version 6.5.

- Tests/conf.json
> some final fixes

- Packs/MISP/TestPlaybooks/playbook-MISPV3-Test.yml
fixes: [link to the issue](https://github.com/demisto/etc/issues/40975)
Fixed a wrong condition after updating attribute
> Fix misp v3 TPB

- Packs/CommonTypes/IndicatorFields/incidentfield-cvss3.json
- Packs/CommonTypes/IndicatorFields/incidentfield-cvssvector.json
- Packs/CommonTypes/ReleaseNotes/3_2_2.md
- Packs/CommonTypes/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/43632
Adds 2 new fields to accommodate CVSS data for a new community integration and other CVF enrichers. 
> Added 2 new common type indicator fields (CVSS3 and CVSS Vector)

- .gitlab/ci/slack-notify.yml
fixes: empty comments in slack
fix artifact folder paths in the slack-notifier job
> fix artifact folder paths in the slack-notifier job

- Packs/Slack/ReleaseNotes/2_4_2.md
- Packs/Slack/Scripts/SlackAskV2/SlackAskV2.py
- Packs/Slack/Scripts/SlackAskV2/SlackAskV2.yml
- Packs/Slack/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46093
Adds a "cahnnel_id" argumet to the SlackAskV2 script to support channel IDs.
> Added channel_id argument

- Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_1_10.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46127
Fixed playbook view
> Fix playbook view

- Packs/PrismaCloud/TestPlaybooks/playbook-RedLockTest.yml
- Tests/conf.json
Change the RQL query for the events search to avoid timeout.
> Update Event search in TPB

- Packs/CommonScripts/ReleaseNotes/1_6_29.md
- Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
- Packs/CommonScripts/pack_metadata.json
Related to this: https://github.com/demisto/etc/issues/45994
Updated docker version.
> Bump convert file script docer

- Packs/CrowdStrikeFalcon/pack_metadata.json
- Packs/CrowdStrikeFalconSandbox/pack_metadata.json
- Packs/CrowdStrikeFalconX/pack_metadata.json
- Packs/CrowdStrikeHost/pack_metadata.json
- Packs/CrowdStrikeIntel/pack_metadata.json
- Packs/CrowdStrikeMalquery/pack_metadata.json
- Packs/CrowdStrikeOpenAPI/pack_metadata.json
- Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45750
Removed CrowdStrike packs from marketplace v2
> Removed Crowdstrike from marketplacev2

- Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
- Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
- Packs/QRadar/ReleaseNotes/2_1_28.md
- Packs/QRadar/pack_metadata.json
> [QRadar V2] Improved code resiliency

- Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.py
- Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
- Packs/SalesforceIndicators/ReleaseNotes/1_0_5.md
- Packs/SalesforceIndicators/pack_metadata.json
NA
This update uses get integration_context commands to better manage the volume of data returned. The integration will now firstly use the last modified date of the indicator in the initial and now subsequent pull to ensure that not every indicator (using the query) is returned every time.
NA
> Aburt-salesforce-indicators-improvements

- Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection_description.md
- Packs/AzureActiveDirectory/ReleaseNotes/1_2_1.md
- Packs/AzureActiveDirectory/pack_metadata.json
fixes: https://github.com/demisto/content-docs/issues/956
> Azure Identity Protection - update required permissions link in detailed desc

- Packs/MicrosoftGraphFiles/TestPlaybooks/test_MsGraphFiles_prod.yml
- Tests/conf.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/44214)
Unskip test playbook in msGraphFiles.
> Unskip test_MsGraphFiles prod TPB

- Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/README.md
https://github.com/demisto/etc/issues/46267
updating support to match McAfee EOL https://kc.mcafee.com/corporate/index?page=content&id=KB94822
> esm_v2_eol_update

- Packs/CommonTypes/IncidentFields/incidentfield-File_SHA256.json
- Packs/CommonTypes/ReleaseNotes/3_2_6.md
- Packs/CommonTypes/pack_metadata.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_1.md
- Packs/CoreAlertFields/pack_metadata.json
- Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Action.json
- Packs/FireMonSecurityManager/ReleaseNotes/1_0_3.md
- Packs/FireMonSecurityManager/pack_metadata.json
- Packs/Malware/pack_metadata.json
Fixing some issues with the new pack.
> Corealertfields fix

- Packs/ContentManagement/README.md
update readme to include video
> Update README to include video

- Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.py
- Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
- Packs/SalesforceIndicators/ReleaseNotes/1_0_5.md
- Packs/SalesforceIndicators/pack_metadata.json
This update uses get integration_context commands to better manage the volume of data returned. The integration will now firstly use the last modified date of the indicator in the initial and now subsequent pull to ensure that not every indicator (using the query) is returned every time.
> Salesforce contribution branch fixed

- Utils/release_notes_generator.py
fixing the following issue in master while running `Utils/release_notes_generator.py`:
`[2022-02-01 00:10:17] - [MainThread] - [ERROR] - missing name for Packs/OTSecurity/IndicatorTypes/reputation-MAC_Address.json
`
FYI @dansterenson
> fix mac address.json

- Packs/CreateEDLInstance/.pack_ignore
- Packs/CreateEDLInstance/README.md
- Packs/CreateEDLInstance/ReleaseNotes/1_0_1.md
- Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.py
- Packs/CreateEDLInstance/Scripts/CreateEDLInstance/CreateEDLInstance.yml
- Packs/CreateEDLInstance/Scripts/CreateEDLInstance/README.md
- Packs/CreateEDLInstance/pack_metadata.json
Update CreateEDLInstance script to allow for specifying ports.
> Update edl creation script

- .gitlab/ci/global.yml
https://github.com/demisto/etc/issues/43773
After lint improvements was released in sdk release - use it in lint step of nightly build
> Add time measure for nightly lint

- dev-requirements-py3.txt
> change the demisto-sdk version in requirements

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/33410
unskip microsoft teams managmenet test playbook after updating the refresh token.
> unskip microsoft teams managmenet test playbook

- Packs/MicrosoftManagementActivity/TestPlaybooks/MicrosoftManagementActivity_-_Test.yml
fixes: https://github.com/demisto/etc/issues/43922
> fixed test playbook MicrosoftManagement

- Packs/CommonTypes/IncidentFields/incidentfield-File_SHA256.json
- Packs/CommonTypes/ReleaseNotes/3_2_8.md
- Packs/CommonTypes/pack_metadata.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Subject.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-File_SHA256.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_3.md
- Packs/CoreAlertFields/pack_metadata.json
- Packs/FireMonSecurityManager/IncidentFields/incidentfield-FireMonSecurityManager-Action.json
- Packs/FireMonSecurityManager/ReleaseNotes/1_0_5.md
- Packs/FireMonSecurityManager/pack_metadata.json
Reversing back changes to fields
> Core alert fields fix 2

- Tests/Marketplace/copy_and_upload_packs.py
- Tests/Marketplace/upload_packs.py
- Tests/scripts/collect_tests_and_content_packs.py
- Tests/scripts/prepare_content_packs_for_testing.sh
- Utils/trigger_test_upload_flow.sh
- dev-requirements-py3.txt
* fixed some missing marketplace type references.
* updated sdk hot-fix commit: https://github.com/demisto/demisto-sdk/commit/5b220445c7e84ed5e80afe83bba21b39ffd9fef7
> Upload Flow: marketplace flag fixes

- Packs/CoreAlertFields/IncidentFields/incidentfield-Action.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Agent_OS_Sub_Type.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Category.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Domain.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Host_FQDN.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Host_Mac_address.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Host_OS.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Hostname.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeaturedhost.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeaturedipaddress.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-containsfeatureduser.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-isphishing.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-ruleid.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_7.md
- Packs/CoreAlertFields/ReleaseNotes/1_0_8.md
- Packs/CoreAlertFields/pack_metadata.json
change some CoreAlertFields fields types to shortText from multiSelect
> change field types

- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
- Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_26.md
- Packs/MicrosoftCloudAppSecurity/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46278
Updating the documentation for obtaining API token for Microsoft Cloud App Security
> Microsoft Cloud App Security - API token obtaining documentation 

- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
- Packs/CortexXDR/ReleaseNotes/4_2_17.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46414
Change "REMOTE_TERMINAL" which do not exists to "LIVE_TERMINAL"
From the UI
> Cortex XDR - IR Audit management logs fix

- Packs/LogRhythmRest/Integrations/LogRhythmRestV2/README.md
https://docs.logrhythm.com/docs/enterprise/find-more-information/end-of-life-policy-for-software-and-hardware#EndofLifePolicyforSoftwareandHardware-Appendix:EndofLifeTables
> logrythem-eol-info

- Packs/CommonTypes/IncidentFields/incidentfield-Tactic.json
- Packs/CommonTypes/IncidentFields/incidentfield-Tactic_ID.json
- Packs/CommonTypes/IncidentFields/incidentfield-Technique.json
- Packs/CommonTypes/IncidentFields/incidentfield-Technique_ID.json
- Packs/CommonTypes/ReleaseNotes/3_2_14.md
- Packs/CommonTypes/pack_metadata.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Mitre_ATT&CK_Tactic.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Mitre_ATT&CK_Technique.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_10.md
- Packs/CoreAlertFields/pack_metadata.json
- Packs/XMCyber/IncidentFields/incidentfield-Technique_Mitre.json
- Packs/XMCyber/IncidentFields/incidentfield-Technique_Name.json
- Packs/XMCyber/ReleaseNotes/1_0_13.md
- Packs/XMCyber/pack_metadata.json
> Mitre fields fix

- Tests/conf.json
> skipping confluence cloud

- Packs/Securonix/README.md
> sx-support-partner-update

- Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
- Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.yml
- Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2_test.py
- Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/README.md
- Packs/ProofpointTAP/ReleaseNotes/1_1_13.md
- Packs/ProofpointTAP/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/45456
> Proofpoint TAP v2 - Handle non-ascii chars in message

- Packs/CoreAlertFields/IncidentFields/incidentfield-Host_IP.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_11.md
- Packs/CoreAlertFields/pack_metadata.json
- Tests/Marketplace/core_packs_mpv2_list.json
> Remove wrong marketplace

- Packs/DomainTools/Integrations/DomainTools/DomainTools.js
- Packs/DomainTools/Integrations/DomainTools/DomainTools.yml
- Packs/DomainTools/ReleaseNotes/1_1_2.md
- Packs/DomainTools/pack_metadata.json
- Tests/known_words.txt
Enhanced the *Username* integration parameter to support credentials fetching object.
> Adding credentials set support domain tools

- Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
- Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py
- Packs/CortexXDR/ReleaseNotes/4_2_18.md
- Packs/CortexXDR/pack_metadata.json
fixed an issue with pagination in the use of `IndicatorsSearcher`.
> Fix xdr iocs pagination issue

- Packs/CortexDataLake/Integrations/CortexDataLake/README.md
[fixes: link to the issue](https://github.com/demisto/etc/issues/29857)
Updated the README according to the comments in https://github.com/demisto/etc/issues/29857
> Edit the configuration instructions in the README

- Packs/PAN-OS/Integrations/Panorama/Panorama.py
- Packs/PAN-OS/ReleaseNotes/1_8_8.md
- Packs/PAN-OS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46577
Changed `source` to destination
> Panorama small fix

- Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/46587)
Remove mandatory dependencies from CommonPlaybooks pack
> Remove mandatory dependencies from CommonPlaybooks pack

- .gitlab/ci/global.yml
copy id set debug files to artifact folder
> ID Set MPv2: copy debug files to artifact folder

- Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
- Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/README.md
- Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_1_3.md
- Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
update PAN-OS EDL Management description and README
> update PAN-OS EDL Management description and README

- Utils/github_workflow_scripts/handle_external_pr.py
Changed contributions team to @yuvalbenshalom
> Changed Contributions

- dev-requirements-py3.txt
fixes: missing items in marketplace v2
hot-fix includes:
* create-content-artifacts updates:
* missing items from packs
* missing indicator layouts
* updated schema of incident field aliases
> Update SDK hot-fix version

- Packs/Code42/Playbooks/playbook-Code42_Exfiltration_Playbook.yml
- Packs/Code42/ReleaseNotes/2_0_13.md
- Packs/Code42/pack_metadata.json
- Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_1_13.md
- Packs/CommonPlaybooks/pack_metadata.json
- Packs/PortScan/Playbooks/Port_Scan_-_Internal_Source.yml
- Packs/PortScan/ReleaseNotes/1_1_7.md
- Packs/PortScan/pack_metadata.json
Update skippable tasks in playbooks.
> update skippable tasks in playbooks

- Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails.py
- Packs/SecurityTrails/ReleaseNotes/1_1_1.md
- Packs/SecurityTrails/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46679
Sets a variables default value that otherwise produces an error on 9 results returned.
NA
> FIxed bug where SQL returns 0 results

- Packs/ServiceNow/Integrations/ServiceNowv2/README.md
> snow update link

- Packs/CoreAlertFields/IncidentFields/incidentfield-File_MD5.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-File_Path.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_17.md
- Packs/CoreAlertFields/pack_metadata.json
file path + file md5 - change x2_fields
> Core alert fix

- Packs/WhereIsTheEgg/pack_metadata.json
- Tests/Marketplace/core_packs_mpv2_list.json
remove easter egg pack from MP v2
> Remove WhereIsTheEgg from MP v2

- Packs/PhishUp/README.md
> PhishUp update README.md

- Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
- Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
- Packs/Infinipoint/ReleaseNotes/1_0_9.md
- Packs/Infinipoint/pack_metadata.json
> fix target

- Packs/ContentManagement/README.md
Remove broken video reference.
> Remove broken video reference

- Packs/CommonTypes/IncidentFields/incidentfield-Alert_URL.json
- Packs/CommonTypes/ReleaseNotes/3_2_20.md
- Packs/CommonTypes/pack_metadata.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-Misc.json
- Packs/CoreAlertFields/IncidentFields/incidentfield-URL.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_18.md
- Packs/CoreAlertFields/pack_metadata.json
Adding 2 new fields to Core Alert Fields.
> Adding fields core alert

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/31653
unskiped Archer test playbook.
> Unskip ArcherRSA TPB

- Packs/PicusAutomation/README.md
- [ x] Ready
Update Readme file.
> PicusAutomation Update README

- Tests/conf.json
https://github.com/demisto/etc/issues/31653#issuecomment-1042716443
> Increase timeout for Archer TPB

- Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower.py
- Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower.yml
- Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower_test.py
- Packs/AnsibleTower/Integrations/AnsibleTower/README.md
- Packs/AnsibleTower/Integrations/AnsibleTower/command_examples.txt
- Packs/AnsibleTower/Integrations/AnsibleTower/test_data/test_responses.py
- Packs/AnsibleTower/ReleaseNotes/1_0_11.md
- Packs/AnsibleTower/pack_metadata.json
I added a new command to query job events by Id.
- [ x] 6.0.0
> Ansible update

- Packs/TrendMicroVisionOne/Classifiers/classifier-Trend_Micro_Vision_One_XDR_-_Incoming_Mapper.json
- Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Impacted_Entities_JSON.json
- Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Indicators_JSON.json
- Packs/TrendMicroVisionOne/IncidentFields/incidentfield-Trend_Micro_Vision_One_XDR_Matched_Rules_JSON.json
- Packs/TrendMicroVisionOne/README.md
- Packs/TrendMicroVisionOne/ReleaseNotes/1_0_1.md
- Packs/TrendMicroVisionOne/pack_metadata.json
- Added 3 new fields with JSON data for indicators, entities and rules per customer request
- Updated mappings to populate new fields
- Updated README based on feedback from PAN Cortex Alliances team
- Added tags based on feedback from PAN Cortex Alliances team
> JSON fields, mappings, updated README

- Packs/Core/.pack-ignore
- Packs/Core/Integrations/CoreIOCs/CoreIOCs.py
- Packs/Core/Integrations/CoreIOCs/CoreIOCs.yml
- Packs/Core/Integrations/CoreIOCs/CoreIOCs_test.py
- Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
- Packs/Core/ReleaseNotes/1_0_1.md
- Packs/Core/pack_metadata.json
Add add_replace_strs to log and removed tag argument from IOCs
> Add add_replace_strs to log and removed tag arg

- Tests/scripts/dev_envs/pytest/conftest.py
Added conftest.py file in order to solve an error in content gold's build. 
> Added conftest file 

- .gitlab/ci/.gitlab-ci.yml
- .gitlab/ci/slack-notify.yml
should make our pipeline jobs start quickly.
> fix registry

- Packs/remedy_SR/ReleaseNotes/1_0_6.md
- Packs/remedy_SR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44132
moved BMC Remedy SR to community support.
> BMC Remedy SR: move pack to community support

- Tests/Marketplace/core_packs_list.json
- Tests/Marketplace/core_packs_mpv2_list.json
Add Generic Export Indicators Service to core packs
> Make edl core pack

- Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.py
- Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3.yml
- Packs/OpsGenie/Integrations/OpsGenieV3/OpsGenieV3_test.py
- Packs/OpsGenie/ReleaseNotes/2_0_4.md
- Packs/OpsGenie/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/46869)
> Ops genie get schedules bug fix

- Packs/F5LTM/Integrations/F5LTM/F5LTM.py
- Packs/F5LTM/Integrations/F5LTM/F5LTM.yml
- Packs/F5LTM/Integrations/F5LTM/README.md
- Packs/F5LTM/ReleaseNotes/1_0_2.md
- Packs/F5LTM/pack_metadata.json
- [x ] Ready
I have updated all integration commands to use an administrative partition argument, this argument value takes precedence over the default partition name that you specify in a configured instance of the integration. 
- [x ] 6.0.0
- [ x] No
- [x ] Documentation
> Adding an additional partition argument to all commands.

- Packs/UrlScan/Integrations/UrlScan/UrlScan.py
- Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
- Packs/UrlScan/ReleaseNotes/1_1_16.md
- Packs/UrlScan/pack_metadata.json
fixes: https://github.com/demisto/content/issues/17721
Added a new parameter and argument (to !url) for scan_visibility
NA
> Added new parameter and argument "scan_visbility"

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
- Packs/SplunkPy/ReleaseNotes/2_3_3.md
- Packs/SplunkPy/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46884
in some cases there is multiple `table` key in the search query
fix the RE when calculating headers for readable output
> fix RE when calculating headers for readable output

- Packs/ServiceNow/ReleaseNotes/2_3_4.md
- Packs/ServiceNow/Scripts/ServiceNowUpdateIncident/ServiceNowUpdateIncident.py
- Packs/ServiceNow/pack_metadata.json
[link to the issue](https://github.com/demisto/etc/issues/46764)
Added the [same](https://github.com/demisto/content/pull/17789) fix to the ServiceNowUpdateIncident script
> ServiceNowUpdateIncident bug fix

- .gitlab/ci/bucket-upload.yml
- .gitlab/ci/global.yml
- .gitlab/ci/instance-test.yml
- .gitlab/ci/miscellaneous.yml
- .gitlab/ci/on-push.yml
- .gitlab/ci/sdk-nightly.yml
- .gitlab/ci/slack-notify.yml
fixes: https://github.com/demisto/etc/issues/46661
added certs installation and new configuration for git, PyPI, and npm.
build-example: https://code.pan.run/xsoar/content/-/pipelines/2453927
> Added network custom certificate handling

- Packs/CommonTypes/IncidentFields/incidentfield-Parent_CMD_line.json
- Packs/CommonTypes/ReleaseNotes/3_2_23.md
- Packs/CommonTypes/pack_metadata.json
fix master by adding a file that was deleted by mistake in https://github.com/demisto/content/pull/17741
> revert deletion of incident-field Parent_CMD_line

- Packs/Slack/Integrations/SlackV3/SlackV3.py
- Packs/Slack/Integrations/SlackV3/SlackV3_test.py
- Packs/Slack/ReleaseNotes/2_5_1.md
- Packs/Slack/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/44744
Bot message was missidentified for action replies.
> Slackv3 botmessage hotfix

- Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.py
- Packs/Lastline/ReleaseNotes/1_0_12.md
- Packs/Lastline/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/46973
correct the condition to avoid out of index error
> Lastline_v2: avoid out of index error in condition

- .gitlab/ci/global.yml
> replaced the tag of unit tests and lint job

- Packs/CrowdStrikeFalconSandbox/TestPlaybooks/CrowdstrikeFalconSandbox2_Test.yml
fixes: [link to the issue](https://github.com/demisto/etc/issues/46741)
> use envid and file

- Packs/CrisisManagement/README.md
- Packs/Devo/Integrations/Devo_v2/README.md
- Packs/ExpanseV2/README.md
- dev-requirements-py3.txt
> hotfix readme validation

- .gitlab/ci/global.yml
- .gitlab/ci/on-push.yml
- .gitlab/ci/sdk-nightly.yml
> increase resource

- Packs/MISP/Integrations/MISPV3/MISPV3.py
- Packs/MISP/Integrations/MISPV3/MISPV3.yml
- Packs/MISP/Integrations/MISPV3/README.md
- Packs/MISP/Integrations/MISPV3/command_examples
- Packs/MISP/ReleaseNotes/2_1_1.md
- Packs/MISP/TestPlaybooks/playbook-MISPV3-Test.yml
- Packs/MISP/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47035
Added new command to publish an event by the given event ID.
> MISP - added new command to publish event

- Packs/Base/ReleaseNotes/1_18_13.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_4_5.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47039)
> CSP - Added new function to remove duplicates from list

- Packs/Microsoft365Defender/.pack-ignore
- Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml
- Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
- Packs/Microsoft365Defender/ReleaseNotes/3_0_2.md
- Packs/Microsoft365Defender/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/32998
> Defender365 ga

- .github/workflows/run-secrets-detection.yml
currently fails on https://github.com/demisto/content/runs/5377510680?check_suite_focus=true due to https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
> Secrets Detection - disable for dependabot

- Packs/SplunkPy/TestPlaybooks/playbook-SplunkPy-Test-V2.yml
- Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.py
- Packs/SplunkPyPreRelease/ReleaseNotes/1_0_7.md
- Packs/SplunkPyPreRelease/pack_metadata.json
https://github.com/demisto/etc/issues/46884
> Reflect RE fixed in SplunkPy to SplunkPyPreRelease

- Packs/CrisisManagement/.pack-ignore
- Packs/Devo/.pack-ignore
- Packs/ExpanseV2/.pack-ignore
- Packs/FeedZoom/.pack-ignore
- Packs/PcapAnalysis/.pack-ignore
- Packs/SOCRadar/.pack-ignore
- Packs/SlashNextPhishingIncidentResponse/.pack-ignore
- dev-requirements-py3.txt
added RM108 ignore to some files.
> added RM108 ignore to some files

- Packs/DeveloperTools/Integrations/CreateIncidents/CreateIncidents.py
- Packs/DeveloperTools/Integrations/CreateIncidents/CreateIncidents.yml
- Packs/DeveloperTools/ReleaseNotes/1_2_16.md
- Packs/DeveloperTools/pack_metadata.json
Internal
added support for incidents without name and occurred.
FYI @idovandijk
> Create incident fix

- Packs/MultiTenantPerformance/README.md
Added the server configuration change that is needed for  this pack.
> Create Multi-Tenant Performance Pack README

- .gitlab/ci/global.yml
> move UT to us-west1

- .gitlab/ci/bucket-upload.yml
- .gitlab/ci/global.yml
- .gitlab/ci/instance-test.yml
- .gitlab/ci/miscellaneous.yml
- .gitlab/ci/on-push.yml
- .gitlab/ci/sdk-nightly.yml
- .gitlab/ci/slack-notify.yml
> remove the es-west1 tags from gitlab gke pipelines

- dev-requirements-py3.txt
> update sdk hotfix

- Packs/Campaign/ReleaseNotes/3_2_9.md
- Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.py
- Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration.yml
- Packs/Campaign/Scripts/GetCampaignDuration/GetCampaignDuration_test.py
- Packs/Campaign/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47088)
Fixed HTML display. Waiting for the customer response to see that the problem is solved.
> Get campaign duration html bug fix

- Packs/AnsibleTower/Integrations/AnsibleTower/AnsibleTower.yml
- Packs/AnsibleTower/Integrations/AnsibleTower/README.md
- Packs/AnsibleTower/Playbooks/Ansible_Tower-_ad_hoc_command-_generic_polling.yml
- Packs/AnsibleTower/Playbooks/Ansible_Tower-_job_generic_polling.yml
- Packs/AnsibleTower/ReleaseNotes/1_0_12.md
- Packs/AnsibleTower/pack_metadata.json
- dev-requirements-py3.txt
Fixed the status matching of the polling sub-playbook and added a task to return job events. 
- [ x] 6.0.0
- [ x] No
- [ x] Documentation
> Fixing the Ansible Launch Job Playbook

- Packs/APIVoid/.pack-ignore
- Packs/APIVoid/Integrations/APIVoid/APIVoid.yml
- Packs/APIVoid/ReleaseNotes/1_0_11.md
- Packs/APIVoid/pack_metadata.json
- Packs/ReversingLabs_Titanium_Cloud/.pack-ignore
- Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2.yml
- Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_0_3.md
- Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
[new validation](https://github.com/demisto/demisto-sdk/pull/1932)/format feature requires common (reputation mostly) fields to have description.
> updated missing fields for new validation

- .github/dependabot.yml
- .github/workflows/check-contribution-form-filled.yml
- .github/workflows/check-contributor-pack.yml
- .github/workflows/create-internal-pr-from-external.yml
- .github/workflows/handle-new-external-pr.yml
- .github/workflows/handle-stale-branches.yml
- .github/workflows/project_manager_daily.yml
- .github/workflows/project_manager_hourly.yml
- .github/workflows/review-release-notes.yml
- .github/workflows/run-secrets-detection.yml
- .github/workflows/sync-contribution-base-branch.yml
- .github/workflows/trigger-contribution-build.yml
https://github.com/demisto/content/pull/17925
https://github.com/demisto/content/pull/17903
added the `docs-approved` label to all pull requests opened by dependabot
> GitHub Actions - bump checkout and setup-python to v3

- .gitlab/ci/on-push.yml
> temp lint fix

- Packs/VerifyIPv4Indicator/ReleaseNotes/1_0_1.md
- Packs/VerifyIPv4Indicator/Scripts/VerifyIPv4Indicator/VerifyIPv4Indicator.yml
- Packs/VerifyIPv4Indicator/pack_metadata.json
Changing to community and yml fixes
> VerifyIPv4Indicator fix

- Packs/MISP/Integrations/MISPV3/MISPV3.py
- Packs/MISP/Integrations/MISPV3/MISPV3.yml
- Packs/MISP/Integrations/MISPV3/README.md
- Packs/MISP/ReleaseNotes/2_1_2.md
- Packs/MISP/ReleaseNotes/2_2_0.md
- Packs/MISP/pack_metadata.json
- Added support for *Sharing group* distribution in **misp-create-event** command.
- Updated the Docker image to: *demisto/pymisp2:1.0.0.27224*.
> MISP - create-event command - Add sharing group support

- Tests/conf.json
Ready
Related to:
https://code.pan.run/xsoar/content-test-conf/-/merge_requests/1402
https://github.com/demisto/content/pull/16731
New instances config for EWS O365 on conf.json
> New instances config for EWS O365 on conf.json

- Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
Updated the Readme file with a line about role assignment to applications.
- [x ] 6.0.0
- [ x] No
> Update Azure Compute v2 README.md

- Packs/AutoFocus/Integrations/FeedAutofocusDaily/FeedAutofocusDaily.yml
- Packs/AutoFocus/Integrations/FeedAutofocusDaily/README.md
- Packs/AutoFocus/ReleaseNotes/2_0_13.md
- Packs/AutoFocus/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47020)
Deprecate AutoFocus Daily Feed since AF daily feed is deprecated.
> Deprecate AutoFocus Daily Feed

- Packs/Okta/README.md
> Update Okta README.md

- Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
- Packs/FeedMandiant/ReleaseNotes/1_0_2.md
- Packs/FeedMandiant/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47085)
Add fixes to mandiant's pack metadata
> Mandiant fix

- Packs/XSOARContentUpdateNotifications/IncidentFields/incidentfield-Content_Notification_Slack_Channel_ID.json
- Packs/XSOARContentUpdateNotifications/Layouts/layoutscontainer-Content_Update_Manager_Layout.json
- Packs/XSOARContentUpdateNotifications/Playbooks/playbook-Content_Update_Manager.yml
- Packs/XSOARContentUpdateNotifications/ReleaseNotes/1_0_4.md
- Packs/XSOARContentUpdateNotifications/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47244
Added the ability to define and use Slack Channel ID in the PB.
NA
> Aburt-content-update-manager-improvements

- Packs/ContentManagement/README.md
> xsoar_ci_cd_youtube_vid

- Packs/CortexXDR/README.md
> cortex_xdr_demo_youtube_vid

- Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
removed the old pwsh version since this is not in use in any of our integration/scripts
> pwsh version dose not support a part of the test requirements

- .gitlab/ci/on-push.yml
- dev-requirements-py3.txt
> demisto-sdk hotfix update

- Packs/CoreAlertFields/IncidentFields/incidentfield-Host_IP.json
- Packs/CoreAlertFields/ReleaseNotes/1_0_20.md
- Packs/CoreAlertFields/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XDR-50312
> Change Host IP from shorttext to array

- Packs/ContentManagement/README.md
- Packs/CortexXDR/README.md
> syntax fixes

- Packs/CortexXDR/.pack-ignore
- Packs/GoogleCloudSCC/Integrations/GoogleCloudSCC/GoogleCloudSCC_test.py
> fix google SCC UT & Packs/CortexXDR/README.md RM108 error

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Packs/MicrosoftTeams/ReleaseNotes/1_1_23.md
- Packs/MicrosoftTeams/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47102
As the message handling un Teams integration done by internal web service - the exceptions raised in this functionality not reflect in the log
the fix will print error entry for those exceptions
> MS Teams: improve error handling when handle incoming message

- Packs/Symantec_Deepsight/Integrations/Symantec_Deepsight/Symantec_Deepsight.yml
- Packs/Symantec_Deepsight/ReleaseNotes/1_0_4.md
- Packs/Symantec_Deepsight/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/47422
deprecate the `Symantec Deepsight` pack.
> deprecate the Symantec Deepsight pack

- Tests/scripts/should_lint_all.sh
- dev-requirements-py3.txt
fixes: https://github.com/demisto/etc/issues/45356
Fixing should_lint_all script to catch a case where the demisto-sdk commit hash is changed.
https://code.pan.run/xsoar/content/-/jobs/11420821
> should_lint_all_fixes

- Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py
- Packs/AWS-EC2/ReleaseNotes/1_2_11.md
- Packs/AWS-EC2/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47442)
> aws-describe-instances bug fix

- Tests/Marketplace/core_packs_list.json
- Tests/Marketplace/core_packs_mpv2_list.json
Add FiltersAndTransformers to core packs lists
> Add FiltersAndTransformers to core packs lists

- Packs/DeepL/pack_metadata.json
> Change to the description

- Tests/scripts/validate.sh
Invoke demisto-sdk with native python invocation (python -m demisto_sdk) instead of script name (demisto-sdk)
connected pr:https://github.com/demisto/demisto-sdk/pull/1963
> fixed how demisto-sdk is running in script

- Packs/Zscaler/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47483
> rm-zscaler-mp-v2

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_7_1.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47472)
> falcon-resolve-detection bug fix

- Packs/Base/ReleaseNotes/1_18_20.md
- Packs/Base/Scripts/CommonServer/CommonServer.js
- Packs/Base/pack_metadata.json
> use older js style

- .github/workflows/check-contribution-form-filled.yml
- .github/workflows/create-internal-pr-from-external.yml
- Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
This a test PR to test copying labels from external PR to internal PR works
> test copy external pr labels to internal pr labels

- Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
- Packs/AzureKeyVault/.pack-ignore
- Packs/EWS/Integrations/EWSO365/EWSO365.py
- Packs/EWS/Integrations/EWSO365/EWSO365.yml
- Packs/EWS/Integrations/EWSO365/EWSO365_test.py
- Packs/EWS/Integrations/EWSO365/README.md
- Packs/EWS/ReleaseNotes/1_11_6.md
- Packs/EWS/ReleaseNotes/1_11_7.md
- Packs/EWS/pack_metadata.json
Fix issues introduced in https://github.com/demisto/content/pull/17930
> Fix Build Issues

- Packs/Jira/.secrets-ignore
- Packs/Jira/Integrations/JiraV2/JiraV2.py
- Packs/Jira/Integrations/JiraV2/JiraV2_test.py
- Packs/Jira/ReleaseNotes/1_4_10.md
- Packs/Jira/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47434)
> jira-get-id-by-attribute bug fix

- Packs/APIVoid/Integrations/APIVoid/README.md
- Packs/APIVoid/ReleaseNotes/1_0_12.md
- Packs/APIVoid/pack_metadata.json
fixes: https://github.com/demisto/content/issues/17420
fixes: https://github.com/demisto/etc/issues/45000
Added README as per the issue.
NA
> Added README to integration

- Documentation/common_server_docs.py
> Common Server Docs - handle modified unifier import

- Packs/Slack/Scripts/SlackAskV2/README.md
n/a
Add note to document the fact that SlackAskV2 does not work in the playbook debugger.
n/a
n/a - content.
> Add note that SlackAskV2 does not work in debugger

- dev-requirements-py3.txt
hotfixing to include [this bug fix](https://github.com/demisto/demisto-sdk/pull/1971)
> 1.6.2 Hotfix

- Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
- Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
- Packs/SecurityScorecard/README.md
- Packs/SecurityScorecard/ReleaseNotes/1_0_3.md
- Packs/SecurityScorecard/pack_metadata.json
Introducing a new header to help measure usage
> Introducing metrics api header

- Packs/FeedBlocklist_de/Integrations/FeedBlocklist_de/README.md
- Packs/FeedBlocklist_de/ReleaseNotes/1_1_15.md
- Packs/FeedBlocklist_de/pack_metadata.json
https://github.com/demisto/content/issues/17423
Added README to the integration.
NA
> Aburt-blocklistDE-README

- Packs/SafeNet_Trusted_Access/.secrets-ignore
- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/README.md
- Packs/SafeNet_Trusted_Access/Integrations/SafeNetTrustedAccess/SafeNetTrustedAccess_description.md
- Packs/SafeNet_Trusted_Access/README.md
- Packs/SafeNet_Trusted_Access/ReleaseNotes/2_0_3.md
- Packs/SafeNet_Trusted_Access/pack_metadata.json
- Pipfile.lock
fixes: Updated the guide link.
We have just introduced a new STA online documentation portal that comes with new URLs. As a result of this, we will need to update the documentation URL at content package.
> Updated guide link

- Tests/Marketplace/upload_packs.py
> fix identation upload zipped packs

- Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA.py
- Packs/TrendMicroDDA/ReleaseNotes/1_0_8.md
- Packs/TrendMicroDDA/pack_metadata.json
Fixed minor issue with hashing function not working correctly
> Trendmicro ddan fix

- Packs/Forescout/.pack-ignore
- Packs/Forescout/Integrations/Forescout/Forescout.yml
- Packs/Forescout/Integrations/Forescout/Forescout_description.md
- Packs/Forescout/Integrations/Forescout/README.md
- Packs/Forescout/ReleaseNotes/1_0_7.md
- Packs/Forescout/pack_metadata.json
> forescout CounterACT naming

- Packs/Cybereason/Integrations/Cybereason/Pipfile
- Packs/Cybereason/README.md
- Packs/Cybereason/ReleaseNotes/1_0_19.md
- Packs/Cybereason/pack_metadata.json
> Adopt cybereason pack

- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
- Packs/AzureSentinel/ReleaseNotes/1_3_7.md
- Packs/AzureSentinel/pack_metadata.json
- Packs/Base/ReleaseNotes/1_19_4.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
- Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
- Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
- Packs/RubrikPolaris/ReleaseNotes/1_0_9.md
- Packs/RubrikPolaris/pack_metadata.json
> Newbranch extra mypy

- Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/README.md
fixes: [link to the issue](https://github.com/demisto/etc/issues/46421)
Updated the version the integration was tested with in readme.
> fix readme to include new version

- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
- Packs/FeedRecordedFuture/ReleaseNotes/1_0_25.md
- Packs/FeedRecordedFuture/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47595
fixed the missed param
> fix param missing

- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.yml
- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_6_2.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Added missing output options to the new commands.
> [msde] Add Output Options to YAML

- Utils/github_workflow_scripts/handle_external_pr.py
update contribution reviews for next shift.
> update contrib reviewers

- Packs/FireEyeHX/.pack-ignore
- Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml
- Packs/FireEyeHX/Integrations/FireEyeHXv2/README.md
- Packs/FireEyeHX/ReleaseNotes/2_1_1.md
- Packs/FireEyeHX/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/37161
Corrections of types and descriptions in the yml and README files
> Corrections types and descriptions

- Packs/ContentManagement/README.md
> Content Mgmt - Fix broken link

- Tests/configure_and_test_integration_instances.py
fixes: fix some installation errors.
change sleep to 120 sec after the marketplace url is set.
> change sleep to 120 sec after marketplace url set

- Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
- Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.yml
- Packs/CortexXDR/ReleaseNotes/4_2_23.md
- Packs/CortexXDR/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/47604)
> XDR XQL added message

- Packs/ContentManagement/.pack-ignore
> Added ignore to youtube

- Packs/ContentManagement/.pack-ignore
> pack ignore - fix typo

- .gitlab/ci/slack-notify.yml
- Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
> Fix slack notify docker image

- Packs/SNDBOX/Integrations/SNDBOX/SNDBOX.yml
- Packs/SNDBOX/ReleaseNotes/1_0_6.md
- Packs/SNDBOX/pack_metadata.json
- Tests/known_words.txt
fixes: [#47726](https://github.com/demisto/etc/issues/47726)
According to the attached issue, deprecated the SNDBOX integration.
> Deprecating sndbox

- .github/workflows/review-release-notes.yml
- Packs/BeyondTrust_Password_Safe/.pack-ignore
- Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.py
- Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
- Packs/BeyondTrust_Password_Safe/ReleaseNotes/1_0_14.md
- Packs/BeyondTrust_Password_Safe/pack_metadata.json
Added the original error to the custom error
> BeyondTrust improve exception message

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- [ x] Ready
(https://github.com/demisto/etc/issues/47806)
Added a list of domains to which traffic should be allowed in order for MS teams integration to work.
> Add list of domains used by the integration

- Packs/ExtFilter/ReleaseNotes/1_1_10.md
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py
- Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml
- Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json
- Packs/ExtFilter/pack_metadata.json
N/A
Fixed an issue where `is updated with` returns incorrect values.
> Fixed an issue where `is updated with` returns incorrect values.

- Packs/PrismaCloudCompute/TestPlaybooks/playbook-PaloAltoNetworks_PrismaCloudCompute-Test.yml
fixes: https://github.com/demisto/etc/issues/45071
fix prisma cloud compute test playbook
> fix prisma cloud compute test playbook

- Packs/PaloAltoNetworks_IoT/README.md
fix this:
https://xsoar.pan.dev/marketplace/details/PaloAltoNetworks_IoT
> IoT readme ---- fix

- Packs/RubrikPolaris/Layouts/layoutscontainer-Account_Indicator.json
fixed duplicate items
related to: https://github.com/demisto/content/pull/18488
not adding RN as it wasn't released yet.
> RubrikPolaris: fix duplicate names

- Packs/GoogleCloudTranslate/Integrations/GoogleCloudTranslate/GoogleCloudTranslate.py
> google translate fix

- .gitlab/ci/global.yml
[gitlab docs](https://docs.gitlab.com/ee/ci/yaml/index.html#interruptible)
> Add interruptible keyword to support auto cancellation in gitlab

- .gitlab/helper_functions.sh
add a human-readable timestamp at the start and end of Gitlab sections
before:
after (see lines 160, 167):
> gitlab: Update section wrappers

- Packs/dnstwist/Integrations/dnstwist/dnstwist.yml
- Packs/dnstwist/ReleaseNotes/1_1_4.md
- Packs/dnstwist/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/47979
Manual update the docker image to speed the process
> update dnstwist docker image

- Packs/KasperskySecurityCenter/.pack-ignore
- Tests/conf.json
ignored accoring to: https://xsoar.pan.dev/docs/packs/packs-format#pack-ignore
> ignore-kaspersky-tpb

- Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.py
- Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.yml
- Packs/ZeroTrustAnalyticsPlatform/ReleaseNotes/1_1_1.md
- Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json
* Fix bug where alerts would not ingest if assigned to a user
* Bump python version to 3.10.4.28442
* Format documentation
> Update ZeroTrustAnalyticsPlatform to 1.1.1

- Packs/EDL/Integrations/EDL/EDL.py
- Packs/EDL/Integrations/EDL/EDL.yml
- Packs/EDL/ReleaseNotes/3_1_1.md
- Packs/EDL/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/48103
Fixes an issue when CIDR size is not specified
> Fix not provided maximum cidr size

- Packs/qualys/README.md
vulnerabilities was spelled wrong.
fixed spelling mistake typo on qualys readme
> fixed spelling mistake typo on qualys readme

- Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
- dev-requirements-py3.txt
Passed build with no proxy problems: https://code.pan.run/xsoar/content/-/pipelines/2810067
> Fix-timetampreplacer-proxy-start

- dev-requirements-py2.txt
> remove requests from python2

- .gitlab/ci/on-push.yml
> fix redundant lint for upload flow

- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/README.md
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_description.md
N/A
Clarify the purpose of the Palo Alto Networks WildFire Reports integration as opposed to the Palo Alto Networks WildFire v2 integration in the in-product documentation, as this had led to some confusion.
> Clarify purpose of PANW WildFire Reports integration in in-product docs

- Packs/ContentManagement/README.md
- Packs/CortexXDR/README.md
- Packs/CrisisManagement/README.md
> rm bad vids

- Packs/ContentManagement/pack_metadata.json
- Packs/CortexXDR/pack_metadata.json
- Packs/CrisisManagement/pack_metadata.json
- Packs/Slack/pack_metadata.json
related: https://jira-hq.paloaltonetworks.local/browse/XDR-52801
Added the new `videos` key to the pack meta_data
> Add video to pack meta data

- Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.py
- Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_18.md
- Packs/MicrosoftGraphSecurity/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/48146
Parsing empty string
> Msgraph fetch lmit fix

- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.py
- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP_test.py
- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/README.md
- Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/1_1_1.md
- Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
None
Removing an integration parameter "Environment" that shouldn't have been introduced. I have talked with Shahaf about this before creating this Pull Request.
- Further details: If any customer has selected "Staging" as environment for the previous version, it will be ignored in this version. However no customer has access to "Staging" so this is a non issue.
> Remove an integration parameter "Environment" that was introduced by mistake

- Packs/FeedCognyteLuminar/pack_metadata.json
> luminar feed typo fix

- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
- Packs/ImageOCR/ReleaseNotes/1_1_3.md
- Packs/ImageOCR/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/48123
The library that runs this command was in the very old version, updated docker image to use the new version of the `tesseract` library.
> updated docker image

- Packs/EDL/Integrations/EDL/README.md
Improved spacing and english(I think)
https://panw-global.slack.com/archives/C01DJNZUQ0G/p1635187030005600
> Export IOCS - terms of time

- Tests/Marketplace/search_and_install_packs.py
- Tests/scripts/prepare_content_packs_for_testing.sh
Add errors list handling (As arises from this build: https://code.pan.run/xsoar/content/-/pipelines/2833816)
> fix 400 error handling

- Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.py
- Packs/AzureActiveDirectory/ReleaseNotes/1_2_7.md
- Packs/AzureActiveDirectory/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XDRSUP-11777
fixed a bug where client credentials mode did not work as expected .
Before:
After:
> Azure ad bug

- Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
- Tests/scripts/wait_in_line_for_xsiam_env.sh
fixes: https://github.com/demisto/etc/issues/47970
> Remove bad build locks

- Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax.yml
- Packs/FeedCyjax/ReleaseNotes/1_0_5.md
- Packs/FeedCyjax/pack_metadata.json
- Packs/Qintel/Integrations/QintelQWatch/QintelQWatch.yml
- Packs/Qintel/ReleaseNotes/1_0_3.md
- Packs/Qintel/pack_metadata.json
- Packs/Slack/Integrations/SlackV3/SlackV3.yml
- Packs/Slack/ReleaseNotes/2_5_9.md
- Packs/Slack/pack_metadata.json
fixes: [link to the issue](https://github.com/demisto/etc/issues/40994)
Last three yml's
defaultvalue: true -> defaultvalue: 'true'
> fix last three yml's

- Packs/Slack/Integrations/SlackV3/SlackV3.yml
- Packs/Slack/ReleaseNotes/2_5_10.md
- Packs/Slack/pack_metadata.json
related: https://github.com/demisto/etc/issues/40994
Defaultvalue for checkbox fixed
> slackV3_yml fix defaultvalue

- Packs/Orca/README.md
- Packs/Orca/pack_metadata.json
until we will add it back to the section
> Orca_rm_video_readme_add_metadata

- Tests/Marketplace/Tests/marketplace_services_test.py
- Tests/Marketplace/marketplace_services.py
Changing `isFetchEvents` to `isfetchevents`.
> Lowercase `isfetchevents`

- Packs/CommonScripts/TestPlaybooks/playbook-HttpV2-Test.yml
> Fix HttpV2 TPB

- Utils/github_workflow_scripts/handle_external_pr.py
> Added prints to debug content bot

- Packs/AzureFirewall/pack_metadata.json
- Packs/AzureKeyVault/pack_metadata.json
- Packs/BatchData/pack_metadata.json
- Packs/CreateEDLInstance/pack_metadata.json
- Packs/DB2/pack_metadata.json
- Packs/DeepL/pack_metadata.json
- Packs/FeedMandiant/pack_metadata.json
- Packs/GCP-IAM/pack_metadata.json
- Packs/GoogleSheets/pack_metadata.json
- Packs/MacVendors/pack_metadata.json
- Packs/MaxList/pack_metadata.json
- Packs/MinList/pack_metadata.json
- Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json
- Packs/NetskopeV2/pack_metadata.json
- Packs/PowerShellUtilities/pack_metadata.json
- Packs/RandomElementFromList/pack_metadata.json
- Packs/VerifyIPv4Indicator/pack_metadata.json
- Packs/WolkenITSM/pack_metadata.json
- Packs/Xsoar_Utils/pack_metadata.json
> Add packs to XSIAM marketplace
