Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml, Packs/Core/Playbooks/playbook-NGFW_Scan.yml
=> testing commit

Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py, Packs/VirusTotal-Private_API/ReleaseNotes/1_0_15.md, Packs/VirusTotal-Private_API/pack_metadata.json, Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.js, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.py, Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.yml, Packs/VirusTotal/ReleaseNotes/2_4_1.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Improve packs use global stats

Packs/UrlScan/Integrations/UrlScan/UrlScan.py, Packs/UrlScan/ReleaseNotes/1_1_22.md, Packs/UrlScan/pack_metadata.json
Set User-Agent header on all API requests to urlscan
=> urlscan - Set Useragent

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py, Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml, Packs/HatchingTriage/ReleaseNotes/1_0_4.md, Packs/HatchingTriage/pack_metadata.json
(file) submission was broken, this PR fixes that. Original file names will be now used, instead of file IDs as names for Triage submissions. It also adds support the the 'fetch' submit type (https://tria.ge/docs/cloud-api/samples/#fetching-a-sample-from-a-url).
=> Fix submit and add fetch support for HatchingTriage

.github/CODEOWNERS
remove un-existent user @abaumgarten from code-owners
=> fix codeowners error

.circleci/config.yml, .gitlab/ci/global.yml
=> build: pip list to artifacts

Packs/MISP/Integrations/MISPV3/MISPV3.py, Packs/MISP/Integrations/MISPV3/MISPV3.yml, Packs/MISP/Integrations/MISPV3/MISPV3_test.py, Packs/MISP/Integrations/MISPV3/README.md, Packs/MISP/Integrations/MISPV3/command_examples, Packs/MISP/Integrations/MISPV3/test_data/warninglist_outputs.md, Packs/MISP/Integrations/MISPV3/test_data/warninglist_response.json, Packs/MISP/ReleaseNotes/2_1_5.md, Packs/MISP/pack_metadata.json
Addition of command ***misp-check-warninglist*** to check values against warninglist.
Addition of command ***misp-set-event-attributes*** to set the attributes of an misp event.
Adding support for the *eventinfo* argument in the ***misp-search-events*** command to search a misp event by eventinfo.
Adding support for multiple types for the *type* argument in search commands like the ***misp-search-attributes*** command.
=> Initial draft of changes

Packs/Jq/.secrets-ignore, Packs/Jq/Scripts/Jq/Jq.py, Packs/Jq/Scripts/Jq/Jq.yml, Packs/Jq/Scripts/Jq/Pipfile, Packs/Jq/Scripts/Jq/Pipfile.lock, Packs/Jq/Scripts/Jq/README.md, Packs/Jq/pack_metadata.json
* [Marketplace Contribution] jq (#18472)
* "pack contribution initial commit"
* fix marketplace bug
* Update json string handling as suggested
Co-authored-by: Adi Bamberger Edri <72088126+BEAdi@users.noreply.github.com>
* Use is_error
* rename package
* Update Packs/Jq/Scripts/Jq/Jq.yml
Co-authored-by: Adi Bamberger Edri <72088126+BEAdi@users.noreply.github.com>
* Update Packs/Jq/Scripts/Jq/Jq.yml
Co-authored-by: Adi Bamberger Edri <72088126+BEAdi@users.noreply.github.com>
* Update Packs/Jq/pack_metadata.json
Co-authored-by: Adi Bamberger Edri <72088126+BEAdi@users.noreply.github.com>
* sdk secrets removal
* Fix yml validation
Co-authored-by: BEAdi <72088126+BEAdi@users.noreply.github.com>
Co-authored-by: 68zuhKQfKPk <98105006+68zuhKQfKPk@users.noreply.github.com>
* Update to 6.1 …
=> [Marketplace Contribution] jq (#18867)

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XDRSUP-11919)
Added to doc files the limit on attachments for the ***send-mail*** command.
=> MicrosoftGraphMail 

Packs/ContentManagement/pack_metadata.json, Packs/CortexXDR/pack_metadata.json, Packs/CrisisManagement/pack_metadata.json, Packs/Orca/pack_metadata.json, Packs/Slack/pack_metadata.json, Tests/Marketplace/marketplace_services.py
Changed videos key from str to list.
=> feat: change videos key to list

Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
We should not set limit in general fetch-events case. Setting limit to optional and defaulting to None.
=> feat: SiemApiModule set limit to optional

.github/CODEOWNERS
=> Move Code Owner

Packs/ApiModules/Scripts/SiemApiModule/SiemApiModule.py
=> feat: SiemApiModule set proxy to Optional[bool] to handle none value

Packs/Netskope/Integrations/NetskopeAPIv1/README.md
=> netskope-readme

Tests/demistomock/demistomock.py
relates: https://github.com/demisto/etc/issues/32031
We will use is_error arg to determine whether or not to display it as an error message in the fetch history
=> Updated demisto.updateModuleHealth

Packs/Slack/Integrations/SlackV3/README.md, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/Integrations/SlackV3/command_example.txt, Packs/Slack/ReleaseNotes/2_5_11.md, Packs/Slack/doc_files/SlackV3_app_manifest.yml, Packs/Slack/pack_metadata.json
When adding our slackbot to a dm, the bot reads the messages and thinks they are sent to it. Will address this by removing those permissions, as they dont seem critical to the bots function
=> took off permissions and added default val

Packs/Core/Integrations/CoreIOCs/CoreIOCs.py, Tests/scripts/wait_in_line_for_xsiam_env.sh
=> Wait in line issue

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml, Tests/Marketplace/configure_and_install_packs.py
fixes: upload issue
related: https://github.com/demisto/content/pull/19036
=> Remove 6.1 from build

Packs/PowershellRemoting/Integrations/PowerShellRemoting/README.md
=> Added link to guide

Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.js, Packs/VirusTotal/ReleaseNotes/2_4_2.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Fix network request error

Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.py, Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml, Packs/ActiveMQ/ReleaseNotes/1_1_0.md, Packs/ActiveMQ/pack_metadata.json
=> feat: ActiveMQ - updated docker image

.gitlab/ci/global.yml
=> Remove lint quiet mode

.github/project_conf/contributions.ini
Changed the contributor column 'Reviewed And Waiting For Changes' to auto be assigned the PRs with the pending-contributor new label
=> add pending-contributor label

Packs/Malware/pack_metadata.json, Tests/Marketplace/core_packs_list.json, Tests/Marketplace/core_packs_mpv2_list.json
fixes: nightly
reverted recent Malware changes
=> revert malware changes

Packs/AzureActiveDirectory/Integrations/AzureADIdentityProtection/AzureADIdentityProtection.yml, Packs/AzureActiveDirectory/ReleaseNotes/1_2_9.md, Packs/AzureActiveDirectory/pack_metadata.json
https://panw-global.slack.com/archives/C011E5T5K17/p1652867436550819
=> changed display to display password

Packs/CrowdStrikeFalcon/README.md
https://github.com/demisto/content/pull/18854
Create pack readme for CrowdStrike Falcon since this is one of the most used packs in the XSOAR MP.
=> Create content for CrowdStrikeFalcon Pack README

Packs/AttachmentsPreProcessing/.pack-ignore
=> contrib fix

Tests/Marketplace/Tests/search_and_install_packs_test.py, Tests/Marketplace/search_and_install_packs.py
fixes: broken build https://code.pan.run/xsoar/content/-/jobs/13036998
=> Fix install packs error response handling

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml, Tests/Marketplace/configure_and_install_packs.py, Tests/scripts/collect_tests_and_content_packs.py, Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
added 6.5 & 6.6 server versions to the build tests.
=> added 6.5 & 6.6 server versions

Packs/MISP/Integrations/MISPV3/MISPV3.py, Packs/MISP/Integrations/MISPV3/MISPV3.yml, Packs/MISP/Integrations/MISPV3/README.md, Packs/MISP/ReleaseNotes/2_1_6.md, Packs/MISP/pack_metadata.json
Added support for creation_date argument for misp-create-event command
=> Added support for creation_date argument for misp-create-event command

Packs/Malware/pack_metadata.json
reverting an unintentional change
=> unhide the malware pack

Packs/MicrosoftGraphSecurity/README.md
Create pack readme for MicrosoftGraphSecurity. This content will appear in Marketplace.
=> Create pack readme for MicrosoftGraphSecurity

Packs/ExtFilter/ReleaseNotes/1_1_11.md, Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py, Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml, Packs/ExtFilter/Scripts/ExtFilter/README.md, Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json, Packs/ExtFilter/pack_metadata.json
N/A
Added a new parameter which is `lhs` to enhance `if-then-else` to make expressions.
=> Enhance an feature of `if-then-else` to make expressions

Packs/ArcherRSA/README.md
Create content for Archer RSA pack readme. This content will appear in Marketplace.
=> Create content for Archer RSA pack readme

Packs/AzureSecurityCenter/README.md
Create pack readme content for Azure Security Center.  This content will appear in Marketplace.
=> Create content for Azure Security Center

Packs/MalwareInvestigationAndResponse/pack_metadata.json
Set the malware pack as hidden.
triggered an upload: https://code.pan.run/xsoar/content/-/pipelines/2981459
=> Malware: set pack as hidden

.gitlab/ci/bucket-upload.yml
Add that upload to marketplace-v2 dependents xsiam-install-packs
=> Add that upload to marketplace-v2 dependents xsiam-install-packs

Packs/AWS-SecurityHub/ReleaseNotes/1_1_16.md, Packs/ActiveMQ/ReleaseNotes/1_1_0.md, Packs/Base/ReleaseNotes/1_30_8.md, Packs/CommonScripts/ReleaseNotes/1_6_63.md, Packs/CommonScripts/ReleaseNotes/1_6_65.md, Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_0_1.md, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_8_0.md, Packs/PrismaCloud/ReleaseNotes/2_0_9.md, Packs/ProofpointTAP/ReleaseNotes/1_1_15.md, Packs/RSANetWitness_v11_1/ReleaseNotes/3_0_0.md, Packs/SplunkPy/ReleaseNotes/2_4_3.md, Packs/qualys/ReleaseNotes/1_0_19.md
RN's was reverted to old correct format
=> RN's was reverted to old correct format

Packs/ARIAPacketIntelligence/.pack-ignore, Packs/Camlytics/.pack-ignore, Packs/CiscoWSA/.pack-ignore, Packs/DomainTools/.pack-ignore, Packs/DomainTools_Iris/.pack-ignore, Packs/Giphy/.pack-ignore, Packs/TheHiveProject/.pack-ignore, Packs/Zabbix/.pack-ignore, Packs/opswat-metadefender/.pack-ignore
Due to adding a new validation, adding the new error to the .ignore file of these packs to make sure the build won't fail until  we fix the errors (I will open a new issue for it)
=> Adding the new IN153 error code to the .ignore file of packs

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml, Packs/CortexXDR/ReleaseNotes/4_5_1.md, Packs/CortexXDR/ReleaseNotes/4_5_2.md, Packs/CortexXDR/pack_metadata.json
=> XDR credentials regression fix

Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_description.md, Packs/FeedRSS/ReleaseNotes/1_0_5.md, Packs/FeedRSS/pack_metadata.json
added two panw feed examples
Updates the Integration example md file with two examples from PANW services that use RSS (Unit42 and Status pages)
=> updates to FeedRSS examples

Packs/Intezer/Integrations/IntezerV2/IntezerV2.py, Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml, Packs/Intezer/Integrations/IntezerV2/IntezerV2_test.py, Packs/Intezer/ReleaseNotes/1_3_2.md, Packs/Intezer/pack_metadata.json
=> Fix: Intezer URL analysis indicators parsing

Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper.json, Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper_6.5.json, Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_1.md, Packs/CrowdStrikeFalcon/pack_metadata.json
=> CS mapper fix

dev-requirements-py3.txt
=> switch to 1.6.7

Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_3_0.md, Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryParse/README.md, Packs/MalwareInvestigationAndResponse/Scripts/InvestigationDetailedSummaryToTable/README.md
=> Fixes to readme

Packs/CrowdStrikeFalcon/README.md
=> Readme fix

Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_4_0.md, Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/README.md, Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/ReadNetstatFileWrapper.py, Packs/MalwareInvestigationAndResponse/Scripts/ReadNetstatFileWrapper/ReadNetstatFileWrapper.yml, Packs/MalwareInvestigationAndResponse/pack_metadata.json
[CIAC-2988](https://jira-hq.paloaltonetworks.local/browse/CIAC-2988)
=> NetstatWrapper

Packs/RedHat/ModelingRules/RedHatEventsCollectorBrokerVM/RedHatEventsCollectorBrokerVM.xif, Packs/RedHat/ModelingRules/RedHatEventsCollectorXDRC/RedHatEventsCollectorXDRC.xif
Fixes the timestamp calculation.
=> Fix timestamp year

Packs/Axonius/Integrations/Axonius/Axonius.yml, Packs/Axonius/pack_metadata.json
=> Docker version bump 1.0.0.28931

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py, Packs/MicrosoftGraphMail/ReleaseNotes/1_1_17.md, Packs/MicrosoftGraphMail/pack_metadata.json
Fixed an issue in **fetch-incidents** where some mails weren't fetched.
=> [Microsoft Graph] Fix Missing Mails During Fetch

Packs/ProofpointTAP/ReleaseNotes/1_1_15.md
The version is not working because of the change of the incident field
=> Update the RN of ProofPoint

Packs/CommonScripts/ReleaseNotes/1_6_69.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
Updated the docker image of ParseEmailFilesV2 to the latest docker image to support french letters in an email's body.
=> ParseEmailFilesV2  - French letters fix

Packs/ProofpointTAP/IncidentFields/incidentfield-ProofPointTAP_Subject.json, Packs/ProofpointTAP/ReleaseNotes/1_1_16.md, Packs/ProofpointTAP/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-12860
Proofpoint revert incident field type
=> Proofpoint revert incident field type

Packs/Syslog/Integrations/Syslogv2/README.md
fixes: https://github.com/demisto/etc/issues/46046
=> Syslog Readme Troubleshoot update

Packs/RedHat/README.md, Packs/RedHat/pack_metadata.json
=> Red Hat pack metadata files

Packs/Base/ReleaseNotes/1_30_11.md, Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py, Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml, Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships_test.py, Packs/Base/pack_metadata.json
=> remove "filter" object key

Packs/Unit42Intel/Integrations/FeedUnit42IntelObjects/FeedUnit42IntelObjects_description.md, Packs/Unit42Intel/ReleaseNotes/1_0_3.md, Packs/Unit42Intel/pack_metadata.json
N/A
Previously, the in-product Help pane did not make it clear that TIM customers (as of XSOAR v6.5+) do NOT need to enter a Unit 42 API key to get this integration to work, leading to confusion. Updated Help to state this clearly.
N/A
=> Update integrate Help file

Packs/Oracle/README.md
Adds a description for configuring a non-integration XSIAM collector.
=> Update Oracle Pack Readme

Packs/MySQLEnterprise/README.md
Adds a description for configuring non-integration event collectors.
=> MySQL Enterprise Pack Readme Update

Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py, Packs/GitHub/ReleaseNotes/2_0_3.md, Packs/GitHub/pack_metadata.json, Packs/PhishLabs/Integrations/PhishLabsIOC/PhishLabsIOC.py, Packs/PhishLabs/ReleaseNotes/1_1_10.md, Packs/PhishLabs/pack_metadata.json, dev-requirements-py3.txt
The commit is the latest commit of 1.6.7 demisto-sdk branch.
=> demisto-sdk lint hotfix

Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml, Packs/Phishing/ReleaseNotes/3_2_2.md, Packs/Phishing/pack_metadata.json, Tests/conf.json
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3047
- Fixed an issue where Phishing URL Detection failed when Rasterize was disabled
- Added Rasterize to the `Phishing v3 - DomainSquatting+EML+MaliciousIndicators - Test` test
6.1.0
No
@yguezpa @erezh31 you can follow this PR for progress
=> fix for pb and added rasterize to test

Packs/CrowdStrikeFalconX/README.md
Create pack readme for Crowdstrike Falcon X. This information will appear in Marketplace.
=> Create pack readme for Crowdstrike Falcon X

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py, Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml, Packs/CortexXDR/ReleaseNotes/4_6_3.md, Packs/CortexXDR/pack_metadata.json
=> Ne xdr prevent only mode

Packs/Securonix/README.md, Packs/Securonix/ReleaseNotes/1_1_12.md, Packs/Securonix/pack_metadata.json
=> Securonix Pack Adoption

Packs/PhishingAlerts/README.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-3103
Added that the Phishing content pack is required for this pack and removed the screenshot of the playbook since this is no longer a suggested addition to the pack readmes.
=> Add that Phishing pack is required for Phishing Alerts pack

Packs/MalwareInvestigationAndResponse/ReleaseNotes/1_5_3.md, Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.py, Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable.yml, Packs/MalwareInvestigationAndResponse/Scripts/InvestigationSummaryToTable/InvestigationSummaryToTable_test.py, Packs/MalwareInvestigationAndResponse/pack_metadata.json
[CIAC-2928](https://jira-hq.paloaltonetworks.local/browse/CIAC-2928)
=> Add MalwareInvestigationToTable `Waiting on entries` message

dev-requirements-py3.txt
=> switch dep

Packs/Recorded_Future/ReleaseNotes/1_1_5.md, Packs/Recorded_Future/Scripts/script-RecordedFutureDomainRiskList.yml, Packs/Recorded_Future/Scripts/script-RecordedFutureHashRiskList.yml, Packs/Recorded_Future/Scripts/script-RecordedFutureIPRiskList.yml, Packs/Recorded_Future/Scripts/script-RecordedFutureURLRiskList.yml, Packs/Recorded_Future/Scripts/script-RecordedFutureVulnerabilityRiskList.yml, Packs/Recorded_Future/pack_metadata.json
=> Fix recorded future

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13413)
Update the `cs-falcon-batch-upload-custom-ioc` command in the readme.
The `multiple_indicators_json` arg should be used with backticks.
=> update CS Falcon README.md

Packs/RSANetWitness_v11_1/README.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-2843?jql=project%20in%20(XDR%2C%20CIAC%2C%20XDRSUP)%20AND%20assignee%20in%20(sdenkberg)
Create content for RSAWitness pack readme. This content will appear in Marketplace.
=> Create content for RSAWitness pack readme

.circleci/config.yml, .gitlab/ci/global.yml, .hooks/bootstrap, poetry.lock, pyproject.toml
=> Build extras

.circleci/config.yml, .gitlab/ci/global.yml
Now when we are on poetry we would like to check the poetry files
=> is file up to date change to poetry

Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json, Packs/CortexXDR/ReleaseNotes/4_6_4.json, Packs/CortexXDR/ReleaseNotes/4_6_4.md, Packs/CortexXDR/pack_metadata.json
=> Cortex XDR - Classifier's id bug fix

Packs/Cymulate/.pack-ignore
accidentally excluded this classifier in https://github.com/demisto/content/pull/19633
=> added BA101 to pack ignore

.github/workflows/run-secrets-detection.yml, .github/workflows/trigger-contribution-build.yml
Fixing permission error when running `poetry run`
=> trigger contrib fix

Packs/Cofense-Intelligence/pack_metadata.json, Packs/Expanse/pack_metadata.json, Packs/FeedMalwareDomainList/pack_metadata.json, Packs/Jask/pack_metadata.json, Packs/Traps/pack_metadata.json
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-2987
=> Hide packs - phase 1

Packs/Oracle/README.md
Update the pack README to include database collector-specific info.
=> Update Oracle DB Pack README

poetry.lock, pyproject.toml
related to: https://github.com/demisto/demisto-sdk/commit/23a8b4bea77bd09519b65bb28bd9df0090814813
=> update poetry - new sdk hotfix

Tests/scripts/wait_in_line_for_xsiam_env.sh
=> little fixes

Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.py, Packs/PrismaSaasSecurity/ReleaseNotes/2_0_3.md, Packs/PrismaSaasSecurity/pack_metadata.json
Remove un-relevant logging SaaS Security
=> Remove un-relevant logging SaaS Security

Packs/Traps/Playbooks/playbook-Block_File_-_Quarantine_-_Traps.yml, Packs/Traps/Playbooks/playbook-Isolate_Endpoint_-_Traps.yml, Packs/Traps/Playbooks/playbook-Traps_Blacklist_File.yml, Packs/Traps/Playbooks/playbook-Traps_Retrieve_And_Download_Files.yml, Packs/Traps/Playbooks/playbook-Traps_Scan_Endpoint.yml, Packs/Traps/ReleaseNotes/1_0_11.md, Packs/Traps/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/CIAC-2987
add ```deprecated: true``` to traps playbooks
=> Deprecate traps playbooks

Packs/AzureLogAnalytics/README.md
https://github.com/demisto/etc/issues/46718
Create pack readme for Azure Log Analytics. This content will appear in Marketplace.
=> Create pack readme for Azure Log Analytics

Tests/configure_and_test_integration_instances.py
=> fixed url parsing

Packs/EmailCommunication/pack_metadata.json
=> email comm - add video

Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
Fix markdown issues in `Prisma Cloud Compute`
=> fix markdown of prisma-cloud-compute README

Packs/EDL/Integrations/EDL/README.md
fix: https://github.com/demisto/content-docs/issues/1135
=> EDL - Add communitynotes to exportable

Packs/Carbon_Black_Enterprise_Live_Response/ReleaseNotes/1_1_4.md, Packs/Carbon_Black_Enterprise_Live_Response/Scripts/CBLiveProcessList/CBLiveProcessList.yml, Packs/Carbon_Black_Enterprise_Live_Response/pack_metadata.json
Deprecated this script due to the usage of deprecated integration commands.
=> Deprecating cb live process list script

Packs/UrlScan/ReleaseNotes/1_1_23.md, Packs/UrlScan/Scripts/UrlscanGetHttpTransactions/UrlscanGetHttpTransactions.yml, Packs/UrlScan/pack_metadata.json
Deprecated this script due to the usage of multiple irreplaceable deprecated integration commands.
=> Deprecating urlscan get http transactions script

Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py, Packs/Malwarebytes/ReleaseNotes/1_1_8.md, Packs/Malwarebytes/pack_metadata.json
=> [malwarebytes-254] Fixed an issue with ***!malwarebytes-list-endpoint-info*** command

Packs/TOPdesk/.pack-ignore
=> ignore error

Packs/ProtectWise/ReleaseNotes/1_0_5.md, Packs/ProtectWise/Scripts/PWEventPcapDownload/PWEventPcapDownload.py, Packs/ProtectWise/Scripts/PWObservationPcapDownload/PWObservationPcapDownload.py, Packs/ProtectWise/pack_metadata.json
Added skip to lint's sleep error.
=> Add sleep ignore to protect wise scripts

Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py, Packs/Malwarebytes/ReleaseNotes/1_1_8.md, Packs/Malwarebytes/pack_metadata.json
manual internal PR for the contribution https://github.com/demisto/content/pull/19812/files
=> internal PR for MalwareBytes contribution

Tests/Marketplace/upload_packs.py
[successful test
](https://code.pan.run/xsoar/content/-/jobs/14139427)
=> Removing the filter by marketplace for the upload that runs in the build

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py, Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/ReleaseNotes/1_3_2.md, Packs/Core/pack_metadata.json
fixes nightly: https://code.pan.run/xsoar/content/-/jobs/14241489
=> Fix cortexCoreIR

Packs/HashiCorp-Vault/.pack-ignore, Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py, Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml, Packs/HashiCorp-Vault/ReleaseNotes/1_0_8.md, Packs/HashiCorp-Vault/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-662)
Added the `namespace` parameter.
=> HashiCorp Vault - Add namespace param

Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml, Packs/CommonPlaybooks/ReleaseNotes/2_2_6.md, Packs/CommonPlaybooks/pack_metadata.json
=> File case fixing

Packs/Cherwell/Integrations/Cherwell/Cherwell.py, Packs/Cherwell/Integrations/Cherwell/Cherwell.yml, Packs/Cherwell/ReleaseNotes/1_0_12.md, Packs/Cherwell/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14035
=> Cherwell download attachments bug fix

Packs/CommonScripts/TestPlaybooks/playbook-Test-IPIndicatorFields.yml
Added a sleep step to the playbook so the indicator can be fetched properly.
=> Added a sleep step to playbook

Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py
=> changing params function in demisto

Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.py, Packs/FeedRSS/Integrations/FeedRSS/FeedRSS.yml, Packs/FeedRSS/Integrations/FeedRSS/FeedRSS_test.py, Packs/FeedRSS/ReleaseNotes/1_0_8.md, Packs/FeedRSS/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13928)
- Call `_http_request` method with the `full_url` argument to avoid adding a trailing / to the provided URL.
- Use `dateparser.parse` instead of `email.utils.parsedate`
=> RSS Feed - Fixed an issue in the RSS URL formatting

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py, Packs/TrendMicroVisionOne/ReleaseNotes/1_2_0.md, Packs/TrendMicroVisionOne/pack_metadata.json
Per customer request we have added the ability to use the system proxy for communication with the Trend Micro Vision One APIs from our integration
=> Added system proxy configuration option

.hooks/bootstrap, poetry.lock, poetry.toml, pyproject.toml
=> poetry update (release SDK)

Packs/CommonScripts/ReleaseNotes/1_7_14.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
=> Moved ParseEmailFilesV2 from beta to GA.

poetry.lock, pyproject.toml
Changing SDK to point at this commit - https://github.com/demisto/demisto-sdk/commit/f736d5e2bd0d96fbf924edee21105282a0cfe2f0
=> update pyproject.tml to use a specific revision of demiso-sdk

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- Image updated to the latest dependencies including sdk 1.7.0
- Use the same image tag that we will no longer need to update the dockerfile in the future.
- Added powershell to the container.
- Run poetry install after creating the container to update the dependencies if the preinstalled dependencies are outdated
=> devcontainer to latest sdk + powershell

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/README.md, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.yml, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne_test.py, Packs/TrendMicroVisionOne/ReleaseNotes/1_2_2.md, Packs/TrendMicroVisionOne/pack_metadata.json
- Added ability to skip certificate validation
=> Config option to disable cert validate

Packs/DuoAdminApi/ModelingRules/DuoModelingRule/DuoModelingRule.xif, Packs/DuoAdminApi/ReleaseNotes/3_0_1.md, Packs/DuoAdminApi/pack_metadata.json
=> Added filter to the mapping rules

Packs/CommonScripts/ReleaseNotes/1_7_15.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
Updated docker image to the latest image.
=> ParseEmailFilesV2 Update Docker Image

Packs/FeedMitreAttack/pack_metadata.json, Packs/LogRhythm/pack_metadata.json, Packs/McAfee_ESM-v10/pack_metadata.json, Packs/MicrosoftPolicyAndCompliance/pack_metadata.json, Packs/Recorded_Future/pack_metadata.json
relates to: https://jira-hq.paloaltonetworks.local/browse/CIAC-2987
https://github.com/demisto/content/pull/19636
=> hide deprecated non relevant packs

Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py, Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml, Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs_test.py, Packs/CortexXDR/ReleaseNotes/4_8_3.md, Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14721.
memory issues and performance improvements.
added batching mechanism for indicator pushing the effect is:
- less memory usage.
- smaller requests.
=> batch iocs in tim insert json xdr ioc

Tests/conf.json
skip pan-os 8.1 test playbooks
=> skip pan-os 8.1 test playbooks

Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_9.md
=> Fix malformed release notes - CrowdStrikeFalcon

Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py
fixes: failing unit tests
related: https://github.com/demisto/content/pull/20144
importing the `test_module` function in the unit-test file caused pytest to collect it as a unit-test.
=> fix SEKOIAIntelligenceCenter unit tests

Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py, Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml, Packs/GooglePubSub/ReleaseNotes/1_0_17.md, Packs/GooglePubSub/pack_metadata.json
related: https://jira-hq.paloaltonetworks.local/browse/XSUP-14210
customer confirm that this solution fixed the issue and pulled all incidents. 
The issue with the fetch-incidents timing is still "in progress" by the  platform team.
@dansterenson 
=> Google pubsub fix

Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch/BrocadeSwitch.xif, Packs/BrocadeSwitch/ReleaseNotes/1_0_1.md, Packs/BrocadeSwitch/pack_metadata.json, Packs/Infoblox/ModelingRules/Infoblox/Infoblox.xif, Packs/Infoblox/ReleaseNotes/1_0_10.md, Packs/Infoblox/pack_metadata.json, Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS/MicrosoftADFS.yml, Packs/MicrosoftADFS/ReleaseNotes/1_0_1.md, Packs/MicrosoftADFS/pack_metadata.json, Packs/MicrosoftIISWebServer/README.md
=> fix_adfs_yml

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py, Packs/CortexXDR/ReleaseNotes/4_8_4.md, Packs/CortexXDR/pack_metadata.json
Added a new entry to the XDR_RESOLVED_STATUS_TO_XSOAR.
=> Cortex xdrir add on

poetry.lock, pyproject.toml
=> For release SDK 1.7.1

Packs/Base/ReleaseNotes/1_31_11.md, Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml, Packs/Base/pack_metadata.json, Packs/ML/ReleaseNotes/1_4_3.md, Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml, Packs/ML/pack_metadata.json
=> Update docker imange for ml docker

Packs/Oletools/README.md, Packs/Oletools/Scripts/OletoolsScript/README.md, Packs/Oletools/pack_metadata.json
- Fixing a typo in the description
- Changing the playbook image in the README file
- Changing the version in the script readme.
=> Oletools fixes

Packs/Okta/TestPlaybooks/OktaV2-Test.yml
=> [Okta v2] Add test for okta-list-users and okta-list-zones in TestPlaybook

Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2.yml, Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2_6_0.yml, Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2_6_1.yml, Packs/CommonPlaybooks/ReleaseNotes/2_2_11.md, Packs/CommonPlaybooks/pack_metadata.json
Fixed an issue where the "Only EWS enabled" condition fails to match
- [x ] No
=> Common delete email playbook

Packs/Respond/pack_metadata.json
Finish rebranding of Respond Analysis Pack to Mandiant.
=> Change Pack branding to Mandiant Automated Defense

Packs/FortiGate/ModelingRules/FortiGate/FortiGate.xif, Packs/FortiGate/ModelingRules/FortiGate/FortiGate.yml, Packs/FortiGate/ModelingRules/FortiGate/FortiGate_schema.json, Packs/FortiGate/README.md, Packs/FortiGate/ReleaseNotes/1_0_8.md, Packs/FortiGate/pack_metadata.json, Tests/known_words.txt
AccessdataV2 package to integrate with the AccessData platform enabling the automation of case/evidence management and endpoint collection.
- [ x] 6.0.0
- [ x] No
- [x ] Tests
- [x ] Documentation
=> Access data v2

Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml, Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_description.md, Packs/FeedTAXII/ReleaseNotes/1_1_9.md, Packs/FeedTAXII/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-60421
the detailed description is side-by-side and not behind a "?" button.
=> Taxii 2 Feed: Fix the display of the credentials parameter

Packs/VirusTotal/Playbooks/Detonate_File_-_VirusTotal_V3.yml, Packs/VirusTotal/ReleaseNotes/2_4_6.md, Packs/VirusTotal/pack_metadata.json
[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-59907)
related PR: https://github.com/demisto/content/pull/20274
Fix virus total DT , the playbook was completed early before completing the scan
=> fix VT detonate file DT

Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.py, Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml, Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_1_2.md, Packs/Cybersixgill-ActionableAlerts/pack_metadata.json
=> [195-sixgill] Adding the fetch_only_current_item to actionable alert content API

.gitlab/ci/on-push.yml, Tests/scripts/collect_tests/path_manager.py
skip test collector's test files
=> skip test files

Packs/PrismaCloud/Integrations/RedLock/README.md, Packs/PrismaCloud/Integrations/RedLock/RedLock.py, Packs/PrismaCloud/Integrations/RedLock/RedLock.yml, Packs/PrismaCloud/ReleaseNotes/2_0_15.md, Packs/PrismaCloud/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13528
Added the `limit` argument to limit the results.
Added the `cloud-account-id` filter to filter by the account ID and avoid confusion with the `cloud-account` filter.
=> RedLock: Fix search command

Packs/FortiGate/ModelingRules/FortiGate/FortiGate_schema.json, Packs/FortiGate/ReleaseNotes/1_0_9.md, Packs/FortiGate/pack_metadata.json
fixes: Changed type of dhost field in scheme
Edited the type followind the last PR.
=> Changed type of dhost in scheme

Packs/CortexXDR/IndicatorFields/incidentfield-xdrstatus.json, Packs/CortexXDR/ReleaseNotes/4_8_9.md, Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-60478
Fixed a typo in the predefined values.
=> XDR status: fix typo

Packs/CybleEvents/ReleaseNotes/1_0_3.md, Packs/CybleEvents/pack_metadata.json
Removed uncceasry rn from cybleEvents
=> remove release notes from cybleEvents

Packs/PrismaAccess/Integrations/PrismaAccess/README.md
fixes: https://panw-global.slack.com/archives/C01225PADU1/p1659961564116609
Added deprecated note to deprecated commands
=> Added deprecated note to docs

Packs/iDefense/Integrations/FeediDefense/FeediDefense.yml, Packs/iDefense/Integrations/iDefense_v2/iDefense_v2.yml, Packs/iDefense/ReleaseNotes/3_2_5.md, Packs/iDefense/TestPlaybooks/Feed_iDefense_Test.yml, Packs/iDefense/TestPlaybooks/iDefense_v2-Test.yml, Packs/iDefense/pack_metadata.json
We are ready to deprecate our older pack Accenture CTI  ( _formerly iDefense_)
=> Initiating deprecation of iDefense pack

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/test_collect_tests.py
=> TestCollection: use `find_type` instead of `find_type_by_path`

Tests/scripts/collect_tests/collect_tests.py
=> TestCollect: better `git diff` logs

Utils/github_workflow_scripts/handle_external_pr.py
Changed the reviewer's names to the new team members.
=> Updated the contributions reviewers names

Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py, Packs/HelloWorld/Scripts/HelloWorldScript/HelloWorldScript.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3792
Fixed docstrings of hello world to Google standards
=> Fixed docstrings

Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py, Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2_test.py, Packs/McAfee_ESM/ReleaseNotes/1_1_23.md, Packs/McAfee_ESM/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13024
improved the test module validations.
=> Update McAfee ESM test module

Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py, Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml, Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity_test.py, Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md, Packs/AbnormalSecurity/Integrations/AbnormalSecurity/command_examples, Packs/AbnormalSecurity/ReleaseNotes/1_1_5.md, Packs/AbnormalSecurity/ReleaseNotes/1_1_6.md, Packs/AbnormalSecurity/pack_metadata.json
- nil -
- Bug fixes for command `!abnormal-security-get-employee-identity-analysis`
- Deprecate command `!abnormal-security-submit-inquiry-to-request-a-report-on-misjudgement`
- Added new commands `!abnormal-security-submit-false-positive-report` and `!abnormal-security-submit-false-negative-report`
- Updated Abnormal Security Image
=> Abnormal Security 1.1.6

Packs/EWS/Integrations/EWSv2/EWSv2.py, Packs/EWS/ReleaseNotes/1_12_5.md, Packs/EWS/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/CIAC-2611
=> Add fetch history EWSv2

Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py, Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml, Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_test.py, Packs/TAXIIServer/ReleaseNotes/2_0_11.md, Packs/TAXIIServer/pack_metadata.json
Returning 406 on invalid headers
closes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15403
=> TAXII2: return 406 on version mismatch

Packs/AzureActiveDirectory/pack_metadata.json
=> Azure identity display and desc fix

Packs/ArcSightLogger/Integrations/ArcSightLogger/ArcSightLogger.js, Packs/ArcSightLogger/ReleaseNotes/1_0_6.md, Packs/ArcSightLogger/pack_metadata.json
fixes: [CIAC-3815](https://jira-hq.paloaltonetworks.local/browse/CIAC-3815)
Added the advanced feature fetch-history to the fetch-incident command in ArcSight Logger integration.
=> [ArcSight Logger] - Added fetch history

Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.py, Packs/mnemonicMDR/ReleaseNotes/1_1_7.md, Packs/mnemonicMDR/pack_metadata.json
A very small update to hotfix how XSOAR does mirroring. 
- Note that I did this manually as `demisto-sdk update-release-notes` did not see any changes?
=> Mnemonic mdr

Tests/Marketplace/upload_packs.py, Tests/private_build/tests/test_upload_packs_private.py, Tests/private_build/upload_packs_private.py
Added the disableMonthly key to the index.json
https://jira-hq.paloaltonetworks.local/browse/CRTX-61514
=> Added contentCommitHash to metadata

Tests/scripts/utils/get_modified_files_for_testing.py
=> Fix import to CONF_JSON

Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py, Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_1_2.md, Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-15505
=> Filter fix

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
added some important notes about the messaging endpoint and certificate
@yaakovi @avidan-H FYI
=> 📝 Microsoft Teams - add important notes to README

Packs/SafeBreach/README.md
fixes: CIAC-3849
They moved the video to YT.
=> Fix the demo link - SafeBreach

Packs/AzureSQLManagement/README.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-3693
Create content for the pack readme.  This content will appear in Marketplace.
=> Create content for the pack readme

Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Host_Advanced_Hunting_For_Persistence.yml, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_11_10.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3846)
In the conditional tasks, I corrected the context path to be more accurate for the tagging tasks.
N.a.
=> Mde fixes- Context Paths on advanced hunting queries

Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/README.md
fixes: XSUP-15703
Added information regarding the need to increment the version of custom content.
=> Add PSA to Demisto REST API integration re: versions.

Packs/Phishing/ReleaseNotes/3_3_0.md
fixes: NA
Elaborating more on the changes being done in the 3.3.0 version.
N.A.
=> Update  Phishing RN 3.3.0

Packs/Phishing/ReleaseNotes/3_3_0.md
=> Phishing RN 3.3.0 fixes

Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
=> Fix broken master

Packs/CheckPointSandBlast/pack_metadata.json, Packs/SandBlastAppliance/Integrations/CheckPointSandblastAppliance/CheckPointSandblastAppliance.yml, Packs/SandBlastAppliance/ReleaseNotes/1_0_2.md, Packs/SandBlastAppliance/pack_metadata.json, Packs/Sandblast/Integrations/CheckPointSandblast/CheckPointSandblast.yml, Packs/Sandblast/ReleaseNotes/1_0_8.md, Packs/Sandblast/TestPlaybooks/playbook-Sandblast_malicious_test.yml, Packs/Sandblast/pack_metadata.json
=> Deprecate old sandblast integrations

Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_False_Positive_Incident_Handling.yml, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_12_1.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3892)
Changed the `indicatorsValues` input in the 'Tag Indicators' task:
**From** `${Indicators to Block.Questions.0}` **to** `${Indicators to Allow.Answers.0}`.
N.a.
=> [Bug fix ] - An issue in the 'MDE - False Positive Incident Handling'  

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/utils.py, Tests/scripts/infrastructure_tests/test_collect_tests.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Packs/myXSOAROnlyPack/TestPlaybooks/myOtherTestPlaybook.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Packs/myXSOAROnlyPack/TestPlaybooks/myTestPlaybook.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Packs/myXSOAROnlyPack/pack_metadata.json, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Tests/conf.json, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M/Tests/id_set.json
add condition 3 to the error raised when
```
(1) missing from conf.json  AND  (2) does not explicitly state `tests: no tests`  AND (3) has support level xsoar
```
to handle cases where partner/community-level packs [fail](https://code.pan.run/xsoar/content/-/pipelines/3552647)
=> only raise error on support_level == xsoar

Packs/AzureDevOps/README.md
Done.
https://github.com/demisto/content/pull/20664
Updated pack readme content.  This content will appear in Marketplace.
=> Update Pack README

Packs/Elasticsearch/README.md
https://github.com/demisto/content/pull/20310
Create content for the Elasticsearch Content Pack. This content will appear in Marketplace.
=> Create content for the Elasticsearch Content Pack

Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js, Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.yml, Packs/Remedy-On-Demand/ReleaseNotes/1_0_6.md, Packs/Remedy-On-Demand/ReleaseNotes/1_1_0.md, Packs/Remedy-On-Demand/pack_metadata.json
- improved test_module when there are too many remedy incidents
- 
=> Randomizerxd-contrib-Remedy-On-Demand

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/exceptions.py, Tests/scripts/collect_tests/id_set.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/A_xsiam/Packs/myXSIAMOnlyPack/Integrations/myIntegration/myIntegration.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/L_XSIAM/Packs/myXSIAMOnlyPack/Wizards/harry.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3929
=> TestCollect: filter-in xsiam-only content on branches

Tests/configure_and_test_integration_instances.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3927
=> do not `test-module` all tests if none are collected

Tests/scripts/collect_tests/path_manager.py
=> TestCollect: remove spammy debug log

.gitlab/ci/on-push.yml
fail build on collection errors
=> TestCollect: fail build when failing

.github/CODEOWNERS
=> Deprecate @bakatzir from CODEOWNERS

Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty_description.md
- [x ] Ready
We want to keep the information generic, so removed reference to XSOAR.
=> Removed reference to XSOAR

Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.py, Packs/AzureStorage/Integrations/AzureStorage/AzureStorage.yml, Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_description.md, Packs/AzureStorage/Integrations/AzureStorage/AzureStorage_test.py, Packs/AzureStorage/Integrations/AzureStorage/README.md, Packs/AzureStorage/ReleaseNotes/1_1_0.md, Packs/AzureStorage/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3694)
Add support for Authorization code flow
=> AzureStorage add auth code flow

Tests/scripts/collect_tests/collect_tests.py
closes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3949
=> TestCollect: validate pack marketplaces on XSIAM

Packs/RecordedFutureASI/Integrations/RecordedFutureASI/RecordedFutureASI_test.py
fixes: https://code.pan.run/xsoar/content/-/jobs/16090240
Quilk fix to build failure.
=> Recorded future quick fix

Packs/Jira/Integrations/JiraV2/README.md
N/A
Incorporate docs feedback from a customer who set up the integration with Jira Data Center using basic auth.
N/A
=> Update README auth details

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/test_conf.py, Tests/scripts/infrastructure_tests/test_collect_tests.py
- checking for ignored files earlier in the process
- better code readability
- a bit more debug logs
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3946
=> TestCollect: change ignore order

Packs/CreateHash/ReleaseNotes/1_0_2.md, Packs/CreateHash/Scripts/CreateHash/CreateHash.py, Packs/CreateHash/Scripts/CreateHash/CreateHash.yml, Packs/CreateHash/Scripts/CreateHash/README.md, Packs/CreateHash/pack_metadata.json
=> Add sha512 support as per customer's requirement

Packs/Slack/Integrations/SlackV3/SlackV3.py, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/ReleaseNotes/3_1_1.md, Packs/Slack/pack_metadata.json
fixes: XSUP-16239
Adds an additional log line for send-notification
=> SlackV3 add debug severity log line

Packs/RegexReplace/ReleaseNotes/1_0_2.md, Packs/RegexReplace/Scripts/RegexReplace/README.md, Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.py, Packs/RegexReplace/Scripts/RegexReplace/RegexReplace.yml, Packs/RegexReplace/Scripts/RegexReplace/RegexReplace_test.py, Packs/RegexReplace/Scripts/RegexReplace/test_data/test-1.json, Packs/RegexReplace/pack_metadata.json
N/A
Supported some regex matching options: re.MULTILINE and re.DOTALL, and also added a feature to transform each output value with DT.
=> Added *multi_line*, *period_matches_newline* and *action_dt* parameters.

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/exceptions.py, Tests/scripts/collect_tests/utils.py, Tests/scripts/infrastructure_tests/test_collect_tests.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/Integrations/myIntegration/myIntegration.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/TestPlaybooks/myOtherTestPlaybook.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/TestPlaybooks/myTestPlaybook.yml, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Packs/myXSOAROnlyPack/pack_metadata.json, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Tests/conf.json, Tests/scripts/infrastructure_tests/tests_data/collect_tests/M3/Tests/id_set.json
solves: https://jira-hq.paloaltonetworks.local/browse/CIAC-3976
=> ignore non-xsoar-support packs in branch collections

Packs/HelloWorld/ReleaseNotes/1_2_13.md, Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_description.md, Packs/StarterPack/ReleaseNotes/1_0_9.md, Packs/StarterPack/pack_metadata.json
Needed for the demisto-sdk markdownlint tests
=> add spaces

Packs/PAN-OS/Integrations/Panorama/Panorama.py, Packs/PAN-OS/ReleaseNotes/1_14_18.md, Packs/PAN-OS/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15724
Fixed an issue where the **create-rule** commands ignored the arg *where*.
=> [PAN-OS] Add Move Rule Functionality to Add Rule Commands

Packs/Tenable_sc/Playbooks/playbook-tenable.sc-scan.yml, Packs/Tenable_sc/ReleaseNotes/1_0_7.md, Packs/Tenable_sc/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15985
Added the missing status to the generic polling subplaybook DT
=> Fix playbook tenable sc

.github/CODEOWNERS
Removing myself as a code owner for common packs.
=> Removing myself as a code owner for common packs.

Packs/AWS-IAM/Integrations/AWS-IAM/AWS-IAM.yml, Packs/AWS-IAM/ReleaseNotes/1_1_11.md, Packs/AWS-IAM/pack_metadata.json
=> 2to3 awsiam

Packs/CommonScripts/ReleaseNotes/1_7_28.md, Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.py, Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag.yml, Packs/CommonScripts/pack_metadata.json
=> bump 2to3 getdockertag

Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml, Packs/Tenable_sc/ReleaseNotes/1_0_8.md, Packs/Tenable_sc/pack_metadata.json
Force merge is needed:
[IN140] - The integration Tenable.sc is currently in skipped (unstable instance).
=> python2 EOL Tenable sc

Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py, Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml, Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems_test.py, Packs/IBMResilientSystems/Integrations/IBMResilientSystems/Pipfile, Packs/IBMResilientSystems/Integrations/IBMResilientSystems/Pipfile.lock, Packs/IBMResilientSystems/ReleaseNotes/1_1_0.md, Packs/IBMResilientSystems/pack_metadata.json
dockerfiles pr https://github.com/demisto/dockerfiles/pull/8520
=> 2to3 resilient

Packs/GRR/ReleaseNotes/1_0_7.md, Packs/GRR/Scripts/GrrGetFiles/GrrGetFiles.yml, Packs/GRR/Scripts/GrrGetFlows/GrrGetFlows.yml, Packs/GRR/Scripts/GrrGetHunt/GrrGetHunt.yml, Packs/GRR/Scripts/GrrGetHunts/GrrGetHunts.yml, Packs/GRR/Scripts/GrrSetFlows/GrrSetFlows.yml, Packs/GRR/Scripts/GrrSetHunts/GrrSetHunts.yml, Packs/GRR/pack_metadata.json
=> Grr scripts deprecate

Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_21.md, Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/CBFindIP.py, Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/CBFindIP.yml, Packs/Carbon_Black_Enterprise_Response/Scripts/CBFindIP/README.md, Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
=> CBFindIP - update to python 3.10

Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.py, Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.yml, Packs/AwakeSecurity/ReleaseNotes/1_0_12.md, Packs/AwakeSecurity/pack_metadata.json
=> Awake security python3

Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.yml, Packs/EWSMailSender/ReleaseNotes/1_1_13.md, Packs/EWSMailSender/pack_metadata.json
Integration is already using a py3 docker image. Fixed the subtype.
=> Ews Mail sender: subtype py3

Packs/FortiGate/Integrations/FortiGate/FortiGate.py, Packs/FortiGate/Integrations/FortiGate/FortiGate.yml, Packs/FortiGate/ReleaseNotes/1_0_11.md, Packs/FortiGate/pack_metadata.json
=> FortiGate --> PY3

Packs/SignalSciences/.pack-ignore, Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.py, Packs/SignalSciences/Integrations/SignalSciences/SignalSciences.yml, Packs/SignalSciences/ReleaseNotes/1_0_10.md, Packs/SignalSciences/pack_metadata.json
=> Signal Sciences WAF --> PY3

Packs/BigFix/Integrations/BigFix/BigFix.py, Packs/BigFix/Integrations/BigFix/BigFix.yml, Packs/BigFix/ReleaseNotes/1_0_9.md, Packs/BigFix/pack_metadata.json
=> BigFix --> PY3

Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.py, Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2.yml, Packs/PassiveTotal/ReleaseNotes/2_1_3.md, Packs/PassiveTotal/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-16291
Fixed an issue in **ip** command where passing a list of ips from the context caused the command to fail.
=> [PassiveTotal v2] Fix ip Command Handling of Lists

Packs/InfoArmor_VigilanteATI/.pack-ignore
Fixed the pack.ignore file of  InfoArmor_VigilanteATI.
=> Updated the Pack ignore file of InfoArmor_VigilanteATI

Packs/Phishing/ReleaseNotes/3_3_3.md, Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.yml, Packs/Phishing/Scripts/CheckEmailAuthenticity/README.md, Packs/Phishing/pack_metadata.json
=> Check email py3

Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py, Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml, Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid_test.py, Packs/ThreatGrid/ReleaseNotes/1_2_14.md, Packs/ThreatGrid/pack_metadata.json
No credentials - instance problem (issue 16197).
Force merge is needed ([IN140] - The integration Threat Grid is currently in skipped.)
=> python2 EOL Threat grid

Packs/ThreatX/Integrations/ThreatX/ThreatX.yml, Packs/ThreatX/ReleaseNotes/1_0_8.md, Packs/ThreatX/pack_metadata.json
=> Update threat x to python3

Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.yml, Packs/McAfee-MAR/ReleaseNotes/1_0_4.md, Packs/McAfee-MAR/pack_metadata.json
=> Mcafee mar - update to python 3

Packs/Stealthwatch_Cloud/.pack-ignore, Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py, Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.yml, Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_10.md, Packs/Stealthwatch_Cloud/pack_metadata.json
=> StealthWatch Cloud --> PY3

Packs/AttivoBotsink/Integrations/AttivoBotsink/AttivoBotsink.py, Packs/AttivoBotsink/Integrations/AttivoBotsink/AttivoBotsink.yml, Packs/AttivoBotsink/ReleaseNotes/1_0_9.md, Packs/AttivoBotsink/pack_metadata.json
=> Attivo Botsink --> PY3

Packs/Tanium/ReleaseNotes/1_0_18.md, Packs/Tanium/Scripts/TaniumFilterComputersByIndexQueryFileDetails/TaniumFilterComputersByIndexQueryFileDetails.yml, Packs/Tanium/pack_metadata.json
=> TaniumFilterComputersByIndexQueryFileDetails --> PY3

.gitlab/ci/slack-notify.yml
update dockerimage for slack-notify
=> fix slack notify

Packs/InfoArmor_VigilanteATI/.pack-ignore
fixes: [build](https://app.circleci.com/pipelines/github/demisto/content/189680/workflows/ae2181d3-d677-4818-aa54-e69b47a6b1e0/jobs/566602)
Ignoring IN145
=> InfoArmorVigilanteATI: Update .pack-ignore

poetry.lock, pyproject.toml
fixes: bug in BC checks
update SDK to use hotfix: https://github.com/demisto/demisto-sdk/pull/2320/commits/4f06d439255fc18583c19aa89a8d9ed45a9bcce2
=> Hotfix: demisto-sdk 1.7.4

Packs/CommonScripts/ReleaseNotes/1_7_37.md, Packs/CommonScripts/Scripts/JSONFileToCSV/JSONFileToCSV.py, Packs/CommonScripts/Scripts/JSONFileToCSV/JSONFileToCSV.yml, Packs/CommonScripts/Scripts/JSONFileToCSV/README.md, Packs/CommonScripts/pack_metadata.json
Migrate JSONFileToCSV from Python 2 to Python 3.
=> Migrate JSONFileToCSV to Python 3

Packs/EWS/ReleaseNotes/1_12_7.md, Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.py, Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery.yml, Packs/EWS/Scripts/BuildEWSQuery/BuildEWSQuery_test.py, Packs/EWS/pack_metadata.json
=> move BuildTWSQuery script to py3

Packs/Base/ReleaseNotes/1_31_21.md, Packs/Base/Scripts/CheckDockerImageAvailable/CheckDockerImageAvailable.py, Packs/Base/Scripts/CheckDockerImageAvailable/CheckDockerImageAvailable.yml, Packs/Base/Scripts/CheckDockerImageAvailable/README.md, Packs/Base/pack_metadata.json
Migrate CheckDockerImageAvailable Script from Python 2 to Python 3
=> Migrate CheckDockerImageAvailable Script to Python 3

.github/workflows/close_jira_issue_by_pr_merge.yml
Workflow fix 
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3473
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3475
related: https://github.com/demisto/content/pull/20255
=> fix jira_github workflow

Packs/CommonScripts/ReleaseNotes/1_7_40.md, Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.py, Packs/CommonScripts/Scripts/IndicatorMaliciousRatioCalculation/IndicatorMaliciousRatioCalculation.yml, Packs/CommonScripts/pack_metadata.json
=> IndicatorMaliciousRatioCalculation --> PY3

Packs/Gamma/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4085
Changed Gamma support to XSOAR
=> updated support for Gamma

Packs/ContentManagement/IncidentFields/incidentfield-S3BucketName.json, Packs/ContentManagement/Layouts/layoutscontainer-configuration_setup.json, Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml, Packs/ContentManagement/ReleaseNotes/1_1_2.md, Packs/ContentManagement/pack_metadata.json
Fix issues introduced in #20665 
=> Fix S3BucketName references after field renamed

Packs/Cybereason/Integrations/Cybereason/Cybereason.py, Packs/Cybereason/Integrations/Cybereason/Cybereason.yml, Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py, Packs/Cybereason/ReleaseNotes/1_0_22.md, Packs/Cybereason/pack_metadata.json
=> Cybereason --> PY3

Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py, Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml, Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_test.py, Packs/AWS-SecurityHub/ReleaseNotes/1_1_22.md, Packs/AWS-SecurityHub/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2611)
=> [AWS Security Hub] - Added support for fetch history

Tests/scripts/collect_tests/collect_tests.py, Tests/scripts/collect_tests/utils.py, Tests/scripts/infrastructure_tests/test_collect_tests.py, Tests/scripts/infrastructure_tests/tests_data/collect_tests/F/Packs/myPack/Scripts/script-myScript.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4062?filter=48080
=> TestCollect: detect old-format scripts

Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_1_3.md, Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.py, Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.yml, Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing_test.py, Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
=> CrowdStrikeStreamingPreProcessing --> PY3

Packs/EclecticIQ/Integrations/EclecticIQ/EclecticIQ.py, Packs/EclecticIQ/Integrations/EclecticIQ/EclecticIQ.yml, Packs/EclecticIQ/Integrations/EclecticIQ/EclecticIQ_test.py, Packs/EclecticIQ/ReleaseNotes/1_0_6.md, Packs/EclecticIQ/pack_metadata.json
=> EclecticIQ --> PY3

Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.py, Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2.yml, Packs/Cylance_Protect/Integrations/Cylance_Protect_v2/Cylance_Protect_v2_test.py, Packs/Cylance_Protect/ReleaseNotes/1_1_1.md, Packs/Cylance_Protect/pack_metadata.json
=> Cylance Protect v2 --> PY3

Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml, Packs/VirusTotal/ReleaseNotes/2_4_10.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Fix dbot score to return a valid score (NONE) when IoC is not found on VT

Packs/Campaign/TestPlaybooks/Phishing_Investigation_-_Generic_v2_-_Campaign_Test.yml, Packs/Phishing/Playbooks/playbook-Get_Original_Email_-_Generic_v2.yml, Packs/Phishing/ReleaseNotes/3_3_4.md, Packs/Phishing/pack_metadata.json, Tests/conf.json
Fix Phishing campaing test playbook.
=> Fix Phishing Campaign Test

Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall/CheckpointFirewall.xif, Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall/CheckpointFirewall.yml, Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall/CheckpointFirewall_schema.json, Packs/CheckpointFirewall/README.md, Packs/CheckpointFirewall/ReleaseNotes/2_3_2.md, Packs/CheckpointFirewall/pack_metadata.json
=> Add modeling rules to Checkpoint Firewall

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml
added `create-instances` job done test in `run-instances` stage.
=> added `create-instances` job done test in `run-instances` stage

Packs/AWS-GuardDuty/ModelingRules/AWSGuardDutyModelingRules/AWSGuardDutyModelingRules.xif, Packs/AWS-GuardDuty/ReleaseNotes/1_3_1.md, Packs/AWS-GuardDuty/pack_metadata.json
=> Guardduty xsiam fix

Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2159)
=> change Demisto REST API display name

Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_Malware_-_Investigation_And_Response.yml, Packs/CortexXDR/ReleaseNotes/4_8_16.md, Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4116
Cortex XDR playbook not handling 'Null' in CMD line analysis + Endpoint Investigation needs to receive only 1 agent id
N.a.a
=> Cortex xdr malware fix

Packs/Base/ReleaseNotes/1_31_22.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/pack_metadata.json
=> Added get_metric_list

.circleci/config.yml, .gitlab/ci/global.yml
=> fix cache issue with virtual env

Packs/Base/ReleaseNotes/1_31_23.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/pack_metadata.json
=> Add feed indicator type malware

Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py, Packs/Base/ReleaseNotes/1_31_24.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/pack_metadata.json, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py, Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/test_data/command_results.json
This PR adds the `Vendor` field as a key when comparing Endpoint objects if it exists.
=> Add Vendor as Key Field for CommonServerPython's Endpoint

Packs/CaseManagement-Generic/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-64010
=> case-management-not-xsiam

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, Tests/scripts/circleci_spell_checker.py
We need to initialize the docker daemon inside the container.
=> fix docker in docker in devcontainer

Packs/AWS-NetworkFirewall/pack_metadata.json
=> aws-network-firewall-pack-rename

Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4155)
Fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4154
- Add [link to issue] support to Jira-Github integration
- Fail the link PR to Jira action if no PRs found
- [n] No
=> Add `[link to issue]` support to Jira-Github integration

Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py, Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml, Packs/FeedUnit42v2/ReleaseNotes/1_0_15.md, Packs/FeedUnit42v2/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15359
=> Feed unit42v2 value bug fix

Utils/github_workflow_scripts/handle_external_pr.py
fixes: [](url)
Updated the contributions reviewers list. 
=> Updated the contributions reviewers list

Tests/conf.json
related to https://github.com/demisto/content/pull/21260
=> conf.json: Remove Splunk Sub Test Playbooks

Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
- [  ] In Progress
- [  ] In Hold - (Reason for hold)
=> Added supported versions to readme

.gitlab/ci/global.yml
=> coburtura change for testing

Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/README.md
=> ms-teams-md-fix

Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml, Packs/QRadar/ReleaseNotes/2_2_11.md, Packs/QRadar/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4192
Changed transformers to take the first start time (and also handle situations with only one event, not an array).
=> Qradar get offense logs fix start time

Packs/LogRhythmRest/pack_metadata.json
=> update pack name

Utils/github_workflow_scripts/handle_external_pr.py
=> update contrib team

Packs/ExtFilter/ReleaseNotes/1_1_12.md, Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.py, Packs/ExtFilter/Scripts/ExtFilter/ExtFilter.yml, Packs/ExtFilter/Scripts/ExtFilter/test_data/test-1.json, Packs/ExtFilter/pack_metadata.json, Packs/MapPattern/ReleaseNotes/1_0_7.md, Packs/MapPattern/Scripts/MapPattern/MapPattern.py, Packs/MapPattern/Scripts/MapPattern/MapPattern.yml, Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json, Packs/MapPattern/pack_metadata.json
N/A
Applied the latest DT parser which is used in `FormatTemplate` or `ConcatFormat` to the scripts since it has been improved to support nested DT expressions.
=> Improved the DT parser to support nested DT expressions

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-16641
Fixed the README file 
=> [CrowdStrike Falcon] Fix integration README file

Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py, Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml, Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py, Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_12.md, Packs/CrowdStrikeFalconX/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-16742
Fix an issue where IOC artifacts of png images weren't parsed correctly.
=> Crowdstrike FalconX Fix png Download

Packs/Zendesk/.pack-ignore
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4264
=> fix .pack-ignore file

Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py, Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml, Packs/Zendesk/ReleaseNotes/2_0_1.md, Packs/Zendesk/pack_metadata.json
fixes [this failure](https://code.pan.run/xsoar/content/-/jobs/17217324)
nightly build https://code.pan.run/xsoar/content/-/pipelines/3800017
=> fix import bug

Packs/PrismaCloud/Integrations/RedLock/RedLock.py, Packs/PrismaCloud/Integrations/RedLock/RedLock.yml, Packs/PrismaCloud/ReleaseNotes/2_0_17.md, Packs/PrismaCloud/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14009
We changed the logic for the timestamp calculation to be easier to read, but it doesn't respect timezones correctly. Reverting this change.
=> Redlock UTC Timestamp fix

.gitlab/ci/global.yml, Packs/Symantec_Deepsight/pack_metadata.json
=> Revert "hide_deprecated_accenture_deepsight" & disable Mypy

Packs/D2/pack_metadata.json
=> deprecating d2, rming from XSIAM MP

Tests/Marketplace/configure_and_install_packs.py
=> Remove Space to fix upload issue

Packs/CiscoStealthwatch/Integrations/CiscoStealthwatch/README.md
related: https://jira-hq.paloaltonetworks.local/browse/XSUP-17312
Adding info about supported versions.
=> Added versioning info

Packs/Pulsedive/README.md, Packs/Pulsedive/ReleaseNotes/1_6_1.md, Packs/Pulsedive/pack_metadata.json
=> Partner doit solutions adoption start

Packs/Slack/Integrations/SlackV3/SlackV3.py, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/ReleaseNotes/3_1_5.md, Packs/Slack/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15577
We now return a friendly little message
=> Add arg validation to slack-invite-users command

Packs/Slack/Integrations/SlackV3/SlackV3.py, Packs/Slack/Integrations/SlackV3/SlackV3_test.py, Packs/Slack/ReleaseNotes/3_1_7.md, Packs/Slack/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15577
=> SlackV3 NoneType users handling

.devcontainer/Dockerfile, .devcontainer/createCommand.sh, .devcontainer/devcontainer.json, .devcontainer/settings.json
- add volume for poetry envirnoment path (if different poetry env needed)
- fix git config to take from local machine
=> volume for poetry and fix git config

Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Alert_Summary.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Asset_ID.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Attack_Surface_Rule_ID.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Cloud.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Data_Collection.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Notification.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Related.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Detection.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_ID.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_System_IDs.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json, Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_0_2.md, Packs/CortexAttackSurfaceManagement/pack_metadata.json
1. Making sure all the ASM fields are hidden so they don't show up in the layout (see https://jira-hq.paloaltonetworks.local/browse/CRTX-63739).
2. Adding x2fields to a few of the fields.
=> Asm x2fields

.devcontainer/createCommand.sh
=> fix create command

Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md, Packs/Microsoft365Defender/Integrations/Microsoft365Defender/README.md, Packs/Microsoft365Defender/ReleaseNotes/4_3_1.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-17483
Added a link to ms docs to clarify where the relevant permissions can be found
=> permissions for defender 365

Packs/Accessdata/Integrations/Accessdata/Accessdata.yml, Packs/Accessdata/Playbooks/playbook-Accessdata__Dump_memory_for_malicious_process.yml, Packs/Accessdata/Scripts/AccessdataCheckProcessExistsInSnapshot/AccessdataCheckProcessExistsInSnapshot.yml, Packs/Accessdata/pack_metadata.json
Deprecating this Pack. Use https://github.com/demisto/content/tree/master/Packs/Exterro instead.
=> Accessdata v1

Packs/AbnormalSecurity/pack_metadata.json, Tests/Marketplace/approved_tags.json
fixes - https://code.pan.run/xsoar/content/-/jobs/17694609
=> add missing "tags", add tag to approved_tags

Packs/DelineaDSV/README.md, Packs/DelineaDSV/pack_metadata.json, Packs/DelineaSS/README.md
I have updated the title and the description for both of the Delinea packs
- [X ] Yes
=> Updating Description Text for Delinea Packs

Packs/Arduino/pack_metadata.json, Packs/ArrayToCSV/pack_metadata.json, Packs/Asset/pack_metadata.json, Packs/AtlassianConfluenceCloud/pack_metadata.json, Packs/AttachmentsPreProcessing/pack_metadata.json, Packs/Attlasian/pack_metadata.json, Packs/AutoFocus/pack_metadata.json, Packs/Automox/pack_metadata.json, Packs/AzureActiveDirectory/pack_metadata.json, Packs/AzureCompute/pack_metadata.json, Packs/AzureDataExplorer/pack_metadata.json, Packs/AzureFirewall/pack_metadata.json, Packs/AzureKeyVault/pack_metadata.json, Packs/AzureKubernetesServices/pack_metadata.json, Packs/AzureNetworkSecurityGroups/pack_metadata.json, Packs/AzureRiskyUsers/pack_metadata.json, Packs/AzureSQLManagement/pack_metadata.json, Packs/AzureSentinel/pack_metadata.json, Packs/AzureStorage/pack_metadata.json, Packs/AzureStorageContainer/pack_metadata.json, Packs/AzureStorageFileShare/pack_metadata.json, Packs/AzureStorageQueue/pack_metadata.json, Packs/AzureStorageTable/pack_metadata.json, Packs/AzureWAF/pack_metadata.json
relates to: https://jira-hq.paloaltonetworks.local/browse/CIAC-4318
=> revamp usecases/tags/categories 70-109

Packs/AccessInvestigation/pack_metadata.json
fixes: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/18782/workflows/1035752b-75f2-4aee-94a8-158061b0fba0/jobs/130454
fixes validation error
=> Fix validation failure

Packs/BMCDiscovery/pack_metadata.json, Packs/Base/pack_metadata.json, Packs/BatchData/pack_metadata.json, Packs/Binalyze/pack_metadata.json, Packs/BitDam/pack_metadata.json, Packs/BitcoinAbuse/pack_metadata.json, Packs/BluecatAddressManager/pack_metadata.json, Packs/Bonusly/pack_metadata.json, Packs/BruteForce/pack_metadata.json, Packs/CIRCLHashlookup/pack_metadata.json, Packs/CTIX/pack_metadata.json, Packs/CVESearch/pack_metadata.json, Packs/FeedBambenekConsulting/pack_metadata.json, Packs/FeedCSV/pack_metadata.json
related to: https://jira-hq.paloaltonetworks.local/browse/CIAC-4318
=> revamp usecases/tags/categories 110-138

Packs/Base/pack_metadata.json, Packs/BitcoinAbuse/pack_metadata.json, Tests/Marketplace/approved_tags.json
=> add Core to approved, fix tag in bitcoin abuse

Tests/Marketplace/approved_tags.json
=> add-breach-simulation

Packs/CVE_2021_40444/pack_metadata.json, Packs/CVE_2021_44228/pack_metadata.json, Packs/CVE_2022_26134/pack_metadata.json, Packs/CVE_2022_30190/pack_metadata.json, Packs/CVE_2022_41040_and_CVE_2022_41082_-_ProxyNotShell/pack_metadata.json, Packs/CVSS/pack_metadata.json, Packs/CadoResponse/pack_metadata.json, Packs/Campaign/pack_metadata.json, Packs/CaseManagement-Generic/pack_metadata.json, Packs/Centreon/pack_metadata.json, Packs/Change_Management/pack_metadata.json, Packs/CheckPhish/pack_metadata.json, Packs/CheckPointDome9/pack_metadata.json, Packs/CheckpointFirewall/pack_metadata.json, Packs/CimTrak-SystemIntegrityAssurance/pack_metadata.json, Packs/Cisco-umbrella-cloud-security/pack_metadata.json, Packs/CiscoESAIronPortEmailAPI/pack_metadata.json, Packs/CiscoEmailSecurity/pack_metadata.json, Packs/CiscoWSA/pack_metadata.json, Packs/CiscoWebExFeed/pack_metadata.json, Packs/Clarizen/pack_metadata.json
relates to: https://jira-hq.paloaltonetworks.local/browse/CIAC-4318
=> update tags/usecases/categories to 60 more packs

Packs/FeedURLhaus/pack_metadata.json, Packs/TIM_Processing/pack_metadata.json, Packs/ThreatIntelligenceManagement/pack_metadata.json, Packs/TwitterIOCHunter-FullDailyFeed/pack_metadata.json
=> fix pack tags

Tests/conf.json
relates to: https://github.com/demisto/demisto-sdk/pull/2420
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4369
Updating conf.json to include all integrations, test playbooks dependencies
=> Updating conf.json to include all integrations, test playbooks dependencies

Packs/Compliance/pack_metadata.json
=> fix-tags-usecases-complaince

Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml, Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md, Packs/CVE_2022_30190/ReleaseNotes/1_0_4.md, Packs/CVE_2022_30190/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4035
Rapid breach response | Fixes for playbooks inputs | Task's Position changed
=> Omrii msdt new

Utils/get_private_build_status.py, Utils/trigger_private_build.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4435)
We had an edge case where all the job steps were completed but the job status didn't get updated yet to completed.
=> bug fix get_private_build_status 

Packs/KnowBe4_KMSAT/ModelingRules/KnowBe4KMSATEventCollector/KnowBe4KMSATEventCollector_schema.json, Packs/KnowBe4_KMSAT/ReleaseNotes/1_0_2.md, Packs/KnowBe4_KMSAT/pack_metadata.json
Fixed an issue with the modeling rules schema which Prevented pack installation.
=> Kmsat modelingrules hotfix

Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE.yml, Packs/CVE_2022_30190/Playbooks/playbook-CVE-2022-30190_-_MSDT_RCE_README.md, Packs/CVE_2022_30190/ReleaseNotes/1_0_5.md, Packs/CVE_2022_30190/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4035
Rapid breach response | Task's Position changed
=> Omri msdt rce 

Packs/Base/ReleaseNotes/1_31_30.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json
- https://github.com/demisto/dockerfiles/pull/9363
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-64873)
=> Bump sane-pdf-reports docker image

Packs/AWS-Enrichment-Remediation/README.md
fixing the path to the image on https://github.com/demisto/content/pull/21953
=> Fix absolute path

.devcontainer/settings.json
- add `-v` to `testing.pytestArgs`
=> verbose pytestArgs

Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules/OneModelDevModelingRules.yml, Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3.yml, Packs/OnemodelDev/ReleaseNotes/1_0_1.md, Packs/OnemodelDev/pack_metadata.json
=> Remove from_xdr_version from OneModelDev

Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3.xif, Packs/OnemodelDev/ReleaseNotes/1_0_2.md, Packs/OnemodelDev/pack_metadata.json
=> Fix one modeldev 1 3

Packs/OnemodelDev/ModelingRules/OneModelDevModelingRules_1_3/OneModelDevModelingRules_1_3_schema.json, Packs/OnemodelDev/ReleaseNotes/1_0_1.md, Packs/OnemodelDev/ReleaseNotes/1_0_2.md, Packs/OnemodelDev/ReleaseNotes/1_0_3.md, Packs/OnemodelDev/pack_metadata.json
=> Fixed yml file OneModelDev.

Tests/Marketplace/approved_tags.json
rmed 3 tags we have removed.
1st PR from a few more to come.
=> rm-tags-not-on-packs-101

Packs/CyrenInboxSecurity/pack_metadata.json, Packs/DB2/pack_metadata.json, Packs/Darktrace/pack_metadata.json, Packs/DeHashed/pack_metadata.json, Packs/DeduplicateValuesbyKey/pack_metadata.json, Packs/DefaultPlaybook/pack_metadata.json, Packs/Dig/pack_metadata.json, Packs/DigitalShadows/pack_metadata.json, Packs/EWS/pack_metadata.json, Packs/EWSMailSender/pack_metadata.json, Packs/EasyVista/pack_metadata.json, Packs/ElasticsearchMonitoring/pack_metadata.json, Packs/EmailCommunication/pack_metadata.json, Packs/EmailRepIO/pack_metadata.json, Packs/EmployeeOffboarding/pack_metadata.json, Packs/Envoy/pack_metadata.json, Packs/FeedDHS/pack_metadata.json, Packs/dnstwist/pack_metadata.json
relates to: tags/usecases/categories 250-300
=> tags/usecases/categories 250-300

Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
=> Add freeze_time to test_case_insensitive

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md, Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_9.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://github.com/demisto/content-docs/issues/1207
Added description for the  `cs-falcon-contain-host` command that the ID argument support a list of ID's
=> update Crowdstrike readme

Tests/Marketplace/upload_packs.py
=> hotifx upload filtering

Tests/conf.json
Remove edl tests as they are sub-playbooks and shouldn't run on their own.
Remove Daily Feed test as the integration is deprecated
=> remove irrelevant tests from conf.json

Packs/AzureActiveDirectory/pack_metadata.json, Packs/DeprecatedContent/pack_metadata.json, Packs/DeveloperTools/pack_metadata.json, Packs/HybridAnalysis/pack_metadata.json, Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json
relates to: https://jira-hq.paloaltonetworks.local/browse/CIAC-4277
=> hide packs 107

Packs/FeedMandiant/pack_metadata.json, Packs/FeedMicrosoftIntune/pack_metadata.json, Packs/ManageEngine_PAM360/pack_metadata.json, Packs/Mantis/pack_metadata.json, Packs/MapPattern/pack_metadata.json, Packs/MapRegex/pack_metadata.json, Packs/MarkdownToHTML/pack_metadata.json, Packs/Mattermost/pack_metadata.json, Packs/MaxList/pack_metadata.json, Packs/McAfeeWebGateway/pack_metadata.json, Packs/McAfee_DXL/pack_metadata.json, Packs/MergeDictArray/pack_metadata.json, Packs/MicrosoftAdvancedThreatAnalytics/pack_metadata.json, Packs/MicrosoftCloudAppSecurity/pack_metadata.json, Packs/MicrosoftGraphAPI/pack_metadata.json, Packs/MicrosoftGraphApplications/pack_metadata.json, Packs/MicrosoftGraphCalendar/pack_metadata.json, Packs/MicrosoftGraphFiles/pack_metadata.json, Packs/MicrosoftGraphGroups/pack_metadata.json, Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json, Packs/MicrosoftGraphMail/pack_metadata.json, Packs/MicrosoftGraphUser/pack_metadata.json, Packs/MicrosoftManagementActivity/pack_metadata.json, Packs/Mimecast/pack_metadata.json, Packs/MinList/pack_metadata.json, Packs/ModulesManagement/pack_metadata.json, Packs/Moloch/pack_metadata.json, Packs/ServiceDeskPlus_On_Premise/pack_metadata.json, Packs/mcafeeDam/pack_metadata.json
=> mp_revamp_500-550

Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.yml, Packs/Dropbox/ReleaseNotes/1_0_5.md, Packs/Dropbox/pack_metadata.json
=> Add marketplaces field in Dropbox event collector

Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer.py, Packs/PANOSPolicyOptimizer/ReleaseNotes/1_1_1.md, Packs/PANOSPolicyOptimizer/pack_metadata.json
=> Fix optimizer headers

Packs/DeveloperTools/pack_metadata.json, Packs/Hunting/pack_metadata.json, Packs/IAM-SCIM/pack_metadata.json, Packs/ILert/pack_metadata.json, Packs/IP-API/pack_metadata.json, Packs/IPQualityScore/pack_metadata.json, Packs/IdentityRecordedFuture/pack_metadata.json, Packs/IllusiveNetworks/pack_metadata.json, Packs/ImpossibleTraveler/pack_metadata.json, Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json, Packs/Inventa/pack_metadata.json, Packs/InvertEveryTwoItems/pack_metadata.json, Packs/IsArrayItemInList/pack_metadata.json, Packs/XForceExchange/pack_metadata.json, Packs/ipinfo/pack_metadata.json
relates to: [mp_revamp_411_450](https://jira-hq.paloaltonetworks.local/browse/CIAC-4318)
=> usecases/tags/categories mp_revamp_411_450

.gitlab/ci/staging.yml, Tests/scripts/utils/compare_staging_graph.py
=> fix demisto-sdk installation in staging

Packs/CheckPointDome9/pack_metadata.json, Packs/Cisco-umbrella-cloud-security/pack_metadata.json, Packs/FeedCyCognito/pack_metadata.json, Packs/GoogleDrive/pack_metadata.json, Packs/SkyhighSecurity/pack_metadata.json
=> fix misspelled categories

Packs/Armorblox/pack_metadata.json, Packs/BreachRx/pack_metadata.json, Packs/KeeperSecretsManager/pack_metadata.json, Packs/NutanixHypervisor/pack_metadata.json
=> rm deprecated tags and use cases

Packs/AquatoneDiscover/.pack-ignore
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4173
=> add pack-ignore

Packs/CortexAttackSurfaceManagement/.pack-ignore
Ignore the IF100 validation error for an incident field in the CortexAttackSurfaceManagement pack.
Fixes broken master.
=> Ignore IF100 error in CortexAttackSurfaceManagement pack

Packs/CortexAttackSurfaceManagement/pack_metadata.json
Fixed dependency issue for new core pack CortexAttackSurfaceManagement.
=> Fix dependency for CortexAttackSurfaceManagement

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18074
Added a note in the `microsoft-atp-advanced-hunting` regarding the supported schemas
=> Added a note to the command documentaion

Tests/conf.json
The credentials we have are not working. opened a ticket for the lab here [CRTX-67423](https://jira-hq.paloaltonetworks.local/browse/CRTX-67423)
=> Skip Cortex Data Lake test playbook

Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_ATP_indicators_Test.yml, Tests/conf.json
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-1079)
Removed old tpb according to old issue (see jira above)
=> Deprecate Microsoft Defender - ATP - Indicators Test TPB

Packs/CommonScripts/TestPlaybooks/playbook-DecodeMimeHeader_-_Test.yml
Fixed missing space in the playbook verify check
=> Fix DecodeMimeHeader - Test test playbook

Tests/conf.json
These are sub-playbooks ran by `TAXII2 Server Performance Test` test playbook
=> Delete sub-testPlaybooks for TAXII2

Packs/Stairwell/Integrations/Inception/Inception.py, Packs/Stairwell/ReleaseNotes/1_0_1.md, Packs/Stairwell/pack_metadata.json
N/A
Small logic fix for test_module
=> Fix for test_module

Tests/scripts/gitlab_slack_notifier.py
no more (thin) walls of text on slack
=> CSV for notifier messages

Packs/MySQLEnterprise/ReleaseNotes/1_0_3.md, Packs/MySQLEnterprise/XDRCTemplates/MySQLEnterprise/MySQLEnterprise.json, Packs/MySQLEnterprise/pack_metadata.json
=> add XDRC Templates rules 1.3

Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/README.md
https://jira-hq.paloaltonetworks.local/browse/CIAC-4287 
https://jira-hq.paloaltonetworks.local/browse/CIAC-4573
The policy optimizer does not have an official API, therefore it had moved to beta. This branch's purpose is to add an explanation to the readme file.
- [X ] 6.0.0
=> Added read me comment by Shirley why is it in beta

Packs/Whois/TestPlaybooks/playbook-Whois-Test.yml
Removed conditions that weren't relevant anymore (condition based on date, condition for field that is no longer available)
=> Fix whois test playbook

Packs/CrowdStrikeFalcon/.pack-ignore, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_10.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [#20862](https://github.com/demisto/content/pull/20862/files)
Reverted some code that was mistakenly deleted in previous prs.
=> Revert cs falcon changes

Tests/Marketplace/upload_packs.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3504
Fixes changelog in build bucket.
Successafull [PR build](https://code.pan.run/xsoar/content/-/pipelines/4046052) and [Upload build](https://code.pan.run/xsoar/content/-/pipelines/4046054) after I did some changes in packs.
Also tested the marketplace url in server.
=> Revert "removed the filter by marketplace for the upload that runs in the build (#19831)"

.gitlab/ci/staging.yml, Tests/scripts/utils/compare_staging_graph.py
=> fix path of zip files

Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3.xif, Packs/PrismaSaasSecurity/ModelingRules/SaasSecurityEventCollector_1_3/SaasSecurityEventCollector_1_3_schema.json, Packs/PrismaSaasSecurity/ReleaseNotes/2_0_9.md, Packs/PrismaSaasSecurity/pack_metadata.json
added additional fields to modeling rule
=> Add fields to SaasSecurity modeling rule

Tests/Marketplace/landingPage_sections.json
=> Remove mote from landing

Packs/Base/ReleaseNotes/1_31_36.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml, Packs/Base/pack_metadata.json
=> Fix pytz import in commonserverpython

Packs/DefaultPlaybook/.pack-ignore
try to fix the validation error introduced in: https://github.com/demisto/content/pull/22293
=> ignore default pb 8 error BA101

Packs/MITRECoA/pack_metadata.json
Removed the price from MITRE CoA content
=> MITRE CoA - Removed price

Packs/CommonTypes/IndicatorFields/indicatorfield-keyvalue.json, Packs/CommonTypes/ReleaseNotes/3_3_28.md, Packs/CommonTypes/pack_metadata.json
Cant create a new indicator because the "Name" key in the "Key Value" field is required.
=> Indicator fields | Fixkeyvalue field

Packs/OnemodelDev/pack_metadata.json
=> Deprecate OneModel pack

Packs/MalwareInvestigationAndResponse/ReleaseNotes/2_0_2.md, Packs/MalwareInvestigationAndResponse/Wizards/wizard-Malware_Investigation_and_Response.json, Packs/MalwareInvestigationAndResponse/Wizards/wizard-Malware_Investigation_and_Response_6.8.json, Packs/MalwareInvestigationAndResponse/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4629
Adding Joe Security support into the Malware Investigation and Response wizard.
N.A.
=> Joe security add to malware wizard

Tests/conf.json
This instance is failing nightly, opened an issue to investigate further here [CIAC-4566](https://jira-hq.paloaltonetworks.local/browse/CIAC-4566)
=> Remove Microsoft SQL Server instance for Generic-sql tpb

.github/CODEOWNERS
Make myself code owner for conf.json to monitor test playbook changes
=> add to codeowners

Tests/conf.json
There seems to be a problem with the credentials of Palo Alto Networks IoT integration, opened a ticket for the lab here - [CRTX-67960](https://jira-hq.paloaltonetworks.local/browse/CRTX-67960)
=> skipPaloAltoNetworks_IoT-Test

Tests/conf.json
This is a sub-playbook and shouldn't run on it's own.
=> remove PAN-OS Create Or Edit Rule Test from conf

Packs/AlibabaActionTrail/ReleaseNotes/1_0_6.md, Packs/CyberArkIdentity/ReleaseNotes/1_0_6.md, Utils/release_notes_generator.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4642)
Fixed release notes in marketplace for packs AlibabaActionTrail and CyberArkIdentity.
Fixed XSIAM Dashboards in release notes.
=> Fixed release notes in marketplace

Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/README.md, Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.py, Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis.yml, Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/SecneurXAnalysis_test.py, Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/command_examples, Packs/SecneurXAnalysis/Integrations/SecneurXAnalysis/test_data/get_response_example.json, Packs/SecneurXAnalysis/ReleaseNotes/1_0_1.md, Packs/SecneurXAnalysis/pack_metadata.json
* Add new command to get API KEY quota usage details
Signed-off-by: Bala Manoharan <bala@secneurx.com>
- [x ] Ready
- [x ] No
- [x ] Documentation
=> Add new command for querying API KEY quota usage

Packs/ANYRUN/CONTRIBUTORS.json, Packs/PAN-OS/CONTRIBUTORS.json, Packs/TheHiveProject/CONTRIBUTORS.json
NA
Added my name to cobtributors on a few packs.
=> Added contributors

Packs/AlibabaActionTrail/ReleaseNotes/1_0_6.md, Packs/CyberArkIdentity/ReleaseNotes/1_0_6.md, Packs/Dropbox/ReleaseNotes/1_0_6.md, Packs/GitLab/ReleaseNotes/2_1_0.md, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_14_1.md, Tests/Marketplace/marketplace_services.py
- Fixed release notes in some packs in marketplace.
- Added debug logs in the upload flow
=> Fix release notes in marketplace

Packs/Thycotic/Integrations/Thycotic/Thycotic.py, Packs/Thycotic/Integrations/Thycotic/Thycotic.yml, Packs/Thycotic/ReleaseNotes/1_0_3.md, Packs/Thycotic/pack_metadata.json, Packs/ThycoticDSV/Integrations/ThycoticDSV/ThycoticDSV.py, Packs/ThycoticDSV/Integrations/ThycoticDSV/ThycoticDSV.yml, Packs/ThycoticDSV/ReleaseNotes/1_0_3.md, Packs/ThycoticDSV/pack_metadata.json
=> Depricate the Thycotic and ThycoticDSV packs

Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.py, Packs/ReversingLabs_A1000/Integrations/ReversingLabsA1000v2/ReversingLabsA1000v2.yml, Packs/ReversingLabs_A1000/ReleaseNotes/2_0_7.md, Packs/ReversingLabs_A1000/pack_metadata.json
Corrected the bug with an unusuable `result-limit` argument in the `advanced_search` funcction. Now the argument is called `resultLimit`.
=> ReversingLabs A1000 2.0.7

Packs/Base/TestPlaybooks/playbook-Indicators-reputation-.json-Test.yml, Packs/CommonScripts/TestPlaybooks/playbook-Test_URL_Regex.yml
Both playbooks had error in the URL checks (upper case instead of lower case),
The indicators test had 2 indicators that are not valid, they were removed after consulting @Ni-Knight  (Dror)
=> Fix ndicators reputation-.json Test and test_url_regex

Tests/Marketplace/marketplace_services.py
=> Revert change made for dedup items

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md, Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_14_3.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18509
Added the name of the azure portal permissions so customers have an easier set-up
=> added explanation for api permissions

.github/workflows/pre-commit.yml
=> quote files in precommit

Packs/CommonTypes/IncidentFields/incidentfield-Account_Member_Of.json, Packs/CommonTypes/IncidentFields/incidentfield-Account_Status.json, Packs/CommonTypes/IncidentFields/incidentfield-sAMAccountName.json, Packs/CommonTypes/ReleaseNotes/3_3_32.md, Packs/CommonTypes/pack_metadata.json
Adding 2 new fields:
- **Account Member Of**
- **Account Status**:
- **sAMAccountName**   
Changed this field to be associated to all incident types. 
=> Additional user's fields

Packs/XSOARmirroring/pack_metadata.json
Remove XSOAR content items from XSIAM 
=> remove XSOARMirroring from xsiam marketplace

Packs/GenericSQL/Integrations/GenericSQL/README.md
fixes: [issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-14043)
=> generic sql: update troubleshooting about autocommit

Packs/XSOARmirroring/pack_metadata.json
fixes: the master is broken
https://code.pan.run/xsoar/content/-/jobs/18882893
=> remove xsoar mirroring from xsiam

.gitlab/ci/on-push.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4700
Added eurpoe tag to create-instances job
=> added europe tag

Tests/configure_and_test_integration_instances.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4619
=> Logs impovment build

Packs/Campaign/ReleaseNotes/3_2_16.md, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py, Packs/Campaign/pack_metadata.json
Update the dockerimage of `FindEmailCampaign` script to align the version of the `tldextract` to the `tldextract` version of the py3-primary image
=> [Campaign] - update FindEmailCampaign dockerimage

Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus.yml, Packs/AutoFocus/Integrations/FeedAutofocus/FeedAutofocus_description.md, Packs/AutoFocus/ReleaseNotes/2_0_31.md, Packs/AutoFocus/pack_metadata.json
fixes: [XSUP-18258](https://jira-hq.paloaltonetworks.local/browse/XSUP-18258)
Added more information about the differences between samples and custom feeds.
=> Autofocus add info about differences between samples and custom feeds

.gitlab/ci/.gitlab-ci.yml, poetry.lock, pyproject.toml
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-4638
reduced the maximum allowed cpu cores.
=> hot fix demisto sdk

Packs/BrocadeSwitch/ParsingRules/BrocadeSwitch/BrocadeSwitch.xif, Packs/BrocadeSwitch/ReleaseNotes/1_0_6.md, Packs/BrocadeSwitch/pack_metadata.json, Packs/CiscoSMA/ParsingRules/CiscoSMA/CiscoSMA.xif, Packs/CiscoSMA/ParsingRules/CiscoSMA/CiscoSMA.yml, Packs/CiscoSMA/ReleaseNotes/1_1_1.md, Packs/CiscoSMA/pack_metadata.json, Packs/FireEyeNX/ParsingRules/FireEyeNX/FireEyeNX.xif, Packs/FireEyeNX/ParsingRules/FireEyeNX/FireEyeNX.yml, Packs/FireEyeNX/ReleaseNotes/1_1_10.md, Packs/FireEyeNX/ReleaseNotes/1_1_11.md, Packs/FireEyeNX/pack_metadata.json, Packs/JuniperSRX/ParsingRules/JuniperSRX/JuniperSRX.xif, Packs/JuniperSRX/ReleaseNotes/1_0_4.md, Packs/JuniperSRX/ReleaseNotes/1_0_5.md, Packs/JuniperSRX/pack_metadata.json
=> added a parsing rules

Packs/CiscoSMA/Integrations/CiscoSMA/CiscoSMA.yml, Packs/CiscoSMA/ReleaseNotes/1_1_2.md, Packs/CiscoSMA/pack_metadata.json, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.yml, Packs/IronPort/ReleaseNotes/2_0_1.md, Packs/IronPort/pack_metadata.json
fixes: [build failure](https://github.com/demisto/content/pull/22604#issue-1470813754)
Updating categories for yml files.
=> Fix integration and pack metadatas categories v3

Tests/Marketplace/approved_categories.json
Added a critical comment that should warn whoever changes this list to avoid future SDK breaks.
=> add_comment_to_approved_categories

Packs/AlibabaActionTrail/ReleaseNotes/1_0_8.md
=> fix Alibaba release notes

Tests/Marketplace/marketplace_services.py, Tests/Marketplace/upload_packs.py, Tests/scripts/collect_tests/collect_tests.py
Removed condition where failed preview image fails the entire pack upload list.
Fixed the case where deleted preview image is failing a single ack
=> removed condition where failed preview image fails the entire list.

Tests/Marketplace/marketplace_services.py, Tests/Marketplace/upload_packs.py, Tests/scripts/collect_tests/collect_tests.py
HF for broken preview image validation that broke upload
=> Missing packs hf

.github/CODEOWNERS
Adding myself as codeowner, to alll XSIAM-build related files.
=> Adding myself as codeowner

Packs/Tenable_io/ReleaseNotes/2_1_0.md
=> Fix tenable.io release notes

Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/README.md
Removed extraneous ** from the Required heading in the parameter table.
=> Removed extraneous **

Packs/KnowBe4_KMSAT/Integrations/KnowBe4KMSATEventCollector/README.md
The path to the integration should be: Navigate to Settings > Configurations > Data Collection > Data Sources.
And this is an XSIAM integration (not XSOAR).
=> Change path to integration instance - KnowB4 KMSAT

Packs/Core/Playbooks/playbook-Impossible_Traveler.yml, Packs/Core/Playbooks/playbook-Impossible_Traveler_README.md, Packs/Core/ReleaseNotes/1_3_19.md, Packs/Core/pack_metadata.json
fixes: a bug caused by hard-coded value in playbook input
=> Fix hardcoded playbook inputs

.gitlab/ci/on-push.yml, .gitlab/ci/sdk-nightly.yml, .gitlab/ci/staging.yml
=> increase requested cpu

Packs/EasyVista/Integrations/EasyVista/EasyVista.yml
=> add additionalinfo to yml

Packs/IntSight/Integrations/IntSight/IntSight.py, Packs/IntSight/Integrations/IntSight/IntSight.yml, Packs/IntSight/Integrations/IntSight/IntSight_description.md, Packs/IntSight/ReleaseNotes/2_0_2.md, Packs/IntSight/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18952
Added support for authorization by API key - when the user Id is `_api_token_key` the integration request will authorize with the API token
=> IntSights - Added support for authorization by API key

Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity.yml, Packs/MicrosoftGraphSecurity/ReleaseNotes/2_1_6.md, Packs/MicrosoftGraphSecurity/pack_metadata.json
Change tests in integrations yml 
=> change tests in yml for MS Graph

Documentation/common_server_docs.py
=> fix import to yml unifier

Packs/McAfee-TIE/Integrations/McAfeeTIEV2/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4514
Insert teh `<>` tags in quotation marks
=> Fix McAfee Threat Intelligence Exchange V2 README

Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml, Packs/ActiveMQ/ReleaseNotes/1_1_10.md, Packs/ActiveMQ/pack_metadata.json, Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml, Packs/Anomali_ThreatStream/ReleaseNotes/2_0_21.md, Packs/Anomali_ThreatStream/pack_metadata.json, Packs/CommonScripts/ReleaseNotes/1_10_22.md, Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml, Packs/CommonScripts/pack_metadata.json, Packs/FeedCSV/Integrations/FeedCSV/FeedCSV.yml, Packs/FeedCSV/ReleaseNotes/1_1_24.md, Packs/FeedCSV/pack_metadata.json, Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml, Packs/FeedElasticsearch/ReleaseNotes/1_0_29.md, Packs/FeedElasticsearch/pack_metadata.json, Packs/FeedPlainText/Integrations/FeedPlainText/FeedPlainText.yml, Packs/FeedPlainText/ReleaseNotes/1_1_22.md, Packs/FeedPlainText/pack_metadata.json, Packs/MongoDB/Integrations/MongoDB/MongoDB.yml, Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.yml, Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.yml, Packs/MongoDB/ReleaseNotes/1_2_17.md, Packs/MongoDB/pack_metadata.json, Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml, Packs/OpenLDAP/ReleaseNotes/2_0_7.md, Packs/OpenLDAP/pack_metadata.json
=> 5Update image

Packs/CommonTypes/IndicatorTypes/reputation-domain.json, Packs/CommonTypes/ReleaseNotes/3_3_37.md, Packs/CommonTypes/pack_metadata.json
Better regex that catches only letters and not unseen chars.
https://regex101.com/r/kIytNC/1
=> Domain regex upgrade to support only natural language.

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py, Packs/QRadar/ReleaseNotes/2_3_4.md, Packs/QRadar/pack_metadata.json
fixes: QRadar fetch performance and logic issues
Fix logic and performance of fetching offenses from QRadar.
=> Bug fix to QRadar Integration

Packs/FeedOpenCTI/Integrations/FeedOpenCTI_v4/README.md
Add supported API version to readme.
=> add version support

Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/README.md
Added descriptions and updated the list of parameters for the GuardDuty Event Collector Integration.
=> Add desc for parameters: GuardDuty Event Collector

Packs/FortiGate/ParsingRules/FortiGate/FortiGate.xif, Packs/FortiGate/ParsingRules/FortiGate/FortiGate.yml, Packs/FortiGate/ReleaseNotes/1_0_17.md, Packs/FortiGate/pack_metadata.json
=> Added parsing rule for fortigate, to export _time.

Packs/SymantecEndpointProtection/Integrations/SymantecEndpointProtection_V2/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18774
Has a bug, the customer had admin permissions and not system admin permissions.
=> Improve documentation - permissions

Packs/Slack/Integrations/SlackV3/README.md
fixes:  https://jira-hq.paloaltonetworks.local/browse/CRTX-70106
Fixed the slack v3 REAMDE
=> Fix slack v3 RADME

Packs/NGINXWebServer/README.md
This PR was created to fix the Readme for NGINX
=> NGINX Readme Fix

Packs/CyberArkIdentity/README.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-70031)
Fix the parameters human readable table
=> CyberArkIdentity - Fix README.md

Packs/FiltersAndTransformers/.pack-ignore
fixes: [link to the issue](https://panw-global.slack.com/archives/C03A9TJ57FT/p1671019138411689)
Fix RM112 in FiltersAndTransformers - false positive of a URL
=> Fix RM112 in FiltersAndTransformers

Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules_1_3/AlibabaModelingRules_1_3_schema.json, Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules_1_3/AlibabaModelingRules_1_3_testdata.json, Packs/AlibabaActionTrail/ReleaseNotes/1_0_11.md, Packs/AlibabaActionTrail/pack_metadata.json
=> Fix alibaba missing fiels in the schema

Tests/docker_native_image_config.json
https://github.com/demisto/dockerfiles/pull/10542
https://github.com/demisto/dockerfiles/pull/10577
replace native image docker reference to include **pycryptodome** library.
=> update docker native image reference

Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml, Packs/VirusTotal/ReleaseNotes/2_4_13.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Fix domain relationships retrieval

Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml, Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md, Packs/Microsoft365Defender/ReleaseNotes/4_4_5.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-19477
Fixed an issue in the ***microsoft-365-defender-incident-update*** command where some pre-defined values for the *classification*, *status*, and *determination* arguments were not correct or missing.
=> fix issue in microsoft-365-defender-incident-update command

Packs/DeveloperTools/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4539)
=> Separate d2 from developertools

Packs/VMware/Integrations/VMware/VMware.py, Packs/VMware/Integrations/VMware/VMware.yml, Packs/VMware/ReleaseNotes/1_2_6.json, Packs/VMware/ReleaseNotes/1_2_6.md, Packs/VMware/pack_metadata.json
Added the **redirect_std_out** integration param, used for troubleshooting.
=> adding redirect_std_out integration param to vmware

.devcontainer/Dockerfile, .devcontainer/createCerts.sh, .devcontainer/createCommand.sh
The workaround for GP may cause issues when no needed (no self signed certifiacte issue), so checking before applying if we need to configure it
=> config certifacte info only if needed

Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py, Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml, Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py, Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md, Packs/MicrosoftGraphListener/ReleaseNotes/1_3_0.md, Packs/MicrosoftGraphListener/pack_metadata.json, Packs/MicrosoftGraphMail/.secrets-ignore, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md, Packs/MicrosoftGraphMail/ReleaseNotes/1_4_0.md, Packs/MicrosoftGraphMail/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4097
- Fix a body-preview being passed for fetch-incidents instead of the full body on "Microsoft Graph Mail Single User".
- Add a "Mark as Read" parameter for fetched emails on "Microsoft Graph Mail" and "Microsoft Graph Mail Single User".
=> Microsoft Graph Mail Enhancement

Packs/Base/ReleaseNotes/1_31_46.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/pack_metadata.json
Pass all mandatory arguments to SSLAdapter cstr. In kwargs dicti.
=> Pass arguments to SSLAdapter cstr in kwargs dict.

Packs/MITRECoA/pack_metadata.json
=> Hidden the pack

Tests/secrets_white_list.json
ignore foo, bar, baz as secrets
=> ignore foo, bar, baz

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml
=> upload csv in the end of the bucket upload

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml
=> fix upload content graph override

.gitlab/ci/bucket-upload.yml
=> fix csv upload

.gitlab/ci/bucket-upload.yml
=> fix csv upload v2

Tests/scripts/utils/GoogleSecretManagerModule.py
=> Added general exception

.gitlab/ci/bucket-upload.yml, .gitlab/ci/on-push.yml
skip using the graph CSVs for the weekend
=> skip using csv

Packs/MITRECoA/pack_metadata.json
=> mitre-coa-ga

Packs/CIRCL/Integrations/CIRCL/CIRCL.py, Packs/CIRCL/Integrations/CIRCL/CIRCL.yml, Packs/CIRCL/ReleaseNotes/1_0_8.md, Packs/CIRCL/pack_metadata.json, Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4819
Circl to py3.
=> Circl to py3

Packs/DemistoRESTAPI/ReleaseNotes/1_3_7.md, Packs/DemistoRESTAPI/Scripts/DemistoLeaveAllInvestigations/DemistoLeaveAllInvestigations.yml, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4724)
=> Deprecate demisto leave all investigations

Packs/DemistoRESTAPI/ReleaseNotes/1_3_7.md, Packs/DemistoRESTAPI/ReleaseNotes/1_3_9.md, Packs/DemistoRESTAPI/Scripts/DemistoLinkIncidents/DemistoLinkIncidents.yml, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4724)
=> Deprecate demisto link incidents

Packs/PAN-OS/.secrets-ignore, Packs/PAN-OS/TestPlaybooks/playbook-PAN-OS_-_URL_FIltering_Enrichment-Test.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5020
=> fix PAN-OS URL Filtering enrichment - Test test-playbook

Packs/DemistoRESTAPI/ReleaseNotes/1_3_10.md, Packs/DemistoRESTAPI/ReleaseNotes/1_3_7.md, Packs/DemistoRESTAPI/Scripts/DemistoLogsBundle/DemistoLogsBundle.yml, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4724)
=> Deprecate demisto logs bundle

Packs/DemistoRESTAPI/ReleaseNotes/1_3_11.md, Packs/DemistoRESTAPI/ReleaseNotes/1_3_7.md, Packs/DemistoRESTAPI/Scripts/DemistoSendInvite/DemistoSendInvite.yml, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4724)
=> Deprecate demisto send invite

Packs/PAN-OS/Integrations/Panorama/Panorama_test.py, Packs/PAN-OS/Integrations/Panorama/test_data/fetch_incidents_input.py
=> pan-os fetch incidents sdk bug

Packs/SMB/TestPlaybooks/playbook-SMB_test.yml
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5069)
The test had two identical download commands which created a race condition, deleted one.
=> Fix SMB test playbook

.gitlab/ci/bucket-upload.yml
=> hotfix to upload content graph

Tests/conf.json
=> raise timeout to ms_graph_mail tpb

.gitlab/ci/bucket-upload.yml
Add the MARKETPLACE_VERSION variable to the upload-to-marketplace steps
=> fix upload graph in upload-flow

Packs/DemistoLocking/pack_metadata.json
=> Change DemistoLock display name

Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml, Packs/Tenable_io/ReleaseNotes/2_1_1.md, Packs/Tenable_io/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-2058
Not sure why the Tenable.io integration originally had category "Data Enrichment & Threat Intelligence"
https://github.com/demisto/content/blob/master/Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.yml#L1
Changed to "Vulnerability Management" (same as pack)
https://github.com/demisto/content/blob/master/Packs/Tenable_io/pack_metadata.json
=> EXPANDR-2058

Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py, Packs/DuoAdminApi/ReleaseNotes/3_2_1.md, Packs/DuoAdminApi/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-19601
The API v2 didn't work so I revert to v1 and fixed a bug with an infinite loop if we have an error when making a request.
=> Duo hotfix

Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.py, Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.yml, Packs/ZeroTrustAnalyticsPlatform/README.md, Packs/ZeroTrustAnalyticsPlatform/ReleaseNotes/1_1_3.md, Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json
* Use separate client for downloading attachments
* Fix issue where api key in download image request caused 422
* Update README to add ztap-get-alert-entries to custom playbooks
=> Update ZeroTrustAnalyticsPlatform to 1.1.3

.circleci/config.yml
=> removed ssh un relevant ssh acctions from circle

poetry.lock, pyproject.toml
=> SDK v1.8.3.

.gitlab/ci/on-push.yml
=> change update to create graphs on builds

.gitlab/ci/on-push.yml, Tests/scripts/check_if_branch_exist.sh, Tests/secrets_white_list.json, Utils/trigger_private_build.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5145
requierd: https://github.com/demisto/content-private/pull/640
job when branch exist: https://code.pan.run/xsoar/content/-/jobs/20092547
triggered: https://github.com/demisto/content-private/actions/runs/3841781671/jobs/6542391473#step:2:672
job when branch doesn’t exist: https://code.pan.run/xsoar/content/-/jobs/20092742
triggered: https://github.com/demisto/content-private/actions/runs/3841826580/jobs/6542484745#step:2:671
added new ability for content-private build trigger with custom branch on content-private repo.
=> trigger build on content private custom branch

Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5177
PB was not accepting items in a list
=> Fix ExpanseV2 TPB

Packs/CommunityCommonScripts/.pack-ignore, Packs/CommunityCommonScripts/Scripts/GetFilePathPreProcessing/GetFilePathPreProcessing.yml
=> fixed validation error

Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5167
Increased the timeout of the TPB.
=> Increased Timeout Indicator Formatter TPB

Tests/scripts/collect_tests/collect_tests.py
Fix always installed packs to be collected only if there other packs to install.
=> Fix collect always installed packs

.circleci/config.yml, .gitlab/ci/global.yml, Tests/scripts/linters_runner.sh, Tests/scripts/pyflake.sh
This reverts commit 81a841a0f25339919fb836f875fafdeda2228e5a.
=> Revert "remove un relevant python2 & update docker tag for circle (#23693)"

poetry.lock, pyproject.toml
[sdk-nightly](https://code.pan.run/xsoar/content/-/pipelines/4364518)
[content-nightly](https://code.pan.run/xsoar/content/-/pipelines/4365031)
[content-private](https://github.com/demisto/content-private/pull/642)
branch name in sdk - `v1.8.3-hotfix`
=> Hotfix - demisto-sdk 1.8.3

Packs/Shodan/.pack-ignore, Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.py, Packs/Shodan/Integrations/Shodan_v2/Shodan_v2.yml, Packs/Shodan/ReleaseNotes/1_1_6.md, Packs/Shodan/TestPlaybooks/playbook-Test_shodan_v2.yml, Packs/Shodan/pack_metadata.json
=> Add Stored Credentials Support to Shodan_v2

Packs/CrowdStrikeFalconX/Playbooks/Detonate_File_-_CrowdStrike_Falcon_X.yml, Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X.yml, Packs/CrowdStrikeFalconX/Playbooks/Detonate_URL_-_CrowdStrike_Falcon_X_README.md, Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File_README.md, Packs/CrowdStrikeFalconX/README.md, Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_18.md, Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml, Packs/CrowdStrikeFalconX/pack_metadata.json
Added more fixes for renaming CrowdStrike faconX
=> Crowd strike falcon x renaming more fixes

Packs/SentinelOne/README.md, Packs/SentinelOne/ReleaseNotes/3_0_5.md, Packs/SentinelOne/pack_metadata.json
=> Partner sentinel one adoption start

Packs/OktaOAG/ModelingRules/OktaOAG/OktaOAG.yml, Packs/OktaOAG/ReleaseNotes/1_0_3.md, Packs/OktaOAG/pack_metadata.json
We see 2 modeling rules in XSIAM without this key.
=> Adding toversion to old modeling rules

Packs/MyXSIAMPack_content/LayoutRules/MyLayoutRule.json, Packs/MyXSIAMPack_content/Layouts/MyLayout.json
=> Xsiam layouts example

Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.yml, Packs/FeedThreatConnect/ReleaseNotes/2_1_3.md, Packs/FeedThreatConnect/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-17613
Added the indicator reputation param per the customer's request.
=> Threatconnect add indicator reputation

Packs/Okta/.pack-ignore, Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py, Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml, Packs/Okta/Integrations/Okta_v2/Okta_v2.py, Packs/Okta/Integrations/Okta_v2/Okta_v2.yml, Packs/Okta/ReleaseNotes/3_1_2.md, Packs/Okta/pack_metadata.json
Add support to stored credentials (type 9 field) for Okta integrations.
=> Add Stored Credentials Support to Okta

Packs/MicrosoftGraphUser/.pack-ignore, Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py, Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml, Packs/MicrosoftGraphUser/ReleaseNotes/1_5_7.md, Packs/MicrosoftGraphUser/pack_metadata.json
=> Microsoft Graph User - add support in credential store

Packs/MicrosoftCloudAppSecurity/.pack-ignore, Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py, Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml, Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_13.md, Packs/MicrosoftCloudAppSecurity/pack_metadata.json
=> MicrosoftCloudAppSecurity - add support in credential store

Packs/ExpanseV2/.pack-ignore, Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py, Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml, Packs/ExpanseV2/Integrations/FeedExpanse/FeedExpanse.py, Packs/ExpanseV2/Integrations/FeedExpanse/FeedExpanse.yml, Packs/ExpanseV2/ReleaseNotes/1_10_26.md, Packs/ExpanseV2/pack_metadata.json
=> ExpanseV2 - add support in credential store

Packs/PAN-OS/Playbooks/playbook-Pan-OS_Commit_Configuration.yml, Packs/PAN-OS/Playbooks/playbook-Pan-OS_Commit_Configuration_README.md, Packs/PAN-OS/ReleaseNotes/1_16_1.md, Packs/PAN-OS/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-19163)
Added the *device-group* argument as an input for the *pan-os-commit-configuration* playbook.
=> add device-group input to pan-os-commit-configuration playbook

Packs/UncoverUnknownMalwareUsingSSDeep/pack_metadata.json
Ready
Added the youtube video to the SSDeep pack.
=> Updated Uncover Unknown Malware using SSDeep pack with video

Packs/D2/pack_metadata.json, Packs/FeedUnit42/pack_metadata.json, Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4277
d2(deprecated as of 6.6)
EDL Management(we have export IOC service)
unit42 feed(we have v2)
=> add hidden:true to deprecated packs

Packs/SlashNextPhishingIncidentResponse/pack_metadata.json
related PRs:
https://github.com/demisto/content/pull/23897
https://github.com/demisto/content/pull/23896
=> add-phishing-usecase-to-free-pack

.gitlab/ci/bucket-upload.yml
fixes: [CIAC-5217](https://jira-hq.paloaltonetworks.local/browse/CIAC-5217)
=> added job for buckets sync after upload flow

Packs/FeedMitreAttack/.pack-ignore, Packs/Kafka/.pack-ignore, Packs/MISP/.pack-ignore, Packs/cyberark_AIM/.pack-ignore
=> ignore photos

Packs/Kafka/.pack-ignore
=> fix kafka image name

.gitlab/ci/on-push.yml, Tests/scripts/print_cloud_machine_details.sh
=> Updated the print_cloud_machine_details 

.gitlab/ci/bucket-upload.yml
Fixed an issue caused sync-buckets to run after a required job was skipped
https://code.pan.run/xsoar/content/-/pipelines/4426029
=> removed always

Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.yml, Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/README.md, Packs/DemistoRESTAPI/ReleaseNotes/1_3_16.md, Packs/DemistoRESTAPI/pack_metadata.json
Fixes incorrect description given to Demisto REST API post-deprecation.
=> fix DemistoRESTAPI description

.circleci/gitlab-ci-env-variables.sh, .gitlab/ci/.gitlab-ci.yml, .gitlab/ci/bucket-upload.yml, .gitlab/ci/global.yml, .gitlab/ci/on-push.yml, .gitlab/ci/sdk-nightly.yml, .gitlab/ci/slack-notify.yml, .gitlab/helper_functions.sh, Tests/scripts/check_jobs_done.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5323
=> fix build not done

Tests/scripts/collect_tests/constants.py, Tests/scripts/infrastructure_tests/test_collect_tests.py
Add [missing types](https://github.com/demisto/demisto-sdk/commit/90f08929e4303f022e6680a61b1f12efbca4bcdf#diff-555c51fe59132215b77801a3bb499d421ebd91468c9d7806cedced34215a3048)
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5372
=> fix test collection - new types

.gitlab/ci/on-push.yml
=> added missed job-done

.gitlab/ci/on-push.yml, Tests/Marketplace/marketplace_services.py, Tests/scripts/create_artifacts_graph/create_artifacts.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5194?filter=-1&jql=reporter%20%3D%20esharf
=> include test playbooks dependencies fix

Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling.yml, Packs/CortexXDR/Playbooks/Cortex_XDR_Alerts_Handling_README.md, Packs/CortexXDR/ReleaseNotes/4_10_3.md, Packs/CortexXDR/pack_metadata.json
=> Fix cortexxdrinchandlin fromversions

Tests/configure_and_test_integration_instances.py
Add exit after installation failed.
=> Add exit after installation failed.

Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml, Packs/AWS-S3/ReleaseNotes/1_2_13.md, Packs/AWS-S3/TestPlaybooks/playbook-AWS_-_S3_Test_Playbook.yml, Packs/AWS-S3/pack_metadata.json, Tests/conf.json
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-5203 
A part of the effort to add sections to existing top used packs:
AWS - S3
=> add sections to aws s3

Tests/scripts/infrastructure_tests/test_collect_tests.py
=> Add UT - validate number of FileType values

Packs/Exabeam/Integrations/Exabeam/Exabeam.py, Packs/Exabeam/ReleaseNotes/2_2_2.md, Packs/Exabeam/pack_metadata.json
=> Fixed an issue where the old authentication was not working properly

Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py, Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.yml, Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py, Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_20.md, Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20610
Fixed an issue where when there were no indicators, then fetch-indicators would fail on IndexError
=> CrowdStrike Feed - fixed issue in fetch-indicators

Tests/configure_and_test_integration_instances.py
=> Fix get identifier

Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json, Packs/CortexXDR/ReleaseNotes/4_10_6.md, Packs/CortexXDR/pack_metadata.json
fixes: N.A.
Fixed an issue when the DT isn't working with null in the `file_artifacts` object.
N.A.
=> XDR dt classifier change

Packs/Phishing/.pack-ignore, Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml, Packs/Phishing/Playbooks/Phishing_-_Generic_v3_README.md, Packs/Phishing/README.md, Packs/Phishing/ReleaseNotes/3_5_2.md, Packs/Phishing/pack_metadata.json
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5333
Improved the documentation for the Phishing Campaign pack inside the Phishing pack. The goal was to make it clearer that phishing campaign support requires another pack.
No
=> Improved documentation for campaigns in the phishing pack

Packs/Remedy-On-Demand/pack_metadata.json
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-5478
Adding the portfolio prefix to the "remedy" pack
=> bmc-remedy-on-demand

Packs/FiltersAndTransformers/ReleaseNotes/1_2_7.md, Packs/FiltersAndTransformers/Scripts/RegexReplace/RegexReplace.py, Packs/FiltersAndTransformers/Scripts/RegexReplace/RegexReplace.yml, Packs/FiltersAndTransformers/Scripts/RegexReplace/test_data/test-1.json, Packs/FiltersAndTransformers/pack_metadata.json
N/A
Fixed an issue where it doesn't work with None given to output_format.
[https://paloaltonetworks.zoom.us/rec/share/aXNP1cxoytu-GFBmGN7X87qNk9RJd0HHAwN6hXrBzWgEA3N0C_Lly2VH2Ky7pENL.UB2o3KCY6urAO7gi](https://urldefense.proofpoint.com/v2/url?u=https-3A__paloaltonetworks.zoom.us_rec_share_aXNP1cxoytu-2DGFBmGN7X87qNk9RJd0HHAwN6hXrBzWgEA3N0C-5FLly2VH2Ky7pENL.UB2o3KCY6urAO7gi&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=Ofm-xnwIyR-wX5Qd5Wta5yebOWzrIzmkRd55xrRodnY&m=o6nzpTeBAlfsyjAdPjwBJD6foD3TozE4flbhT_mNzAMKIoYuAiOzPEWiuINn2-LW&s=Cfbh2MgTI05gDiqbB4ZUvS1UJl_IDBK4na …
=> Fixed an issue where it doesn't work with None given to output_format.

Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-20748)
Documentation was added regarding playbook ID.
=> XSOAR Mirroring Integration

.github/workflows/auto-merge-dockers.yml
=> Auto-approve docker updates fix

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md, Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook.py, Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook.yml, Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook_description.md, Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/MicrosoftTeamsWebhook_test.py, Packs/MicrosoftTeams/Integrations/MicrosoftTeamsWebhook/README.md, Packs/MicrosoftTeams/ReleaseNotes/1_3_0.md, Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Webhook_-_Test.yml, Packs/MicrosoftTeams/pack_metadata.json, Tests/conf.json
fixes: [issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5408)
Added proxy + trust any cert support.
=> Teams webhook - proxy + trust any cert support

Packs/CommonScripts/ReleaseNotes/1_11_20.md, Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml, Packs/CommonScripts/pack_metadata.json
=> Fixing from version of the script

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
=> Fix TrendMicroVisionOne tests

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneV3/TrendMicroVisionOneV3_test.py
Replaces all instances of TrendMicro API to mock to fix UT network exceptions. Example log for failure in https://code.pan.run/xsoar/content/-/jobs/21171918.
=> Fix TrendMicroVisionOneV3 UT endpoints with mock

Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.py, Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml, Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_description.md, Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_test.py, Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_0.md, Packs/SEKOIAIntelligenceCenter/pack_metadata.json
The link was broken in the description
=> fix(sekoia-io-cti): broken link in description file

.gitlab/ci/on-push.yml
Fail the build step if test modeling rules fail.
=> Fail on failure test modeling rules

Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py, Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml, Packs/HashiCorp-Vault/ReleaseNotes/1_1_3.md, Packs/HashiCorp-Vault/pack_metadata.json
=> Hashicorp vault specific roles bug

Packs/Campaign/ReleaseNotes/3_2_18.md, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml, Packs/Campaign/pack_metadata.json, Tests/docker_native_image_config.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5249
This PR aligns the find email campaign to be able to use the native image as well
=> Align find email campaign script to native image

Packs/Netcraft/Integrations/Netcraft/Netcraft.yml, Packs/Netcraft/ReleaseNotes/1_0_15.md, Packs/Netcraft/TestPlaybooks/playbook-Netcraft_Test.yml, Packs/Netcraft/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20785
Deprecating. 
=> Deprecating Netcraft

Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.py, Packs/MicrosoftGraphUser/ReleaseNotes/1_5_12.md, Packs/MicrosoftGraphUser/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21042)
The param we used is incorrect - should be creds_auth_code and not creds_auth_id.
=> Azure active directory didn't work with Client Credentials

Packs/FiltersAndTransformers/ReleaseNotes/1_2_9.md, Packs/FiltersAndTransformers/Scripts/IfThenElse/IfThenElse.js, Packs/FiltersAndTransformers/pack_metadata.json
N/A
Fixed an issue where it broke a backward compatibility.
It didn't work when setting parameters to `condition` and `options`.
[https://paloaltonetworks.zoom.us/rec/share/3rFVJPnycheq0kjbLxaifXyWkxBgxtXEiLBHRY8PD9sbtN6PKIobpF3PR-wfsZdw.1_8XrG12fg1ZCxW2](https://urldefense.proofpoint.com/v2/url?u=https-3A__paloaltonetworks.zoom.us_rec_share_3rFVJPnycheq0kjbLxaifXyWkxBgxtXEiLBHRY8PD9sbtN6PKIobpF3PR-2DwfsZdw.1-5F8XrG12fg1ZCxW2&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=Ofm-xnwIyR-wX5Qd5Wta5yebOWzrIzmkRd55xrRodnY&m=7sQ2tR-utr4kVnw77iJ2gvXlWmWPSVLmuiHTxHQ5CzYqrPy …
=> Fixed an issue where it broke a backward compatibility.

.github/workflows/auto-merge-dockers.yml
Updated the watch checks step to watch only the required checks and increased the interval to 60 seconds
=> Updated the watch checks step

.github/workflows/check-devcontainer.yml
* Fixes updating the hashfile of the poetry when depednencies are updated
=> fix check devcontainer.json update

Packs/FiltersAndTransformers/pack_metadata.json
=> Added xpanse to FiltersAndTransformers

Packs/CommonTypes/.pack-ignore
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-5410
=> Ignore IF100

Packs/Netcraft/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-20785)
=> Hiding this pack after deprecating it

.gitlab/ci/on-push.yml
This should be reverted once Demisto-SDK 1.10.1 is released.
=> Temporary change to create graph

Packs/Rapid7_Nexpose/Playbooks/Rapid7_-_Nexpose_-_Enrichment.yml, Packs/Rapid7_Nexpose/ReleaseNotes/1_2_3.md, Packs/Rapid7_Nexpose/pack_metadata.json
[EXPANDR-90](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-90)
Updating input for a task in the Rapid7 - Nexpose - Enrichment playbook. Updating to match the [suggestion from a previous PR](https://github.com/demisto/content/pull/24147/files/677f9a2f4a2485db9ea3d349d105f5c4877829f3#r1092995468).
=> [ASM] - Updating Rapid7 - Nexpose - Enrichment playbook

Packs/AzureSentinel/pack_metadata.json
=> Microsoft-Sentinel-pack-desc

Tests/scripts/collect_tests/collect_tests.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5430
=> save incompatible marketplaces false

Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif, Packs/CheckpointFirewall/ReleaseNotes/2_3_8.md, Packs/CheckpointFirewall/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5141
=> Check Point FW - Compatibility with XDR mapping

package.json, poetry.lock, pyproject.toml
=> not module

.gitlab/ci/on-push.yml, Utils/should_trigger_test_upload.sh, Utils/test_upload_flow/wait_for_upload.py
Fixed the script to return the value into the job so the job will be skipped correctly.
=> Fixed should_trigger_test_upload script

.gitlab/ci/on-push.yml, Tests/scripts/create_artifacts_graph/create_artifacts.py
fixes: [CIAC-5562](https://jira-hq.paloaltonetworks.local/browse/CIAC-5562)
Fixed an issue where dependencies weren't created correctly for certain packs.
=> graph depedencies test

Packs/AzureEventsHub/ModelingRules/AzureEventsHub_1_3/AzureEventsHub_1_3.xif, Packs/AzureEventsHub/ReleaseNotes/1_0_4.md, Packs/AzureEventsHub/pack_metadata.json, Packs/BrocadeSwitch/ModelingRules/BrocadeSwitch_1_3/BrocadeSwitch_1_3.xif, Packs/BrocadeSwitch/ReleaseNotes/1_0_7.md, Packs/BrocadeSwitch/pack_metadata.json, Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif, Packs/CheckpointFirewall/ReleaseNotes/2_3_9.md, Packs/CheckpointFirewall/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5169)
=> Xdm.event.outcome bulk5

Packs/Core/ReleaseNotes/1_3_31.md, Packs/Core/Triggers/Trigger_-_Ransomware_Response.json, Packs/Core/Triggers/Trigger_-_T1486_-_Data_Encrypted_for_Impact.json, Packs/Core/Triggers/Trigger_-_XCloud_Cryptojacking.json, Packs/Core/pack_metadata.json
New triggers for Ransom and Cryptojacking alerts
=> XSIAM new triggers

Packs/CortexXDR/Integrations/CortexXDRIR/README.md
relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-20580)
Added the permissions needed for each command to the readme.
=> Jb xdr permission docs

Tests/conf.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5353)
Increased timeout for ExpanseV2 because the tests fail on timeout sometimes
=> Increased timeout for ExpanseV2

Packs/FireEyeCommonFields/pack_metadata.json
Removing dependencies to Phishing and Malware, since there is no reason for this pack to depend on them
=> removed mandatory dependencies of Phishing and Malware

.gitlab/ci/on-push.yml
Removing NG until the bugs are fixed
=> Removing NG until the bugs are fixed

.gitlab/ci/bucket-upload.yml
We will check if creating the graph every time in validate will avoid the false positives.
Then we will know where to focus in order to solve the bug.
@YuvHayun @dorschw FYI
=> dont upload graph files

.gitlab/ci/on-push.yml
fix jobs-done-check-nightly step to not fail if xsiam fails.
=> fix jobs-done-check-nightly

.devcontainer/createCommand.sh, .devcontainer/devcontainer.json
No need to use the native image for devcontainers
=> Devcontainer remove native python dependencies

Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py, Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml, Packs/AWS-SQS/ReleaseNotes/1_2_21.md, Packs/AWS-SQS/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/CIAC-5405
=> Sqs list bug

.pre-commit-config.yaml
=> Revert "pre-commit: add trailing-whitespace, end-of-file-fixer"

Packs/ApacheTomcat/README.md, Packs/ApacheWebServer/README.md, Packs/Auditd/README.md, Packs/BrocadeSwitch/README.md, Packs/CheckpointFirewall/README.md, Packs/CiscoASA/README.md, Packs/CiscoSMA/README.md, Packs/CiscoStealthwatch/README.md, Packs/CitrixADC/README.md, Packs/F5ASM/README.md, Packs/FireEyeNX/README.md, Packs/FortiGate/README.md, Packs/IllusiveNetworks/README.md, Packs/Infoblox/README.md, Packs/JuniperSRX/README.md, Packs/LinuxEventsCollection/README.md, Packs/OktaOAG/README.md, Packs/Oracle/README.md, Packs/SymantecEndpointProtection/README.md, Packs/ThinkstCanary/README.md, Packs/VMwareESXi/README.md, Packs/VMwareVCenter/README.md, Packs/ZscalerZPA/README.md, Packs/cisco-meraki/README.md, Packs/epo/README.md
=> change links

Tests/Marketplace/search_and_install_packs.py, Tests/configure_and_test_integration_instances.py, Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
Adding a sleep time after copying the bucket, should fix the issue that the pack is not found. 
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5718
=> Save more sleep time

Packs/Mimecast/Integrations/MimecastV2/README.md
See: https://panw-global.slack.com/archives/C011E5T5K17/p1676679596376009
=> Mimecast update README

Packs/Base/ReleaseNotes/1_31_68.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py, Packs/Base/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21656
Fixed an issue where the *look_back* parameter has an empty value.
=> Fixed an issue where look back parameter has empty value

Packs/PAN-OS/Integrations/Panorama/README.md
Update the README of panorama to include also panorama 10 support
=> update panorama readme

Packs/CortexXpanse/Layouts/layoutscontainer-Xpanse_Alert_Layout.json, Packs/CortexXpanse/ReleaseNotes/1_0_1.md, Packs/CortexXpanse/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-2916
The layout from ExpanseV2 pack was used to create the layout in this pack and in doing so we brought over some dependencies we didn't want.  Recreated layout from scratch (all the same information) and no longer have those dependencies.
N/A
=> [ASM] expandr 2916

Packs/Base/Scripts/DBotSuggestClassifierMapping/dbot_suggest_classifier_mapping_test.py
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5788
freeze datetimes in DBotSuggestClassifierMapping unit-tests
=> freeze time in unit-tests of DBotSuggestClassifierMapping

Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.py, Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2.yml, Packs/ThreatQ/Integrations/ThreatQ_v2/ThreatQ_v2_test.py, Packs/ThreatQ/ReleaseNotes/1_0_22.md, Packs/ThreatQ/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21447
Fixed an issue in the body format for reputation commands.
=> Fix ThreatQ Bug

Tests/Marketplace/marketplace_services.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-76679)
A bug was fixed in the metadata build stage when adding layout rule.
=> bug fix pack metadata

.gitlab/ci/on-push.yml
=> extend sleep

Packs/CommonScripts/ReleaseNotes/1_11_38.md, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py, Packs/CommonScripts/pack_metadata.json
=> SearchIncidentsV2 - Fix max page for paging

Packs/CommonScripts/ReleaseNotes/1_11_38.md, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py, Packs/CommonScripts/pack_metadata.json
=> Search incidents v2 fix paging

Packs/SEKOIAIntelligenceCenter/pack_metadata.json
=> SEKOIAIntelligenceCenter: change DevEmails

Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefense/InfobloxBloxOneThreatDefense.yml
=> fixup fromVersion for InfobloxBloxOneThreatDefense 

Packs/CommonScripts/ReleaseNotes/1_11_39.md, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21824)
=> Search incidents bug

Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/README.md
=> Proofpoint protection server: update README (typo)

.gitlab/ci/bucket-upload.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5853
=> always sync buckets

Packs/AWS-AccessAnalyzer/pack_metadata.json, Packs/AWS-SQS/pack_metadata.json, Packs/AWS-SecurityHub/pack_metadata.json, Packs/AzureDevOps/pack_metadata.json, Packs/AzureStorageQueue/pack_metadata.json, Packs/Gmail/pack_metadata.json, Packs/GmailSingleUser/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5039)
Added vendor name to data source packs "keywords".
=> Add keywords

Packs/EWS/ReleaseNotes/2_1_0.md, Packs/EWSMailSender/ReleaseNotes/1_1_18.md, Packs/EWSMailSender/ReleaseNotes/1_2_0.md
Fixed the EWS Mail Sender release notes version 1.2.0.
=> Fix EWS Mail Sender release notes

Packs/Tenable_io/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-1734
Update pack README.md.
=> Tenable.io pack readme

Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5738
doubled the memory threshold of the test.
=> [Tests] Office365_Feed_Test - memory threshold increase

Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5794
Fixing a failure test playbook that fails in nightly, by extending the timeout.
=> fix-failur-TestPlaybook(XDR)

Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM.yml, Packs/FireEyeCM/ReleaseNotes/1_1_19.md, Packs/FireEyeCM/pack_metadata.json
relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5831)
Added sections to the Fire eye central management integration
=> [Fire eye central management] Adding sections

Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX.yml, Packs/FireEyeEX/ReleaseNotes/2_0_13.md, Packs/FireEyeEX/pack_metadata.json
relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5831)
Added sections to the Fire eye email security integration
=> [Fire eye email security (ex)] Adding sections

Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml, Packs/FireEyeHX/ReleaseNotes/2_3_3.md, Packs/FireEyeHX/pack_metadata.json
relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5831)
Added sections to the Fire eye hx integration
=> [Fire eye hx] Adding sections

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml, Packs/DemistoRESTAPI/Integrations/DemistoRESTAPI/DemistoRESTAPI.yml, Packs/DemistoRESTAPI/ReleaseNotes/1_3_19.md, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://marketplace.xsoar.paloaltonetworks.com/)
=> Core Rest API fix default marketplace URL

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml, Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py, Packs/MicrosoftGraphMail/ReleaseNotes/1_4_12.md, Packs/MicrosoftGraphMail/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21656
Fixed an issue where fetch-incidents from a folder that the user moved emails to doesn't work.
=> Fix fetch-incidents occurred field MSGraphMail

Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.py, Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_21.md, Packs/PaloAltoNetworks_IoT/TestPlaybooks/playbook-PaloAltoNetworks_IoT-Test.yml, Packs/PaloAltoNetworks_IoT/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5461)
- fix test playbook
- fix fetch incidents error
=> Fix PaloAltoNetworks_IoT-Test

Packs/SkyhighSecurity/Integrations/SkyhighSecurity/SkyhighSecurity.py, Packs/SkyhighSecurity/ReleaseNotes/1_0_4.md, Packs/SkyhighSecurity/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21854)
Fixed an issue where the **Skyhigh Security** integration didn't work with proxy.
=> Fix skyhigh security proxy issue

Tests/conf.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5704)
Set **Test XDR Playbook retrieve file command** timeout to 500
=> Increase Test XDR Playbook retrieve file command timeout

Tests/conf.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5606)
Set **EvaluateMLModllAtProduction-Test** timeout to 500
=> Increase EvaluateMLModllAtProduction-Test timeout

Packs/SumoLogic_Cloud_SIEM/IncidentFields/incidentfield-Sumo_Logic_Cloud_SIEM_Insight_Signals.json, Packs/SumoLogic_Cloud_SIEM/ReleaseNotes/1_1_8.md, Packs/SumoLogic_Cloud_SIEM/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5652
=> Fix incidentfield sumourl

Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md, Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring.yml, Packs/XSOARmirroring/Integrations/XSOARmirroring/XSOARmirroring_description.md, Packs/XSOARmirroring/Integrations/XSOARmirroring/command_examples, Packs/XSOARmirroring/ReleaseNotes/2_0_13.md, Packs/XSOARmirroring/pack_metadata.json
related: https://jira-hq.paloaltonetworks.local/browse/XSUP-21831, https://jira-hq.paloaltonetworks.local/browse/XSUP-21430
Updated the documentation of XSOAR Mirroring pack, to be more understandable and right, as the documentation was not updated even when the pack has changed significantly.
=> XSOAR Mirroring docs update

Tests/Marketplace/approved_categories.json
This reverts commit c372388e416d388d2e96c136663673933a67ae51.
In addition, it adds `Messaging and Conferencing` to the approved categories because some of the content was changed.
=> Revert "adjustments to the pack categories (#24985)"

Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/README.md
=> Fixe README tags

Packs/SymantecEDR/pack_metadata.json
=> symantec-edr-pack-name-change

Utils/github_workflow_scripts/handle_external_pr.py
=> Change contribution form automatic message

Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5602)
Update the host id in the playbook
=> Fix Test - CrowdStrike Falcon

Packs/ThreatGrid/Integrations/ThreatGrid/1_8490e145-c880-4802-a995-9ec32e4f82e2, Packs/ThreatGrid/Integrations/ThreatGridv2/README.md, Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py, Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml, Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py, Packs/ThreatGrid/ReleaseNotes/2_0_3.md, Packs/ThreatGrid/pack_metadata.json
=> Update url argument description

Utils/github_workflow_scripts/handle_external_pr.py
Changing the list of reviews, to get contributions faster.
=> Setting me first

Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_description.md, Packs/RecordedFuture/ReleaseNotes/1_3_4.md, Packs/RecordedFuture/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5966
Fixed the docs link in the integration description file since the link was broken (404)
=> [RecordedFuture] Fixed docs link

Packs/MicrosoftDefenderAdvancedThreatProtection/CorrelationRules/MicrosoftDefenderAdvancedThreatProtection_correlation-rule.yml, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_15.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22097
Alert field mapping update - `xdm.target.process.command_line` mapped to `Initiator CMD` field.
=> Mapping field defender correlation rule

Packs/FiltersAndTransformers/Scripts/TimeComponents/test_data/test.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5982)
Fix unit-test failure.
See JIRA ticket for context about the issue.
=> [TimeComponents] Fix Unit-Test Failure

Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py, Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX_test.py, Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_24.md, Packs/CrowdStrikeFalconX/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21683
Fixed an issue where the ***cs-fx-get-full-report*** command failed due to unexpected structure of the API response.
=> csfalconx parse indicator bugfix

Packs/PrismaCloud/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5660
Remove mandatory dependencies for Prisma Cloud and make them not-mandatory.
=> Remove mandatory dependencies for Prisma Cloud

Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml, Packs/SymantecDLP/ReleaseNotes/2_0_9.md, Packs/SymantecDLP/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22313
Fixed the parameter IncidentStatusID type
=> St symantec dlp yml fix

Packs/NetscoutAED/Integrations/NetscoutAED/NetscoutAED_description.md, Packs/NetscoutAED/ReleaseNotes/1_0_17.md, Packs/NetscoutAED/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6003
=> update Netscout description

Packs/Kubernetes/README.md
Added backticks to the code to prevent marketplace build failures.
=> [Kubernetes] fix the Readme file

Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector_1_3/CyberArkIdentityEventCollector_1_3.xif, Packs/CyberArkIdentity/ReleaseNotes/1_0_17.md, Packs/CyberArkIdentity/pack_metadata.json
This PR is created to update the modeling rules of CyberArk Identity.
=> Fix for CyberArk Identity Modeling Rules

Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py, Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml, Packs/AWS-S3/ReleaseNotes/1_2_14.md, Packs/AWS-S3/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22430
Moved the demisto.command statement to be called first so it could be successfully printed as part of later exceptions
=> Aws s3 handle print

Packs/CommonScripts/ReleaseNotes/1_11_54.md, Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.yml, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5999
=> Revert docker update - DBotUpdateLogoURLPhishing

.circleci/config.yml, .gitlab/ci/global.yml, .gitlab/ci/on-push.yml, .gitlab/helper_functions.sh, Tests/scripts/check_jobs_done.py
=> Testing for moving linter to gitlab

Packs/CortexAttackSurfaceManagement/.pack-ignore, Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Detect_Service.yml, Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_5_9.md, Packs/CortexAttackSurfaceManagement/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/EXPANDR-3212
Changes to update regex to detect Insecure Openssh banner less than 9.2
=> [ASM] - EXPANDR-3212 Updating regex to detect Insecure Openssh

Packs/Base/ReleaseNotes/1_31_77.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json
Related PR: https://github.com/demisto/dockerfiles/pull/12682
=> Update sane-pdf-report script with new docker image

Packs/Reco/Integrations/Reco/README.md, Packs/Reco/Integrations/Reco/Reco.py, Packs/Reco/Integrations/Reco/Reco.yml, Packs/Reco/Integrations/Reco/Reco_test.py, Packs/Reco/README.md, Packs/Reco/ReleaseNotes/1_0_2.md, Packs/Reco/pack_metadata.json
=> Reco add new commands

Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py, Packs/TaniumThreatResponse/ReleaseNotes/2_1_10.md, Packs/TaniumThreatResponse/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21485
=> Tanium Threat Response - list alerts fix

.gitlab/ci/global.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6046?filter=-2
=> Fix upload coverage report in nightly

Packs/MajorBreachesInvestigationandResponse/README.md
changed the hyperlink to the new pack instead of playbook
=> Fix an issue with playbook hyperlink

Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Alert_Summary.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Asset_ID.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Cloud.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Notification.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Private_IP.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Remediation_Path_Rule.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_ID.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Service_Owner.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_System_IDs.json, Packs/CortexAttackSurfaceManagement/IncidentFields/incidentfield-ASM_-_Tags.json, Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_0.md, Packs/CortexAttackSurfaceManagement/pack_metadata.json
[Custom Alerts project](https://confluence.paloaltonetworks.local/display/XPANSE/Ev2.2+-+One+Pager+-+AR+Alert+Custom+Layouts)
Updating ASM fields for hidden attribute from true to false.
=> [ASM] - Update ASM fields hidden attribute to false

Packs/Core/Layouts/layoutscontainer-Default.json, Packs/Core/Layouts/layoutscontainer-Default_XDR_Alert.json, Packs/Core/ReleaseNotes/1_3_45.md, Packs/Core/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-78452)
=> XSIAM Layouts Fix

Tests/scripts/check_jobs_done.py
The run unit tests job name was renamed. We need to update this script to the new names so we will be able to tell this job is done.
=> fixed jobs done for upload

Utils/gitlab/stop_running_pipelines.sh
this PR makes sure that we are canceling only older builds.
=> added -gt instead != in pipelines stop util

Packs/jamf/README.md
This PR updates the Jamf README file to correspond with the new data sources page.
=> Updating Jamf README

.gitlab/ci/on-push.yml, Tests/scripts/lock_cloud_machines.py
=> adding back the NG job

Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml, Packs/ArcherRSA/ReleaseNotes/1_2_7.md, Packs/ArcherRSA/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-22350)
Improved parameter documentation.
=> Archer - improve parameter description

Packs/PrismaCloud/ModelingRules/PrismaCloud/PrismaCloud.xif, Packs/PrismaCloud/ReleaseNotes/3_0_4.md, Packs/PrismaCloud/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5079)
=> Prisma cloud correction

Packs/MicrosoftCore/README.md, Packs/MicrosoftCore/pack_metadata.json
This PR fixes the READMe of the Microsoft Logs Base pack and updates it with the relevant name.
=> Microsoft Logs Base README Fix

Packs/qualys/.pack-ignore
@altmannyarden fyi
Ignore the incident word in the QualysCreateIncidentFromReport.yml
=> Ignore the incident word in the qualys

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py, Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml, Packs/HatchingTriage/ReleaseNotes/1_0_9.md, Packs/HatchingTriage/pack_metadata.json
Add user_tags argument to sample submission command, add possible option to network argument, and update user-agent used.
=> HatchingTriage v1.0.9 - Add user tags to sample submit

Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Domain_Abuse_Layout.json, Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Playbook_Alert.json, Packs/RecordedFuture/Layouts/layoutscontainer-Recorded_Future_Vulnerability_Layout.json, Packs/RecordedFuture/ReleaseNotes/1_5_1.md, Packs/RecordedFuture/pack_metadata.json
Fixed RecordedFuture layouts to be only XSOAR supported to fix the [validation errors](https://code.pan.run/xsoar/content/-/jobs/23926572)
=> Fixed RecordedFuture layouts

Packs/Code42/.pack-ignore
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-5580
=> The last file to ignore validation BA124 from

Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.py, Packs/AWS-CloudWatchLogs/Integrations/AWS-CloudWatchLogs/AWS-CloudWatchLogs.yml, Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_17.md, Packs/AWS-CloudWatchLogs/pack_metadata.json, Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.py, Packs/AWS-EC2/Integrations/AWS-EC2/AWS-EC2.yml, Packs/AWS-EC2/ReleaseNotes/1_2_33.md, Packs/AWS-EC2/pack_metadata.json, Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.py, Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml, Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/AWSGuardDutyEventCollector.py, Packs/AWS-GuardDuty/Integrations/AWSGuardDutyEventCollector/AWSGuardDutyEventCollector.yml, Packs/AWS-GuardDuty/ReleaseNotes/1_3_17.md, Packs/AWS-GuardDuty/pack_metadata.json, Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.py, Packs/AWS-Lambda/Integrations/AWS-Lambda/AWS-Lambda.yml, Packs/AWS-Lambda/ReleaseNotes/1_2_35.md, Packs/AWS-Lambda/pack_metadata.json, Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py, Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml, Packs/AWS-S3/ReleaseNotes/1_2_16.md, Packs/AWS-S3/pack_metadata.json, Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py, Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml, Packs/AWS-SecurityHub/ReleaseNotes/1_2_2.md, Packs/AWS-SecurityHub/pack_metadata.json, Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py, Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-484
Added support for PrivateLink connections. ([docs](https://docs.aws.amazon.com/vpc/latest/privatelink/privatelink-share-your-services.html))
=> AWS private link support

.github/workflows/auto-merge-dockers.yml
=> Changed action name

Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml, Packs/AutoFocus/ReleaseNotes/2_1_5.md, Packs/AutoFocus/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5869
Deprecate AutoFocues tags feed
=> Deprecate AutoFocues tags feed

Packs/AWS-Enrichment-Remediation/.pack-ignore
=> Ignore RM108 for AWS README file

Packs/FiltersAndTransformers/Scripts/ModifyDateTime/README.md
replace broken links:
 https://dateparser.readthedocs.io/en/latest/\#relative\-dates
https://dateparser.readthedocs.io/en/latest/\#popular\-formats
to: 
https://dateparser.readthedocs.io/en/latest/#relative-dates
https://dateparser.readthedocs.io/en/latest/#popular-formats
=> replace broken readme links - modify date time

Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py, Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml, Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2_test.py, Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_31.md, Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
https://github.com/cohesity/cortex-xsoar/pull/1
=> CBR v2 endpoint fix

Packs/AWS-Enrichment-Remediation/.pack-ignore, Packs/AWS-Enrichment-Remediation/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6199
changed commit hash to master and removed ignore. all links in the readme now work
=> Fixed broken images in AWS S3

Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py, Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml, Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector_test.py, Packs/Netskope/ReleaseNotes/3_0_13.md, Packs/Netskope/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22801
Added dedup mechanism to avoid duplicate events
=> Netskope collector fix

Packs/Stairwell/Integrations/Inception/Inception.py, Packs/Stairwell/Integrations/Inception/Inception.yml, Packs/Stairwell/Integrations/Inception/Inception_test.py, Packs/Stairwell/Integrations/Inception/test_data/file_enrichment_command_result.json, Packs/Stairwell/ReleaseNotes/1_0_4.md, Packs/Stairwell/pack_metadata.json
Update human-readable output with new Mal-Eval verdict data
=> Add support for Mal-Eval

Packs/CortexDataLake/CONTRIBUTORS.json, Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py, Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml, Packs/CortexDataLake/ReleaseNotes/1_4_4.md, Packs/CortexDataLake/pack_metadata.json
- [ X ] Ready
Two CDL queries for threat logs do not include the ThreatName field and the output fields do not either, updating to include that useful value
- [ X ] No
=> updating CDL integration to add ThreatName to two threat log queries

.github/workflows/auto-merge-dockers.yml
Added `sleep` step, so the action will wait till Gitlab pipeline will start running.
=> Added sleep step to wait till gitlab start running

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py, Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml, Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_20.md, Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3519
Improved error message for ***wildfire-upload*** command when providing unsupported files.
=> [WildFire] Improve error message when failing to upload an unsupported file

Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization_README.md, Packs/PrismaCloud/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6246
Adding video to PrismaCloud Pack Readme file and playbook readme.
=> Adding video to PrismaCloud Pack 

Packs/CoreAlertFields/IncidentFields/incidentfield-Email_Subject.json, Packs/CoreAlertFields/ReleaseNotes/1_0_24.md, Packs/CoreAlertFields/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6220
Fixing unmapped "Email Subject" field
=> Email subject unmapped

Packs/Base/ReleaseNotes/1_31_87.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.py, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json, Packs/CommonScripts/ReleaseNotes/1_11_60.md, Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.py, Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5986)
Occasionally, the condition is not consistent, leading to a contradiction between the coverage carried out in Nightly and the coverage when running the build.
This comment prevents the coverage calculation for the code inside the condition and thus resolves the issue
=> '# pragma no cover' for solving the coverage problem

Packs/RTIR/Integrations/RTIR/RTIR.py, Packs/RTIR/Integrations/RTIR/RTIR.yml, Packs/RTIR/ReleaseNotes/1_0_14.md, Packs/RTIR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22905
custom fields was not set properly in content variable in post request. due to new line,
=> Fix content variable in edit ticket post req.

Packs/Luminate/Integrations/Luminate/Luminate.py, Packs/Luminate/ReleaseNotes/1_0_5.md, Packs/Luminate/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6268
fixing broken python syntax code in Luminate pack.
=> fixing broken python code

Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys.yml, Packs/qualys/Playbooks/playbook-Launch_And_Fetch_Scan_Based_Findings_Report_-_Qualys_README.md, Packs/qualys/ReleaseNotes/1_2_4.md, Packs/qualys/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6270
- Added *InfoFile* playbook outputs to **Launch And Fetch Scan Based Findings Report - Qualys** playbook.
=> [Qualys V2] Add outputs to Launch And Fetch Scan Based Findings Report - Qualys

Packs/Slack/Integrations/SlackV3/SlackV3.py, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/Integrations/SlackV3/SlackV3_test.py, Packs/Slack/ReleaseNotes/3_1_31.md, Packs/Slack/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22898
a wrong condition cause the bug that user message was considered as bot message and ignored
=> SlackV3: fix missing user messages

Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling.yml, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_True_Positive_Incident_Handling_README.md, Packs/CortexXDR/ReleaseNotes/4_10_32.md, Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6284
The 'URL_or_Domain' playbook input value is configured to get the 'Domain' context key and append the 'URL' phrase, instead of appending the 'URL' context key value.
=> Cortex XDR - True Positive Incident Handling - fix playbook inputs

Packs/GigamonThreatINSIGHT/ReleaseNotes/1_0_2.md, Packs/GigamonThreatINSIGHT/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6271
change support from partner to community.
=> change_to_community

.github/workflows/protect-infra-directories.yml
fixes: everything
Sometimes we miss a little dot.
=> Fix path issue in protected dir validation

Packs/CommonScripts/ReleaseNotes/1_11_62.md, Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.py, Packs/CommonScripts/Scripts/ResolveShortenedURL/ResolveShortenedURL.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23432)
Add an option to use a proxy when using the `ResolveShortenedURL` script.
=> [ResolveShortenedURL] Add Proxy Support

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md, Packs/CortexXDR/Integrations/CortexXDRIR/README.md, Packs/CortexXDR/ReleaseNotes/4_10_34.md, Packs/CortexXDR/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/CRTX-80426
Fix instructions for Get URL
=> Fix instructions for Get URL

Packs/VMwareVCenter/ParsingRules/VMwareVcenterParsingRules/VMwareVcenterParsingRules.xif, Packs/VMwareVCenter/ReleaseNotes/1_0_6.md, Packs/VMwareVCenter/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23590)
=> Vmware Vcenter Parsing Logic Update

Packs/DuoAdminApi/ModelingRules/DuoModelingRule_1_3/DuoModelingRule_1_3_schema.json, Packs/DuoAdminApi/ReleaseNotes/3_2_11.md, Packs/DuoAdminApi/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23597
=> Duo modelingrules schema fix

Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6329)
Fixed task no. 69 in the test playbook because of a nightly failure
=> Fix/CIAC 6329/fix TPB test CrowdStrike falcon

Packs/Zendesk/Integrations/Zendeskv2/README.md, Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.py, Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2.yml, Packs/Zendesk/Integrations/Zendeskv2/Zendeskv2_test.py, Packs/Zendesk/ReleaseNotes/2_0_6.json, Packs/Zendesk/ReleaseNotes/2_0_6.md, Packs/Zendesk/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5507
changed zendesk fetch incidents mechanism to support fetch query parameter + more filters
decided to mark this version as a breaking changes version.
this will probably lead to some duplicate incidents.
=> zendesk fetch query

Packs/CloudflareWAF/.pack-ignore, Packs/CloudflareWAF/ModelingRules/CloudflareWAF/CloudflareWAF_schema.json, Packs/CloudflareWAF/ReleaseNotes/1_0_13.md, Packs/CloudflareWAF/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6373
=> Modify schema file couldflare waf

Packs/CortexXDR/.pack-ignore, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256.yml, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Retrieve_File_by_sha256_README.md, Packs/CortexXDR/ReleaseNotes/4_10_35.md, Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6357
Replacing the 'Print Error - No path was found' task automation from 'print' to 'PrintErrorEntry' automation.
=> Fix For 'Cortex XDR - Retrieve File by sha256' playbook

Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3.xif, Packs/VMwareVCenter/ReleaseNotes/1_0_7.md, Packs/VMwareVCenter/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23813)
=> Vmware Vcenter Modeling Rule Fix

Packs/VMwareVCenter/ModelingRules/VMwareVcenter_1_3/VMwareVcenter_1_3.xif, Packs/VMwareVCenter/ReleaseNotes/1_0_8.md, Packs/VMwareVCenter/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23813)
=> Vmware Vcenter ModelingRule Fix2

Packs/Base/ReleaseNotes/1_31_92.md, Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py, Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml, Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery_test.py, Packs/Base/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-23820
A fix to the empty fields issue.
=> Fix empty fields issue

Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Contributor asked to temporarily hide the MandiantAdvantageThreatIntelligence pack.
=> Temporary hide MandiantAdvantageThreatIntelligence pack

.devcontainer/devcontainer.json, Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.py, Packs/OctoxLabs/Integrations/OctoxLabs/OctoxLabs.yml, Packs/OctoxLabs/ReleaseNotes/1_1_4.md, Packs/OctoxLabs/pack_metadata.json
Octox Labs Cyber Security Asset Management platform XSoar Integration update.
=> fix: octoxlabs device function

Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py, Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml, Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_29.md, Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Improving the logs of the fetch-incidents in Microsoft Defender for Cloud Apps
=> Ms cloud app sec improve logs

Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py, Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml, Packs/Box/ReleaseNotes/3_1_21.md, Packs/Box/pack_metadata.json
=> [Box] Fix LastRun setting in event collector

Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py, Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.yml, Packs/Box/ReleaseNotes/3_1_21.md, Packs/Box/pack_metadata.json
- [] Ready
Fixes several integration configuration/operation issues created by recent XSOAR platform changes.
=> Fix several integration issues created by recent XSOAR platform changes.

.gitlab/ci/on-push.yml
=> Change NG job to be required

Packs/FireEyeHX/Integrations/FireEyeHXEventCollector/FireEyeHXEventCollector.py, Packs/FireEyeHX/Integrations/FireEyeHXEventCollector/FireEyeHXEventCollector.yml, Packs/FireEyeHX/ReleaseNotes/2_3_6.md, Packs/FireEyeHX/pack_metadata.json
=> [FireEyeHX] Fix LastRun setting in event collector

Packs/CloudflareWAF/ParsingRules/CloudflareWAF/CloudflareWAF.xif, Packs/CloudflareWAF/ReleaseNotes/1_0_14.md, Packs/CloudflareWAF/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6411
=> Cloudflare fix timestamp

Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml, Packs/CommonPlaybooks/ReleaseNotes/2_3_61.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6416
- Fixed the condition in task 58 `Is there a manager?` where it was also needed to verify that `MSGraphUser.ID` also exist.
- Fixed an issue in task 54. The playbook input `UserEmail` value was changed from `Account.Email.Address` to `Account.Email`.
=> Account enrichment fix

Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.py, Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml, Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector_test.py, Packs/Mimecast/ReleaseNotes/2_1_7.md, Packs/Mimecast/pack_metadata.json
=> [Mimecast] Fix LastRun setting in event collector

Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.py, Packs/NetBox/Integrations/NetBoxEventCollector/NetBoxEventCollector.yml, Packs/NetBox/ReleaseNotes/1_0_4.md, Packs/NetBox/pack_metadata.json
=> [Netbox] Fix LastRun setting in event collector

Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py, Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml, Packs/Netskope/ReleaseNotes/3_0_14.md, Packs/Netskope/pack_metadata.json
=> [Netskope] Fix LastRun setting in event collector

Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.py, Packs/OneLogin/Integrations/OneLoginEventCollector/OneLoginEventCollector.yml, Packs/OneLogin/ReleaseNotes/1_0_4.md, Packs/OneLogin/pack_metadata.json
=> [OneLogin] Fix LastRun setting in event collector
