demisto/content

- Scripts/script-PublishEntriesToContext.yml
Mostly to be used with `context.lastCompletedTaskEntries`.
> Allow publishing of entries to context

- Scripts/script-CommonServerPython.yml
1. Name is not required, so it won't print it if not provided
2. Added the ability to define headers order (if not provided, the default behaviour will be used)
> Fixed the table to markdown function

- Scripts/script-TrendMicroClassifier.yml
Added trendmicro-alert-status dependency, so the classifier script won't show up in CLI if no trendmicro instance is configured
> Added dependency on trendmicro-alert-status command

- Scripts/script-commentsToContext.yml
Use case: analyst puts some comments on a manual task he is doing. Later in playbook a task takes those comments and adds them to a sent email. (SureScripts)
> utility to add specific entry comments to context

- Scripts/script-ParseEmailFile.yml
Simple fix as there was a type that came back as ASCII text, with very long lines, with CRLF line terminators which seemed to fix the problem. Might need further review down the road if there are other issues
> Fix for type that came back as with very long lines. 

- Scripts/script-AssignAnalystToIncident.yml
If isRandom is 'yes' (default) the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
If isRandom is 'no' the less busy analyst will be picked to be the incident owner.
Please run it as well and do some tests (I think I covered everything, but need to verify)
> Assign analyst to incident utility

- Integrations/integration-LogRhythm.yml
In case there were no incidents found on the return a json of an empty array.
so there will be no errors in the server
> LR fetch incidents return on empty value

- Playbooks/playbook-Account_Enrichment.yml
- Playbooks/playbook-PhishingAutomated.yml
1. Set sender properly into context
2. Use the sender from incident label instead of context, since context can contain many other emails as well
> Fix phishing playbook

- Scripts/script-DataHashReputation.yml
- Scripts/script-DataIPReputation.yml
- Scripts/script-DataURLReputation.yml
Changing all dataXreputataion to take manual reputation before checking threat intel services.
Please review but do not merge. Once changes are agreed upon, will redo the changes in the other scripts.
> DataXreputation manual override

- release_notes.py
@meirwah has noticed that if file is renamed in some PR (& merged) and in a later PR modified - the build fails
This fix support this scenario
> handle `R093` Status

- Scripts/script-AreValuesEqual.yml
In order to handle correctly situations where one of the arguments is empty/missing - returning no instead of raising an error in the playbook and awaiting users intervention
> AreValuesEqual - making arguments non-mandatory

- release_notes_clear.py
Fixes: https://github.com/demisto/server/issues/8575
added a stand-alone script that removes all release notes from json\yml files
> Release notes reset automation

- Scripts/script-EmailAskUserResponse.yml
1. using setContext to override the value every time an EmailAskUser flow is executed
2. not declaring it, so if used as conditional task, user can set its labels as needed. System still shows this key in the Source window...
> EmailAskUserResponse - Adding user's response to context

- Scripts/script-ParseEmailFiles.yml
When raw messages are retrieved from a server, there sometimes have mixed line terminations. These messages are still parsable by Python's email module, but the filetype string is not recognized in this Script.
> Adding support for mixed CR/LF in ParseEmailFiles

- Scripts/script-CreateEmailHtmlBody.yml
1. added ability to provide placeholder values as an object
2. returning the HTML body for use with non-incident scenarios (pre-processing)
3. removed args as no needed anymore
4. adding outputs
> CreateEmailHtmlBody improvement

- Integrations/integration-Wildfire.yml
Ignoring sha1 hashes so it doesnt break playbooks
> Wildfire fix - ignoring SHA1

- Scripts/script-CommonServer.yml
In case no path was given to the function as argument, in the first iteration path would be undefined.key[0], which causes errors.
> Updating flattenFields

- Playbooks/playbook-QRadar_-_Get_offense_correlations_.yml
- Scripts/script-QRadarClassifier.yml
- Scripts/script-QRadarFullSearch.yml
- Scripts/script-QRadarGetCorrelationLogs.yml
- Scripts/script-QRadarGetOffenseCorrelations.yml
Added playbook
* `QRadar - get offense correlations`
Updated qradar scripts:
* `QRadarClassifier` - deprecated (use mapping feature instead)
* `QRadarFullSearch` - fix bug
* updated context output in rest
> QRadar - get offense correlations

- Integrations/integration-AnomaliThreatStream.yml
So when there are no returns it will mention the integration name
> Add Anomali ThreatStream to no records response

- TestPlaybooks/playbook-CB-Response-Test.yml
Don't know why till now it worked. But most probably something changed.
Same session was exported to the context, so the step cb-close-session was executed twice. The first run it closed the session, but second time the session was already closed so we got exception 404
> fix Carbon Black Response test playbook

- Scripts/script-EmailAskUserResponse.yml
ignoring multiline `script` and `style` blocks
> ignore multi-line html code

- Integrations/integration-GRR.yml
Right now user has to wrap the input in `[]` and it's pretty hard to escape backslashes.
Before:
`paths="[\"c:\\\\documents\\\\a.txt\"]"`
After:
`paths="c:\\documents\\a.txt"`
also support old method for backward compatibility
> Fix GRR paths input

- Scripts/script-ExtractDomain.yml
- Scripts/script-ExtractURL.yml
remove unused `filter` variable from ExtractDomain & ExtractURL
we are now filter only by indicators whitelist
> Remove unused variable

- Scripts/script-GeneratePassword.yml
There was a leftover comment referencing "default_sane" parameter which has been removed.
> Fix error in GeneratePassword documentation.

- Tests/scripts/run_installer_on_instance.sh
- circle.yml
- content_creator.py
related to: https://github.com/demisto/etc/issues/10403
create 2 artifacts zip files:
- `content_yml.zip` - contains all content artifacts up to 3.5
- `content_new.zip` - contains all content artifacts 
tested against 2.6.1, 3.0.1, 3.1.0 & master
leftovers:
- json
- update wiki docs
server PR: https://github.com/demisto/server/pull/10230
very good work of @yaakovi 👍
> Artifacts separation for new version

- Playbooks/playbook-CrowdStrike_Endpoint_Enrichment.yml
- Playbooks/playbook-Endpoint_Enrichment_-_Generic.yml
- Tests/scripts/server_get_artifact.sh
We have changed transformers args to support complex args are well (i.e also take args from context)
this will upgrade playbooks transformers to the new schema
I also ran this branch against server `transformers-args` branch (contains the new schema) - https://circleci.com/gh/demisto/content/6460
will merge this after server build 
plz approve :)
> Upgrade transformers args

- Tests/scripts/create_instance.sh
- Tests/scripts/pull_docker_images.sh
- Tests/test_content.py
- Tests/test_integration.py
- circle.yml
- run test playbook second time if for the first time it failed
- increase the timeout for getting incident (from 3 seconds to 10)
- pull docker images before the tests started to run
> Rerun test playbook if failed

- Playbooks/playbook-CrowdStrike_Falcon_Sandbox_-_Detonate_file.yml
- Playbooks/playbook-Detonate_File_-_Generic.yml
- Playbooks/playbook-WildFire_-_Detonate_file_.yml
Made all playbooks inputs not to be mandatory and added task in CS Falcon Sandbox to check if there exists a file to detonate through it.
> Detonate file playbooks fix

- Integrations/integration-VirusTotal.yml
In the VT Integration, if you scan a file hash and no results are returned,
the context adds an entry with Type 'file', however in all other cases it
adds Type 'hash' to the context. This fixes the behavior to consistently apply
'hash' in all cases.
related https://github.com/demisto/content/pull/1263
> Fix Type for hashes when no results are returned

- Widgets/widget-CPUUsageAvg.json
- Widgets/widget-DiskUsageAvg.json
- Widgets/widget-MemoryUsageAvg.json
`currencySign` is not replaced with `sign` for backward compatibility
> Fix sign alignment

- Scripts/script-CommonServerPython.yml
Improved condition that checks if cell value is `null` in tableToMarkdown
> tableToMarkdown null removal fix

- Integrations/integration-Pipl.yml
Fixes https://github.com/demisto/etc/issues/10408
If an email is returned, then it is returned in an object with key `Address` and value that contains the address, so it is enough to change only the context path in order to fix the issue.
> Pipl integration email context path fix

- Scripts/script-ParseEmailFiles.yml
Added section to strip non-utf chars, so script doesn't fail
When non utf chars are stripped - original is stored as file so it can be parsed and get IOC extracted from
> better handling of non utf chars

- release_notes.py
related to https://github.com/demisto/etc/issues/11463
temporary disabled release notes. disable this allows others to keep pushing to master
working on a better solution for having release notes for incident fields
> temporary disable release notes

- Scripts/script-CommonServerPython.yml
- TestPlaybooks/script-TestPyCommonServer.yml
tableToMarkdown - if the response was empty, then in previous version it resulted an error
new branch due to other changes made in this function
> tabletomarkdown - handling with empty response

- Scripts/script-Ping.yml
I kept the (weird) `ping_result` default context key for backward compatibility.
Also changed the `verbose` argument to be predefined.
> Added Ping results as output

- Playbooks/playbook-ATD-sandbox.yml
- Playbooks/playbook-Archer_initiate_incident.yml
- Playbooks/playbook-Arcsight_-_Get_events_related_to_the_Case.yml
- Playbooks/playbook-D2_-_Endpoint_data_collection.yml
- Playbooks/playbook-Endpoint_data_collection.yml
- Playbooks/playbook-Enrich_DXL_with_ATD_verdict.yml
- Playbooks/playbook-Enrich_McAfee_DXL_using_3rd_party_sandbox.yml
- Playbooks/playbook-Get_File_Sample_From_Hash_-_Generic.yml
- Playbooks/playbook-MAR_-_Endpoint_data_collection.yml
- Playbooks/playbook-Packetsled.yml
- Playbooks/playbook-Process_Email.yml
- Playbooks/playbook-QRadar_-_Get_offense_correlations_V3_1_0.yml
- Playbooks/playbook-Sentinel_One_-_Endpoint_data_collection.yml
- Playbooks/playbook-TIE_-_IOC_Hunt.yml
- Playbooks/playbook-WildFire_-_Detonate_file_V3_1_0.yml
- Tests/schemas/playbook.yml
- content_creator.py
All playbook should have `fromversion` attribute
- added `fromversion: "3.5.0"` to Archer playbook
- added `fromversion: ""` to missing playbooks (though we can use also `fromversion: "2.5.0"`)
- change `fromversion` to be required in schema validation
> Enforce playbooks fromversion

- Integrations/integration-Okta.yml
Fixed missing break on switch-case. It caused unnecessary execution of a command.
> Okta bug fix

- Tests/conf.json
Trustar had some issues so we moved the test to nightly (see https://github.com/demisto/content/pull/1596)
Now the issues are resolved, so we are reactivating the test.
Issue: https://github.com/demisto/etc/issues/11776
> Reactivate trustar test

- .circleci/config.yml
- Tests/conf.json
- Tests/scripts/run_tests.sh
example: https://circleci.com/gh/demisto/content/9398#artifacts/containers/0
Now server logs are added (destroy step is always running) when build fails.
> Circleci 2 server log on fail build

- Scripts/script-ParseEmailFiles.yml
Print both email body parts - Text and HTML in the war room entry response.
Fixes https://github.com/demisto/etc/issues/11934
do not merge until final confirmation
> print both email body parts

- Integrations/integration-PhishTank.yml
Updated context according to the standard, so the url address will always be pushed to context under `URL.Data` and not only when the url is malicious.
> PhishTank integration context update

- Scripts/script-DisplayHTML.yml
Until now you got an error since you can't do note.lower() for not existing var
> Fix script DisplayHTML execution in case matkAsNote was not defined

- Tests/conf.json
```
Create integration Qualys succeed
Qualys-Test failed with error/s
Playbook Qualys-Test has failed:
- Command: !qualys-pc-scan-list using-brand="Qualys"
- Body: Error from Qualys is : Script failed to run: 
This API cannot be run again until 1 currently running instance has finished.
Code: 1960
HTTP Status Code: 409 at parseXMLAndCheckErrors (script:551:23(43)) (2603)
- Body: Playbook **Qualys-Test** execution error
```
https://circleci.com/gh/demisto/content/10037
> move qualys test to nightly - it requires only single run of build in parallel

- Integrations/integration-TruSTAR.yml
Merged from https://github.com/demisto/content/pull/1706
> TruSTAR integration enhancements

- Integrations/integration-ProofpointTAP.yml
Fixes https://github.com/demisto/etc/issues/12381
> Added filter to fetch specific event types

- Integrations/integration-fireeye.yml
* FireEye URL submissions
Added functionality to submit URLs to FireEye and retrieve their status.
Commands added are fe-submit-url and fe-submit-url-status
> FireEye URL submissions (#1743)

- Scripts/script-CrowdStrikeUrlParse.yml
Updated the regex to properly pull the detection ID.
Sometimes the detection ID changes in length, but it's always a number from 0-9
> Updated the regex

- Scripts/script-CrowdStrikeUrlParse.yml
Updated the regex to properly pull the detection ID.
Sometimes the detection ID changes in length, but it's always a number from 0-9
> Updated the regex (#1801)

- IncidentFields/incidentfields.json
- Integrations/integration-rasterize.yml
- Layouts/layout-details-Phishing.json
- Playbooks/playbook-Process_Email_-_Generic.yml
- Tests/schemas/incidentfields.yml
* And `HTML Rendered Image` MD field to phishing layout
* Add Base64 output to the `rasterize-email` command
* Update rasterized image to the Phishing summary page
TODO:
* Remove the HTML field mapping in the relevant integrations
Fixes: https://github.com/demisto/etc/issues/12327
> Update process email + phishing layout

- Integrations/integration-DemistoLocking.yml
timeout parameter and argument - Minutes to seconds
Increasing default timeout to 10 minutes (600 seconds)
> Demisto lock description fix and increase default timeout

- Integrations/integration-ServiceNow.yml
servicenow-get-computer: query the cmdb_ci_computer table with a computer code
returns: 'sys_id', 'u_code', 'support_group.value', 'os', 'comments'
> added servicenow-get-computer command (#1897)

- Scripts/script-CommonServerPython.yml
same format as commonserver(for js)
for the global(/g) flag use re.findall({regex_format},str)
> added regex formatting for commonserverpython

- Scripts/script-CommonServerPython.yml
so that `print_log()` will not print always to both server log and war room
> add verbose

- Classifiers/classifier-EWS_v2.json
- Classifiers/classifier-Mail-listener.json
Removed from:
* EWSv2
* Mail-listener
Didn't remove from:
* Gmail - `body` field is mapped to `Email Body`, field that's not of type `html` and is not rendered (links aren't clickable)
fixes https://github.com/demisto/etc/issues/12327
> Remove HTML mapping from default phishing mapping

- Scripts/script-TextFromHTML.yml
* Python3 Docker for TextFromHTML
Proposing that we add the Python3 docker for this automation script.  Python 2.7 frequently returns errors for decoding strings as input
* Added regex flag and unicode representation of string
Added changes based on Itay and Slavik's recommendation... Removed Py 3 docker for now
> Python3 Docker for TextFromHTML (#1816)

- Tests/conf.json
Redlock suddenly cleared all the alerts.
Until we find a way to generate alerts, this test should be skipped.
> Skipped Redlock test

- Tests/conf.json
It seems that the credentials have expired, moving the test to skip
> moving scadafence test to skip

- Scripts/script-ADGetUser.yml
UserAccountControl Flags:
Instead of creating a row for each possible flag and set true/false values, merge the flags that are actually set in one row.
image
instead of
image
> ADGetUser - Output formatting 

- Integrations/integration-Cybereason.yml
Fixes:
- Sending the malop dictionary instead of key to `malop_to_incident()`
- Getting only malops which were created after the last fetched malop in previous fetching.
> Cybereason fetch incidents fix

- Integrations/integration-Cylance_Protect_v2.yml
Some responses for specific api calls return 404 status when no data is found, added ability to treat those as "no data found" message to user instead of throwing exception.
> 404 from api call to "not found message" instead of raising exception

- TestPlaybooks/playbook-Cybereason_Test.yml
Cause of changes in our instance DB, I've removed `Parent` field from verify context which is not populated for all processes
> Cybereason integration test fix

- Integrations/integration-Carbon_Black_Enterprise_Live_Response.yml
The following will be deprecated:
- cb-command-create
- cb-command-create-and-wait
This is a 'generic command' to execute specific commands on the endpoind. We added explicit commands in the last integration update.
e.g.  _cb-command-create name="directory-list" session=[sessionID] object=[path]_ is now available as _cb-directory-listing path=[path] sensor=[sensorID]_
- cb-command-cancel
To cancel a 'pending' command. Not usable if 'cb-command-create' is not available.
> deprecate CB Live Response older version commands

- Scripts/script-ReadPDFFile.yml
pdfx library also categorizes domains as URLs.  Switching to ExtractURL to accurately display URLs presented in PDF
related to:
https://github.com/demisto/etc/issues/12962
> Using ExtractURL instead of pdfx library

- Scripts/script-SetByIncidentId.yml
* New Automation for 'Set' in other incidents
I created this automation, which is able to call the 'Set' command on incidents from anywhere, by allowing the user to specify Incident ID. I think this is a valuable script to have. I know I definitely needed it.
* Updated SetByIncidentId
+ Added output identical to that of 'Set' command
+ Added a second output that verifies the command was successful.
* Rename SetByIncidentId.yml to script-SetByIncidentId.yml
+ Renamed to follow naming convention
* Simplified Results in SetByIncidentId
Additions had been made to SetByIncidentId, which used another Demisto API call and some additional logic to verify whether the context key had indeed been set. This has been instead changed to use the return value from 'executeCommandAt', which already …
> SetByIncidentId (#2468)

- Integrations/integration-QRadar.yml
Ready
In 3 commands the context key used for comparison was passed without wrapping parenthesis. This caused the comparison to not work as intended.
- No
Removed logging line that was originally added for debugging purposes.
> QRadar entry context key comparison fix

- TestPlaybooks/playbook-GetTime-Test.yml
Ready
Changed test regex to support singular dates e.g. "5" as opposed to "05"
- No
> Fixes GetTime Test

- Tests/conf.json
Ready
Our Azure instance is missing security alerts we can fetch through Graph.
DevOps are aware and working on it.
Until then - skipping the test.
> Skip Microsoft Graph Test

- Integrations/integration-ArcSightESM.yml
Ready
fixes: https://github.com/demisto/etc/issues/14168
There is an error sometimes when logout arcsight esm session, so we will just ignore the error (because it is only logout)
- No
> fix arcsight logout

- Playbooks/playbook-Get_Original_Email_-_EWS.yml
- Playbooks/playbook-Get_Original_Email_-_Gmail.yml
- Playbooks/playbook-Phishing_Investigation_-_Generic.yml
- Playbooks/playbook-Process_Email_-_Generic.yml
- Fixes for GetOriginalEmail (mailbox of sender instead of recipient)
- Preparations for v4.1 - specific autoextracts, as "system default" won't be an option
contains fixes for 2 separate GIT issues.
GetOriginalEmail:
fixes: https://github.com/demisto/etc/issues/14154
Default Auto-Extract:
fixes: https://github.com/demisto/etc/issues/14112
Fix bugs + prepare for next version (4.1)
- No
> GetOriginalEmail fixes + Auto-Extract preparations for v4.1

- Integrations/integration-EWSv2.yml
Ready
fixes: https://github.com/demisto/etc/issues/14301
Keyerror would occur for some of the items returned by get_searchable_mailboxes() function.
branch | PR
x.x.x
- No
Fixed typo in error message.
> Fixed grammar error, handled special case.

- Tests/conf.json
In Progress:
fixes: https://github.com/demisto/etc/issues/14128
command 'fireeye-hx-file-acquisition' not failing on timeout as described on the issue.
will observe the behavior as the command runs as part of HX test on circleci.
> remove FE HX test from skipped

- Playbooks/playbook-BitDam_Scan_File.yml
Ready
Removed 2 playbook inputs there were not actually used in the playbook itself.
- No
> BITDAM - removed 2 inputs from playbook, was not used anywhere.

- Integrations/integration-Cylance_Protect_v2.yml
Ready
https://github.com/demisto/etc/issues/14222
Integration settings for context output were Sha256 instead of SHA256
- No
> Fixed output context from Sha256 to SHA256 as convention dictates

- Integrations/integration-EWSv2.yml
Ready/In Progress/In Hold(Reason for hold)
fixes: fixes folder get items.  Some mailboxes caused and exception if the limit is not set.  Also the documentation for exchangelib reccommends setting this limit on query strings.
branch | PR
3.6
- Yes
> Ews fix folder get items

- Integrations/integration-Threat_Grid.yml
Ready
fixes: https://github.com/demisto/etc/issues/14567
Expanded raw-response of the following commands:        
threat-grid-get-html-report-by-id
threat-grid-get-processes-by-id
threat-grid-get-video-by-id
threat-grid-get-analysis-by-id
- Yes
- Further details: For customers who used the raw-response path of the above commands since the implementation of the integration.
> Threat Grid - Expand contents

- Tests/conf.json
on different endpoints/commands.
Including error 500/error 405 and several others which started only few days ago.
> Skipped mimecast due to too many random errors from their service 

- Playbooks/playbook-BitDam_Scan_File.yml
- Playbooks/playbook-Detonate_File_-_Lastline.yml
- Playbooks/playbook-Detonate_File_-_McAfee_ATD.yml
- Playbooks/playbook-Detonate_File_-_SNDBOX.yml
- Playbooks/playbook-Detonate_File_-_ThreatGrid.yml
- Playbooks/playbook-Detonate_File_-_WildFire.yml
Ready
fixes: https://github.com/demisto/etc/issues/14424
add a filter in the upload file task to filter non supported file types. checked vs .png, .eml
> Detonate file playbooks upload add filter

- Integrations/integration-EWSv2.yml
Ready
None
Most error messages would be "RateLimitError: Max Timeout Reached (85)".
This fix makes error messages more informative.
Part of a UX overhaul for EWS.
Example of a readable error:
x.x.x
- No
> EWS v2: Improved error messages.

- Tests/conf.json
Ready
Moving zscaler to nightly because of instance change 
any
- No
> Moving Zscaler to nightly

- Scripts/script-BuildEWSQuery.yml
- TestPlaybooks/playbook-BuildEWSQuery_Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/14276
Some parameters of the BuildEWSQuery (such as subject) may contain non-ascii characters.
This change will parse these characters correctly.
x.x.x
- No
> BuildEWSQuery: handle non-ascii characters

- Integrations/integration-Mail_Sender_(New).yml
- TestPlaybooks/playbook-Email_Sender_Python.yml
Ready
fixes: https://github.com/demisto/etc/issues/14277
first bug: fixed.
second bug:
this feature did not work since 3.0 because the server drops undeclared arguments.
plus, there wasn't any way to use it with playbooks.
instead, the 3 arguments for transient files are now comma-separated lists.
new use is:
`!send-mail to="yarden@demistodev.com" subject="special test via playbook" body="this is a test by playbook" attachIDs="305@1678" attachNames="attach.txt" transientFile="test.txt,test2.txt" transientFileContent="this is a test text inside a test attachment mail!,another mail content."`
@gshriki @anara123 
need to see if comma is best separator for the file contents as it may appear inside the file.
List related PRs against other …
> fixed transient bug in mail sender (new) integration

- Playbooks/playbook-default.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/14732
Replace deprecated CloseInvestigation script task at the end of the Default playbook with the builtin closeInvestigation script.
4.1.0
- No
> Default playbook fix

- Scripts/script-SetIncidentCustomFields.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/14572
Deprecate the SetIncidentCustomFields script and alter description to state what to use instead.
- No
> Deprecate set incident custom fields

- Scripts/script-ParseCSV.yml
- TestPlaybooks/playbook-ParseCSVnullbytesTest.yml
- Tests/conf.json
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/14873
Updated ParseCSV script to replace nullbyte chars with empty strings.
- No
Created an additional test playbook - ParseCSVnullbytesTest - to test that the ParseCSV script is correctly replacing nullbyte chars with empty strings.
> Parsecsv nullbyte

- Integrations/integration-EWSMailSender.yml
Ready
None
Fix that was done in EWS v2 and is also relevant for EWS mail sender
branch | PR
ews-error-messages | https://github.com/demisto/content/pull/2674
x.x.x
- No
Playbooks:
Integrations:
Collected the following tests:
> EWS Mail Sender: change service account to credentials.

- Scripts/script-DocumentationAutomation.yml
Ready
demisto/etc#14871
Move to use default docker image for DocumentationAutomation
- No
> change to use default docker image as it contains pyyaml

- Tests/conf.json
Ready
Reached allowed number of submissions per month in Joe Security, until 1/2/19.
Increased the timeout for Tenable.io Scan Test to 700
- No
> Increased Tenable.io Scan Test Timeout And Skipped Joe Security

- Integrations/integration-Jask.yml
- Tests/id_set.json
Ready
@gshriki 
1. reverse the order we get from the service - acs instead of desc
2. set `lastRun` to latest incident we get from the service
3. keep limit ingestion and have it configurable
- No
> Jask fixed fetch incidents

- Misc/reputations.json
Ready
related to: https://github.com/demisto/etc/issues/14953 (partial fix)
SHA256 hash used to not be extracted and not get inserted into context. It should now work.
- Added reputation value and context path for SHA256
- Removed deprecated / useless scripts (should not break BC)
This is what it would look like (except the name won't have "v2" in it and SplunkSearch would also be under `Enhancement Scripts`)
- No
- [Script ] FileReputation
Removed useless scripts too.
This fix should solve the problem of `Phishing test - Inline` failing due to the malicious SHA256 not appearing under File.SHA256 in context, thus not receiving a malicious score.
> - Added reputation value and context path for SHA256

- Scripts/script-SendEmailOnSLABreach.yml
- Tests/id_set.json
- Tests/scripts/update_id_set.py
Ready
fixes: https://github.com/demisto/etc/issues/14785
- Added a new script to send email on SLA breach
- Added the new `update_id_set.py` file that Rony fixed with me on another branch I worked on, that should now accomodate for line breaks in the regex, and deal with CRLF / LF and more.
4.1.0+
- No
> Added a new script to send email on SLA breach

- Integrations/integration-EWSv2.yml
- TestPlaybooks/playbook-pyEWS_Test.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/15203
Added new command, ews-expand-group, that expands a distribution list and displays all of the list members. The command requires mandatory argument which is email address of the group to expand.
- No
Integrations:
Tests:
> Added expand-group command to Ews v2

- Integrations/integration-EWSv2.yml
Ready
Removed unnecessary escape character of dot in `SearchMailboxes.call` function.
Escaping the dot character caused breaking the search query and thus search results were filtered incorrectly.
- No
Playbooks:
Integrations:
Tests:
> EWS: Fixed filter in search_mailboxes function

- Integrations/integration-EWSv2.yml
Ready
fixes: https://github.com/demisto/etc/issues/14969
Exchange 2010 has some compatibility issues which are fixed in the `fix_2010()` function.
In the issue
- No
Playbooks:
Integrations:
Collected the following tests:
> EWS: Fixed Exchange 2010 issue with folder fields.

- Integrations/integration-Gmail.yml
Ready
fixes: https://github.com/demisto/etc/issues/15092
Fixed gmail-revoke-user-role command.
- No
> Gmail fix gmail-revoke-user-role command

- Integrations/integration-AbuseDB.yml
Ready
In some case where the user checks `Trust any certificate` option 
All the commands in the warroom get the error
- No
> ignore warning error

- Scripts/script-FetchFromInstance.yml
Ready
fixes: https://github.com/demisto/etc/issues/15353
Will replace whitespace in integration's name with underscore for correct activation of fetch command.
- No
> FetchFromInstance - Added support for integrations with spaces in the name

- Scripts/script-CommonServerPython.yml
- TestPlaybooks/script-TestPyCommonServer.yml
Ready
Usually it is very confusing and unknown to users the structure of the demisto.executeCommand()
Added 2 commands:
is_error - returns true if the results of executeCommand is error
get_error - extract the error from error entry
https://github.com/demisto/content/pull/2911
- No
> add is_error and get_error helper functions to common server python

- Integrations/integration-ArcSightESM.yml
Ready
as-get-security-events command was using invalid param useproxy. So in env where proxy configured, it behaved improperly
- No
> don't ignore proxy in as-get-security-events

- Scripts/ParseEmailFiles/ParseEmailFiles.py
- Scripts/ParseEmailFiles/ParseEmailFiles.yml
- Scripts/ParseEmailFiles/Pipfile
- Scripts/ParseEmailFiles/Pipfile.lock
- Scripts/ParseEmailFiles/parse_email_files_test.py
- Scripts/ParseEmailFiles/test_data/smtp_email_type.eml
- Tests/scripts/update_id_set.py
- Tests/scripts/validate_files_structure.py
- package_extractor.py
- tox.ini
Ready
related to: https://github.com/demisto/etc/issues/15277
A fix to work with eml files which have an "smtp mail" type
- No
Also added package_extractor.py script to extract python code from yml file.
> Parse email files "smtp mail" type

- Tests/scripts/update_id_set.py
- Tests/scripts/validate_files_structure.py
Ready
When we merge from master and we have a conflict in id_set.json , and git can't handle the merge automatically, then it will corrupt it in most cases with `>>>> master` strings 
The json get corrupted , so validate_files_structure and update_id_set get JSON error, which is not indicative at all to the user
This PR will popup proper error to the user to run update_id_set.py
And update_id_set.py will checkout id_set.json to master and will update it again
- No
> handle corrupted id_set.json file

- Playbooks/playbook-DeDup_incidents.yml
Ready
N/A
Conditional task in the playbook requires boolean comparison for isSimilarIncidentFound
Current
Required
3.5.0
- No
> fixed dedup conditional task

- Tests/conf.json
Ready
Add Freshdesk integration to the skipped integration list because the credentials for the nightly test along with the Trial account that they are associated with have expired.
branch | PR
freshdesk-integration | https://github.com/demisto/content/pull/2916
- No
- N/A
> Add freshdesk to skipped integrations

- Integrations/integration-Microsoft_Graph.yml
Ready
fixes: https://github.com/demisto/etc/issues/15526
Handling 206 - Partial Content response returned from Microsoft Graph.
This means a response was returned successfully, but with warning.
Adding to warning to the logs and processing the response as success.
Any
- No
None
> Microsoft Graph - 206 Partial Content handling

- Tests/conf.json
Ready
If configured the `active-user` we use for testing in Duo to have a phone numbrer. The test playbook should pass now.
> enable back duo test playbook after configuring the user

- Scripts/script-ReadPDFFile.yml
- TestPlaybooks/playbook-Extract_Indicators_From_File_-_test.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/15559#event-2137787152
Fixed outputs that were unintentionally removed while adding ExtractIndicators functionality for 4.1.
Everything should now work as expected again.
4.1.0
- No
> Fixed pdf outputs while maintaining 4.1 extractIndicators functionality

- Integrations/integration-EWSv2.yml
- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/15203
Added option recursively expand nested distribution lists in `ews-expand-group` command.
By default, the recursive expansion is set to false and returns only the first layer of the distribution list. 
In other case, if **recursive-expansion** argument is true, all the layers of the distribution list will be expanded and it's members will be returned.
- No
Playbooks:
Integrations:
Tests:
> EWS v2: recursive expansion

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/15212
Removed tenable io tests from skipped as the instance is no longer stuck.
> removed tenable io tests from skipped

- Integrations/integration-Gmail.yml
Ready
fixes: https://github.com/demisto/etc/issues/15125
Fixed gmail-add-filter from argument not working properly.
- No
> Fixed gmail-add-filter from argument not working properly

- Integrations/integration-Sandblast.yml
Ready
fixes: https://github.com/demisto/etc/issues/15643
Fixed test button, so that it will fail if the user is out of quota
- No
Fixed `sandblast-quota` as well.
> Fixed sandblast 

- Integrations/integration-SplunkPy.yml
Ready
fixes: https://github.com/demisto/etc/issues/15695
Fixed an issue with the command splunk-search, when the result contained unicode values.
- No
Changed a description for the command `splunk-sumbit-event` because it contained an error.
> SplunkPy unicode decode fix

- Integrations/integration-MISP_V2.yml
Ready
fixes: demisto/etc#15835
Changed logger settings to only throw errors and not warnings
- No
> Suppressed warnings generated by out of date misp package

- Integrations/integration-MimecastV2.yml
even if one of the components is missing the URL won't break.
Ready
fixes: @vik-patel's issue in hosted poc
- No
> Constructed the URL in list-managed-urls more carefully, 

- Integrations/ArcSightESMv2/ArcSightESMv2.py
- Integrations/ArcSightESMv2/ArcSightESMv2.yml
Ready
when setting integration context outside of the CLI we're getting time outs. this is a content side bypass for ArcSight ESM. (bug only occurs in engines).
> setIntegrationContext bug bypass

- Integrations/integration-Threat_Grid.yml
- Playbooks/playbook-Detonate_URL_-_ThreatGrid.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/15126
The command threat-grid-upload-sample now works properly with file names that contain new line characters.
- No
> ThreatGrid fix

- Playbooks/playbook-Detonate_File_-_ThreatGrid.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/15853, https://github.com/demisto/etc/issues/15767
ignore case for file.type/extension/info and adding filter for file.size bigger than 0
- No
> ThreatGrid - detonate File playbook fixes

- Integrations/integration-dnstwist.yml
Ready
fixes: https://github.com/demisto/etc/issues/15828
provide whois argument to dnstwist command
- No: Note whois was being done automatically but it seems that it doesn't work for most domains. So changing this to default false should not impact users.
Added a verification at test that we can run dnstwist.
> make whois lookup option controlled by a parameter

- Integrations/integration-Exchange2016_Compliance.yml
- Playbooks/playbook-Exchange_2016_Search_and_Delete.yml
- Tests/id_set.json
Ready
fixes: https://github.com/demisto/etc/issues/14122
The integration can run only on engine without docker as described in the integration tips. 
The integration has the following commands:
1. exchange2016-start-compliance-search
2. exchange2016-get-compliance-search
3. exchange2016-remove-compliance-search
4. exchange2016-purge-compliance-search-results
5. exchange2016-get-compliance-search-purge-status
Functionality and outputs of the commands are identical to `ews-0365` commands that are part of `EWS v2` integration.
Additionally added `Exchange 2016 Search and Delete` playbook that accepts as an input query (KQL) that is used as search conditions for compliance Search.
Structure of the playbook is identical to `Office 365 Search and Delete` playbook.
- No
> Exchange 2016 Compliance Search - integration and playbook

- Integrations/integration-Exchange2016_Compliance.yml
Ready
Fixed query argument escaping while passing as unicode to poweshell subprocess.
The fix was to convert query from unicode to string.
- No
**TEST 1:**
`!exchange2016-start-compliance-search query="subject:\"Email to search\""`
**TEST 2:**
`!exchange2016-start-compliance-search query="subject:\"Email to search\" AND to:\"DEM695412@lab-demisto.com\""`
**TEST 3:**
`!exchange2016-start-compliance-search query="body:\"Email to be searched and deleted.\""`
**TEST 4:**
`!exchange2016-start-compliance-search query="body: c025615b169bbe067afba2b64b149559"`
**TEST 1:**
**TEST 2:**
**TEST 3:**
**TEST 4:**
All manual tests passed and were saved as incidents in self-service.
Playbooks:
Integrations:
> Exchange 2016 Compliance - query escaping fix

- Integrations/integration-Alexa.yml
Ready
fixes: https://github.com/demisto/etc/issues/15914
fixes: https://github.com/demisto/etc/issues/15913
Fixed: Alexa would go through proxy even though it should never do that.
Fixed: No "type" key in DbotScore.
branch | PR
x.x.x
- Yes
- Further details: If, by some miracle, someone configured alexa and a proxy in demsito, and it worked for him, it won't go through the proxy now, so there is a slim chance that it will stop working.
This case brought up before @anara123 and he authorized the change.
Describe additional changes done, for example adding a …
> Fixed proxy handling. Fixed domain type in dbotscore.

- Integrations/integration-Whois.yml
- Tests/conf.json
Ready
Added Whois to un-mockable integration and added Whois to config.json to add an instance since it is no longer a default.
> Fix Whois Test issue

- Scripts/script-ParseCSV.yml
- TestPlaybooks/playbook-TestParseCSV.yml
Ready
fixes: https://github.com/demisto/etc/issues/15925
ParseCSV would fail to decode iso-8859-8 character sets, added support to switch the codec type from utf-8 (default) to anything else.
- No
> ParseCSV - Added codec type support

- Integrations/integration-Gmail.yml
due to "queryuserkey" param being None, thus sending None instead of default admin_email to the request.
Ready
fixes: https://github.com/demisto/etc/issues/15840
- No
> Gmail - Fixed fetch incidents not working 

- Integrations/integration-EWSv2.yml
Ready
In case of using auto-discovery instance configuration without filling Exchange Server Hostname or IP address, caused error in the following EWS compliance commands:
- ews-o365-get-compliance-search
- ews-o365-remove-compliance-search
- ews-o365-start-compliance-search
- ews-o365-purge-compliance-search-results
- ews-o365-get-compliance-search-purge-status
Attached screen shot of the error.
- No
Playbooks:
Integrations:
Tests:
> EWS v2 - fixed compliance commands check

- Scripts/script-FilterByWhitelist.yml
Ready
fixes: https://github.com/demisto/etc/issues/16082
Fix FilterByList bug when the list is empty
The list:
result:
> fix FilterByList script

- Integrations/integration-EWSv2.yml
Ready
fixes: https://github.com/demisto/etc/issues/16011
Added str to headers values and headers names so in case one of them is None, concatenation of two strings will be available and will not raise exception.
- No
Playbooks:
Integrations:
Tests:
> EWS v2 - fetch incident error fix

- .gitignore
- Scripts/ParseEmailFiles/ParseEmailFiles.py
- Scripts/ParseEmailFiles/ParseEmailFiles.yml
- Scripts/ParseEmailFiles/parse_email_files_test.py
- Scripts/script-ParseEmailHeaders.yml
- TestPlaybooks/playbook-TestParseEmailHeaders.yml
- Tests/conf.json
- Tests/secrets_white_list.json
- Tests/test_integration.py
Ready
fixes: https://github.com/demisto/etc/issues/13217
ParseEmailHeaders using ParseEmailFiles.
ParseEmailHeaders will be deprecated - instead use ParseEmailFiles
- Yes
> fix parse email headers

- Layouts/layout-details-Phishing.json
Ready
fixes: https://github.com/demisto/etc/issues/15340
Remove `Email Body HTML` custom field from default Phishing incident Summary.
- I do not believe so
- Tests - N/A
- Documentation - N/A
Altered the `validate_version` function in `validate_files_structure.py` to correctly fetch the version field from a layouts-*.json file as per the layouts schema.
> Phishing layout fix

- Integrations/integration-Centreon.yml
- Scripts/script-CommonServerPython.yml
Ready
Due to container re-use, when deleting the proxy environment variables, they are not returned.
Added `disable_proxy()` and `enable_proxy()` commands to CommonServerPython to resolve this issue.
See screenshot for example usage.
- No
This has been applied to centreon (because of nightly test failure)
> Add generic proxy logic to CommonServerPython

- package_creator.py
Ready
package_creator.py wraps `detaileddescription` in quotation marks, so any other quotation marks in the description will break the yml.
fix now only add `|` at the beginning, and shift everything to the right (for multilined `detaileddescription`)
> improved package_creator.py detailed description parsing

- Integrations/Active_Directory_Query/Active_Directory_Query.py
Ready
No open issues
Because the port is given to the ldap3 library as a string, a "port must be an integer" error is thrown when you specify a port in the instance configuration. Casting this parameter to an integer resolves this issue.
branch | PR
x.x.x
- No
> Active Directory Query v2 - Fixed error when specifying a port

- Integrations/integration-CrowdStrikeFalconSandbox.yml
- TestPlaybooks/playbook-VxStream_Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/15482
Fixes mistake in how URLs were being submitted to CrowdStrike, such that CrowdStrike wasn't processing anything in the URL after and including an ampersand character.
- No
Update the test playbook for the CrowdStrike Falcon Sandbox integration to
a) replace a task that was using a deprecated script, and
b) verify that URLs are being submitted to CrowdStrike properly.
> CrowdStrike URL Bug

- Widgets/widget-MyMentions.json
So mentions that were marked as read will not be displayed
> Change mention widget to show only new

- Integrations/integration-HashiCorp-Vault.yml
- TestPlaybooks/playbook-hashicorp_test.yml
Ready
fixes: https://github.com/demisto/etc/issues/16317
Support KV 1 engine in `list-secrets` command
Fix non-indicative test errors
Fix multiple engine configurations
> Hashicorp Vault Fixes

- Integrations/integration-CyberTriage.yml
Allow user to specify a Cyber Triage incident and choose the type of data to collect. 
Ready/In Progress/In Hold(Reason for hold)
Updating the Cyber Triage integration app to allows users to specify the type of data they want to collect. Also allow users to specify and incident name when creating a Cyber Triage session. Cyber Triage 2.6 or later is required to use this integration. 
branch | PR
x.x.x
- Yes
- No
> Update integration to work with Cyber Triage 2.6

- Integrations/integration-PaloAlto_MineMeld.yml
Ready
fixes: https://github.com/demisto/etc/issues/16336
Without defaults extract indicators fails to provide arg url to execute command url.
- No
> minemeld - Added defaults to threat intel commands

- Tests/scripts/create_instance.sh
- Tests/scripts/create_instances.py
- Tests/test_content.py
Ready
fixes: https://github.com/demisto/etc/issues/16265
this prints the ami info including the ami name in the beginning of contetnt test run.
so the name will include the version and build of the server running the content test
- No
> Print ami info(server version and build) in content test run

- Integrations/integration-VirusTotal.yml
Ready
fixes: https://github.com/demisto/etc/issues/16344
Added two additional parameters - preferred vendors list and preferred vendors threshold.
If these parameters are supplied, any file/url must be detected as malicious by as many vendors from the preferred vendors list as the threshold given, in order to be declared as malicious.
- No
> VirusTotal - Added preferred vendors feature

- Integrations/integration-ThreatMiner.yml
- Tests/conf.json
Ready
Moved AbuseIPDB to unmockable - no insecure checkbox.
Changed proxy logic of ThreatMiner to work before the module test.
branch | PR
x.x.x
- No
> Handled nightly failed tests: ThreatMiner and TCPIPUtils

- TestPlaybooks/playbook-Phishing_test_-_Inline.yml
- TestPlaybooks/playbook-Phishing_test_-_attachment.yml
Ready
- Added tasks that add (and at the end, also remove) a malicious URL to Minemeld miner. This way, Minemeld, which we rely on in the phishing tests, will always find this indicator malicious.
> Added logic to ensure malicious indicator is found in phishing tests

- Tests/conf.json
Ready
related: https://github.com/demisto/etc/issues/16461
Symantec Deepsight Intelligence moved to skipped due to issues related to id_set.json
> moved Symantec Deepsight Intellignece to skipped

- Integrations/integration-PhishAI.yml
- Playbooks/playbook-Detonate_URL_-_PhishAI.yml
- TestPlaybooks/playbook-Detonate_URL_PhishAI-Test.yml
In Progress
fixes: https://github.com/demisto/etc/issues/16435
fix logic of check-status, add outputs, fix logic of detonate playbook, add a meaningful test to it.
- Yes
phish-ai-scan-url - change of context from DBotScore.ScanID to PhishAI.ScanID
since we shouldn't save the scanid under DBotScore
phish-ai-check-status - change of argument from url to scan_id
since we want to pull on a specific scan its status, and not scan a new url.
> Phish.AI integration logic and detonate url playbook fixes

- Integrations/integration-EWSMailSender.yml
- TestPlaybooks/NonCircleTests/playbook-Send-Email-To-Recipients-Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/16425
Truncated the subject of email in case subject is more than 255 chars. 
Added subject with more than 255 chars to `EWS Mail Sender Test 2` test.
- No
Playbooks:
Integrations:
Tests:
> EWS Mail Sender - subject truncate

- Scripts/script-CommonServerPython.yml
Ready
common serever function `logger` used function attributes ```func.func_name``` which is not supported in py3. Using ```__name__``` is the preferred method as it applies uniformly
> p3 support for `logger`

- Tests/conf.json
Ready
moved virus total - private API to unmockable due to it failing on master.
> moved virus total - private API to unmockable

- Scripts/ParseEmailFiles/ParseEmailFiles.py
- Scripts/ParseEmailFiles/ParseEmailFiles.yml
- Scripts/ParseEmailFiles/parse_email_files_test.py
- Scripts/ParseEmailFiles/test_data/utf_8_email.eml
- Tests/secrets_white_list.json
Ready
fixes: https://github.com/demisto/etc/issues/16514
Fixes unicode text file type case
- No
> Parse email utf text file type

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/16461
Removing Symantec Deepsight from skipped
- No
> removing Symantec Deepsight from skipped

- Integrations/integration-VirusTotal.yml
Ready
fixes: https://github.com/demisto/etc/issues/16483
Added fullResponseGlobal parameter. Determines whether to return all results, which can number in the thousands. If "true", returns all results and overrides the _fullResponse_, _long_ arguments (if set to "false") in a command. If "false", the _fullResponse_, _long_ arguments in the command determines how results are returned.
- No
> vt - add fullresponseglobal param

- Scripts/script-ExtractIndicatorsFromWordFile.yml
Ready
fixes: https://github.com/demisto/etc/issues/16472
get_file_details method failed when file entry is not a list
> Fix ExtractIndicatorsFromWordFile - get file type

- Scripts/script-BuildEWSQuery.yml
Ready
fixes: https://github.com/demisto/etc/issues/16242
BuildEWSQuery was building illegal query that contains invalid search property `AttachmentName`.
The fix is to change `AttachmentName` property to `Attachment`.
Additional information about AQS syntax: 
[Microsoft Documentation](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-perform-an-aqs-search-by-using-ews-in-exchange) 
- No
Scripts:
Playbooks:
Tests:
> BuildEWSQuery: fixed illegal query

- Integrations/integration-CrowdStrikeIntel.yml
Ready
fixes: https://github.com/demisto/etc/issues/16533
Fixed unix time parsing in cs-report
Before:
After:
> CS FalconIntel - Fix unix time parsing

- Playbooks/playbook-Process_Email_-_Generic.yml
- TestPlaybooks/playbook-Process_Email_-_Generic_-_Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/16127
Fixed the `SetIncident` task in `Process Email - Generic` where it was retrieving data from the wrong context fields.
The fix utilizes the new Email.HeadersMap outputs from the `ParseEmailFiles` script, **where applicable and where possible.**
The following fields are now populated:
- Email Subject
- Email Return Path
- Email Reply To
- Email Message ID
- Email To
- Email From
- Email CC
- Email Subject
Also added a test playbook for the new (and old) changes.
4.0.0
- No - it adds extra data
> Process Email - Generic - fix for SetIncident retrieving data from wrong context fields

- Scripts/ParseEmailFiles/ParseEmailFiles.py
- Scripts/ParseEmailFiles/parse_email_files_test.py
- Scripts/ParseEmailFiles/test_data/multiple_to_cc.eml
- TestPlaybooks/playbook-TestParseEmailHeaders.yml
- tox.ini
Ready
fixes: https://github.com/demisto/etc/issues/16746
Fix to returned headers map with raw headers for from/to/cc
HR note after fix:
- No
This fix also includes `unfold` functionality for headers.
> Parse email raw to/from/cc headers

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/16555
Cybereason instance is alive, and added `fromversion: 4.1.0` cause of fetch test
4.1.0 for the test
- Yes
None
> Unskip Cybereason test

- Tests/conf.json
Ready
Moved crowdstrike falcon test to skipped. Test is unmockable, and has its data deleted every few weeks.
> moved CrowdStrike falcon test to skipped

- Integrations/integration-Wildfire.yml
Ready
master failed due to missing RN because of last release - fixed.
file argument in the file command should not be deprecated. fixed as well.
- No
> WF - RN and file arg in file command

- Playbooks/playbook-Account_Enrichment_-_Generic_v2.1.yml
- TestPlaybooks/playbook-Account_Enrichment_-_Generic_v2.1_-_Test.yml
- Tests/conf.json
In Progress - need documentation
Related to: https://github.com/demisto/etc/issues/16881
Added the `Account Enrichment - Generic v2.1` playbook. The playbook features the following improvements over the previous one:
- Changed AD to AD v2
- Updated descriptions of task names / playbook
- Removed redundant outputs
Also added the test playbook `Account Enrichment - Generic v2.1 - Test`.
Playbook
Test playbook
4.1.0
- No
> Added Account Enrichment v2.1 + Test v2.1

- Tests/conf.json
Ready
skip Carbon Black test until test will be update
> Add Carbon Black Enterprise Protection V2 Test to skipped tests

- TestPlaybooks/playbook-InfoArmorVigilanteATITest.yml
Ready
opened issue to be track later https://github.com/demisto/etc/issues/17022
The test failed because the command vigilante-query-domains output missing the email and the password for the account.
> remove validation for email and password outputs

- Playbooks/playbook-Get_Original_Email_-_EWS.yml
Ready
fixes: https://github.com/demisto/etc/issues/17014
Typo in `Get original email` task input, target-mailbox must receive `inputs.Mailbox` instead of `inputs.mailbox`.
4.0.0
- No
Playbooks:
Tests:
> fixed typo in get original email task

- Integrations/integration-FireEyeHX.yml
Ready
fixes: https://github.com/demisto/etc/issues/13365
Fix issue where `<dict>.get(<key>, <default value>)` was used, but `<dict>[<key>]` had a value of `None`.
- No
> FireeEye HX: Fixed issue where key exists but value was not checked.

- .circleci/config.yml
Ready
fixes: demisto/etc#17037
Changed build config to send chat notifications on build fail/restored to the content team slack channel
- No
> Add broken master notifications

- TestPlaybooks/playbook-CrowdStrike_Endpoint_Enrichment_-_Test.yml
Ready
The test CrowdStrike Endpoint Enrichment - Test failed on the task `Context check` on validate if windows is in `Endpoint.OS` context path. I changed the condition type from 'As value' to 'From previous tasks'
**before:**
**after:**
> fix test playbook - change Context check condition

- Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex.py
- Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex.yml
- Tests/conf.json
Ready
Added handling for logging query status.
Increased the max time out of logging query to 30 seconds.
For commands, if query status is `RUNNING` or `FAILED` - an error will be raised.
For fetch, if status is `RUNNING`, the query id will be passed to next run, which will try poll the results of query job is finished.
Removed the deletion of query from the service cause it is not longer needed in current sdk version.
4.1
- No
None
> PANW Cortex - handle logging query status

- Integrations/integration-opswat-metadefender-v2.yml
- Integrations/integration-opswat-metadefender.yml
In Progress
fixes: https://github.com/demisto/etc/issues/17188
marking the the commands in the old integration as deprecated and not the new ones.
- No
> Fix opswat deprecated

- Integrations/integration-Fortigate.yml
Ready
fixes: https://github.com/demisto/etc/issues/17186
The update-policy command used to replace the existing data with the arguments supplied.
Now there is a possibility to keep the existing data and add / remove the supplied arguments to it.
- No
> Enabled keeping the existing data in update-policy

- Scripts/script-FormattedDateToEpoch.yml
Ready
N/A
New transformer which converts a custom-formatted timestamp to a UNIX epoch time, using a Python strptime format string.  Very useful for converting custom timestamps to a Demisto date field.  Parameters are the string to convert (value), and the formatter string (formatter).  Valid formatter values can be found at https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior.
N/A 
N/A
4.x.x
- No
N/A
N/A
> Added transformer FormattedDateToEpoch

- Tests/scripts/validate_files.py
Ready
Fixes the issue of `validate_files.py` trying to validate `*_unified.yml` files locally if they appear before the integration yml in a given directory.
Also on occasion the `get_modified_files` function would raise an `IndexError`. I believe that that this would occur when `glob.glob` didn't return any results because the directory (and files of the directory) of the modified file in the list of modified files in `origin/master` do not exist in the local branch being worked on. Now the loop will continue if this happens.
The `validate_files.py` mistakenly trying to validate an unstaged `*_unified.yml` file.
x.x.x
- Don't think so
> Fix local file validation

- Tests/conf.json
Ready
The reason for skipped: https://github.com/demisto/etc/issues/17358
Moving tests to skipped in order to make the master build green again
> Added infoarmor to skipped

- Scripts/FormattedDateToEpoch/FormattedDateToEpoch.py
- Scripts/FormattedDateToEpoch/FormattedDateToEpoch.yml
- Scripts/script-FormattedDateToEpoch.yml
- TestPlaybooks/playbook-FormattedDateToEpochTest.yml
- Tests/conf.json
Ready/In Progress
external PR
fixes: https://github.com/demisto/content/pull/3491
New transformer which converts a custom-formatted timestamp to a UNIX epoch time, using a Python strptime format string. Very useful for converting custom timestamps to a Demisto date field. Parameters are the string to convert (value), and the formatter string (formatter). Valid formatter values can be found at https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior.
- No
> Added transformer FormattedDateToEpoch (#3491)

- Integrations/rasterize/rasterize.py
- Integrations/rasterize/rasterize.yml
Ready
some error won't come from the subprocess, i.e. the command execution will finish with no errors, but will not generate any image, and therefore trying to open the image will throw an error. added try catch block.
- No
> Better error suppression for Rasterize

- Scripts/ParseEmailFiles/ParseEmailFiles.py
- Scripts/ParseEmailFiles/parse_email_files_test.py
- Scripts/ParseEmailFiles/test_data/eml_contains_base64_eml.eml
- Scripts/ParseEmailFiles/test_data/eml_contains_base64_eml2.eml
Ready
fixes: https://github.com/demisto/etc/issues/17526
Fixing the bug in ParseEmailFiles that was failing to parse base64 encoded eml inside of eml
- No
> Parse email files fix bugs

- .hooks/pre-commit
- Tests/scripts/run_all_pkg_dev_tasks.sh
Ready
If the following env variable is set: `CONTENT_PRECOMMIT_RUN_DEV_TASKS` pre-commit hook will run the dev tasks (pylint/pytest...) as we do in the build.
- No
> add option to run dev tasks (pytest/flake8/pylint/mypy) as part of pre-commit hook

- Tests/conf.json
Ready
Update Tests/conf.json with ms graph integrations development instance names. Add all ms graph integrations to unmockable list.
| PR |
| ------ |
| https://github.com/demisto/content-test-conf/pull/451 |
- No
- ~~[ ] Tests~~
- ~~[ ] Documentation (with link to it)~~
> Add dev instance names, and add ms graph integrations to unmockable

- Tests/scripts/hook_validations/integration.py
Ready
when running files validations we are using the requests library to retrieve the original (deleted) files from github-master.
this is spamming the build logs with warning errors about SSL verification.
- No
> Disable SSL verification warnings

- Integrations/ThreatX/ThreatX.py
Ready
N/A
Fixes an issue where fingerprint sometimes comes back as Null from the API, creating the following error:
argument of type 'NoneType' is not iterable
N/A
N/A
branch | PR
None
- No
N/A
> fix issue where fingerprint sometimes comes back as Null from the API

- Scripts/script-SendEmailToManager.yml
Missing closing parentheses cause a syntax error when attempting to run the command in the SOAR platform.
Ready
The calls to `demisto.get()` were no closed, causing a syntax error when attempting to run the command from Demisto
No
> Added missing closing parentheses

- Tests/scripts/validate_files.py
Ready
It seems that the `new_added_files` logic removes all new_files from validation (at least those that are fully committed). They are verified during circle build as this happens only during a local validation (pre-commit hooks). 
I've commented this out. Need to better understand why this was added.
> validate_files: new_added_files logic fix

- TestPlaybooks/playbook-Intezer_Test.yml
- Tests/conf.json
Ready
The test failed on 'Test enrichment with sha256 exist' task when checking if DBotScore.Indicator equals to sha256 value while DBotScore.Indicator is array. Changed the 'equals' condition to 'contains'
> fix intezer test

- Integrations/integration-LogRhythm.yml
- Releases/LatestRelease/integration-LogRhythm.md
Ready
fixes: https://github.com/demisto/etc/issues/17739
The command !lr-get-alarm-events-by-id crash when there was no events for the alarm
> fix bug in lr-get-alarm-events-by-id command

- Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2.yml
- Releases/LatestRelease/ExtractIndicatorsFromTextFile.md
- Releases/LatestRelease/playbook-Extract_Indicators_From_File_-_Generic_v2.md
- Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.py
- TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test.yml
- Tests/secrets_white_list.json
Ready
fixes: https://github.com/demisto/etc/issues/17655
Fixed 
* playbook to handle a bug where `.rtf` files are not inspected with `Extract Indicators From File - Generic v2`.
* bug in `ExtractIndicatorsFromTextFile` script where certain strings had their escape characters removed, which created impossible characters (which threw an exception).
* Follow up of a previous bug that I noticed while working on this - in https://github.com/demisto/etc/issues/17351. (look for the next part in the comments).
Though there is a condition prior to this task that was fixed, I realised that in a multi-file scenario this task might still be reached, and so this task had to be changed as well
4.1.0+
- No
> [Bug] Rich Text Files are not inspected with 'Extract Indicators From File - Generic v2'

- Integrations/Rapid7_Nexpose/Pipfile
- Integrations/Rapid7_Nexpose/Pipfile.lock
- Integrations/Rapid7_Nexpose/Rapid7_Nexpose.py
- Integrations/Rapid7_Nexpose/Rapid7_Nexpose_test.py
- Releases/LatestRelease/Rapid7_Nexpose.md
Ready
fixes: https://github.com/demisto/etc/issues/17765
The issue was caused by a known behaviour of `time.strptime` function where if given the flag `%f` (milliseconds) when milliseconds is 0 will result in an exception.
The fix is to wrap the call with a function that contains a fallback if there aren't milliseconds.
- No
> [Bug] Nexpose nexpose-get-assets returns a date format error

- Integrations/integration-opswat-metadefender-v2.yml
- Releases/LatestRelease/integration-opswat-metadefender-v2.md
Ready
fixes: https://github.com/demisto/etc/issues/17189
Fixes the curated file upload by *not* using muiltipart
Handling responses when `total_detected_avs` is missing.
the one dose not have tests because we don't have an instance.
It was tested in the customer environment. this can be seen in the issue.
- No
> Opswat metadefender bug fix: corrupted file upload

- Integrations/Cisco-umbrella/Cisco-umbrella.py
- Integrations/Cisco-umbrella/Cisco-umbrella.yml
- Releases/LatestRelease/Cisco-umbrella.md
- Tests/conf.json
Ready
fixes: demisto/etc#17937
* Reversed logic of Insecure setting while preserving backwards compatibility.
- No
> Reverse Insecure logic for Cisco Umbrella

- Playbooks/playbook-Process_Email_-_Generic.yml
- Releases/LatestRelease/playbook-Process_Email_-_Generic.md
Ready
fixes: https://github.com/demisto/etc/issues/16438
Adding a condition that checks if the HTML is empty and if so not rendering an image.
> fixing rendering bug

- Integrations/JiraV2/JiraV2.py
- Releases/LatestRelease/JiraV2.md
Ready
Fetch incidents in Jira integration creates new incident for the same ticket every fetch iteration.
The fix use to avoid incidents duplication
> Fix bug in fetch incidets - integration duplicates the last ticket

- TestPlaybooks/playbook-RedLockTest.yml
Ready
fixes: https://github.com/demisto/etc/issues/15493
The alert in Redlock's test playbook was not suitable for the playbook.
Edited it so it would test the functionality properly.
- No
> Fixed alert in Redlock's test playbook

- Integrations/AutofocusV2/AutofocusV2.py
- Releases/LatestRelease/AutofocusV2.md
- TestPlaybooks/playbook-AutoFocus_V2_test.yml
Ready
fixes: https://github.com/demisto/etc/issues/18147
Added the status of top-tags, sessions and samples searches into context.
- No
> Propagated status to context in search results

- TestPlaybooks/playbook-Active_Directory_Test.yml
- TestPlaybooks/playbook-Whois-Test.yml
Ready
Fixed Active Directory playbook and Whois playbook
changed AD playbook values and query to match actual server status. 
Whois playbook checked a non-existing field (Domain.Whois.QueryStatus) and an invalid value ("GOOGLE.COM" instead of simply "google.com") - changed both
branch | PR
5.0.0
- No
> Active Directory Query playbook fixed

- Tests/test_content.py
Ready
fixes: https://github.com/demisto/etc/issues/18233
Just use latest version when testing non-ami
> set server version to latest when running with non-ami

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18102
https://github.com/demisto/etc/issues/18273
Pwned API has changed, resulting in several of the integration commands not working (returning error 403 forbidden).
AlienVault USM license needs to be renewed
> Moving Pwned and AlienVault USM integrations to skipped until fixed

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18328
ArcSight ESM license has expired, moving the integration to skipped until renewal.
> Moved ArcSight ESM v2 to skipped

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18332
Moved RSA NetWitness Packets and Logs test to skipped until a fix can be found for the command that fails it.
> Moving "rsa_packets_and_logs_test" to skipped

- TestPlaybooks/playbook-Windows_Defender_Advanced_Threat_Protection_Test.yml
- Tests/conf.json
Ready
Updates Windows Defender ATP test playbook (updated hash for the "Get machines related to file" command). Remove Windows Defender ATP from skipped integrations and unmockable integrations.
- No
> Windows defender atp tests

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18349
https://github.com/demisto/etc/issues/18343
https://github.com/demisto/etc/issues/18350
Autoextract - skipped because of changes in reputations.json file
CreatePhishingClassifierMLTest - skipped because test is unstable
TIE - tests fail to create instance from time to time - a rerun solves the problem
> Skipping CreatePhishingClassifierMLTest, Autoextract tests, and McAfee TIE tests

- Integrations/EWSv2/EWSv2.py
Ready
fixes: https://github.com/demisto/etc/issues/16908
When fetching emails as incidents, the `eml` file (that was uploaded to war room) of attached email was created from `MimeContent` only that was decoded from Base64. The response could include additional x-headers that were not included in `MimeContent`. The fix is to create email from `MimeContent` and then add `InternetMessageHeaders` to email and return `eml` file to war room.
4.5.0
- No
Playbooks:
Integrations:
Tests:
> EWS v2 - missing headers fix

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18376
https://github.com/demisto/etc/issues/18377
https://github.com/demisto/etc/issues/18385
SCADAfence CNM -  integration fails to create an instance, throwing a '502 bad gateway' error.
XDR instance seems to have problems - returning '500 Internal server error'.
LogRhytemRest - A command doesn't return the expected results - I couldn't find a way to skip it.
> Skipping SCADAfence CNM, Cortex XDR and LogRhythemRest tests

- Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR.yml
- Integrations/PaloAltoNetworks_XDR/PaloAltoNetworks_XDR_description.md
- Releases/LatestRelease/PaloAltoNetworks_XDR.md
- Releases/LatestRelease/XDRSyncScript.md
- Scripts/XDRSyncScript/XDRSyncScript.py
- Scripts/XDRSyncScript/XDRSyncScript.yml
- Scripts/XDRSyncScript/XDRSyncScript_test.py
In progress
https://github.com/demisto/etc/issues/18211
- sync will update grid fields instead of markdown field
- added verbose option
https://github.com/demisto/content/pull/3875
- Yes
- Currently yes, XDRSyncScript will populate alerts to xdralerts instead of markdown field
> detailed documentation added

- Releases/LatestRelease/StixParser.md
- Scripts/StixParser/StixParser.py
- Scripts/StixParser/StixParser_test.py
- Scripts/StixParser/TestData/little_stix2.json
- Scripts/StixParser/TestData/little_stix2_results.json
- Scripts/StixParser/TestData/stix2.json
- Scripts/StixParser/TestData/stix2_results.json
Ready
Adds support for registry and CVE indicators. 
added unit tests
fixed bug with `ip-x-x-x-x` to `x.x.x.x` IP format
- No
> Stix2 new indicators support

- Tests/conf.json
Ready
https://github.com/demisto/etc/issues/18385
LogRhytemRest - A command doesn't return the expected results - I couldn't find a way to replicate the sought results neither through Demisto nor the UI. 
(made a mistake and skipped the playbook and not the test - so Im pushing again)
> Skipping LogRhythmRest

- docs/context_and_ouputs/README.MD
Sets link to https://github.com/demisto/content/blob/master/docs/code_conventions/README.MD#linking-context
Old link https://github.com/demisto/content/blob/master/docs/code_conventions/README.MD#linking-context no longer working
> fix link to linking context

- Integrations/JiraV2/JiraV2.py
- Integrations/JiraV2/JiraV2.yml
Ready
This PR adds support to provide the application when created a remote issue link.
This is useful if there are other Atlassian products connected to Jira, like Confluence. 
Especially if linked Confluence Articles are forced somewhere in the issue workflow.
API details here:
https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-rest-api-3-issue-issueIdOrKey-remotelink-get
Before (resolves as generic URL):
After (resolves as Confluence Article): 
4.5
- No
> Jira integration: add support for remote application links

- Integrations/JiraV2/JiraV2.py
- Integrations/JiraV2/JiraV2.yml
- Releases/LatestRelease/JiraV2.md
* Jira integration: add support for remote application links
* Fix edit issue (remove empty 'project' object)
* fix formatting -.-
* Revert "Fix edit issue (remove empty 'project' object)"
Will be handled in a separate PR
This reverts commit d29e16de69712819a9ea15adcb7d677839879ebb.
Ready
Adds support for remote application links.
branch | PR
pingunaut:jira-confluence-remote-link | https://github.com/demisto/content/pull/3854
- No
> Jira integration: add support for remote application links (#3854)

- Integrations/JiraV2/JiraV2.py
Ready
Fixes the `jira-edit-issue` command which would fail if the empty `project` field was included in the body.
branch | PR
pingunaut:edit-jira-empty-projects | https://github.com/demisto/content/pull/4062
- No
> Fix jira-edit-issue command (#4062)

- Scripts/ParseEmailFiles/ParseEmailFiles.py
When using a msg file with characters like 'à,é,è,ç' in the subject or the body, they are not decoded.
> Fixed the missing special characters from an msg email

- Integrations/MailSenderNew/MailSenderNew.py
- Integrations/MailSenderNew/MailSenderNew.yml
Ready
This PR adds support for custom mail headers to the MailSenderNew integration. Users can simply add additional one or multiple mail headers to an email by providing `headerName1=headerName1,headerName2=headerName2`
4.5.0
- No
> MailSenderNew add support for custom headers

- Integrations/IntSight/CHANGELOG.md
- Integrations/IntSight/IntSight.py
- Integrations/IntSight/IntSight.yml
Ready
fixes: https://github.com/demisto/etc/issues/18055
the integration crashed when the extracting alerts tags with different encoding, set default encoding to utf-8 fix that
> set default encoding to utf-8 in Intsights

- IndicatorFields/incidentfield-description.json
- IndicatorFields/incidentfield-description_CHANGELOG.md
- IndicatorFields/incidentfield-osversion.json
- IndicatorFields/incidentfield-osversion_CHANGELOG.md
Ready
Changed id for indicators that did not match expected id name (was: `incident_*` should've been `indicator_*`)
Os version and description successfully installed:
5.0.0
- No
> [Fix] Changed Indicator Fields IDs

- Scripts/CommonServerPython/CommonServerPython.py
- Scripts/CommonServerPython/CommonServerPython_test.py
Ready
Added the option to a raised error to return_error so we can log the Error and not depend on the user.
- No
> add Exception object to return_error

- Integrations/MailSenderNew/CHANGELOG.md
- Integrations/MailSenderNew/MailSenderNew.py
- Integrations/MailSenderNew/MailSenderNew.yml
- Integrations/MailSenderNew/MailSenderNew_test.py
Ready
Adds the ability to add custom headers to an email.
branch | PR
pingunaut:integration_mailsender_new_custom_headers | https://github.com/demisto/content/pull/3904
- No
> MailSenderNew add support for custom headers (#3904)

- Tests/conf.json
Ready
Fixed in: https://github.com/demisto/server/pull/13269
Original issue: https://github.com/demisto/etc/issues/18343
Test was moved to skipped originally because of a server bug, since this bug was fixed, the test can be unskipped.
> removed autoextract from skipped

- Tests/test_integration.py
Ready
fixes: https://github.com/demisto/etc/issues/15038
we hold all the conf.json file and can better log the instance name and playbook ID so the developer can see if the error is related to the mismatch or to a schema in the TPB.
- No
> better logging of "Mismatch between playbookID...."

- Scripts/CommonServerPython/CHANGELOG.md
- Scripts/CommonServerPython/CommonServerPython.md
Ready
Added release notes to common server python.
any
- No
None
> Add get_demisto_version to CommonServerPython CHANGELOG

- Integrations/MicrosoftTeams/CHANGELOG.md
- Integrations/MicrosoftTeams/MicrosoftTeams.py
- Integrations/MicrosoftTeams/MicrosoftTeams_test.py
- Tests/secrets_white_list.json
Ready
1. Added message to be sent on channel creation as part of mirror flow.
2. Fixed bug in which error returned from server are not sent in direct messages.
Error returned from server when an external user tries to send `list my incidents` to the bot in direct message:
5.0
- No
> Microsoft Teams enhancements

- docs/context_standards/README.MD
Ready
Removed `Account.Email` string (left object) and removed double `Account.Username`.
> [Documentation] Removed redundant context paths

- Integrations/integration-Remedy-On-Demand.yml
- Integrations/integration-Remedy-On-Demand_CHANGELOG.md
Ready
Removed trailing slash from login URL, since it caused bad request response returned from remedy.
Any
- No
None
> Remedy On Demand - remove trailing slash from login url

- Integrations/MimecastV2/MimecastV2.py
In Progress - waiting first for packigify to merge into master
Fixes issue when not having access_key configured blocks the integration from running any command due to auto token refresh that needs it.
Fix: If there is no access key, won't run auto token refresh since it won't work anyway.
Also reflects in test error in case access key is not provided, that it cannot actually test the integration.
> Mimecast v2 fix

- Integrations/ServiceNow/CHANGELOG.md
- Integrations/ServiceNow/ServiceNow.py
- Integrations/ServiceNow/ServiceNow.yml
Ready
fixes: https://github.com/demisto/etc/issues/17758
The command servicenow-upload-file failed when using the file generated with generateSummaryReport script.
> fix upload-file command when the file is summary report

- Integrations/QRadar/CHANGELOG.md
- Integrations/QRadar/QRadar.py
Ready (validated with @yoavBenZion)
leftover from: https://github.com/demisto/content/pull/4067
Fixed an issue in which the `qradar-offense-by-id` command failed when trying to get offense type with a missing SEC header.
- No
> [Fix] QRadar missing SEC header when trying to get offense types

- Integrations/EWSv2/CHANGELOG.md
- Integrations/EWSv2/EWSv2.py
- Integrations/EWSv2/EWSv2.yml
- TestPlaybooks/playbook-pyEWS_Test.yml
Ready
In case of saving new contact as distribution list in target mailbox, `ews-get-contacts` will raise AttributeError. Added type checking in order separate between `Contact` and `DistributionList` objects. Additionally fixed the `limit` argument that had no impact on the results. 
4.5.0
- No
Playbooks:
Integrations:
Tests:
> EWS v2 - fixed ews-get-contacts command

- Integrations/PaloAlto_MineMeld/CHANGELOG.md
- Integrations/PaloAlto_MineMeld/PaloAlto_MineMeld.py
- Integrations/PaloAlto_MineMeld/PaloAlto_MineMeld.yml
- Tests/scripts/hook_validations/integration.py
- Tests/scripts/hook_validations/tests/integration_test.py
Also changed descriptions of DBOTSCORE output paths according to our new standards.
Ready
fixes: https://github.com/demisto/etc/issues/18898
weird behavior of urllib2, was omitting the subdomain from URLs on join operations (concat server root + api path) for instances that were installed on non root paths in server.
- No
> MineMeld treat properly non root server URLs

- Tests/conf.json
Ready
No need for mocking in mysql tests. It doesn't use http.
- No
> unmock mysql - doesn't use http

- Integrations/AutofocusV2/AutofocusV2.py
- Integrations/AutofocusV2/AutofocusV2.yml
- Integrations/AutofocusV2/CHANGELOG.md
- TestPlaybooks/playbook-AutoFocus_V2_test.yml
Ready
fixes: https://github.com/demisto/etc/issues/17949
Updated Palo Alto Networks AutoFocus V2 Indicators context outputs to support version 5.0.
- No
> PANW AutoFocus V2 indicators context outputs - Support for version 5.0

- Tests/scripts/validate_files.py
Ready
When backward compatibility check run, it won't fail the build even if the check failed.
> Backward compatibility check won't fail builds

- Tests/scripts/constants.py
Ready
related: https://circleci.com/gh/demisto/content/29036
@DeanArbel FYI
fixed regex for code files in integration/script packages.
this regex will only catch code files in the package directories (excluding the unit test files).
- No
as a followup to this fix, i opened dev task to validate the rest of the regex in that file:
https://github.com/demisto/etc/issues/19073
> fixed integration/script code files regex

- Integrations/QRadar/CHANGELOG.md
- Integrations/QRadar/QRadar.py
- Integrations/QRadar/QRadar.yml
Ready
fixes: https://github.com/demisto/etc/issues/17548
fixes: https://github.com/demisto/etc/issues/18597
Added new functionality to `qradar-get-note` command. `note_id` argument is no longer required, so when executed without it, the command will get all the offense's notes.
- No
Fixed a bug that prevented closing offenses.
> [Enhancement] QRadar qradar-get-note command

- Scripts/CommonServerPython/CommonServerPython.py
- Scripts/CommonServerPython/CommonServerPython_test.py
Ready
Switched the condition when `utc` parameter in `parse_date_range` function is set to True.
4.5.0
- No
> parse_date_range - fixed utc parameter condition and added unit-tests

- Tests/scripts/pkg_dev_test_tasks.py
Ready
ex.output is None because of the way we run subprocesses in non verbose mode. Simply added a printout suggesting to run in verbose mode if failing. Should make life easier when encountering failures.
> mention -v option when failing

- Integrations/DuoAdminApi/CHANGELOG.md
- Integrations/DuoAdminApi/DuoAdminApi.py
- Integrations/DuoAdminApi/DuoAdminApi.yml
- Scripts/StixParser/StixParser_test.py
- TestPlaybooks/playbook-DuoAdminaAPITest.yml
Ready
fixes: https://github.com/demisto/etc/issues/19141
The usage of the api in the command was wrong. The param passed to the API has to be users and not username.
By default if no users are specified then the response returned is auth logs for all users, which led to same results for different users.
The PB have been enhanced to check for the bug fix.
- No
> [Fixed] DUO Admin - Auth logs bug

- Scripts/CommonServerPython/CommonServerPython.py
- Scripts/CommonServerPython/CommonServerPython_test.py
Ready
removed integration_name, integration_context_name and integreation_command_name from BaseClient.
unified server and base suffix params into base_url.
- No
> Remove integration strings from BaseClient

- .circleci/config.yml
Reverts demisto/content#4405
reverting for now until proper testing will be done to this change:
1. nightly doesn't run `instance_testing` job, only `build` job.
2. same for trigger scripts.
3. unit tests doesn't run due to lacking of python.
extra:
* `instance_testing` should output as artifacts all files (not just server logs).
note:
having two jobs that developers should keep an eye on can be confusing. we should consider different approach. 🤔
> Revert "Update circleci config for a limited build on forks"

- Integrations/MicrosoftTeams/CHANGELOG.md
- Integrations/MicrosoftTeams/MicrosoftTeams.py
- Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Ready
- Added support for single port mapping
- Added integration health command, which checks connectivity to Microsoft APIs and lists the mirrored channels
5.0
- No
@kirbles19 please review:
> Microsoft Teams - single port support and integration health command

- Tests/test_integration.py
Ready
Sometimes (mostly in nightly build) one of the API requests to the server fails making the build to fail. This should not cause the whole build to fail, rather the single unsuccessful test.
> Added try except blocks for exceptions when calling to demisto API

- Integrations/AttackIQFireDrill/AttackIQFireDrill.py
- Integrations/AttackIQFireDrill/AttackIQFireDrill.yml
- Integrations/AttackIQFireDrill/CHANGELOG.md
Ready
fixes: https://github.com/demisto/etc/issues/19353
documentation issue: https://github.com/demisto/etc/issues/19352
Added `on_demand_only` to `attackiq-run-all-tests-in-assessment` http request.
- No
Changed display name of the integration to `AttackIQ Platform`
> [Fix] attackiq-run-all-tests-in-assessment missing on_demand_only arg

- Integrations/PagerDuty/CHANGELOG.md
- Integrations/PagerDuty/PagerDuty.py
- Integrations/PagerDuty/PagerDuty.yml
- Scripts/script-PagerDutyAssignOnCallUser.yml
- Scripts/script-PagerDutyAssignOnCallUser_CHANGELOG.md
- TestPlaybooks/playbook-PagerDuty_Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/18842
- added new arguments to ***PagerDuty-get-users-on-call-now*** command:
- escalation_policy_ids: Filters the results, showing only on-calls for the specified escalation
policy IDs.
- schedule_ids: Filters the results, showing only on-calls for the specified schedule
IDs. If null is provided, it includes permanent on-calls due to direct user
escalation targets.
- No
> [Enhancement] PagerDuty-get-users-on-call-now

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
- Integrations/SplunkPy/SplunkPy.yml
Ready
fixes: https://github.com/demisto/etc/issues/19347
Added two new parameters that allow the user to control the names of the earliest fetch time and latest fetch time fields.
- No
> Added new params and changed fetch incidents to use them

- Tests/scripts/update_id_set.py
Ready
The regex that should've matched non-package integrations was replaced by the one that matches package integrations
> Replaced the integration regex 

- Integrations/integration-HybridAnalysis.yml
- Integrations/integration-HybridAnalysis_CHANGELOG.md
Ready
On the latest release, the *min_malicious_scanners* was added to ***hybrid-analysis-search*** command which caused a malformed request body. See diff
- No
> Hybrid Analysis - bug fix

- Integrations/ServiceNow/CHANGELOG.md
- Integrations/ServiceNow/ServiceNow.py
- Integrations/ServiceNow/ServiceNow.yml
Ready
fixes: [https://github.com/demisto/etc/issues/19083](https://github.com/demisto/etc/issues/19083)
Added a test for fetch_time in test-module command
- No
- Set the default value of proxy parameter to ''
- Fixed CHANGELOG format
> ServiceNow - added validation to fetch_time parameter

- Integrations/IntSight/CHANGELOG.md
- Integrations/IntSight/IntSight.py
Ready
Updating req function to return the response instead of response text.
fixes: https://github.com/demisto/etc/issues/19507
https://github.com/demisto/content/pull/4278
> Fix intsights-get-alert-image and intsights-get-alert-takedown-status commands

- Playbooks/playbook-Prisma_Cloud_Remediation_-_AWS_Security_Groups_Allows_Internet_Traffic_To_TCP_Port.yml
- Scripts/AwsEC2GetPublicSGRules/AwsEC2GetPublicSGRules.py
- Scripts/AwsEC2GetPublicSGRules/AwsEC2GetPublicSGRules.yml
- Scripts/AwsEC2GetPublicSGRules/AwsEC2GetPublicSGRules_test.py
- TestPlaybooks/playbook-AwsEC2GetPublicSGRules-Test.yml
- Tests/conf.json
- Tests/secrets_white_list.json
* Add script AwsEC2GetPublicSGRules
* code cleanup
* fix type assignment
* set array to true for ipPermissions
* add test and change output to use return_output
* add test playbook TestAwsEC2GetPublicSGRules
* add playbook Prisma Cloud Remediation - AWS Security Groups Allows Internet Traffic To TCP
* 10/30/2019 changes:
- remove CHANGELOG.md,
- use return_error
- update script and test playbook ID
* changed playbook id to match playbook name
* add docs.aws.amazon.com to whitelist
* Updated texts
Updated description texts.
* Updated texts
Updated description texts.
* Updated texts
Updated description texts.
> Add prismacloud playbook SG allows all traffic (#4471)

- Integrations/MailSenderNew/CHANGELOG.md
- Integrations/MailSenderNew/MailSenderNew.py
- Integrations/MailSenderNew/MailSenderNew.yml
Ready
Related: https://github.com/demisto/etc/issues/18994
An empty or blank fqdn can cause issues with some smtp servers. fix ignore an empty or blank configuration.
> Mail Sender new: ignore fqdn name which is empty or contains only whitespace

- Integrations/Panorama/Panorama.py
- Integrations/Panorama/Panorama.yml
Fixed: !panorama-edit-custom-url-category doesn't work with PANOS 9.x
Error message:
With message: ["Demisto_Malicious_URLs -> list 'https://xxxx.com/yyyy' is invalid. custom-url-category entry has to be type specified", 'Demisto_Malicious_URLs -> list is invalid']
Ready
Fixed: !panorama-edit-custom-url-category doesn't work with PANOS 9.x
branch | PR
Integration-BUG---Panorama |
5.0
- Yes
> Panorama edit custom url category issue on panos 9

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
Ready
`app` param is not required, and the direct key access raised `KeyError`
Any
- No
None
> SplunkPy - improved app parameter handling

- Integrations/GitHub/CHANGELOG.md
- Integrations/GitHub/GitHub.py
- Integrations/GitHub/GitHub.yml
Ready
the default fetch time was in text format, while it should be a number (the integration code converts it to int: `start_time = datetime.now() - timedelta(days=int(FETCH_TIME))`
- No, if someone used the previous default value it would break fetch flow
> Fix first fetch default value

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
Ready
fixes: https://github.com/demisto/etc/issues/19572
Splunk was producing an error  when the rule name was an array.
This case in now handled correctly.
- No
> Fixed array handling in Splunk notable to incident

- Integrations/SentinelOne-V2/CHANGELOG.md
- Integrations/SentinelOne-V2/SentinelOne-V2.py
- Integrations/SentinelOne-V2/SentinelOne-V2_test.py
Ready
fixes: https://github.com/demisto/etc/issues/19630
Fix issue where not all threats were getting fetched into Demisto as incidents properly.
any
- No
Fixed bug of comparisons with a Nonetype operand in the `get_threats_command` function.
> Sentinelone v2 fetch fix

- Integrations/AWS-IAM/AWS-IAM.yml
- TestPlaybooks/playbook-AWS-IAM-Test.yml
- Tests/conf.json
Ready
fixes: master
Old AWS playbooks were using hardcoded version. Switched IAM test playbook to -1
> Change Version Number in IAM Test Playbook

- Playbooks/playbook-Get_File_Sample_By_Hash_-_Cylance_Protect_v2.yml
- Playbooks/playbook-Get_File_Sample_By_Hash_-_Generic_v2.yml
- Playbooks/playbook-Retrieve_File_from_Endpoint_-_Generic.yml
Ready
fixes: https://github.com/demisto/etc/issues/19748
New playbooks: 
1) Get File Sample By Hash - Cylance Protect v2
2) Get File Sample By Hash - Generic v2
3) Retrieve File from Endpoint - Generic
4.0.0
- No
> New playbooks - Retrieve file by hash & generic

- Scripts/CommonServerPython/CHANGELOG.md
- Scripts/CommonServerPython/CommonServerPython.py
- Scripts/CommonServerPython/CommonServerPython_test.py
Ready
fixes: tbd
Credential object object named with one of the following strings: ‘key’, ‘private’, ‘password’, ‘secret’, ‘token’ would error.
- No
> CommonServerPython IntegrationLogger auto replace fix

- Scripts/HTMLDocsAutomation/CHANGELOG.md
- Scripts/HTMLDocsAutomation/HTMLDocsAutomation.py
- Scripts/HTMLDocsAutomation/HTMLDocsAutomation_test.py
Ready
1. There was an issue where in the commands part it was command_name:command_name instead of description: name(i.e. List all assets: attackiq-list-assets)
2. i added a link to the part of the page where the command is detailed.
- No
> HTMLDocumenation commands fix

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/19849
https://github.com/demisto/etc/issues/19870
Remove LogRhythmRest and LogRhythm from skipped integrations after fixed the instance.
> remove logrhythm tests from skipped

- Integrations/rasterize/CHANGELOG.md
- Integrations/rasterize/rasterize.py
Ready
fixes: https://github.com/demisto/etc/issues/19847
Fixed Rasterize bug: not supporting `px` suffix in `width` and `height` parameters.
Now it will support both conventions.
- No
> 'px' suffix

- Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.py
- Integrations/BeyondTrust_Password_Safe/BeyondTrust_Password_Safe.yml
- Integrations/BeyondTrust_Password_Safe/CHANGELOG.md
Ready
fixes: https://github.com/demisto/etc/issues/19565
Credentials created and stored by this integration into Demisto did not have unique names preventing users from using the stored credentials with duplicate names when configuring integrations. Changed the names given to stored credentials so as to be more unique.
any
- Yes
Added python subtype to the integration yaml.
> Change Created Credential Names to be Unique

- Scripts/script-UnEscapeURLs.yml
- Scripts/script-UnEscapeURLs_CHANGELOG.md
- TestPlaybooks/playbook-UnEscapeURLs-Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/18545
Was mistakenly only handling Proofpoint v3 links that had been modified by Outlook. Updated the script to handle regular Proofpoint v3 links and added a check to the test playbook.
branch | PR
update-unescapeurls | https://github.com/demisto/content/pull/4639
any
- No
> UnEscapeURLs Proofpoint V3 Fix

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
- Integrations/SplunkPy/SplunkPy.yml
Ready
fixes: https://github.com/demisto/etc/issues/20012
The limit on Splunk's fetch incidents was too low and caused slow ingestion.
The problem should be fixed by this increase.
- No
> Increased maximal fetch limit

- Scripts/XDRSyncScript/CHANGELOG.md
- Scripts/XDRSyncScript/XDRSyncScript.py
Ready
fix - xdr-update-incident should not execute with empty arguments
- No
> fix - xdr-update-incident should not execute with empty arguments

- TestPlaybooks/playbook-SecurityAdvisor-Test.yml
- Tests/conf.json
Ready
fixes the build, the integration is from version 4.5.0 but the test has no fromversion, that is why the build fails on server with version prior than 4.5.0
- No
> add fromversion to test playbook

- Playbooks/playbook-Phishing_-_Core.yml
- Playbooks/playbook-Phishing_-_Core_CHANGELOG.md
- TestPlaybooks/playbook-Phishing_-_Core_-_Test.yml
- Tests/conf.json
Ready
- fixes: https://github.com/demisto/etc/issues/20087
- fixes test failing issue as well (no issue opened)
- The test was failing because the scheduled command that should automatically complete the manual task in the `Phishing - Core` playbook, was referring to the wrong playbook ID (most likely due to changes in the test). I fixed the ID and increased the frequency and number of times that the manual task completion runs.
- I also spotted a small bug in the playbook in the Rasterize task - it would attempt to run even if inactive. Fixed as well.
4.5.0
- No
> Phishing - Core - playbok + test fix

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
- Integrations/SplunkPy/SplunkPy.yml
Ready
fixes: https://github.com/demisto/etc/issues/20060
Whenever an event was fetched as an incident to Demisto, some of the fetched event's fields were missing from the labels.
I've added a parameter that will allow the user to have those fields added to the labels.
However, since this is a significant increase in each incident's size which might slow down fetching, the default remains only adding the raw data to the labels.
- No
> Splunk - Fixed the missing data of notable events bug

- Tests/scripts/wait_until_server_ready.py
Ready
nightly build fails because server is not ready until the end of the retries to connect to it.
so this one increases the retries by 50%
- No
> extend retries in wait for server to be ready

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/20156
fixes: https://github.com/demisto/etc/issues/20037
don't see any reason to change the SELinux permissions as the tests passes.
- No
> Unskipping PAN-OS

- Tests/test_content.py
Ready
fixes: a bug, probably creates others.
We used username and password while running the tests. By design, demisto-py creates a singular client. This client is then invoked multiple times throughout the testing process. After an undetermined amount of time, the session expires and renders the client invalid. We catch this error, but it takes down the build in the process.
We are changing the client to use the api-key which should address this issue.
> Client change to use API key

- TestPlaybooks/playbook-RedLockTest.yml
- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/15493
Fixed Redlock's test with new creds, and now removing it from skipped.
- No
> Moving Redlock out of skipped

- Integrations/JiraV2/CHANGELOG.md
- Integrations/JiraV2/JiraV2.py
- Integrations/JiraV2/JiraV2.yml
- TestPlaybooks/playbook-Jira-v2-Test.yml
Ready
fixes: https://github.com/demisto/etc/issues/19707
`jira-issue-upload-file` fails with error 500 if the file to be uploaded contains special (non-ASCII). added a new argument **attachmentName** that will override the original filename when trying to upload.
- No
> jira-issue-upload-file with ASCII filenames

- Tests/scripts/constants.py
- Tests/scripts/hook_validations/integration.py
- Tests/scripts/hook_validations/tests/integration_test.py
- docs/code_conventions/README.MD
- docs/yaml-file-integration/README.MD
Ready
fixes: https://github.com/demisto/etc/issues/19803
IOC reputation commands will be required to support batched indicators. Therefore implement validations check that args are marked as `isArray`.
any
- No
> IOC Reputation Command Args isArray Validation

- Integrations/integration-VirusTotal.yml
- Integrations/integration-VirusTotal_CHANGELOG.md
- TestPlaybooks/playbook-virusTotal-test.yml
Ready
related: demisto/etc#19784
Added batch support to IP check commands
branch | PR
ipinfo-batch | https://github.com/demisto/content/pull/4699
urlscan.io | https://github.com/demisto/content/pull/4703
circl.lu (CVE Search) | https://github.com/demisto/content/pull/4718
Have I been Pwned | https://github.com/demisto/content/pull/4877
AbuseIPDB | https://github.com/demisto/content/pull/4894
IBM X-Force Exchange | https://github.com/demisto/content/pull/4929
Any
- No
None
> Added batch support for IP URL Domain - virusTotal

- Integrations/integration-ArcherRSA.yml
- Integrations/integration-ArcherRSA_CHANGELOG.md
Ready
fixes: https://github.com/demisto/etc/issues/19721
For several app IDs, such as 411, the field mapping which returns from Archer is reversed (the field ID is mapped to the field name instead of vice versa).
These cases used to cause an error, and are now handled.
- No
> Archer - Fixed retrieval of app IDs for applications with reverse field mapping. 

- Reports/report-docx-criticalAndHighIncidentsReport.json
- Reports/report-docx-criticalAndHighIncidentsReport_CHANGELOG.md
Ready
fixes: https://github.com/demisto/etc/issues/19889
The headers of the table's column s in the report were not capitalised.
Now they are.
Before (on my mac):
After (notice the problem is fixed):
- No
> docxCriticalAndHighIncidentsReport - Fixed the capitalisation of the table's headers

- Integrations/integration-LogRhythm.yml
- Integrations/integration-LogRhythm_CHANGELOG.md
- Tests/secrets_white_list.json
Ready
fixes: https://github.com/demisto/etc/issues/20409
The error message in 'getTimeFrame' method was not clear and therefore has changed
- No
> Changed the error message in 'getTimeFrame' method

- Scripts/CommonServerPython/CHANGELOG.md
- Scripts/CommonServerPython/CommonServerPython.py
- Scripts/script-CommonServer.yml
- Scripts/script-CommonServer_CHANGELOG.md
Ready
The current `dbotscores` object does not actually represent DBot Scores and is misleading, so added a comment about that
Any
- No
None
> CommonServer - comment about DBot Score object

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/19841
The playbook `Get File Sample From Hash - Generic` use the playbook `Get File Sample By Hash` for the deprecated integration Carbon Black Enterprise Response(Go version) and for Cylance protect.
No need to test it in Carbon Black and for testing in Cylance Protect we have `Get File Sample By Hash - Cylance Protect - Test`
> remove Get File Sample By Hash - Generic - Test

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/19843
https://github.com/demisto/etc/issues/19852
The tests: get_file_sample_by_hash_-_carbon_black_enterprise_Response_-_test and search_endpoints_by_hash_-_carbon_black_response_-_test uses the deprecated integration Carbon Black Enterprise Response(Go version).
> remove carbon black tests

- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/19842
The playbook `Get File Sample From Hash - Generic` use the integrations Cylance Protect and Carbon Black Enterprise Response(Go version) both of them are deprecated.
> remove Get File Sample From Hash - Generic - Test

- Integrations/Slack/CHANGELOG.md
- Integrations/Slack/Slack.py
- Integrations/Slack/Slack_test.py
Ready
fixes: https://github.com/demisto/etc/issues/20429
As in Slack v1, added Reporter, Reporter email and Source to the incidents labels created in direct messages.
- No
> Slack - Add incident labels

- TestPlaybooks/playbook-SentinelOne-Beta-Test.yml
Ready
Changing the sleep to 30 seconds, since we got an error `query is still in process`
- No
> Test Fix SentinelOne V2

- Scripts/ZipFile/CHANGELOG.md
- Scripts/ZipFile/ZipFile.py
Ready
The output path in the playbook was wrong. added the output in the script.
- No
> fixed output paths in ZipFile

- TestData/Inline_malicious_url.eml
- TestPlaybooks/NonCircleTests/playbook-Extract_Indicators_From_File_-_test.yml
- TestPlaybooks/NonCircleTests/playbook-Phishing_test_-_Inline.yml
- TestPlaybooks/NonCircleTests/playbook-Phishing_test_-_attachment.yml
- TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test.yml
- TestPlaybooks/playbook-Extract_Indicators_From_File_-_Generic_v2_-_Test_4_5.yml
- TestPlaybooks/playbook-Phishing_v2_Test_-_Attachment.yml
- TestPlaybooks/playbook-Phishing_v2_Test_-_Inline.yml
Ready
Seems like the URL **sometimes** wasn't detected as malicious even though it was added to the miner right before being calculated. Although the build passed when the original URL was replaced with this one, it failed nightly. Attempting this fix now which works locally.
- No
> Stability fix for phishing tests

- Integrations/RSANetWitness_v11_1/CHANGELOG.md
- Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
Ready
fixes: https://github.com/demisto/etc/issues/18744
Changed handle proxy spot to be after the get token operation
- No
- RSA NetWitness v11.1
> changed handle proxy spot to be after the get token operation

- Integrations/IntSight/CHANGELOG.md
- Integrations/IntSight/IntSight.py
- Integrations/IntSight/IntSight.yml
Ready
fixes https://github.com/demisto/etc/issues/20715
`is-hidden` and `rate` in the command `close-alert` were not handled well when checked if provided.
didn't add test because there is no command to create an alert.
Any
- No
None
> IntSights close-alert handle arguments prorperly

- dev-requirements-py3.txt
dev-requirements-py3 will now install up to but not including demisto-sdk version 1.0.0
> fixing dev-requirements-py3 demisto-sdk download

- Integrations/rasterize/CHANGELOG.md
- Integrations/rasterize/rasterize.py
- Integrations/rasterize/rasterize.yml
- Integrations/rasterize/rasterize_test.py
Ready
fixes: https://github.com/demisto/etc/issues/20702
Implemented a function that closes the driver & reaps all the child process that are defunct.
- No
> Defunct processes

- .circleci/config.yml
Ready
fixes: https://github.com/demisto/content/pull/5213#discussion_r360155250
Changes the location of the unzipped content_test.zip so that it won't end up in the artifacts directory should the build step unexpectedly fail before the extracted contents are deleted.
any
- No
> unzipped test_content not in artifacts folder

- TestData/attachment_malicious_url.eml
Ready
fixes: https://github.com/demisto/etc/issues/20867
Updated phishing v2 attachment testdata with new EML file which contains a new TXT file which contains a new URL.
Should make the test pass from now on (unless failing for the weird server issue)
4.1.0
- No
> Updated phishing v2 attachment testdata

- TestPlaybooks/script-SimpleRequest.yml
- TestPlaybooks/script-SimpleRequestExecutor.yml
- TestPlaybooks/script-SimpleRequestGetter.yml
- Tests/conf.json
Ready
fixes: https://github.com/demisto/etc/issues/20337
Add disable_warnings to `SimpleRequest`, `SimpleRequestExecutor`,  and `SimpleRequestGetter` scripts because the warning was failing the task in the playbook.
5.0.0
- No
> Request debugging test fix

- Scripts/ParseEmailFiles/CHANGELOG.md
- Scripts/ParseEmailFiles/ParseEmailFiles.py
Ready
fixes: https://github.com/demisto/etc/issues/20683
Won't break when attachment has neither `DisplayName` nor `AttachName`.
any
- No
- ~~[ ] Tests~~ - couldn't create an .msg file for a unittest
Tests
> Parseemailfiles lower nonetype fix

- Integrations/integration-HybridAnalysis.yml
- Tests/test_integration.py
Ready
fixes: https://github.com/demisto/etc/issues/20372
Fixed the issue in `test_integration.py` in which whenever an investigation experienced an error during the CircleCI build, the body of the error didn't seep to the logs.
- No
Currently, there's also a change in Hybrid Analysis integration that causes it to fail in order to see the fix in the build.
> test_integration.py bug

- Integrations/integration-IBM_Resilient_Systems.yml
- Integrations/integration-IBM_Resilient_Systems_CHANGELOG.md
Ready
fixes: https://github.com/demisto/etc/issues/20815
Changed to use `.get()` instead of direct key access to NistAttackVector
Any
- No
None
> IBM Resilient - fixed NistAttackVector key error

- Integrations/PaloAlto_MineMeld/CHANGELOG.md
- Integrations/PaloAlto_MineMeld/PaloAlto_MineMeld.yml
Type argument to commands `minemeld-add-to-miner` and `minemeld-remove-from-miner` was. supported in the code but not exposed in the integration YAML file.
- Exposed *type* argument in `minemeld-add-to-miner` command in the YAML file
- Exposed *type* argument in `minemeld-remove-from-miner` command in the YAML file
- Updated CHANGELOG.md 
No. The *type* argument is **not** required and if not specified the behavior is the same as before.
> Fixes oversight in Palo Alto Networks MineMeld integration

- Tests/demistomock/demistomock.py
Ready
Added new demisto command getIndexHash to demistomock. The command returns the hash of the current tenant index.
> added getIndexHash to demistomock

- Beta_Integrations/OpenLDAP/CHANGELOG.md
- Beta_Integrations/OpenLDAP/OpenLDAP.yml
Ready
OpenLDAP commands where marked as `Potentially harmful` (in order to prevent users from running it's command in playbooks), what caused failure on running scheduled commands (populate AD Roles Mapping) on engine with the following error: `Module OpenLDAP does not accept command: ad-groups (High privilege command ad-groups cannot be run automatically, please complete task manually (67))`. 
The fix is to remove `Potentially harmful` from integration commands.
- No
> OpenLDAP - fixed authentication with engine 

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
The Demisto entry resulting from a Splunk search may not be properly
formatted when the search string contains special characters like pipe,
backticks etc. Removing newlines from the markdown header resolves this
issue and allows for the resulting Entry/Note/Evidence to be converted
to HTML using the built-in mdToHtml regardless of the presence of special
characters in the query string.
Ready/In Progress/In Hold(Reason for hold)
x.x.x
- Yes
- No
Describe additional changes done, for example …
> Remove newlines in markdown header

- Integrations/FeedCSV/FeedCSV.py
Ready
Fixed an issue with the instance testing when using more than a single fieldname.
5.5.0
- No
> [Fix] CSVFeed - fixed instance test for multiple fieldnames

- Scripts/CommonServerPython/CommonServerPython.py
Ready
timeout can be a tuple. fixed it.
- No
> fix annotation for timeout in commonsp

- release_notes.py
in json files from version key is with capital V (`fromVersion`).
> fix release notes generator

- TestPlaybooks/playbook-GetIndicatorDBotScore_Test.yml
There is no `SHA1` indicator type anymore in 5.5. Now it is only `File`
> fix GetIndicatorDBotScore test

- Tests/scripts/wait_until_server_ready.py
Ready
Fixes issue where during the build the expected content version on the Demisto instances during the `Setup Instances` step is for the new release number but because the installation of new content does not occur until the `Run Tests` steps, the version of content actually found on the instances does not match.
- Any
- No
> Release fix

- Scripts/DBotPredictPhishingWords/CHANGELOG.md
- Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.py
1) presenting positive words instead of positive tokens at explain_result_hr
2) removing tailing punctuation from positive and negative words (more readable, and positive word ends with comma causes highlighting of all text)
> Bugs fixes at DBotPredictPhishingWords 

- Scripts/ReadPDFFileV2/CHANGELOG.md
- Scripts/ReadPDFFileV2/ReadPDFFileV2.py
- Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
- TestPlaybooks/playbook-ReadPDFFileV2_Test.yml
fixes: https://github.com/demisto/etc/issues/21826
- Fixed a bug where emails would be labeled as urls.
- Added Email standard context.
> [Fix] ReadPDFFileV2 doesn't extract indicators correctly

- Integrations/integration-SumoLogic.yml
- Integrations/integration-SumoLogic_CHANGELOG.md
N/A
This would cause incorrect results to be returned by the Sumo integration, based only on the subset of messages being scanned.
> SumoLogic: do not exit early when fetching records

- Tests/test_content.py
in case of a problem, we should assume latest demisto version
fixes:
> Fix default demisto version in test_content.py

- Integrations/Panorama/Panorama.py
- Integrations/Panorama/Panorama.yml
- Playbooks/NetSec_-_Palo_Alto_Networks_DUG_-_Tag_User.yml
- Playbooks/playbook-Block_Account_-_Generic.yml
fixes: https://github.com/demisto/etc/issues/19049
Added 2 commands to PAN-OS to support registering and unregistering user tags.
Added the command to Block Account generic playbook.
Added another playbook showcasing this capability which can be further customized.
Tested working with PAN-OS 9.1.0
> PAN-OS integration - Dynamic User Groups - tagging and untagging

- Packs/FeedAWS/Integrations/FeedAWS/CHANGELOG.md
- Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.py
Fixed the mapping to be cli name and not name
> AWS Feed fix

- Integrations/ZeroFox/CHANGELOG.md
- Integrations/ZeroFox/ZeroFox.py
fixes: https://github.com/demisto/etc/issues/21886
Fixed an issue with fetch incidents fetching the same incident repeatedly
> zerofox bug fix

- Tests/conf.json
Skip AlphaSOC Wisdom failed on nightly and other builds.
> Skip AlphaSOC Wisdom because API key has expired

- .hooks/bootstrap
Check to find that python3 is 3.7 or above. Fix after test on Ubuntu by @aburt-demisto
> fix for bootstrap to detect python 3.7 and above (needed by demisto-sdk)

- Tests/conf.json
- Tests/test_utils.py
related to: https://github.com/demisto/etc/issues/20719
Increased default docker memory usage threshold from 50 to 75 MB and increased threshold for additional tests.
> Increased default docker memory usage threshold and additional tests

- Scripts/DockerHardeningCheck/CHANGELOG.md
- Scripts/DockerHardeningCheck/DockerHardeningCheck.py
- Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
Update docker hardening script to include also in error entry the full details why the error happened. This helps if we get just the error entry form a customer without the entry with the table results.
> update docker hardening to provide full error entry

- TestPlaybooks/playbook-Send_Investigation_Summary_Reports_Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/22299
Use default mem threshold (75MB)
> remove mem threshold for send notification test so it uses the default

- Misc/reputation-url.json
Works towards https://github.com/demisto/etc/issues/21756
Update the default mapping of the URL indicator type to include new indicator fields.
> URL Indicator Type: update default mapping

- Misc/reputation-ip.json
Works towards https://github.com/demisto/etc/issues/21756
Update the default mapping of the IP indicator type to include new indicator fields.
> IP Indicator Type: update default mapping

- Integrations/AbuseDB/AbuseDB.py
Ready
related to: https://github.com/demisto/content/pull/5404
Update a command that acts on an indicator to return timeline data to be used by server in updating the Indicator's timeline. An example command is needed by server-side to demo this feature.
5.5.5
- No
> update AbuseDB's indicator-related commands to return timeline data

- Misc/reputation-ipv6.json
Works towards https://github.com/demisto/etc/issues/21756
Update the default mapping of the IPv6 indicator type to include new indicator fields.
> IPv6 Indicator Type: update default mapping

- Integrations/JiraV2/CHANGELOG.md
- Integrations/JiraV2/JiraV2.py
- Integrations/JiraV2/JiraV2.yml
N/A
Fixed an issue in ***jira-create-issue*** and ***jira-edit-issue*** where the due date was not set correctly.
I'm pretty certain that changing just the `issue_args["duedate"]` to `issue_args["dueDate"]` would be sufficient, but leaning to the defensive programming here.
> [JiraV2] Fix setting up incident due date

- Integrations/RSANetWitness_v11_1/CHANGELOG.md
- Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
- Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1_test.py
NetWitness 11.4 changed the incident JSON format. If no sources have been defined, they now display as `[null]` in the JSON:
```
{"id":"INC-46269","title":"My incident","summary":null,"priority":"Critical","riskScore":90,"status":"New","alertCount":2,"averageAlertRiskScore":90,"sealed":true,"totalRemediationTaskCount":0,"openRemediationTaskCount":0,"created":"2020-02-20T15:38:51.710Z","lastUpdated":"2020-02-20T15:38:51.710Z","lastUpdatedBy":null,"assignee":null,"sources":[null],"ruleId":"5d2d850417efd403bae12e70","firstAlertTime":"2020-02-20T15:38:48.370Z","categories":[],"journalEntries":null,"createdBy":"My incident","deletedAlertCount":0,"eventCount":2,"alertMeta":{"SourceIp":[],"DestinationIp":[]}}
```
This causes the integration to crash with this error:
```
!netwitness-get-incident …
```
> Fix netwitness-get-incident for NetWitness 11.4

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/22298
PANW Cortex out of skipped build is green.
> cortex out of skipped

- Packs/CVESearchV2/Integrations/CVESearchV2/CVESearchV2_test.py
CVE-Search website can sometimes be flaky, no need to test connectivity to it in unittest
> Removed test_module from cvesearch unittesting

- .circleci/config.yml
- .hooks/bootstrap
fixes: https://github.com/demisto/etc/issues/22604
Skip setup of py2 when working on a fork
> support for skipping py2 setup in bootstrap

- Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
Optimise so $demisto object will initialise from global:InnerContext also if it is an object. Save on the server side the overhead to convert to a string. Server PR will follow once this is merged.
> CommonServerPowerShell accept inner context as an object

- Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/CHANGELOG.md
- Packs/FeedAlienVault/Integrations/FeedAlienVaultOTXTaxii/FeedAlienVaultOTXTaxii.yml
- Packs/FeedAlienVault/Integrations/FeedAlienVaultReputation/README.md
- Packs/FeedAlienVault/pack_metadata.json
Is it just me or the `t` comes naturally after `alien`?
> Fix typos in AlienVault

- Tests/store_packs.py
Server version 6.0.0 will not support old format reputation json files. Skipped it while zipping and additionally removed zipping of not necessary files that were used for debugging (pack_metadata.json).
> Marketplace - Skipped zipping of old format reputation files

- Integrations/EDL/EDL.yml
Fixes a typo in the description of the `edl-update` command. `available` was misspelled as 'avaialable'.
> EDL edl-update Command Description Typo Fix

- Scripts/FindSimilarIncidentsV2/CHANGELOG.md
- Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
Just release notes - those arguments should be deprecated long ago, probably missed
> Find similar incident deprecated args

- Integrations/Tanium_v2/CHANGELOG.md
- Integrations/Tanium_v2/Tanium_v2.py
- Integrations/Tanium_v2/Tanium_v2.yml
- Integrations/Tanium_v2/Tanium_v2_test.py
fixes: https://github.com/demisto/etc/issues/22492
- Update parse_question method to support question text with parameters instead of using the `parameters` argument in `tn-ask-question` command, which means that now its possible to call this command:
`!tn-ask-question question-text="Get Folder Contents[c:\] from all machines"`
instead of this:
`!tn-ask-question question-text="Get Folder Contents from all machines" parameters="Folder Contents{folderPath=c:\}"`
- Fix parse_question_results method to support list in single column result.
> Update Tanium V2 to support question text with parameters

- Integrations/SplunkPy/CHANGELOG.md
- Integrations/SplunkPy/SplunkPy.py
- Integrations/SplunkPy/SplunkPy.yml
- TestPlaybooks/playbook-SplunkPy-Test-V2.yml
replacing: https://github.com/demisto/content/pull/6104
fixes: https://github.com/demisto/etc/issues/22345
Add a new command to SplunkPy integration for checking the status of a job in Splunk
> New SplunkPy command !splunk-job-status

- Tests/conf.json
`Feodo Tracker Hashes Feed` memory threshold was string instead of int which crashed the nightly build. FYI @roysagi
> Changed type of memory threshold string to int

- TestPlaybooks/NonCircleTests/playbook-TestParseEmailHeaders.yml
- TestPlaybooks/playbook-CreateIndicatorFromSTIXTest.yml
- TestPlaybooks/playbook-UnzipFile-Test.yml
fix download links in test playbooks of test data.
after we moved the content items to Legact packs some link were broken
> fix download links in test playbooks of test data

- Packs/Base/Scripts/CommonServerPython/CHANGELOG.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
When the base client gets a text error response- trying to get `res.json()` will cause ValueError and hide the true cause of the error which can be taken from `res.text`
> Improved base client exception parsing

- Tests/Marketplace/upload_packs.py
In line 461, `private_packs` may be not defined if there is no private bucket provided. I defined it in the beginning of the code.
> Secure private packs

- Tests/conf.json
Removed the test playbook configuration because the test playbook not exist anymore , was deleted by the partner
> remove sixgill darkfeed test playbook - the old playbook was deleted 

- Tests/conf.json
https://github.com/demisto/etc/issues/22018
Removing the high threshold for slack PID in the build
> Remove slack threshold

- Tests/conf.json
Test failed on nightly due to memory threshold
> added memory threshold to recorded future feed on build

- Packs/Expanse/Integrations/Expanse/CHANGELOG.md
- Packs/Expanse/Integrations/Expanse/Expanse.py
- Packs/Expanse/pack_metadata.json
Incident ingest was not including behavior data _seemingly_ because `demisto.incidents()` was called more than once. There was also an issue where our logic of whether to check for new events was off by 1 day, so it was duplicating events. 
> [expanse-272] Expanse Expander - Fixing incident polling bug

- Tests/Marketplace/Tests/upload_packs_test.py
- Tests/Marketplace/upload_packs.py
In case that new pack is uploaded, need to create new pack folder in index. `shutill.copy` doesn't handle it. Received error: [Errno 20] Not a directory: `/tmp/tmp.ZbcYkPjdus/index/MicrosoftGraphCalendar/metadata-1.0.0.json`
https://circleci.com/gh/demisto/content/49515#artifacts/containers/0
> Marketplace - update index fix

- .circleci/config.yml
- Tests/Marketplace/upload_packs.py
- Skipped signing step in `upload_packs` until the issue is resolved. Currently all packs fail on signing step `b'Unable to read key file: /keyfile. Error: open /keyfile: no such file or directory\n'`
`--------------------------------------- Packs Upload Summary ---------------------------------------
Total number of packs: 76
Number of failed packs: 76
`
- Additionally from now, if at least one of pack fails in upload step, the build will fail after adding non zero exit status.
> Marketplace - skipped temporary signing step

- Tests/Marketplace/marketplace_services.py
fixes: https://github.com/demisto/etc/issues/23844
Changed `contentItems` `report` section dictionary according to @asafshen request.
Example of parsed report item:
```
{
"name": "Last 30 days incidents",
"description": "Last 30 days summary of incidents statistics, followed by a list of all current open incidents."
}
```
> Marketplace - changed contentItems report section

- Packs/Legacy/Integrations/GitHub/CHANGELOG.md
- Packs/Legacy/Integrations/GitHub/GitHub.py
- Packs/Legacy/Integrations/GitHub/GitHub.yml
- Packs/Legacy/Integrations/GitHub/README.md
Add support for authenticating using creds for Github bots.
The flow doesn't replace the existing one with API key, it just operates one step before by generating the API key using the creds. I also wrapped it using 
`if TOKEN == '' and PRIVATE_KEY != ''` to not break backward compatibility.
> Add creds support for Github integration

- Tests/test_integration.py
https://github.com/demisto/etc/issues/21383
Adjusted the incident search flow to try and handle the issue and debug it:
- increased timeout to 300 sec
- increased the sleep to 10 sec
- added prints of search filter and search response
> Test integration flow - modify incident search for debugging

- Tests/scripts/configure_tests.py
- Tests/scripts/infrastructure_tests/test_configure_tests.py
fixes: https://github.com/demisto/etc/issues/24015
Moved `sample_test` collection after `is empty tests` condition. Test samples shouldn't be triggered when tests were provided.
> [CircleCi] Don't Trigger Sample Tests If Tests Were Provided

- Packs/GenericSQL/Integrations/GenericSQL/CHANGELOG.md
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
fixes: https://github.com/demisto/etc/issues/23354
When a sql query return an empty table an error return - fixing it to a valid output "No entries.".
> Genericsql - when query returns an empty table don't return an error

- Packs/EDL/Integrations/EDL/CHANGELOG.md
- Packs/EDL/Integrations/EDL/EDL.py
fixes: https://github.com/demisto/etc/issues/23728
Set app hostname to be `0.0.0.0` to hanlde IPv6
> EDL - set app server host to handle ipv6

- Tests/test_integration.py
Changed the logic to print the server incident search response only in case of timeout
> Tests - print incident search response only in case of timeout

- Packs/Zabbix/pack_metadata.json
Changed `currentVersion` from `2.0.0` to `1.0.0`
> Zabbix - currentVersion from 2.0.0 to 1.0.0

- Packs/Zabbix/pack_metadata.json
Pack Metadata should be 1.0.0 as initial release.
> Pack Metadata should be 1.0.0 as initial release.

- Packs/Expanse/Integrations/Expanse/CHANGELOG.md
- Packs/Expanse/Integrations/Expanse/Expanse.py
- Packs/Expanse/Integrations/Expanse/Expanse.yml
- Packs/Expanse/Integrations/Expanse/Expanse_test.py
- Packs/Expanse/Integrations/Expanse/README.md
N/A
Adds support for new *expanse-get-exposures* command.
> [expanse-272] Add support for expanse-get-exposures command

- Tests/Marketplace/Tests/marketplace_services_test.py
- Tests/Marketplace/marketplace_services.py
- Fixed `local variable 'user_metadata' referenced before assignment` error when trying to load missing pack metadata (https://circleci.com/gh/demisto/content/52017).
-  Deleted `Okta_v2` folder, the real pack is `Okta`.
> [Marketplace] - missing pack metadata load fix

- Packs/Legacy/Scripts/FilterByList/CHANGELOG.md
- Packs/Legacy/Scripts/FilterByList/FilterByList.py
- Packs/Legacy/Scripts/FilterByList/FilterByList.yml
- Packs/Legacy/Scripts/FilterByList/FilterByList_test.py
fixes: demisto/etc#24185
Since we can configure Demisto lists to have other delimiters besides "," we need to add that option to Filterbylist script
> Added delimiter argument

- .circleci/config.yml
Moves configuration of a scheduled build to the circleci config file.
Triggers the scheduled instances test build from the circleci config file itself.
> Schedule Trigger instances_test

- Packs/Expanse/Integrations/Expanse/CHANGELOG.md
- Packs/Expanse/Integrations/Expanse/Expanse.py
- Packs/Expanse/Integrations/Expanse/Expanse.yml
- Packs/Expanse/Integrations/Expanse/Expanse_test.py
- Packs/Expanse/Integrations/Expanse/README.md
We've received a custom request to do severity filtering on new incidents during ingest, rather than allow customers to utilize playbook filtering to auto-close low-severity incidents. This change adds support for a new `minimum_severity` app param to choose `ROUTINE`, `WARNING`, or `CRITICAL` as the minimum Expanse severity level they'd like to ingest. `WARNING` is default. 
> [expanse-272]  Adding support for minimum severity incident filtering

- Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule.py
- Packs/ApiModules/Scripts/JSONFeedApiModule/JSONFeedApiModule_test.py
- Packs/FeedJSON/Integrations/FeedJSON/CHANGELOG.md
fixes: https://github.com/demisto/etc/issues/24461
Added handling for flattened list of indicators inside a JSON object.
Before it was treated as json objects that includes the value, now it also support a list of text indicators one after another. (you can see an example in the test)
> FeedJSON handling flattened list inside a JSON object

- .circleci/config.yml
- Tests/mock_server.py
- Tests/scripts/ami_mock_dependencies_setup.sh
- Tests/scripts/copy_content_data.sh
- Tests/test_content.py
- Tests/timestamp_replacer.py
Implements timestamp replacement script that is executed by `mitmdump`. After recording a mock file, the file is edited to replace timestamp data with constant values. The next time that a test playbook is executed against that mock, the requests are modified as they are made to replace the same timestamp data that was replaced in the mock file with the same constant values so that the requests being made by the test playbook match the requests in the edited mock file.
> Timestamp Replacement

- Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2.yml
- Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_CHANGELOG.md
- Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_README.md
Ready
fixes: https://github.com/demisto/etc/issues/24202
Replaced the deprecated `SendEmail` script with the `send-mail` command.
4.5.0
No
> Replaced SendEmail with send-mail in Phishing v2

- Packs/CortexDataLake/TestPlaybooks/Cortex_Data_Lake_Test.yml
It appears `CharacteristicOfApp` is not returned in all the records, removing it from the test playbook verification.
> removed verification for CharacteristicOfApp field

- Packs/DeprecatedContent/Playbooks/playbook-ExtraHop_-_Ticket_Tracking.yml
- Packs/DeprecatedContent/Playbooks/playbook-ExtraHop_-_Ticket_Tracking_CHANGELOG.md
- Packs/DeprecatedContent/Playbooks/playbook-ExtraHop_-_Ticket_Tracking_README.md
Ready
fixes: https://github.com/demisto/etc/issues/24207
Replaced deprecated `SearchIncidents` with `SearchIncidentsV2` in `ExtraHop - Ticket Tracking`
4.5.0
> Replaced deprecated searchincidents in ExtraHop - Ticket Tracking

- .circleci/config.yml
replaced `GIT_SHA1` value in order to delete the branch `20.5.0_clear_rn`.
> updated git sha1 of clear release notes of version 20.5.1

- Packs/FeedMicrosoftIntune/Integrations/FeedMicrosoftIntune/CHANGELOG.md
- Packs/FeedMicrosoftIntune/ReleaseNotes/1_0_1.md
- Packs/FeedMicrosoftIntune/pack_metadata.json
- Packs/PAN-OS/Integrations/Panorama/CHANGELOG.md
- Packs/PAN-OS/Integrations/Panorama/Panorama.py
- Packs/PAN-OS/ReleaseNotes/1_0_1.md
- Packs/PAN-OS/pack_metadata.json
fixes: demisto/etc#24420
Replaced spaces with '%20' in the URL output
> Replaced spaces with '%20' in the URL output

- Packs/CommonScripts/Scripts/script-EmailAskUser_README.md
Adding a Prerequisites section like in https://xsoar.pan.dev/docs/reference/scripts/slack-ask.
makes it easier to the user to understand which integration instance needed in order to use the script.
> Adding a Prerequisites section to EmailAskUser

- Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/CHANGELOG.md
- Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
- Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
- Packs/MicrosoftGraphListener/ReleaseNotes/1_0_1.md
- Packs/MicrosoftGraphListener/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/24502
In case no emails were fetched, now time was set as last fetch, and led to emails missed and not fetched
set the last run to be the last fetched
> Microsoft Graph Mail Single User - set last run to be last fetched and not now time

- Packs/Legacy/Layouts/layout-indicatorsDetails-domain.json
- Packs/Legacy/Layouts/layout-indicatorsDetails-domain_CHANGELOG.md
- Packs/Legacy/Layouts/layout-indicatorsDetails-ip.json
- Packs/Legacy/Layouts/layout-indicatorsDetails-ip_CHANGELOG.md
- Packs/Legacy/Layouts/layout-indicatorsDetails-unifiedFile.json
- Packs/Legacy/Layouts/layout-indicatorsDetails-unifiedFile_CHANGELOG.md
- Packs/Legacy/Layouts/layout-indicatorsDetails-url.json
- Packs/Legacy/Layouts/layout-indicatorsDetails-url_CHANGELOG.md
Fixes an issue where Extended Details would not display the Threat Category and Threat Category Confidence fields.
> Threat Types layouts fix

- Packs/FeedCofense/Integrations/FeedCofense/CHANGELOG.md
- Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.py
- Packs/FeedCofense/Integrations/FeedCofense/FeedCofense.yml
- Packs/FeedCofense/ReleaseNotes/1_0_1.md
- Packs/FeedCofense/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/24794
Fixed a bug where the 'test' button always returned a positive 
answer.
before:
after:
> FeedCofense: 'test' button always returned a positive answer

- Packs/SNDBOX/TestPlaybooks/playbook-SNDBOX_Test.yml
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/24349
Removes `SNDBOX_Test` from the skip list and adds the `SNDBOX` integration to the unmockable integrations since it sends files for analysis which the mocking mechanism doesn't currently support. Update the test playbook so that it doesn't fail in two situations,
1. generic polling finished and the analysis is still pending - therefore the `download report` task does not execute and the playbook concludes successfully.
2. `SNDBOX` experienced an error in analyzing the file as in the attached screenshot, and therefore we do not execute the `download report` task and conclude the playbook successfully.
> Update SNDBOX_Test Playbook

- .circleci/config.yml
fixes: https://github.com/demisto/etc/issues/23265
Schedules a nightly build to be triggered using the CircleCI `config.yml` itself. Also, disabled the pre-existing crontab job.
> CircleCI Nightly Scheduled Trigger

- Packs/PAN-OS/Integrations/Panorama/CHANGELOG.md
- Packs/PAN-OS/Integrations/Panorama/Panorama.py
- Packs/PAN-OS/ReleaseNotes/1_0_1.md
- Packs/PAN-OS/ReleaseNotes/1_0_2.md
- Packs/PAN-OS/pack_metadata.json
fixes: demisto/etc#24535:
For some reason the server failed to return a proper response with status line, instead it sent a body without it.
That's why when the client tried to parse the first line of the body (the status line) it came across the first line of the following body:
```
<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center></center>
</body>
</html>
```
And that's why the erroring status line was `BadStatusLine('<html>\r\n')`
Thing is when using a post request- the standard is to send the parameters through the body and not through the uri since the uri has a limit of =~ 2 kB which the body does not have.
> POST requests params should be passed through body and not uri

- Packs/ServiceNow/Integrations/ServiceNowv2/CHANGELOG.md
- Packs/ServiceNow/Integrations/ServiceNowv2/Pipfile
- Packs/ServiceNow/Integrations/ServiceNowv2/Pipfile.lock
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
- Packs/ServiceNow/ReleaseNotes/1_1_2.md
- Packs/ServiceNow/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25052
`incident_name` exist in the `params` object, and hence the default value of `.get()` was not taken
also, added `defaultvalue` to the param in the yml file
See test failure at https://circleci.com/gh/demisto/content/54959#tests/containers/1
> ServiceNow v2 - init incident_name param with default value

- Packs/CortexDataLake/Integrations/CortexDataLake/CHANGELOG.md
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
- Packs/CortexDataLake/Integrations/CortexDataLake/README.md
- Packs/CortexDataLake/ReleaseNotes/1_0_1.md
- Packs/CortexDataLake/pack_metadata.json
When there were no records found for a given query in **!cdl-query-logs** command a `StopIteration` was raised and in the user side- there was no reason for the error at all.
So instead of getting table name from the records, table name will be taken from the query.
> Fixed a bug in query-logs command

- Packs/RedCanary/Integrations/RedCanary/CHANGELOG.md
- Packs/RedCanary/Integrations/RedCanary/RedCanary.py
- Packs/RedCanary/ReleaseNotes/1_0_1.md
- Packs/RedCanary/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25265
- in https://github.com/demisto/content/pull/5973, a condition was fixed that led to all timeline of a detection will be fetched, instead of only the first page.
apparently a timeline can be huge, in such way that caused the issue and made the fetch times out. so I've removed the timeline retrieval from the fetch and that can be done in a playbook with a command.
- also encountered a bug in which acknowledged detections were fetched, so fixed the condition there as well.
> Red Canary - bug fixes in fetch incidents

- Packs/FortiSIEM/Integrations/FortiSIEM/CHANGELOG.md
- Packs/FortiSIEM/Integrations/FortiSIEM/FortiSIEM.py
- Packs/FortiSIEM/ReleaseNotes/1_0_0.md
- Packs/FortiSIEM/ReleaseNotes/1_0_1.md
- Packs/FortiSIEM/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25331
Disabled the request to trigger an event in order to get the query data, instead, now query data is a hardcoded dict.
> fortisiem bug fix

- Packs/Base/ReleaseNotes/1_0_7.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
`timestamp_to_datestring`'s default date format includes Z for the time
zone. However, it uses `datetime.fromtimestamp` which is in localtime.
This yields incorrect results when the default time zone is anything
other than UTC.
The `epochToTimestamp` function in the same file does correctly use
`utcfromtimestamp`. This commit corrects and normalizes the timestamp
processing.
> timestamp_to_datestring uses `utcfromtimestamp`

- .circleci/config.yml
- Tests/scripts/prepare_content_packs_for_testing.sh
When $GCS_MARKET_KEY is not set- print `GCS_MARKET_KEY not set aborting!` instead of `not set aborting!`
##Screenshots
> Fixed print when GCS_MARKET_KEY is not set

- Tests/scripts/ami_mock_dependencies_setup.sh
- Tests/scripts/copy_content_data.sh
- Tests/scripts/wait_until_server_ready.py
fixes: https://github.com/demisto/etc/issues/25349
For each server instance, we increase the MaxStartups to `20:30:100` and then restart the `sshd` service. Because the build runs in threads and the mocking mechanism executes commands on a given server instance via ssh, we may be hitting the `sshd` connection limit of the server instance. Can read more about it [here](https://appuals.com/fix-ssh_exchange_identification-connection-closed-by-remote-host/).
> increase sshd MaxStartups and restart sshd

- Packs/RsaNetWitnessPacketsAndLogs/Integrations/integration-RsaNetWitnessPacketsAndLogs_README.md
fixes: https://github.com/demisto/etc/issues/25278
Added a Troubleshooting section to the integration README describing that RSA NetWitness appliances maintain their own `sessionid`'s for sessions which may be different from each other.
> Create Troubleshooting Section for Packets and Logs README

- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/CHANGELOG.md
- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
- Packs/FeedRecordedFuture/ReleaseNotes/1_0_1.md
- Packs/FeedRecordedFuture/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25336
`fetch_indicators_command` did not handle well response with missing fields
See failing test at https://app.circleci.com/pipelines/github/demisto/content/14735/workflows/a5304f86-fcfa-4961-a003-01e4e2dceb2b/jobs/56470/parallel-runs/1?filterBy=FAILED
> Recorded Future Feed - handle sparse response in fetch indicators command

- Packs/ThreatX/TestPlaybooks/playbook-ThreatX-test.yml
fixes: https://github.com/demisto/etc/issues/25599
Change get-entities cmd timeframe from 1 hour to 1 day to increase the change of getting entities results
> ThreatX - update test get entities timeframe

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/25605
Removed EWS O365 from skipped.
> [Test Fail] Removed ews o365 from skipped

- Tests/conf.json
https://github.com/demisto/etc/issues/25654
Skipping lastline v2 integration, to disable the nightly run. This is because we have quota issues with the integration and we want to save all quota for the upcoming PR https://github.com/demisto/content/pull/7580.
> lastline v2 skip nightly

- Tests/conf.json
fixes https://github.com/demisto/etc/issues/25599
the change done in https://github.com/demisto/content/pull/7557 increases the runtime of the test
increased the timeout to allow the test to finish running
> ThreatX - increase test timeout

- Tests/configure_and_test_integration_instances.py
fixes: https://github.com/demisto/etc/issues/25678
The __test_integration_instance method returns a tuple - previously received to a single variable. This resulted in no failure recognition for tests, hence the issue.
I broke Lastline on purpose on a different build and printed the recognized successful and failing tests
here is before the fix - all tests are noted as successful though Lastline failed:
seen here: https://circleci.com/gh/demisto/content/58127
Here is after the fix - Lastline's failure has been noted:
can be seen here: https://circleci.com/gh/demisto/content/58133
> fixing build test failure recognition

- .circleci/config.yml
fixes: https://github.com/demisto/etc/issues/25717
skip validate on nightly build run to save time and prevent current timeout.
this validate runs anyway on every master build.
> skip validate files on nightly run

- Packs/MongoDB/Integrations/MongoDB/MongoDB.py
- Packs/MongoDB/Integrations/MongoDB/MongoDB_test.py
- Packs/MongoDB/ReleaseNotes/1_0_4.md
- Packs/MongoDB/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25735
Nested dicts were not parsed properly when they had a datetime object.
Test introducing the bug:
> Mongodb: nested dicts fix

- Packs/CheckpointFirewall/Integrations/integration-CheckpointFirewall.yml
- Packs/CheckpointFirewall/Integrations/integration-CheckpointFirewall_README.md
- Packs/CheckpointFirewall/ReleaseNotes/1_0_2.md
- Packs/CheckpointFirewall/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25725
ipname argument has been never used and not needed for the command to work. So now it's deprecated to not break BC.
> Fix cfw extra arg

- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_1_2.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
The default scope that was set was for graph, changed it to ATP one
> Microsoft Defender ATP - set scope to default

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
- Packs/MicrosoftTeams/ReleaseNotes/1_0_2.md
- Packs/MicrosoftTeams/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25819
- handle notifications from server that come with notifications channel only in the arguments
- add unclassified to incident severity notifications
- update module health on webserver start - needed for case it crashed and spins up again
- move integration_context init out of the try-except block, as it raised var referenced before var sometimes
- added traceback print to logs
> Microsoft Teams - handle notifications from server

- Packs/Slack/Integrations/Slack/Slack.py
- Packs/Slack/ReleaseNotes/1_2_1.md
- Packs/Slack/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/24819
Fix possible cause for long running container zombie-state for a few customers since 20.4.1 content release.
Requires force merge because of the docker image, will be fixed in the next release.
> Slack skip setting loop in long running container

- Packs/Zscaler/.secrets-ignore
- Packs/Zscaler/Integrations/Zscaler/Zscaler.py
- Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
- Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py
- Packs/Zscaler/ReleaseNotes/1_0_1.md
- Packs/Zscaler/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25684
Added an argument to the `url` command in `Zscaler` called `multiple`. By default, it's value will be `"true"` which will maintain backward compatibility. When the argument is set to `"false"`, the command won't interpret the value passed to the `url` command's `'url'` argument as a comma separated list of URLs. This will allow for the submission of singular URLs that have commas in them.
> Add 'multiple' Command Argument to Zscaler's 'url' command

- Packs/CommonScripts/ReleaseNotes/1_1_9.md
- Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat.py
- Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat.yml
- Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat_test.py
- Packs/CommonScripts/pack_metadata.json
- Packs/CommonTypes/IndicatorTypes/reputation-domain.json
- Packs/CommonTypes/ReleaseNotes/1_2_1.md
- Packs/CommonTypes/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25351
This PR adds a transformer that takes a date string and converts it to ISO-8601 format. That transformer has then been added as an additional transformer to the `CreationDate` and `UpdatedDate` indicator fields for the `Domain` indicator type.
> To ISO Format Transformer

- Packs/Phishing/Playbooks/Get_Original_Email_-_EWS.yml
- Packs/Phishing/Playbooks/Get_Original_Email_-_EWS_CHANGELOG.md
- Packs/Phishing/ReleaseNotes/1_6_0.md
- Packs/Phishing/pack_metadata.json
Ready
fixes: https://github.com/demisto/etc/issues/25746
Fixed the DT that sets details of the original email to the email context. Now Email.HeadersMap will also be outputted and set in the layout properly. By fixing the DT, the headersmap get outputted from `Get Original Email - EWS` to `Get Original Email - Generic` and then to `Process Email - Generic`, where the headers are set in the grid using `SetGridField`:
No
> Enhanced DT in Get Original Email to output HeadersMap

- Packs/CheckpointFirewall/Integrations/integration-CheckpointFirewall.yml
- Packs/CheckpointFirewall/ReleaseNotes/1_0_3.md
- Packs/CheckpointFirewall/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25915
For some reason if there are no arguments configured for a command- all arguments are accepted and used in `demisto.args()`
But if there are arguments configured for a command- all non-configured arguments will be ignored
Therefore, the change that added this `command`argument have broke backwards compatibility, so reverting it back is the solution.
> Reverting restrictive api change

- Packs/CommonScripts/ReleaseNotes/1_1_11.md
- Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/CHANGELOG.md
- Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.py
- Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
- Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/find_similar_incidents_test.py
- Packs/CommonScripts/pack_metadata.json
fixes: https://support.demisto.com/hc/en-us/requests/13701
The method `get_incidents_by_keys` called `.replace` on all values. This failed on boolean and numeric values, therefore I excluded them.
I also added id as second sort key to the output to ensure the oldest incident is first when multiple incidents with the same time exist.
> Fix FindSimilarIncidentsV2

- Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
- Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
- Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2_test.py
- Packs/ArcSightESM/Integrations/ArcSightESMv2/README.md
- Packs/ArcSightESM/ReleaseNotes/1_0_3.md
- Packs/ArcSightESM/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/23963
Added a new parameter to the integration, `use_rest` which when `True` will change the `as-get-entries` and `as-clear-entries` commands to use the updated REST endpoints instead of the older SOAP endpoints.
> ArcSight ESM v2 Updated REST Endpoints

- Packs/Kafka/Integrations/Kafka_V2/Kafka_V2.py
- Packs/Kafka/Integrations/Kafka_V2/Kafka_V2.yml
- Packs/Kafka/Integrations/Kafka_V2/test_data/README.md
- Packs/Kafka/ReleaseNotes/1_0_1.md
- Packs/Kafka/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/25999 https://github.com/demisto/etc/issues/25976
- Apparently `reset_offsets` does not set the first offset to fetch from as expected, so added the keyword arg `auto_offset_reset` according to https://pykafka.readthedocs.io/en/latest/usage.html?highlight=reset_offsets#setting-the-initial-offset
- Wrapped the available offset fetch, which seems to timeout in some cases, in try-except
> Kafka v2 - set auto_offset_reset to intial offset to fetch from

- Tests/conf.json
Went over the timeouts in conf.json and using the latest nightly build reduced the successful ones that was not using mocks.
Details:
* Test Syslog: Execution time: 3:02. Reduced from 1000 to 600
* GoogleKubernetesEngine_Test: Execution time: 4:25. Reduced from 1200 to 600
* CloudShark - Test Playbook: Execution time: 0:40. Reduced from 500 to default of 160
* HelloWorld_Scan-Test: Execution time: 2:00. Reduced from 2000 to 400
* Slack Test Playbook: Execution time: 0:50. Reduced from 2400 to 400
* Detonate File - SNDBOX - Test: Execution time: 6:00. Reduced from 2400 to 600
* intsights_standard_account: Execution time: 0:35. Reduced from 500 to default of 160
* Intezer Testing v2: Execution time: 5:00. Reduced from 700 to 600
* Splunk-Test: Execution time: 1:00. Reduced from 500 to 200
* …
> Reducing long unnessessery timeouts

- Packs/CommonScripts/ReleaseNotes/1_1_14.md
- Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
- Packs/CommonScripts/Scripts/ParseEmailFiles/parse_email_files_test.py
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/26004
- seems like sometimes the `info` field in the file entry metadata is returned empty and its values is returned in the `type` field
- added `message/rfc822` file type to be handled as eml 
See failing test at https://app.circleci.com/pipelines/github/demisto/content/17863/workflows/7cfbe4af-195a-4879-a5c4-006c97a7e109/jobs/60457/parallel-runs/1?filterBy=FAILED
> ParseEmailFiles - add support for message/rfc822 eml type

- Tests/conf.json
related: https://github.com/demisto/etc/issues/24937
Remove Duo Admin from skipped tests
> remove Duo Admin test from skipped tests

- Packs/PAN-OS/Integrations/Panorama/Panorama.py
- Packs/PAN-OS/Integrations/Panorama/Panorama.yml
- Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
- Packs/PAN-OS/ReleaseNotes/1_1_1.md
- Packs/PAN-OS/pack_metadata.json
Adds support for two new commands to the PAN-OS integration
* panorama-block-vulnerability
* Allows threat IDs to be overridden by user-configurable actions  (drop/alert/reset-both etc.)
* panorama-get-predefined-threats-list
* Retrieves the entire signature database from a PANOS device for reference purposes such as looking up CSVs
Credit enir@paloaltonetworks.com for panorama-get-predefined-threats list!
> Panos threat

- Tests/mock_server.py
- Tests/test_content.py
1. Changed the `run_and_record` method in `test_content.py` to only try and clean a mock file if the recording was successful - otherwise, there is no point.
2. Updated the `start` method of `MITMProxy` class to copy over a pre-existing `problematic_keys.json` (if there is one for that test) to the temporary directory in which the mock recording and log files for a given test are written to. The idea here is that `problematic_keys.json` files should only ever get added to, never freshly overwritten. That way, if someone has manually added problematic keys for a test (presumably keys that `timestamp_replacer.py` does not successfully detect itself), those keys will not get overwritten in a case where for example, the test playbook has been updated with additional commands and therefore is …
> Small Tweaks to Mocking Process

- Packs/Phishing/TestPlaybooks/Phishing_v2_-_Test_-_Incident_Starter.yml
Ready
A race condition causes the test to fail intermittently. Last seen on nightly:
Fixed this by sleeping between the task that investigates the incident and the task that sets the playbook. This fix was also applied to other test playbooks related to phishing where the incident type of the incident matters.
6.0.0
No
> Phishing v2 - Test - Incident Starter - race condition fix

- Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Upgrade_CHANGELOG.md
- Packs/PAN-OS/Playbooks/playbook-NetOps_-_Firewall_Version_Content_Upgrade.yml
fixes: https://github.com/demisto/etc/issues/26310
DT Syntax modified in NetOps playbook that is causing failure of status ID captures.
> Fixed DT syntax error

- .circleci/config.yml
- Documentation/docs_site_update.sh
- Tests/configure_and_test_integration_instances.py
- Tests/scripts/destroy_instances.py
- Tests/scripts/run_tests.sh
- Tests/scripts/server_get_artifact.sh
- Tests/scripts/slack_notifier.py
- Tests/scripts/slack_notifier.sh
- Tests/scripts/wait_until_server_ready.py
- Utils/trigger_content_build_with_no_backward_check.sh
- Utils/trigger_content_build_with_time_to_live.sh
- Utils/trigger_content_nightly_build.sh
- Utils/trigger_content_nightly_build_with_memory.sh
- Utils/trigger_content_nightly_instance_tests.sh
- Utils/trigger_content_non_ami_build.sh
- Utils/trigger_content_non_ami_build_by_number.sh
- Utils/trigger_nightly_sdk_build.sh
https://github.com/demisto/etc/issues/23899
In this PR the build is migrated from single job to multiple jobs using workflows.
This PR will not be merged until @ronykoz will implement a locking mechanism.
Main changes:
- Removing the current parallelism method with container numbers 0 and 1, parallelism is implemented using workflows.
- **wait until server ready** step is done separately for each server version.
- *Slack notifier* is done once in **unit tests** job and once in **server Master** instance test job
- Destroy instances will destroy the relevant instance only, if no error occurred
- Moved the contribution branch check to circle built in branch handling, jobs that should not be executed, will not be displayed.
This implementation has the following advantages:
1. It is faster …
> Migrating circleci build to using workflow

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
- Packs/SplunkPy/ReleaseNotes/1_0_1.md
- Packs/SplunkPy/pack_metadata.json
For Splunk HEC submissions using the submit-event-hec command, fields param used to take in a comma separated string. So when you used the command, in splunk a field by the name "fields" will be created and its value will be the comma separated string. This is not the recommended usage of fields according to Splunk. Fields should actually be a JSON key value pair where you can create new fields (with the name provided in the param and not hardcoded 'fields') and values in Splunk. This PR addresses that issue.
- [ X] No
> SplunkPy - correct the usage of fields for hec submit event command

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/ReleaseNotes/1_0_1.md
- Packs/SplunkPy/pack_metadata.json
It's a standard across integrations to use the common server method 'handle_proxy'. The SplunkPy integration has 3 requests.post call and it was relying on the older method of checking `if not proxy: then do this or that`. This PR sets a variable `PROXIES=handle_proxy()` in the beginning of the file and everywhere there is a requests call adds `proxies=PROXIES` to it.
- [X ] No
> Use handle_proxy() in all requests in SplunkPy integration.

- .circleci/config.yml
- Tests/scripts/download_demisto_conf.sh
When  a branch exists in `content-test-conf` repo with same name is the current `content` branch name, The step **Download configurations** fails in order to remind the developer to push the `content-test-conf` branch to master.
Since this step is part of `Create Instances` job- it prevent the Instances jobs from being created.
This PR is about moving the failure to `Run Validations` job and letting `Create Instances` job succeed.
> Not failing instance creation when a test-conf branch exists

- .circleci/config.yml
Handle collision between nightly context and pipeline parameter
> don't overwrite time_to_live env variable from context

- Tests/conf.json
SNDBOX often fails on timeout. see [here](https://app.circleci.com/pipelines/github/demisto/content/19032/workflows/b3b9a93a-0e84-41c0-8458-e1880d4bc333/jobs/62671/steps), increasing the timeout back to 1000.
> increase SNDBOX test playbook timeout

- Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
- Packs/Tenable_io/ReleaseNotes/1_0_1.md
- Packs/Tenable_io/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/26481
Fixed an issue in `tenable-io-launch-scan` command where `scanTargets` argument was ignored.
> [Fix] tenable-io-launch-scan ignores scanTargets argument

- Packs/ApiModules/ReleaseNotes/1_0_4.md
- Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.py
- Packs/ApiModules/Scripts/MicrosoftApiModule/MicrosoftApiModule.yml
- Packs/ApiModules/pack_metadata.json
The docstring claimed that the return type is a Response object which is not,
> Updated docstring in ApiModule

- Packs/QRadar/Integrations/QRadar/QRadar.py
- Packs/QRadar/ReleaseNotes/1_0_4.md
- Packs/QRadar/ReleaseNotes/1_0_5.md
- Packs/QRadar/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/26007
Some responses res.json attributes can be none ascii. in this case python2 keeps it in bytes form and then when trying to use it as string it fails.
This seems to be a known issue in this integration since there is already a method that solves this recursivly- `unicode_to_str_recur`
> converting unicode response to string

- .circleci/config.yml
- Tests/scripts/prepare_content_packs_for_testing.sh
Running the following command,
`./Utils/trigger_content_build_with_time_to_live.sh content_branch_name <CircleCiToken> 420 contrib_name:contrib_branch_name Packs/New_Pack/`
is supposed to trigger a build that will take the contribution and will run a regular content build using the contributor's code/additions. Currently, the build does not actually use the contributor's code/additions for testing on server instances. This PR implements proper handling in our build for this usecase. See this [build](https://app.circleci.com/pipelines/github/demisto/content/19257/workflows/f7a00841-2b11-4a62-a002-7a1410eb84fb) (which was triggered by `./Utils/trigger_content_build_with_time_to_live.sh code42_contrib <circle-token-redacted> 420 code42:download-file Packs/Code42/`) for an example where the …
> Build Fixes & Tweaks

- Tests/Marketplace/Tests/upload_packs_test.py
- Tests/Marketplace/marketplace_services.py
- Tests/Marketplace/upload_packs.py
related to: https://github.com/demisto/etc/issues/26536
Update index in case it is missing pack folder for any reason. Partial solution for original issue. 
The race condition between builds will be solved by adding commit hash and in separate PR.
> Update index in case pack is missing as subfolder 

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/26452
Removed the use of `activedir` in the Circle tests since it's deprecated.
> Removed deprecated integration test (Active Directory)

- Tests/scripts/collect_tests_and_content_packs.py
- Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
- Tests/scripts/infrastructure_tests/tests_data/mock_id_set.json
- dev-requirements-py3.txt
fixes: https://github.com/demisto/etc/issues/26438
Currently server versions 4.1.0 to 5.0.0 are installed only if there is a relevant test that can run in them.
This PR changes them to be installed even if there is no test that can run in them as long as the modified files in the branche's commits can run in this version.
If no info could be extracted about the files- will run all versions.
In addition:
* Refactored the usage of id_set.json, conf.json and amu_builds.json so that they will be opened and read only once, and be saved as consts.
* Replaced prints with logging
> install relevant server vesrions

- Packs/AccessInvestigation/Playbooks/Access_Investigation_-_Generic.yml
- Packs/AccessInvestigation/ReleaseNotes/1_2_0.md
- Packs/AccessInvestigation/pack_metadata.json
Ready
Related to: https://github.com/demisto/etc/issues/26510
`Access Investigation - Generic` will skip `Active Directory - Get User Manager Details` if the AD pack is not installed
No
> Skipping AD get user manager details in AccessInvestigation if pack is unavailable

- .circleci/config.yml
1. Partner deleted playbook in his branch
2. When `trigger_content_build_with_time_to_live` was triggered, it checked out the changes from partner branch , but it didn't deleted the deleted file. The reason for that is because `git checkout somefile` only copies from files. 
So I delete the pack first and then run the checkout
> delete the pack folder before checking out

- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/26104
Checked the memory issue within alien vault feed, it is due to the feed itself, when running the get-indicators command the docker ram consumption raises up to 350 MB. This feed is using the CSV API Module, same as Bambenek feed. Checked Bambenek too, and its not changing its memory consumption much.
> AlienVault memory threshold increase

- Packs/PhishTank/Integrations/README.md
```
Validating Packs/PhishTank unique pack files
Validating Packs/PhishTank/Integrations/README.md as readme
Validating scheme for Packs/PhishTank/Integrations/README.md
Packs/PhishTank/Integrations/README.md: [RM100] - Failed verifying README.md Error Message is: SyntaxError: unknown: Unterminated JSX contents (184:16)
182 | <br>Total 15939 URLs loaded.<br>
183 | <br>Last load time Sun Jul 26 2020 18:56:10 GMT+0300 (IDT)<br>
> 184 |     </MDXLayout>
|                 ^
185 |   )
186 | };
187 | MDXContent.isMDXComponent = true
at Object._raise (/home/circleci/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:757:17)
```
fixes: master
> phishtank readme - did not close the br

- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks.py
- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks.yml
- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks_test.py
- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/README.md
Patch to fix GenericPolling behavior when raw-response is not JSON deserializable
Bug fix
> Fix raw response

- .github/workflows/check-contributor-pack.yml
Skipped notifier in case branch name begins with `contrib/` or `to-merge/`.
> Skipped contributor notifier on contrib branches

- Packs/Code42/Integrations/Code42/Code42.yml
- Packs/Code42/Integrations/Code42/Code42_test.py
- Packs/Code42/ReleaseNotes/2_0_1.md
- Packs/Code42/pack_metadata.json
This addresses a minor bug in this dependency that causes the incorrect type of python error to be raised/thrown under some circumstances when `code42-download-file` cannot find the supplied hash.
- [] 5.5.0
> [code42-636] Bump py42 dependency docker container

- Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py
- Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.yml
- Packs/Anomali_ThreatStream/ReleaseNotes/1_0_1.md
- Packs/Anomali_ThreatStream/pack_metadata.json
fix confirmed to work in: https://github.com/demisto/etc/issues/27002
Fixed an issue in **threatstream-import-indicator-with-approval** where the command would not import indicators properly.
> [Fix] threatstream-import-indicator-with-approval not working

- Packs/Phishing/Playbooks/Process_Email_-_Core.yml
- Packs/Phishing/Playbooks/Process_Email_-_Generic.yml
- Packs/Phishing/ReleaseNotes/1_8_0.md
- Packs/Phishing/pack_metadata.json
Ready
fixes: https://github.com/demisto/etc/issues/27113
Will now continue on error in the tasks that use `SetGridField` due to customer complaints. Need to understand the cause of the bug too https://panw-global.slack.com/archives/C011E5T5K17/p1596227521158100
No
> Process Email Generic+Core - continueonerror for SetGridField

- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
- Packs/GenericSQL/ReleaseNotes/1_0_5.md
- Packs/GenericSQL/pack_metadata.json
This change marks *query* command as depracated and adds *pgsql-query*
so it's seamless to switch over to GenericSQL integration,
and encourages switching to *sql-command*.
Signed-off-by: Omer Cohen <git@omer.io>
fixes: https://github.com/demisto/etc/issues/27036
> Encourage migrating to GenericSQL

- .circleci/config.yml
- Tests/mock_server.py
- Tests/test_content.py
Adds a `run_tests.log` file to the artifacts for each server instance `Run Tests` circleci job, to which `mock_server.py` logs extra debugging statements. The outputs of `stdout` and `stderr` of the `mitmproxy` process are logged there as well.
> Mocks Logging

- Packs/Base/ReleaseNotes/1_1_9.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/27239
Fix CommandResults when provided only outputs_prefix with DT
This is how it looks in CrowdStrikeMalquery
> fix commandresults when provided only outputs_prefix

- Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
fixes: https://github.com/demisto/etc/issues/27164
Test failed for alert ID 1, changed to 80
> LogRhythm-Test - set tested alert to be ID 80

- Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
- Packs/VirusTotal-Private_API/ReleaseNotes/1_0_2.md
- Packs/VirusTotal-Private_API/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/27383
Made the resource url that was returned from viruses total a simple text instead of clickable link because it can be malicious
before:
after: 
> Private VirusTotal return clickable links

- Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml
fixes: https://github.com/demisto/etc/issues/27164
- tested alarm id (80) was not found in the db, so changed to id 1150
- added playbook input for the alarm id so all tasks will take the id from there
> LogRhythm Test - change tested alarm ID

- Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
- Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
- Packs/ThreatConnect/ReleaseNotes/2_0_4.md
- Packs/ThreatConnect/TestPlaybooks/ThreatConnect_v2_-_Test.yml
- Packs/ThreatConnect/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/22513
added the command ***tc-download-report***.
> adding report download command to ThreatConnect v2

- Packs/Gmail/Integrations/Gmail/Gmail.py
- Packs/Gmail/Integrations/Gmail/Gmail.yml
- Packs/Gmail/ReleaseNotes/1_0_4.md
- Packs/Gmail/pack_metadata.json
fixes: https://github.com/demisto/content/pull/8167
Fixes a bug where in Gmail integration where send-mail command would send both body and htmlBody
Before:
After:
- It's possible that there are some customers that may expect the incorrect behavior when sending emails with both `body` and `htmlBody` arguments...
> Gmail bugfix send mail

- .github/workflows/sync-contribution-base-branch.yml
- Utils/contribution_sync/Pipfile
- Utils/contribution_sync/Pipfile.lock
- Utils/contribution_sync/sync_contrib_base.py
works toward: https://github.com/demisto/etc/issues/26526
Adds a scheduled github actions (every 12 hours) workflow that syncs base branches of contribution PRs (`contrib/*`) with `master` branch.
> sync base branch with master

- Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md
fixes: https://github.com/demisto/etc/issues/27458
When a file is uploaded using the CrowdStrike FalconX integration, its identifier is changing.
It happens again when the uploaded file is submitted.
In order to emphasising this change an extra explanation was added to the readme.
> Crowdstrike Falcon X  - emphasising the file identifiers change in the readme

- .gitignore
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.py
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
- Packs/CofenseTriage/ReleaseNotes/1_1_3.md
- Packs/CofenseTriage/pack_metadata.json
Cofense was throwing an error when getting the attachment if the attachment was ID was reference in context.  This is because this value needs to be passed as a string to the API call. 
> CofenseTriage Force attachment type to be string; Add .swp files to .gitignore

- .circleci/config.yml
- Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Attack_Pattern.json
- Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Malware.json
- Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Report.json
- Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Threat_Actor.json
- Packs/CommonTypes/Layouts/layout-indicatorsDetails-STIX_Tool.json
- Packs/CommonTypes/ReleaseNotes/1_8_6.md
- Packs/CommonTypes/pack_metadata.json
- Reformatted STIX indicator layouts and added missing `typeId` and `version` fields
- Set the right indicator type ID
- bump to content release 20.8.2
> Reformat STIX indicator layouts

- Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS.py
- Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS.yml
- Packs/CyberArkPAS/Integrations/CyberArkPAS/CyberArkPAS_test.py
- Packs/CyberArkPAS/Integrations/CyberArkPAS/README.md
- Packs/CyberArkPAS/Integrations/CyberArkPAS/test_data/context.py
- Packs/CyberArkPAS/Integrations/CyberArkPAS/test_data/http_resonses.py
- Packs/CyberArkPAS/ReleaseNotes/1_0_2.md
- Packs/CyberArkPAS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/27830
Part of the deprecation of the CyberArk AIM integration, moving the account-get-details command that uses the PAS API from the AIM integration to the PAS.
> CyberArk PAS - adding cyberark-pas-account-get-details command

- Packs/Gmail/Integrations/Gmail/Gmail.py
- Packs/Gmail/Integrations/Gmail/Gmail.yml
- Packs/Gmail/ReleaseNotes/1_0_5.md
- Packs/Gmail/pack_metadata.json
- Packs/MailListener/TestPlaybooks/playbook-MailListener_Test.yml
fixes: https://github.com/demisto/etc/issues/27361
fixes: https://github.com/demisto/etc/issues/27057
fixes: https://github.com/demisto/etc/issues/27362
fixes: https://github.com/demisto/etc/issues/27811
fixes: https://github.com/demisto/etc/issues/27845
removed event argument from `gmail-list-users` command, the argument was removed on in the Gmail API.
> removed event argument from gmail-list-users command

- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py
- Packs/CofenseTriage/Integrations/CofenseTriagev2/conftest.py
FYI - @glicht 
Failing unit-tests - https://app.circleci.com/pipelines/github/demisto/content/23725/workflows/9102461c-399d-4e0b-bc08-773e51c45d16/jobs/94408/artifacts
Fixing unit-test invocation errors:
- `__init__.py` - should not be in Integration.
- Wrong imports - The reason for the unit-tests failures. 
- unit-tests - Accessing the wrong value.
In addition, I will open PR for catching invocation errors.
> fix unit-tests

- Packs/CommonScripts/Scripts/DateStringToISOFormat/DateStringToISOFormat_test.py
I was using `capfd.disable()` to suppress `stderr` that I was outputting expectedly in certain cases since `stderr` would fail the unit test. This was bad practice since this could swallow/mask other (non-expected) errors. I replaced the use of `capfd.disable()` with simply patching `demisto.error()`.
> Fix DateStringToISOFormat Unit Test

- Packs/QueryAI/Integrations/QueryAI/QueryAI.py
- Packs/QueryAI/Integrations/QueryAI/QueryAI.yml
- Packs/QueryAI/ReleaseNotes/1_0_1.md
- Packs/QueryAI/pack_metadata.json
Updated request timeout for Query.AI integration
> query-ai-3526: Updated QueryAI timeout

- Utils/checkout_contribution.sh
check if branch exists already and switches to it.
fixes: https://github.com/demisto/etc/issues/27227
added checks if remote branch exists 
> Checkout contrib remote branch exists fix

- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
- Packs/CortexDataLake/ReleaseNotes/1_2_2.md
- Packs/CortexDataLake/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/24346
Failed with the following error 
```
Error: [Traceback (most recent call last):
File "<string>", line 897, in <module>
File "<string>", line 856, in main
File "<string>", line 47, in __init__
File "<string>", line 64, in _get_access_token
File "<string>", line 90, in _oproxy_authorize
ValueError: invalid literal for int() with base 10: ''
```
When executing this line `expires_in = int(oproxy_response.get(EXPIRES_IN, MINUTES_60))`
It seems like a case where the `EXPIRES_IN` key was in the dict but with empty string as value.
The solution is to add a fallback to 0 in case the value was empty string
> fixing error in parsing oproxy response

- Packs/MicrosoftCloudAppSecurity/.pack-ignore
- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
- Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_2.md
- Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Updated `demisto-sdk` to check if there is a `defaultValue` in the `max_fetch` param.
The defaultValue was set to 50 as it was defined in the integration in `DEFAULT_INCIDENT_TO_FETCH`.
> MicrosoftCloudAppSecurity adding defaultValue to max_fetch

- Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
- Packs/FeedElasticsearch/ReleaseNotes/1_0_6.md
- Packs/FeedElasticsearch/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/28320
- Change the default ***Feed Type*** from ***Cortex XSOAR Feed*** to ***Cortex XSOAR MT Shared Feed***.
- Docker image updated.
> change elastic default Feed Type

- .github/config.yml
Removes the `Welcome` bot's message that is used to comment on new PRs. (We should also remove the `Welcome` bot from the repo)
~~- Tests~~ N/A
~~- Documentation~~ N/A
> Remove Welcome Bot Message

- Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md
In cases where Windows Defender ATP was already configured, can't use the same set of auth. flow creds for this one.
> Explained need to re-run auth. flow

- Tests/configure_and_test_integration_instances.py
fixes: https://github.com/demisto/etc/issues/28468
changes the comparison against commit.
in standard branches against `origin/master`.
and `origin/master~1` in the master branch.
> Fixing the logic for find none added packs

- Utils/contribution_sync/sync_contrib_base.py
Can see this [internal PR](https://github.com/demisto/content/pull/8972) whose head branch was synced with `master` (therefore rendering the PR useless) because a [PR](https://github.com/demisto/content/pull/8974) to the branch `contrib/code42_master` was open at the time the scheduled sync automation executed. I've changed the sync automation to check if there is an open internal PR with the branch in question before adding it to the list of branches that should get synced with master.
~~- Tests~~ N/A
~~- Documentation~~ N/A
> Only Sync Contrib Base Branch If It Isn't The Head Branch Of An Open Internal PR

- Packs/CommonScripts/ReleaseNotes/1_2_44.md
- Packs/CommonScripts/Scripts/FindSimilarIncidentsV2/FindSimilarIncidentsV2.yml
- Packs/CommonScripts/Scripts/GetDuplicatesMlv2/GetDuplicatesMlv2.yml
- Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
- Packs/CommonScripts/Scripts/script-DBotClosedIncidentsPercentage.yml
- Packs/CommonScripts/Scripts/script-DeleteConext.yml
- Packs/CommonScripts/Scripts/script-IndicatorMaliciousRatioCalculation.yml
- Packs/CommonScripts/Scripts/script-MarkRelatedIncidents.yml
- Packs/CommonScripts/Scripts/script-findIncidentsWithIndicator.yml
- Packs/CommonScripts/pack_metadata.json
- Tests/conf.json
fixes: https://github.com/demisto/etc/issues/28562
fixes: https://github.com/demisto/etc/issues/27980
phase one PR: https://github.com/demisto/content/pull/9009
scripts executing `setIncident`:
scripts executing `setIncident`:
> Updated role of several scripts - phase two

- Packs/Base/ReleaseNotes/1_3_3.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
This adds `sha512Regex` and adds necessary check in `auto_detect_indicator_type()` to support `sha512`. Also added test case for a `sha512` hash for the `auto_detect_indicator_type()` function. 
All checks passing.
> adding support for sha512 and sha512Regex

- Tests/demistomock/demistomock.py
Added docstring detailing the fields that are expected to be in incidents when calling `demisto.createIncidents`, with emphasis on `type` - as it's not required by the server, but should be provided.
> [Documentation] Expanded demistomock docstring to emphasise incidents keys

- Packs/Bonusly/Integrations/Bonusly/README.md
In the Bonus.ly integration README, a link to https://bonus.ly/api/v1/ is autogenerated through markdown and doesn't work as it's just a prefix. Adding escapes to avoid having it recognized as autolink.
This is to fix a broken link in content-docs reference section.
> Fix Bonusly Integration README link

- Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
- Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
- Packs/QRadar/ReleaseNotes/1_0_11.md
- Packs/QRadar/pack_metadata.json
- Tests/conf.json
Fixed an issue where fetched incidents IP values weren't enriched correctly.
> [Fix] QRadar v2 enrichment fails to enrich IP values

- Utils/contribution_sync/sync_contrib_base.py
No branches were being returned by the `get_branch_names_with_contrib` function after the previous "fix".
- ~~[ ] Tests~~ N/A
- ~~[ ] Documentation~~ N/A
> fix bad fix of sync contrib-base branch :-P

- .circleci/config.yml
turning off xsoar linter for 4.5 feature branch
preventing existing linter issues: https://app.circleci.com/pipelines/github/demisto/content/28656/workflows/9eaa4cfc-055f-4b49-afba-b0ec1042a298/jobs/126600
> no xsoar linter in v4.5.0

- Packs/GoogleChronicleBackstory/TestPlaybooks/playbook-GoogleChronicleBackstoryListIOCs-Test.yml
fixes: https://github.com/demisto/etc/issues/26461
`gcb-list-iocs` is not deterministic on our instance, in some cases it can be empty. so in order to make the playbook more stable I added a check that there is no error, and then a check if the result was empty. if it was, the playbook will not fail. if there are results, it will verify context. this is not optimal, but it is better than a flaky test.
> do not fail when no iocs in Google Chronicle Backstory List IOCs test

- Tests/conf.json
https://github.com/demisto/etc/issues/28826
https://github.com/demisto/etc/issues/24349
SNDBOX instance is returning status code: 503 and reason: Service Unavailable: Back-end server is at capacity.
so it will be skipped until the issue will be solved.
note the that this pr also remove the skip from "SNDBOX Test" because it should have been removed from skip in: https://github.com/demisto/etc/issues/24349.
> Skip sndbox integration

- Packs/Slack/Integrations/Slack/README.md
Fixed 2 typos in the Slack v2 integration README
> Slack - fix typos in the README

- Tests/conf.json
In case you are a technological partner:
If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.
fixes: https://github.com/demisto/etc/issues/26463
VT private encounter issues with the mocker on nightly on `URL Enrichment - Generic v2 - Test`.
So it will be moved to unmockable integrations for now.
a relevant dev-bug was opened about the mocker issue: https://github.com/demisto/etc/issues/28888
> move vt private to unmockable

- Tests/mock_server.py
Currently we're calling proxy.stop without sending the prints manager.
This is a bug which is now fixed.
> Fixing call to proxy.stop without thread_index and prints_manager

- Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_(v11.3)_-_Test.yml
changed the status names arguments so the init test playbook will handle them.
fixes: https://github.com/demisto/etc/issues/29028
fixes: https://github.com/demisto/etc/issues/29027
> change the name status in McAfee ESM v2 test playbook for v 11.3

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
- Packs/SplunkPy/ReleaseNotes/1_2_3.md
- Packs/SplunkPy/pack_metadata.json
1. `handle_proxy()` was not used on SplunkPy until today, which has now changed.
2. Improved the `submit-event-hec` command to meet Splunk's recommendations.
> Adding usage of handle_proxy + enhancing the submit-event-hec command

- Packs/MicrosoftGraphUser/TestPlaybooks/Microsoft_Graph_User_test.yml
- Tests/conf.json
The previous name of this test is different in later versions.
This change aligns the test name to version 5.0.0 test and beyond.
> [4.5.0] Changed Microsoft Graph User test name to reflect changes in 5.0.0+

- Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
- Packs/CaseManagement-Generic/Layouts/layout-close-Case_layout-Case.json
- Packs/CaseManagement-Generic/Layouts/layout-detailsV2-Case_layout-Case.json
- Packs/CaseManagement-Generic/Layouts/layout-edit-Case_layout-Case.json
- Packs/CaseManagement-Generic/Layouts/layout-mobile-Case_layout-Case.json
- Packs/CaseManagement-Generic/Layouts/layout-quickView-Case_layout-Case.json
- Packs/CaseManagement-Generic/Layouts/layoutscontainer-Case_layout.json
- Packs/CaseManagement-Generic/ReleaseNotes/1_1_0.md
- Packs/CaseManagement-Generic/Reports/report-CaseReport.json
- Packs/CaseManagement-Generic/Scripts/AssignToMeButton/AssignToMeButton.yml
- Packs/CaseManagement-Generic/Scripts/GenerateSummaryReportButton/GenerateSummaryReportButton.yml
- Packs/CaseManagement-Generic/Scripts/LinkIncidentsButton/LinkIncidentsButton.yml
- Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
- Packs/CaseManagement-Generic/Widgets/widget-Mean_Time_To_Remediation_SLA.json
- Packs/CaseManagement-Generic/Widgets/widget-My_Incidents_by_Type.json
- Packs/CaseManagement-Generic/Widgets/widget-My_Mean_Time_To_Remediation_SLA.json
- Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents.json
- Packs/CaseManagement-Generic/Widgets/widget-Participating_Incidents_Count.json
- Packs/CaseManagement-Generic/Widgets/widget-Time_To_Assignment.json
- Packs/CaseManagement-Generic/pack_metadata.json
N/A
This fixes the incident action buttons on the layout for the case type, which had the script guid instead of the name.  Buttons didn't appear as a result on they layout when you created a new Incident.
In addition we have added the Case Report to the Pack, as there was an issue uploading it the first time. 
Added 'Active Incidents by Source' panel to the Incidents Overview Dashboard, showing where Incidents were coming from.
Lastly adding in the widgets for the Time to Assignment, Remediation SLA Timers, and Participating Incidents (My Incidents Dashboard) which can be optionally added to dashboards from this pack. 
Tested with 6.0 (81077), 6.0.1 (84583), and 5.5 (78518) instances.
Case Mgmt - Button issue
Case Mgmt - Fixed button on layout (what it should look like)
Incidents …
> Case Management Pack - Fixes for Incident Action Buttons on Layout, Case Report, Widgets

- .circleci/config.yml
https://github.com/demisto/etc/issues/28121
On November 1st, Docker Hub will begin limiting anonymous image pulls.
Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
This solution is documented [here](https://circleci.com/docs/2.0/private-images/?mkt_tok=eyJpIjoiTURRd01XRTFabUV5T1dSaSIsInQiOiJ4MXhVdVRHckZSTkN5RFk3M2xhMk1WTkpOSU05eXZpTDRzZmxcL08wZXk4MTl1SkRLZmc1UUtnZytzZkg5K1VtemRJeWZcL1h4VFwvakFBdnZmWUtSU2ZOa3lubk80XC9FQ2J5d1RJYlEraHp0ZzhSSGx2aUMwNDdpTU56dU9GMW1qbXYifQ%3D%3D)
> Add docker authentication to avoid docker rate limits

- Tests/mock_server.py
- Tests/test_content.py
To get better understanding about the proxy's effectiveness - every job will append the following metrics to a GCP object:
- Date
- Count of successful tests
- Count of failed tests
- Count of successful rerecords
- Count of failed rerecords
- IDs of the playbooks that were rerecorded successfully
- Ids of the playbooks that have failed rerecording
With this data we will be able to get the following data:
- Current failure rate of the proxy.
- Failure rate of the proxy on a time line.
- Common playbooks that are failing  
- Current rerecord failure rate of the proxy.
- Rerecord failure rate of the proxy on a time line.
- Common playbooks that are failing rerecord
> send proxy metrics to GCP object

- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.py
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_description.md
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py
- Packs/CofenseTriage/Integrations/CofenseTriagev2/README.md
- Packs/CofenseTriage/Integrations/CofenseTriagev2/command_examples.txt
- Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/inbox_reports.json
- Packs/CofenseTriage/Integrations/CofenseTriagev2/test/fixtures/reporters_by_email_reporter2.json
- Packs/CofenseTriage/ReleaseNotes/1_1_6.md
- Packs/CofenseTriage/TestPlaybooks/playbook-Cofense_Triage_v2-Test.yml
- Packs/CofenseTriage/pack_metadata.json
In case you are a technological partner:
If you are not a technological partner (i.e. PANW employee, customer or individual developer), please delete this section.
The `cofense-search-inbox-reports` command allows searching for reports in the inbox.
The `mailbox_location` parameter controls the source of reports for the periodic fetch functionality.
The new command and the legacy `cofense-search-reports` command both support querying by reporter address in addition to reporter ID.
> [Cofense] Add support for `inbox_reports` endpoint

- Tests/conf.json
It seems like the default timeout of 160 seconds is not enough for `Create ServiceNow Ticket and State Polling Test`.
See here for example:
https://app.circleci.com/pipelines/github/demisto/content/32112/workflows/8c4d05b5-277a-4b13-82e6-e830450971a2/jobs/140267
Increased it to 500 seconds
> Increased test timeout for service now polling playbook

- Packs/CommonWidgets/ReleaseNotes/1_0_4.md
- Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.py
- Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
- Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents_test.py
- Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.py
- Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations.yml
- Packs/CommonWidgets/Scripts/GetLargestInvestigations/GetLargestInvestigations_test.py
- Packs/CommonWidgets/Widgets/widget-LargestInputsAndOuputsInIncidentsWidget.json
- Packs/CommonWidgets/Widgets/widget-LargestInvestigationsWidget.json
- Packs/CommonWidgets/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29128
fixes: https://github.com/demisto/etc/issues/29235
* Fixed an issue where the widgets/scripts did not work for "All times".
* Changed header Size->Size(MB)
* Changed header Size value to float
* Changed investigation IDs to Hyperlink
* Changed task IDs to Heyperlink
* GetLargestInvestigations now returns by default Text, but can also return table
* GetLargestInputsAndOuputsInIncidents now returns Text result
* Added handling for **playground** investigation
- Further details: changes from table to text result (to support links) may adversely affect widgets/scripts that used it before
@kirbles19 please review:
* Packs/CommonWidgets/Scripts/GetLargestInputsAndOuputsInIncidents/GetLargestInputsAndOuputsInIncidents.yml
* …
> [Enhancement] Large incidents widgets - usability changes

- Packs/CommonScripts/ReleaseNotes/1_2_56.md
- Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29011
changed defaultValue argument from mandatory to optional
re-opening due to PR corruption 
https://github.com/demisto/content/pull/9392
> defaultValue is changed to default = false

- Packs/Alexa/Integrations/Alexa/Alexa.py
- Packs/Alexa/Integrations/Alexa/Alexa.yml
- Packs/Alexa/ReleaseNotes/1_1_0.md
- Packs/Alexa/pack_metadata.json
Update to the `Alexa` Pack Integration to add the `benign` parameter. The current `threshold` parameter only accounts for `unknown` or `suspicious` domains, however the top X domains (i.e. top 1000) could easily be considered `good` which is helpful context for an analyst. 
> **NOTE:** It was clear this integration is a bit older and does not use the new coding conventions. There's several things that could be cleaned up to align with best practices. While I think it'd be easy to go ahead and update that now, I thought it best to keep the solution simple and avoid breaking any backward compatibility. 
> Add Alexa Benign Parameter for Good Domains

- Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-VxStream_Test.yml
fixes: https://github.com/demisto/etc/issues/29280
seems like the total VMs property is no longer returned from the API, removed validation of it
> VxStream Test - remove check for totals VMs

- Tests/scripts/infrastructure_tests/release_notes_generator_test.py
- Utils/release_notes_generator.py
Added a space between content entities that are separated by capital letters, such as IncidentFields
> release notes generator - add white spaces between entities of 2 words

- Packs/Expanse/Integrations/Expanse/Expanse.py
- Packs/Expanse/Integrations/Expanse/Expanse.yml
- Packs/Expanse/Integrations/Expanse/Expanse_test.py
- Packs/Expanse/ReleaseNotes/1_1_3.md
- Packs/Expanse/pack_metadata.json
Blocking https://github.com/demisto/content/pull/9305 due to test playbook failure.
A change in Expanses API is causing this command to fail in some circumstances. This change should make the integration more resilient to conditions where `recentIps` is null.
> [expanse-272] Domain command fix

- Packs/ServiceNow/IncidentTypes/incidenttype-ServiceNowTicket.json
- Packs/ServiceNow/Layouts/layoutscontainer-ServiceNow_Ticket.json
fixes: https://github.com/demisto/etc/issues/29410
Reverting ServiceNow Ticket layout to the original ID. 
> ServiceNow Ticket Layout ID Revert

- Packs/UrlScan/Integrations/UrlScan/UrlScan.py
- Packs/UrlScan/ReleaseNotes/1_0_5.md
- Packs/UrlScan/pack_metadata.json
fixes: N/A
Wanted to have IPv6 support on Urlscan search. Also chaned query type logic (no further checks are made if valid IP address is found).
Didn't test with Demisto versions other than 6.0.0
Please label PR with _hacktoberfest-accepted_ if you accept this PR.
- [x ] No
> IPv6 support added in search

- Packs/FeedAWS/Classifiers/classifier-FeedAWS.json
- Packs/FeedAWS/Classifiers/classifier-mapper-incoming-FeedAWS.json
- Packs/FeedAWS/Integrations/FeedAWS/FeedAWS.yml
- Packs/FeedAWS/ReleaseNotes/1_0_6.md
- Packs/FeedAWS/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29814
Fixed an issue where the classifier and the mapper have the same id. Updated these ids.
> changed classifier's id and mapper's id

- .circleci/config.yml
- Tests/test_content.py
- Tests/test_dependencies.py
- Tests/test_integration.py
- Utils/tests/update_playbook_test.py
- dev-requirements-py3.txt
fixes: https://github.com/demisto/etc/issues/29435
Refactored names to not be collected by Pytest, added import to globally work (slack import).
Running pytest on both Utils and Tests folder.
> Fixed pytest run on Tests and Utils

- Packs/Zscaler/Integrations/Zscaler/README.md
Removed HTML elements from the readme, because they made the Readme render incorrectly.
> [Documentation] Zscaler - remove html elements from docs

- Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.py
- Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.yml
- Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2_test.py
- Packs/DNSDB/Integrations/DNSDB_v2/README.md
- Packs/DNSDB/Integrations/DNSDB_v2/command_examples
- Packs/DNSDB/README.md
- Packs/DNSDB/ReleaseNotes/2_1_0.md
- Packs/DNSDB/TestPlaybooks/playbook-DNSDB-Test.yml
- Packs/DNSDB/pack_metadata.json
* farsight-security-57 Add support for DNSDB API version 2
* README tweaks per @ShahafBenYakir
* Add rdata raw
* Change version to 2.1.0, add raw to release notes
* unbind the dnsdb-flex command in test playbook
* Update readme to mention version 2 of the api
* remove unneccessary check for http status 404
* Add RawRData to flex context
* Add test cases for flex
* quiet some pep8 errors
* Fix indentation
* Update urls to png files in README
* Increase timeout
Paste here any …
> farsight-security-57 Add support for DNSDB API version 2 (#9603)

- Packs/Base/ReleaseNotes/1_3_23.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
Fixed an issue where return_results incorrect output for list of commands
> [Fix] return_results incorrect output for list of commands

- Tests/conf.json
Removing duplicated configuration of test playbook ExtractDomainFromEmailTest as it's in the configuration twice
> Removing duplicated test configuration

- Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
- Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
- Packs/MicrosoftGraphMail/ReleaseNotes/1_0_10.md
- Packs/MicrosoftGraphMail/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29913
According to the API there are three types of attachments and the integration only handled two of them.
> MS graph mail - skipped referenceAttachment

- Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
- Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
- Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
- Packs/PrismaCloudCompute/ReleaseNotes/1_0_4.md
- Packs/PrismaCloudCompute/pack_metadata.json
- The endpoint was updated on Compute side to `xsoar-alerts`
- Query the new endpoint, if not found fallback to the previous endpoint)
> [Prisma Cloud Compute] Update compute integration endpoint (with backward compatibility)

- Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.py
- Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2.yml
- Packs/OpenPhish/Integrations/OpenPhish_v2/OpenPhish_v2_test.py
- Packs/OpenPhish/ReleaseNotes/2_0_1.md
- Packs/OpenPhish/pack_metadata.json
epic: https://github.com/demisto/etc/issues/29016
* Use the new `CommandResults.indicator` parameter.
* Update the reputation command **url** to return a different result for each indicator.
- Further details: custom scripts that run these commands using `executeCommand` might miss the switch, and handle only the first result.
> [Enhancement] OpenPhish v2 - reputation command to return a list of results

- Packs/VirusTotal/Integrations/integration-VirusTotal_5.5.yml
- Packs/VirusTotal/ReleaseNotes/1_0_2.md
- Packs/VirusTotal/TestPlaybooks/playbook-virusTotal-test.yml
- Packs/VirusTotal/pack_metadata.json
epic: https://github.com/demisto/etc/issues/29016
* Use the new `CommandResults.indicator` parameter.
* Update the reputation command **file** to return a different result for each indicator.
- Further details: custom scripts that run these commands using `executeCommand` might miss the switch, and handle only the first result.
> [Enhancement] VirusTotal - reputation command to return a list of results

- Tests/Marketplace/Tests/test_pack_dependencies.py
- Tests/Marketplace/packs_dependencies.py
fixes: https://github.com/demisto/etc/issues/29255
Improved the timing from ~10-13 minutes to ~15 seconds.
1. Instead of generating a new dependencies graph for each pack from scratch and calculate its dependencies - A full dependencies graph of all packs will be generated once, saved into memory, and from it the dependency sub-graph of each pack will be extracted and used for the calculations
2. Once the full graph is ready, the dependency calculation of each pack will be executed concurrently using multiprocessing.
See the related sdk PR [here](https://github.com/demisto/demisto-sdk/pull/855)
> Speed up pack dependencies calculations

- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity_test.py
- Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_9.md
- Packs/MicrosoftCloudAppSecurity/pack_metadata.json
epic: https://github.com/demisto/etc/issues/29016
* Use the new `CommandResults.indicator` parameter.
* Update the command **microsoft-cas-activities-list** to return a different result for each indicator.
* Various linter corrections
- Further details: custom scripts that run these commands using `executeCommand` might miss the switch, and handle only the first result.
> [Enhancement] MicrosoftCloudAppSecurity - reputation commands to return a list of results

- Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
- Packs/HelloWorld/Integrations/HelloWorld/HelloWorld_test.py
- Packs/HelloWorld/Integrations/HelloWorld/README.md
- Packs/HelloWorld/ReleaseNotes/1_1_12.md
- Packs/HelloWorld/pack_metadata.json
epic: https://github.com/demisto/etc/issues/29016
* Use the new `CommandResults.indicator` parameter.
* Update the reputation command **file** to return a different result for each indicator.
- Further details: custom scripts that run these commands using `executeCommand` might miss the switch, and handle only the first result.
> [Enhancement] HelloWorld - reputation commands to return a list of results

- Tests/Marketplace/marketplace_services.py
related: https://github.com/demisto/etc/issues/29431 
Fixes an issue where versions were not wrapped with `LooseVersion` and failed to recognize greater versions correctly.
> Bucket Version Assertion Fix

- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
- Packs/SentinelOne/ReleaseNotes/1_0_3.md
- Packs/SentinelOne/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29885
related: https://github.com/demisto/etc/issues/28233
> SentinelOne v2 - deprecated the sentinelone-expire-site command

- Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
- Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_11.md
- Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
fixes: https://github.com/demisto/etc/issues/29363
- Fixed an issue in which setting the authorization headers overridden the `Content-Type` and `Accept` headers and by that led to the following error:
```
stderr: [Task exception was never retrieved
future: <Task finished name='Task-5' coro=<EventStream._discover_refresh_stream() done, defined at <string>:5263> exception=DemistoException('Error in API call [415] - Unsupported Media Type\n{"meta": {"query_time": 1.26e-07, "powered_by": "crowdstrike-api-gateway", "trace_id": "43297451-38cb-499a-8a57-d1ac9f0b4ed6"}, "errors": [{"code": 415, "message": "415: Unsupported Media Type"}]}', None)>
Traceback (most recent call last):
File "<string>", line 5279, in _discover_refresh_stream
File "<string>", line 5231, in refresh_stream_session
File …
```
> CrowdStrike Falcon Streaming v2 - update client headers with auth header and add log prints
