Packs/APIVoid/.pack-ignore
Packs/APIVoid/Integrations/APIVoid/APIVoid.py
Packs/APIVoid/Integrations/APIVoid/APIVoid.yml
Packs/APIVoid/ReleaseNotes/1_0_27.md
Packs/APIVoid/pack_metadata.json

APIVoid - add support in credential store

---

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
Packs/HatchingTriage/ReleaseNotes/1_0_8.md
Packs/HatchingTriage/pack_metadata.json

Makes the `triage-get-sample-summary` accept an array of sample IDs. This is so the command can be used in a Genericpolling block. This requires the command to be an array. This PR also updates the docker image version and causes the `interactive` argument for the `triage-submit-sample` command to actually be used, instead of ignored.

Make summary retrieval command accept array and more

---

Packs/Base/ReleaseNotes/1_31_54.md
Packs/Base/Scripts/CommonServer/CommonServer.js
Packs/Base/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20016
Comparing server versions did not work as expected.

Comparing server versions did not work as expected

---

Packs/ProofpointThreatResponse/.pack-ignore
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
Packs/ProofpointThreatResponse/ReleaseNotes/2_0_5.md
Packs/ProofpointThreatResponse/pack_metadata.json

Proofpoint Threat Response - add support in credential store

---

Tests/Marketplace/search_and_install_packs.py

There is starvation of XSIAM build machines. We have only 3 XSIAM machines, but much more builds.
Currently XSIAM nightly is broken. Sending an API call to install packs not responding for a long time. 
As a hotfix I set a timeout - install packs on XSIAM will fail on timeout after 30 minutes.

Set timeout for install packs on XSIAM - Hot Fix

---

Tests/Marketplace/upload_packs.py

The commit in the index.json didn't has updated since we use the graph in the build, this is because we are uploading the index.json from the build artifacts and in the staging we added the "graph" word to the index file name, so since we used the graph it didn't found the `index.json` in the artifacts because it called `index-graph.json`.
Test upload: https://code.pan.run/xsoar/content/-/pipelines/4369014

Fix commit update in index.json

---

Packs/CortexXDR/Integrations/CortexXDRIR/README.md

The parameter was removed on 2.7.4. Removed it from the Docs

XDR remove parameter from README.md

---

Packs/ApiModules/ReleaseNotes/2_2_13.md
Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule_test.py
Packs/ApiModules/pack_metadata.json
Packs/FeedDHS/Integrations/DHSFeedV2/DHSFeedV2.py
Packs/FeedDHS/Integrations/DHSFeedV2/DHSFeedV2.yml
Packs/FeedDHS/Integrations/DHSFeedV2/DHSFeedV2_test.py
Packs/FeedDHS/ReleaseNotes/2_0_1.md
Packs/FeedDHS/pack_metadata.json
Packs/FeedMitreAttackv2/ReleaseNotes/1_1_8.md
Packs/FeedMitreAttackv2/pack_metadata.json
Packs/FeedTAXII/ReleaseNotes/1_1_20.md
Packs/FeedTAXII/pack_metadata.json

Move handling InvalidJSONError to Taxii2ApiMoudle.

Taxii2 json error

---

Packs/Zscaler/.pack-ignore
Packs/Zscaler/Integrations/Zscaler/Zscaler.py
Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
Packs/Zscaler/ReleaseNotes/1_3_6.md
Packs/Zscaler/pack_metadata.json

Zscaler - add support in credential store

---

Packs/AlienVault_OTX/.pack-ignore
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
Packs/AlienVault_OTX/ReleaseNotes/1_1_28.md
Packs/AlienVault_OTX/pack_metadata.json

AlienVault OTX v2 - add support in credential store

---

Packs/TIM_Processing/Playbooks/playbook-TIM_-_Indicator_Relationships_Analysis.yml
Packs/TIM_Processing/ReleaseNotes/1_1_14.md
Packs/TIM_Processing/pack_metadata.json

disable indicators auto-extract

Tim   indicator relationships playboox   disable auto extract

---

Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
Packs/SymantecDLP/ReleaseNotes/2_0_7.md
Packs/SymantecDLP/pack_metadata.json

Ran into an issue where an environment with no custom attributes causes failures on incident fetching. Python's dictionary.pop() takes a second parameter to default what it returns if the key is not found...since the integration code defaults the .get() for the 'customAttributeGroups' key, it should also default the .pop() for removing it from the dictionary. Code test in our environment solves the issue and successfully fetches incidents.

Symantec DLP Integration - Support environments with no custom attributes defined

---

.devcontainer/devcontainer.json

Allows editing demisto-sdk files from a content devcontainer

devcontainer: demisto-sdk write permissions

---

Utils/github_workflow_scripts/sync_contrib_base.py

fixes: **CIAC-5186**
A race condition was being caused where editing and then immediately merging a pr would trigger this workflow to run, merge, and then this workflow would ovverride the branch with the master commit. Setting force to false will cause only fast-forwarding changes to be accepted

took out force

---

Packs/CommonWidgets/ReleaseNotes/1_2_12.md
Packs/CommonWidgets/Widgets/widget-IncidentsDroppedInPreprocessing.json
Packs/CommonWidgets/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-71910)
remove audit type widget from xsoar ng

remove audit type widget from xsoar ng

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/ReleaseNotes/1_16_3.md
Packs/PAN-OS/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20343
Fixed an issue where in the pan-os-push-to-device-group command, the device-group argument that is returned in context and human readable is always the one from integration parameters.

[PAN-OS] - fix issue in the pan-os-push-to-device-group command

---

Tests/docker_native_image_config.json

https://jira-hq.paloaltonetworks.local/browse/CIAC-5241
skip IntezerV2 in native:ga cause it fails

skip Interzer v2 in native ga

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/3_1_20.md
Packs/Slack/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20735
Change to the listener logic resulted in all threads being treated as a reply. Changed this to re-add the missing validation.

Slack thread entitlement hotfix

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/ReleaseNotes/1_16_5.md
Packs/PAN-OS/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-20715)
Fixed an issue where in case trying to remove all addresses from an address group, then command fails on ambiguous error rather than saying the real issue.
*Note*: its not possible to remove all addresses from an address group, address group must at least have one address in its configuration.

Fix pan os edit address group bug

---

Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Possible_External_RDP_Brute-Force_-_Set_Verdict.yml
Packs/CortexXDR/ReleaseNotes/4_10_8.md
Packs/CortexXDR/pack_metadata.json

Swapped the "XDR Related Alerts" incident field with "XDR Alert Search Results" field to accommodate the layout.

Fix alerts mapping xdrbruteverdict

---

Packs/ApiModules/Scripts/MicrosoftAzureStorageApiModule/MicrosoftAzureStorageApiModule.py
Packs/AzureStorageContainer/ReleaseNotes/1_0_8.md
Packs/AzureStorageContainer/pack_metadata.json
Packs/AzureStorageFileShare/ReleaseNotes/1_0_6.md
Packs/AzureStorageFileShare/pack_metadata.json
Packs/AzureStorageQueue/ReleaseNotes/1_0_6.md
Packs/AzureStorageQueue/pack_metadata.json
Packs/AzureStorageTable/ReleaseNotes/1_0_6.md
Packs/AzureStorageTable/pack_metadata.json

fix for a bug in AzureStorageApiModule 
which cause error on the build 
https://code.pan.run/xsoar/content/-/jobs/21413006

Fix AzureStorageApiModule bug

---

Packs/Slack/doc_files/SlackV3_app_manifest.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-20927
Missing the `im:write` scope

Add missing scope to SlackV3 manifest

---

Packs/Flashpoint/Integrations/Flashpoint/Flashpoint_test.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5599)
Fixed an issue where a unit-test in FlashPoint was flaky because it didn't freeze the datetime.

[FlashPoint] - fix flaky unit-test

---

Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml
Packs/Aella_StarLight/ReleaseNotes/1_0_8.md
Packs/Aella_StarLight/pack_metadata.json

fixes: [21769159](https://code.pan.run/xsoar/content/-/jobs/21769159)
Fixed an issue where the integration wasn't supported by lower version machines.

Downgrade aella fromversion

---

Utils/test_upload_flow/create_test_branch.py

Skip triggering CI pipeline for the test branches in the test-upload-flow job.

Skip triggering CI for test branches

---

Packs/ServiceNow/.pack-ignore

Ignoring IF100 and IN139 errors to prevent the following validate failures before merging [this](https://github.com/demisto/demisto-sdk/pull/2740) PR:
```
[ERROR]: Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml: [IN139] - This is a core pack with an integration that contains the word incident in the following commands' name or argument:
command's name: [] 
command's argument: {'servicenow-create-ticket': ['parent_incident', 'incident_state'], 'servicenow-update-ticket': ['parent_incident', 'incident_state']}
[ERROR]: …
```

ignored snow errors

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_commands.txt
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Packs/MicrosoftTeams/ReleaseNotes/1_4_6.md
Packs/MicrosoftTeams/pack_metadata.json

https://jira-hq.paloaltonetworks.local/browse/CIAC-1268
After the Auth code flow implemented for Microsoft Teams in https://github.com/demisto/content/pull/23665
added the `microsoft-teams-generate-login-url` command

Microsoft Teams: add generate login uri command

---

Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP_test.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5659)
Unittest was fixed after nightly failed.
In the ticket.

FireEyeETP fix unittest

---

Packs/MicrosoftGraphIdentityandAccess/.pack-ignore

Ignore IF100 error for 'incidentfield-Alert_Type.json' as the name is fine.

Ignore IF100 in MicrosoftGraphIdentityandAccess

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Packs/MicrosoftTeams/ReleaseNotes/1_4_7.md
Packs/MicrosoftTeams/pack_metadata.json

- Fixed an issue where the *Bot ID* parameter wasn't parsed correctly after upgrading from pack version 1.4.5. 
- Added the following integration parameters to support credentials fetching object.
- *Certificate*
- *Private Key*

ms teams add support in credential store & fix

---

Packs/Core/Playbooks/playbook-NGFW_Scan.yml
Packs/Core/Playbooks/playbook-NGFW_Scan_README.md
Packs/Core/ReleaseNotes/1_3_34.md
Packs/Core/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21394)
Fixes the 'scannerIP' input usage in task 4
Changes the default value of the 'scannerIP' input to 'alert.localip'

NGFW Fixes

---

Tests/scripts/validate.sh

This PR adds Bash's `set -x` flag to the validate.sh script, which is used by our CircleCI validation build.
This flag makes the terminal echo every command it runs before it runs it (with the actual values of variables if variables are involved).
Using this flag is a common practice in CI/CD jobs, as it allows easier debugging and troubleshooting in case there are issues.
An example can be seen on the `Validate Files and Yaml` step of this PR here:
https://app.circleci.com/pipelines/github/demisto/content/238505/workflows/c7980ae0-113e-436c-a058-442824b5df39/jobs/672710
For example, now it is possible to see what SDK command was used to run validate:

[Circle CI Validation] Add `set -x` Flag to Validation Script

---

Tests/scripts/wait_until_server_ready.py

Adding more logs to wait_until_server_ready to get more information in case there's failure with SDK step [demisto-sdk-nightly:run-commands-against-instance](https://www.google.com/url?q=https://code.pan.run/xsoar/content/-/jobs/22176808&sa=D&source=editors&ust=1677405923576537&usg=AOvVaw3n8y_cA3K8qvn0BP9cgEFP)

Adding error logging for wait_until_server_ready

---

Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py

related: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21419)
If the link is None, the API call will result in a 'connection timed out error', so we raise an exception.

CoreIRApiModule - An exception was added in case link is None

---

Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.py
Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
Packs/FeedMandiant/ReleaseNotes/1_0_8.md
Packs/FeedMandiant/pack_metadata.json

fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21653)
added tags to indicators created in create_indicator method

added tags to indicators created in create_indicator method

---

Packs/MicrosoftExchangeOnline/Integrations/EwsExtension/EwsExtension.Tests.ps1
Packs/MicrosoftExchangeOnline/Integrations/EwsExtension/EwsExtension.yml
Packs/MicrosoftExchangeOnline/Integrations/EwsExtension/EwsExtension_description.md
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_0_9.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21480
PowerShell 7.2 introduced the deprecation notice for RPS, we don't want this banner breaking the output so downgrade to 7.1 is necessary.

Downgrade docker to fix banner issue

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/Integrations/SlackV3/SlackV3.yml
Packs/Slack/ReleaseNotes/3_1_23.md
Packs/Slack/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21481?filter=-1
When answering questions, use the `response_url` to edit the message instead of `chat.update` endpoint. This way it will rerender the text again and remove the previews.

Slack - Remove preview messages after answering questions

---

Packs/Exabeam/Integrations/Exabeam/Exabeam.py
Packs/Exabeam/Integrations/Exabeam/Exabeam.yml
Packs/Exabeam/Integrations/Exabeam/test_data/response_incidents.py
Packs/Exabeam/ReleaseNotes/2_2_3.md
Packs/Exabeam/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21687
Fixed an issue where the fetch-incidents command did not fetch incidents automatically,
changed the query for fetch.

fix fetch-incidents bug

---

Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5706
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5778
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5779
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5791
Increase Microsoft Defender Advanced Threat Protection - Test timeout to 200

[Tests] Microsoft Defender Advanced Threat Protection - Test - increase test timeout

---

Packs/Core/Layouts/layoutscontainer-Default.json
Packs/Core/Layouts/layoutscontainer-Default_XDR_Alert.json
Packs/Core/ReleaseNotes/1_3_36.md
Packs/Core/pack_metadata.json

Fixing an issue with layout where the dynamic section used the script GUID and not the script name.

Fix core layout

---

Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
Packs/FireEyeNX/ReleaseNotes/1_1_17.md
Packs/FireEyeNX/pack_metadata.json

relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5831)
Added sections to the FireEyeNX integration

[FireEye Network Security (NX)] Adding sections

---

Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.py
Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore.yml
Packs/IPQualityScore/Integrations/IPQualityScore/IPQualityScore_test.py
Packs/IPQualityScore/ReleaseNotes/1_0_6.md
Packs/IPQualityScore/pack_metadata.json
package.json

N/A
Bug fixes for two issues:
- The URL lookup functionality currently doesn't pull the correct value. It should pull risk_score instead of fraud_score.
- The Email lookup functionality did not URL encode all emails. This could lead to malformed results. The Email lookup functionality now encodes all emails.
N/A
- [ x ] 6.0.0
- [ x ] No

IPQualityScore Encoding and Results Bug Fixes

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5603)
Increase Test XDR Playbook execute script commands timeout from 2500 to 3000.

Test XDR Playbook execute script commands - increase test timeout

---

Tests/Marketplace/core_packs_list.json
Tests/Marketplace/core_packs_mpv2_list.json

relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-5744
Revert the removal of the VirusTotal pack from the core_packs lists.

Revert removal of "VirusTotal"

---

Packs/AwakeSecurity/Integrations/AwakeSecurity/AwakeSecurity.py
Packs/AwakeSecurity/ReleaseNotes/1_0_19.md
Packs/AwakeSecurity/pack_metadata.json

In Python2.7, map returns a list, but in 3, it returns an iterator and fails like this:
```
File "<string>", line 443, in <module>
File "<string>", line 422, in fetchIncidents
File "<string>", line 288, in incidents
File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File …
```

Awake Security: Fix python3 issue where map returns an iterator instead of a list

---

Packs/CommonPlaybooks/Playbooks/playbook-Isolate_Endpoint_-_Generic.yml
Packs/CommonPlaybooks/ReleaseNotes/2_3_46.md
Packs/CommonPlaybooks/pack_metadata.json

relates: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4886)
Deprecate `Isolate Endpoint - Generic` playbook, which is replaced by `Isolate Endpoint - Generic V2`.

"Isolate Endpoint - Generic" Playbook Deprecation

---

Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents_test.py
Packs/FiltersAndTransformers/Scripts/TimeComponents/test_data/test.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-5982)
It appears that the values of `time_zone_abbreviations` can change according to whether we're on daylight savings time.
What caused the original issue (mentioned in the ticket), seems to be that daylight savings time changed on 12/03, and with that, some timezones ("CDT" and "EDT") were changed to UTC-4 from UTC-5, which is what the test checked for.
"AST" on the other hand, probably has no change to daylight savings (there is a daylight savings variation with a different name - "ADT"), which is why it remain with or without daylight savings.
This issue has been resolved by locking the date using `freezegun.freeze_time`

[Time Components] Add `freeze_time` to unit test to make it consistent

---

Packs/Core/ReleaseNotes/1_3_40.md
Packs/Core/ReleaseNotes/1_3_41.md
Packs/Core/Triggers/Trigger_-_IOC_Alert.json
Packs/Core/pack_metadata.json

Changes the filter query from alert_source eq "XDR IOC" to alert_source eq "IOC"

IOC Alert Trigger - Filter Fix

---

Packs/CommonPlaybooks/Playbooks/playbook-Domain_Enrichment_-_Generic_v2.yml
Packs/CommonPlaybooks/ReleaseNotes/2_3_49.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-22403)
https://jira-hq.paloaltonetworks.local/browse/XSUP-22403
Fix missing `else` path in first task of the playbook

Fix missing else path in first task

---

Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5973
Increasing the memory threshold for the `Phishing v3 - DomainSquatting+EML+MaliciousIndicators - Test` test playbook.
Link to the failure: https://code.pan.run/xsoar/content/-/jobs/22874506#L3757

Phishing v3 - DomainSquatting increase memory threshold

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6019)
This playbook failed in Nightly due to timeout

CrowdStrike_Falcon_X_-Test-Detonate_URL playbook timeout update

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6018)
Increase SlackV3 TestPB timeout from 400 to 600.

[SlackV3] TestPB - Increase timeout from 400 to 600

---

Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6029?jql=project%20%3D%20CIAC%20AND%20issuetype%20%3D%20Bug
Fixing Test XDR Playbook general commands that has been failing in the Nightly, by extending the timeout to 2500.
-[x] 5.0.0

Fix Test XDR Playbook general commands fails Nightly

---

Packs/Base/ReleaseNotes/1_31_79.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json
Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/EDL.yml
Packs/EDL/ReleaseNotes/3_1_20.md
Packs/EDL/pack_metadata.json

relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-22216
relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-19830
- Added debug logs and the profiling dump functionality to EDL integration.
- Fixed an issue where profiling dump functionality could not be used in long running integrations that use Flask applications.
Debug logs:
Profiling dump:

More EDL logs

---

Packs/VirusTotal/Integrations/FeedLivehunt/FeedLivehunt_test.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6055)
The unit-test failed because we didn't freeze datetime, see the issue.

[FeedLiveHunt] - freeze datetime in unit-tests

---

Tests/conf.json

fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6084)
Extended timeout to 1500 from 1000

[Autofocus Query Samples, Sessions and Tags - Test Playbook] Extend timeout

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6083)
Changed timeout to 800 from 600

[SlackV3 TestPB] - Extend timeout

---

Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.py
Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform.yml
Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/ZeroTrustAnalyticsPlatform_test.py
Packs/ZeroTrustAnalyticsPlatform/Integrations/ZeroTrustAnalyticsPlatform/test_data/xsoar_data.py
Packs/ZeroTrustAnalyticsPlatform/Layouts/layoutscontainer-ZTAP_Alert.json
Packs/ZeroTrustAnalyticsPlatform/ReleaseNotes/1_1_6.md
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/README.md
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/ZTAPViewTimeline.py
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/ZTAPViewTimeline.yml
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/ZTAPViewTimeline_test.py
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/test_data/entries.json
Packs/ZeroTrustAnalyticsPlatform/Scripts/ZTAPViewTimeline/test_data/output.md
Packs/ZeroTrustAnalyticsPlatform/pack_metadata.json

Add view timeline script
* Add back input tag to differentiate ztap input notes
* Add script to view ZTAP timeline
* Add page to view ZTAP timeline
* Fix sync tag priority (escalate should take precidence)
Notes that inbound/outbound sync can be difficult to filter in the default view. Add a view to filter this information.
Outbound tag priority was backwards (escalation should happen if selected).

Update ZeroTrustAnalyticsPlatform to 1.1.6

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6081)
Increase Extract Indicators From File - Generic v2 - Test timeout from 350 to 700.

[Extract Indicators From File - Generic v2] - Increase timeout from 350 to 700

---

Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6134)
Changed so that **cs-falcon-get-behavior** will not get a fixed id, but from the context data.
**Before**
**After**

[playbook-CrowdStrikeFalcon-Test] - changed 'Get Behavior' to get id from context 

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/ReleaseNotes/2_4_14.md
Packs/QRadar/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22822
The command ***qradar-reference-set-value-delete*** will not fail when the value is missing from the reference set.

[QRadar v3] Ignore missing value when deleting reference set value

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
Packs/UrlScan/ReleaseNotes/1_2_7.md
Packs/UrlScan/pack_metadata.json

To make it easier for analysts to refer to the scan result as shown by URLScans own UI, I added a link to the scan result page to the output that gets written to the context.

Add urlscan res page to content output

---

.circleci/config.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6164
update remote docker version to fix native:dev failure issue.

update circle-ci remote docker version

---

Packs/Sixgill-Darkfeed/.pack-ignore

https://jira-hq.paloaltonetworks.local/browse/CIAC-5940
Now after fixing the bug with the PB validation for inputs (PB118, PB119) in this [PR](https://github.com/demisto/demisto-sdk/pull/2866) we remove these ignored errors from pack-ignore file

Sixgill Darkfeed - update pack-ignore

---

Packs/AWS-CloudTrail/Integrations/AWS-CloudTrail/AWS-CloudTrail.yml
Packs/AWS-CloudTrail/ReleaseNotes/1_0_9.md
Packs/AWS-CloudTrail/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6163
Added the *AccessKeyId* and *ReadOnly* attribute keys to the **aws-cloudtrail-lookup-events** command.

AWS-CloudTrail new attributes

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/2_5_17.md
Packs/ServiceNow/pack_metadata.json

n/a – Customer-reported issue but the customer is unable to open a support case.
Small change to fix an issue with running `servicenow-get-ticket-notes` with `use_display_value=true` when any of the ticket work notes or comments contain any newline characters. Previously, the script would throw the error below due to the notes being split on the newline (`\n`) character.

fix issue with note .split()

---

Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.py
Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
Packs/DuoAdminApi/ReleaseNotes/3_2_10.md
Packs/DuoAdminApi/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23092
Bug in Duo collector that might be related to loss of events.
demisto.setLastRun is called before the sending of the events to XSIAM.
That means that if the send-events-to-xsaim will fail the last_run already changed and the events will be lost.

Dou collector missing events

---

.gitlab/ci/global.yml
Tests/scripts/check_jobs_done.py

Adding "run-unittests-and-lint-upload-flow: [native:ga,native:maintenance,native:candidate]" to the list of upload jobs to search if the job is done
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6249

fix job done upload

---

.gitlab/ci/global.yml

Do not run lint -g on master since it breaks the coverage report
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6250)

Fixing coverage report file

---

Packs/CommonTypes/IndicatorTypes/reputation-email.json
Packs/CommonTypes/ReleaseNotes/3_3_63.md
Packs/CommonTypes/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6253
Some of the regex got changed by mistake from `\\\\` to `\\` changing its meaning.

Email regex revert to allow slash at start of email

---

Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
Packs/rasterize/Integrations/rasterize/rasterize_test.py

* Increase timeout sanepdf report test
* Change port in the test

SanePDFReport: Change port number in test and Increase timeout

---

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
Packs/HatchingTriage/ReleaseNotes/1_0_10.md
Packs/HatchingTriage/ReleaseNotes/1_0_9.md
Packs/HatchingTriage/pack_metadata.json

Some users experienced get_pack_version throwing connection errors, which causes commands to fail.
This commit should stop that from happening.

Catch and ignore error on pack version retrieval

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/EDL.yml
Packs/EDL/ReleaseNotes/3_1_23.md
Packs/EDL/pack_metadata.json

Adding debug logs for EDL integration

Adding logs for EDL

---

Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5_README.md
Packs/CommonPlaybooks/ReleaseNotes/2_3_59.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23485)
Fix a bug with the filter for pdf files in the task "Extract indicators from PDF file" of the playbook "Extract Indicators From File - Generic v2". the filter tried to match equals to `application/pdf` which was sometimes shown as other text including `pdf`, introduced a fix which changes the filter to match when includes `pdf`.

wrong filter for pdf files in playbook extract indicators from file generic v2

---

Tests/Marketplace/search_and_install_packs.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6327
Change the way we search packs in the build. Instead of searching each pack a-synchrony, let's search them and their dependencies one by one.

Search packs one by one in the build install packs step

---

Tests/docker_native_image_config.json

Remove traps from native image config as `lint -a` does not run on deprecated integrations anymore.

remove traps from native image config

---

Packs/SymantecDLP/.pack-ignore
Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.py
Packs/SymantecDLP/Integrations/SymantecDLPV2/SymantecDLPV2.yml
Packs/SymantecDLP/ReleaseNotes/2_0_10.md
Packs/SymantecDLP/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6374)
Fixed incidentStatusId parameter handling.

[Symantec Data Loss Protection V2] fixed - 'ValueError: empty separator' when using the  incidentStatusId parameter

---

.gitlab/ci/on-push.yml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6359
validate-test-conf build step validates that there is no branch in content-test-conf repo with the same name as the content branch, but contains the name. For example: 
My content branch name is: test
Content-Test-Cont repo has branches: test_darya, test_new etc.. 
Before my fix the step will fail.

Validate content-test-conf failed when brachname is substring of the branchname

---

Packs/VMRay/Integrations/VMRay/VMRay.py
Packs/VMRay/Integrations/VMRay/VMRay.yml
Packs/VMRay/ReleaseNotes/1_1_9.md
Packs/VMRay/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23603
Fixed an issue in `vmray-get-sample` output where it fails to match on SampleID (produces redundant sample entries) as reported in https://github.com/demisto/content/issues/24533.

Fixed typo in vmray-get-sample Command

---

Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
Packs/AutoFocus/ReleaseNotes/2_1_8.md
Packs/AutoFocus/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-78763
As the AutoFocus Tags Feed is deprecated we are removing its auto install

Changed AutoFocus Tags Feed to not be configured by default

---

Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.py
Packs/LogRhythmRest/Integrations/LogRhythmRestV2/LogRhythmRestV2.yml
Packs/LogRhythmRest/ReleaseNotes/2_0_18.md
Packs/LogRhythmRest/TestPlaybooks/playbook-LogRhythmRestV2-test.yml
Packs/LogRhythmRest/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-22838
currently, the command to get the drilldown data of an alarm points to incorrect path
fixing this and add the required header
according to [LogRhythm community doc](https://community.logrhythm.com/t5/AIE-Rules/AIE-Drilldown-API/m-p/44276#M1295%C2%A0)

LogRhythm: correct the drilldown data endpoint & the headers

---

Packs/ApiModules/.pack-ignore

As all the functionality of MicrosoftGraphMailApiModule are tested in the sub classes (MSGraphMail & MSGraphListener)
there is no need to test it 
add ignore to the .pack_ignoe
prevent [build fails ](https://app.circleci.com/pipelines/github/demisto/demisto-sdk/23529/workflows/eec8edff-cecb-45bf-a093-3d35a0e24bf9)

MicrosoftGraphMailApiModule: ignore BA124

---

.gitlab/ci/bucket-upload.yml

Skip non-relevant steps (upload-id-set-bucket and sync-buckets) in test upload-flow build.
Example test upload-flow build: https://code.pan.run/xsoar/content/-/pipelines/5178715

Skip non-relevant steps in test upload-flow build

---

Packs/EmailCommunication/ReleaseNotes/2_0_7.md
Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.py
Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail.yml
Packs/EmailCommunication/Scripts/PreprocessEmail/PreprocessEmail_test.py
Packs/EmailCommunication/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-24033)
when the emailsubject field of the incident are `None` the script fail due to incorrect if condition
**updated unit test failed before the fix**
**updated unit test pass after the fix**

PreproccessEmail: correct the if condition

---

Packs/TIM_Processing/.pack-ignore
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_6_0_0.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_6_0_0_README.md
Packs/TIM_Processing/ReleaseNotes/1_1_17.md
Packs/TIM_Processing/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23893
The task needs to check for suspicious IPs but checks for unknown as it is set to "0" and not "2".

Fix TIM IP enrichment playbook - wrong value in task #134

---

Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
Packs/Core/ReleaseNotes/1_3_50.md
Packs/Core/pack_metadata.json
Packs/CortexXDR/ReleaseNotes/4_10_39.md
Packs/CortexXDR/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-21419)
Fixed the url in the get request. 
In XSOAR, the base URL is the same as in XDR, but in XSIAM we must add "/api/webapp/" before the "public_api/v1/download/" (as we are doing in the main function in the Core integration).

Fixing url in 'core-get-script-execution-result-files'  XSIAM command

---

Packs/Base/ReleaseNotes/1_31_95.md
Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
Packs/Base/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24078
The method **enriched_incidents**  call **GetIncidentsByQuery**  with the **from_date**  filter
in case the result from this command is empty :
`if not json.loads(res[0]['Contents']):`
we expected to get empty array and not the `dt` (Incidents dataFrame) value.

DBotFindSimilarIncidentsByIndicators - fix fromDate filter

---

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/README.md
Packs/MicrosoftGraphMail/ReleaseNotes/1_5_2.json
Packs/MicrosoftGraphMail/ReleaseNotes/1_5_2.md
Packs/MicrosoftGraphMail/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24185
As `Single User` integration comes to provide mail functionalities for a single user, the `from`
arg is not supported in the `send-mail` and `reply-mail`, the sender will be the email configured in the `Email address from which to fetch incidents` integration param

MicrosoftGraphListener: remove the "from" arg in "send-mail" and "reply-mail"

---

Packs/Core/Layouts/layoutscontainer-Default_XDR_Alert.json
Packs/Core/ReleaseNotes/1_3_51.md
Packs/Core/pack_metadata.json

Changes the remediation buttons name.

XSIAM Layouts Buttons Name

---

Tests/Marketplace/upload_packs.py

Fixed an issue where `UnboundLocalError: local variable 'pack_image_data' referenced before assignment` in https://code.pan.run/xsoar/content/-/jobs/25799984.

Fixed an issue in upload where a variable is referenced before assignment

---

Packs/Opsgeniev2/Integrations/Opsgeniev2/Opsgeniev2.yml
Packs/Opsgeniev2/ReleaseNotes/1_0_6.md
Packs/Opsgeniev2/pack_metadata.json

https://jira-hq.paloaltonetworks.local/browse/CIAC-6615
Deprecate the **opsgeniev2** integration

Deprecate opsgenieV2

---

Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector.yml
Packs/Vectra_AI/Integrations/VectraAIEventCollector/VectraAIEventCollector_test.py
Packs/Vectra_AI/ReleaseNotes/1_2_3.md
Packs/Vectra_AI/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6639
Nightly job failed https://code.pan.run/xsoar/content/-/jobs/25812483.
Basically the `given` decorator is what is fed as input into the function `test_create_headers`. the argument that is fed into the given is `strategies.text()` which means that it generates a very large amount of `str`-type inputs into the function.
i looked further at the log out of curiosity and found why this test was considered flaky. looks like when the generated str that we use as input to the test function is “/X”, we see the following printed:
```python
message = "Hypothesis test_create_headers(token='X/') produces unreliable results:
Falsified on the first call but did not on a subsequent one"
```
I scrolled up a bit and saw the following: …

Limit Hypothesis Examples

---

pyproject.toml

removing rules not implemented in the ruff versuin used by SDK 1.14.5, until the upcoming SDK 1.15.0 release
ForceMerge reason: Doesn't affect content build, will allow people to use pre-commit

fix ruff in SDK 1.14.5

---

Packs/qualys/.secrets-ignore
Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
Packs/qualys/Integrations/Qualysv2/README.md
Packs/qualys/ReleaseNotes/1_2_7.md
Packs/qualys/pack_metadata.json

There are several API endpoints on the Qualys API that can be used in the QualysV2 integration configurations as the `SERVER URL` parameter.
Due to a recent [issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23644), this PR adds relevant info about making use of the right `SERVER URL` parameter when using asset-tags commands.

[QualysV2] Add asset-tag related documentation

---

.gitlab/ci/on-push.yml

allowed the xsoar ng build step to fail until we stabilize it

allowed ng to fail

---

.gitignore

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6696
Since we don't want to add Modeling Rules test configuration to `content` repository, we can add it to `gitignore`. 
The PR adds a `glob` pattern to match the expected directory and files of Modeling Rules test configuration.

Ignore Modeling Rules test conf

---

.github/workflows/handle-new-external-pr.yml

Downgrade the changed-files because the newest version causes issues.
example:
https://github.com/demisto/content/actions/runs/5038409895/jobs/9035879956?pr=26669
we will use in the external pr workflow the same version as we have in update_release_notes.

handle external pr workflow: downgrade the changed-files version

---

.github/workflows/handle-new-external-pr.yml

Fixes an issue where the `changed-files` in the `handle-new-external-pr.yml` workflow failed on the following error:
```
Error: Similar commit hashes detected: previous sha: d547ae0268b99a344c9f9d19032f98f80493bc67 is equivalent to the current sha: d547ae0268b99a344c9f9d19032f98f80493bc67.
Error: Please verify that both commits are valid, and increase the fetch_depth to a number higher than 50.
Error: Process completed with exit code 1.
```
the fetch-depth = 2 will retrieve the previous commit.
for more info see: https://github.com/tj-actions/changed-files#usage

add fetch-depth - handle external pr workflow

---

.github/workflows/handle-new-external-pr.yml
Packs/PAN-OS/Integrations/Panorama/Panorama.py
Utils/github_workflow_scripts/handle_external_pr.py

we cannot use the `changed-files` for the `handle-external-pr` workflow because the `pull_request_target` event operates on the base branch and not on the branch that triggered the workflow, because of that we got the following error:
```
Error: Similar commit hashes detected: previous sha: d547ae0268b99a344c9f9d19032f98f80493bc67 is equivalent to the current sha: d547ae0268b99a344c9f9d19032f98f80493bc67.
Error: Please verify that both commits are valid, and increase the fetch_depth to a number higher than 50.
Error: Process completed with exit code 1.
```
this commit is a commit of merging to the master branch which is not what we want in this case, we want the commits of the branch that triggered the workflow.
that happens because the checkout step checks out to the master branch …

Support label feature fixes

---

Packs/OSQuery/ReleaseNotes/1_0_8.md
Packs/OSQuery/Scripts/OSQueryOpenSockets/OSQueryOpenSockets.yml
Packs/OSQuery/pack_metadata.json

The <> tags are not allowed in YML files when being rendered into HTML at xsoar.pan.dev.

fix JSX error in OSQueryOpenSocket

---

Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Get_Endpoint_Forensics_Data.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_19.md
Packs/CrowdStrikeFalcon/TestPlaybooks/Test_Playbook_-_CrowdStrike_Falcon_-_Get_Endpoint_Forensics_Data.yml
Packs/CrowdStrikeFalcon/pack_metadata.json
Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6790
Test playbook for the ‘CrowdStrike Falcon - Get Endpoint Forensics Data’ playbook, which is part of the malware investigation and response pack.

Test playbook for 'CrowdStrike Falcon - Get Endpoint Forensics Data'

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/ReleaseNotes/2_4_20.md
Packs/QRadar/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24642

QRadar: better error message when search fails

---

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_5.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24410
When an attachment's name contains a control character, the XML is no longer valid when parsing the attachment's information from Microsoft via exchangelib.
Please note, when a new version of exchangelib is available, we will need to bump the docker image (should happen automatically, but we can revert this fix when it happens).
Details of the XML parsing issue can be found here - https://github.com/ecederstrand/exchangelib/issues/1200

EWS O365 Fix for attachment XML error

---

Packs/CommonScripts/ReleaseNotes/1_11_82.json
Packs/CommonScripts/ReleaseNotes/1_11_82.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-81822
**Before:**
**After:**
- Further details: `ParseEmailFilesV2` automation will no longer embed the base64 of an image in the returned HTML

ParseEmailFilesV2: update the docker image to stop embed the base64

---

Tests/docker_native_image_config.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6817)
release py3-native image for XSOAR-NG 8.3

Release native image for XSOAR-NG 8.3

---

Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_Find_AWS_Resource_by_FQDN_v2.yml
Packs/PrismaCloud/ReleaseNotes/4_1_3.md
Packs/PrismaCloud/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6858
A logic fail was fixed in the playbook: Prisma Cloud - Find AWS Resource by FQDN v2.
The condition `Are there NON AWS FQDNs?` in task #26 was fixed to verify that `NONAWSFQDN` is not empty instead of `AWSFQDN`.

Prisma cloud playbook fix

---

Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_Find_Azure_Resource_by_FQDN_v2.yml
Packs/PrismaCloud/ReleaseNotes/4_1_4.md
Packs/PrismaCloud/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6861
A logic fail was fixed in the playbook: Prisma Cloud - Find Azure Resource by FQDN v2.
The condition in task #26, `Are there NON Azure FQDNs?`, has been revised to validate that the variable **NONAzureFQDN** is not empty, instead of checking **AzureFQDN**.

Prisma cloud playbook fix azure fqdn

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/ReleaseNotes/1_17_4.md
Packs/PAN-OS/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24853
Fixed an issue where ***pan-os-list-rules*** command was filtering by *tag* instead of *tags* argument.

PAN-OS tag vs tags bug

---

Packs/ApiModules/Scripts/TAXII2ApiModule/TAXII2ApiModule.py
Packs/FeedDHS/ReleaseNotes/2_0_10.md
Packs/FeedDHS/pack_metadata.json
Packs/FeedMitreAttackv2/ReleaseNotes/1_1_13.md
Packs/FeedMitreAttackv2/pack_metadata.json
Packs/FeedTAXII/ReleaseNotes/1_1_26.md
Packs/FeedTAXII/pack_metadata.json

fixes: [XSUP-24851](https://jira-hq.paloaltonetworks.local/browse/XSUP-24851)
This PR will fix a function call error in `TAXII2ApiModule.py` where kwargs are being called as defined (`**kwargs`) instead of as an argument (`kwargs=kwargs`).
Results of `TAXII 2 Feed Test` playbook with original pack:
Results of `TAXII 2 Feed Test` playbook after changes:

[TAXII2ApiModule] Fix kwargs argument in function call

---

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
Packs/DemistoRESTAPI/ReleaseNotes/1_3_26.md
Packs/DemistoRESTAPI/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6864)
Force merge is needed:
[ERROR][INFO] : Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml: [RM110] - The following commands appear in CoreRESTAPI.yml but not in the README file:
demisto-api-post
demisto-api-get
demisto-api-put
demisto-api-delete
demisto-api-download
demisto-api-multipart
demisto-delete-incidents
demisto-api-install-packs

CoreRestAPI URL suffix fix

---

Packs/Base/ReleaseNotes/1_32_9.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

Fix urllib.parse import
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24890

Fix urllib.parse import

---

Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
Packs/Core/ReleaseNotes/1_4_1.md
Packs/Core/pack_metadata.json
Packs/CortexXDR/ReleaseNotes/4_11_4.md
Packs/CortexXDR/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24914
Fixed an issue where the polling timeout parameter wasn't used correctly.

Xdrir fix polling timeout

---

Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_12.md
Packs/MicrosoftGraphDeviceManagement/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25023

[MSGraphDeviceMgmt] fix bool parsing

---

Tests/Marketplace/search_and_install_packs.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6926
Fixes unbound local variable on search dependencies XSIAM build.

fixing unbound local variable on search dependencies

---

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
Packs/DemistoRESTAPI/ReleaseNotes/1_3_27.md
Packs/DemistoRESTAPI/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6915
A "xsoar_hosted" option as a possible platform name of XSOAR 8.x.
tested on XSOAR 6.x, XSAIM and XSOAR 8.x

Core rest api add xsoar hosted

---

Packs/ExtraHop/Playbooks/playbook-ExtraHop_-_CVE-2019-0708_BlueKeep.yml
Packs/ExtraHop/ReleaseNotes/2_1_1.md
Packs/ExtraHop/pack_metadata.json

This is a PR so we can merge the changes to the CVE layout and type that is blocked due to a bug. After merging this one we will merge the CVE one which will be able to pass the checks.
https://github.com/demisto/content/pull/26486

Switched the PB to use generic cve command as CVE Search is going to be derecated

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
Packs/AzureSentinel/Integrations/AzureSentinel/README.md
Packs/AzureSentinel/ReleaseNotes/1_5_8.md
Packs/AzureSentinel/pack_metadata.json
Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25098
Despite the documentation stating that the argument is comma separated, calling the API throws an error. When passing a string, it works as expected.

AzureSentinel - keywords argument from 'comma separate' to 'str' in azure-sentinel-threat-indicator-query

---

Packs/Salesforce/.pack-ignore
Packs/Salesforce/Integrations/Salesforce/README.md
Packs/Salesforce/Integrations/Salesforce/Salesforce.js
Packs/Salesforce/Integrations/Salesforce/Salesforce.yml
Packs/Salesforce/Integrations/Salesforce_IAM/Salesforce_IAM.py
Packs/Salesforce/Integrations/Salesforce_IAM/Salesforce_IAM.yml
Packs/Salesforce/ReleaseNotes/2_0_13.md
Packs/Salesforce/pack_metadata.json
Packs/SalesforceFusion/.pack-ignore

Align credentials stores  part 14

---

Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects20.json
Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_domain.json
Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_file.json
Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_malware.json
Packs/TAXIIServer/Integrations/TAXII2Server/test_data/objects21_spec_fields_file.json
Packs/TAXIIServer/ReleaseNotes/2_0_37.md
Packs/TAXIIServer/pack_metadata.json

fixes: [CIAC-6920](https://jira-hq.paloaltonetworks.local/browse/CIAC-6920)
- Fixed an issue where the same extension was shown to all objects.

Taxii2 fix

---

Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6961)
Instead of sending arbitrary alert that might be removed by XDR, we query all the correlation alerts we have in the instance and then put the first one we find.
In that way its being done dynamically rather then giving specific `alert_id` as an input.

fix Test_XDR_Playbook_general_commands TPB

---

Packs/AWS_WAF/Integrations/AWSWAF/AWSWAF.py
Packs/AWS_WAF/Integrations/AWSWAF/AWSWAF.yml
Packs/AWS_WAF/ReleaseNotes/1_0_1.md
Packs/AWS_WAF/pack_metadata.json
Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.py
Packs/AccentureCTI/Integrations/ACTIIndicatorQuery/ACTIIndicatorQuery.yml
Packs/AccentureCTI/ReleaseNotes/2_2_16.md
Packs/AccentureCTI/pack_metadata.json

This fix addresses a couple of small grammar mistakes in docstrings.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!

Fix small grammar typos in documentation

---

Tests/Marketplace/search_and_install_packs.py

We always try to install packs on the servers, even if the packs list is empty. Added a check on that list and considered the installation as a success in case there are no packs to install.

Fixed empty installation 

---

Packs/RTIR/Integrations/RTIR/RTIR.py
Packs/RTIR/Integrations/RTIR/RTIR.yml
Packs/RTIR/Integrations/RTIR/RTIR_test.py
Packs/RTIR/ReleaseNotes/1_0_16.md
Packs/RTIR/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25105

RTIR: fix add-comment

---

Packs/Base/ReleaseNotes/1_32_16.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
Packs/Base/pack_metadata.json

Removed double assignment to amount_of_events variable in CommonServerPython script.

Remove redundant assignment of var

---

Packs/CommonScripts/TestPlaybooks/playbook-TestIsMaliciousIndicatorFound.yml

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6842)
add sleep in order to wait for indicators to be indexed

[TestIsMaliciousIndicatorFound] - add sleep for indexing indicators

---

Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml
Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7113)
* Fixed an issue where **Test XDR Playbook general commands** TPB failed because there are not agent reports on a specific endpoint that we queried.

Test playbook fixes

---

Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
Packs/Phishing/ReleaseNotes/3_5_22.md
Packs/Phishing/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6884
"Reported Email Subject" field has been added to the basic details section of the layout.

Phishing add subject to layout

---

Packs/ApiModules/Scripts/CrowdStrikeApiModule/CrowdStrikeApiModule.py
Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.yml
Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_16.md
Packs/CrowdStrikeOpenAPI/pack_metadata.json

…mand was not returned the file.
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-25343)
- Fixed an issue where the cs-download-sensor-installer-by-id command was not returned the file.

Crowdstrike OpenAPI: Fixed the the cs-download-sensor-installer-by-id command

---

Packs/CarbonBlackEnterpriseEDR/.pack-ignore
Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_29.md
Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Packs/Carbon_Black_Enterprise_Live_Response/Integrations/Carbonblackliveresponse/Carbonblackliveresponse.js
Packs/Carbon_Black_Enterprise_Live_Response/Integrations/Carbonblackliveresponse/Carbonblackliveresponse.yml
Packs/Carbon_Black_Enterprise_Live_Response/ReleaseNotes/1_1_5.md
Packs/Carbon_Black_Enterprise_Live_Response/pack_metadata.json
Packs/DuoAdminApi/.pack-ignore
Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.py
Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
Packs/DuoAdminApi/ReleaseNotes/4_0_3.md
Packs/DuoAdminApi/pack_metadata.json

Align credentials stores - part 22

---

Packs/GoogleCloudCompute/.pack-ignore
Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.py
Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
Packs/GoogleCloudCompute/ReleaseNotes/1_1_3.md
Packs/GoogleCloudCompute/pack_metadata.json
Packs/GoogleCloudStorage/.pack-ignore
Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
Packs/GoogleCloudStorage/ReleaseNotes/1_0_10.md
Packs/GoogleCloudStorage/pack_metadata.json

Google align credentials stores - part 25

---

Packs/MicrosoftGraphDeviceManagement/.pack-ignore
Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_13.md
Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Packs/MicrosoftGraphFiles/.pack-ignore
Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.py
Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles.yml
Packs/MicrosoftGraphFiles/ReleaseNotes/1_1_13.md
Packs/MicrosoftGraphFiles/pack_metadata.json
Packs/MicrosoftGraphGroups/.pack-ignore
Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_22.md
Packs/MicrosoftGraphGroups/pack_metadata.json
Packs/MicrosoftManagementActivity/.pack-ignore
Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py
Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml
Packs/MicrosoftManagementActivity/ReleaseNotes/1_3_20.md
Packs/MicrosoftManagementActivity/pack_metadata.json

Fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7170

Microsoft Align credentials stores -part 23

---

Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7114)
* Fixed an issue with **Test - CrowdStrike Falcon** where the TPB failed because there are no quarantine files.
* Removed tasks which were duplicated.

fix Test - CrowdStrike Falcon TPB

---

Packs/Reco/Integrations/Reco/Reco.py
Packs/Reco/Integrations/Reco/Reco.yml
Packs/Reco/Integrations/Reco/Reco_test.py
Packs/Reco/ReleaseNotes/1_1_3.md
Packs/Reco/pack_metadata.json

Packs/Reco: fix validate_api_key

---

Packs/Maltiverse/.pack-ignore
Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.py
Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.yml
Packs/Maltiverse/ReleaseNotes/1_0_22.md
Packs/Maltiverse/pack_metadata.json
Packs/fireeye/.pack-ignore
Packs/fireeye/Integrations/Fireeye/Fireeye.js
Packs/fireeye/Integrations/Fireeye/Fireeye.yml
Packs/fireeye/Integrations/Fireeye/README.md
Packs/fireeye/ReleaseNotes/1_0_12.md
Packs/fireeye/pack_metadata.json

Align credentials stores - part 27

---

Packs/PagerDuty/.pack-ignore
Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.yml
Packs/PagerDuty/ReleaseNotes/1_1_7.md
Packs/PagerDuty/pack_metadata.json
Packs/Tanium/.pack-ignore
Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.yml
Packs/Tanium/ReleaseNotes/1_0_27.md
Packs/Tanium/pack_metadata.json

Align credentials stores - part 31

---

.github/workflows/handle-new-external-pr.yml
Utils/github_workflow_scripts/handle_external_pr.py

- Update contribution reviewers
- Ruff upgrades to code standards
- Upgraded Python version `3.9` to `3.10`

Update contribution reviewers

---

Packs/Claroty/Integrations/Claroty/Claroty.py
Packs/Claroty/Integrations/Claroty/Claroty.yml
Packs/Claroty/ReleaseNotes/1_0_25.md
Packs/Claroty/pack_metadata.json

Make sure to register your contribution by filling out the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)
The severity mapping was not working correctly, and were sent key instead of a value. Also, there was an additional separator in query params that was braking filters

Fix incorrect parsing of severity level

---

Packs/ContentManagement/.pack-ignore
Packs/ContentManagement/Playbooks/playbook-Delete_Custom_Content.yml
Packs/ContentManagement/Playbooks/playbook-Delete_Custom_Content_README.md
Packs/ContentManagement/ReleaseNotes/1_2_10.md
Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.py
Packs/ContentManagement/Scripts/DeleteContent/DeleteContent.yml
Packs/ContentManagement/pack_metadata.json

Added new inputs `instance_name` - the Core REST API instance name to use.

[Delete Custom Content] Add input - `using`

---

Packs/AnsibleCiscoIOS/.pack-ignore
Packs/AnsibleKubernetes/.pack-ignore
Packs/AnsibleLinux/.pack-ignore
Packs/AzureKeyVault/.pack-ignore
Packs/CloudConvert/.pack-ignore
Packs/FreshDesk/.pack-ignore
Packs/GoogleKubernetesEngine/.pack-ignore
Packs/GoogleSafeBrowsing/.pack-ignore
Packs/GoogleVault/.pack-ignore
Packs/Jira/.pack-ignore
Packs/Perch/.pack-ignore
Packs/SalesforceFusion/.pack-ignore
Packs/SplunkPyPreRelease/.pack-ignore
Packs/TrendMicroCAS/.pack-ignore
Packs/TrendMicroDDA/.pack-ignore
Packs/VMwareWorkspaceONEUEM/.pack-ignore
Packs/VersaDirector/.pack-ignore
Packs/cyberark_AIM/.pack-ignore

Add IN145 To Failing Integrations

Add IN145 To Failing Integrations

---

Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch.py
Packs/CIRCL/Integrations/CirclCVESearch/CirclCVESearch_test.py
Packs/CIRCL/ReleaseNotes/1_0_13.md
Packs/CIRCL/ReleaseNotes/1_0_14.md
Packs/CIRCL/pack_metadata.json

Updated the integration to extract the correct CVSS version from its vector.

CIRCL CVE Search parse CVSS version

---

pyproject.toml

Ignore any Python update in ApiModules, until we can properly determine their desired version.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7313
Ignore any Python update in ApiModules, until we can properly determine their desired version.

Ignore any Python update in ApiModules, until we can properly determine their desired version.

---

Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Enrichment.yml
Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_22.md
Packs/CortexAttackSurfaceManagement/pack_metadata.json

[EXPANDR-4135](https://jira-hq.paloaltonetworks.local/browse/EXPANDR-4135)
Updates `Cortex ASM - Enrichment` playbook conditionals to check if `inputs.RemoteIP` is an IPv4 address.

[ASM] - Expander 4135 - IPv4 / IPv6

---

Packs/MicrosoftADFS/pack_metadata.json
Packs/MicrosoftCore/pack_metadata.json
Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif
Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_5.md
Packs/MicrosoftWindowsEvents/pack_metadata.json

This PR is created in order of removing the dependecies between the packs - Microsoft Core, ADFS and Windows Event Logs

XSIAM | Remove dependencies from Windows Packs & Fix for Windows Events Modeling (EventType)

---

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_29.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25973
fixed an issue that caused the `file` command to return data for only one file.

fix WildFire v2 file command for files array

---

Packs/ProofpointTAP/ParsingRules/ProofpointTAP/ProofpointTAP.xif
Packs/ProofpointTAP/ReleaseNotes/1_2_6.md
Packs/ProofpointTAP/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26112

Proofpoint parsing issue

---

Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule.py
Packs/ApiModules/Scripts/NGINXApiModule/NGINXApiModule_test.py
Packs/EDL/ReleaseNotes/3_2_3.md
Packs/EDL/ReleaseNotes/3_2_4.md
Packs/EDL/pack_metadata.json
Packs/ExportIndicators/ReleaseNotes/1_0_19.md
Packs/ExportIndicators/pack_metadata.json
Packs/TAXIIServer/ReleaseNotes/2_0_41.md
Packs/TAXIIServer/pack_metadata.json

related: https://jira-hq.paloaltonetworks.local/browse/XSUP-24435?filter=-1
This fixes an issue when the exception was supressed in internal function.

Kill long running container when the connection is lost

---

Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml

Fix for missing `marketplacev2` for the event collector.

Darktrace Event Collector - Added the marketplacev2 to the yml file

---

Packs/CommonScripts/ReleaseNotes/1_12_5.md
Packs/CommonScripts/Scripts/GetlistRow/GetListRow.py
Packs/CommonScripts/Scripts/GetlistRow/GetListRow.yml
Packs/CommonScripts/pack_metadata.json

related: 
https://jira-hq.paloaltonetworks.local/browse/XSUP-25540
https://github.com/demisto/content/pull/28066
Server side issue that replace the tab character `	` to 4 space cause the `GetListRow` script to not work as expected when the delimator of the list are tab
fix : replace `\\t' with '\t' as now the tab separated values saved in server  as `\t` separated values
**the list**
**call from Playbook**
**call from CLI**

GetListRow: fix tab separated values issue

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_3.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-26344)
due to changes in [this pr](https://github.com/demisto/content/issues/27530)
an if condition is removed and this lead to call the function `get_incidents_entities` with empty `incidents_ids` and the API throw `400 - reason: Bad Request`

CrowdStrike Falcon: add condition to before get_incidents_entities

---

Packs/HarfangLabEDR/.pack-ignore
Packs/Zabbix/.pack-ignore
Packs/Zabbix/Integrations/Zabbix/README.md

`BA125` validation assures that terms like `test-module` aren't in use in customer-facing documentation.
The 2 integrations that are being ignored from this validation on this PR are integrations that have `test-module` as a command in their YAML file, meaning that when we run format on them (which is what happened that failed the build), a section with `test-module` command's description (from the YAML) is automatically added.

Fix BA125 Validation Failure

---

Packs/HarfangLabEDR/.pack-ignore
Packs/Zabbix/.pack-ignore

The fix on https://github.com/demisto/content/pull/28403 added the ignore to the wrong file (YAML instead of README).
This PR fixes it.

[Demisto-SDK] Fix BA125 Validation Failure (part 2)

---

Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict.yml
Packs/CommonPlaybooks/Playbooks/playbook-Enrichment_for_Verdict_README.md
Packs/CommonPlaybooks/Playbooks/playbook-User_Investigation_-_Generic.yml
Packs/CommonPlaybooks/ReleaseNotes/2_3_82.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7530)
enhancement for the following playbooks:
**User Investigation - Generic:**
Added transformer `set-if-empty` to MathUtil task for calculating the total number of failed logins.
**Enrichment for Verdict:**
Added input `UseReputationCommand` - This input determines if to use the reputation command (!IP, !Domain, !Url) to enrich the IP, URL, and domain.

Playbook enhancment enrichment for verdicet and user investigation

---

Packs/FeedMitreAttackv2/ReleaseNotes/1_1_19.md
Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/MITREIndicatorsByOpenIncidentsv2.py
Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/MITREIndicatorsByOpenIncidentsv2.yml
Packs/FeedMitreAttackv2/Scripts/MITREIndicatorsByOpenIncidentsv2/MITREIndicatorsByOpenIncidentsv2_test.py
Packs/FeedMitreAttackv2/pack_metadata.json

Managed to reproduce. When the server http response was as follows:
res = {'total': 0, 'iocs': None, 'searchAfter': None, 'accountErrors': None, 'totalAccounts': 0}
res.get('iocs', []) will return [] only if iocs key does not exist in the dict. if the iocs is None in the dict it will return None and fail afterwords in the for loop.
Added UT to cover this case.
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-26443)

Mitre indicators by open incidents bug fix

---

Packs/CommunityCommonScripts/ReleaseNotes/1_1_0.md
Packs/CommunityCommonScripts/Scripts/GetIndicatorCustomFieldsByQuery/GetIndicatorCustomFieldsByQuery.py
Packs/CommunityCommonScripts/Scripts/GetIndicatorCustomFieldsByQuery/GetIndicatorCustomFieldsByQuery.yml
Packs/CommunityCommonScripts/Scripts/GetIndicatorCustomFieldsByQuery/README.md
Packs/CommunityCommonScripts/pack_metadata.json

Returns indicator custom fields into the context by the given query.

GetIndicatorDBotScoreFromContext Automation

---

Packs/ServiceNow/Playbooks/playbook-ServiceNow_Ticket_State_Polling.yml
Packs/ServiceNow/ReleaseNotes/2_5_35.md
Packs/ServiceNow/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7409)
Changed the condition from `ServiceNow.Ticket(val.State != '6' || val.State != '7').Number` to `ServiceNow.Ticket(val.State != '6' && val.State != '7').Number`, as in the original situation the loop is always true

fixed dt condition in snow ticket state polling playbook

---

Packs/HarfangLabEDR/.pack-ignore
Packs/Zabbix/.pack-ignore

We originally added `BA125` to `.pack-ignore` of these packs because their integrations have `test-module` listed as a command in their YAML file, causing the validation to fail when people run `format` and don't remove the added`test-module` section in their README file.
Now that the SDK version has been updated on the `content` repository, we can restore the validation for these integrations and trust that people won't cause master's build to fail, since the validation will fail during the PR stage, blocking them from merging, and they'll have to remove the `test-module` section from the README file to merge.

Remove `BA125` from `.pack-ignore`

---

Tests/Marketplace/versions-metadata.json

Lock corepacks-8.3.0.json file back after unlocking it for fixing the issue below.
relates: https://jira-hq.paloaltonetworks.local/browse/CRTX-89375.

Re-lock corepacks-8.3.0.json file

---

.pre-commit-config_template.yaml

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7670
Sourcery is configured to run once pre-commit is ran, and since Sourcery requires users to log in in order for it to run, [reference](https://github.com/sourcery-ai/sourcery#cli), we should disable it so users won't need to do that when they run pre-commit.

Add skip:true to skip sourcery

---

Packs/Workday/Integrations/Workday/Workday.yml
Packs/Workday/ReleaseNotes/1_3_8.md
Packs/Workday/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26766
Fixed the credentials type parameters display names (they were all password)

fixed display for type 9 parameters in workday

---

pyproject.toml

Removes SIM108 from the list of ruff rules used across the repo

ruff: remove `SIM108`

---

Tests/docker_native_image_config.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7655
Add Intezer to the list of ignored content items to run UT and lints on `native` Docker image. This is for https://github.com/demisto/content/pull/28630.

Ignore Intezer from Running on Native Docker Images

---

.gitlab/ci/.gitlab-ci.global.yml

Added more loggings to better debug the process where we mkdir unittests dir in the unittests-and-lint step in the build.

added loggings

---

Packs/CortexXDR/Classifiers/classifier-PaloAltoNetworks_Cortex_XDR_Incident_Handler.json
Packs/CortexXDR/ReleaseNotes/5_0_6.md
Packs/CortexXDR/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26713
Fixed an issue where incoming incidents classified to the wrong incident type (malware instead of XDR incident).

XDR classifier fix

---

Packs/CommonScripts/ReleaseNotes/1_12_12.md
Packs/CommonScripts/Scripts/AssignAnalystToIncident/AssignAnalystToIncident.yml
Packs/CommonScripts/pack_metadata.json

Fixed an issue where this script was shown as `AssignAnalystToAlert` in XSIAM. Script functionality is unchanged (Assigns analyst to an incident. XSIAM alerts cannot be assigned.)
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7748

fix `AssignAnalystToAlert` to `AssignAnalystToIncident`

---

Tests/Marketplace/search_and_uninstall_pack.py

added loggings for unsuccessful processes, where we could not uninstall packs and got exception with more retries left, we did not print anything to the logs.

added loggings for unsuccessful processes

---

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
Packs/Core/ReleaseNotes/2_0_5.json
Packs/Core/ReleaseNotes/2_0_5.md
Packs/Core/pack_metadata.json

fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-26537)
Changed the *email* argument of the command ***core-report-incorrect-wildfire*** to be required as the command wouldn't return any results without it.

[CortexCoreIR] change the "email" argument of core-report-incorrect-wildfire

---

Packs/ProofpointTAP/Integrations/ProofpointTAP_v2/ProofpointTAP_v2.py
Packs/ProofpointTAP/ReleaseNotes/1_2_9.md
Packs/ProofpointTAP/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26869
Fixed an issue where setting new instance of the integration result in an error "'<' is not supported".

[ProofPoint Tap v2] Fix '<' is not supported

---

Packs/EDL/Integrations/EDL/EDL_description.md
Packs/EDL/ReleaseNotes/3_2_7.md
Packs/EDL/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24767

EDL HA Doc

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
Packs/AzureSentinel/ReleaseNotes/1_5_16.md
Packs/AzureSentinel/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26514
Currently, in mirror out we send only few fields if they are changed
but the `owner` field is missed and this lead to Azure to set the owner to Unassigned.
fix: get the original owner from azure and send it when we update the other fields

Azure Sentinel: send the original owner in mirror

---

Packs/CommonScripts/ReleaseNotes/1_12_15.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26948
https://jira-hq.paloaltonetworks.local/browse/XSUP-27106
update the docker image to the new one with the `parse-emails` module version 0.1.16

ParseEmailsV2: update docker image

---

Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.py
Packs/SecureWorks/Integrations/TaegisXDRv2/TaegisXDRv2.yml
Packs/SecureWorks/ReleaseNotes/5_0_1.md
Packs/SecureWorks/pack_metadata.json

This provides a fix for 2 issues:
* `taegis-fetch-investigation` was using an old field called `processing_status`. Should be `processingStatus`
* `taegis-create-comment` was using an old field called `id`. Should be `investigationId`.

Taegisxdrv2 Investigations Hotfix

---

Tests/docker_native_image_config.json

remove intezer v2 as it contains two entries under the `ignored_content_items`

remove intezer v2 from docker native image config

---

Packs/DefaultPlaybook/Playbooks/Default_8_2_README.md
Packs/PAN-OS/Playbooks/PAN-OS_-_Configure_DNS_Sinkhole_README.md
Packs/PasswordResetViaChatbot/Playbooks/Reset_User_Password_via_Chatbot_README.md

Ready
Related: https://jira-hq.paloaltonetworks.local/browse/CIAC-2793
Related: https://jira-hq.paloaltonetworks.local/browse/CIAC-4697
Adds videos to the playbook READMEs of the DNS Sinkhole and Password Reset via Chatbot use-cases.

Add playbook videos to DNS Sinkhole and Password Reset via Chatbot use-cases

---

.github/workflows/check-partner-approved-label.yml

The initial [PR](https://github.com/demisto/content/pull/28279)
had a condition that made the partner-approved flow to run only when PR is opened and not when something changes in the PR.
Fixed it.

Fix gtihub workflow for partner-approved label flow

---

Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.py
Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports.yml
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_33.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

relates: [CRTX-77146](https://jira-hq.paloaltonetworks.local/browse/CRTX-77146).
While working on the above-mentioned issue, I opened this PR - [pull/25002](https://github.com/demisto/content/pull/25002) which includes a content patch for handling xsoar ng version 8.1.0. 
As described in the issue, the server team fixed their issue and we can now classify XSAOR NG machines as XSOAR machines, by using the `get_demisto_version().get('platform')` only. 
In this PR I'm reverting the content patch.

Wildfire Reports - Reverted the content patch

---

Packs/CommonScripts/ReleaseNotes/1_12_17.md
Packs/CommonScripts/Scripts/GeneratePassword/GeneratePassword.py
Packs/CommonScripts/Scripts/GeneratePassword/GeneratePassword.yml
Packs/CommonScripts/Scripts/GeneratePassword/GeneratePassword_test.py
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8069)
Fixed an issue where no correct default values were given for max_* arguments.
Before and after the fix:

Fix default argument values in Generate Password

---

Packs/IllusiveNetworks/ModelingRules/IllusiveNetworks_1_3/IllusiveNetworks_1_3_schema.json
Packs/IllusiveNetworks/ReleaseNotes/1_0_29.md
Packs/IllusiveNetworks/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8109)

Illusive Fix

---

Packs/Workday/Integrations/WorkdayIAMEventsGenerator/WorkdayIAMEventsGenerator.yml

added toversion to make sure this integration won't be available in xsoar 8

toversion for workday event generator

---

Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_22.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27369)
Fixed an issue where the ***o365-sc-new-search-action*** command failed on timeout because of a missing command parameter.

S&c timeout issue

---

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.py
Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2.yml
Packs/MicrosoftExchangeOnPremise/Integrations/EWSv2/EWSv2_test.py
Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_0_7.md
Packs/MicrosoftExchangeOnPremise/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27576)

ewsv2 from argument fix

---

Packs/CommonScripts/TestPlaybooks/playbook-GeneratePassword-Test.yml

fixes: [CIAC-7732](https://jira-hq.paloaltonetworks.local/browse/CIAC-7732)
Fix `GeneratePassword-Test` TPB as a part of the following effort: [CIAC-7201](https://jira-hq.paloaltonetworks.local/browse/CIAC-7201).
This TPB failed because none of the following GeneratePassword script arguments were sent to the GeneratePassword-Test TPB:  min_uppercase, min_lowercase, min_digits, min_symbols.
As a result, all of the arguments defaulted to 0 and a corresponding exception was raised (further details in the Jira issue).
Changes made:

Fix GeneratePassword-Test TPB

---

Packs/qualys/ModelingRules/QualysModelingRules/QualysModelingRules_schema.json
Packs/qualys/ReleaseNotes/2_0_4.md
Packs/qualys/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8269)
Added fields to schema, and changed "is_array": "true" to "is_array": "false"

Qualys fix schema

---

Packs/dnstwist/TestPlaybooks/playbook-dnstwist_Test.yml

fixes: [CIAC-7743](https://jira-hq.paloaltonetworks.local/browse/CIAC-7743)
Fix `dnstwistTest` TPB as a part of the following effort: [CIAC-7201](https://jira-hq.paloaltonetworks.local/browse/CIAC-7201).
This TPB failed because the domain command arguemnt in task 6 was causing timeout. (further details in the Jira issue).
Changes made:
___

Fix dnstwistTest TPB

---

Packs/ContentManagement/doc_files/ci-cd.yml

Fixing call to demisto-sdk lint with -vvv, this flag is deprecated

fix demisto-sdk -vvv in content management pack

---

Packs/QRadar/Playbooks/playbook-Access_Investigation_-_QRadar.yml
Packs/QRadar/ReleaseNotes/2_4_35.md
Packs/QRadar/pack_metadata.json

Deprecate qradar access investigation

Deprecate qradar access investigation

---

Packs/CommonPlaybooks/TestPlaybooks/playbook-Containment_Plan-Test.yml
Packs/CommonPlaybooks/TestPlaybooks/playbook-Eradication_plan_-_Test.yml

The following test playbook failed during the nightly run with a timeout error when the playbook attempted to create a file using core-run-script-execute-commands. The timeout for the polling command (to create the file) was updated.

timeout for polling command (create file) was updated.

---

Utils/trigger_test_upload_flow.sh

This will provide the SDK_REF variable to the trigger of test upload so the test upload flow will be triggered with the custom sdk branch if necessary.
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8375

Test upload: use the SDK_REF in the test upload job

---

Packs/AWS-SNS/pack_metadata.json
Packs/CIRCLHashlookup/pack_metadata.json
Packs/CadoResponse/pack_metadata.json
Packs/CheckPointSandBlast/pack_metadata.json
Packs/CimTrak-SystemIntegrityAssurance/pack_metadata.json
Packs/CiscoAMP/pack_metadata.json
Packs/FeedCognyteLuminar/pack_metadata.json
Packs/FeedReversingLabsRansomwareAndRelatedToolsApp/pack_metadata.json
Packs/FortinetFortiwebVM/pack_metadata.json
Packs/Hackuity/pack_metadata.json
Packs/HarfangLabEDR/pack_metadata.json
Packs/Inventa/pack_metadata.json
Packs/Jq/pack_metadata.json
Packs/MITRECoA/pack_metadata.json
Packs/ManageEngine_PAM360/pack_metadata.json
Packs/Ncurion/pack_metadata.json
Packs/PhishUp/pack_metadata.json
Packs/RemoveEmptyEvidence/pack_metadata.json
Packs/SimpleAPIProxy/pack_metadata.json
Packs/TrustwaveFusion/pack_metadata.json
Packs/Wiz/pack_metadata.json
Tests/scripts/collect_tests/constants.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-92099
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-92921
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-92914
- Adds the `marketplaces` key to pack metadata files that are missing this.
- Align default marketplaces between collect-tests and create-graph.

Add marketplaces to pack metadata

---

Packs/Workday/Integrations/WorkdayEventCollector/README.md
Packs/Workday/Integrations/WorkdayEventCollector/WorkdayEventCollector.yml
Packs/Workday/ReleaseNotes/1_4_1.md
Packs/Workday/pack_metadata.json

updated the example of the server url in the yml and readme.

Workday documentation fix

---

Tests/conf.json

`generic-sql-oracle` TPB was added to "skipped_tests" due to instance issues as a part of the following Jira issue: https://jira-hq.paloaltonetworks.local/browse/XSUP-24414.
Now that the instance is valid, we are removing the `generic-sql-oracle` TPB from skipped_tests so it can run in Nightly again.

Remove generic-sql-oracle from skipped_tests

---

Packs/CortexXDR/TestPlaybooks/Test_XDR_Playbook_general_commands.yml

fixes: [CIAC-8341](https://jira-hq.paloaltonetworks.local/browse/CIAC-8341)
Fix `Test XDR Playbook general commands` TPB as a part of the following effort: [CIAC-7201](https://jira-hq.paloaltonetworks.local/browse/CIAC-7201).
This TPB failed because it used deprecated commands.
Changes made:

Fix Test XDR Playbook general commands TPB

---

Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
Packs/Kafka/ReleaseNotes/2_0_16.md
Packs/Kafka/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-93194

Kafka Client Certificate Hidden

---

Packs/RSANetWitness_v11_1/Integrations/RSANetWitnessv115/RSANetWitnessv115_test.py

Related to this: https://github.com/demisto/content/pull/29713/files
Fixing the test test_clean_old_inc_context_with_expired_incident in RSA Netwitness, adding to it a freeze_time and increasing the timedelta().

Fixing a test in RSA Netwitness 

---

Tests/Marketplace/common.py

fixing "operation is already in progress" string search
related to [CRTX-93506](https://jira-hq.paloaltonetworks.local/browse/CRTX-93506)

fixing "operation is already in progress" string search

---

Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server_description.md

Update TAXII2 Server for EDL

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_10.md
Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_8.md
Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_9.md
Packs/CrowdStrikeFalcon/pack_metadata.json

relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-28161
relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-28512
Reverted changes done on version 1.11.8 and 1.11.9 to fetch incidents as they probably introduced a bug in fetching detections from CS

Cs falcon detections revert

---

Packs/CommonScripts/ReleaseNotes/1_12_27.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26948
[PR in dockerfiles ](https://github.com/demisto/dockerfiles/pull/20516)
Use the updated `parse-emails` image with the version `0.1.18` of `parse-emails` module

ParseEmailFilesV2: update docker image

---

Tests/Marketplace/marketplace_services.py
Tests/scripts/collect_tests/collect_tests.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8285?
Fix a bug that collect_test.py would always work with the index file of marketplace-dist. instead of downloading the index file corresponding to the marketplace we are collecting test for.

added functionallity to download index by marketplace

---

Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.py
Packs/GCP-IAM/Integrations/GCPIAM/GCPIAM.yml
Packs/GCP-IAM/ReleaseNotes/1_0_19.md
Packs/GCP-IAM/pack_metadata.json

Related: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8236)
In order to run `pre-commit` on our entire repo, it is necessary to fix certain files that fail the `mypy` hook.

[pre-commit MyPy] Align the entire repo with MyPy #4

---

Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.py
Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_test.py
Packs/Armis/ReleaseNotes/1_1_3.md
Packs/Armis/pack_metadata.json

relates: [XSUP-28767](https://jira-hq.paloaltonetworks.local/browse/XSUP-28767)
This PR sets the last run for the initial fetch, so that the original fetch time would remain constant until events are fetched (and not update the initial fetch time every fetch cycle).
Changes made:

[Armis Event Collector] Update initial fetch handling

---

Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.yml
Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_9.md
Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json

Resolves an issue where a limit is manually passed to the `mati-feed-get-indicators` command results in an error saying '>' not supported between instances of 'str' and 'int'

Fixing `limit` argument for `mati-feed-get-indicators`

---

.pre-commit-config_template.yaml

Because `run-unit-tests` hook sometimes generates temporary files, and currently they are not deleted, then `validate` hook fails because it does not recognize these files, so `validate` needs to run before `run-unit-tests`.
**This will only take effect after https://github.com/demisto/demisto-sdk/pull/3719 is merged.**

[pre-commit-config_template] Fix validate

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/ReleaseNotes/2_4_37.md
Packs/QRadar/pack_metadata.json

The `task_id` argument is a polling argument in `qradar-indicators-upload` and  in `qradar-reference-set-value-upsert`. It was misplaces in the YAML. Moved this to the correct place
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28968?filter=-1

[QRadar] fix task_id argument in YAML

---

Packs/SymantecManagementCenter/.pack-ignore
Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.py
Packs/SymantecManagementCenter/Integrations/SymantecManagementCenter/SymantecManagementCenter.yml
Packs/SymantecManagementCenter/ReleaseNotes/1_0_11.md
Packs/SymantecManagementCenter/pack_metadata.json

N/A
Make changes to:
- Prevent additions of duplicate 'url' entries in function `add_policy_content_request()`
- Ignore case when deleting ‘url’ entries in function `delete_policy_content_request()`

Updates to prevent additions of dup url entries and ignore case when deleting url entries

---

Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
Packs/ServiceNow/ReleaseNotes/2_5_43.md
Packs/ServiceNow/pack_metadata.json

fixes: None
ServiceNow lets you define custom APIs. Added the possibility to send request to such custom APIs by adding an optional custom_api_root argument to the **servicenow-generic-api-call** command which lets you overwrite the hardcoded default api root. Additionally the changes from demisto-sdk validation have been applied and a unit test for the new argument has been added.

Additional argument for servicenow-generic-api-call command

---

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/Elasticsearch/ReleaseNotes/1_3_18.md
Packs/Elasticsearch/pack_metadata.json
Packs/FeedCyjax/Integrations/FeedCyjax/FeedCyjax.yml
Packs/FeedCyjax/ReleaseNotes/1_0_24.md
Packs/FeedCyjax/pack_metadata.json

Update cyjax and elastic search images as the python modules that they use cannot support urlib3 > 2
see docker PR: https://github.com/demisto/dockerfiles/pull/20988

Update elastic search & cyjax docker images

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8614)
Added timeout = 1800 to "Autofocus Query Samples, Sessions and Tags Test Playbook"

[Autofocus Query Samples, Sessions and Tags Test Playbook] Adding timeout

---

Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8647)
Added timeout = 300 to "playbook-SearchIncidentsV2InsideGenericPollng-Test"

[playbook-SearchIncidentsV2InsideGenericPollng-Test] Adding timeout

---

Packs/DevSecOps/Integrations/MinIO/MinIO.py
Packs/DevSecOps/Integrations/MinIO/MinIO.yml
Packs/DevSecOps/Integrations/MinIO/README.md
Packs/DevSecOps/Integrations/MinIO/command_examples
Packs/DevSecOps/ReleaseNotes/1_1_7.md
Packs/DevSecOps/pack_metadata.json

This PR adds 3 commands to the integration `MinIO`:
- minio-copy-object: Create an object by server-side copying data from another object.
- minio-set-tag: Set tags configuration to an object.
- minio-get-tags: Get tags configuration of an object.
It also fix an issue where the parameter `bucket_name` had an predefined value to empty string which show a dropdown menu for the `minio-put-object` and `minio-fput-object` commands. It fix the same issue on the parameter `length` for the `minio-get-object` command.
Here is the visual picture:
Here is the …

[DevSecOps] MinIO Bug fix and add new commands

---

.gitlab/ci/.gitlab-ci.bucket-upload.yml

fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6807)
Sync at first stage marketplace-saas-dist instead of marketplace-dist to marketplace-xsoar-dev

sync from marketplace-saas-dist instead of marketplace-dist to qa-dev bucket

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/ReleaseNotes/2_1_11.md
Packs/PAN-OS/pack_metadata.json

Updated the Docker image and fix `autopep8` error.

[Palo Alto Networks PAN-OS] Updated the Docker image

---

Packs/qualys/Integrations/Qualysv2/Qualysv2.py

fix added warning IP list too large

---

Packs/Reco/Integrations/Reco/Reco.py
Packs/Reco/Integrations/Reco/Reco_test.py
Packs/Reco/ReleaseNotes/1_1_7.md
Packs/Reco/pack_metadata.json

packs/reco: change path of url

---

Tests/scripts/is_file_up_to_date.sh

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-7218
github actions does not have branch context, so added fallback to use the latest commit

[Pre-Commit] Support `is_file_up_to_date.sh` script in GitHub Actions

---

Packs/ThreatZone/README.md

wrong character in the README cause it to not rendered well

ThreatZone: fix README

---

.gitlab/ci/.gitlab-ci.on-push.yml
.gitlab/ci/.gitlab-ci.sdk-nightly.yml

fix SDK nightly build on destroy instance

fix SDK nightly build on destroy instance & Content Merge build

---

.gitlab/ci/.gitlab-ci.bucket-upload.yml
Tests/Marketplace/install_packs.sh

added bot name without space

---

Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.py
Packs/XSOARFileManagement/Integrations/XSOARFileManagement/XSOARFileManagement.yml
Packs/XSOARFileManagement/ReleaseNotes/1_0_2.md
Packs/XSOARFileManagement/pack_metadata.json

Add a parameter that takes in imput base64 to upload binary file to XSOAR.
Base64 encoding is just a way to pass binary as a parameter, the function will decode the base64 and insert the output in the file.

add a way to upload binary file

---

.gitlab/ci/.gitlab-ci.global.yml

fixing the check validating build files are up to date

fixing the check validating build files are up to date

---

Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_By_Highest_DBotScore_6_0.yml
Packs/CommonPlaybooks/ReleaseNotes/2_4_17.md
Packs/CommonPlaybooks/pack_metadata.json

Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8883
Improved the performance of the `Calculate Severity By Highest DBotScore` playbook by ensuring that only unique items from `DBotScore.Indicator` are passed to the `GetIndicatorDBotScoreFromCache` script.

Calculate Severity By Highest DBotScore - performance improvement

---

Packs/Whois/Integrations/Whois/Whois.py
Packs/Whois/Integrations/Whois/Whois.yml
Packs/Whois/ReleaseNotes/1_5_5.json
Packs/Whois/ReleaseNotes/1_5_5.md
Packs/Whois/pack_metadata.json
Tests/conf.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-30171
Updated the default value of Rate Limit Retry Count parameter and rate_limit_retry_count argument of !ip command from 3 to 0.

update the retry count to 0

---

Packs/ctf01/pack_metadata.json

fixes: N.A.
Added Cortex XDR to be a mandatory dependency for Capture the Flag 01 pack

Added Cortex XDR to be mandatory dependency for Capture the flag 01 pack

---

Packs/NationalVulnerabilityDatabaseFeed/.pack-ignore
Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/CONTRIBUTORS.json
Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/NationalVulnerabilityDatabaseFeed.py
Packs/NationalVulnerabilityDatabaseFeed/Integrations/NationalVulnerabilityDatabaseFeed/NationalVulnerabilityDatabaseFeed.yml
Packs/NationalVulnerabilityDatabaseFeed/ReleaseNotes/1_0_4.md
Packs/NationalVulnerabilityDatabaseFeed/pack_metadata.json

update and align the fields for NVD into CVE default layout and fix the cvss field which had json blob in it to extract teh base score, align with security PANW security advisories integration
Update and align the fields for NVD into CVE default layout and fix the cvss field which had json blob in it to extract the base score, align with security PANW security advisories integration
cvsstable, cvss, cvssversion now written accurately

update nvd fields

---

Packs/CommonScripts/ReleaseNotes/1_12_47.md
Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.py
Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.yml
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9015)
Fixed an issue that in the [latest version](https://github.com/demisto/content/pull/31016) (1.12.46) the *outputs* changed incorrectly.

[IsIntegrationAvailable] Fix the Outputs

---

Packs/CommonTypes/IncidentFields/incidentfield-External_Severity.json
Packs/CommonTypes/ReleaseNotes/3_3_93.md
Packs/CommonTypes/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-30432)
Make the `External Severity` field to be searchable in XSOAR.

External severity -  change to be searchable 

---

Packs/IsItPhishing/Integrations/IsItPhishing/IsItPhishing.js
Packs/IsItPhishing/Integrations/IsItPhishing/IsItPhishing.yml
Packs/IsItPhishing/ReleaseNotes/1_0_4.md
Packs/IsItPhishing/pack_metadata.json
Packs/Pipl/Integrations/Pipl/Pipl.js
Packs/Pipl/Integrations/Pipl/Pipl.yml
Packs/Pipl/ReleaseNotes/1_0_9.md
Packs/Pipl/pack_metadata.json
Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT.js
Packs/isight/Integrations/FireEyeISIGHT/FireEyeISIGHT.yml
Packs/isight/ReleaseNotes/1_0_5.md
Packs/isight/pack_metadata.json

fixes: [CIAC-9047](https://jira-dc.paloaltonetworks.com/browse/CIAC-9047)

Add support for is array for rep commands js

---

Packs/F5APM/README.md

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9078
Removed the XSIAM tags in the README file since it brokes the marketplace build and it's redundant because the entire pack is XSIAM only.

F5 APM Remove XSIAM tags

---

Packs/CommonScripts/ReleaseNotes/1_12_54.md
Packs/CommonScripts/Scripts/IsEmailAddressInternal/IsEmailAddressInternal.js
Packs/CommonScripts/Scripts/IsEmailAddressInternal/IsEmailAddressInternal.yml
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9069)
Fixed an issue where when the **domain** argument received a single value (rather than a list) it did not work as expected (issue was introduced in 1.12.53).

[IsEmailAddressInternal] Fix an issue with **domain** argument

---

Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py

* Fixed an issue where exceptions from `requests` module would not be caught, leading the taxii2-server test to fail on the first port.
* Added additional ports for testing

[e2e xsoar-saas] - fix issue with taxii2-server test

---

Packs/Gmail/Integrations/Gmail/Gmail.py
Packs/Gmail/Integrations/Gmail/Gmail.yml
Packs/Gmail/Integrations/Gmail/README.md
Packs/Gmail/ReleaseNotes/1_3_15.json
Packs/Gmail/ReleaseNotes/1_3_15.md
Packs/Gmail/pack_metadata.json

fixes: [XSUP-30923](https://jira-dc.paloaltonetworks.com/browse/XSUP-30923)

Fix gmail get mail context output

---

Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Incident_Enrichment.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_7.md
Packs/CrowdStrikeFalcon/pack_metadata.json
Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_Malware_-_Incident_Enrichment.yml
Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_20.md
Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json

fixes: N.A.
I specified an integration brand for MDE and CS Falcon (as shown on Cortex XDR PB).
The main reason is to avoid PB failing in case another integration implements `!endpoint` and keeps on failing as we are checking for an endpoint ID (which only appears in the same EDR that we are using).

Malware Investigation and Response -  Added specification for integration brand for the  !endpoint command.

---

Packs/DemistoRESTAPI/ReleaseNotes/1_3_41.md
Packs/DemistoRESTAPI/Scripts/GetIncidentTasksByState/GetIncidentTasksByState.js
Packs/DemistoRESTAPI/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9172
Changed `includes` to `indexOf` as it is not supported in ecma 5 which means it will not work in xsoar 6.9

Fix js get incident tasks by state

---

Packs/FiltersAndTransformers/ReleaseNotes/1_2_45.md
Packs/FiltersAndTransformers/Scripts/IfElif/IfElif.py
Packs/FiltersAndTransformers/Scripts/IfElif/IfElif.yml
Packs/FiltersAndTransformers/pack_metadata.json

Currently, if more args than specified in the yml would be added to the If-Elif transformer, it would throw an error as the args are unpacked directly into the `ConditionParser` constructor and it has only the yml args a parameters.
To solve this, this PR adds the parameter `**_` to the constructor so that the unexpected args can be safely ignored.

Fix "unexpected keyword argument" Error

---

Packs/SentinelOne/Integrations/SentinelOne-V2/README.md
Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
Packs/SentinelOne/ReleaseNotes/3_2_14.md
Packs/SentinelOne/pack_metadata.json

Currently, it is not possible to retrieve threats regardless of their status (resolved/unresolved/in_progress) with the command ***sentinelone-get-threats***.
This PR adds the *include_resolved_param* argument to the command ***sentinelone-get-threats*** which allows to ignore the *resolved* argument in order to get threats regardless of their status.

Add argument include_resolved_param to sentinelone-get-threats

---

Packs/Armis/Integrations/Armis/Armis.py
Packs/Armis/Integrations/Armis/Armis.yml
Packs/Armis/Integrations/Armis/Armis_test.py
Packs/Armis/ReleaseNotes/1_1_10.md
Packs/Armis/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9187
reported https://github.com/demisto/content-docs/issues/1439
Added support for base URL without `api/v1` suffix.

Armis fix url suffix

---

Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_First_SSO_Access.yml
Packs/CortexXDR/ReleaseNotes/6_0_10.md
Packs/CortexXDR/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8333)
Fix for The "Cortex XDR - First SSO Access" playbook. The playbook fails when there is no integration to enrich IPs enabled.

First sso fix ip task

---

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_34.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

This is a quick bug fix for the recent additions to the EWS_0365 which added the rfc compliant specifications along with the header deduplication prevention.
We just had one email come through where the DATE header value stored in the O365 object was different than the value stored in the EML bytes. 
When parsing using the python email library, since when using the SMTP and SMTPUTF8 policies, some  headers have specific restrictions on how many can be included. DATE has a restriction of 1, and since the header deduplication works off key/value …

Ews header deduplication bug

---

.github/workflows/pre-commit.yml

Since v1.25.0 is a broken release, and pre-commit until v1.25.0 uses the latest release on pypi, we have to manually set it to the latest good release.
This should be removed after v1.25.1 is released.

Workaround for pre-commit job

---

.hooks/pre-commit
.pre-commit-config_template.yaml
Tests/scripts/script_runner.py

* fix issue with script runner when the script errors resulted error code 0 (not pytest failures, but failures executing the script)
* Remove __init__ folders from content (if we want to add `__init__`, we need to add in all of them, since those packages has priority over others.
* Add commit mode to the template

[pre-commit] remove __init__folders, fix script_runner and add commit mode

---

Packs/ElasticsearchMonitoring/pack_metadata.json

fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9242)
Move the elasticsearch monitoring to xsoar on prem only

moving the pack to on_prem support only

---

Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2_test.py
Packs/Netskope/ReleaseNotes/3_3_2.md
Packs/Netskope/pack_metadata.json

Fixed an issue where due to a typo, the `alert_query` argument value was not used when provided. 
fixes: [XSUP-31727](https://jira-dc.paloaltonetworks.com/browse/XSUP-31727)

NetskopeAPIv2 `alert_query` argument

---

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_39.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-31533
Deprecating the "format" argument for  "wildfire-upload-url" and "wildfire-upload-file-url" commands, since it was added by us by mistake.

deprecating the format argument

---

Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py

* Fixed an issue where the e2e taxii2 server didn't break when test is complete

[xsoar-saas-e2e-taxii2] - break when test is complete

---

Packs/MicrosoftGraphMail/Classifiers/classifier-Microsoft_Graph_Mail_Mapper.json
Packs/MicrosoftGraphMail/ReleaseNotes/1_6_2.md
Packs/MicrosoftGraphMail/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-30182
Fixed an issue where in some cases multiple **Email BCC** value was processed as an array of values.

Fixing an error of Bcc values was processed as an array of values

---

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
Packs/HatchingTriage/ReleaseNotes/1_0_16.md
Packs/HatchingTriage/pack_metadata.json

[link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31229)
- Fixed an issue where using the integration could potentially cause xsoar to be overloaded. That happens because the `get_pack_version` pulls all the integration/script metadata which can be quite large.

[Hatching Triage] - remove usage of get pack version

---

Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9446)
Now the ExtractAttackPattern script is in the Common Scripts pack, and since it uses an integration command from the MITER ATT&CK pack, it creates a circular dependency between the two packs.
That's why we make MITER ATT&CK optional in Common Scripts dependency.

[Common Scripts] Make MITRE ATT&CK optional dependency

---

.github/workflows/pre-commit.yml

We can now unite the pre-commit to one workflow since we can now can exclude hooks from running on community packs.

[Pre-Commit] Run pre-commit in community PR

---

Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py

Adding `freeze_time("2024-01-15 17:00:00 UTC")` to a few time-related tests
fixes: [CIAC-9473](https://jira-dc.paloaltonetworks.com/browse/CIAC-9473)

add `freeze_time` on time-related UT

---

Tests/scripts/infrastructure_tests/lock_cloud_machines_test.py
Tests/scripts/lock_cloud_machines.py

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9477
As a result of changes in https://github.com/demisto/content/pull/32098, the _Infrastructure testing_ job is failing in the _Run Unit Testing And Lint_ flows. An example can be seen in [this job failure](https://app.circleci.com/pipelines/github/demisto/content/337496/workflows/aa59b79b-cf47-475a-b6f2-002627c40556/jobs/737300?invite=true#step-119-2376_99).
This PR is a fix for this issue by moving the Slack token env var retrieval from global to local method scope.

Move Slack Token/Channel to Local method

---

Packs/CommonScripts/ReleaseNotes/1_13_20.md
Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.py
Packs/CommonScripts/Scripts/DBotUpdateLogoURLPhishing/DBotUpdateLogoURLPhishing.yml
Packs/CommonScripts/pack_metadata.json

Change docker image to an image of python 3.9 since the model was trained on python 3.9 so we can't use python3.10.
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32123?filter=-1

Update dockerimage in DBotUpdateLogoURLPhishing.yml

---

Packs/PrismaCloud/LayoutRules/Prisma_Cloud_V2.json
Packs/PrismaCloud/ReleaseNotes/4_2_17.md
Packs/PrismaCloud/pack_metadata.json

https://jira-dc.paloaltonetworks.com/browse/CRTX-103516
Fix to the following bug:
https://jira-dc.paloaltonetworks.com/browse/CRTX-103516

Prismalayoutrulefix

---

Tests/Marketplace/versions-metadata.json

Updated the versioned core packs
from the prepare-testing-bucket step

lock core packs

---

Packs/CommonScripts/ReleaseNotes/1_13_25.md
Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
Packs/CommonScripts/pack_metadata.json

As XSOAR SAAS ommits from the context keys with empty values as XSIAM, we need to handle XSOAR SAAS the same we do as XSIAM
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32518

[SetGridField] Handle XSOAR SAAS correctly

---

Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.yml
Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI_test.py
Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_17.md
Packs/CrowdStrikeOpenAPI/pack_metadata.json

Fixing an issue where the `cs-update-rulesv1` command would not run properly, by wrapping the payload with a list ([API expects](https://github.com/CrowdStrike/falconpy/blob/3edfb2b5fb98fc939937942369c58d53d8223cd1/src/falconpy/_payload/_recon.py#L56
) a list of dictionaries)
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32756

Crowdstrike OpenAPI `cs-update-rulesv1` fix

---

.pre-commit-config_template.yaml
poetry.lock
pyproject.toml

* Log file path (can be set by the `--log-file-path` flag or the `DEMISTO_SDK_LOG_FILE_PATH` environment variable) can now only accept directory values. Setting it to a file path is no longer supported (file name is now constantly `demisto_sdk_debug.log` and cannot be changed). The path will now be automatically generated if it doesn't exist. [#3912](https://github.com/demisto/demisto-sdk/pull/3912)
* Log files will now be saved by default to `$HOME/.demisto-sdk/logs`. This behavior can be overridden by the `--log-file-path` flag, or the `DEMISTO_SDK_LOG_FILE_PATH` environment variable. [#3912](https://github.com/demisto/demisto-sdk/pull/3912)
* Added warning when running on Windows (not supported) [#3950](https://github.com/demisto/demisto-sdk/pull/3950)
* Fixed an issue where the …

demisto-sdk-release 1.26.0

---

.gitlab/ci/.gitlab-ci.sdk-nightly.yml

relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-9556
On https://github.com/demisto/content/pull/32403 an issue was introduced where the `demisto-sdk-nightly:trigger-slack-notify` step was added to unrelated pipelines. This PR fixes this issue.
Link to a "Build Machine Cleanup" pipeline from before the changes:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/789797
Link to a "Build Machine Cleanup" pipeline following the changes:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/790605
SDK Nightly following the changes (job should be added for this pipeline)
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/790656
Content nightly following the changes:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/790660 …

Fix SDK Slack Notifier Being Triggered For Non-relevant Pipelines

---

nightly_ruff.toml
pyproject.toml

fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9676)
Adding the W291-trailing-whitespace rule to both `pyproject.toml`, and `nightly_ruff.toml`.
Blocked by https://github.com/demisto/content/pull/32855

[Ruff] Added The W291-trailing-whitespace Rule

---

Packs/Tanium/Integrations/Tanium_v2/README.md

This pr is fixing [this](https://github.com/demisto/content/pull/32679) contribution.

update tanium v2 readme

---

Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector.py
Packs/OktaAuth0/Integrations/OktaAuth0EventCollector/OktaAuth0EventCollector.yml
Packs/OktaAuth0/ReleaseNotes/1_0_2.md
Packs/OktaAuth0/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-33662)

[XSUP-33662] Fix Okta Auth0 test-module

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/2_5_54.md
Packs/ServiceNow/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-33532
_Problem_:
In the `upload-file` command there is redundant `copy` to copy the file from fileEntry path to local 
this cause an exception when the file name contain invalid characters (especial `/`).
_Fix_:
Remove the redundant code that cause the bug.

ServiceNowV2: fix bug in upload-file command

---

Packs/Base/ReleaseNotes/1_33_35.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fix base client execution metrics

---

Packs/OpenCTI/.pack-ignore
Packs/OpenCTI/Integrations/OpenCTI/README.md
Packs/OpenCTI/ReleaseNotes/1_0_10.md
Packs/OpenCTI/pack_metadata.json

relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-33614
Update documentation to specify that versions 5.12.0 of OpenCTI are not currently supported.

[OpenCTI] Update Documentation

---

Tests/docker_native_image_config.json

Update native image tag to `demisto/py3-native:8.6.0.88298`.
After support for `openpyxl` and `python-pptx` packages was added in this PR https://github.com/demisto/dockerfiles/pull/24500, we're upgrading the native image reference to the latest version.

[Native Image] Update native image tag

---

Tests/sdk_release/create_sdk_pr.py

moved the sleep(10) to the beginnig of the while loop to get the workflow status, example for failure pipeline:
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/4865011

Fix retrieve the SDK changelog workflow status while loop

---

Tests/docker_native_image_config.json

Upgrade native:candidate to `demisto/py3-native:8.6.0.88298`.
This upgrade is to handle recently added libraries in native:8.6.

[Native Image] Upgrade native:candidate to 8.6

---

Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8659)
Test playbook `CrowdStrike_Falcon_X_-Test-Detonate_File` is failing nightly because it downloaded a PDF file that no longer exists.
This PR changes the download file to a file in this repo that won't be removed.

Fix CS Falcon X TPB

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/EDL.yml
Packs/EDL/Integrations/EDL/EDL_test.py
Packs/EDL/ReleaseNotes/3_2_20.md
Packs/EDL/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-33964)
Fixed an issue where `demisto.error` uses a local variable that can be undefined.

[EDL] get_indicators_to_format - fix demisto.error

---

Packs/CTIX/Integrations/CTIX/CTIX.py
Packs/CTIX/Integrations/CTIX/CTIX.yml
Packs/CTIX/Integrations/CTIX/CTIX_test.py
Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
Packs/CTIX/ReleaseNotes/2_2_16.md
Packs/CTIX/pack_metadata.json

I also ran all of the pre-commit hooks and resolved all of those issues.
The main goal of this PR is to make the `ctix-allowed-iocs` and `ctix-get-allowed-iocs` compatible with CTIX 3.6 as the endpoint used by those two commands changed in that version. For both commands, we'll make a call to the new endpoint first, and if that returns a 404 (which it will if the user has CTIX < 3.6), make a call to the previous endpoint.
The rest of the changes are all done by running the pre-commit hooks.

Added Compatibility with new Allowed Indicator Module in CTIX 3.6

---

Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3.yml
Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3_README.md
Packs/CommonPlaybooks/ReleaseNotes/2_6_19.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9929
I added a new playbook input named "AccountDomain". It provides the user's domain name for the account enrichment sub-playbook.

Fix for the 'Entity Enrichment - Generic v3' playbook

---

Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.yml
Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeComplianceReportButton/CreatePrismaCloudComputeComplianceReportButton.yml
Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeLink/CreatePrismaCloudComputeLink.yml
Packs/PrismaCloudCompute/Scripts/TagIndicatorButton/TagIndicatorButton.yml
Packs/QRadar/Scripts/QRadarFetchedEventsSum/QRadarFetchedEventsSum.yml
Packs/QRadar/Scripts/QRadarMagnitude/QRadarMagnitude.yml
Packs/QRadar/Scripts/QRadarPrintAssets/QRadarPrintAssets.yml
Packs/QRadar/Scripts/QRadarPrintEvents/QRadarPrintEvents.yml
Packs/SplunkPy/Scripts/SplunkShowAsset/SplunkShowAsset.yml
Packs/SplunkPy/Scripts/SplunkShowIdentity/SplunkShowIdentity.yml

Update the `demisto/python3` docker image of the following integration/scripts which coverage rate of `75-100-Nightly`%:
```
Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.yml
Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeComplianceReportButton/CreatePrismaCloudComputeComplianceReportButton.yml
Packs/PrismaCloudCompute/Scripts/CreatePrismaCloudComputeLink/CreatePrismaCloudComputeLink.yml
Packs/PrismaCloudCompute/Scripts/TagIndicatorButton/TagIndicatorButton.yml
Packs/QRadar/Scripts/QRadarPrintAssets/QRadarPrintAssets.yml
Packs/QRadar/Scripts/QRadarFetchedEventsSum/QRadarFetchedEventsSum.yml
Packs/QRadar/Scripts/QRadarPrintEvents/QRadarPrintEvents.yml …
```

Update `demisto/python3` 75-100-Nightly coverage rate

---

Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.py
Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml

Update the `demisto/py3-tools` docker image of the following integration/scripts which coverage rate of `75-100-Nightly`%:
```
Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml
```

Update `demisto/py3-tools` 75-100-Nightly coverage rate

---

Packs/MicrosoftExchangeOnline/Scripts/CreateCertificate/CreateCertificate.yml

Update the `demisto/pwsh-exchange` docker image of the following integration/scripts which coverage rate of `75-100-Nightly`%:
```
Packs/MicrosoftExchangeOnline/Scripts/CreateCertificate/CreateCertificate.yml
```

Update `demisto/pwsh-exchange` 75-100-Nightly coverage rate

---

Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml

Update the `demisto/sane-pdf-reports` docker image of the following integration/scripts which coverage rate of `75-100-Nightly`%:
```
Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
```

Update `demisto/sane-pdf-reports` 75-100-Nightly coverage rate

---

Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml

Update the `demisto/googleapi-python3` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
```

Update `demisto/googleapi-python3` 50-100-Non-Nightly coverage rate

---

Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.py
Packs/Symantec_Messaging_Gateway/ReleaseNotes/1_0_17.md
Packs/Symantec_Messaging_Gateway/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-33687
After upgrading the docker image to `demisto/bs4-py3:1.0.0.86348`
the following ssl error is occurred 
`SSLV3_ALERT_HANDSHAKE_FAILURE`
this comes from the `urllib3` version installed in that docker image (2.1.0)
fix:
instead of call `requests.request` directly , use the `BaseClient` session, which contain a workaround already
@JudahSchwartz FYI

SymantecMessagingGateway: fix an ssl connection error

---

Packs/CommonScripts/ReleaseNotes/1_14_18.md
Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
Packs/CommonScripts/pack_metadata.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/XSUP-34973)
Fixing the ability to pass in comma-separated list to `key` which was broken in the last update.

fixing csv key passing

---

.gitlab/ci/.gitlab-ci.global.yml

This line could be removed after the new sdk will be released, when we will skip empty packs

workaround for mypack bug

---

Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py
Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml

Update the `demisto/taxii-server` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
```

Update `demisto/taxii-server` 0-50 coverage rate

---

Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson.yml

Update the `demisto/python3` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/Anomali_ThreatStream/Scripts/ThreatstreamBuildIocImportJson/ThreatstreamBuildIocImportJson.yml
```

Upgrade image

---

Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/O365DefenderSafeLinksSingleUser.yml
Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml

Update the `demisto/powershell-ubuntu` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/O365DefenderSafeLinksSingleUser.yml
Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml
```

Update `demisto/powershell-ubuntu` 0-50 coverage rate

---

Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.yml

Update the `demisto/powershell-teams` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/MicrosoftTeams/Scripts/ConfigureAzureApplicationAccessPolicy/ConfigureAzureApplicationAccessPolicy.yml
```

Update `demisto/powershell-teams` 0-50 coverage rate

---

Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml

Update the `demisto/google-k8s-engine` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
```

Update `demisto/google-k8s-engine` 0-50 coverage rate

---

Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment.yml

Update the `demisto/exodusintelligence` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/ExodusIntelligence/Integrations/ExodusVulnerabilityEnrichment/ExodusVulnerabilityEnrichment.yml
```

Update `demisto/exodusintelligence` 50-100-Non-Nightly coverage rate

---

Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_58.md
Packs/MicrosoftCloudAppSecurity/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-35352)
Fixed an issue in **Fetch Incidents** when the *Incident severity* or *Incident resolution status* parameters was not provided in **XSOAR 8**.

[MicrosoftCloudAppSecurity] Fix the fetch in XSOAR 8

---

Packs/RedCanary/Integrations/RedCanary/RedCanary.py
Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
Packs/RedCanary/ReleaseNotes/1_1_20.md
Packs/RedCanary/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-35357
If a detection not contain relationships, the command failed.
**added test before fix:**
**after fix:**

RedCanary: fix detection without relationship

---

Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
Packs/Tanium/ReleaseNotes/1_0_31.md
Packs/Tanium/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-35421
credentials retrieved as null when not used at all, so added default value to the get method

Xsup 35421 fix nonetype

---

.gitlab/ci/.gitlab-ci.global.yml

* Returning exit code 0 in pre-commit so the build will not be spammed for now
* If we `pre-commit -a`, we need to create the content graph in advance so we will not use too much resources in the command (as we parse all integrations scripts and all the packs seperately).

Pre-Commit - graph fix and make exit code 0

---

Packs/Base/ReleaseNotes/1_33_45.md
Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
Packs/Base/pack_metadata.json

fixes: XSUP-34767
we pass the flag as an argument to os command thus we need to pass it as string and not bool.
Sane app did not handle the arg as bool correctly hence the flags was not enforced

XSUP-34767 - treat utfbom8 flag as string and not bool

---

Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.yml

Update the `demisto/argus-toolbelt` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/mnemonicMDR/Integrations/ArgusManagedDefence/ArgusManagedDefence.yml
```

Update `demisto/argus-toolbelt` 50-100 coverage rate

---

Packs/Tufin/Integrations/Tufin/Tufin.yml

Update the `demisto/netutils` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/Tufin/Integrations/Tufin/Tufin.yml
```

Update `demisto/netutils` 0-50 coverage rate

---

Packs/Infocyte/Integrations/Infocyte/Infocyte.yml

Update the `demisto/pwsh-infocyte` docker image of the following integration/scripts which coverage rate of `0-50`%:
```
Packs/Infocyte/Integrations/Infocyte/Infocyte.yml
```

Update `demisto/pwsh-infocyte` 0-50 coverage rate

---

Packs/AWS-EC2/ReleaseNotes/1_4_5.md
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts.py
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts.yml
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts_test.py
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/README.md
Packs/AWS-EC2/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10153)
Added the argument `exclude_accounts` to support a list of accounts to exclude in the `AWS - Organizations` instance configuration.

Exclusion List for AWSSyncAccounts

---

Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml

Update the `demisto/py3-tools` docker image of the following integration/scripts which coverage rate of `75-100-Nightly`%:
```
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml
Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
```

Update `demisto/py3-tools` 75-100-Nightly coverage rate 

---

Packs/StringSifter/Scripts/StringSifter/StringSifter.yml

Update the `demisto/stringsifter` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/StringSifter/Scripts/StringSifter/StringSifter.yml
```

Update demisto/stringsifter 50-100-Non-Nightly coverage rate 

---

Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml

Update the demisto/xsoar-tools docker image of the following integration/scripts which coverage rate of `0-50%`:

Update Demisto/XSOAR- Tools 0-50 coverage rate

---

Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml

Update the `demisto/xsoar-tools` docker image of the following integration/scripts which coverage rate of `50-100-Non-Nightly`%:
```
Packs/ContentManagement/Scripts/CommitFiles/CommitFiles.yml
```

Update `demisto/xsoar-tools` 50-100-Non-Nightly coverage rate

---

Packs/Reco/Integrations/Reco/Reco.py
Packs/Reco/Integrations/Reco/Reco.yml
Packs/Reco/Integrations/Reco/Reco_test.py
Packs/Reco/ReleaseNotes/1_2_1.md
Packs/Reco/pack_metadata.json

reco.py: change validate api key endpoint

---

.pre-commit-config_template.yaml

Do not run ruff hooks in parallel, as the ruff runs on the entire repo extremely quick (1 second)

[pre-commit] - do not run ruff with parelleisem

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_4.md
Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_5.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-35743)
Added a new argument **polling_timeout** to the **cs-falcon-rtr-retrieve-file** command to set the polling timeout.

Crowdstrike: added argument polling_timeout to cs-falcon-rtr-retrieve-file command

---

Packs/CaseManagement-Generic/ReleaseNotes/1_4_7.md
Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.py
Packs/CaseManagement-Generic/Scripts/CloseLinkedIncidentsPostProcessing/CloseLinkedIncidentsPostProcessing.yml
Packs/CaseManagement-Generic/pack_metadata.json

fixes: [XSUP-35719](https://jira-dc.paloaltonetworks.com/browse/XSUP-35719)
Fixed an issue where the `!CloseLinkedIncidentsPostProcessing` command raised an error when an incident's `closeNotes` field was empty.
**Before:**
**After:**

Fix CloseLinkedIncidentsPostProcessing Error

---

Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.py
Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
Packs/AWS-SNS-Listener/ReleaseNotes/1_0_1.md
Packs/AWS-SNS-Listener/pack_metadata.json

Bump docker version.
Fixed an issue where subscription notification API return result was not set to response type but had a raise_for_status call for it.

Fix subscription notification.

---

Packs/PhishingURL/ReleaseNotes/1_1_13.md
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
Packs/PhishingURL/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36113)
Fixed an issue in which an error was raised when more than one URL failed in the `rasterise` command.

Fix DBotPredictURLPhishing failing on rasterize errors

---

Packs/CommonScripts/ReleaseNotes/1_14_36.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36119)

ParseEmailFiles: Fixed an issue where same eml files are not recognized

---

Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py
Packs/FortiSIEM/Integrations/FortiSIEMV2/test_data/triggered_events.json
Packs/FortiSIEM/ReleaseNotes/2_0_35.md
Packs/FortiSIEM/pack_metadata.json

fixes: [link to the issue
](https://jira-dc.paloaltonetworks.com/browse/XSUP-36299)
Fixing an issue where the `fetch-incident` command fails to parse the response time field.

XSUP-36299 FortiSIEM Fix Fetch Incident

---

Packs/CommonScripts/ReleaseNotes/1_14_37.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: [XSUP-36063](https://jira-dc.paloaltonetworks.com/browse/XSUP-36063)
Added support to Apple HFS file type.

Update parse emails files docker image

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
Packs/CortexXDR/ReleaseNotes/6_1_30.md
Packs/CortexXDR/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-36389
On specific cases, where the ms in the time parsing is starting with many 0, the parser doesn't return the ms and therfore the splitting doesn't change the value, leading to the last_update_without_ms to contain the timezone offset. As we do not use this offset, removed it from the return value. 
failing test

added setting to dateparser

---

Packs/ThreatConnect/Integrations/ThreatConnectV3/README.md
Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
Packs/ThreatConnect/ReleaseNotes/3_1_6.md
Packs/ThreatConnect/pack_metadata.json

fixes: [XSUP-36658](https://jira-dc.paloaltonetworks.com/browse/XSUP-36658)
Added the missing argument `owner` to the `add-indicator` command

ThreatConnect add indicator owner argument fix

---

Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/AnsibleKubernetes_description.md
Packs/AnsibleKubernetes/Integrations/AnsibleKubernetes/README.md
Packs/AnsibleKubernetes/ReleaseNotes/1_0_7.md

…n Service Account are created. Minor update to manually create secret to get token.
Changed the following description files to affect this change
Changes to be committed:
modified:   Integrations/AnsibleKubernetes/AnsibleKubernetes_description.md
modified:   Integrations/AnsibleKubernetes/README.md
new file:   ReleaseNotes/1_0_7.md

Starting Kubernetes 1.24, Secrets are not automatically created. Add manually create method to description files

---

.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10425)
It seems that the Token used in the following GitHub actions is revoked which causes them to fail:
-Manage Contribution Board - Daily
-Manage Contribution Board - Hourly
As discussed with @glicht it is better to use the GitHub default token. 
In this PR I:
1. Replaced the old token with the github default token.
2. Set the version of the github automation package to the last version for (best practice).

Change Token in Contributions Board Github actions

---

Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/README.md
Packs/AWS-SNS-Listener/ReleaseNotes/1_0_3.md
Packs/AWS-SNS-Listener/pack_metadata.json

Current status all long running integrations (except for EDL) is that they do not get a long running port assigned automatically on XSOAR8 / XSIAM.
This is in constrast to the the documentation.
This PR fixes the documentation for AWS-SNS-Listener.
Until server will fix the auto port allocation on their side.

Aws sns listener documentation edits

---

.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

relates: [CIAC-10425](https://jira-dc.paloaltonetworks.com/browse/CIAC-10425). 
The contributions board cron jobs (Manage Contribution Board - Daily, Manage Contribution Board - Hourly) have stopped running as described in the above-mentioned issue. 
In this PR I did the following: 
1. Changed the used token from the default Github Token to a more powerful token (reason explained in the issue).
2. Removed the permission section (cause it is relevant only for the Github Token which isn't used anymore).

Fix Contributions Board Cron Jobs

---

pyproject.toml

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10461) to the issue
Add `demistomock` file to the `extend-exclude` config in `pyproject.toml`

[demistomock] Ruff Exclude `demistomock`

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/ReleaseNotes/1_5_41.md
Packs/AzureSentinel/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-37051)
Fixes mirroring issue when closing a Microsoft Sentinel incident with classification 'BenignPositive'.
Without this fix the following error can be observed:
`Error in Microsoft Sentinel outgoing mirror for incident <ID>. Error message: [BadRequest 400] classification 'BenignPositive' must have classificationReason.`
Will also add here that it seems puzzling that the classificationReason from the outgoing mapper is not used. Maybe there is a reason for it, so I decided not to change it here. …

MS Sentinel - Added missing classification reason for BenignPositive classification when closing incident

---

Packs/SentinelOne/ModelingRules/SentinelOneModelingRules/SentinelOneModelingRules.xif
Packs/SentinelOne/ReleaseNotes/3_2_24.md
Packs/SentinelOne/pack_metadata.json

Resolves runtime errors seen on ingestion
`unable to add field xdm.target.process.integrity_level: runtime error on to_integer (cant convert "medium" to int)`
Updating the data model rule to properly handle the target process integrity level. which per [the standard](https://docs-cortex.paloaltonetworks.com/r/Cortex-Data-Model-Schema-Guide/xdm.target?section=xdm.target.process.integrity_level) needs to be a Number, but is coming up as a human-readable level name in the logs. This handles properly, and gracefully falls back if the logs ever indeed change to containing a numeric value.

update data modeling rule to properly handle integrity level

---

Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.py
Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2_test.py
Packs/FeedNVDv2/ReleaseNotes/1_0_2.md
Packs/FeedNVDv2/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-37575
When KEV was requested by the user a malformed URL was created which caused a timeout. 
Fixed the formation of the URL.

NIST NVD 2.0 - KEV causing feed to timeout.

---

Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py

Disabling the problematic unit test in CommonServerPython until it will be fixed in [CIAC-10650](https://jira-dc.paloaltonetworks.com/browse/CIAC-10650).

Disable problematic CSP UT

---

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/README.md

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-9574) to the issue
Updated the readme file to include the permission required to use the "shared mailbox."

[Microsoft Graph Mail Single User] Update Docs for Shared Mailbox

---

Tests/demistomock/demistomock.py

fixes: None
related: https://github.com/demisto/content/pull/34620
Adding timeout parameter since it was added to the function by server, and also so the related pr won't fail on 
`Unexpected keyword argument 'timeout' `

adding timeout param

---

Utils/github_workflow_scripts/handle_external_pr.py

CIAC-8513 Notify when there is more than 1 PR that was contributed by the same author - addition to find internal PR's as well
We found that internal PR's are not found by the solution here [PR](https://github.com/demisto/content/pull/33870),
as Internal PR's are opened by content-bot, they weren't found by the handle_external_pr and missed and not counted.
Added the option to look also for PR's opened by content-bot
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8513)

CIAC-8513 Notify when there is more than 1 PR that was contributed by the same author - addition to find internal PR's as well

---

Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
Packs/JoeSecurity/Integrations/JoeSecurityV2/README.md
Packs/JoeSecurity/ReleaseNotes/1_1_21.json
Packs/JoeSecurity/ReleaseNotes/1_1_21.md
Packs/JoeSecurity/pack_metadata.json

The `submission_ids` argument of the `joe-submission-info` command is now required because the command's purpose is to retrieve information for a specific ID. Without this argument, the command cannot function as intended. This design ensures that the necessary information is not overlooked.

Joe-submission-info command Update

---

Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinksSingleUser/O365DefenderSafeLinksSingleUser.yml
Packs/Microsoft365Defender/ReleaseNotes/4_5_27.md
Packs/Microsoft365Defender/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-37913)
Safelink single-user is being deprecated because Microsoft no longer allows single user authentication

Deprecate O365 Defender SafeLinks - Single User

---

.pre-commit-config_template.yaml

Skipping the autopep8 on pre-commit nightlies due to an issue with this step.

skipping autopep8 on nightlies

---

Packs/CommonScripts/ReleaseNotes/1_15_11.md
Packs/CommonScripts/Scripts/ReadPDFFileV2/README.md
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38422
Fixed an issue where the pdf file was no open in binary mode before extracting data.

ReadPDFFileV2 open in binary mode

---

.github/content_roles.json
.github/github_workflow_scripts/handle_external_pr.py
.github/github_workflow_scripts/utils.py
.github/github_workflow_scripts/utils_test.py

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-10855
Retrieve the `content_roles.json` from `demisto/content` `master` blob instead of from the filesystem. If we can't get it from the `master` blob, we use the one from the filesystem as a fallback.
This is to fix an issue where contributions coming from forks have an outdated `content_roles.json` file and incorrectly assigns PR reviewers.

Get Content Roles from Blob

---

.github/github_workflow_scripts/create_internal_pr.py

fixes:https://jira-dc.paloaltonetworks.com/browse/CIAC-10855
In continuation of https://github.com/demisto/content/pull/34932, update to use `get_content_roles` in the internal PR.

Use Content Roles in Internal PR

---

Tests/docker_native_image_config.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10936
Remove ZipFile from skip list. The package was originally ignored because of an issue with pyminizip as described in CIAC-1036. Later, pyminizip was replaced altogether so ignoring ZipFile is no longer necessary. 

remove zipfile from native ignore

---

Packs/TIM_Processing/Playbooks/playbook-TIM_-_Process_Indicators_Manual_Review.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Review_Indicators_Manually.yml
Packs/TIM_Processing/ReleaseNotes/1_1_26.md
Packs/TIM_Processing/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38796
Fixes an issue with the playbook failing due to wrong query and the subplaybook context not being shared globaly.

XSOAR TIM - Fix to manual indicator review playbook

---

Packs/Lacework/.pack-ignore
Packs/Lacework/ReleaseNotes/2_0_0.md

Fixing the last RN of Lacework, since it contained a mapper header that doesn't exist in the classifier folder.

RN- removing invalid header(content item doesn't exist)

---

Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-pyEWS_Test.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10696
pyews tpb fails since it use send-mail of other configured integrations, added EWS v2 for each command

pyews test fails - add EWS v2 to commands

---

Tests/docker_native_image_config.json

fixes: [CIAC-11000](https://jira-dc.paloaltonetworks.com/browse/CIAC-11000)
relates: [CIAC-8493](https://jira-dc.paloaltonetworks.com/browse/CIAC-8493)
Unskip Ping from the native image, since skipping it in https://github.com/demisto/content/pull/29576 was unnecessary.

[Native Image & Ping] Remove From The Ignore List

---

Tests/docker_native_image_config.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11003) to the issue
The reason why the Github Feed was in the ignore list is because we added 2 new libraries, yara-python and plyara, to the native image.
Now, after [updating](https://github.com/demisto/content/pull/34767) the candidate image, 
these libraries are present on the candidate image (py3-native:8.6.0.98251),
so we can remove the GitHub Feed from the ignore list of the candidate image only.

[Native & Github Feed] Remove From The Ignore List Of `candidate` Image

---

.github/github_workflow_scripts/autobump_rn.py
.github/workflows/autobump_rn.yml

Added filtering so that the autoBump does not collect PRs that are defined as draft
An example PR that didn't need to be collected and crashed the bot run: https://github.com/demisto/content/pull/34228

avoid collect draft prs in autobump

---

Packs/Base/ReleaseNotes/1_34_20.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10853)
Update the request timeout for the **generic_http_request** function to 60 seconds.

[CSP] Increasing timeout for generic_http_request to 60 seconds

---

.github/github_workflow_scripts/handle_external_pr.py

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8513)
After reviewer done with review - github "requested_reviewers" is empty, until re-review is requested.
So need to switch the lookup for assignees and not reviewers
The fix was tested in this [PR](https://github.com/demisto/content/pull/34754) and this [check](https://github.com/demisto/content/pull/34754/checks) that was opened to the branch of this PR

Fix issue when finding reviewer and reviewer already finished the review updated

---

Packs/CTF02/ReleaseNotes/1_0_4.md
Packs/CTF02/Scripts/CTF2BF/CTF2BF.yml
Packs/CTF02/pack_metadata.json
Packs/ctf01/Integrations/CortexXDRIRCTF/CortexXDRIRCTF.yml
Packs/ctf01/Integrations/OHMYVTCTF/OHMYVTCTF.yml
Packs/ctf01/ReleaseNotes/1_0_19.md
Packs/ctf01/Scripts/CTF1/CTF1.yml
Packs/ctf01/pack_metadata.json

In this [nightly job](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/6791397), we see an error related to installing ctf01 and ctf02 packs on an XSOAR6 machine. 
The CTF01, CTF02 packs, shouldn't be installed on XSAOR 6, only on XSOAR8 (you can see in the packs' metadata files that "serverMinVersion" is "8.2.0").
Therefore, in this PR we removed the XSAOR marketplace from the pack metadata files.

CTF Packs - Removed XSOAR on-prem Marketplace

---

Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.yml
Packs/CommunityCommonScripts/Scripts/MapRegex/MapRegex.yml
Packs/CommunityCommonScripts/Scripts/MaxList/MaxList.yml
Packs/CommunityCommonScripts/Scripts/MinList/MinList.yml
Packs/CommunityCommonScripts/Scripts/RandomElementFromList/RandomElementFromList.yml
Packs/CommunityCommonScripts/Scripts/isArrayItemInList/IsArrayItemInList.yml

Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressBinary/IPCalcReturnAddressBinary.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnAddressIANAAllocation/IPCalcReturnAddressIANAAllocation.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetAddresses/IPCalcReturnSubnetAddresses.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetBroadcastAddress/IPCalcReturnSubnetBroadcastAddress.yml
Packs/CommunityCommonScripts/Scripts/IPCalcReturnSubnetNetwork/IPCalcReturnSubnetNetwork.yml
Packs/CommunityCommonScripts/Scripts/isArrayItemInList/IsArrayItemInList.yml
Packs/CommunityCommonScripts/Scripts/MapRegex/MapRegex.yml
Packs/CommunityCommonScripts/Scripts/MaxList/MaxList.yml …

demisto/python3:3.10.14.100715 | 0-100 | PR batch #4/19

---

Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.yml
Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.yml
Packs/MitreCaldera/Scripts/CalderaGetOperationReport/CalderaGetOperationReport.yml
Packs/MitreCaldera/Scripts/CalderaOperationPostProcessing/CalderaOperationPostProcessing.yml
Packs/MitreCaldera/Scripts/CalderaPopulateAdversaryIDField/CalderaPopulateAdversaryIDField.yml
Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.yml
Packs/MitreCaldera/Scripts/CalderaPopulateEventLogs/CalderaPopulateEventLogs.yml
Packs/MitreCaldera/Scripts/CalderaPopulateObjectiveIDField/CalderaPopulateObjectiveIDField.yml
Packs/MitreCaldera/Scripts/CalderaPopulatePlannerIDField/CalderaPopulatePlannerIDField.yml
Packs/MitreCaldera/Scripts/CalderaPopulateSourceIDField/CalderaPopulateSourceIDField.yml

Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.yml
Packs/MitreCaldera/Integrations/MitreCaldera/MitreCaldera.yml
Packs/MitreCaldera/Scripts/CalderaGetOperationReport/CalderaGetOperationReport.yml
Packs/MitreCaldera/Scripts/CalderaOperationPostProcessing/CalderaOperationPostProcessing.yml
Packs/MitreCaldera/Scripts/CalderaPopulateAdversaryIDField/CalderaPopulateAdversaryIDField.yml
Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.yml
Packs/MitreCaldera/Scripts/CalderaPopulateEventLogs/CalderaPopulateEventLogs.yml
Packs/MitreCaldera/Scripts/CalderaPopulateObjectiveIDField/CalderaPopulateObjectiveIDField.yml …

demisto/python3:3.10.14.100715 | 0-100 | PR batch #10/19

---

Packs/Jira/Integrations/JiraV3/JiraV3.py
Packs/Jira/Integrations/JiraV3/JiraV3.yml
Packs/Jira/Integrations/JiraV3/JiraV3_test.py
Packs/Jira/ReleaseNotes/3_2_1.md
Packs/Jira/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39103)
Fixed an issue where mirroring new comments from Jira to XSOAR was not functioning correctly.

XSUP-39103/JiraV3/Fix_Incoming_Comments

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
Packs/CortexXDR/ReleaseNotes/6_1_55.md
Packs/CortexXDR/pack_metadata.json

fixes: [Pre-Commit](https://github.com/demisto/demisto-sdk/actions/runs/9852212535/job/27200324541#step:7:91)
Fixing `mypy` type annotation error

type annotation fix

---

Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml

Packs/SSLCertificates/Scripts/GenerateCSR/GenerateCSR.yml
Packs/SSLCertificates/Scripts/SSLVerifierV2/SSLVerifierV2.yml
Packs/SSLCertificates/Scripts/SSLVerifierV2GenerateEmailBody/SSLVerifierV2GenerateEmailBody.yml

demisto/ansible-runner:1.0.0.102086 | 0-100 | PR batch #1/1

---

Packs/Tenable_io/Integrations/Tenable_io/Tenable_io.py
Packs/Tenable_io/ReleaseNotes/2_2_5.md
Packs/Tenable_io/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38643

Tenable fetch bug

---

Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
Packs/Akamai_SIEM/ReleaseNotes/1_1_5.md
Packs/Akamai_SIEM/pack_metadata.json

fixes: [XSUP-37947](https://jira-dc.paloaltonetworks.com/browse/XSUP-37947)
Fixed an issue where the **fetch-events** flow created duplications & missing events due to wrong usage of offset & from query params.

Akamai waf event collector missing and duplicated events issue

---

Packs/SophosCentral/CONTRIBUTORS.json
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral_test.py
Packs/SophosCentral/ReleaseNotes/1_3_1.md
Packs/SophosCentral/pack_metadata.json

The Sophos Central Endpoint API provides a parameter for looking up devices by IP addresses. This PR adds this parameter to the related command. Furthermore the Sophos API does a partial string matching to check the IP. In probably the most cases you want a full match, therefor I also added an optional parameter to do a full match after retreiving the results.

Add new parameters for Sophos Central API

---

.github/github_workflow_scripts/handle_external_pr.py

fixes:
https://jira-dc.paloaltonetworks.com/browse/CIAC-11154
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11154)

Add community message for adding contributor to contributors.json

---

Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
Packs/ThreatConnect/ReleaseNotes/3_1_8.md
Packs/ThreatConnect/pack_metadata.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11146) to the issue
In Python 3.11, there is a [change](https://docs.python.org/3.11/whatsnew/3.11.html#enum) in how the `f-string` is handled on the Enum object.
```python
class Method(str, Enum):
GET = 'GET'
print(format(Method.GET))
```
in Python 3.10 this will output `GET` in Python 3.11 `Method.GET`

[ThreatConnectV3] Support Python 3.11

---

Tests/docker_native_image_config.json

The `rapid7_threat_command` and `CyrenThreatInDepthRenderRelated` integrations require a Python 3.11 image.
In PR #35455, we updated the `rapid7_threat_command` integration to support Python 3.11.
In PR #35456, we updated the `CyrenThreatInDepthRenderRelated` integration to support Python 3.11.
Until the native images for `GA` and `candidate` are updated to support Python 3.11, these items are unsuitable for the native image.

[Native Image] Ignore Python 3.11 Integrations

---

Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py
Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml
Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_3.md
Packs/ProofpointEmailSecurity/pack_metadata.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11182) to the issue
In python 3.11 you must use `.value` to get the value of Enum

[ProofpointEmailSecurityEventCollector] Python 3.11

---

Tests/docker_native_image_config.json

Related: [CIAC-11186](https://jira-dc.paloaltonetworks.com/browse/CIAC-11186)
The following integrations are supported only by python 3.11
- `CyrenThreatInDepthRenderRelated` #35456
- `rapid7_threat_command`  #35455
- `Respond_Analyst` #35470
- `rapid7appsec` #35466

[Native Image & Python 3.11] Ignore For GA and candidate

---

.pre-commit-config_template.yaml

Relates: [CIAC-11128](https://jira-dc.paloaltonetworks.com/browse/CIAC-11128).
As discussed we un-skipped the following hooks: 
- validate-deleted-files
- validate-conf-json
- validate-content-paths
The following hooks remained skipped for auto-update docker PRs: 
- xsoar-lint
- validate
- format

Un-skip hooks for autoupdate docker PRs

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/3_1_35.md
Packs/SplunkPy/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39727
currently, we trying to get the `earliest` and `latest` of the drilldown search, from the `earliest` and `latest` keys
in some cases, this data stored under `earliest_offset` and `latest_offset` 
`'drilldown_searches': '[{"name":"NAME","search":"index=*","earliest_offset":"1713530640.000000000","latest_offset":"1721306640.000000000"}`
**_new test before fix:_**
**_after fix:_**

SplunkPy: fix the `earliest` key in drilldown enrichment

---

Packs/CommonScripts/ReleaseNotes/1_15_35.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39649
dockerfiles PR: https://github.com/demisto/dockerfiles/pull/29953
Due to a bug in version >=0.1.0 of the `RTFDE` module
we lock the version to 0.0.2 in the `demisto/parse-emails` docker image

ParseEmailFilesV2: fix a bug of 'gbk' decoding in MSG file

---

Packs/CommonScripts/TestPlaybooks/DBotUpdateLogoURLPhishing_test.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11311
Currently, the TPB add image and after that delete it
in case of error in deletion, the next add Image will fail with the message `This logo name already exists in the model. Please use another logo name`
like happened in [nightly](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/7251229/raw#L9741)
fix:
change the tasks order, the first step after delete context will try to delete the image and will pass even in case of error (image not exist)
PB before:
PB after:

DBotUpdateLogoURLPhishing_test : change tasks order

---

Packs/Troubleshoot/ReleaseNotes/2_1_0.md
Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.py
Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.yml
Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot_test.py
Packs/Troubleshoot/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11115)
added openssl to the docker. 
in case of successful connections the openssl subprocess just would timeout on an open succesful connection, so now sending Q in to quit

fix openssl mode

---

Packs/CommonPlaybooks/Playbooks/playbook-File_Reputation.yml
Packs/CommonPlaybooks/ReleaseNotes/2_6_37.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11387)
[File Reputation PB] Fixed the data path for VirusTotal malicious file count.

[File Reputation PB] Fixed the data path for VirusTotal malicious file count

---

Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_4_5.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: [XSUP-40124](https://jira-dc.paloaltonetworks.com/browse/XSUP-40124)
Fixed an issue where **ews-global-junk-rules-set** and **ews-junk-rules-set** would fail on empty values for trusted and blocked domains and email sections.

Fix set-junk-rules regular and global commands

---

Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
Packs/TheHiveProject/ReleaseNotes/1_1_21.md
Packs/TheHiveProject/pack_metadata.json

fixes: [XSUP-40322](https://jira-dc.paloaltonetworks.com/browse/XSUP-40322)
Fixed an issue where mirror out would fail when changing the *severity*, *pap* and *tlp* fields.

The hive severity fix

---

Packs/CommonScripts/ReleaseNotes/1_15_45.md
Packs/CommonScripts/Scripts/IsIntegrationAvailable/IsIntegrationAvailable.js
Packs/CommonScripts/pack_metadata.json

Fixed an issue where the script would return an error when the *raw-response* argument was provided.
Before:
After:

[isIntegrationAvailable] Fixed an issue with raw-response

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
Packs/CortexXDR/ReleaseNotes/6_1_62.md
Packs/CortexXDR/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40446)
Fixed an issue in which multiple incidents were created.
The problem was caused as the list `incidents_at_last_timestamp` in `last_run` which held a list of all previously created incidents which occurred on the exact same time as the next run will be queried with, so that we can delete any duplicate s that are fetched.
The issue happened when the list was deleted after an empty run even though the last fetch time stayed the same. This caused the next run not to delete the new incident pulled even though it was a duplicate.
In this PR, the `incidents_at_last_timestamp` list is kept if an empty run is executed.

[Cortex XDR - IR] Fix multiple incidents pulled

---

Packs/AzureSentinel/Integrations/AzureSentinel/README.md

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39923)
Explain that incidents below specified severity won't be mirrored even if their severity is later increased in Microsoft Sentinel.

[Microsoft Sentinel] Update the README.md

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/3_1_37.json
Packs/SplunkPy/ReleaseNotes/3_1_37.md
Packs/SplunkPy/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-40336
currently, in `splunk-search` we create the search by the given `query` arg, and then check if it's have results.
in case there is `fatal` error (invalid syntax of the query for example) we return message that there is no results,
but the `splunk-sdk` `Job` instance contains the indications about the failure but no exception was raised.
in the fix, i check the status in the `Job` instance, and raise `DemistoException` according with the `Job` failure message.
**unit test befor fix:**
**unit test after fix:**
**playground:**
command to reproduce 
```
!splunk-search query="`notable` | where 1= | head 1"
```

SplunkPy: better error handling in `splunk-search`

---

Packs/PhishingURL/ReleaseNotes/1_1_19.md
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
Packs/PhishingURL/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40525)
Fixed an issue in which the response from `rasterize` for `mailto` URLs would not be parsed correctly as the `DBotPredictURLPhishing` filtered out all responses from `rasterize` in which the `Contents` key was a string and assumed all other responses were dictionaries, as was the case when this logic was written.
In the latest version of Rasterize, responses for `mailto` URLs are returned in this format:
```python
{
'Type': 11,
'ContentsFormat': 'json',
'Contents': None,
'HumanReadable': '<messsage>',
'EntryContext': {},
'IndicatorTimeline': [],
'IgnoreAutoExtract': False,
'Note': False,
'Relationships': []
}
```
In this case, the `Contents` key contains a `NoneType` causing the error: `AttributeError: …

[DBotPredictURLPhishing] Fix mailto URLs fail with rasterize responses.

---

Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.py
Packs/TheHiveProject/Integrations/TheHiveProject/TheHiveProject.yml
Packs/TheHiveProject/ReleaseNotes/1_1_22.md
Packs/TheHiveProject/pack_metadata.json

fixes: [XSUP-40322](https://jira-dc.paloaltonetworks.com/browse/XSUP-40322)
Fixed an issue where mirror-out would fail when trying to update custom fields (which are handled as dictionary)

TheHive custom fields fix

---

Packs/Axonius/Integrations/Axonius/Axonius.yml
Packs/Axonius/ReleaseNotes/1_2_4.md
Packs/Axonius/pack_metadata.json
Packs/CommonScripts/ReleaseNotes/1_15_52.md
Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.yml
Packs/CommonScripts/pack_metadata.json

- AquatoneDiscoverV2 - Updated the Docker image to: *demisto/aquatone:2.0.0.108439*.
- Axonius - Updated the Docker image to: *demisto/axonius:1.1.0.108438*.

Update AquatoneDiscoverV2  and Axonius dockers

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/TestPlaybooks/ServiceNow_Fetch_Incidents_Test.yml
Tests/conf.json

related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11520
link the test playbook "ServiceNow Fetch Incidents Test" to service now V2 integration yml, where it was missing in the tests section.

Link Service Now test playbook to integration yml

---

.github/workflows/run-legacy-validate-for-contribution.yml

Since we [get](https://github.com/demisto/content/actions/runs/10440792032/job/28911130320?pr=35886) 
```
Traceback (most recent call last):
File "/home/runner/work/content/content/.venv/bin/demisto-sdk", line 8, in <module>
sys.exit(main())
File "/home/runner/work/content/content/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/home/runner/work/content/content/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/home/runner/work/content/content/.venv/lib/python3.10/site-packages/click/core.py", line [16](https://github.com/demisto/content/actions/runs/10440792032/job/28911130320?pr=35886#step:6:17)88, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

use `fetch-depth:0` in `legacy-validate`

---

Packs/FortiGate/Integrations/FortiGate/FortiGate.py
Packs/FortiGate/Integrations/FortiGate/FortiGate.yml
Packs/FortiGate/Integrations/FortiGate/FortiGate_test.py
Packs/FortiGate/ReleaseNotes/2_0_3.md
Packs/FortiGate/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40743)
Fixed an issue with **fortigate-list-firewall-policies** command which caused all policies to be displayed when filtering by a policyName that did not have any matches.

Fortigate fix

---

Packs/Base/TestPlaybooks/playbook-DBotTrainClustering-test.yml

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11478)
Fix `DBotTrainClustering` TPB
The `Check outputs` step was changed from a string comparison that didn't allow for other incidents in a given cluster...
...to a list membership check which ensures that the created incidents are in the correct clusters but ignores any other incidents in the cluster.

Fix DBotTrainClustering TPB

---

Packs/FiltersAndTransformers/ReleaseNotes/1_2_77.md
Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate.py
Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate.yml
Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/AfterRelativeDate_test.py
Packs/FiltersAndTransformers/Scripts/AfterRelativeDate/README.md
Packs/FiltersAndTransformers/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-40818
currently, when using the `AfterRelativeDate` automation with date argument like `21 Aug 13:00 UTC` the following error is appear `TypeError: can't compare offset-naive and offset-aware datetimes`
fix:
parsing the time as `offset-naive`
**test before:**
**test after:**

AfterRelativeDate: fix offset-awere date

---

Packs/CommonPlaybooks/TestPlaybooks/playbook-GenericPollingTest.yml
Packs/CommonScripts/ReleaseNotes/1_15_54.md
Packs/CommonScripts/Scripts/GenericPollingScheduledTask/GenericPollingScheduledTask.js
Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py
Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml
Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling_test.py
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-40734
Added escaping for quotations in arg names and values both in **ScheduleGenericPolling** and **GenericPollingScedulledTask**

added a fix to GenericPollingScheduledTask

---

Packs/qualys/pack_metadata.json

https://jira-dc.paloaltonetworks.com/browse/EXPANDR-10862
In researching Tenable/Qualys asset collection integrations I realized the Qualys doesn't show up as a pack with "asset collection" even though it does have the capability.  Adding the same keyword to it as [Tenable](https://github.com/demisto/content/blob/9874c42fd4f7a29e904e29bdf5d6be85300968d9/Packs/Tenable_io/pack_metadata.json#L15)

Add Asset Collection keyword to Qualys Pack

---

Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_5.md
Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.py
Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.yml
Packs/SuspiciousDomainHunting/pack_metadata.json

Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10508)
mypy failed on 
```
Module "cv2" does not explicitly export attribute "cv2"  [attr-defined]
from cv2 import cv2
```
and the script failed on the platform
Seems to be related to BC that happened in version 4.6. (we are using 4.10.0.84)
see  https://github.com/opencv/opencv-python/issues/676

[imagecompare] mypy

---

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_4.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: [XSUP-41053](https://jira-dc.paloaltonetworks.com/browse/XSUP-41053)
Removing redundant whitespaces from service tag name that caused a value error in `ews-expand-group` command

removing redundant whitespaces from service tag name

---

Packs/Whois/Integrations/Whois/Whois.py
Packs/Whois/Integrations/Whois/Whois_test.py
Packs/Whois/ReleaseNotes/1_5_16.json
Packs/Whois/ReleaseNotes/1_5_16.md
Packs/Whois/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41040
Return a dictionary as raw response in the new flow when calling `domain` or `whois` commands.

Whois return JSON in raw_response

---

Packs/SSLLabs/pack_metadata.json

The pack metadata had a typo in the description. This PR fixes that issue see below
Before: 
"This pack integrations with Qualys SSL Labs. A free online service performs a deep analysis of the configuration of any SSL web server on the public Internet"
After:
"description": "This pack integrates with Qualys SSL Labs. A free online service performs a deep analysis of the configuration of any SSL web server on the public Internet"

Fixed a typo in the SSL Labs pack metadata

---

Packs/Vertica/Integrations/Vertica/README.md
Packs/Vertica/Integrations/Vertica/Vertica.py
Packs/Vertica/Integrations/Vertica/Vertica.yml
Packs/Vertica/ReleaseNotes/1_0_5.md
Packs/Vertica/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11664)
In Vertica the implementation of getting a user from the env is overridden with a safer function. Some of its' implementation seems redundant but after closer inspection everything has meaning. Added some code comments to clarify what is going on.

Add comments to getuser override implementation in Vertica

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/ReleaseNotes/1_4_67.md
Packs/MicrosoftTeams/pack_metadata.json

Added a health endpoint for Teams Long Running integration. It allows fast testing to see if the endpoint / server is up.

Teams add health ep

---

Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
Packs/AzureCompute/Integrations/AzureCompute_v2/README.md
Packs/AzureCompute/Integrations/AzureCompute_v2/test_data/get_vm_command.json
Packs/AzureCompute/ReleaseNotes/1_2_29.md
Packs/AzureCompute/pack_metadata.json

[EXPANDR-2805](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-2805)
- Updated the `azure-vm-get-instance-details` command to add `Tags` from a VM instance to alert context.

[Marketplace Contribution] -  EXPANDR-2805 - Update Get VM Details Command

---

Packs/CommonDashboards/ReleaseNotes/1_7_5.md
Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics.py
Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics_test.py
Packs/CommonDashboards/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11672
Fixed an issue where an uninformative error was displayed in the "use case adoption coverage" widget because of misconfiguration of the **Core REST API** integration.

CIAC-11672/AdoptionMetrics

---

Packs/AWS-EC2/ReleaseNotes/1_4_12.md
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts.py
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts.yml
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/AwsEC2SyncAccounts_test.py
Packs/AWS-EC2/Scripts/AwsEC2SyncAccounts/README.md
Packs/AWS-EC2/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41400)
Add the new argument `max_accounts` to `AwsEC2SyncAccounts` which controls the amount of accounts pulled.

[AwsEC2SyncAccounts] new argument "max_accounts"

---

Packs/Core/Integrations/CoreIOCs/CoreIOCs.py
Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py

Following a mypy error that sometimes occurs, ignore was added to the import line of the google.cloud library

Fix mypy error flaky for google.cloud library

---

Packs/SentinelOne/Integrations/SentinelOneEventCollector/README.md
Packs/SentinelOne/Integrations/SentinelOneEventCollector/SentinelOneEventCollector.yml
Packs/SentinelOne/ReleaseNotes/3_2_32.md
Packs/SentinelOne/pack_metadata.json

Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11847)
Rename "SentinelOne Event Collector" to "SentinelOne Activity and Alerts".

Rename "SentinelOne Event Collector" to "SentinelOne Activity and Alerts"

---

.github/workflows/pre-commit-reuse.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11768
Use `demisto-sdk secrets` in `pre-commit`, so contributors will be able to see failures in it.

Return demisto-sdk secrets to pre-commit

---

.pre-commit-config_template.yaml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11768
In continuation to https://github.com/demisto/content/pull/36412
Use demisto-sdk secrets in pre-commit, so contributors will be able to see failures in it.

Unskip secrets in pre-commit

---

Packs/CommonDashboards/ReleaseNotes/1_7_6.md
Packs/CommonDashboards/Scripts/AdoptionMetrics/AdoptionMetrics.py
Packs/CommonDashboards/pack_metadata.json

n/a
Small fix to the `AdoptionMetrics` script that is used to populate a widget in the 'XSOAR Automation Insights' dashboard. This was necessary because the script currently checks for an invalid key, `incident_types`. The condition that checks the `incident_types` key will never return true, and therefore it is impossible for the "Business Email Compromise Coverage" category to ever get a green checkmark.

Fix logic error in AdoptionMetrics script

---

Packs/SekoiaXDR/Integrations/SekoiaXDR/SekoiaXDR_test.py

fixes: [Build failure](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/9003099/raw)
Adding Freeze to Sekoia tests using timestamps to avoid flakiness.

added freeze to sekoia test_arg_to_timestamp unit test

---

Packs/CommonScripts/ReleaseNotes/1_15_66.md
Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
Packs/CommonScripts/pack_metadata.json

fixes: [XSUP-42280](https://jira-dc.paloaltonetworks.com/browse/XSUP-42280)
'DBotScore' key is now excluded from context deletion, in order to prevent caching it repeatadly and causing performance issues.

exclude 'dbotscore' from deletions

---

Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
Packs/CommonPlaybooks/ReleaseNotes/2_6_43.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41176
currently, we consider a file which contain `xml` in the `file.info` - as file to be converted to pdf
this lead to convert also a docx file with `vnd.openxmlformats-officedocument.wordprocessingml.document` in the `file.info`
adding additional check to filter out `doc/docx` files

Extract Indicators From File PB: not convert docx to pdf

---

Tests/docker_native_image_config.json

In #35796, we added ParseEmailFilesV2 to the ignore list of the native. For more details on why we added it, please see [this](https://jira-dc.paloaltonetworks.com/browse/CIAC-11469) ticket.
As part of releasing the new GA version (8.8), we forgot to add the new version to the images that need to be ignored in ParseEmailFilesV2. This caused an issue in the coverage of the UT.

[Native image] skip ParseEmailFilesV2  GA

---

Packs/AtlassianConfluenceCloud/.pack-ignore

Upload packs to the marketplace failed because of the IN161 validation - this validation didn't failed in the [PR](https://github.com/demisto/content/pull/36077/files) but failed in the upload flow. add this validation to the ignore.

Add IN161 ignore to AtlassianConfluenceCloud.yml

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
Packs/AzureSentinel/ReleaseNotes/1_5_49.md
Packs/AzureSentinel/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42696)
Fixed an issue where the **get-remote-data** (mirroring) command was not working properly for *Alerts Count* field.

[Microsoft Sentinel] Fix issue in mirroring the AlertsCount field

---

Packs/GitLab/Integrations/GitLabv2/GitLabv2.py
Packs/GitLab/ReleaseNotes/2_2_23.md
Packs/GitLab/pack_metadata.json

fixes: [XSUP-42366](https://jira-dc.paloaltonetworks.com/browse/XSUP-42366)
Replace deprecated request parameters in [Commits API](https://docs.gitlab.com/ee/api/commits.html). More information in the attached Jira ticket.
Before changes - some entries in the response are out of the desired time-frame:
After changes - All entries in the response are in the desired time-frame:

[Gitlab V2] Update deprecated request params

---

Packs/Workday/ParsingRules/WorkdayParsingRules/WorkdayParsingRules.xif
Packs/Workday/ReleaseNotes/1_4_12.md
Packs/Workday/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-134825)
Added a use of parse_timestamp function to the parsing rule (previous rule contained a simple mapping of _time = requestTime).

Modified parsing rule - Workday

---

Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.py
Packs/ApiModules/Scripts/MicrosoftGraphMailApiModule/MicrosoftGraphMailApiModule.yml
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
Packs/MicrosoftGraphMail/ReleaseNotes/1_6_18.md
Packs/MicrosoftGraphMail/pack_metadata.json

fixes: [XSUP-42649](https://jira-dc.paloaltonetworks.com/browse/XSUP-42649)
Add ability to download 'microsoft.graph.message' attachment types via new `msgraph-mail-get-attachment` command argument.

[Microsoft Graph Mail] Enhance msgraph-mail-get-attachment command

---

.pre-commit-config_template.yaml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-7098
https://github.com/demisto/content/pull/36057
Added the `--enforce-all` [flag](https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#check-added-large-files) to include all files (not only staged)

Added large files hook enforce all to include committed files

---

Packs/UrlScan/CONTRIBUTORS.json
Packs/UrlScan/Integrations/UrlScan/README.md
Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
Packs/UrlScan/ReleaseNotes/1_2_15.md
Packs/UrlScan/pack_metadata.json

No related issues
Added the option to specify what country to scan from at the integration instance level. The available countries are listed in the [api/v1/availableCountries endpoint](https://urlscan.io/api/v1/availableCountries/), and have been implemented in the instance choice as a single choice field.

urlscan country option

---

Packs/Tanium/Integrations/Tanium_v2/Tanium_v2.py
Packs/Tanium/ReleaseNotes/1_0_34.md
Packs/Tanium/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43089)
Fixed an issue where the **tn-get-question-metadata** command was raising an error when the saved_question field was empty.

[Tanium v2] Fixed an issue in tn-get-question-metadata command

---

Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.py
Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2_test.py
Packs/PrismaCloud/ReleaseNotes/4_3_14.md
Packs/PrismaCloud/pack_metadata.json

fixes: [XSUP-42066](https://jira-dc.paloaltonetworks.com/browse/XSUP-42066)
In the latest version of PrismaCloudV2 (4.3.13), we added the `HeuristicSearch` parameter to the body.
However, this parameter is case-sensitive, meaning we must use a lowercase 'h' instead of an uppercase 'H'. This PR updates the code accordingly.

[PrismaCloudV2] Update The `HeuristicSearch` Parameter

---

Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.py
Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2_test.py
Packs/RemoteAccess/ReleaseNotes/1_0_35.md
Packs/RemoteAccess/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42283
currently, when someone run the copy-to command with the destination dir arg, we run the mkdir -p to be sure this dir will be exist
if the dir already exist and the user don't have the permission to create the dir - an error (without detailed desctiption) is occureding
we can ignore the error from the mkdir as, if the dir already exist it will pass and if the dir didn't exist - the process will fail with detailed description in the copy process
**new test before fix:**
**after fix:**

RemoteAccess v2: fix issue in case of missing permission.

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_21.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/RestartFailedTasks/RestartFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42792
the script use the wrong `incident_id` arg for the script `taskReopen`, so this lead to reopen all the task with this id even in the current incident
fixing the arg name to `incidentId` according the command help and server code

RestartFailedTasks: correct the arg name

---

Packs/CommonScripts/ReleaseNotes/1_15_77.md
Packs/CommonScripts/Scripts/FailedInstances/FailedInstances.js
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43180)
Fixed an issue where the script was ignoring instances in an error state.

[FailedInstances] Fixed an issue related to instances in an error state

---

Packs/CommonPlaybooks/TestPlaybooks/playbook-Containment_Plan-Test.yml

relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8772)
Updated the test playbook after fixing an issue in the tested playbook.
added new task to remove hash from block list.

Test playbook containment plan enhancement

---

Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.yml
Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/README.md
Packs/CiscoUmbrellaReporting/ReleaseNotes/1_1_4.md
Packs/CiscoUmbrellaReporting/pack_metadata.json

This is an addition to the already merged PR #36253 
The optional `categories` argument has been added to all commands which supports it according to the [Cisco Umbrella API](https://developer.cisco.com/docs/cloud-security/api-reference-reports-reporting-overview/) (in the initial PR the argument itself was only added to two of the commands but 7 other commands support it as well).

CiscoUmbrellaReporting: Added optional "categories" argument to supporting commands

---

Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
Packs/LinuxEventsCollection/ReleaseNotes/1_0_11.md
Packs/LinuxEventsCollection/pack_metadata.json

fixes: [XSUP-42968](https://jira-dc.paloaltonetworks.com/browse/XSUP-42968)
This PR extends the existing supported formats for parsing the timestamp on Linux event logs: 
- Added support for ISO 8601 timestamp profile with a space separating the date and hour (instead of the common "T" designator), as well as a space between the timestamp and it's corresponding timezone offset from UTC. 
- Example: `2024-11-04 10:36:12.818 +1100`
- Added support for extracting timestamp from json payload embedded in the raw linux log, as well as the case where the entire log is a valid JSON object. The extract is based on the following key paths from the root JSON level: `time` and `Data.Client.CurrentDateTime`. 
- Example: 
`Nov  4 08:16:27 myHostName d1[1455]: …

XSUP-42968 Linux Parsing Rule Extension for Additional Timestamp Formats

---

Packs/CommonScripts/ReleaseNotes/1_15_78.md
Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py
Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml
Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12033

Ciac 12033 - Hide includeinformational argument in SearchAlertsV2 script in XSOAR using hidden in yml

---

Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.py
Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute.yml
Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/PaloAltoNetworks_PrismaCloudCompute_test.py
Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/README.md
Packs/PrismaCloudCompute/Integrations/PaloAltoNetworks_PrismaCloudCompute/commands.txt
Packs/PrismaCloudCompute/ReleaseNotes/1_7_5.md
Packs/PrismaCloudCompute/pack_metadata.json

fixes: [CIAC-11607](https://jira-dc.paloaltonetworks.com/browse/CIAC-11607)
Added new command to remove blocked IPs from the custom feeds

Prisma Cloud Compute custom feeds ip remove (CIAC-11607)

---

Packs/PhishingURL/ReleaseNotes/1_1_20.md
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
Packs/PhishingURL/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42753)
Removed the URLs that started with `mailto:` from *urls* argument.

DBotPredictURLPhishing - remove mailto urls

---

Packs/Incapsula/Integrations/Incapsula/Incapsula.js
Packs/Incapsula/ReleaseNotes/1_1_7.md
Packs/Incapsula/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43155)
Fixed an issue where the commands' args were not parsed as expected.

Incapsula - pass arguments in url params

---

Packs/Base/ReleaseNotes/1_35_4.md
Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
Packs/Base/pack_metadata.json
Packs/CommonScripts/ReleaseNotes/1_15_91.md
Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml
Packs/CommonScripts/pack_metadata.json
Packs/CommunityCommonScripts/ReleaseNotes/1_3_4.md
Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
Packs/CommunityCommonScripts/pack_metadata.json

Aud demisto/auto update docker staging branch 52

---

Packs/CommonWidgets/ReleaseNotes/1_2_52.md
Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget.yml
Packs/CommonWidgets/pack_metadata.json
Packs/JARM/Integrations/JARM/JARM.yml
Packs/JARM/ReleaseNotes/1_0_16.md
Packs/JARM/pack_metadata.json
Packs/Zabbix/Integrations/Zabbix/Zabbix.yml
Packs/Zabbix/ReleaseNotes/1_0_35.md
Packs/Zabbix/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12212)

demisto/py3-tools3:1.0.0.116158 | 0-100 | PR batch #1/1

---

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.py
Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_17_3.md
Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json

relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43570)
- Fixed an issue where the Client Credentials Flow in GCC High was redirecting to the wrong endpoint.

[Microsoft Defender for Endpoint] fix for GCC High

---

.github/workflows/security-label-check.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12235
If a contributor has opened a PR which requires the Security team to review it, then the merge should be blocked until they have reviewed the PR. This check will block a merge only if the PR is from a contribution and only if the "Security Review" label has been added.

Add a check for Security Approved for contributions

---

Packs/CommonScripts/ReleaseNotes/1_15_92.md
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2_test.py
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44142)
Fixed an issue where the script failed to handle binary data in PDF annotation objects.

[ReadPDFFileV2] Fix issue where the script failed to handle binary data

---

Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_17.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44009
Fixed an issue where the ***ews-message-trace-get*** command returned invalid context outputs.

Ews powershell bug

---

Packs/SophosCentral/Classifiers/classifier-mapper-incoming-SophosCentral.json
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
Packs/SophosCentral/ReleaseNotes/1_3_3.md
Packs/SophosCentral/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42727
Adding debugging logs to see whats happening during fetch. Suspicion is that there are no incidents being retrieved in the window that's being provided by the fetch samples command.

Add debugging logs to Sophos fetch incidents command

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_23.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44352)
Added the *get_scripts_name* argument that enables the script to retrieve and display custom script names instead of script IDs.

[GetFailedTasks] New argument - get_scripts_name

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/2_7_1.md
Packs/ServiceNow/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12318
Currently there is some mirrir related fileds which are presented in XSIAM - hide them

ServiceNowV2: Hide mirror fileds in XSIAM

---

Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml

Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
Packs/CommonScripts/Scripts/ExtractHyperlinksFromOfficeFiles/ExtractHyperlinksFromOfficeFiles.yml
Packs/CommonScripts/Scripts/ConvertFile/ConvertFile.yml
Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml

demisto/office-utils:2.0.0.117810 | 0-100 | PR batch #1/1

---

Packs/jamf/CONTRIBUTORS.json
Packs/jamf/Integrations/jamfV2/README.md
Packs/jamf/Integrations/jamfV2/command_examples.txt
Packs/jamf/Integrations/jamfV2/jamfV2.py
Packs/jamf/Integrations/jamfV2/jamfV2.yml
Packs/jamf/Integrations/jamfV2/jamfV2_test.py
Packs/jamf/Integrations/jamfV2/test_data/get_computer_configuration_profiles/get_computer_configuration_profiles_by_id_raw_response.json
Packs/jamf/Integrations/jamfV2/test_data/get_mobile_configuration_profiles/get_mobile_configuration_profiles_by_id_raw_response.json
Packs/jamf/ReleaseNotes/2_2_4.md
Packs/jamf/pack_metadata.json

[external pull request](https://github.com/demisto/content/pull/37591)
@daftops
Implement commands to get Configuration profiles for OS X or Mobile devices managed by JAMF.
See JAMF documentation:
- https://developer.jamf.com/jamf-pro/reference/findmobiledeviceconfigurationprofilesbyid
- https://developer.jamf.com/jamf-pro/reference/findosxconfigurationprofilesbyid

JAMF - Add Get configuration-profiles-by-id commands

---

validation_config.toml

Because of a possible bug that causes RN111 to fail when it shouldn't (the docker image in the yml file and in the RN are identical), I move it to be a warning until further investigation.

Update RN111 to be a warning

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_26.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44352)
Improved performance when using the get_scripts_name argument.

[GetFailedTasks] Improved performance when using the get_scripts_name argument

---

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
Packs/GenericSQL/ReleaseNotes/1_3_7.md
Packs/GenericSQL/pack_metadata.json

fixed: https://jira-dc.paloaltonetworks.com/browse/XSUP-43827
added the cryptography module to the docker image
and updated the integration to use the new docker image
docker repo pr: https://github.com/demisto/dockerfiles/pull/34754

GenerixSQL: update docker image with cryptography

---

Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
Packs/ProactiveThreatHunting/.pack-ignore

relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-12403
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-12304
After merging the deprecation of multiple MS commands, the [validation](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/12314979) started failing because the playbooks team hadn’t finished removing the deprecated commands from the playbooks using them. In the PR, these validation errors will be ignored until the playbook updates are complete.

Temporary ignore GR-107 until CIAC-12403 is resolved

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_27.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-45252)
Updated the script to return and display the brand name for integration commands, improving the visibility of failed tasks across different integrations.
Before:
After:

[GetFailedTasks] Return the command name and brand name separately

---

Packs/Jira/Integrations/JiraV3/JiraV3.py
Packs/Jira/ReleaseNotes/3_2_11.md
Packs/Jira/pack_metadata.json

relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-43839
When customers are using OnPrem version of Jira DataCenter, the fetch is trying to retrieve reports like done on OnPrem but in DC it is not possible, therefore they encounter an error.
This PR adds logs and handling the exception for this case (and in general) so the fetch will not fail when reports are not being fetched.

Jira V3 forms DC OnPrem handling

---

Packs/Core/Playbooks/playbook-WildFire_Malware.yml
Packs/Core/ReleaseNotes/3_2_10.md
Packs/Core/ReleaseNotes/3_2_11.md
Packs/Core/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12496)
Fixed an issue with the condition that checks if the alert was generated in the last 24h.
The fixes includes the following:
- fixed the context key path with the right prefix
- fixed the unix timestamp to be in millieseconds instead of nano seconds

Fix-wildfire-malware-playbook

---

Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
Packs/CommonPlaybooks/ReleaseNotes/2_6_49.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44693
Removed timeout input for WildFire - Detonate file v2 task, the playbook's default configuration will be used instead.

Remove wildfire polling fields

---

.pre-commit-config_template.yaml

Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12536)
Temporarily skips pre-commit pycln hook, until it is fixed as part of CIAC-12536.

[pre-commit] Skip pycln hook

---

Packs/PhishingURL/ReleaseNotes/1_1_22.md
Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
Packs/PhishingURL/pack_metadata.json

Remove redundant server calls to fetch the ML model.

[DBotPredictURLPhishing] Remove redundant server calls

---

.pre-commit-config_template.yaml

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12536)
Since the patch is merged [here](https://github.com/hadialqattan/pycln/pull/250), we can run `pycln` again with version 2.5.0.

[pre-commit] Add again pycln hook

---

Packs/CortexResponseAndRemediation/Playbooks/playbook-Office_process_creates_a_scheduled_task_via_file_access.yml
Packs/CortexResponseAndRemediation/ReleaseNotes/1_0_3.md
Packs/CortexResponseAndRemediation/pack_metadata.json

fix for the playbook "Office process creates a scheduled task via file access".
Added the 'continue on error' option when the regex for the suspicious Office path did not match.

Office process creates a scheduled task fix

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/3_1_50.md
Packs/SplunkPy/pack_metadata.json

[SplunkPy] MyPy In Docker

---

Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py
Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml
Packs/EclecticIQ/ReleaseNotes/3_0_6.md
Packs/EclecticIQ/pack_metadata.json
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
Packs/Elasticsearch/ReleaseNotes/1_3_27.md
Packs/Elasticsearch/pack_metadata.json
Packs/EmailCommunication/ReleaseNotes/2_0_37.md
Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
Packs/EmailCommunication/pack_metadata.json
Packs/ExabeamDataLake/Integrations/ExabeamDataLake/ExabeamDataLake.py
Packs/ExabeamDataLake/Integrations/ExabeamDataLake/ExabeamDataLake.yml
Packs/ExabeamDataLake/ReleaseNotes/1_0_2.md
Packs/ExabeamDataLake/pack_metadata.json
Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.py
Packs/ExabeamSecurityOperationsPlatform/Integrations/ExabeamSecOpsPlatform/ExabeamSecOpsPlatform.yml
Packs/ExabeamSecurityOperationsPlatform/ReleaseNotes/1_1_2.md
Packs/ExabeamSecurityOperationsPlatform/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Fix Pylint errors in E packs.

Fix Pylint errors in E packs

---

.pre-commit-config_template.yaml

Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Temporarily disabling E0601 and E0606 rules for pylint until they are fixed.

[pre-commit] PyLint disable E0601 and E0606

---

Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
Packs/AlibabaActionTrail/ReleaseNotes/1_1_2.md
Packs/AlibabaActionTrail/pack_metadata.json

fixes: [XSUP-45571](https://jira-dc.paloaltonetworks.com/browse/XSUP-45571)
Fixed an issue where the *First fetch time interval* parameter wasn't parsed correctly.

AlibabaActionTrail Event Collector - Fixed a parsing error related to the  First fetch time interval parameter

---

.pre-commit-config_template.yaml

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12592)
Remove native from .pre-commit-config_template.yaml

Remove native from .pre-commit-config_template.yaml

---

Packs/ThreatIntelReports/ReleaseNotes/1_0_20.md
Packs/ThreatIntelReports/pack_metadata.json
Packs/Whois/ReleaseNotes/1_5_20.md
Packs/Whois/pack_metadata.json

As a result of[ this PR](https://github.com/demisto/content/pull/38083), the [upload failed](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1966213) because they did not release a version for the `Whois` and `ThreatIntelReports` packs.

Locked dependencies of core packs

---

Tests/conf.json

https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/13317625#L1483
```
ker stats --no-stream --no-trunc --format "{{json .}}" | grep -Ei "demistopython33.11.10.115186--"'
[2025-01-09 23:55:28] - [10.184.214.33-0 (execute_tests)] - [ERROR] - Failed docker resource test. Docker container demistoserver_pyexec-67196338-54a0-4032-88e7-19ebd0792e96-demistopython33.11.10.115186--45 exceeded the memory threshold, configured: 160 MiB and actual memory usage is 224.4 MiB.
Fix container memory usage or add `memory_threshold` key to failed test in conf.json with value that is greater than 224.4
[2025-01-09 23:55:28] - [10.184.214.33-0 (execute_tests)] - [ERROR] - Test failed: playbook: "CrowdStrike_FalconX_Test" with integration(s): ["CrowdStrike Falcon X"]
```

Increased the memory threshold for CrowdStrike_FalconX TPB

---

Packs/DemistoLocking/Integrations/CoreLock/README.md
Packs/DemistoLocking/Integrations/DemistoLock/DemistoLock.js
Packs/DemistoLocking/Integrations/DemistoLock/DemistoLock.yml
Packs/DemistoLocking/Integrations/DemistoLock/README.md
Packs/DemistoLocking/ReleaseNotes/1_1_5.md
Packs/DemistoLocking/pack_metadata.json

fixes: [CIAC-11126](https://jira-dc.paloaltonetworks.com/browse/CIAC-11126)

added interval param

---

Packs/CommonPlaybooks/TestPlaybooks/playbook-IP_Enrichment_-_Generic_v2_-_Test.yml

The IP Enrichment - Generic v2 - Test required modification due to changes in the IPToHost script. The script no longer returns the IP address when no hostname is found, which the test playbook originally relied on.
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12580)

fixed testplaybook after IPToHost script change

---

Packs/FiltersAndTransformers/ReleaseNotes/1_2_89.md
Packs/FiltersAndTransformers/Scripts/WhereFieldEquals/WhereFieldEquals.js
Packs/FiltersAndTransformers/TestPlaybooks/playbook-Test_filters_and_transformers.yml
Packs/FiltersAndTransformers/pack_metadata.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/XSUP-46122) to the issue
Fixed an issue where the **WhereFieldEquals** transformer was not properly handling cases where the field value was equal to false.
`!WhereFieldEquals value=`[{"type": "test","value":false}]` field=type equalTo=test getField=value`
War Room
Test Playbook

Fix WhereFieldEquals Transformer Handling of false Field Values

---

Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.py
Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP_test.py
Packs/OpenLDAP/ReleaseNotes/2_0_16.md
Packs/OpenLDAP/ReleaseNotes/2_0_17.md
Packs/OpenLDAP/pack_metadata.json

Revert "LDAP Authentication - Fail login attempts when wildcards are used"

---

Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
Packs/ZeroFox/ReleaseNotes/1_3_6.md
Packs/ZeroFox/pack_metadata.json

Fix an issue identified when restricting the type of ZeroFox alerts ingested as XSOAR Incidents by correcting the filtering parameter in http request

[ZeroFox] Replace min_timestamp filter with escalated_min_date when only escalated alerts are fetched as incidents

---

Packs/Flashpoint/Integrations/Ignite/Ignite.py
Packs/Flashpoint/ReleaseNotes/2_0_4.md
Packs/Flashpoint/pack_metadata.json
Packs/FlashpointFeed/Integrations/IgniteFeed/IgniteFeed.py
Packs/FlashpointFeed/ReleaseNotes/2_0_4.md
Packs/FlashpointFeed/pack_metadata.json

fixes: [XSUP-46473](https://jira-dc.paloaltonetworks.com/browse/XSUP-46473).
It turns out that the call to the `get_pack_version()` function that occurs every run of the main function causes performance issues, therefore we temporarily replace this call with a hardcoded string of the current pack version.

Flashpoint - Removed the call to get_pack_version function

---

Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
Packs/CortexXpanse/ReleaseNotes/1_2_6.md
Packs/CortexXpanse/pack_metadata.json
Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.py
Packs/VectraXDR/ReleaseNotes/1_0_10.md
Packs/VectraXDR/Scripts/VectraXDRDisplayEntityDetections/VectraXDRDisplayEntityDetections.py
Packs/VectraXDR/pack_metadata.json

It turns out that the call to the `get_pack_version()` function causes performance issues, therefore we temporarily replace this call with a hardcoded string of the current pack version.

VectraXDR and CortexXpanse - Removed the use of the get_pack_version function

---

Packs/SecurityScorecard/Integrations/SecurityScorecard/README.md
Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py
Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml
Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_test.py
Packs/SecurityScorecard/Integrations/SecurityScorecard/command_examples.txt
Packs/SecurityScorecard/ReleaseNotes/1_0_12.md
Packs/SecurityScorecard/pack_metadata.json

Adds a new command  `!securityscorecard-issue-details-get` internally calling `issue_details_get_command()`
It fetches the list of findings for a given domain and given issue-type detected by securityscorecard.
The list is a markdown table with a set of columns relevant to all issue-types
Since the list can be quite long (thousands of findings some times), there will a limit added to the endpoint call to SSC
https://github.com/user-attachments/assets/9ba62114-ee44-4c2f-83c9-c4b48e65a585

feat: add issue_details_get_command

---

Packs/qualys/Integrations/Qualysv2/Qualysv2.py
Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py
Packs/qualys/ReleaseNotes/3_2_1.md
Packs/qualys/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46857)
Fixed an issue with updating module health during asset and vulnerability fetching when response timeouts occurred or command execution times were exceeded.

Fix UnboundLocalError when updating module health in Qualys VMDR 'fetch-assets' command

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/ReleaseNotes/3_2_3.md
Packs/SplunkPy/pack_metadata.json

fixes: [XSUP-43248](https://jira-dc.paloaltonetworks.com/browse/XSUP-43248).
It appears that when an error is raised during the run of the `get-modified-remote-data` command, the server will stop running this command and will call the `get-remote-data` command instead.
In the Splunkpy integration, the `get-remote-data` command is not implemented (since version 3.2.0). Therefore we are getting into an endless loop of calling an unimplemented command over and over, and the 'Mirror In' mechanism just stops.
In this PR we fix that issue by wrapping the …

SplunkPy - Fixed a Mirror In issue (XSUP-43248)

---

Config/core_packs_platform_list.json
Packs/DomainTools/Integrations/DomainTools/DomainTools.yml
Packs/DomainTools/ReleaseNotes/1_1_7.md
Packs/DomainTools/pack_metadata.json
Tests/conf.json

N/A
Deprecate the DomainTools Enterprise Pack, use the `DomainTools Iris` Pack instead.

Deprecate DomainTools Enterprise Integrations

---

Packs/PortScan/.pack-ignore

Since DomainTools has become deprecated [here](https://github.com/demisto/content/pull/38725), we need to add ignore to GR107.

[Port Scan - External Source] Add ignore GR107

---

Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.py
Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot.yml
Packs/CTM360-CyberBlindspot/Integrations/CyberBlindspot/CyberBlindspot_test.py
Packs/CTM360-CyberBlindspot/ReleaseNotes/2_1_1.md
Packs/CTM360-CyberBlindspot/pack_metadata.json

fixes: slicing error caused by attempting to slice a dict instead of a list.
This is to fix a `test_module` bug where the returned value is not a list causing an exception upon slicing that value.

CTM360-CBS bug fix expecting `list` but getting `dict`

---

Packs/MicrosoftTeams/Scripts/MicrosoftTeamsAsk/README.md

fixes: [XSUP-47328](https://jira-dc.paloaltonetworks.com/browse/XSUP-47328)
Added to the readme file a note explaining that the `MicrosoftTeamsAsk`script shouldn't been run from the debugger panel. 
Same reason as - `SlackAskV2` script - [slack-ask-v2](https://xsoar.pan.dev/docs/reference/scripts/slack-ask-v2).

MicrosoftTeamsAsk script - Improved docs

---

Packs/cisco-ise/pack_metadata.json
Packs/cisco-meraki/pack_metadata.json
Packs/cyberark_AIM/pack_metadata.json
Packs/dnstwist/pack_metadata.json
Packs/epo/pack_metadata.json
Packs/fireeye/pack_metadata.json
Packs/iDefense/pack_metadata.json
Packs/illuminate/pack_metadata.json
Packs/ipinfo/pack_metadata.json
Packs/isight/pack_metadata.json
Packs/jamf/pack_metadata.json
Packs/knowbe4Phisher/pack_metadata.json
Packs/mcafeeDam/pack_metadata.json
Packs/mnemonicMDR/pack_metadata.json
Packs/nessus/pack_metadata.json
Packs/opswat-metadefender/pack_metadata.json
Packs/qualys/pack_metadata.json
Packs/rasterize/pack_metadata.json
Packs/remedy_SR/pack_metadata.json
Packs/sampleSiem/pack_metadata.json
Packs/trendMicroDsm/pack_metadata.json

Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-12864
Updating the following packs before merging to `'platform-content-support-merge-gateway`:  
```
CitrixADC
cisco-ise
cisco-meraki
cyberark_AIM
dnstwist
epo
fireeye
iDefense
illuminate
ipinfo
isight
jamf
knowbe4Phisher
mcafeeDam
mnemonicMDR
nessus
opswat-metadefender
qualys
rasterize
remedy_SR
sampleSiem
trendMicroDsm
```

Adopt 'platform' MP to content packs #33

---

Packs/ImageOCR/ReleaseNotes/1_1_38.md
Packs/ImageOCR/pack_metadata.json

Fix
```
The dependency ImageOCR/1.1.37 of the pack rasterize/2.1.0 in the rasterize.zip does not meet the conditions for ImageOCR/1.1.36 in the corepacks-8.10.0.json list.
```

Bump Image OCR

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Packs/MicrosoftTeams/ReleaseNotes/1_5_22.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: [CIAC-13091](https://jira-dc.paloaltonetworks.com/browse/CIAC-13091)
Allow calling ms-teams-ring-user when the integration is configured to use authorization code.
Done by authenticating with 'Client Credentials' for ring-user while caching both token types separately.

Ms teams ring user in authcode

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Packs/MicrosoftTeams/ReleaseNotes/1_5_24.md
Packs/MicrosoftTeams/pack_metadata.json

Related: [CIAC-13241](https://jira-dc.paloaltonetworks.com/browse/CIAC-13241)
- Split the required permissions dictionary to differentiate client credentials and authorization code flow required permissions.
- Added ChannelMessage.Send permission to the required list for send-notification in Authorization code flow.
- Added a more detailed error message for cases of authorization error when trying to use the bot API

MS Teams add missing permission requirement to docs

---

Packs/CommonScripts/TestPlaybooks/playbook-UnzipFile-Test.yml

fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13446
fixed an issue where the unzipFile-test tpb failed due to changing a folder name in the UnZip script folder.

fixed wrong url in unzip file tpb

---

Packs/CertStream/pack_metadata.json
Packs/CheckPointDome9/pack_metadata.json
Packs/CheckPointNDR/pack_metadata.json
Packs/CheckPointSandBlast/pack_metadata.json
Packs/CheckpointFirewall/pack_metadata.json
Packs/CiscoCatalyst/pack_metadata.json
Packs/CiscoSpark/pack_metadata.json
Packs/Claroty/pack_metadata.json
Packs/ClarotyXDome/pack_metadata.json

Alignment tags, keywords and categories packs (chunk8)

---

Packs/FeedMISPThreatActors/CONTRIBUTORS.json
Packs/FeedMISPThreatActors/Integrations/FeedMISPThreatActors/FeedMISPThreatActors.py
Packs/FeedMISPThreatActors/ReleaseNotes/1_0_2.md
Packs/FeedMISPThreatActors/pack_metadata.json

Added rawJSON to fetched indicator object in Feed MISP Threat Actors to enable custom mapping.
fixes: N/A
Currently unable to build a custom mapper for this Feed Integration due to the rawJSON not being returned. This causes no data to be returned in the Classifier/Mapper editors when you pull from this instance. The simple addition of `'rawJSON': threat_actor` to the returned indicators object from `fetch_indicators_command` allows the Classifier/Mapper editors to actually fetch data to build the mapper off of.
- [x ] Tests
- [ x] Documentation

Add rawJSON to fetched indicator object in Feed MISP Threat Actors

---

Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.py
Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.yml
Packs/CiscoUmbrellaReporting/ReleaseNotes/1_1_6.md
Packs/CiscoUmbrellaReporting/pack_metadata.json

The validation of the categories which can be sent to the Cisco Umbrella API uses the python function isdigit() which returns only true for positive numbers. However, the Cisco Umbrella API accepts also negative numbers (to filter out categories explicitly)
So `[10, 34, 63]` is a valid list of categories but `[10, 34, -63]` is also valid. In the current version, the second argument throws a `ValueError()` although it is valid.
To be able to filter out categories explicitly, I added a `lstrip('-')` right before the `isdigit()` check which results in …

CiscoUmbrellaReporting bugfix category filter

---

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
Packs/Core/ReleaseNotes/3_2_37.md
Packs/Core/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-170299
make the `generic_file_path` - REQUIRED and fix it's context paths

CoreIR: fix quick action arg path

---

Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml
Packs/AWS-SNS-Listener/ReleaseNotes/1_0_10.md
Packs/AWS-SNS-Listener/pack_metadata.json
Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
Packs/GenericWebhook/ReleaseNotes/1_1_9.md
Packs/GenericWebhook/pack_metadata.json
Packs/GenericWebhook_FormData/Integrations/GenericWebhookFormData/GenericWebhookFormData.yml
Packs/GenericWebhook_FormData/ReleaseNotes/1_0_3.md
Packs/GenericWebhook_FormData/pack_metadata.json
Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml
Packs/GitLab/ReleaseNotes/2_2_29.md
Packs/GitLab/pack_metadata.json
Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.yml
Packs/Okta/ReleaseNotes/3_3_15.md
Packs/Okta/pack_metadata.json
Packs/PublishList/Integrations/PublishList/PublishList.yml
Packs/PublishList/ReleaseNotes/1_1_8.md
Packs/PublishList/pack_metadata.json
Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml
Packs/SimpleAPIProxy/ReleaseNotes/1_0_8.md
Packs/SimpleAPIProxy/pack_metadata.json
Packs/Zoom/Integrations/Zoom/Zoom.yml
Packs/Zoom/ReleaseNotes/1_6_28.md
Packs/Zoom/Scripts/ZoomAsk/ZoomAsk.yml
Packs/Zoom/pack_metadata.json

Update content items used `fastapi` docker image to use the latest tag `demisto/fastapi:0.115.12.3243695`

update `fastapi` tag

---

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_6.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

fixes: [XSUP-49874](https://jira-dc.paloaltonetworks.com/browse/XSUP-49874)
Fix ews-get-attachment output returning a CommandResults object to the war room.

Ewso365 get attachment output parsing fix

---

Packs/ThreatGrid/.secrets-ignore
Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.py
Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2.yml
Packs/ThreatGrid/Integrations/ThreatGridv2/ThreatGridv2_test.py
Packs/ThreatGrid/ReleaseNotes/2_0_26.md
Packs/ThreatGrid/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11055)
The URL in the command result were clickable due to angle brackets, removed angle brackets to make them un-clickable

CiscoThreat un-clickable URL

---

Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py
Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule_test.py
Packs/Core/ReleaseNotes/3_3_4.md
Packs/Core/pack_metadata.json
Packs/CortexXDR/ReleaseNotes/6_2_23.md
Packs/CortexXDR/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-51010)
Newly added add_playbook_metadata failed if context dict had sub keys which were None.

handle None keys in context

---

Packs/AMP/CONTRIBUTORS.json
Packs/AMP/Integrations/AMPv2/AMPv2.py
Packs/AMP/Integrations/AMPv2/AMPv2.yml
Packs/AMP/ReleaseNotes/2_1_9.md
Packs/AMP/pack_metadata.json
Packs/CiscoAMP/Integrations/CiscoAMP/CiscoAMP.py
Packs/CiscoAMP/ReleaseNotes/1_0_2.md
Packs/CiscoAMP/pack_metadata.json

Fixing an error in the endpoint command implementation for Cisco AMP. When the IP argument is used with multiple values, only the last response is returned.
I fix a simple mistake in the implementation for the AMPv2 integration. Where not all results for the endpoint command with IP addresses are correctly collected. I also fixed it in the outdated Pack because it is where the mistake originated from.

Fix Cisco AMP endpoint command

---

Packs/PAN-OS/Integrations/Panorama/README.md

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-50324)
Add audit-comment option to `pan-os-edit-rule` documentation

[XSUP-50324] Add audit-comment option to pan-os-edit-rule documentation

---

Packs/Campaign/ReleaseNotes/3_4_23.md
Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py
Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml
Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign_test.py
Packs/Campaign/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-50931)
Added an option for the values of the fields_to_displays to have pipes ("|") in the value.

XSUP-50931: FindEmailCampaign improvements 

---

Packs/MS-ISAC/Integrations/MSISAC/MSISAC.py
Packs/MS-ISAC/ReleaseNotes/1_0_6.md
Packs/MS-ISAC/pack_metadata.json

The MSISAC API defaults to html for several of its error responses, even when you request a json response in the header. Because of this, it causes errors with the OOTB error_handling function in BaseClient, and the html output is very difficult to read in the War Room, and integration test window.

Format MSISAC Error Handling

---

Packs/rasterize/Integrations/rasterize/README.md
Packs/rasterize/Integrations/rasterize/rasterize.py
Packs/rasterize/ReleaseNotes/2_1_8.md
Packs/rasterize/pack_metadata.json
Tests/conf.json

fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-14105) to the issue
This PR improves the documentation in the Rasterize integration README.md by clarifying the instructions for increasing timeout settings when working with large numbers of URLs.

Added Documentation For Rasterize Timeout Configuration Instructions

---

Packs/rasterize/Integrations/rasterize/rasterize.py
Packs/rasterize/Integrations/rasterize/rasterize_test.py
Packs/rasterize/ReleaseNotes/2_1_9.md
Packs/rasterize/pack_metadata.json

fixed: [link](https://jira-dc.paloaltonetworks.com/browse/XSUP-46913) to the issue
Added a 60-second timeout for screenshot capture operations in ***rasterize*** commands to prevent hanging operations.

Add 60-second timeout for Rasterize screenshot capture operations

---

Packs/QRadar/CONTRIBUTORS.json
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/ReleaseNotes/2_5_21.md
Packs/QRadar/pack_metadata.json

Adds in an additional sleep, plus debug log line to address an issue where the integration checks for a search being completed ~5-10 milliseconds after starting it. 
In testing, this reduced the amount of time it took to ingest 36 Offenses from ~5 minutes, down to 1 minute.

QRadar_v3: Added sleep before initial check if query is complete.

---

Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Script_file_added_to_startup-related_Registry_keys.yml
Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_Port_Scan.yml
Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_73.md
Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_74.md
Packs/CortexResponseAndRemediation/pack_metadata.json

Suspicious port scan playbook:
change create indicator and enrich indicator to !file
Script file added to startup-related Registry keys playbook:
change command from 'wildfire-get-verdicts' to  'wildfire-get-verdict'.

Silent_pbs_fixes_portScan_and_Script_added_to_Registry

---

Packs/MicrosoftExchangeOnline/.secrets-ignore
Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
Packs/MicrosoftExchangeOnline/ReleaseNotes/1_6_13.md
Packs/MicrosoftExchangeOnline/pack_metadata.json

Powershell EWS integration uses [Get-MessageTrace APIv1](https://learn.microsoft.com/en-us/powershell/module/exchange/get-messagetrace?view=exchange-ps). Based on documentation both FromIP and ToIP are String type values.
```
Get-MessageTrace
[-FromIP <String>]
[-ToIP <String>]
```
Demisto content integration written in PowerShell treats FromIP and ToIP as MultiValuedProperty, parsing input string with arguments from input to List instead on giving expected value of single IP to `Get-MessageTrace` resulting in runtime error.
```
Error: …
```

ews-message-trace-get from_ip, to_ip bug

---

Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.py
Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml
Packs/Tenable_sc/ReleaseNotes/1_1_3.md
Packs/Tenable_sc/pack_metadata.json

```
Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.py:139: error:(B If x =
b'abc' then f(B"{x}"(B or (B"{}"(B.format(x) produces (B"b'abc'"(B, not (B"abc"(B. If this is
desired behavior, use f(B"{x!r}"(B or (B"{!r}"(B.format(x). Otherwise, decode the bytes 
(B[str-bytes-safe](B
f" body {res.content} with headers {res.headers!s}...(B
^~~~~~~~~~~~~(B
Found 1 error in 1 file (checked 359 source files)(B
```

Update Tenable.sc To python 3.12

---

Packs/Base/ReleaseNotes/1_39_43.md
Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml
Packs/Base/pack_metadata.json

- Updated the Docker image to: *demisto/powershell:7.5.0.3759715*.

Update docker for CommonServerPowerShell

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/Integrations/SlackV3/SlackV3.yml
Packs/Slack/ReleaseNotes/3_5_27.md
Packs/Slack/pack_metadata.json

Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-53362)
Fixed an issue where the script failed to provide detailed error information during Slack event listening and could encounter null pointer exceptions when processing entitlement data.

[Slack V3] Improve error logging with full traceback instead of basic exception message

---

Packs/CortexResponseAndRemediation/Playbooks/playbook-Excessive_User_Account_Lockouts.yml
Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_Local_User_Account_Creation.yml
Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_92.md
Packs/CortexResponseAndRemediation/pack_metadata.json

Ready
- Fixed an issue where the DT transformer that saves evidence to the verdict could receive an empty value, causing the task to fail instead of saving "False" for the corresponding check (due to FirstArrayElement returning Null when the value is empty).
- Added failsafe mechanism with SetIfEmpty to other tasks with such DT
- Added continueonerror for `Excessive User Account Lockouts` failure on the `core-get-endpoints` task which could fail when missing a license

Excessive User Account Lockouts + silent-Suspicious local user account creation dt transformer fix

---

Packs/EmailCommunication/ReleaseNotes/2_0_46.md
Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
Packs/EmailCommunication/pack_metadata.json

relates: [link to issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-53433)
Fixed an issue where the script would fail in the **XSOAR - Email Communication Signature** list could not be loaded.
If running `execute_command` with `fail_on_error` == `False`, the `error_message` is already extracted (if `is_error`).

Fix error handling when loading signature in sendEmailReply script

---

Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch.py
Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch.yml
Packs/Cyberwatch/Integrations/Cyberwatch/Cyberwatch_test.py
Packs/Cyberwatch/Integrations/Cyberwatch/README.md
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_fetch_compliance_asset.json
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_fetch_sysadmin_server.json
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_compliance_assets.json
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_compliance_assets_page.json
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_sysadmin_servers.json
Packs/Cyberwatch/Integrations/Cyberwatch/test_data/test_list_sysadmin_servers_page.json
Packs/Cyberwatch/README.md
Packs/Cyberwatch/ReleaseNotes/1_0_4.md
Packs/Cyberwatch/pack_metadata.json

N/A
Allows Cortex to fetch new data (metadata + compliance scans) from Cyberwatch.
Allows Cortex to send metadata to Cyberwatch.

Cyberwatch integration 1.0.4

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/3_5_28.md
Packs/Slack/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-48610
Adding a debug log which shows the args in the mirror-investigation command.

Slack V3: adding logs for the mirror-investigation command

---

Packs/RedCanary/Integrations/RedCanary/RedCanary.py
Packs/RedCanary/Integrations/RedCanary/RedCanary.yml
Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py
Packs/RedCanary/ReleaseNotes/1_1_28.md
Packs/RedCanary/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-55227)
Fixed an issue where the *redcanary-get-detection* command failed when processing detections with null file paths.

[Red Canary] Handle null file paths in detection timeline processing

---

Packs/Jira/Integrations/JiraV3/JiraV3.py
Packs/Jira/Integrations/JiraV3/JiraV3.yml
Packs/Jira/Integrations/JiraV3/JiraV3_test.py
Packs/Jira/ReleaseNotes/3_3_8.md
Packs/Jira/pack_metadata.json

fixes: [XSUP-55543](https://jira-dc.paloaltonetworks.com/browse/XSUP-55543)
Change issue queries to only use the new endpoint for Jira Cloud environments, as it is not available in the onPrem API.

Jira run query fix endpoint selection

---

Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
Packs/Netskope/Integrations/NetskopeEventCollector/README.md
Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.py
Packs/Netskope/Integrations/NetskopeEventCollector_v2/NetskopeEventCollector_v2.yml
Packs/Netskope/Integrations/NetskopeEventCollector_v2/README.md
Packs/Netskope/ReleaseNotes/4_1_1.md
Packs/Netskope/pack_metadata.json

relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-55598
Following a client complaint, this PR lowers the default limit for the get-events command. A client's playground froze after running the command without specifying a limit, due to the previously high default value.

Decrease default limit netskope collectors

---

Packs/AzureSentinel/IncidentFields/incidentfield-Microsoft_Sentinel_Classification_Reason.json
Packs/AzureSentinel/ReleaseNotes/1_5_71.md
Packs/AzureSentinel/pack_metadata.json

fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-55353?filter=-1
This pr resolves an issue where ms classification reason was set default to inaccurate data even when the field is actually missing.

bug fix - set Microsoft Sentinel Classification Reason to empty if missing 

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/Integrations/Panorama/README.md
Packs/PAN-OS/Integrations/Panorama/test_data/pan-os-check-latest-dynamic-update-status_expected-returned-outputs-no-gp-license.json
Packs/PAN-OS/ReleaseNotes/2_6_9.md
Packs/PAN-OS/pack_metadata.json

fixes: [XSUP-55634](https://jira-dc.paloaltonetworks.com/browse/XSUP-55634).
Fixes several issues in the `pan-os-check-dynamic-updates-status` command: 
1. Handles a scenario where the user runs the command from a Panorama instance without specifying a `target` argument. 
2. Handles a scenario where the checked Firewall doesn't contain any installations on it (instead of failing, we wrapped it with a suitable message). 
3. Handles an error message which received when there is no GP license on the Firewall.

Xsup 55634 panorama fixes

---

Packs/CommunityCommonScripts/ReleaseNotes/1_4_0.md
Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
Packs/CommunityCommonScripts/pack_metadata.json

Due to the lack of updates for the pyjq library over the last three years and its incompatibility with newer Python versions, we have deprecated this transformer. You can now use the official JMESPath transformer instead.

deprecated jq

---

Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
Packs/ThreatConnect/ReleaseNotes/3_1_16.md
Packs/ThreatConnect/pack_metadata.json

fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-55760)
Added "Web Link" to field to list group command output.

feat: add Web Link field to ThreatConnect group list output
