demisto/content

- Utils/should_trigger_test_upload.sh
> run test-upload-flow in sdk nightly

- Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.py
- Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.yml
- Packs/ProofpointThreatResponse/ReleaseNotes/2_0_9.md
- Packs/ProofpointThreatResponse/pack_metadata.json
> [ProofpointThreatResponse] Fix LastRun setting in event collector

- Packs/CommonDashboards/Dashboards/dashboard-My_Threat_Landscape.json
- Packs/CommonDashboards/ReleaseNotes/1_3_2.md
- Packs/CommonDashboards/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6418)
Changed the default date range4 from 180 days to 30.
> Fixd Dashboard  date range

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
- Packs/SplunkPy/ReleaseNotes/3_0_16.md
- Packs/SplunkPy/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6438
fixed the 404 error in the *splunk-results* command.
> fix splunk 404 error msg

- Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py
Un-comment unit-tests of `SearchIncidentsV2`
> [SearchIncidentsV2] - update unit-tests

- Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6462)
changed in task 19 - 'Send Mail' the email address from 'testbox@demistodev.onmicrosoft.com' to 'testbox2@demistodev.onmicrosoft.com'
> [MSGraphMail] - TPB - mail-sending loop

- Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
- Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule_test.py
- Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_linux_response.json
- Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_mac_response.json
- Packs/ApiModules/Scripts/CoreIRApiModule/test_data/get_endpoints_windows_response.json
- Packs/Core/ReleaseNotes/1_3_49.md
- Packs/Core/pack_metadata.json
- Packs/CortexXDR/ReleaseNotes/4_10_37.md
- Packs/CortexXDR/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-79175)
- Fixed bug when running "core-retrieve-files" command with "generic_field_path" argument and endpoint from 'os_type = macos' was failing.
- Added logs to the CoreIRApiModule.
> [CoreIRApiModule] fix bug in retrieve-files

- Packs/CiscoWebExFeed/pack_metadata.json
- Packs/FeedAWS/pack_metadata.json
- Packs/FeedAzure/pack_metadata.json
- Packs/FeedAzureADConnectHealth/pack_metadata.json
- Packs/FeedCloudflare/pack_metadata.json
- Packs/FeedFastly/pack_metadata.json
- Packs/FeedGCPWhitelist/pack_metadata.json
- Packs/FeedMicrosoftIntune/pack_metadata.json
- Packs/FeedOffice365/pack_metadata.json
- Packs/FeedPublicDNS/pack_metadata.json
- Packs/FeedZoom/pack_metadata.json
- Packs/FreeFeeds/pack_metadata.json
- Tests/Marketplace/approved_tags.json
Added all the "Allow List" feeds to the Free Feeds pack.
> FreeFeeds - Added all "Allow list" feeds to the pack and relevant tags.

- poetry.lock
Revert changes merge by mistake in https://github.com/demisto/content/pull/25620
> Revert poetry.lock wrong changes

- .github/workflows/review-release-notes.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6524
> set pythonpath to review release notes

- Packs/FeedMandiant/Integrations/FeedMandiant/FeedMandiant.yml
- Packs/FeedMandiant/ReleaseNotes/1_0_13.md
- Packs/FeedMandiant/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6516
- Deprecate the Manidant Feed
- Hide the deprecated pack
> Deprecate Mandiant feed

- Tests/Marketplace/core_packs_list.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-81639
This PR adds all the core packs as auto-update packs (to be installed automatically upon upgrade).
> Updated the update_core_packs_list

- poetry.lock
- pyproject.toml
> 1.14.1 release

- Packs/Slack/Integrations/SlackV3/SlackV3.yml
- Packs/Slack/ReleaseNotes/3_1_35.md
- Packs/Slack/pack_metadata.json
> [SlackV3] Added support for war room mentions

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
- Packs/SplunkPy/ReleaseNotes/3_0_17.md
- Packs/SplunkPy/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-24112)
Fixed an issue where proxy parameter wasn't parsed correctly.
> [splunk] fix for proxy parameter wasn't parsed correctly

- .hooks/bootstrap
- .hooks/pre-commit
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> Run pre-commit hook with poetry env

- Packs/FeedMandiant/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6516)
Hide the deprecated Manidant Feed
> Hide manidant feed

- Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
- Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
- Packs/ArcherRSA/ReleaseNotes/1_2_10.md
- Packs/ArcherRSA/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23833
fixed an issue that causes the integration to use a `None` variable when the result was in an unexpected format.
> fix archer get record unexpected response format

- .hooks/pre-commit
- pyproject.toml
> ruff check F821

- Packs/FortiGate/ParsingRules/FortiGate/FortiGate.xif
- Packs/FortiGate/README.md
- Packs/FortiGate/ReleaseNotes/1_0_20.md
- Packs/FortiGate/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-23945)
> Fortinet Fortigate fix

- .gitlab/ci/.gitlab-ci.yml
- Tests/docker_native_image_config.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6550)
update `native:candidate` to latest `native:dev`
> update the native:candiadte to latest native:dev

- .gitlab/ci/.gitlab-ci.yml
> add demisto-sdk logs to gitlab

- Utils/github_workflow_scripts/handle_external_pr.py
> changed reviewers

- Packs/CommonDashboards/Dashboards/dashboard-APIExecutionMetrics.json
- Packs/CommonDashboards/ReleaseNotes/1_3_4.md
- Packs/CommonDashboards/pack_metadata.json
- Packs/IntSight/ReleaseNotes/3_0_1.md
- Packs/IntSight/Widgets/Widget-API_Call_Results_for_Rapid7_Threat_Command.json
- Packs/IntSight/pack_metadata.json
> Rapid7 widget id update

- .devcontainer/Dockerfile
- .devcontainer/createCommand.sh
- .devcontainer/devcontainer.json
- .devcontainer/settings.json
- .github/workflows/check-devcontainer.yml
- .vscode/extensions.json
update devcontainer features commit
Update extensions.json
Update setttings.json
Update CI
Enable pre-commit in devcontainer
> devcontainer updates

- Packs/CommonPlaybooks/Playbooks/playbook-Extract_Indicators_From_File_-_Generic_v2_4_5.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_3_66.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24210
Fixed an issue where otf files were identified as word files.
> Extract indicators exclude oft

- Packs/TeamViewer/.secrets-ignore
- Packs/TeamViewer/README.md
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6680)
fixes the read me of team viewer
> TeamViewer readme fix

- Packs/Jira/Integrations/JiraV2/JiraV2.py
- Packs/Jira/Integrations/JiraV2/JiraV2.yml
- Packs/Jira/Integrations/JiraV2/JiraV2_test.py
- Packs/Jira/ReleaseNotes/2_0_36.md
- Packs/Jira/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-24339)
> Fixing an issue in Jira v2 when the language is not English

- Packs/CommonScripts/ReleaseNotes/1_11_75.md
- Packs/CommonScripts/Scripts/EmailAskUser/EmailAskUser.js
- Packs/CommonScripts/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15556
> fix subject concat EmailAskUser script

- Packs/DemistoRESTAPI/ReleaseNotes/1_3_25.md
- Packs/DemistoRESTAPI/Scripts/DemistoUploadFileV2/DemistoUploadFileV2.yml
- Packs/DemistoRESTAPI/pack_metadata.json
Fixes typo in the deprecation description https://panw-global.slack.com/archives/C011E5T5K17/p1684438989644909
> Fix upload file typo

- .github/workflows/pre-commit.yml
> show diff on failure precommit

- Packs/Opsgeniev2/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6615)
Hide the Opsgenie v2 pack.
> hide Opsgenie v2 pack

- Packs/Base/ReleaseNotes/1_32_5.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
related: https://jira-hq.paloaltonetworks.local/browse/XSUP-24343
> except JSONDecodeError

- Packs/NonSupported/IndicatorFields/incidentfield-tagsMultiSelectType.json
- Packs/NonSupported/IndicatorTypes/reputation-fqdn_5_4_9.json
- Packs/NonSupported/IndicatorTypes/reputation-ip_5_4_9.json
- Packs/NonSupported/Integrations/QRadar_5_4_9/QRadar_5_4_9.yml
- Packs/NonSupported/Integrations/integration-VirusTotal_5_1_0.yml
- Packs/NonSupported/Scripts/SaneDocReport/SaneDocReport.yml
- Packs/NonSupported/Scripts/script-CommonServerUserPowerShell.yml
- Packs/NonSupported/Scripts/script-CommonServerUserPython.yml
- Packs/NonSupported/Scripts/script-CommonUserServer.yml
- Packs/NonSupported/TestPlaybooks/playbook-TestDedupIncidentsByName.yml
- Packs/NonSupported/TestPlaybooks/playbook-TestDedupIncidentsPlaybook.yml
- Packs/NonSupported/pack_metadata.json
Deprecate the 'Non Supported' pack to avoid having to fix validation errors on its items (which are no longer supported).
> Deprecate 'Non Supported' Pack

- Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Endpoint_Investigation.yml
- Packs/CortexXDR/ReleaseNotes/4_10_43.md
- Packs/CortexXDR/ReleaseNotes/4_10_44.md
- Packs/CortexXDR/TestPlaybooks/Test_Playbook_-_Cortex_XDR_-_Endpoint_Investigation.yml
- Packs/CortexXDR/pack_metadata.json
- Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6705
Test playbook for the ‘Cortex XDR - Endpoint Investigation’ playbook, which is part of the malware investigation and response pack.
> Test Playbook For 'Cortex XDR - Endpoint Investigation'

- Packs/CommonTypes/IncidentFields/incidentfield-Alert_Source.json
- Packs/CommonTypes/IncidentFields/incidentfield-Source_Priority.json
- Packs/CommonTypes/IncidentFields/incidentfield-Source_Status.json
- Packs/CommonTypes/ReleaseNotes/3_3_70.md
- Packs/CommonTypes/pack_metadata.json
- Packs/OpsGenie/.pack-ignore
- Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Alias.json
- Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Count_Linked_Alerts.json
- Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_Responder.json
- Packs/OpsGenie/IncidentFields/incidentfield-OpsGenie_TinyId.json
- Packs/OpsGenie/ReleaseNotes/2_0_14.md
- Packs/OpsGenie/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-19906
Changed some incident fields in the packs **CommonTypes**, and **OpsGenie** to be searchable.
> Unsearchable common type incident fields

- Packs/CommonScripts/ReleaseNotes/1_11_79.md
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
- Packs/CommonScripts/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-23605
Update the docker image to support bug fixes in parse-emails package.
> Parse emails docker update

- Packs/Vectra/Integrations/Vectra/Vectra.yml
- Packs/Vectra/Integrations/Vectra_v2/README.md
- Packs/Vectra/Integrations/Vectra_v2/Vectra_v2.yml
- Packs/Vectra/README.md
- Packs/Vectra/ReleaseNotes/1_0_11.md
- Packs/Vectra/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-5928
Deprecate Vectra Pack.
@bakatzir - FYI.
> Deprecate Vectra Pack

- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_description.md
- Packs/CortexXDR/Integrations/CortexXDRIR/README.md
- Packs/CortexXDR/ReleaseNotes/4_10_45.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-80426
XDR integrations had wrong description for how to get the URL of XDR.
> Bugfix/xdr URL instructions

- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
- Packs/ServiceNow/ReleaseNotes/2_5_23.md
- Packs/ServiceNow/pack_metadata.json
fixes: [XSUP-22390](https://jira-hq.paloaltonetworks.local/browse/XSUP-22390)
> Snow v2 fix 404 handling

- Packs/PAN-OS/Integrations/Panorama/Panorama.yml
- Packs/PAN-OS/Integrations/Panorama/README.md
- Packs/PAN-OS/ReleaseNotes/1_17_2.md
- Packs/PAN-OS/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6724
Edit documentation for ***pan-os-list-rules*** command.
> [PAN-OS] Edit documentation 

- Packs/Gmail/Integrations/Gmail/README.md
Removed extra line break between text and images
> Update Gmail Integration README.md

- .markdownlint.json
> add mardkownlint config

- Packs/CiscoASA/ModelingRules/CiscoASA_1_3/CiscoASA_1_3_testdata.json
> fixed test modeling rules

- Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
- Packs/qualys/ReleaseNotes/1_2_10.md
- Packs/qualys/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/EXPANDR-4226
Changes Qualys integration category to "Vulnerability Management" which is should be
n/a
> Qualys expandr 4226

- Packs/FireEyeHX/README.md
> Fixed readme file.

- Packs/ProofpointTAP/README.md
fixes: CIAC-6816 Bug.
This PR is created to fix the README for Proofpoint TAP to include the proper XDR documentaion.
> Fix for Proofpoint TAP README

- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
- Packs/ServiceNow/ReleaseNotes/2_5_25.md
- Packs/ServiceNow/pack_metadata.json
> Snow resending mirrored attachments bug

- Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA.py
- Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA.yml
- Packs/TrendMicroDDA/Integrations/TrendMicroDDA/TrendMicroDDA_test.py
- Packs/TrendMicroDDA/ReleaseNotes/1_0_13.md
- Packs/TrendMicroDDA/pack_metadata.json
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-24781)
> TrendMicroDDA - Add encoding to the url and an UT

- Packs/Netmiko/Integrations/Netmiko/Netmiko.yml
- Packs/Netmiko/Integrations/Netmiko/README.md
- Packs/Netmiko/ReleaseNotes/1_0_3.md
- Packs/Netmiko/pack_metadata.json
> Fix "cmds" command argument and update markdown

- Packs/TruSTAR/ReleaseNotes/2_1_17.md
- Packs/TruSTAR/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-6844
Changed pack support to community.
> St trustart to community

- .github/workflows/autobump_rn.yml
- .github/workflows/check-contributor-pack.yml
- .github/workflows/close_jira_issue_by_pr_merge.yml
- .github/workflows/link_edited_pr_to_jira_issue.yml
- .github/workflows/run-secrets-detection.yml
- .github/workflows/trigger-contribution-build.yml
> Update setup poetry version to 8

- Packs/Envoy/.pack-ignore
- Packs/Envoy/Integrations/EnvoyIAM/EnvoyIAM.py
- Packs/Envoy/Integrations/EnvoyIAM/EnvoyIAM.yml
- Packs/Envoy/ReleaseNotes/1_0_7.md
- Packs/Envoy/pack_metadata.json
- Packs/ExceedLMS/.pack-ignore
- Packs/ExceedLMS/Integrations/IAMExceedLMS/IAMExceedLMS.py
- Packs/ExceedLMS/Integrations/IAMExceedLMS/IAMExceedLMS.yml
- Packs/ExceedLMS/ReleaseNotes/1_0_7.md
- Packs/ExceedLMS/pack_metadata.json
> Align credentials stores part 8

- Packs/CommonScripts/Scripts/IdentifyAttachedEmail/IdentifyAttachedEmail.yml
- Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4161
the playbook should work well
> Unskipp test playbook

- Packs/Gamma/.pack-ignore
- Packs/Gamma/Integrations/Gamma/Gamma.py
- Packs/Gamma/Integrations/Gamma/Gamma.yml
- Packs/Gamma/ReleaseNotes/1_0_16.md
- Packs/Gamma/pack_metadata.json
- Packs/Telegram/Integrations/Telegram/Telegram.py
- Packs/Telegram/Integrations/Telegram/Telegram.yml
- Packs/Telegram/ReleaseNotes/1_0_6.md
- Packs/Telegram/pack_metadata.json
> Align credentials stores part 9

- .github/workflows/pre-commit.yml
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
> precommit fix MDX server

- Packs/EDL/Integrations/EDL/EDL.yml
- Packs/EDL/Integrations/EDL/EDL_description.md
- Packs/EDL/ReleaseNotes/3_1_27.md
- Packs/EDL/pack_metadata.json
Fixed a typo in the description for XSIAM.
> [EDL] Fixed a typo in the description

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_20.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24902
Fixed an issue where the tags argument did not appear in the cs-falcon-upload-custom-ioc command.
> Cs falcon add tags to cs-falcon-upload-custom-ioc command

- Packs/Syslog/.pack-ignore
- Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
- Packs/Syslog/ReleaseNotes/2_0_16.md
- Packs/Syslog/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-24927
> Syslogv2 was removed from xsiam marketplace

- Packs/FeedLOLBAS/pack_metadata.json
- Packs/FreeFeeds/pack_metadata.json
Tag was missing from pack meta data.
> LOLBAS - Added "Plug & Fetch" tag

- Packs/SysAid/Integrations/SysAid/README.md
- Packs/SysAid/Integrations/SysAid/SysAid.py
- Packs/SysAid/Integrations/SysAid/SysAid.yml
- Packs/SysAid/Integrations/SysAid/SysAid_test.py
- Packs/SysAid/Integrations/SysAid/command_examples
- Packs/SysAid/Integrations/SysAid/test_data/input_data.py
- Packs/SysAid/ReleaseNotes/1_0_7.md
- Packs/SysAid/pack_metadata.json
Continues #25442
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-21748
> Sysaid delete-file, get, add-note, record-attach-file

- Packs/CommonTypes/IndicatorFields/incidentfield-Action.json
- Packs/CommonTypes/ReleaseNotes/3_3_73.md
- Packs/CommonTypes/pack_metadata.json
This was asked by an SA as part of the work he is doing for a customer.
> Associate "Action" indicator field to all indicator types

- Packs/CommonTypes/IndicatorFields/indicatorfield-Action.json
- Packs/CommonTypes/ReleaseNotes/3_3_74.md
- Packs/CommonTypes/pack_metadata.json
> Fixed file name to be "indicatorfield"

- Packs/FireEyeHX/README.md
> FIreeye HX - update readme file

- Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/MicrosoftGraphTeams_description.md
- Packs/MicrosoftGraphTeams/ReleaseNotes/1_0_7.md
- Packs/MicrosoftGraphTeams/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25141
> MSGraphTeams fix path in the documentation

- Packs/Base/ReleaseNotes/1_32_12.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
> Fix common server python mypy

- Packs/CiscoISR/.pack-ignore
> ignore modeling/parsing rules suffix validate

- Packs/FireEyeETP/.pack-ignore
- Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.py
- Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.yml
- Packs/FireEyeETP/ReleaseNotes/1_2_3.md
- Packs/FireEyeETP/pack_metadata.json
- Packs/Zimperium/.pack-ignore
- Packs/Zimperium/Integrations/Zimperium/Zimperium.py
- Packs/Zimperium/Integrations/Zimperium/Zimperium.yml
- Packs/Zimperium/ReleaseNotes/1_1_9.md
- Packs/Zimperium/pack_metadata.json
> Align credentials stores part 16

- Packs/ForcepointSWG/.pack-ignore
https://github.com/demisto/demisto-sdk/pull/3110
> Ignore rules suffix validate

- Packs/Workday/Integrations/WorkdayEventCollector/WorkdayEventCollector.yml
- Packs/Workday/ReleaseNotes/1_3_2.md
- Packs/Workday/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-85295)
Added marketplaces to event collector yml.
> added marketplaces to event collector yml

- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
- Packs/VirusTotal/ReleaseNotes/2_6_4.md
- Packs/VirusTotal/pack_metadata.json
> [VirusTotal] Fix only_stats default value

- .github/workflows/pre-commit.yml
> precommit run on sdk 1.15.5

- Packs/CiscoSpark/.pack-ignore
- Packs/CiscoSpark/Integrations/CiscoSpark/CiscoSpark.js
- Packs/CiscoSpark/Integrations/CiscoSpark/CiscoSpark.yml
- Packs/CiscoSpark/ReleaseNotes/1_0_3.md
- Packs/CiscoSpark/pack_metadata.json
- Packs/CloudLock/.pack-ignore
- Packs/CloudLock/Integrations/CiscoCloudLock/CiscoCloudLock.js
- Packs/CloudLock/Integrations/CiscoCloudLock/CiscoCloudLock.yml
- Packs/CloudLock/ReleaseNotes/1_0_1.md
- Packs/CloudLock/pack_metadata.json
- Packs/Giphy/.pack-ignore
- Packs/Giphy/Integrations/Giphy/Giphy.js
- Packs/Giphy/Integrations/Giphy/Giphy.yml
- Packs/Giphy/Integrations/Giphy/README.md
- Packs/Giphy/Integrations/Giphy/examples.txt
- Packs/Giphy/ReleaseNotes/1_0_2.md
- Packs/Giphy/pack_metadata.json
- Packs/PacketMail/.pack-ignore
- Packs/PacketMail/Integrations/PacketMail/PacketMail.js
- Packs/PacketMail/Integrations/PacketMail/PacketMail.yml
- Packs/PacketMail/ReleaseNotes/1_0_3.md
- Packs/PacketMail/pack_metadata.json
- Packs/RsaNetWitnessPacketsAndLogs/.pack-ignore
- Packs/RsaNetWitnessPacketsAndLogs/Integrations/RSANetWitnessPacketsAndLogs/RSANetWitnessPacketsAndLogs.js
- Packs/RsaNetWitnessPacketsAndLogs/Integrations/RSANetWitnessPacketsAndLogs/RSANetWitnessPacketsAndLogs.yml
- Packs/RsaNetWitnessPacketsAndLogs/ReleaseNotes/1_0_5.md
- Packs/RsaNetWitnessPacketsAndLogs/pack_metadata.json
fixes: [Align Credentials for CiscoSpark, RSANetWitnessPacketsAndLogs, Giphy, PacketMail, CiscoCloudLock](https://jira-hq.paloaltonetworks.local/browse/CIAC-6946)
Aligns creds for:
- CiscoSpark
- RSANetWitnessPacketsAndLogs
- Giphy
- PacketMail
- CiscoCloudLock 
> Align Credentials part 4 (JavaScript)

- Packs/AlibabaActionTrail/ReleaseNotes/1_0_16.md
- Packs/AlibabaActionTrail/XSIAMDashboards/AlibabaActionTrail_Dashboard.json
- Packs/AlibabaActionTrail/pack_metadata.json
- Packs/CyberArkIdentity/ReleaseNotes/1_0_24.md
- Packs/CyberArkIdentity/XSIAMDashboards/CyberArkIdentity_Dashboard.json
- Packs/CyberArkIdentity/pack_metadata.json
- Packs/Dropbox/ReleaseNotes/1_0_22.md
- Packs/Dropbox/XSIAMDashboards/Dropbox_Dashboard.json
- Packs/Dropbox/pack_metadata.json
- Packs/GitLab/ReleaseNotes/2_2_9.md
- Packs/GitLab/XSIAMDashboards/GitLab_Overview_-_Dashboard.json
- Packs/GitLab/pack_metadata.json
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_26.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/XSIAMDashboards/MicrosoftDefenderAdvancedThreatProtection_Dashboard.json
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
- Packs/MicrosoftWindowsEvents/ReleaseNotes/1_0_3.md
- Packs/MicrosoftWindowsEvents/XSIAMDashboards/MicrosoftWindowsEvents_Dashboard.json
- Packs/MicrosoftWindowsEvents/pack_metadata.json
Fixed the from version in some xsiam dashboards to be 6.10.0.
> Add fromversion to files

- Packs/FeedZeroDayLiveTIFusion/Integrations/FeedZeroDayLiveTIFUSION/FeedZeroDayLiveTIFUSION.yml
- Packs/FeedZeroDayLiveTIFusion/README.md
- Packs/FeedZeroDayLiveTIFusion/ReleaseNotes/1_0_1.md
- Packs/FeedZeroDayLiveTIFusion/pack_metadata.json
This changes are updating description of the Zero Day Live Feed pack
> Updated description

- Packs/VMRay/Integrations/VMRay/VMRay.py
- Packs/VMRay/Integrations/VMRay/VMRay.yml
- Packs/VMRay/Integrations/VMRay/VMRay_test.py
- Packs/VMRay/ReleaseNotes/1_1_10.md
- Packs/VMRay/pack_metadata.json
Remove forbidden characters from the file name before submitting the file to VMRay.
> [VMRay] fix encoding of file names

- Packs/MxToolBox/.pack-ignore
- Packs/MxToolBox/Integrations/MxToolBox/MxToolBox.js
- Packs/MxToolBox/Integrations/MxToolBox/MxToolBox.yml
- Packs/MxToolBox/Integrations/MxToolBox/README.md
- Packs/MxToolBox/ReleaseNotes/1_0_2.md
- Packs/MxToolBox/pack_metadata.json
- Packs/TrendMicroDeepSecurity/.pack-ignore
- Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.py
- Packs/TrendMicroDeepSecurity/Integrations/TrendMicroDeepSecurity/TrendMicroDeepSecurity.yml
- Packs/TrendMicroDeepSecurity/ReleaseNotes/1_0_8.md
- Packs/TrendMicroDeepSecurity/pack_metadata.json
> Align credentials stores part 18

- Packs/CommonPlaybooks/Playbooks/playbook-Ticket_Management_-_Generic.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_3_76.md
- Packs/CommonPlaybooks/pack_metadata.json
- Packs/Core/Playbooks/playbook-Cloud_IAM_User_Access_Investigation.yml
- Packs/Core/Playbooks/playbook-IOC_Alert.yml
- Packs/Core/Playbooks/playbook-Impossible_Traveler.yml
- Packs/Core/Playbooks/playbook-Local_Analysis_alert_Investigation.yml
- Packs/Core/Playbooks/playbook-NGFW_Internal_Scan.yml
- Packs/Core/Playbooks/playbook-NGFW_Scan.yml
- Packs/Core/Playbooks/playbook-Ransomware_Response.yml
- Packs/Core/Playbooks/playbook-T1036_-_Masquerading.yml
- Packs/Core/Playbooks/playbook-T1059_-_Command_and_Scripting_Interpreter.yml
- Packs/Core/Playbooks/playbook-WildFire_Malware.yml
- Packs/Core/Playbooks/playbook-XCloud_Cryptomining.yml
- Packs/Core/ReleaseNotes/1_4_3.md
- Packs/Core/pack_metadata.json
- Packs/ServiceNow/Playbooks/playbook-ServiceNow_-_Ticket_Management.yml
- Packs/ServiceNow/Playbooks/playbook-ServiceNow_-_Ticket_Management_README.md
- Packs/ServiceNow/ReleaseNotes/2_5_29.md
- Packs/ServiceNow/pack_metadata.json
Added skip if unavailable true for Set Incident Severity to High task in core playbooks.
> Incident context core pb fix

- Packs/PhishingURL/ReleaseNotes/1_1_2.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
- Packs/PhishingURL/TestPlaybooks/DBotPredictURLPhishing_test.yml
- Packs/PhishingURL/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7044)
* Fixed an issue where the script would fail in cases where no result was returned from **WhoIs** integration.
* Added retry mechanism to the test-playbook that failed.
> [DBotPredictURLPhishing] - fix bug with None entires

- Packs/CTIX/Integrations/CTIX/CTIX.yml
- Packs/CTIX/Integrations/CTIXv3/CTIXv3.py
- Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml
- Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py
- Packs/CTIX/Integrations/CTIXv3/README.md
- Packs/CTIX/Integrations/CTIXv3/command_examples
- Packs/CTIX/Integrations/CTIXv3/test_data/get_cve_threat_data.json
- Packs/CTIX/Integrations/CTIXv3/test_data/get_cvss_score.json
- Packs/CTIX/Integrations/CTIXv3/test_data/get_vulnerability_product_details.json
- Packs/CTIX/Integrations/CTIXv3/test_data/get_vulnerability_source_description.json
- Packs/CTIX/ReleaseNotes/2_2_10.md
- Packs/CTIX/pack_metadata.json
Add new `ctix-get-vulnerability-data` and `cve` commands to CTIXv3 integration.
> CVE command

- Packs/MacOS/ModelingRules/MacOS/MacOS.xif
- Packs/MacOS/ModelingRules/MacOS/MacOS_schema.json
- Packs/MacOS/README.md
- Packs/MacOS/ReleaseNotes/1_0_2.md
- Packs/MacOS/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6986)
> MacOS Update

- Packs/Workday/ParsingRules/WorkdayParsingRules/WorkdayParsingRules.yml
- Packs/Workday/ReleaseNotes/1_3_4.md
- Packs/Workday/pack_metadata.json
Changed workday parsing rule id
> fix workday parsing rule id

- Packs/ForcepointDLP/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-86122
> remove xsoar marketplace

- Packs/MicrosoftGraphListener/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-86125
Hide Microsoft Graph Mail Single User pack.
> Hide Microsoft Graph Mail Single User pack

- Packs/LogRhythmRest/.pack-ignore
- Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.py
- Packs/LogRhythmRest/Integrations/LogRhythmRest/LogRhythmRest.yml
- Packs/LogRhythmRest/ReleaseNotes/2_0_19.md
- Packs/LogRhythmRest/pack_metadata.json
- Packs/Stealthwatch_Cloud/.pack-ignore
- Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.py
- Packs/Stealthwatch_Cloud/Integrations/Stealthwatch_Cloud/Stealthwatch_Cloud.yml
- Packs/Stealthwatch_Cloud/ReleaseNotes/1_0_12.md
- Packs/Stealthwatch_Cloud/pack_metadata.json
> Align credentials stores -  part 24

- Packs/TIM_Processing/Layouts/layoutscontainer-Review_Indicators_Manually.json
- Packs/TIM_Processing/Layouts/layoutscontainer-Review_Indicators_Manually_For_Whitelisting.json
- Packs/TIM_Processing/ReleaseNotes/1_1_19.md
- Packs/TIM_Processing/pack_metadata.json
changed the mp to be xsoar only
> added mp to tim processing layouts

- Packs/CrowdStrikeMalquery/.pack-ignore
- Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.py
- Packs/CrowdStrikeMalquery/Integrations/CrowdStrikeMalquery/CrowdStrikeMalquery.yml
- Packs/CrowdStrikeMalquery/ReleaseNotes/1_0_26.md
- Packs/CrowdStrikeMalquery/pack_metadata.json
- Packs/RsaNetwitnessSecurityAnalytics/.pack-ignore
- Packs/RsaNetwitnessSecurityAnalytics/Integrations/RSANetWitnessSecurityAnalytics/RSANetWitnessSecurityAnalytics.js
- Packs/RsaNetwitnessSecurityAnalytics/Integrations/RSANetWitnessSecurityAnalytics/RSANetWitnessSecurityAnalytics.yml
- Packs/RsaNetwitnessSecurityAnalytics/ReleaseNotes/1_0_10.md
- Packs/RsaNetwitnessSecurityAnalytics/pack_metadata.json
> Align credentials stores part 28

- Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Verify_Containment_Actions.yml
- Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Verify_Containment_Actions_README.md
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_27.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7188
The 'Get full detection details' task, which uses 'Set' automation, has an incorrect value for the 'key' input.
As the 'key' input was set to 'Detection.Behavior.pattern_disposition_details', all of the tasks within the playbook relate to 'Detection.Behavior'.
> Changed the 'key' input value of the 'Get full detection details' task

- Packs/CommonScripts/ReleaseNotes/1_11_89.md
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-25423)
Related: https://github.com/demisto/parse-emails/pull/65
> ParseEmailFilesV2: update Docker

- Packs/BPA/.pack-ignore
- Packs/BPA/Integrations/BPA/BPA.py
- Packs/BPA/Integrations/BPA/BPA.yml
- Packs/BPA/ReleaseNotes/1_2_21.md
- Packs/BPA/pack_metadata.json
- Packs/Cisco-umbrella/.pack-ignore
- Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py
- Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
- Packs/Cisco-umbrella/ReleaseNotes/1_0_17.md
- Packs/Cisco-umbrella/pack_metadata.json
fixes: [CIAC-7191](https://jira-hq.paloaltonetworks.local/browse/CIAC-7191)
Align Credentials for BPA, Cisco-umbrella-investigate
> Align Credentials for BPA, Cisco-umbrella-investigate

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
- Packs/SplunkPy/ReleaseNotes/3_0_22.md
- Packs/SplunkPy/pack_metadata.json
- code improvement (ruff rules)
> [SplunkPy] code improvement

- Packs/Base/ReleaseNotes/1_32_17.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7168
> Disable `urllib3` warnings in CSP

- .github/CODEOWNERS
Just taking ownership of TIM code.
> Taking ownership of TIM code and some TIM main integrations

- Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.py
- Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml
- Packs/ArcherRSA/ReleaseNotes/1_2_13.md
- Packs/ArcherRSA/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-23833
added a new cache for field names in case the filed name is not a part of the response.
> fix None type header in archer

- Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_Malware_-_Verify_Containment_Actions.yml
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_28.md
- Packs/CrowdStrikeFalcon/TestPlaybooks/Test_Playbook_-_CrowdStrike_Falcon_Malware_-_Verify_Containment_Actions.yml
- Packs/CrowdStrikeFalcon/pack_metadata.json
- Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7212
Test playbook for the ‘CrowdStrike Falcon Malware - Verify Containment Actions’ playbook
> Test Playbook - CrowdStrike Falcon Malware - Verify Containment Actions

- Packs/MicrosoftDefenderAdvancedThreatProtection/Playbooks/playbook-MDE_-_Retrieve_File.yml
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_28.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_15_29.md
- Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Test_Playbook_-_MDE_-_Retrieve_File.yml
- Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
- Tests/conf.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7243
test playbook for ‘MDE - Retrieve File’
> Test Playbook For MDE - Retrieve File

- .github/workflows/protect-infra-directories.yml
- Packs/Base/ReleaseNotes/1_32_19.md
- Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
- Packs/Base/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6932)
> Update DBotPredictPhishingWords docker

- Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.py
- Packs/AbnormalSecurity/Integrations/AbnormalSecurity/AbnormalSecurity.yml
- Packs/AbnormalSecurity/Integrations/AbnormalSecurity/README.md
- Packs/AbnormalSecurity/Integrations/AbnormalSecurity/command_examples
- Packs/AbnormalSecurity/ReleaseNotes/2_0_21.md
- Packs/AbnormalSecurity/pack_metadata.json
None
This PR updates some out of date documentation and removes a deprecated endpoint. It also changes the request timeout from 60s to 300s.
N/A
- Further details: it removes an existing command
> [AbnormalSecurity] Update documentation and examples

- Packs/Campaign/ReleaseNotes/3_3_3.md
- Packs/Campaign/Scripts/CollectCampaignRecipients/CollectCampaignRecipients.py
- Packs/Campaign/Scripts/CollectCampaignRecipients/CollectCampaignRecipients.yml
- Packs/Campaign/pack_metadata.json
- Packs/CommonScripts/Scripts/UnzipFile/data_test/testZip.yml
- Packs/KasperskySecurityCenter/TestPlaybooks/Kaspersky_Security_Center_-_Test.yml
- Tests/conf.json
> Kaspersky Security Center - add test pb to conf.json

- Packs/PhishingURL/ReleaseNotes/1_1_3.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
- Packs/PhishingURL/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6885)
Update error message in case Rasterize data is not complete to be more specific (see JIRA ticket for full context)
> [DBotPredictURLPhishing] Update Error Message

- Packs/ForcepointDLP/README.md
> forcepoint dlp update readme

- Packs/Traceable/pack_metadata.json
fixes: https://github.com/mtraceable/content/commit/6f49e5235234584b367a4b7f71646f78aeedb407
Corrected the Author for the pack
> Corrected "author"

- Packs/CommonScripts/ReleaseNotes/1_11_92.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-25768
Added a BC note for the fix merged in version 1.11.92
> GetListRow: added bc

- Packs/HelloWorld/Playbooks/playbook-Handle_Hello_World_Alert.yml
Test for https://github.com/demisto/content/pull/27940.
> TEST | CIAC-4682 | Test External PR/Security Review and Assignment

- Packs/HelloWorld/Playbooks/playbook-Handle_Hello_World_Alert.yml
Test for https://github.com/demisto/content/pull/27940.
> TEST | CIAC-4682

- Packs/Slack/Integrations/SlackEventCollector/SlackEventCollector.py
- Packs/Slack/ReleaseNotes/3_1_42.md
- Packs/Slack/pack_metadata.json
fixes: [XSUP-24909](https://jira-hq.paloaltonetworks.local/browse/XSUP-24909)
> slack collector add retries

- .gitlab/ci/bucket-upload.yml
- .gitlab/ci/global.yml
remove duplicate conf clone from CI.
> remove duplicate conf clone

- Packs/Core/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7420
Fixed the broken link in markteplace.
> Fix core readme pack broken link

- Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
- Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_5.md
- Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Corrects the source of the `MScore` table field from the DBot Score to the MScore
> Properly sourcing `mscore` for `fetch_reputation` function

- Packs/Core/pack_metadata.json
- Packs/CortexXDR/pack_metadata.json
> false mandatory - fix upload

- .github/pull_request_template.md
> Shorter pull_request_template.md

- Packs/CommonScripts/ReleaseNotes/1_12_3.md
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26219
Added decoding for an attached file name with special characters.
> Upgrade the docker image for parse emails

- .gitlab/ci/global.yml
contrib build: https://code.pan.run/xsoar/content/-/jobs/29378346
> add stop section for external contrib builds

- .github/content_roles.json
- .github/contribution_team.json
fixes: [Add Github label to better handle contributions.](https://jira-hq.paloaltonetworks.local/browse/CIAC-4862)
> Add comment and reviewers to contributed PRs

- Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml
- Packs/Orca/Integrations/OrcaEventCollector/OrcaEventCollector.yml
https://github.com/demisto/demisto-sdk/pull/3357/
Added the `marketplaces` field to the ymls of the event collectors: Darktrace and Orca
> Added the mp field to the yml

- .github/CODEOWNERS
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.slack-notify.yml
Fixes more places that includes the gitlab-ci files as before they [were renamed](https://github.com/demisto/content/pull/28289/files).
> Fix slack-notify file path

- Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml
> Revert "Darktrace Event Collector - Added the marketplacev2 to the yml file"

- Packs/Bitbucket/Integrations/Bitbucket/README.md
- Packs/FeedURLhaus/Integrations/FeedURLhaus/README.md
- Packs/FullHunt/Integrations/FullHunt/FullHunt.yml
- Packs/FullHunt/Integrations/FullHunt/FullHunt_description.md
- Packs/FullHunt/ReleaseNotes/1_0_2.md
- Packs/FullHunt/pack_metadata.json
- Packs/HarfangLabEDR/Integrations/Hurukai/README.md
- Packs/Okta/Integrations/OktaEventCollector/README.md
- Packs/Zabbix/Integrations/Zabbix/README.md
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-6459
Fix files that fail the [new BA-125 validation](https://github.com/demisto/demisto-sdk/pull/3355)
> Remove Internal Terms From Customer-Facing Docs

- Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml
Fix master [failure](https://code.pan.run/xsoar/content/-/pipelines/5818608)
> added marketplacev2

- Packs/ApacheWebServer/README.md
Fixes the cortex-marketplace nightly failure.
https://code.pan.run/xsoar/cortex-marketplace/-/jobs/29687024
> ApacheWebServer fix Docusaurus parse error

- Packs/ApacheWebServer/README.md
- Packs/IvantiConnectSecure/README.md
> Changed form < to { in README files in order to avoid failing the marketplace build

- Packs/Zabbix/Integrations/Zabbix/README.md
> Remove test-module from Zabbix's README

- Packs/EDL/Integrations/EDL/README.md
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1623
For Cortex XSOAR 8, add a link to Manage External Dynamic Lists in the Administrator Guide.
> Add link to Cortex XSOAR 8 documentation for EDLs

- Packs/Phishing/Playbooks/playbook-Spear_Phishing_Investigation.yml
- Packs/Phishing/ReleaseNotes/3_5_25.md
- Packs/Phishing/pack_metadata.json
"Set keywords found to layout" task input replaced to "KeyWordsFound" context key to avoid errors
> Spear phishing fix

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
- Tests/scripts/add_secrets_file_to_build.py
- Tests/scripts/download_conf_repos.sh
- Tests/scripts/utils/GoogleSecretManagerModule.py
There is an error in the GSM changes PR to revert them.
> Revert GSM changes

- Packs/HelloWorld/ReleaseNotes/1_1_0.md
Test https://github.com/demisto/content/pull/28507.
> Test 28507

- Packs/GoogleSheets/TestPlaybooks/GoogleSheets-Test.yml
- Tests/conf.json
> adding memory_threshold to GoogleSheets-Test playbook

- Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.py
- Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.yml
- Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_description.md
- Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture_test.py
- Packs/RecordedFuture/ReleaseNotes/1_6_5.md
- Packs/RecordedFuture/pack_metadata.json
N/A
Reduce the amount of data sent from the calling context when Collective Insights setting is set to **On**, and added description of what is saved.
> Recordedfuture reduce callingcontext sent

- Packs/CybleEventsV2/.pack-ignore
> Added ignore for image in readme

- Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.py
- Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
- Packs/CortexXpanse/Integrations/CortexXpanse/README.md
- Packs/CortexXpanse/ReleaseNotes/1_0_7.md
- Packs/CortexXpanse/pack_metadata.json
Adding back the asm-update-alerts command
> [ASM] - Expander - Add update alerts command

- Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.yml
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_13.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
REST version of the Exchange Online library
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26109
Using a new a docker image which supports REST version of Exchange Online Library.
> Using docker image which supports

- .gitignore
- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- Tests/Marketplace/search_and_uninstall_pack.py
- Tests/configure_and_test_integration_instances.py
- Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
fixes: [CIAC-7603](https://jira-hq.paloaltonetworks.local/browse/CIAC-7603)
Uninstall one-by-one with waiting for the status from the server not to be in "create / update / delete operation is already in progress (10102)"
Nightly test: https://code.pan.run/xsoar/content/-/pipelines/5907768
> Uninstall one-by-one with waiting for the status from the server not to be in "create / update / delete operation is already in progress (10102)"

- .gitlab/ci/.gitlab-ci.on-push.yml
- Tests/Marketplace/search_and_install_packs.py
- Tests/Marketplace/search_and_uninstall_pack.py
fixes: [CIAC-7621](https://jira-hq.paloaltonetworks.local/browse/CIAC-7621)
XSIAM - uninstalling packs adding retry to every endpoint call to the server
XSIAM - uninstalling packs adding retry to every endpoint call to the server
> uninstalling packs adding retry to every endpoint call to the server

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
We forget to implement different queues. Adding it and testing. 
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7659
> Adding new queue for upload machines 

- Packs/Base/ReleaseNotes/1_32_23.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
> Fixed fetch incidents debug logs

- Tests/docker_native_image_config.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7645)
Stop supporting native 8.2 as native maintenance
> [native-runner] - stop supporting 8.2

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
- Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
- Packs/QRadar/ReleaseNotes/2_4_27.md
- Packs/QRadar/pack_metadata.json
> QRadar: pre-commit

- .github/workflows/update-demisto-sdk-version.yml
Fixed the --no-unit-test flag in pre-commit
https://github.com/demisto/content/actions/runs/5740765291/job/15559334531
https://github.com/demisto/demisto-sdk/blob/master/demisto_sdk/__main__.py#L3335
> pre-commit fixed the --no-unit-test flag

- Packs/AzureEventsHub/pack_metadata.json
> AzureEventHub to Hidden

- .github/workflows/update-demisto-sdk-version.yml
Added git add before pre-commit so the pre-commit command will identify the changed files.
> git-add-before-pre-commit

- Packs/CrowdStrikeFalconX/Playbooks/playbook-FalconX_Detonate_and_Analyze_File.yml
- Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_32.md
- Packs/CrowdStrikeFalconX/pack_metadata.json
detection logic for brand version is incorrect, updating
The logic in the playbook is incorrect for the current name of the Brand, updating the detection logic for the first branch
> CrowdStrike Falcon X playbook - branch logic is incorrect

- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_15.json
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_15.md
Added Breaking Change notice to ensure customers will know how to handle existing instances of S&C V2
> Add breaking change notice to S&C

- Tests/docker_native_image_config.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7686)
update native:candidate version
> update native candidate

- Packs/Reco/Integrations/Reco/README.md
- Packs/Reco/Integrations/Reco/Reco.py
- Packs/Reco/Integrations/Reco/Reco.yml
- Packs/Reco/Integrations/Reco/Reco_test.py
- Packs/Reco/ReleaseNotes/1_1_5.md
- Packs/Reco/pack_metadata.json
> packs/Reco: add change alert status command

- Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
- Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
- Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
- Packs/Mimecast/ReleaseNotes/2_1_11.md
- Packs/Mimecast/pack_metadata.json
Pre-Commit and some improvement
and updated docker
> [Mimecast] Pre-Commit and some improvement

- Packs/MicrosoftGraphSecurity/README.md
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-6928)
> MicrosoftGraphSecurity README Update

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
> fixed machines_locks path for removing the lock in bucket upload

- Packs/MxToolBox/Integrations/MxToolBox/MxToolBox_description.md
- Packs/MxToolBox/Integrations/MxToolBox/README.md
- Packs/MxToolBox/ReleaseNotes/1_0_3.md
- Packs/MxToolBox/pack_metadata.json
- Packs/PassiveTotal/Integrations/PassiveTotal_v2/PassiveTotal_v2_description.md
- Packs/PassiveTotal/Integrations/PassiveTotal_v2/README.md
- Packs/PassiveTotal/ReleaseNotes/2_1_11.md
- Packs/PassiveTotal/pack_metadata.json
- Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_description.md
- Packs/PhishTank/Integrations/PhishTankV2/README.md
- Packs/PhishTank/ReleaseNotes/2_0_27.md
- Packs/PhishTank/pack_metadata.json
- Packs/PolySwarm/Integrations/PolySwarmV2/PolySwarmV2_description.md
- Packs/PolySwarm/Integrations/PolySwarmV2/README.md
- Packs/PolySwarm/ReleaseNotes/2_0_5.md
- Packs/PolySwarm/pack_metadata.json
- Packs/Pulsedive/Integrations/Pulsedive/Pulsedive_description.md
- Packs/Pulsedive/Integrations/Pulsedive/README.md
- Packs/Pulsedive/ReleaseNotes/1_6_5.md
- Packs/Pulsedive/pack_metadata.json
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-4743
PR #9: Updated the README files with a warning for the user that indicators data might be publicly available.
> Private upload mode docs #9

- Packs/Pwned/Integrations/PwnedV2/PwnedV2_description.md
- Packs/Pwned/Integrations/PwnedV2/README.md
- Packs/Pwned/ReleaseNotes/1_0_11.md
- Packs/Pwned/pack_metadata.json
- Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/README.md
- Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/ReversingLabsTitaniumCloudv2_description.md
- Packs/ReversingLabs_Titanium_Cloud/ReleaseNotes/2_1_1.md
- Packs/ReversingLabs_Titanium_Cloud/pack_metadata.json
- Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/README.md
- Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter_description.md
- Packs/SEKOIAIntelligenceCenter/ReleaseNotes/1_2_13.md
- Packs/SEKOIAIntelligenceCenter/pack_metadata.json
- Packs/SecurityTrails/Integrations/SecurityTrails/README.md
- Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails_description.md
- Packs/SecurityTrails/ReleaseNotes/1_1_6.md
- Packs/SecurityTrails/pack_metadata.json
- Packs/Sixgill-Darkfeed/.pack-ignore
- Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/README.md
- Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/Sixgill_Darkfeed_Enrichment_description.md
- Packs/Sixgill-Darkfeed/ReleaseNotes/2_2_5.md
- Packs/Sixgill-Darkfeed/pack_metadata.json
relates: https://jira-hq.paloaltonetworks.local/browse/CIAC-4743
PR #10: Updated the README files with a warning for the user that indicators data might be publicly available.
> Private upload mode docs #10

- Packs/Neosec/.secrets-ignore
- Packs/Neosec/README.md
link was broken due to site been removed (will be redirected to a new site)
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7825)
> changed link to redirect

- Packs/CiscoCatalyst/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7334)
> Cisco Catalyst Update

- .github/content_roles.json
> updated the reviewers and security architect

- Packs/Base/ReleaseNotes/1_32_27.md
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators_test.py
- Packs/Base/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26901
> Optimize Find Similar Incidents

- Packs/BreachNotification-US/pack_metadata.json
- Packs/BruteForce/pack_metadata.json
- Packs/CortexDataLake/pack_metadata.json
- Packs/GDPR/pack_metadata.json
- Packs/HIPAA-BreachNotification/pack_metadata.json
- Packs/RiskIQDigitalFootprint/pack_metadata.json
- Packs/SANS/pack_metadata.json
- Packs/XSOARContentUpdateNotifications/pack_metadata.json
[link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-7870)
remove mandatory dependancies for packs that do not have any content item in them
> remove mandatory dependancies for some packs

- Tests/scripts/analyze-nightly-logs.py
- Tests/scripts/analyze_nightly_logs.py
Add analyze-nightly-logs script to Tests/scripts, which allows analyzing failed TPBs for data collection.
> Add analyze-nightly-logs script to Tests/scripts

- Packs/Discord/Integrations/Discord/Discord.py
- Packs/Discord/Integrations/Discord/Discord.yml
- Packs/Discord/ReleaseNotes/1_0_1.md
- Packs/Discord/pack_metadata.json
> [Discord] Add support for credentials (type 9)

- Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_3_92.md
- Packs/CommonPlaybooks/pack_metadata.json
Decoded command has been added as inputs to the 'Compare Process Execution Arguments To LOLBAS Patterns' sub-playbook.
> Commandline analysis fix

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_5.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27153)
- Added the *timeout* argument to the following commands:
- ***cs-falcon-rtr-kill-process***
- ***cs-falcon-rtr-list-network-stats***
- ***cs-falcon-rtr-list-processes***
- ***cs-falcon-rtr-list-scheduled-tasks***
- ***cs-falcon-rtr-read-registry***
- ***cs-falcon-rtr-remove-file***
- ***cs-falcon-rtr-retrieve-file***
> CrowdStrike Falcon timeout argument

- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
> removed a newline

- Packs/Use_Case_Builder/ReleaseNotes/1_0_3.md
- Packs/Use_Case_Builder/Scripts/CreateUseCaseTemplateList/CreateUseCaseTemplateList.yml
- Packs/Use_Case_Builder/pack_metadata.json
> [Use Case Builder] Update the docker image

- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/README.md
- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.js
- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.yml
- Packs/Remedy-On-Demand/ReleaseNotes/1_1_3.md
- Packs/Remedy-On-Demand/pack_metadata.json
fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27091?filter=62403)
Added support for the *custom-fields-seperator* argument in the ***re…
> Added support for the  custom-fields-seperator argument

- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/README.md
- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.yml
- Packs/Remedy-On-Demand/ReleaseNotes/1_1_3.md
> doc review fixes

- Tests/scripts/download_conf_repos.sh
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-7901
fixing git clone retry mechanism to allow retries.
> fixing git clone retry mechanism to allow retries.

- Packs/EDL/Integrations/EDL/EDL.py
- Packs/EDL/Integrations/EDL/EDL.yml
- Packs/EDL/ReleaseNotes/3_2_8.md
- Packs/EDL/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26699
Exit upon getting 429 in X2 and NG.
> [EDL] Exit for 429

- Packs/MaxMind_GeoIP2/Integrations/MaxMind_GeoIP2/MaxMind_GeoIP2.py
- Packs/MaxMind_GeoIP2/Integrations/MaxMind_GeoIP2/MaxMind_GeoIP2.yml
- Packs/MaxMind_GeoIP2/ReleaseNotes/1_0_12.md
- Packs/MaxMind_GeoIP2/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27247)
Align credentials for MaxMind_GeoIP2.
> Align credentials for MaxMind_GeoIP2.

- Tests/configure_and_test_integration_instances.py
> XSIAM build typo fix

- Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/MicrosoftGraphTeams.py
- Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/MicrosoftGraphTeams.yml
- Packs/MicrosoftGraphTeams/Integrations/MicrosoftGraphTeams/README.md
- Packs/MicrosoftGraphTeams/ReleaseNotes/1_0_10.md
- Packs/MicrosoftGraphTeams/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27110)
- Added support for the ***msgraph-teams-auth-reset*** and ***msgraph-teams-generate-login-url*** commands.
> [O365 Teams] added msgraph-teams-generate-login-url  command

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.test-native-candidate.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8006
fixing errors in gitlab yml build files
> fixing errors in gitlab yml build files

- Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic_v1.5.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_3_96.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27471
Fixed the input URL for the playbook
> Detonate url input fix

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- Packs/MicrosoftTeams/ReleaseNotes/1_4_31.md
- Packs/MicrosoftTeams/pack_metadata.json
Currently, MS Team won’t work on 8.2 tenants - https://panw-global.slack.com/archives/C011J0AP7J8/p1682664625693719
> [MS TEAMS] Update README - Currently MS Team won’t work on 8.2 tenants

- Packs/Tenable_sc/Integrations/Tenable_sc/README.md
- Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml
- Packs/Tenable_sc/ReleaseNotes/1_0_11.md
- Packs/Tenable_sc/pack_metadata.json
https://jira-hq.paloaltonetworks.local/browse/XSUP-27086
Updated the description of the ***source_type*** argument in **tenable-sc-get-vulnerability** command.
> [Tenable.sc] Updated the description of the source_type argument 

- Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.yml
Un hiding the credentials param that was wrongly hidden
> Un-hiding API token

- Packs/CortexXpanse/Classifiers/classifier-Xpanse_-_Incoming_Mapper.json
- Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
- Packs/CortexXpanse/Integrations/CortexXpanse/README.md
- Packs/CortexXpanse/README.md
- Packs/CortexXpanse/ReleaseNotes/1_0_9.md
- Packs/CortexXpanse/pack_metadata.json
EXPANDR-5754
Update the enums used for alert statuses
> [ASM] - Expander - command argument bug fix

- .gitlab/ci/.gitlab-ci.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8120
Setting build pip environment
> Setting build pip environment

- Packs/AlibabaActionTrail/ModelingRules/AlibabaModelingRules_1_3/AlibabaModelingRules_1_3_schema.json
- Packs/AlibabaActionTrail/ReleaseNotes/1_0_20.md
- Packs/AlibabaActionTrail/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8104)
> Alibaba AT Fix

- Packs/NetBox/ModelingRules/NetBoxModelingRules_1_3/NetBoxModelingRules_1_3_schema.json
- Packs/NetBox/ReleaseNotes/1_0_11.md
- Packs/NetBox/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8105)
> Netbox IRM Fix

- Packs/MicrosoftADFS/ModelingRules/MicrosoftADFS_1_3/MicrosoftADFS_1_3_schema.json
- Packs/MicrosoftADFS/ReleaseNotes/1_0_17.md
- Packs/MicrosoftADFS/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8106)
> MS ADFS Fix

- Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3_schema.json
- Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_1.md
- Packs/MicrosoftWindowsEvents/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8117)
> MS Windows Fix

- Packs/CyberArkIdentity/ModelingRules/CyberArkIdentityEventCollector_1_3/CyberArkIdentityEventCollector_1_3_schema.json
- Packs/CyberArkIdentity/ReleaseNotes/1_0_29.md
- Packs/CyberArkIdentity/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8133)
> Cyberark Identity Fix

- Packs/Vectra_AI/ModelingRules/Vectra_AIEventCollector_1_3/Vectra_AIEventCollector_1_3_schema.json
- Packs/Vectra_AI/ReleaseNotes/1_2_8.md
- Packs/Vectra_AI/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8110)
> Vectra AI Fix

- Packs/Orca/ModelingRules/OrcaModelingRules_1_3/OrcaModelingRules_1_3_schema.json
- Packs/Orca/ReleaseNotes/2_2_6.md
- Packs/Orca/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8119)
> Orca Security Fix

- .github/CODEOWNERS
> Remove myself

- Packs/epo/ModelingRules/McafeeEpoModelingRules_1_3/McafeeEpoModelingRules_1_3_schema.json
- Packs/epo/ReleaseNotes/2_0_24.md
- Packs/epo/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8115)
> Mcafee EPO Fix

- Packs/ManageEngine-ADManager/ModelingRules/ManageEngine-ADManager_1_3/ManageEngine-ADManager_1_3_schema.json
- Packs/ManageEngine-ADManager/ReleaseNotes/1_0_2.md
- Packs/ManageEngine-ADManager/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8135)
> ME AD Manager Fix

- Packs/GitLab/ModelingRules/GitlabModelingRules_1_3/GitlabModelingRules_1_3_schema.json
- Packs/GitLab/ReleaseNotes/2_2_16.md
- Packs/GitLab/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8134)
> Gitlab Fix

- Packs/MicrosoftDHCP/ModelingRules/MicrosoftDHCP_1_3/MicrosoftDHCP_1_3_schema.json
- Packs/MicrosoftDHCP/ReleaseNotes/1_0_2.md
- Packs/MicrosoftDHCP/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8113)
> MS DHCP Fix

- Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3_schema.json
- Packs/Netskope/ReleaseNotes/3_2_1.md
- Packs/Netskope/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8118
Refactor the compatibility between the data model rules and the schema hints
> Fix netskope schema mismatch

- Packs/Base/ReleaseNotes/1_32_29.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
- Packs/Base/pack_metadata.json
fixes: [XSUP-27558](https://jira-hq.paloaltonetworks.local/browse/XSUP-27558)
reproduced: https://github.com/demisto/content/actions/runs/6011790809/job/16305859539
> XSUP-27558 bugfix (BetweenHours)

- Packs/Elasticsearch/ReleaseNotes/1_3_15.md
> Updated Elasticsearch Release notes

- Packs/CommonScripts/ReleaseNotes/1_12_19.md
- Packs/CommonScripts/Scripts/IsInternalHostName/IsInternalHostName.yml
- Packs/CommonScripts/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-90811
- Removed the `predefined` from the yml
- Updated docker image
> Isinternalhostname small fix

- .github/workflows/pre-commit.yml
- .hooks/bootstrap
- Packs/ContentManagement/doc_files/ci-cd.yml
npm install running without fund or audit.
> npm install running without fund or audit.

- Packs/Base/ReleaseNotes/1_32_30.md
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml
- Packs/Base/pack_metadata.json
fixes:  https://jira-hq.paloaltonetworks.local/browse/XSUP-26901
> BotFindSimilarIncidentsByIndicators return_results

- Tests/scripts/sdk_pylint_check.sh
sdk pylint error checking script was broken.
pylint_tests_result was set, but pylint_test_result was used.
> sdk pylint error checking script was broken

- Tests/setup/playbook-invalid-id-test.yml
- Tests/setup/playbook-valid-id-test.yml
Related: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8236)
In order to run `pre-commit` on our entire repo, it is necessary to fix certain files that fail the `check-yaml` hook.
> [pre-commit check-yaml] Align the entire repo with check-yaml

- Tests/scripts/test_modeling_rules.sh
> fix test modeling rule

- Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.py
- Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture.yml
- Packs/IdentityRecordedFuture/ReleaseNotes/1_1_4.md
- Packs/IdentityRecordedFuture/pack_metadata.json
Related: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8236)
- Deleting an unused import
- Update RN
> [Recorded Future Identity] Deleting an unused import

- Utils/release_notes_generator.py
> [Release Notes Generator] Change log info to debug

- Packs/GenericSQL/TestPlaybooks/generic-sql-mssql-encrypted-connection.yml
- Tests/conf.json
fixes: [CIAC-7726](https://jira-hq.paloaltonetworks.local/browse/CIAC-7726)
Fix generic-sql-mssql-encrypted-connection TPB as a part of the following effort: [CIAC-7201](https://jira-hq.paloaltonetworks.local/browse/CIAC-7201).
Changes made:
> Fix generic-sql-mssql-encrypted-connection TPB

- Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.py
- Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups.yml
- Packs/MicrosoftGraphGroups/ReleaseNotes/1_1_31.md
- Packs/MicrosoftGraphGroups/pack_metadata.json
Fixed an issue where 'msgraph-groups-generate-login-url' command had incorrectly raised an error when executed.
> [Azure Active Directory Groups] fixed bug when calling command

- .gitlab/ci/.gitlab-ci.on-push.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8263
Revert change regarding the xsoar-ng test-pb not running
> revert changes regardin xsoar_ng_server_ga

- Packs/Palo_Alto_Networks_Enterprise_DLP/Layouts/layoutscontainer-Data_Loss_Prevention_6_8.json
- Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop_6_8.yml
- Packs/Palo_Alto_Networks_Enterprise_DLP/Playbooks/DLP_Incident_Feedback_Loop_6_8_README.md
- Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_4.md
- Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8210
- Adding a better playbook description.
- Filter out "Benign" results in the indicators section in the layout.
> Dlp description

- package-lock.json
- package.json
> Revert "Bump markdownlint from 0.26.2 to 0.30.0"

- .circleci/config.yml
fix using deprecated -vvv argument when calling the demisto sdk
> fix-sdk-warning-messages-vvv

- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8305
rehash: warning: skipping domain-ca.pem,it does not contain exactly one certificate or CRL
> certificate-rehash-warning

- Packs/PAN-OS/pack_metadata.json
Ready
Added keywords to help with searching for the DNS sinkhole playbooks
> Added keywords related to DNS sinkhole to the PAN-OS pack

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_11_9.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
Revert changes in IDP detections.
> Cs limit in idp detections

- Packs/Armis/ModelingRules/ArmisModelingRules/ArmisModelingRules_schema.json
- Packs/Armis/ReleaseNotes/1_1_1.md
- Packs/Armis/pack_metadata.json
relates: [CRTX-92099](https://jira-hq.paloaltonetworks.local/browse/CRTX-92099)
This PR adds missing `connectionIds` key to the modeling rules schema.
> [Armis Event Collector] Add connectionIds to modeling rules schema

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
> fixed content path

- Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3_schema.json
- Packs/Netskope/ReleaseNotes/3_2_4.md
- Packs/Netskope/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-92099)
> Netskope Schema Update

- Packs/PrismaCloud/TestPlaybooks/Prisma_Cloud_Test.yml
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8018
Fix `Prisma Cloud V2 Test` TPB as a part of the following effort: [CIAC-7201](https://jira-hq.paloaltonetworks.local/browse/CIAC-7201).
This TPB failed because we moved to a different machine, which has different repositories in Prisma Cloud Code Security.
Also, there are less connections and alerts there so we needed to change the tasks accordingly.
Changes made:
> Prisma Cloud V2 Test Playbook Fix

- Packs/Base/ReleaseNotes/1_32_33.md
- Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.py
- Packs/Base/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-26901
Fixed the output.
> [DBotFindSimilarIncidentsByIndicators] Fixed the output

- Tests/Marketplace/pack_readme_handler.py
- Tests/Marketplace/upload_packs.py
Convert some spamming logs to debug mode
> Turn markdown logs to debug

- Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
- Packs/CortexXDR/ReleaseNotes/5_1_5.md
- Packs/CortexXDR/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-27785)
Fixed an issue with the display filter on the investigation tab.
> Xdr layout fixes

- Utils/gitlab_triggers/trigger_content_instance_testing_build.sh
- Utils/gitlab_triggers/trigger_content_nightly_build.sh
fix trigger script, missing comment
> fix trigger script, missing comment

- Tests/docker_native_image_config.json
Updated native candidate to: demisto/py3-native:8.3.0.73915
> Updated native candidate

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
Remove some code that triggered upload on dev branches.
> remove code to trigger upload on dev branches

- Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_AWS_Enrichment.yml
- Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_35.md
- Packs/CortexAttackSurfaceManagement/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-5553
Bug fix for AWS Project number in ASM Cloud field.
> [ASM] - EXPANDR-5553

- Packs/ProofpointEmailSecurity/ModelingRules/ProofpointEmailSecurity/ProofpointEmailSecurity_schema.json
- Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_1.md
- Packs/ProofpointEmailSecurity/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8396?filter=-1
Fix the description in Proofpoint email security pack
> Proofpoint email security pack: update description

- Packs/RemoteAccess/Integrations/RemoteAccessv2/RemoteAccessv2.yml
- Packs/RemoteAccess/ReleaseNotes/1_0_30.md
- Packs/RemoteAccess/pack_metadata.json
relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-28317
> update netmiko docker

- Packs/WebFileRepository/Integrations/WebFileRepository/README.md
- Packs/WebFileRepository/Integrations/WebFileRepository/WebFileRepository.yml
- Packs/XsoarWebserver/Integrations/XSOARWebServer/README.md
- Packs/XsoarWebserver/Integrations/XSOARWebServer/XSOARWebServer.yml
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1811
Update parameters for EDL for XSOAR 8 and XSIAM
> Update WebFileRepository and XSOARWebServer integration files

- Packs/PingCastle/Integrations/PingCastle/PingCastle.yml
- Packs/PingCastle/Integrations/PingCastle/README.md
- Packs/PublishList/Integrations/PublishList/PublishList.yml
- Packs/PublishList/Integrations/PublishList/PublishList_description.md
- Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml
- Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy_description.md
Update descriptions for EDL. Content packs included are:
SimpleAPIProxy
PublishList
PingCastle
> Update for EDL

- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_description.md
- Packs/GenericWebhook/Integrations/GenericWebhook/README.md
- Packs/TAXIIServer/Integrations/TAXIIServer/README.md
- Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
- Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer_description.md
https://jira-hq.paloaltonetworks.local/browse/CRTXDOC-1811
Updated the parameter descriptions and instructions for Cortex XSOAR 8 and Cortex XSIAM
> Update Generic Webhook and TAXIIServer for EDL

- .gitlab/ci/.gitlab-ci.on-push.yml
- Tests/Marketplace/install_packs.sh
- Tests/scripts/install_content_and_test_integrations.sh
- Tests/scripts/print_cloud_machine_details.sh
- Tests/scripts/run_tests.sh
- Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
- Tests/scripts/wait_in_line_for_cloud_env.sh
fixing cloud machine ids processing
> fixing cloud machine ids processing

- Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3_description.md
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_26.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27956
> XSUP-27956/ Added EWS PS V3 Description

- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_35.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8453
Added timeout argument
> Wildfire-upload-url add poling timeout argument

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.sdk-nightly.yml
- Tests/Marketplace/print_test_playbook_summary.py
- Tests/Marketplace/search_and_uninstall_pack.py
- Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
fixing typos in build scripts.
unremovable -> non-removable
productname -> product_name
testplaybook -> test_playbook
changed some arg passing to use their full name:
-gpidd -gpidp
> fixing typos in build scripts

- Tests/docker_native_image_config.json
fixes: [CIAC-8460](https://jira-hq.paloaltonetworks.local/browse/CIAC-8460)
- Update native:8.4 docker image due to the changes made in https://github.com/demisto/dockerfiles/pull/20295.
- Add `auth-utils` support for native:8.4 and native:candidate followed by https://github.com/demisto/dockerfiles/pull/19619.
> [Native Image] Updated native:8.4 image

- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml
- Packs/FeedRecordedFuture/ReleaseNotes/1_0_29.md
- Packs/FeedRecordedFuture/pack_metadata.json
> New logs feed recorded future

- Packs/Zscaler/ModelingRules/ZscalerModelingRule_1_3/ZscalerModelingRule_1_3_schema.json
- Packs/Zscaler/ReleaseNotes/1_3_14.md
- Packs/Zscaler/pack_metadata.json
This PR is created to remove duplicated field "spriv" from the schema file.
> Zscaler FW - Fix duplicated field in Schema

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
moving machines destroy/unlock to after_script
> moving machines destroy/unlock to after_script

- Packs/CrowdStrikeFalcon/TestPlaybooks/Test_Playbook_-_CrowdStrike_Falcon_Malware_-_Verify_Containment_Actions.yml
Change this: `'Policy.Stateâ€™`
To this: `'Policy.State'`
> [Test Playbook - CrowdStrike Falcon Malware - Verify Containment Actions] fix bad unicode character

- Templates/Integrations/Database/Database.py
> Fix autopep8 error

- Tests/docker_native_image_config.json
fixes: [CIAC-7837](https://jira-hq.paloaltonetworks.local/browse/CIAC-7837)
Unskip FindEmailCampaign script in native image so it can run with native-runner.
> [Native Image] Unskip FindEmailCampaign Script

- .circleci/config.yml
fix github ssh issue
using circle suggested solution: https://circleci.com/docs/github-integration/#establish-the-authenticity-of-an-ssh-host
> fix github ssh

- .github/content_roles.json
Change the developers in the contributions round
> contribution_round_change

- Packs/ManageEngine-ADAudit/ModelingRules/ManageEngine-ADAudit_1_3/ManageEngine-ADAudit_1_3.xif
- Packs/ManageEngine-ADAudit/ReleaseNotes/1_0_1.md
- Packs/ManageEngine-ADAudit/pack_metadata.json
- Packs/Netskope/ModelingRules/NetskopeEventCollector_1_3/NetskopeEventCollector_1_3.xif
- Packs/Netskope/ReleaseNotes/3_2_5.md
- Packs/Netskope/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-93320)
> Update - Multitype Casting to String

- .gitlab/ci/.gitlab-ci.build-machines-cleanup.yml
- Tests/Marketplace/search_and_uninstall_pack.py
Add timeout to Build Machines Cleanup.
> Build Machines Timeout

- Packs/Base/ReleaseNotes/1_32_36.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
https://github.com/demisto/dockerfiles/pull/20545
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28365
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-27592
> Release base pack 1.32.36

- Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement.yml
- Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/CortexAttackSurfaceManagement_description.md
- Packs/CortexAttackSurfaceManagement/Integrations/CortexAttackSurfaceManagement/README.md
- Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_6_41.md
- Packs/CortexAttackSurfaceManagement/pack_metadata.json
- Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse.yml
- Packs/CortexXpanse/Integrations/CortexXpanse/CortexXpanse_description.md
- Packs/CortexXpanse/Integrations/CortexXpanse/README.md
- Packs/CortexXpanse/ReleaseNotes/1_0_11.md
- Packs/CortexXpanse/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6362
Added an explanation to only use the standard API key (not the advanced one).
> [ASM] Expander 6362

- .gitlab/ci/.gitlab-ci.on-push.yml
> Temporary skip Find dependencies changes section

- Packs/Base/ReleaseNotes/1_32_37.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
https://github.com/demisto/dockerfiles/pull/20771
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28365
> Release base pack 1.32.37

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.sdk-nightly.yml
- .gitlab/ci/.gitlab-ci.security-scans.yml
- .gitlab/ci/.gitlab-ci.slack-notify.yml
- .gitlab/ci/.gitlab-ci.yml
- Tests/Marketplace/search_and_install_packs.py
- Tests/scripts/download_conf_repos.sh
- Tests/scripts/lock_cloud_machines.py
- Utils/github_workflow_scripts/trigger_contribution_build.py
- Utils/gitlab/stop_running_pipelines.sh
- Utils/gitlab_triggers/trigger_build_url.sh
- Utils/test_upload_flow/create_test_branch.py
- Utils/test_upload_flow/wait_for_upload.py
> Revert "Make CI more dynamic"

- Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage_description.md
- Packs/HatchingTriage/ReleaseNotes/1_0_14.md
- Packs/HatchingTriage/pack_metadata.json
N/A
Update documentation for easier setup and showing available options
> [Hatching Triage] Documentation Update

- Tests/Marketplace/common.py
- Tests/Marketplace/search_and_install_packs.py
- Tests/Marketplace/search_and_uninstall_pack.py
Add timeout to calls to server.
> generic_request Timeout

- Packs/Palo_Alto_Networks_Enterprise_DLP/.pack-ignore
- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.py
- Packs/Palo_Alto_Networks_Enterprise_DLP/Integrations/Palo_Alto_Networks_Enterprise_DLP/Palo_Alto_Networks_Enterprise_DLP.yml
- Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_6.md
- Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8587
Removed printing the integration parameter information to the debug logs.
> [Palo Alto Networks Enterprise DLP] Change Params Print

- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_1_3/DuoModelingRule_1_3_schema.json
- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0_schema.json
- Packs/DuoAdminApi/ReleaseNotes/4_0_12.md
- Packs/DuoAdminApi/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-85978)
> Duo Update

- Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.py
- Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
- Packs/JoeSecurity/ReleaseNotes/1_1_15.md
- Packs/JoeSecurity/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28870?filter=-1
This will return only one partial result while polling
> [JoeSecrity] Fix submut url/file polling commands

- Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py
- Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml
- Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_description.md
- Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py
- Packs/ZeroFox/ReleaseNotes/1_2_0.md
- Packs/ZeroFox/ReleaseNotes/1_2_1.md
- Packs/ZeroFox/pack_metadata.json
- It adds a missing command to the yml file
- It adds a new config param to fetch only escalated alerts
- It fixes an issue with transforming the body of the requests to strings
> [ZeroFox] Add filter to fetch only escalated alerts

- Packs/CortexXDR/Integrations/CortexXDRIR/README.md
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8607
XDR Readme - Added text to the readme:
- "Required license: Cortex XDR Pro per Endpoint, Cortex XDR Pro, or Cortex XDR Pro per GB" was added to 3 commands.
-  fixed 4 command from "per TB" to "per GB"
> XDR Readme - Add "Required license" to 3 commands, and fix wrong license in 4 commands.

- Packs/CiscoUmbrellaReporting/.secrets-ignore
- Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.py
- Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting.yml
- Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/CiscoUmbrellaReporting_test.py
- Packs/CiscoUmbrellaReporting/Integrations/CiscoUmbrellaReporting/README.md
- Packs/CiscoUmbrellaReporting/ReleaseNotes/1_1_0.md
- Packs/CiscoUmbrellaReporting/pack_metadata.json
relates: https://jira-hq.paloaltonetworks.local/browse/XSUP-28496
Updated API endpoints per migration guide https://developer.cisco.com/docs/cloud-security/#!how-to-migrate-to-the-umbrella-api/step-2-update-your-client-code
> Updated urls for new API

- Packs/XSOAR_Engineer_Training/Integrations/XSOAREngineerTraining/README.md
- Packs/XSOAR_Engineer_Training/Integrations/XSOAREngineerTraining/XSOAREngineerTraining.yml
- Packs/XSOAR_Engineer_Training/Integrations/XSOAREngineerTraining/command_examples.txt
- Packs/XSOAR_Engineer_Training/ReleaseNotes/1_0_1.md
- Packs/XSOAR_Engineer_Training/pack_metadata.json
N/A
Added the body argument to the xet-send-mail command.   Command does nothing, just says it didn't send a fake email, used as part of our XSOAR Engineer Training videos from customer success.
> Xsoar engineer update - added body argument to xet-send-mail command.

- Packs/CommonPlaybooks/Playbooks/Entity_Enrichment_-_Generic_v3.yml
- Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml
- Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Enrichment_-_Generic_v2.1_6_8.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_4_6.md
- Packs/CommonPlaybooks/pack_metadata.json
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8054
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8575
- Added a check for the "Core" integration in XSIAM
- Added core-list-risky-users command to Account Enrichment
- Added core-list-risky-hosts command to Endpoint Enrichment
- Added Core outputs to enrichment playbooks
> Added support for Core integration in the enrichment playbooks in XSIAM

- Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_28.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
- Tests/Marketplace/search_and_install_packs.py
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28623
Fixed an issue were SSL cert verification was still performed even when trust a certs was enabled.
> Security and Compliance V2 SSL Certificate Verification

- Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
- Packs/FeedElasticsearch/ReleaseNotes/1_1_2.md
- Packs/FeedElasticsearch/pack_metadata.json
https://github.com/demisto/content/pull/30183
> Update elastic search feed docker

- Tests/conf.json
related: https://jira-hq.paloaltonetworks.local/browse/CIAC-7727
Unmocked `PhishTank Testing` test playbook.
> unmcok `PhishTank Testing` test playbook

- Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
- Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml
- Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_test.py
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_29.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-28234 https://jira-hq.paloaltonetworks.local/browse/XSUP-29109
> EWS O365: Fixed missing the eml extension

- Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
- Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_10.md
- Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Resolves issue where import would become stuck in a loop during ingestion and be unable to catch up.
Resolves an issue where indicator ingestion would become stuck in a loop and never import newer indicators.
> Improving MATI indicator ingestion

- Tests/Marketplace/Tests/search_and_install_packs_test.py
> fixed test to use CI_PROJECT_ID

- .github/content_roles.json
> Change oncall dev - October

- Packs/CiscoASR/ModelingRules/CiscoASR/CiscoASR.xif
- Packs/CiscoASR/ReleaseNotes/1_0_2.md
- Packs/CiscoASR/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8611)
> Cisco ASR Update

- Packs/CommonPlaybooks/Playbooks/playbook-Calculate_Severity_-_Generic_v2.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_4_12.md
- Packs/CommonPlaybooks/pack_metadata.json
Ready
Fixed an issue where the XDR playbook that contributes to the incident severity was not added in the previous update.
> Calculate Severity - added ITDR subplaybook

- Packs/cisco-ise/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8490)
> Cisco ISE Metadata Update

- Packs/PrismaCloud/Playbooks/playbook-Prisma_Cloud_-_VM_Alert_Prioritization.yml
- Packs/PrismaCloud/ReleaseNotes/4_2_10.md
- Packs/PrismaCloud/pack_metadata.json
fixes: [CIAC-8708 - VM Alert Prioritization - fix query in task #4](https://jira-hq.paloaltonetworks.local/browse/CIAC-8708)
Fixed an error in the query in the `Verify if public IP exists (Azure)` task.
> Vm alert prioritization azure fix

- Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate_test.py
> [Cisco Umbrella Investigate Test] Fix typo

- Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
- Packs/Core/ReleaseNotes/2_0_20.md
- Packs/Core/pack_metadata.json
A recent enhancement was done but the input argument was not inserted to the yml, causing error and inability to use the command.
This PR fixes it.
> Cortex CoreIR add filter_alert_fields

- .pre-commit-config_template.yaml
- Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule_test.py
- Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_test.py
- Packs/BMCDiscovery/Integrations/BMCDiscovery/BMCDiscovery_test.py
- Packs/BmcHelixRemedyForce/Scripts/BMCHelixRemedyforceCreateIncident/BMCHelixRemedyforceCreateIncident_test.py
- Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast_test.py
- Packs/Cherwell/Integrations/Cherwell/Cherwell_test.py
- Packs/CommonScripts/Scripts/UnzipFile/UnzipFile_test.py
- Packs/CommonWidgets/Scripts/RSSWidget/RSSWidget_test.py
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR_test.py
- Packs/HYASInsight/Integrations/HYASInsight/HYASInsight_test.py
- Packs/HYASProtect/Integrations/HYASProtect/HYASProtect_test.py
- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks_test.py
- Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_test.py
- Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/test_data/context.py
- Packs/ManageEngine_PAM360/Integrations/ManageEnginePAM360/test_data/responses.py
- Packs/PANOSPolicyOptimizer/Integrations/PANOSPolicyOptimizer/PANOSPolicyOptimizer_test.py
- Packs/RDPCacheHunting/Scripts/SetIndicatorstype/SetIndicatorstype_test.py
- Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging_test.py
- Packs/Silverfort/Integrations/Silverfort/Silverfort_test.py
- Packs/TrendMicroCAS/Integrations/TrendMicroCAS/TrendMicroCAS_test.py
- Tests/Marketplace/Tests/zip_packs_test.py
- Tests/scripts/infrastructure_tests/lock_cloud_machines_test.py
- Update the autopep8 to 2.0.4.
- Fixing the files that fall due to the update.
> [pre-commit-config_template] Update the autopep8 to 2.0.4

- Tests/Marketplace/upload_packs.py
> dont clean packs from xsoar_saas

- Packs/CortexAttackSurfaceManagement/pack_metadata.json
- Packs/CortexXpanse/pack_metadata.json
- Packs/PAN-OS/pack_metadata.json
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-8414)
>  Add panw tag

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-95696)
Revert a change syncing QA tenants with xsoar-saas mp.
> revert mp-saas-dist

- .gitlab/ci/.gitlab-ci.global.yml
> gitlab CI build parameters

- .gitlab/ci/.gitlab-ci.on-push.yml
- Tests/scripts/check_jobs_done.py
- Tests/scripts/common.py
- Tests/scripts/gitlab_slack_notifier.py
> fix merge to master pipeline

- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.variables.yml
- Tests/scripts/check_jobs_done.py
- Tests/scripts/gitlab_slack_notifier.py
Slack notify on merge fixes, test-upload-flow fix job-done
> Slack notify on merge fixes, test-upload-flow fix job-done

- .gitlab/ci/.gitlab-ci.on-push.yml
> hotfix contrib branches

- .gitlab/ci/.gitlab-ci.on-push.yml
fixing contrib rule for docker builds
> fixing contrib rule for docker builds

- Packs/Netmiko/Integrations/Netmiko/Netmiko.yml
- Packs/Netmiko/ReleaseNotes/1_0_11.md
- Packs/Netmiko/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-29103?filter=-1
fixes bookwar/bullseye issue. See here: https://stackoverflow.com/questions/70087344/python-in-docker-runtimeerror-cant-start-new-thread#comment135267083_70093119
> [Netmiko] fix starting new threads

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.sdk-nightly.yml
- Tests/scripts/run_tests.sh
fixing instance_role.txt not written to artifacts folder
> fixing instance_role.txt not written to artifacts folder

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- Tests/scripts/install_content_and_test_integrations.sh
- Tests/scripts/run_end_to_end_tests.sh
- Tests/scripts/run_tests.sh
- Tests/scripts/test_modeling_rules.sh
- Tests/scripts/uninstall_packs_and_reset_bucket_cloud.sh
fixes: [link to the issue](https://github.com/demisto/content/pull/29906)
fixed after changes that were represented in https://github.com/demisto/content/pull/30367
> fixed the file variables handling

- .github/CODEOWNERS
Deleting myself from one file in order to reduce spam.
> Deleting myself codeowner from one file

- Tests/scripts/gitlab_slack_notifier.py
- Tests/scripts/test_modeling_rule_results.sh
- Tests/scripts/test_playbooks_results.sh
fixing jira convert to tickets, wrong path.
> fixing jira convert to tickets, wrong path.

- Utils/github_workflow_scripts/github_workflow_scripts_tests/link_pr_to_jira_issue_test.py
- Utils/github_workflow_scripts/jira_integration_scripts/link_pr_to_jira_issue.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8719
Added regex to catch issues in the new Jira instance.
> Added regex to catch the Jira DC issues

- Tests/scripts/test_modeling_rule_results.sh
- Tests/scripts/test_playbooks_results.sh
fixing jira convert to tickets, wrong path to artifacts folder
> fixing jira convert to tickets, wrong path to artifacts folder

- Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py
- Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml
- Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_37.md
- Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-29625)
Fixed the client authorization workflow.
> fixed a bug

- Packs/MandiantAdvantageThreatIntelligence/Integrations/MandiantAdvantageThreatIntelligence/MandiantAdvantageThreatIntelligence.py
- Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_0_11.md
- Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
Fixes an issue experienced by a customer when no Threat Actors were ingested.
> Fixing issue with empty actor/malware list

- Packs/BluecatAddressManager/Integrations/BluecatAddressManager/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-4382)
update the API version Bluecat supports
> Update README with correct API version.

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- .gitlab/ci/.gitlab-ci.on-push.yml
fix merge dev secrets and sync buckets
> fix merge dev secrets and sync buckets

- Packs/MicrosoftDHCP/ModelingRules/MicrosoftDHCP_1_3/MicrosoftDHCP_1_3.xif
- Packs/MicrosoftDHCP/ReleaseNotes/1_0_3.md
- Packs/MicrosoftDHCP/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8759)
Fixed the logic of the target ip mapping in the modeling rule.
> Fix for dhcp

- Tests/scripts/collect_tests/collect_tests.py
https://panw-global.slack.com/archives/G011E63JXPB/p1698841171967629
comment out us it looks unused and adding unchanged_files to the changed_files
> collect_tests: removing unused condition

- Tests/test_content.py
- Tests/tests/configure_and_test_integration_instances_test.py
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-6637
temporary fix for finding invalid server version
> temporary fix for finding invalid server version

- Packs/CortexDataLake/Integrations/CortexDataLake/README.md
https://jira-dc.paloaltonetworks.com/browse/XSUP-22707
Add path to get customer name for XSOAR 8.  This is available for Admins only
> Update README.md with XSOAR 8 info

- Packs/Armis/Integrations/Armis/Armis.py
- Packs/Armis/Integrations/Armis/Armis.yml
- Packs/Armis/Integrations/Armis/Armis_test.py
- Packs/Armis/ReleaseNotes/1_1_6.md
- Packs/Armis/pack_metadata.json
Updated the authentication mechanism to pass the secret key in the body parameter
> Armis Release 116: Updated the authentication mechanism to pass the secret key in the body parameter.

- Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md
- Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector_description.md
- Packs/TrendMicroVisionOne/ReleaseNotes/3_0_4.md
- Packs/TrendMicroVisionOne/pack_metadata.json
Updated the link to the **search detection** log api documentation in the help section.
> [trend-micro-vision-one] - update wrong link to search logs

- Packs/Tenable_io/ModelingRules/TenableioEventCollector_1_3/TenableioEventCollector_1_3_schema.json
- Packs/Tenable_io/ReleaseNotes/2_1_14.md
- Packs/Tenable_io/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8822)
> Tenable IO Update

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
> fix bucket upload

- Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.py
- Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml
- Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3_test.py
- Packs/ThreatConnect/ReleaseNotes/3_0_14.md
- Packs/ThreatConnect/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-96591
replace split args with argToList function
> change arg split to argToList

- Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8787
correct the wrong condition in the TPB
(try to compare two elements at index 0 from two arrays which may be not always in the same order)
> MicrosoftDefenderAdvancedThreatProtection - fix TPB

- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8654
put the relevant instance name in conf file as there is one new secret which cause the integration to fail
> QRadar: update conf file with instance name

- Packs/RTIR/Integrations/RTIR/RTIR.yml
- Packs/RTIR/Integrations/RTIR/RTIR_description.md
- Packs/RTIR/ReleaseNotes/1_0_19.md
- Packs/RTIR/pack_metadata.json
> [RTIR] Improving the description

- Tests/Marketplace/upload_packs.py
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8814)
Removed the  check_if_exists_in_index function.
> [UploadFlow Ref] Remove check_if_exists_in_index

- Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.py
- Packs/Okta/ReleaseNotes/3_2_4.md
- Packs/Okta/pack_metadata.json
> Handle lint errors.

- Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_13.md
- Packs/CortexAttackSurfaceManagement/Scripts/GenerateASMReport/GenerateASMReport.yml
- Packs/CortexAttackSurfaceManagement/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-6887
Update the docker version of the script.
> [ASM] EXPANDR-6887 Docker version changes

- Packs/Exchange2016_Compliance/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-4169
Made the pack hidden
> made exchange2016compliance hidden

- Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.py
- Packs/Darktrace/ReleaseNotes/3_0_6.md
- Packs/Darktrace/pack_metadata.json
Fixing an issue where DarktraceMBs actions requiring HTTP POST would fail when the target instance is a Darktrace Unified View instance.
> Darktrace: Patch post request

- Packs/ThreatGrid/Integrations/FeedCiscoSecureMalwareAnalytics/FeedCiscoSecureMalwareAnalytics.py
- Packs/ThreatGrid/ReleaseNotes/2_0_16.md
- Packs/ThreatGrid/ReleaseNotes/2_0_17.md
- Packs/ThreatGrid/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-29855
Fixed a few params.
> fixed base url

- .gitlab/ci/.gitlab-ci.global.yml
fixing cloud machine unlock script to handle cases that no machines was locked.
> fixing cloud machine unlock script to handle cases that no machines was locked.

- Packs/CloudIncidentResponse/README.md
Fixed the XSOAR & XSIAM close tags according to [this](https://xsoar.pan.dev/docs/documentation/documentation_tips#cortex-xsoar-and-cortex-xsiam-formatting) docs.
> fix XSOAR XSIAM close tags

- .gitlab/ci/.gitlab-ci.global.yml
- .gitlab/ci/.gitlab-ci.variables.yml
> Revert "Added  *fetch-through-merge-base"

- Packs/BeyondTrustPrivilegedRemoteAccess/pack_metadata.json
- Tests/Marketplace/print_test_playbook_summary.py
- Tests/scripts/common.py
- Tests/scripts/test_playbooks_results.sh
> Oncall artifacts missing

- Packs/Wiz/Integrations/Wiz/Wiz.py
- Packs/Wiz/Integrations/Wiz/Wiz_test.py
- Packs/Wiz/ReleaseNotes/1_2_14.md
- Packs/Wiz/pack_metadata.json
- Updated the error handling for when there are no new Issues to fetch on a periodic fetch in the Pull method, to not show an error.
-
> Wiz 1.2.14

- Packs/FreeEnrichers/pack_metadata.json
Small fixes in the pack meta data to pack names that are not being shown in the pack.
> Free Enrichers - Small fixes to pack names that are missing

- Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
- Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/README.md
- Packs/Anomali_ThreatStream/ReleaseNotes/2_2_4.md
- Packs/Anomali_ThreatStream/pack_metadata.json
fixes:https://jira-dc.paloaltonetworks.com/browse/XSUP-28232
Updated command documentation, since it was not clear hoe to use the command.
> Anomaly add description

- Tests/scripts/validate_synced_buckets.sh
Fix sync validation for xsoar-saas bucket.
> Fix sync validation for xsoar-saas bucket

- Packs/CIRCL/pack_metadata.json
- Packs/FreeEnrichers/pack_metadata.json
Added CIRCL CVE Search to Free Enrichers
> Added CIRCL CVE Search to Free Enrichers

- .gitlab/ci/.gitlab-ci.on-push.yml
> remove legacy rn generator

- Packs/Base/ReleaseNotes/1_32_46.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
- https://github.com/demisto/dockerfiles/pull/22113
fixes: [CRTX-97293](https://jira-dc.paloaltonetworks.com/browse/CRTX-97293)
> Release a new base pack

- .pre-commit-config_template.yaml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8764)
Added the arguments for Ruff and Sourcery hooks.
> Generalized Modes for Ruff and Sourcery hooks

- Packs/AzureSecurityCenter/Integrations/MicrosoftDefenderForCloudEventCollector/MicrosoftDefenderForCloudEventCollector_description.md
- Packs/AzureSecurityCenter/ReleaseNotes/2_0_18.md
- Packs/AzureSecurityCenter/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8986)
Improved the documentation for the authentication of microsoft defender for cloud event collector
> Clear defender for cloud documentation

- .gitlab/ci/.gitlab-ci.on-push.yml
- Tests/Marketplace/upload_packs.py
Fixed an issue where upload_with_dependencies fails because non-modified packs were cleaned and couldn't find their folder to sign and zip them.
> [UploadFlow Ref] Fix upload with dependencies

- Tests/Marketplace/search_and_install_packs.py
change the expected error message json
> change the expected error message json

- .gitlab/ci/.gitlab-ci.variables.yml
fixes: [link to the issue
](https://jira-dc.paloaltonetworks.com/browse/CIAC-9012)
will use instead Git shallow clone, See https://docs.gitlab.com/ee/ci/pipelines/settings.html#limit-the-number-of-changes-fetched-during-clone
> removed GIT_DEPTH

- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.py
- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR_test.py
- Packs/ImageOCR/Integrations/ImageOCR/README.md
- Packs/ImageOCR/ReleaseNotes/1_1_21.md
- Packs/ImageOCR/pack_metadata.json
Added support for providing multiple Entry IDs to ImageOCR integration
> support multiple entry ids in ImageOCR

- .gitlab/ci/.gitlab-ci.on-push.yml
> generate empty junit files for e2e/tpbs

- Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
> [xsoar saas] - fix ports taxii2 e2e

- Tests/conf.json
Skip ThreatStream-Test because Anomali ThreatStream Inaccessible From Self-Service:
https://jira-dc.paloaltonetworks.com/browse/CRTX-96526
> Skip ThreatStream-Test

- Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.py
- Packs/TAXIIServer/Integrations/TAXII2Server/TAXII2Server.yml
- Packs/TAXIIServer/ReleaseNotes/2_0_51.md
- Packs/TAXIIServer/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9045)
> Taxii2 server relationship bug

- Packs/RDPCacheHunting/.pack-ignore
> update pack ignore

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
> Check if should run Instance role

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
- Tests/scripts/validate_synced_buckets.sh
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8669)
Added sync from the saas prod.
> Sync mp xsoar saas - with saas bucket.

- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
- Packs/CortexDataLake/ReleaseNotes/1_4_8.md
- Packs/CortexDataLake/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9019)
Update the Docker Image.
> [Cortex Data Lake] Update the Docker Image and run ruff

- Packs/HelloWorld/IncidentFields/incidentfield-Hello_World_OnPrem.json
- Packs/HelloWorld/ReleaseNotes/3_0_2.md
- Packs/HelloWorld/pack_metadata.json
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9136)
A incident field that is supposed to be present only in xsoar on-prem for demonstration purpose
> incident field helloworld onprem

- Packs/CommonScripts/ReleaseNotes/1_12_55.md
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2_test.py
- Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-30843, https://jira-dc.paloaltonetworks.com/browse/XSUP-30803
- Fixed an issue where the Bcc was not parsed.
- Fixed an issue where EML files were not parsed if they contained text at the beginning.
> update ParseEmailFilesV2 to 0.1.19

- Packs/CiscoSMA/ModelingRules/CiscoSMAModelingRules_1_3/CiscoSMAModelingRules_1_3.xif
- Packs/CiscoSMA/ReleaseNotes/1_1_24.md
- Packs/CiscoSMA/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-99312)
> CISCO SMA u200b Update

- Packs/CortexXDR/README.md
- Packs/MalwareInvestigationAndResponse/README.md
Updated ReadMe files with the correct image path 
Instead of `github.com` we now use the `raw.githubusercontent.com`
> Update "malware investigation and response" and cortex xdr image path

- Packs/Base/ReleaseNotes/1_33_4.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
- https://github.com/demisto/dockerfiles/pull/22956
fixes: [CRTX-96742](https://jira-dc.paloaltonetworks.com/browse/CRTX-96742)
> CRTX-96742: Release a new base pack

- Tests/scripts/check_jobs_done.py
> added xsoar-saas_test_e2e_results

- Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py
- Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml
- Packs/FreshworksFreshservice/ReleaseNotes/1_0_19.md
- Packs/FreshworksFreshservice/pack_metadata.json
Adding more debug logs to the integration
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-30067)
> added logs

- Packs/EmailCommunication/Classifiers/classifier-EWS_-_Incoming_Mapper_-_Email_Communication.json
- Packs/EmailCommunication/Classifiers/classifier-Gmail_-_Incoming_Mapper_-_Email_Communication.json
- Packs/EmailCommunication/Classifiers/classifier-MSGraphMailSingleUser_-_Incoming_Mapper_-_Email_Communication.json
- Packs/EmailCommunication/Classifiers/classifier-MSGraphMail_-_Incoming_Mapper_-_Email_Communication.json
- Packs/EmailCommunication/ReleaseNotes/2_0_16.json
- Packs/EmailCommunication/ReleaseNotes/2_0_16.md
- Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
- Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
- Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py
- Packs/EmailCommunication/pack_metadata.json
[XSUP-31203](https://jira-dc.paloaltonetworks.com/browse/XSUP-31203)
> Fix email com

- .gitlab/ci/.gitlab-ci.on-push.yml
> adding xsoar-saas_test_e2e_results to needs list

- Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.py
- Packs/OpenCVE/Integrations/OpenCVE/OpenCVE.yml
- Packs/OpenCVE/Integrations/OpenCVE/test_data/CVE-2021-26418.json
- Packs/OpenCVE/ReleaseNotes/1_0_2.md
- Packs/OpenCVE/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31415
OpenCVE throws an error when trying to enrich a CVE
> OpenCVE throws an error when trying to enrich a CVE

- .circleci/config.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9209
> install specific version of neo4j in ci

- Packs/Elasticsearch/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2241
Remove irrelevant content and provide correct content
> Update Elasticsearch pack README.md

- Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.py
- Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
- Packs/AzureCompute/ReleaseNotes/1_2_19.md
- Packs/AzureCompute/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-100312)
- Fixed an issue about the API Version in the following commands:
- azure-vm-create-nic
- azure-vm-get-nic-details
- azure-vm-get-public-ip-details
- Updated the Docker image to: *demisto/crypto:1.0.0.83343*.
> [Azure Compute v2] Fixed the API version

- Packs/Tessian/README.md
- Packs/Tessian/pack_metadata.json
–
This pull request updates the copy of the description of Tessian's integration
> Update copy of Tessian Integration

- Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
Align the `run_cli_command` to the new SDK release.
> [xsoar-saas-e2e] - align run_cli_command to SDK release

- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0.xif
- Packs/DuoAdminApi/ReleaseNotes/4_0_15.md
- Packs/DuoAdminApi/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31043)
> Duo 2.0 (Research) Update

- Packs/CheckPointDome9/pack_metadata.json
- Packs/CheckPointHEC/pack_metadata.json
- Packs/CheckPointSandBlast/pack_metadata.json
- Packs/CheckpointFirewall/pack_metadata.json
fixes: [CIAC-9214](https://jira-dc.paloaltonetworks.com/browse/CIAC-9214)
This PR adds keywords to the existing checkpoint content packs metadata in order to improve the search for these packs on the content marketplace.
> xsiam-checkpoint-add-mp-keywords-ciac-9214

- Packs/CheckPointDome9/pack_metadata.json
- Packs/CheckPointHEC/pack_metadata.json
- Packs/CheckPointSandBlast/pack_metadata.json
- Packs/CheckpointFirewall/pack_metadata.json
- Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
- Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0.xif
- Packs/DuoAdminApi/ReleaseNotes/4_0_15.md
- Packs/DuoAdminApi/ReleaseNotes/4_0_16.md
- Packs/DuoAdminApi/pack_metadata.json
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
- Packs/HashiCorp-Vault/ReleaseNotes/1_1_21.md
- Packs/HashiCorp-Vault/pack_metadata.json
- Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
- Packs/Kafka/ReleaseNotes/2_0_20.md
- Packs/Kafka/pack_metadata.json
- Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
- Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
- Packs/TeamCymru/ReleaseNotes/1_0_20.md
- Packs/TeamCymru/pack_metadata.json
New Integration
Integration with FortiGuard Threat Intel to Fetch Indicators and Query URL Categories
> FortiGuard Threat Intel & Enrichment

- Packs/CheckPointDome9/pack_metadata.json
- Packs/CheckPointHEC/pack_metadata.json
- Packs/CheckPointSandBlast/pack_metadata.json
- Packs/CheckpointFirewall/pack_metadata.json
- Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
- Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0.xif
- Packs/DuoAdminApi/ReleaseNotes/4_0_15.md
- Packs/DuoAdminApi/ReleaseNotes/4_0_16.md
- Packs/DuoAdminApi/pack_metadata.json
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
- Packs/HashiCorp-Vault/ReleaseNotes/1_1_21.md
- Packs/HashiCorp-Vault/pack_metadata.json
- Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
- Packs/Kafka/ReleaseNotes/2_0_20.md
- Packs/Kafka/pack_metadata.json
- Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
- Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
- Packs/TeamCymru/ReleaseNotes/1_0_20.md
- Packs/TeamCymru/pack_metadata.json
fixed: all previous Authentication Issues switching from a credentials  to API Tokens
The Goal is to Fix the Content Pack because I have to post it every time to different customer and explaining why the current package doesn't work as it isn't updated, hence updated 😁.
https://github.com/demisto/content/commit/9e4efd7a7a2ba07c6d00931f06aff133ba7d79fd
> FortiGate XSOAR integration Updated for version 6.x FortiOS

- Packs/CheckPointDome9/pack_metadata.json
- Packs/CheckPointHEC/pack_metadata.json
- Packs/CheckPointSandBlast/pack_metadata.json
- Packs/CheckpointFirewall/pack_metadata.json
- Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
- Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
- Packs/DuoAdminApi/ModelingRules/DuoModelingRule_2_0/DuoModelingRule_2_0.xif
- Packs/DuoAdminApi/ReleaseNotes/4_0_15.md
- Packs/DuoAdminApi/ReleaseNotes/4_0_16.md
- Packs/DuoAdminApi/pack_metadata.json
- Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
- Packs/HashiCorp-Vault/ReleaseNotes/1_1_21.md
- Packs/HashiCorp-Vault/pack_metadata.json
- Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
- Packs/Kafka/ReleaseNotes/2_0_20.md
- Packs/Kafka/pack_metadata.json
- Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/README.md
- Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
- Packs/TeamCymru/ReleaseNotes/1_0_20.md
- Packs/TeamCymru/pack_metadata.json
No public issue
Fix hardcoded HREF in the Illumio Rapid ransomware containment playbook.
> Illumio Content Pack - Fix hardcoded IP list HREF

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
> fix validate condition

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
This implements https://xsoar.ideas.aha.io/ideas/FR-I-3623
Add a Version of the Integration that is compatible with an on-premise instance
The On-Premise Integration is a direct copy of the existing Cloud integration with the following adjustments:
- Removed already deprecated ´export-to-jbxview´ parameter usage
- Remove 'Cloud Only' ´delete-after-days´ parameter 
Details regarding Deprecation / Cloud Only taken from https://github.com/joesecurity/jbxapi/blob/master/jbxapi.py
- The "Detonate File - Joe Sandbox V2" Playbook has been adjusted, to support both Versions of the …
> Add Joesecurity onprem integration

- Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
- Packs/VirusTotal/ReleaseNotes/2_6_13.md
- Packs/VirusTotal/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31602
> [VirusTotal] Fix missing suspicious value for running instances

- Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.xif
- Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass.yml
- Packs/Siemens_SiPass/ModelingRules/Siemens_SiPass/Siemens_SiPass_schema.json
- Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.xif
- Packs/Siemens_SiPass/ParsingRules/Siemens_SiPass/Siemens_SiPass.yml
- Packs/Siemens_SiPass/README.md
- Packs/Siemens_SiPass/pack_metadata.json
> Test branch before sync

- Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
- Packs/SentinelOne/ReleaseNotes/3_2_15.md
- Packs/SentinelOne/pack_metadata.json
> SentinelOneV2

- .github/workflows/pre-commit-reuse.yml
> Revert "code-freeze - added exit 1"

- Packs/ThreatIntelligenceManagement/Dashboards/dashboard-Threat_Intelligence_Management.json
- Packs/ThreatIntelligenceManagement/ReleaseNotes/1_1_7.md
- Packs/ThreatIntelligenceManagement/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-101151
Fixed the query by adding paranthesis to allow it to filter by type.
> Fixed wrong query in widget "Indicator by type"

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- Packs/MicrosoftTeams/ReleaseNotes/1_4_44.md
- Packs/MicrosoftTeams/pack_metadata.json
> Teams documentation update

- .gitlab/ci/.gitlab-ci.global.yml
> Fix skipping unit tests on test upload

- Packs/MailSenderNew/TestPlaybooks/playbook-Email_Sender_Python.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8789)
Fix the TPB.
> [Mail Sender (New)] Fix the TPB

- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.py
- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR_test.py
- Packs/ImageOCR/Integrations/ImageOCR/README.md
- Packs/ImageOCR/ReleaseNotes/1_1_24.json
- Packs/ImageOCR/ReleaseNotes/1_1_24.md
- Packs/ImageOCR/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31355
Removed the *skip_corrupted* argument from the ***image-ocr-list-languages*** command to be an integration parameter instead.
> [ImageOCR] move to parameter

- .gitlab/ci/.gitlab-ci.on-push.yml
Checking if the Gitlab variable - "CI_COMMIT_TITLE" is what I expect it to be.
> Test the "commit title" gitlab veriable

- Packs/Phishing/Playbooks/Phishing_-_Generic_v3_6_8.yml
- Packs/Phishing/ReleaseNotes/3_6_4.md
- Packs/Phishing/pack_metadata.json
https://github.com/demisto/demisto-sdk/pull/3908
> PB input/output sections - align field names with backend

- .pre-commit-config_template.yaml
* add fixable property
* add min_py_version property
* save pytest coverage reports in the pre-commit folder and use parallel mode.
> Pre commit config template config update

- .github/content_roles.json
> change on call to thefrieddan1 and MosheEichler

- Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.ps1
- Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.yml
- Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/README.md
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_36.md
- Packs/MicrosoftExchangeOnline/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V3-Test copy.yml
- Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-1292
added 3 new commnds for forwarding rules.
> Ews new rules commands

- Tests/conf.json
Revert [changes](https://github.com/demisto/content/pull/31174/files#diff-c3c83c2d208e31cadb814b0d9ebd7641fb52547cd965fd7919bd38b5081bc6c2) in conf.json file
> Revert Changes In conf.json File

- .gitlab/ci/.gitlab-ci.global.yml
- Tests/scripts/check_jobs_done.py
> Revert "Add new validate manager to builds"

- .github/workflows/review-release-notes.yml
- Tests/secrets_white_list.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9382
> Upgrade tj-actions/changed-files

- Packs/CommonPlaybooks/Playbooks/playbook-Wait_Until_Datetime.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_5_4.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31808)
Added another transformer for the sleep commend to round non int values.
> Added round transformer for playbook "wait until datetime"

- Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
- Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.yml
- Packs/PagerDuty/Integrations/PagerDuty/PagerDuty_test.py
- Packs/PagerDuty/ReleaseNotes/1_1_9.md
- Packs/PagerDuty/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31703)
Fixed an issue where logging an error caused a timeout.
> Xsup 31703 pager duty

- .github/workflows/pre-commit-reuse.yml
Forks does not have permission to comment on our PR, so this will skip the comment.
> [Pre-Commit] Dont comment in fork PR

- Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9397
Added freeze time to Divo UT to ignore flaky errors.
> freeze time for Devo UT

- Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31937
Added documentation to clarify default microsoft behavior
> Update Documentation for S&C

- Packs/GCP-Enrichment-Remediation/.pack-ignore
- Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation.yml
- Packs/GCP-Enrichment-Remediation/Playbooks/GCP_-_Firewall_Remediation_README.md
- Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_13.md
- Packs/GCP-Enrichment-Remediation/pack_metadata.json
@johnnywilkes
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-7532)
Added the instance_name input to allow the ability to specify Google Cloud Compute integration instance if you have multiple (optional).
> GCP - Specify instance on 'GCP - Firewall Remediation' playbook (#31854)

- Packs/Base/ReleaseNotes/1_33_14.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
Fixing issue with tables are not displaying their whole rows.
And an issue that we had overlapping sections.
- https://github.com/demisto/dockerfiles/pull/23233
fixes: [CRTX-96742](https://jira-dc.paloaltonetworks.com/browse/CRTX-96742)
> CRTX-101690: Release a new base pack

- Packs/Fortimail/Integrations/Fortimail/Fortimail_description.md
- Packs/Fortimail/ReleaseNotes/1_0_1.md
- Packs/Fortimail/pack_metadata.json
> Clearify the integration description

- Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_19.md
- Packs/CortexAttackSurfaceManagement/Triggers/Trigger_-_Cortex_ASM_-_ASM_Alert.json
- Packs/CortexAttackSurfaceManagement/pack_metadata.json
EXPANDR-2883
Playbook trigger suggestion for Cortex ASM pack
> [ASM] - EXPANDR-2883 Playbook trigger suggestion

- Packs/Mimecast/Integrations/MimecastV2/MimecastV2.py
- Packs/Mimecast/Integrations/MimecastV2/MimecastV2.yml
- Packs/Mimecast/Integrations/MimecastV2/MimecastV2_test.py
- Packs/Mimecast/Integrations/MimecastV2/README.md
- Packs/Mimecast/ReleaseNotes/2_2_2.md
- Packs/Mimecast/ReleaseNotes/2_2_3.md
- Packs/Mimecast/pack_metadata.json
Updated the **mimecast-get-message** outputs to include File.Extension.
- Updated the **mimecast-download-attachments** outputs to include File.Extension and Mimecast.Message.Attachments.Extension
- 
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-31117)
> Xsup 31117 mimecast

- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9450
Since the integratoin is supported only on server 6.10
> set AWS organizations test to 6.10

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_12_13.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
Fixed the function to retrieve correct ioa rules correctly. This has been tested on our environment.
This is related to the recent changes from these pull request
https://github.com/demisto/content/pull/31992
https://github.com/demisto/content/pull/32124
> [Crowdstrike Falcon] Update CrowdStrikeFalcon.py - Fixed the function to retrieve correct ioa rules correctly.

- Packs/Reco/README.md
- Packs/Reco/pack_metadata.json
> Packs/Reco: update description and readme

- Tests/tests_e2e/content/xsoar_saas/test_e2e_xsoar_saas.py
> [saas-e2e] - print incident metadata each iteration

- Packs/CommonScripts/Scripts/GetDockerImageLatestTag/GetDockerImageLatestTag_test.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9457
Mock the http requests in docker image UT.
> mock requests for docker image UT

- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py
- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml
- Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector_description.md
- Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_1_54.md
- Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-32191)
Fixed after changes implemented in https://github.com/demisto/content/pull/29574
> [Microsoft Defender for Cloud Apps Event Collector] Fix the Client

- .gitlab/ci/.gitlab-ci.on-push.yml
- .gitlab/ci/.gitlab-ci.sdk-nightly.yml
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9425
Skipping for now until this issue will be done.
> Skipped end 2 end tests

- Packs/AlibabaActionTrail/CorrelationRules/AlibabaActionTrail_Correlation.yml
- Packs/AlibabaActionTrail/ReleaseNotes/1_0_22.md
- Packs/AlibabaActionTrail/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-102915)
> Alibaba ActionTrail CorrelationRules Fix

- Packs/Phishing/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9468
Added dependency on Microsoft Exchange online pack
> Added dependency on Microsoft exchange online pack

- Packs/CommonTypes/IndicatorFields/indicatorfield-Blocked.json
- Packs/CommonTypes/ReleaseNotes/3_3_99.md
- Packs/CommonTypes/pack_metadata.json
fixes: N.A.
Update **_Blocked_** indicator field to be searchable.
> Update blocked indicator field to be searchable

- Packs/CarbonBlackEnterpriseEDR/CONTRIBUTORS.json
- Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py
- Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
- Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py
- Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
- Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/command_examples.txt
- Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_33.md
- Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
Extending CarbonBlackEnterpriseEDR to support API v7 new functionalities.
- Add tags to threats
- Add threat notes
- Add alerts notes
- Get threat tags
PR related to https://github.com/demisto/content/pull/28232 that was closed to get clearance from customer.
> Extend CarbonBlackEnterpriseEDR to support new API v7 methods. 

- Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif
- Packs/LinuxEventsCollection/ReleaseNotes/1_0_8.md
- Packs/LinuxEventsCollection/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9449)
> Linux events collection par diff fix

- Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
- Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.yml
- Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement_test.py
- Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md
- Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_1_21.md
- Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-30281)
Adding the change the customer suggested to retrieve the correct information of the physical Byte memory.
> 30281 fix msgraph updated

- Packs/BluecatAddressManager/ParsingRules/BluecatAddressManager_1_3/BluecatAddressManager_1_3.xif
- Packs/BluecatAddressManager/ReleaseNotes/1_1_12.md
- Packs/BluecatAddressManager/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9449)
> Bluecat am srx par diff fix

- Packs/Barracuda_Cloudgen_Firewall/ParsingRules/Barracuda_Cloudgen_FirewallParsingRules/Barracuda_Cloudgen_FirewallParsingRules.xif
- Packs/Barracuda_Cloudgen_Firewall/ReleaseNotes/1_0_2.md
- Packs/Barracuda_Cloudgen_Firewall/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9449)
> Barracuda cf srx par diff fix

- Packs/FiltersAndTransformers/ReleaseNotes/1_2_54.md
- Packs/FiltersAndTransformers/Scripts/SetIfEmpty/SetIfEmpty.js
- Packs/FiltersAndTransformers/Scripts/SetIfEmpty/SetIfEmpty.yml
- Packs/FiltersAndTransformers/TestPlaybooks/SetIfEmptyTest.yml
- Packs/FiltersAndTransformers/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-32348)
Fixed an issue in the **defaultValue** argument, where it failed to handle values from context paths.
> [SetIfEmpty] Fixed an issue in defaultValue arg

- Packs/PhishingURL/TestPlaybooks/DBotPredictURLPhishing_test.yml
> fix tpb DBotPredictURLPhishing_test

- .github/CODEOWNERS
Add me as code owner to versions-metadata.json file.
> Add code owner to versions-metadata.json

- Packs/CommonPlaybooks/TestPlaybooks/playbook-Retrieve_File_from_Endpoint_-_Generic_V3_Test.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8613
> fix tpb Retrieve File from Endpoint - Generic V3 Test

- Packs/AMP/Integrations/AMPv2/AMPv2.yml
- Packs/Jira/Integrations/JiraV3/JiraV3.py
- Packs/Jira/Integrations/JiraV3/JiraV3.yml
- Packs/Jira/Integrations/JiraV3/JiraV3_test.py
- Packs/Jira/Integrations/JiraV3/README.md
- Packs/Jira/ReleaseNotes/3_1_8.md
- Packs/Jira/TestPlaybooks/playbook_JiraV3_Test.yml
- Packs/Jira/pack_metadata.json
> Revert "Test SK"

- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-8613
> add integration

- Packs/XSOARmirroring/Integrations/XSOARmirroring/README.md
- Packs/XSOARmirroring/ReleaseNotes/2_0_22.md
- Packs/XSOARmirroring/pack_metadata.json
New version of integration with EclecticIQ Intelligence Center. New commands and functionality.
> EclecticIQv3integration

- Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_6_5.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9467
https://jira-dc.paloaltonetworks.com/browse/CIAC-9535
> Blockindicatorfix

- .github/workflows/create-internal-pr-from-external.yml
- Utils/github_workflow_scripts/create_internal_pr.py
links to test PR's
https://github.com/demisto/content/pull/32369
https://github.com/demisto/content/pull/32374
> Fixed Create Internal PR

- Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
- Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
- Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
- Packs/Elasticsearch/ReleaseNotes/1_3_19.md
- Packs/Elasticsearch/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32388
Reduced the load of the test button. Now there is a dedicated command for the additional tests.
> Elasticsearch update test

- Packs/Slack/ReleaseNotes/3_4_3.json
- Packs/Slack/ReleaseNotes/3_4_3.md
- Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse.py
- Packs/Slack/Scripts/GetSlackBlockBuilderResponse/GetSlackBlockBuilderResponse.yml
- Packs/Slack/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32476
Reversed the list of entries so the latest is always used first.
> Reverse entries so SBB script will receive latest entry

- Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
- Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/README.md
- Packs/DemistoRESTAPI/ReleaseNotes/1_3_46.md
- Packs/DemistoRESTAPI/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-31921
> file exists in context description

- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
- Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
- Packs/ServiceNow/ReleaseNotes/2_5_51.md
- Packs/ServiceNow/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32555
> SNow display name fetch param fix

- Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/README.md
https://github.com/demisto/content/pull/32349
> SK Test Notify External PR Merge  

- Packs/AWS_WAF/README.md
- Packs/CheckpointFirewall/README.md
- Packs/CiscoStealthwatch/README.md
- Packs/DelineaSS/README.md
- Packs/Forcepoint/README.md
- Packs/IllusiveNetworks/README.md
- Packs/IronPort/README.md
- Packs/McAfeeNSM/README.md
- Packs/SafeNet_Trusted_Access/README.md
- Packs/Salesforce/README.md
- Packs/SymantecEndpointProtection/README.md
- Packs/TaniumThreatResponse/README.md
- Packs/cisco-ise/README.md
- Packs/epo/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8343)
> Packs <~XSIAM> tags additions

- Packs/FiltersAndTransformers/ReleaseNotes/1_2_56.md
- Packs/FiltersAndTransformers/Scripts/SetIfEmpty/SetIfEmpty.js
- Packs/FiltersAndTransformers/TestPlaybooks/SetIfEmptyTest.yml
- Packs/FiltersAndTransformers/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-32809)
Fixed an issue where the script incorrectly parsed values when chaining transformers.
> [SetIfEmpty] Fixed an issue in case of chaining transformers

- Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.py
- Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX.yml
- Packs/FireEyeNX/Integrations/FireEyeNX/FireEyeNX_test.py
- Packs/FireEyeNX/ReleaseNotes/1_1_30.md
- Packs/FireEyeNX/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32456
UT failure:
> fix 404 error in fetch

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- Packs/MicrosoftTeams/ReleaseNotes/1_4_49.md
- Packs/MicrosoftTeams/pack_metadata.json
updated the docs to support xsoar 8
> Update MS teams docs

- Tests/conf.json
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9604
Add `memory_threshold`.
> add memory_threshold to Calculate Severity - Generic v2 - Test  

- Packs/CommunityCommonScripts/ReleaseNotes/1_1_6.md
- Packs/CommunityCommonScripts/Scripts/RedactIndicator/RedactIndicator.py
- Packs/CommunityCommonScripts/Scripts/RedactIndicator/RedactIndicator.yml
- Packs/CommunityCommonScripts/pack_metadata.json
n/a
Modify the `redactindicator` script so that it can be used as a transformer, to make it simpler and more intuitive to use. Organize the script into a `main()` function.
> Modify redactindicator script so that it can be used as a transformer

- Packs/IRISDFIR/README.md
> IRIS DFIR clear readme content

- Packs/Slack/Integrations/SlackV3/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2409
> Fix formatting

- Packs/FeedBambenekConsulting/.secrets-ignore
- Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.py
- Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting.yml
- Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/FeedBambenekConsulting_test.py
- Packs/FeedBambenekConsulting/Integrations/FeedBambenekConsulting/README.md
- Packs/FeedBambenekConsulting/ReleaseNotes/1_2_0.md
- Packs/FeedBambenekConsulting/TestPlaybooks/playbook-FeedBambenekConsulting.yml
- Packs/FeedBambenekConsulting/pack_metadata.json
> Added Malware And Phishing Domain Feeds - Bambenek Consulting 

- Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2.yml
- Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_41.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32999
> XSUP-32999-fix input description in Detonate URL - WildFire v2.2

- Packs/MicrosoftGraphSecurity/ParsingRules/MicrosoftGraphSecurity/MicrosoftGraphSecurity.xif
- Packs/MicrosoftGraphSecurity/ReleaseNotes/2_2_7.md
- Packs/MicrosoftGraphSecurity/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-33066)
Add support for different milliseconds options.
> Graph security parsing refactor

- Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_6_8.md
- Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-33092)
Added a transformer in the extractIndicators command to remove null values
> Fix command analysis playbook null values

- Tests/conf.json
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9604
> CIAC-9604/add memory_threshold

- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_42.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
- Tests/conf.json
- Tests/docker_native_image_config.json
> SpyCloud Enterprise Protection initial commit

- Packs/FeedBambenekConsulting/README.md
- Packs/FeedBambenekConsulting/ReleaseNotes/1_2_1.md
- Packs/FeedBambenekConsulting/pack_metadata.json
> Bambenek Consulting Adoption

- Packs/HPE_Service_Manager/Integrations/ServiceManager/ServiceManager.js
- Packs/HPE_Service_Manager/Integrations/ServiceManager/ServiceManager.yml
- Packs/HPE_Service_Manager/ReleaseNotes/1_0_6.md
- Packs/HPE_Service_Manager/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-32464
- Enhanced error messaging for failed parsing of the *customFields* argument parsing in the following commands:
- ***hpsm-create-incident***
- ***hpsm-update-incident***
- ***hpsm-create-resource***
- ***hpsm-update-resource***
> [SevriceManager] better error message

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
https://github.com/demisto/content/pull/32708
Updated the condition to verify if the `packs_results_upload.json` file exists before copy to the bucket
> Fix Upload when packs_results_upload.json not exists

- Packs/CiscoESAIronPortEmailAPI/ReleaseNotes/1_1_1.md
- Packs/CiscoESAIronPortEmailAPI/pack_metadata.json
Updated the Cisco_ESA_IronProt rn pointer to a new pack.
> Cisco ESA IronProt Release Note Update

- .github/CODEOWNERS
fixes: None
Updating code ownership.
> change code ownership.

- Packs/AWS-SecurityLake/Integrations/AWSSecurityLake/AWSSecurityLake.yml
- Packs/AWS-SecurityLake/Integrations/AWSSecurityLake/README.md
- Packs/AWS-SecurityLake/ReleaseNotes/1_0_3.json
- Packs/AWS-SecurityLake/ReleaseNotes/1_0_3.md
- Packs/AWS-SecurityLake/pack_metadata.json
Fixed a typo in the yml and readme context path
> Aws data lake fix yml

- .github/workflows/create-internal-pr-from-external.yml
https://github.com/demisto/content/pull/32349
> [Test PR] Private Branch

- .github/workflows/create-internal-pr-from-external.yml
https://github.com/demisto/content/pull/32349
> [TEST PR] Privet Branch

- Tests/conf.json
https://github.com/demisto/content/pull/32854
Added test playbook to the conf file
> [TestIsNotInCidrRanges] Added Test Playbook To The Conf File

- Packs/Base/ReleaseNotes/1_33_29.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
Use `List` instead of `list` for typing
> Fix CommonServerPython mypy

- Packs/PhishingURL/ReleaseNotes/1_1_10.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
- Packs/PhishingURL/pack_metadata.json
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-9467
revert the changes: https://github.com/demisto/content/pull/32916/files
> revert docker changes

- .github/content_roles.json
Updated on call to @BEAdi @israelpoli
> Update on call to Edri & Polishuk

- Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
- Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
- Packs/Syslog/ReleaseNotes/2_0_17.md
- Packs/Syslog/pack_metadata.json
Staging branch & pr for the following PRs which contains `yml` from `Syslog` pack:
https://github.com/demisto/content/pull/32669
https://github.com/demisto/content/pull/32670
> Update docker images of `Syslog` items

- Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
- Packs/Elasticsearch/ReleaseNotes/1_3_20.md
- Packs/Elasticsearch/pack_metadata.json
- Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
- Packs/FeedElasticsearch/ReleaseNotes/1_1_4.md
- Packs/FeedElasticsearch/pack_metadata.json
Update the docker image tag in the following files:
```
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
```
> Update the `elasticsearch` image tag

- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
- Packs/GenericSQL/ReleaseNotes/1_1_7.md
- Packs/GenericSQL/pack_metadata.json
Update the docker image tag in the following files:
```
Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
```
> Update the`genericsql` image tag

- Packs/PAN-OS/Integrations/Panorama/Panorama.yml
- Packs/PAN-OS/ReleaseNotes/2_1_21.md
- Packs/PAN-OS/pack_metadata.json
Update the docker image tag in the following files:
```
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
```
> Update the `pan-os-python` image tag

- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
- Packs/Active_Directory_Query/ReleaseNotes/1_6_29.md
- Packs/Active_Directory_Query/pack_metadata.json
Update the docker image tag in the following files:
```
Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
```
> Update the `ldap` image tag

- Packs/SplunkPy/Integrations/SplunkPy/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-33231, https://jira-dc.paloaltonetworks.com/browse/XSUP-33338
> troubleshooting splunk cloud

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- Packs/MicrosoftTeams/ReleaseNotes/1_4_52.md
- Packs/MicrosoftTeams/pack_metadata.json
* updated readme
* edited description
* added rn
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* lr
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
* Update Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
* Update …
> Teams docs (#32949)

- Packs/MicrosoftDNS/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-33380)
> Update MS DNS README

- .gitlab/ci/.gitlab-ci.on-push.yml
> revert the  nightly in gitlab on-push

- .circleci/config.yml
> Raise neo4j memory limit.

- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/README.md
- Packs/Remedy-On-Demand/Integrations/RemedyOnDemand/RemedyOnDemand.yml
- Packs/Remedy-On-Demand/ReleaseNotes/1_1_4.md
- Packs/Remedy-On-Demand/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-5478)
[A few sentences describing the overall goals of the pull request's commits.](https://jira-dc.paloaltonetworks.com/browse/CIAC-5478) all the work here was done by a contractor besides deprecating the old content
> Deprecate old bmc

- Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/README.md
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34042)
When sending an email, the integration uses the "from" argument as the email sender. If this argument is missing, it then uses the "Email address from which to fetch incidents" parameter as the sender.
> [MicrosoftGraphMail] update docs send-mail command

- Packs/Okta/Integrations/Okta_IAM/README.md
- Packs/Okta/Integrations/Okta_v2/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2567
Fixed formatting so that only commands appear in Pan Dev in the right command selection panel.
> Fix formatting in Readme files

- Packs/PhishingURL/ReleaseNotes/1_1_11.md
- Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.yml
- Packs/PhishingURL/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/XSUP-32123
> Phishing URL Docker Image Update

- Packs/Whois/pack_metadata.json
Update the Whois pack to replace "DomainTools" pack with "DomainTools Iris" pack as optional dependency. The two packs have been merged and "DomainTools Iris" will receive updates going forward.
> [Whois] DomainTools Iris Update

- Packs/DemistoRESTAPI/ReleaseNotes/1_3_51.md
- Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.py
- Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.yml
- Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile_test.py
- Packs/DemistoRESTAPI/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34028)
Add the functionality to run the script uploadFile with a specific integration instance.
> Uploadfile with using argument

- Tests/docker_native_image_config.json
> bump candidate

- Packs/PrismaCloud/Integrations/PrismaCloudV2/PrismaCloudV2.yml
- Packs/PrismaCloud/ReleaseNotes/4_3_0.md
- Packs/PrismaCloud/pack_metadata.json
Mark Prisma Cloud v2 as `hybrid`.
> Mark Prisma Cloud v2 `hybrid`

- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
- Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
- Packs/GenericSQL/ReleaseNotes/1_2_1.md
- Packs/GenericSQL/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34106)
Fixed an issue which caused a timeout error as appears in the related ticket.
> Generic SQL fix

- Packs/SplunkPy/Integrations/SplunkPy/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34057
Updated the versions in the README
> SplunkPy: fix supported version in readme

- Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js
- Packs/DemistoRESTAPI/ReleaseNotes/1_3_52.md
- Packs/DemistoRESTAPI/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-108118
Fix the human readable message.
> CoreRESTAPI: fix command message

- Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py
- Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml
- Packs/HelloWorld/ReleaseNotes/3_0_8.md
- Packs/HelloWorld/pack_metadata.json
> Remove redundant demisto params in HelloWorld integration

- Packs/X509Certificate/ReleaseNotes/1_0_41.md
- Packs/X509Certificate/pack_metadata.json
> fix create graph due to incorrect boolean value

- Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.py
- Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
- Packs/GoogleDrive/ReleaseNotes/1_3_4.md
- Packs/GoogleDrive/pack_metadata.json
> GoogleDrive.py: fix get-parents infinite loop

- Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
- Packs/Mimecast/ReleaseNotes/2_2_5.md
- Packs/Mimecast/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9919)
Fix the broken link in Mimecast documentation.
> Fix broken link in mimecast documentation

- Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.py
- Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
- Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin_test.py
- Packs/GSuiteAdmin/ReleaseNotes/1_1_37.md
- Packs/GSuiteAdmin/pack_metadata.json
- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9926
> Fix conf.json checks failing

- Packs/CommonScripts/ReleaseNotes/1_14_11.md
- Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.py
- Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName.yml
- Packs/CommonScripts/Scripts/IsInternalDomainName/IsInternalDomainName_test.py
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34569)
Fix an issue where the script IsInternalDomainName would return false positive on edge cases.
> Bug fix is internal domain name return false positive

- Packs/FiltersAndTransformers/ReleaseNotes/1_2_64.md
- Packs/FiltersAndTransformers/Scripts/IsInCidrRanges/IsInCidrRanges.js
- Packs/FiltersAndTransformers/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.js
- Packs/FiltersAndTransformers/TestPlaybooks/playbook-TestIsNotInCidrRanges.yml
- Packs/FiltersAndTransformers/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34670
Instead of incorrectly using executeCommand(), the script now has the IsInCidrRanges code hardcoded.
I added comments in both scripts to ensure whoever make changes in one of them will be aware that the change needs to be done in the other.
> [XSUP-34670] Remove usage of executeCommand

- Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_7.md
- Packs/MicrosoftWindowsEvents/XSIAMDashboards/MicrosoftWindowsEvents_Dashboard.json
- Packs/MicrosoftWindowsEvents/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-108866 https://jira-dc.paloaltonetworks.com/browse/CRTX-108862
Added space in the dashboard and fixed a typo
> Fix Microsoft windows events dashboard

- Packs/CommonScripts/Scripts/IsEmailAddressInternal/README.md
- Packs/CommonScripts/Scripts/SetAndHandleEmpty/README.md
- Packs/FiltersAndTransformers/Scripts/SetIfEmpty/README.md
Update the README files with the correct script type.
> Update the README files with the correct script type

- Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py
- Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
- Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_46.md
- Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34666
API Reference: https://developer.carbonblack.com/reference/enterprise-response/latest/rest-api/#search-alerts
> Carbon Black EDR sort

- .github/CODEOWNERS
> Update codeowners files to include the validate config file

- Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml
- Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_47.md
- Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34666
> Carbon Black EDR YML Fix

- Tests/scripts/common.py
- Tests/scripts/gitlab_slack_notifier.py
> Add log prints to Slack notifier

- Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.py
- Packs/Netskope/Integrations/NetskopeAPIv2/NetskopeAPIv2.yml
- Packs/Netskope/ReleaseNotes/3_3_7.md
- Packs/Netskope/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34876)
Fixed an issue where the *list_type* argument not working as expected in the **netskope-url-list-update** and **netskope-url-list-create** commands.
> [netskope_api_v2] Fixed an issue in the list_type argument

- Packs/CortexXDR/Integrations/XDR_iocs/README.md
https://jira-dc.paloaltonetworks.com/browse/XSUP-34855
Updated the README file with the **xdr-iocs-create-sync-file** inputs
> Cortex XDR - IOC - update xdr-iocs-create-sync-file in README

- Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
- Packs/Active_Directory_Query/ReleaseNotes/1_6_33.md
- Packs/Active_Directory_Query/pack_metadata.json
should be args.get('group-cn') instead of args.get('group_name')
> Active Directory Query - correct argument name in add_member_to_group()

- Packs/FiltersAndTransformers/ReleaseNotes/1_2_65.md
- Packs/FiltersAndTransformers/Scripts/IsNotInCidrRanges/IsNotInCidrRanges.js
- Packs/FiltersAndTransformers/TestPlaybooks/playbook-TestIsNotInCidrRanges.yml
- Packs/FiltersAndTransformers/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-35016
The test playbook now checks the two possible results for the filter.
> fix is not in cidr bug

- Packs/CommonTypes/IncidentFields/incidentfield-Containment_SLA.json
- Packs/CommonTypes/IncidentFields/incidentfield-Incident_Duration.json
- Packs/CommonTypes/IncidentFields/incidentfield-Triage_SLA.json
- Packs/CommonTypes/ReleaseNotes/3_4_6.md
- Packs/CommonTypes/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10004)
Change sla timer fields from unsearchable to searchable, to use them in dashboards
> CIAC-10004/Change-Triage-SLA-incident-field-to-searchable

- Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py
- Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml
- Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md
- Packs/GoogleCloudStorage/ReleaseNotes/1_0_13.md
- Packs/GoogleCloudStorage/pack_metadata.json
N/A
Contributing on behalf of a customer who needs this functionality. Adds a copy command to the Google Cloud Storage integration to copy an object from one storage bucket to another.
> Add copy command to Google Cloud Storage integration

- Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
As requested, added a link to the supported file types.
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2662
Add this link https://docs.paloaltonetworks.com/advanced-wildfire/administration/advanced-wildfire-overview/advanced-wildfire-file-type-support/advanced-wildfire-file-type-support-complete#idbfe44505-f816-40db-8b28-4047bb834a8c for the supported file types in the Wildfire integration README.
> Add link to supported file types

- Packs/Tenable_sc/Integrations/Tenable_sc/README.md
- Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.yml
- Packs/Tenable_sc/ReleaseNotes/1_0_12.md
- Packs/Tenable_sc/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-108925
short the description
> Tenable_sc: short the description

- Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.py
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_2_44.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-34105)
Fixed an issue where some emails with attachments was not being fetched correctly.
> EWS O365 - fix fetch emails

- Packs/PingCastle/ReleaseNotes/1_0_9.md
- Packs/PingCastle/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10033
Move PingCastle Pack to community support.
> Move PingCastle to Community Support

- Packs/Base/ReleaseNotes/1_33_43.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
- https://github.com/demisto/dockerfiles/pull/25194
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-107246)
> Release new base pack

- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py
- Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py
- Packs/FeedRecordedFuture/ReleaseNotes/1_1_2.md
- Packs/FeedRecordedFuture/pack_metadata.json
fixes: [XSUP-35105](https://jira-dc.paloaltonetworks.com/browse/XSUP-35105)
> Rf threshold bug fix

- Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml
Update the demisto/docxpy docker image of the following integration/scripts which coverage rate of 75-100-Nightly%:
`Packs/CommonScripts/Scripts/ParseWordDoc/ParseWordDoc.yml`
> replace docxpy for office-utils

- Packs/WindowsDefenderAdvancedThreatProtection/pack_metadata.json
Fixed a description to point the users to the right pack.
> fix description Microsoft Defender

- Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py
- Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml
- Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py
- Packs/Akamai_SIEM/ReleaseNotes/1_0_13.md
- Packs/Akamai_SIEM/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10070)
Fixed an issue where **fetch-incidents** was unlimited, limited to a maximum of 2000 incidents per fetch.
> [Akamai WAF SIEM] limit the fetch to 2000

- Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
- Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9857)
Remove failing jobs from the TPB.
> Fix Expanse_V2 TPB

- .gitlab/ci/.gitlab-ci.bucket-upload.yml
nightly: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/915696
> add DEMISTO_SDK_GRAPH_FORCE_CREATE to validate in bucket upload

- Packs/SplunkPy/Integrations/SplunkPy/README.md
- Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
- Packs/SplunkPy/ReleaseNotes/3_1_25.md
- Packs/SplunkPy/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-35014
documentation updates.
> SplunkPy: documentation updates

- .pre-commit-config_template.yaml
Skip the `validate-deleted-files`, `is-circle-changed`, `is-gitlab-changed` hooks when running pre-commit on nightly.
> [pre-commit] - skip some hooks on nightly

- .pre-commit-config_template.yaml
related: https://github.com/demisto/demisto-sdk/pull/4084
> pre-commit path validations 

- .github/workflows/check-nightly-ok-label.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10134
> use three-dot-diff for `nightly-ok`

- Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.py
- Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector.yml
- Packs/CybelAngel/Integrations/CybelAngelEventCollector/CybelAngelEventCollector_test.py
- Packs/CybelAngel/ReleaseNotes/1_0_1.md
- Packs/CybelAngel/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-35422)
Fixed an issue with `CybelAngelEventCollector` where in case the api returned 403, we wouldn't create new token.
> [CybelAngelEventCollector] - fix issue with authentication

- .github/content_roles.json
> changed contribution

- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
- Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
- Packs/CortexXDR/ReleaseNotes/6_1_26.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34724
Fixed the variable to first try the new parameter and take the old one only if the new one doesnt exist
> apikey creds fix

- Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive_description.md
- Packs/GoogleDrive/ReleaseNotes/1_3_6.md
- Packs/GoogleDrive/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-34824
Update the commands and their scopes in the description.md
> GoogleDrive: update scopes in description.md

- Packs/CommonScripts/Scripts/StringReplace/README.md
https://github.com/demisto/content/pull/33349
> Fixed typos in documentation page for StringReplace

- Packs/Base/ReleaseNotes/1_33_46.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
- https://github.com/demisto/dockerfiles/pull/25726
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-111037)
> Release base pack v1.33.46

- Packs/MongoDB/Integrations/MongoDB/MongoDB.py
- Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10102)
> Re-Enable MongoDB TPB

- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10115
> increase memory for Alienvault_OTX_v2

- Packs/Netskope/Integrations/NetskopeEventCollector/NetskopeEventCollector.py
> remove line

- .gitlab/ci/.gitlab-ci.on-push.yml
> [run-pre-commit] fix rules

- Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
Update the `demisto/pycountry_partner` docker image of the following integration/scripts which coverage rate of `0-50%`:
```
Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
```
> update docker image

- Tests/scripts/new_validate.sh
> Fix validate invalid flag issue

- Utils/trigger_contribution_build.py
> Revert "[Trigger contribution build] Add missing ENV variable in trigger pipeline request"

- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
- Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
- Packs/CortexDataLake/ReleaseNotes/1_4_10.md
- Packs/CortexDataLake/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-35208)
Added support rule parameter for the cdl-query-traffic-logs command
> Add support for rule parameter in query-traffic-logs command

- Packs/CortexXDR/Integrations/CortexXDRIR/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2131
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2132
Review Cortex XCR Flexible Close Reason Mappings Mirroring text.
> Review and update CortexXDRIR README.md

- Packs/CommonScripts/ReleaseNotes/1_14_28.md
- Packs/CommonScripts/Scripts/ZipFile/ZipFile.py
- Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10264)
Downgrade the docker image due to TPB errors.
> Revert ZipFile image

- Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.yml
- Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
Packs/PcapAnalysis/Scripts/PcapConvert/PcapConvert.yml
Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
> demisto/pcap-miner:1.0.0.91369 | 0-100 | PR batch #1/3

- Packs/CommonScripts/ReleaseNotes/1_14_28.md
- Packs/CommonScripts/ReleaseNotes/1_14_29.md
- Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
- Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck_test.py
- Packs/CommonScripts/pack_metadata.json
mock the intensive check so the CPU check will work as expected.
> Docker Hardening test - fix flaky test

- Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.yml
- Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.yml
Packs/PcapAnalysis/Scripts/PcapFileExtractor/PcapFileExtractor.yml
Packs/PcapAnalysis/Scripts/PcapFileExtractStreams/PcapFileExtractStreams.yml
> demisto/pcap-miner:1.0.0.91369 | 0-100 | PR batch #2/3

- Packs/SplunkPy/TestPlaybooks/playbook-SplunkPy-Test-V2.yml
fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10231) to the issue
fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10230) to the issue
Updated the arguments for the `splunk-search` command in the `SplunkPy-Test-V2` TPB
- `earliest_time` to `-10d`
- `query` to `sourcetype=*`
> [Splunk] Fixed TPB

- Packs/CommonScripts/ReleaseNotes/1_14_30.md
- Packs/CommonScripts/Scripts/DeleteContext/DeleteContext.js
- Packs/CommonScripts/TestPlaybooks/playbook-DeleteContext-test.yml
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10272)
Removed redundant code for excluding keys deletion when using 'DeleteContext' for deleting all keys.
> drop-redundant-keystokeep-code

- Tests/scripts/collect_tests/collect_tests.py
- Tests/scripts/infrastructure_tests/test_collect_tests.py
When the pack is new, the release note does not exist, so skip the check in these cases.
> fix - sort_packs_to_upload - new pack

- Packs/PcapAnalysis/Scripts/PcapMinerV2/PcapMinerV2.yml
Packs/PcapAnalysis/Scripts/PcapMinerV2/PcapMinerV2.yml
> demisto/pcap-miner:1.0.0.91369 | 0-100 | PR batch #3/3

- .github/content_roles.json
> updated security reviewer

- Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
- Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
- Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
- Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
- Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
- Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
- Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml
- Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
- Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml
- Packs/CommonScripts/Scripts/StixCreator/StixCreator.yml
Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml
Packs/CommonScripts/Scripts/ExifRead/ExifRead.yml
Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/FetchIndicatorsFromFile/FetchIndicatorsFromFile.yml
Packs/CommonScripts/Scripts/LanguageDetect/LanguageDetect.yml
Packs/CommonScripts/Scripts/ParseExcel/ParseExcel.yml …
> demisto/py3-tools:1.0.0.91908 | 0-100 | PR batch #1/3

- Packs/Palo_Alto_Networks_WildFire/Integrations/WildFireReports/WildFireReports_description.md
- Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/2_1_44.md
- Packs/Palo_Alto_Networks_WildFire/pack_metadata.json
Removed unnecessary version which also displayed in XSIAM
> Wf description

- Packs/CommonScripts/ReleaseNotes/1_14_31.md
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.py
- Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10271)
> ParseEmailFilesV2: added log handler

- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks.yml
- Packs/IllusiveNetworks/Integrations/IllusiveNetworks/IllusiveNetworks_test.py
- Packs/IllusiveNetworks/ReleaseNotes/1_0_31.md
- Packs/IllusiveNetworks/pack_metadata.json
due to time not freezed - a test may fail due to diff in times
see https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/5550139#L3582
> IllusiveNetworks: freeze time in unit test 

- Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py
- Packs/SafeBreach/ReleaseNotes/1_4_1.md
- Packs/SafeBreach/pack_metadata.json
> safebreach expose

- Packs/Druva/README.md
continues https://github.com/demisto/content/pull/33706
> druva: fix image link

- Packs/ServiceNow/Integrations/ServiceNowv2/README.md
https://github.com/demisto/content-docs/issues/1541
Ability to call web services in ServiceNow is granted by role snc_platform_rest_api_access.
> Update permission needed for API calls in  ServiceNow

- .gitlab/ci/.gitlab-ci.variables.yml
- .pre-commit-config_template.yaml
- pyproject.toml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10352
> poetry: set `package-mode = false`

- Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10350)
> remove MP from generic webhook

- .pre-commit-config_template.yaml
- Tests/conf.json
only run validate-conf-json in CI, and only if Tests/conf.json changes
related: https://github.com/demisto/content/pull/34027
> minimize validate-conf-json friction

- Packs/Redmine/Integrations/Redmine/Redmine.yml
- Packs/Redmine/ReleaseNotes/1_0_2.md
- Packs/Redmine/pack_metadata.json
Fixed [here](https://github.com/demisto/content/pull/34027) in conf.json, but not in the yml
> Update Redmine.yml tests

- Packs/MicrosoftExchangeOnline/TestPlaybooks/playbook-GetEWSFolder-Test.yml
- Tests/conf.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10378)
add memory_threshold - Failed docker resource test. Docker container exceeded the memory threshold, configured: 100 MiB and actual memory usage is 102.4 MiB.
> add memory_threshold

- Packs/Core/Layouts/layoutscontainer-Identity_Analytics_Alerts.json
- Packs/Core/ReleaseNotes/3_0_25.md
- Packs/Core/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36238)
Updated the layout to utilize the 'VerdictResult' script.
> Identity analytics for XSIAM - layout fix

- Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
- Packs/AnsibleCiscoIOS/ReleaseNotes/1_0_7.md
- Packs/AnsibleCiscoIOS/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36181)
> revert docker

- Packs/ThinkstCanary/Playbooks/playbook-Enrich_Thinkst_Canary_Events.yml
- Packs/ThinkstCanary/ReleaseNotes/1_0_21.md
- Packs/ThinkstCanary/pack_metadata.json
fixes: [XSUP-36296](https://jira-dc.paloaltonetworks.com/browse/XSUP-36296)
Fixed the input for the Set automation in the playbook task
> Thinks canary playbook fix

- .gitlab/ci/.gitlab-ci.global.yml
- .pre-commit-config_template.yaml
Fix the nightly failures 
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/5650676#L2383
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/5649760#L2292
https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/5649760#L2342"
> fix pre commit nightly

- Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml
- Packs/ActiveMQ/ReleaseNotes/1_1_15.md
- Packs/ActiveMQ/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/CRTX-105751
> ActiveMQ Config Data Types

- Packs/PhishTank/TestPlaybooks/playbook-PhishTank-Test.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-7727)
Adding retry mechanism since there is a limit on PhishTank side.
try 3 time (an api call and the interval between the requests is 300 seconds)
> add retry mechanism

- Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml
- Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_34.md
- Packs/CortexAttackSurfaceManagement/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-7915
Add the *SSHTerrapinAttack* attack surface rule to apply to automated remediation.
> [ASM] XPANDR- 7915 - Add the *SSHTerrapinAttack* attack surface rule.

- Packs/MicrosoftExchangeOnline/Integrations/EwsExtensionEXOPowershellV3/EwsExtensionEXOPowershellV3.yml
- Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_6.md
- Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-35116)
per Microsoft error these are the supported options:
> [EWS Extension Online Powershell v3] Update  list_subtype argument to include Submission option

- Packs/CommonPlaybooks/Playbooks/playbook-URL_Enrichment_-_Generic_v2.yml
- Packs/CommonPlaybooks/ReleaseNotes/2_6_30.md
- Packs/CommonPlaybooks/pack_metadata.json
Use the "Is not Empty" condition rather than the "isExists" condition when checking if there are URLs to analyze.
This resolves an issue, if the input is given an empty string, that the "rasterize" command would fail because it can't access an empty string.
This can happen, for example: If there are no URLs in the Context, but the "replace match" transformer is used. For some reason, the output then is an empty string, rather than nothing (as the input was)
There are no Changes in the Layout / other logic, only the Condition was replaced
> Url enrichment

- Packs/RubrikPolaris/.secrets-ignore
- Packs/RubrikPolaris/Integrations/RubrikPolaris/README.md
- Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
- Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
- Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris_test.py
- Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/sonar_user_access_get_response_hr.md
- Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/sonar_user_access_list_response_hr_1_1.md
- Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/sonar_user_access_list_response_hr_1_2.md
- Packs/RubrikPolaris/Integrations/RubrikPolaris/test_data/sonar_user_access_list_response_hr_2_1.md
- Packs/RubrikPolaris/ReleaseNotes/1_3_2.md
- Packs/RubrikPolaris/pack_metadata.json
Added a hyper link to the Human Readable output of the following commands. Users can now click on the hyper link to access the specific user's details on the RSC portal.
> Changes related to the Rubrik Polaris release v1.3.2

- Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.py
- Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
- Packs/CheckPointHEC/ReleaseNotes/1_1_1.md
- Packs/CheckPointHEC/pack_metadata.json
Fetch incidents method is raising an error since a parameter was not properly casted to integer.
> Fix fetching incidents

- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.py
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_test.py
- Packs/GenericWebhook/Integrations/GenericWebhook/README.md
- Packs/GenericWebhook/ReleaseNotes/1_1_0.md
- Packs/GenericWebhook/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9739)
> support multiple incidents in webhook

- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
- Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
- Packs/AzureSentinel/ReleaseNotes/1_5_40.md
- Packs/AzureSentinel/pack_metadata.json
fixes: [XSUP-36474](https://jira-dc.paloaltonetworks.com/browse/XSUP-36474)
Fixed an issue where mirroring labels did not work properly.
> Azure sentinel mirrored labels fix

- Packs/Zscaler/Integrations/Zscaler/Zscaler.py
- Packs/Zscaler/ReleaseNotes/1_3_19.md
- Packs/Zscaler/pack_metadata.json
Lowered the amount of retries in the HTTP request
> Zscaler lowered retries 

- .circleci/config.yml
Use Poetry 1.8.2
test PR: https://github.com/demisto/content/pull/34155, [test CI run](https://app.circleci.com/pipelines/github/demisto/content/359020/workflows/1feee6c6-17e1-43f2-9445-7fbbd91af83c)
> bump CircleCI image tag

- Packs/Palo_Alto_Networks_WildFire/TestPlaybooks/playbook-Wildfire_Test_With_Polling.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10309
> Fix WildFire TPB

- Packs/Carbon_Black_Enterprise_Live_Response/Playbooks/playbook-Get_File_Sample_From_Path_-_VMware_Carbon_Black_EDR_-_Live_Response_API_README.md
- Packs/Carbon_Black_Enterprise_Response/Playbooks/playbook-Get_binary_file_from_Carbon_Black_by_its_MD5_hash_README.md
After changing image files we saw a link to content repo for a specific commit instead of master
> change image link to use master

- Tests/Marketplace/versions-metadata.json
> locked core packs

- Packs/jamf/ParsingRules/jamf/jamf.xif
- Packs/jamf/ReleaseNotes/2_2_1.md
- Packs/jamf/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36721)
> JAMF Pro Parsing Update

- Tests/scripts/linters_runner.sh
- Tests/scripts/utils/logging_wrapper/__init__.py
- Utils/github_workflow_scripts/github_workflow_scripts_tests/autobump_rn_test.py
fixes: https://github.com/demisto/content/pull/34280
> fix `linters_runner.sh`

- Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py
- Packs/Malwarebytes/ReleaseNotes/1_1_17.md
- Packs/Malwarebytes/pack_metadata.json
> [malwarebytes-254] Updated Domain to threatdown.com in Usage Analytics

- Utils/update_contribution_pack_in_base_branch.py
relates: [CIAC-10490](https://jira-dc.paloaltonetworks.com/browse/CIAC-10490)
Add logs to update_contribution_pack_in_base_branch.py
> [Contrib] Add logs to update_contribution_pack_in_base_branch.py

- Packs/CrowdStrikeFalcon/Playbooks/playbook-CrowdStrike_Falcon_-_Get_Detections_by_Incident.yml
- Packs/CrowdStrikeFalcon/TestPlaybooks/Test_Playbook_-_CrowdStrike_Falcon_-_Get_Detections_by_Incident.yml
fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10499) to the issue
Change task no. 248 to take the last incident, not the new one, as there is more information in the last one.
> [CrowdStrike Falcon TPB] 

- Packs/Blueliv/Integrations/Blueliv/Blueliv.yml
- Packs/Blueliv/ReleaseNotes/1_0_4.md
- Packs/Blueliv/pack_metadata.json
fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-8623) to the issue
Deprecate the `Blueliv_beta` integration
> [Blueliv (Beta)] Deprecated

- Packs/Wiz/Integrations/Wiz/README.md
- Packs/Wiz/Integrations/Wiz/Wiz.py
- Packs/Wiz/Integrations/Wiz/Wiz.yml
- Packs/Wiz/Integrations/Wiz/Wiz_test.py
- Packs/Wiz/Integrations/Wiz/command_examples.txt
- Packs/Wiz/ReleaseNotes/1_3_0.json
- Packs/Wiz/ReleaseNotes/1_3_0.md
- Packs/Wiz/pack_metadata.json
- Added the ***wiz-resolve-issue*** command to resolve Thread Detection Issues in Wiz.
- Removed the option to run ***wiz-get-issue-evidence*** for Issues without evidence.
- Improved the performance of commands using ***issue-id***.
> wiz add resolve issue command

- Packs/CommonDashboards/ReleaseNotes/1_4_3.md
- Packs/CommonDashboards/pack_metadata.json
> Fix Common Dashboards pack

- Packs/CitrixADC/pack_metadata.json
fixes: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-10372) to the issue
Added`NetScaler` tag to the `keywords` in the `pack_metadata` file
> [Citrix ADC] Add `NetScaler` Tag 

- Packs/rasterize/Integrations/rasterize/rasterize.yml
- Packs/rasterize/ReleaseNotes/2_0_11.md
- Packs/rasterize/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-36909
> Rasterize Upgrade Docker

- Packs/CortexXDR/.secrets-ignore
- Packs/CortexXDR/Playbooks/Cortex_XDR_-_Large_Upload.yml
- Packs/CortexXDR/Playbooks/Cortex_XDR_-_Large_Upload_README.md
- Packs/CortexXDR/ReleaseNotes/6_1_33.md
- Packs/CortexXDR/ReleaseNotes/6_1_34.md
- Packs/CortexXDR/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10538
1- Incorrect object is being passed as input to task number 3.
2- modification of task number 69 to remove any decimal point that might prevent the task from being executed correctly
> Fixes For 'Cortex XDR - Large Upload' Playbook

- Packs/Base/ReleaseNotes/1_34_2.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
- Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
- Packs/CofenseTriage/ReleaseNotes/2_1_24.md
- Packs/CofenseTriage/pack_metadata.json
- Packs/ExpanseV2/ReleaseNotes/1_10_54.md
- Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml
- Packs/ExpanseV2/pack_metadata.json
- Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml
- Packs/ImageOCR/ReleaseNotes/1_1_31.md
- Packs/ImageOCR/pack_metadata.json
- Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_1.md
- Packs/SuspiciousDomainHunting/Scripts/HtmlDifflabDynamic/HtmlDifflabDynamic.yml
- Packs/SuspiciousDomainHunting/Scripts/HtmlDifflibCheck/HtmlDifflibCheck.yml
- Packs/SuspiciousDomainHunting/pack_metadata.json
relates: [XSUP-36992](https://jira-dc.paloaltonetworks.com/browse/XSUP-36992)
Updated the docker images
> Update docker images

- Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.yml
- Packs/FeedNVDv2/Integrations/FeedNVDv2/README.md
- Packs/FeedNVDv2/ReleaseNotes/1_0_1.md
- Packs/FeedNVDv2/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10592
related: https://github.com/demisto/content-docs/issues/1552
> fix FeedNVDv2 docs

- .github/content_roles.json
Update on-call devs to @yaakovpraisler and @AradCarmi
> On-call devs update

- Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.yml
- Packs/Akamai_WAF/ReleaseNotes/2_0_10.md
- Packs/Akamai_WAF/pack_metadata.json
Update Akamai WAF Docker image. Related to https://github.com/demisto/content/pull/34354.
> Update Akamai WAF Docker Image

- Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py
- Packs/Core/ReleaseNotes/3_0_32.md
- Packs/Core/pack_metadata.json
- Packs/CortexXDR/ReleaseNotes/6_1_36.md
- Packs/CortexXDR/pack_metadata.json
- Packs/ctf01/ReleaseNotes/1_0_14.md
- Packs/ctf01/pack_metadata.json
fixes: [XSUP-37017](https://jira-dc.paloaltonetworks.com/browse/XSUP-37017)
Improved the command. 
Added a validation for the sha256.
> Xdr ir blocklist fix

- Packs/DeveloperTools/ReleaseNotes/1_3_15.md
- Packs/DeveloperTools/Scripts/GetServerInfo/GetServerInfo.yml
- Packs/DeveloperTools/pack_metadata.json
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.py
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml
- Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook_test.py
- Packs/GenericWebhook/ReleaseNotes/1_1_2.md
- Packs/GenericWebhook/pack_metadata.json
fixes: [CIAC-10600](https://jira-dc.paloaltonetworks.com/browse/CIAC-10600)
> add raw_json for bw compatibility

- .gitlab/helper_functions.sh
> commit test

- Utils/github_workflow_scripts/check_protected_directories.py
> fix contribution (circle-ci)

- Packs/AbnormalSecurity/.pack-ignore
related: https://github.com/demisto/content/pull/34374
> fix abnormal hidden param

- .circleci/add_pr_comment.py
- .circleci/comment_on_pr.py
- .circleci/config.yml
- .circleci/linters_runner.sh
- .circleci/mypy.sh
- .circleci/update_contribution_pack_in_base_branch.py
- Tests/Marketplace/landingPage_sections.json
- Utils/github_workflow_scripts/autobump_release_notes/skip_conditions.py
> back all scripts for contribution

- Utils/download_packs_and_docker_images.py
restoring - Utils/download_packs_and_docker_images.py
> restoring - Utils/download_packs_and_docker_images.py

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_9.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-37600
passing proxy param to generic http call
> Use proxy in crwdstrike

- Packs/PrismaCloud/Integrations/PrismaCloudV2/README.md
- Packs/PrismaCloud/pack_metadata.json
related: https://github.com/demisto/demisto-sdk/pull/4302
> Remove Data Source From Prisma Cloud

- Packs/Base/ReleaseNotes/1_34_7.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
- Packs/Base/pack_metadata.json
https://github.com/demisto/dockerfiles/pull/27098
fixes: [CRTX-90233](https://jira-hq.paloaltonetworks.local/browse/CRTX-90233)
> Bump sane-pdf-report docker image

- Packs/Gatewatcher-AionIQ/Integrations/GCenter/GCenter_test.py
relates: [CIAC-10725](https://jira-dc.paloaltonetworks.com/browse/CIAC-10725)
Fixed an issue when the ID of the test is a color name.
> Fix parametrize ID Issue

- Packs/EDL/Integrations/EDL/EDL.py
- Packs/EDL/Integrations/EDL/EDL.yml
- Packs/EDL/Integrations/EDL/EDL_test.py
- Packs/EDL/ReleaseNotes/3_3_1.md
- Packs/EDL/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-37761
fix issue where the integration stop to working due to error about log file not exist
fix:
dd condition to check if file exist before reading it
> EDL: fix error in integration

- Packs/CommonScripts/ReleaseNotes/1_15_3.md
- Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache.py
- Packs/CommonScripts/Scripts/GetIndicatorDBotScoreFromCache/GetIndicatorDBotScoreFromCache_test.py
- Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-37476)
Added a few more escaping for special chars
> get_indicators_fix_escape_special_chars

- Packs/Gem/Integrations/Gem/Gem.py
- Packs/Gem/Integrations/Gem/Gem.yml
- Packs/Gem/Integrations/Gem/README.md
- Packs/Gem/ReleaseNotes/1_0_1.md
- Packs/Gem/pack_metadata.json
Adding the option to trust any certificate.
> Gem Pack - Add "trust any certificate" option

- Packs/FireEyeHX/README.md
Added XSIAM tags to fireeye hx readme file.
> Added XSIAM tags to fireeyehx readme

- Packs/Phishing/TestPlaybooks/Phishing_v3_-_DomainSquatting+EML+MaliciousIndicators_-_Test.yml
- Packs/Phishing/TestPlaybooks/Phishing_v3_-_Get_Original_Email_+_Search_&_Delete_-_Test.yml
Ready
https://panw-global.slack.com/archives/G011E63JXPB/p1717047434929729
Added notes to the test playbooks regarding usage and testing phishing in general
> Added usage notes to the phishing test playbooks

- .circleci/analyze_non_packs_files.sh
- .circleci/config.yml
fixes: [CIAC-10009](https://jira-dc.paloaltonetworks.com/browse/CIAC-10009)
[working Nightly build](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1063650)
> remove lint from build

- Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.yml
- Packs/PhishTank/ReleaseNotes/2_0_31.md
- Packs/PhishTank/pack_metadata.json
- Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-7727
> Remove PhishTank TPB

- Packs/Base/ReleaseNotes/1_34_10.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10616
Confluence:
- https://confluence-dc.paloaltonetworks.com/pages/viewpage.action?pageId=283771114
- https://confluence-dc.paloaltonetworks.com/display/DemistoContent/What+The+Container+Runs
Use with this one-liner (Look at the source of this comment)
for i in `docker ps -q`; do docker exec -it $i sh -c 'echo "$HOSTNAME: $([ -f script_info.txt ] && cat script_info.txt)"'; done
With the Image:
for i in `docker ps -q`; do docker exec -it $i sh -c 'echo "$HOSTNAME $DOCKER_IMAGE: $([ -f script_info.txt ] && cat script_info.txt)"'; done
In Docker-in-Docker (XSOAR-NG, XSIAM) 
for i in `podman ps -q`; do echo "$i" ; podman exec -it $i sh -c 'echo "$HOSTNAME, $DOCKER_IMAGE: $([ -f script_info.txt ] && cat script_info.txt)"'; echo "" ; …
> Container Script Null ExecutedCommands

- Packs/VectraXDR/.pack-ignore
- Packs/VectraXDR/Integrations/VectraXDR/README.md
- Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.py
- Packs/VectraXDR/Integrations/VectraXDR/VectraXDR.yml
- Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_description.md
- Packs/VectraXDR/Integrations/VectraXDR/VectraXDR_test.py
- Packs/VectraXDR/Integrations/VectraXDR/test_data/invalid_page_number_404_error.json
- Packs/VectraXDR/ReleaseNotes/1_0_5.md
- Packs/VectraXDR/pack_metadata.json
- Updated the incoming mirroring logic to automatically reopen the closed XSOAR incident if the associated Vectra entity gets new detections or existing detections become active again.
> Changes related to the Vectra XDR release 1.0.5

- Packs/Incapsula/Integrations/Incapsula/Incapsula.js
- Packs/Incapsula/Integrations/Incapsula/Incapsula.yml
- Packs/Incapsula/ReleaseNotes/1_1_6.md
- Packs/Incapsula/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-38032)
Added the credentials to the header
> Fix Incapsula authorization error

- Packs/Infoblox/ParsingRules/InfobloxParsingRules/InfobloxParsingRules.xif
- Packs/Infoblox/ReleaseNotes/1_1_2.md
- Packs/Infoblox/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-38025)
> Infoblox Update

- Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC.yml
- Packs/CheckPointHEC/Integrations/CheckPointHEC/CheckPointHEC_description.md
- Packs/CheckPointHEC/Integrations/CheckPointHEC/README.md
- Packs/CheckPointHEC/ReleaseNotes/1_1_3.md
- Packs/CheckPointHEC/pack_metadata.json
Missing regions
Previously: 
This new version:
> Implement support for other regions

- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_description.md
- Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
- Packs/MicrosoftTeams/ReleaseNotes/1_4_62.md
- Packs/MicrosoftTeams/pack_metadata.json
> [MS teams] update URLs

- Packs/Forescout/ReleaseNotes/1_0_10.md
- Packs/Forescout/pack_metadata.json
Per the Partner request, change the name of the Forescout Pack.
> Change Forescout Pack Name

- Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
Packs/PcapAnalysis/Scripts/PcapExtractStreams/PcapExtractStreams.yml
> demisto/pcap-miner:1.0.0.96695 | 0-100 | PR batch #1/1

- Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml
> demisto/pycountry:1.0.0.96960 | 0-100 | PR batch #1/1

- Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
> demisto/py3-tools:1.0.0.96976 | 0-100 | PR batch #1/1

- Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
- Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml
- Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
Packs/ContentManagement/Scripts/ConfigurationSetup/ConfigurationSetup.yml
Packs/ContentManagement/Scripts/ListCreator/ListCreator.yml
Packs/CovalenceForSecurityProviders/Integrations/CovalenceForSecurityProviders/CovalenceForSecurityProviders.yml
> demisto/xsoar-tools:1.0.0.96723 | 0-100 | PR batch #1/1

- Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
Packs/AnsibleCiscoIOS/Integrations/AnsibleCiscoIOS/AnsibleCiscoIOS.yml
> demisto/ansible-runner:1.0.0.96928 | 0-100 | PR batch #1/1

- Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector.py
- Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector.yml
- Packs/CyberArkEPM/Integrations/CyberArkEPMEventCollector/CyberArkEPMEventCollector_test.py
- Packs/CyberArkEPM/ReleaseNotes/1_0_2.md
- Packs/CyberArkEPM/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10859)
Added new instance parameter **Enable admin audits events** to enable or disable admin audits.
> Cyberark epm add instance param

- Packs/MicrosoftWSUS/README.md
…ce to NPS in the readme
Removed duplicate XDRC section form readme, and removed wrong reference to NPS in the readme.
> Microsoft WSUS readme modifications

- Packs/Base/ReleaseNotes/1_34_12.md
- Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
- Packs/Base/pack_metadata.json
Revert Container Script #34445.
> Remove script_info.txt creation

- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
- Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md
- Packs/CrowdStrikeFalcon/ReleaseNotes/1_13_11.md
- Packs/CrowdStrikeFalcon/pack_metadata.json
Align the README with the update in this [PR](https://github.com/demisto/content/pull/33806).
> CS Falcon -readme update

- Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_2.md
- Packs/SuspiciousDomainHunting/Scripts/DisplaySiteCategory/DisplaySiteCategory.py
- Packs/SuspiciousDomainHunting/Scripts/DisplaySiteCategory/DisplaySiteCategory.yml
- Packs/SuspiciousDomainHunting/Scripts/MSEScoreWidget/MSEScoreWidget.py
- Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.py
- Packs/SuspiciousDomainHunting/Scripts/SSIMScoreWidget/SSIMScoreWidget.py
- Packs/SuspiciousDomainHunting/pack_metadata.json
Fixed an issue with autopep8 failing in content master.
> fixed pre-commit autopep8 malformed packs

- .gitlab/ci/.gitlab-ci.yml
Add back the artifacts expiration setting to content.
> Add setting to keep artifacts in GitLab jobs

- .github/github_workflow_scripts/autobump_release_notes/autobump_rn.py
- .github/github_workflow_scripts/check_if_partner_approved_label_exists.py
- .github/github_workflow_scripts/create_internal_pr.py
- .github/github_workflow_scripts/handle_external_pr.py
> fix contribution workflow scripts

- Packs/CortexAttackSurfaceManagement/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2967
Replace graphic links so that they link to the master.
> Replace links so they link to master

- validation_config.toml
> moved lo107 to warning

- Packs/Base/ReleaseNotes/1_34_14.md
- Packs/Base/Scripts/SanePdfReport/SanePdfReport.py
- Packs/Base/Scripts/SanePdfReport/SanePdfReport_test.py
- Packs/Base/pack_metadata.json
> [sane-pdf-reports] - assign markdown server port automatically

- Packs/Barracuda_Cloudgen_Firewall/README.md
Removed reference of checkpoint from readme file
> Barracuda Cloudgen Firewall - Readme Fix

- Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
- Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml
- Packs/AutoFocus/ReleaseNotes/2_2_3.md
- Packs/AutoFocus/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-118600)
Fixed an issue where test button failed with un informative error.
> Fixed an issue where test button failed with un informative error.

- Packs/ProofpointTAP/.pack-ignore
- Packs/ProofpointTAP/ReleaseNotes/1_2_13.md
- Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers.py
- Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers.yml
- Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers_test.py
- Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers.py
- Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers.yml
- Packs/ProofpointTAP/Scripts/ProofpointTapTopClickers/ProofpointTapTopClickers_test.py
- Packs/ProofpointTAP/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-111606, https://jira-dc.paloaltonetworks.com/browse/CRTX-111605
Fixed dashboards for xsoar 8 not rendering properly.
> Fix proofpoint widget

- Packs/Base/TestPlaybooks/playbook-Search_Endpoints_By_Hash_-_Carbon_Black_Protection_-_Test.yml
> Revert "delete tpb carbon black"
