Packs/UnifiVideoNVR/Integrations/UnifiVideo/UnifiVideo.yml, Packs/UnifiVideoNVR/ReleaseNotes/1_0_2.md, Packs/UnifiVideoNVR/pack_metadata.json
=> [Auto Update Docker] Update demisto/unifi-video

Packs/CommonDashboards/Dashboards/dashboard-My_Threat_Landscape.json, Packs/CommonDashboards/ReleaseNotes/1_7_2.md, Packs/CommonDashboards/pack_metadata.json
fixes:
https://jira-dc.paloaltonetworks.com/browse/CRTX-85319
https://jira-dc.paloaltonetworks.com/browse/CRTX-110905
Updated the indicators query in the widgets to improve performance.
=> My Threat Landscape dashboard - Update the indicators query

Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py, Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml, Packs/SentinelOne/ReleaseNotes/3_2_27.md, Packs/SentinelOne/pack_metadata.json
The command **sentinelone-get-threats** only returns the first threat when a list of threats is given as input using the argument *threat_ids*, which is an issue.
=> Fix sentinelone-get-threats cmd

.github/content_roles.json
updating the content oncall tagging by jeeves
=> updating the content oncall tagging by jeeves

Packs/ZeroFox/.secrets-ignore, Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.py, Packs/ZeroFox/Integrations/ZeroFox/ZeroFox.yml, Packs/ZeroFox/Integrations/ZeroFox/ZeroFox_test.py, Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/closed_alert.json, Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records_page1_5records.json, Packs/ZeroFox/Integrations/ZeroFox/test_data/alerts/list_10_records_page2_5records.json, Packs/ZeroFox/ReleaseNotes/1_3_3.json, Packs/ZeroFox/ReleaseNotes/1_3_3.md, Packs/ZeroFox/pack_metadata.json
Refactor: change fetch incidents log and reimplement mirroring
- change fetch incidents so it pulls all alerts instead of a single page
- modify get_remote_data and get_modified_remote_data commands so it matches this logic and avoids closing an incident multiple times
=> change fetch incidents log and reimplement mirroring (#134)

Packs/PrismaSaasSecurity/pack_metadata.json
Added the `created` field to the pack_metadata file.
=> [PrismaSaasSecurity] Add created field

Packs/MicrosoftExchangeOnPremise/TestPlaybooks/playbook-Get_Original_Email_-_EWS_v2_-_test.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10790
=> Specify EWS integration brand in `send-mail`

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365.yml, Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_14.md, Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10699, https://jira-dc.paloaltonetworks.com/browse/CIAC-10959
docker update broke authentication
=> Fix ews docker

.github/content_roles.json
Updating contributions TL and reviewers.
=> Update contribution team.

Packs/IdentityRecordedFuture/.pack-ignore
=> Added ignore

Packs/Base/ReleaseNotes/1_34_18.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json
=> Bump sane reports

.github/content_roles.json
Changed the names of the Build on-call team members for the next round.
=> Changed Build on-call team members for the next round

Packs/DeveloperTools/ReleaseNotes/1_3_16.md, Packs/DeveloperTools/Scripts/Hey/Hey.py, Packs/DeveloperTools/Scripts/Hey/Hey.yml, Packs/DeveloperTools/Scripts/Hey/Hey_test.py, Packs/DeveloperTools/pack_metadata.json
related : [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-9768) to the issue
Fixed an issue where the script failed when passing a header with space to the ***headers*** argument.
=> [Hey] Improve `header` Argument

Packs/CommonScripts/ReleaseNotes/1_15_18.md, Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.py, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-38841)
Allow indicator extraction for `ReadQRCode`.
=> [ReadQRCode] Allow indicator extraction

Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.yml
Packs/GoogleVertexAI/Integrations/GoogleVertexAI/GoogleVertexAI.yml
=> demisto/googleapi-python3:1.0.0.100240 | 0-100 | PR batch #1/1

Packs/Lacework/Integrations/Lacework/Lacework.yml
Packs/Lacework/Integrations/Lacework/Lacework.yml
=> demisto/lacework:1.0.0.100340 | 0-100 | PR batch #1/1

Packs/TeamCymru/README.md, Packs/TeamCymru/ReleaseNotes/1_0_23.md, Packs/TeamCymru/pack_metadata.json
=> TeamCymru Pack Adoption Start

Packs/Zscaler/Integrations/Zscaler/Zscaler.py, Packs/Zscaler/Integrations/Zscaler/Zscaler_test.py, Packs/Zscaler/ReleaseNotes/1_3_22.md, Packs/Zscaler/pack_metadata.json
related: https://jira-dc.paloaltonetworks.com/browse/XSUP-39029
reproduced:
=> [XSUP-39029] fix unhandled error

Packs/CommonScripts/ReleaseNotes/1_15_19.md, Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.py, Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml, Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile_test.py, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11028)
Added outputs to ExtractIndicators automation
=> ExtractIndicators add outputs

Packs/HPESwitch/ReleaseNotes/1_0_1.md, Packs/HPESwitch/pack_metadata.json
fixes: [CRTX-120419](https://jira-dc.paloaltonetworks.com/browse/CRTX-120419)
This pack contains only modeling rules and therefore should only exist in mpv2
=> HPE switch marketplace

Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py, Packs/Base/ReleaseNotes/1_34_23.md, Packs/Base/pack_metadata.json
=> Use DemistoWrapper in all integrations and scripts

Packs/CommonPlaybooks/Playbooks/playbook-Block_Account_-_Generic_v2.yml, Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml, Packs/CommonPlaybooks/Playbooks/playbook-Block_URL_-_Generic_v2.yml, Packs/CommonPlaybooks/ReleaseNotes/2_6_34.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-36896)
Fixed an issue with the data collection tasks to send emails to the corresponding roles in XSIAM (Investigator/Instance Administrator) and XSOAR (Analyst / Administrator).
=> Fix roles in common playbooks data collection task

Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10805?src=confmacro
Added sort to a list comparison task.
=> fixed test pb Microsoft Defender Advanced Threat Protection - Test prod fails nightly

Packs/ComputerVisionEngine/Integrations/ComputerVisionEngine/ComputerVisionEngine.yml
Packs/ComputerVisionEngine/Integrations/ComputerVisionEngine/ComputerVisionEngine.yml
=> demisto/yolo-coco:1.0.0.98891 | 0-100 | PR batch #1/1

Packs/DB2/Integrations/DB2/DB2.yml
Packs/DB2/Integrations/DB2/DB2.yml
=> demisto/ibm-db2:1.0.0.100241 | 0-100 | PR batch #1/1

Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml
Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml
=> demisto/feed-performance-test:1.0.99137 | 0-100 | PR batch #1/1

Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml, Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml, Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
=> demisto/bs4-py3:1.0.0.100299 | 0-100 | PR batch #1/1

Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
Packs/CommunityCommonScripts/Scripts/Jq/Jq.yml
=> demisto/jq:1.0.0.100247 | 0-100 | PR batch #1/1

Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.yml
Packs/XSOARLabUpdates/Scripts/BuildSlackBlocksFromIndex/BuildSlackBlocksFromIndex.yml
=> demisto/unzip:1.0.0.100283 | 0-100 | PR batch #1/1

Packs/CommunityCommonScripts/Scripts/PHash/PHash.yml
Packs/CommunityCommonScripts/Scripts/PHash/PHash.yml
=> demisto/python-phash:1.0.0.100267 | 0-100 | PR batch #1/1

Packs/CommonScripts/ReleaseNotes/1_15_20.md, Packs/CommonScripts/Scripts/ContentPackInstaller/ContentPackInstaller.yml, Packs/CommonScripts/pack_metadata.json, Packs/ContentManagement/ReleaseNotes/1_2_22.md, Packs/ContentManagement/Scripts/CustomPackInstaller/CustomPackInstaller.yml, Packs/ContentManagement/Scripts/JobCreator/JobCreator.yml, Packs/ContentManagement/pack_metadata.json
relates: [CIAC-9308](https://jira-dc.paloaltonetworks.com/browse/CIAC-9308)
Branch name: `AUD-demisto/bump-demisto-xsoar-tools`
Updated docker images:
>demisto/xsaor-tools
=> [Auto Update Docker] AUD-demisto/bump-demisto-xsoar-tools

Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml, Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.yml, Packs/Arduino/Integrations/Arduino/Arduino.yml, Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.yml, Packs/BitDam/Integrations/BitDam/BitDam.yml, Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext.yml, Packs/Bonusly/Integrations/Bonusly/Bonusly.yml, Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/IncOwnerToBonuslyUser.yml, Packs/CaseManagement-Generic/Scripts/AddUserToIncidentTeam/AddUserToIncidentTeam.yml, Packs/CaseManagement-Generic/Scripts/CaseMgmtAnalystTools/CaseMgmtAnalystTools.yml
Packs/Aella_StarLight/Integrations/AellaStarLight/AellaStarLight.yml
Packs/AlphaVantage/Integrations/AlphaVantage/AlphaVantage.yml
Packs/Arduino/Integrations/Arduino/Arduino.yml
Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.yml
Packs/BitDam/Integrations/BitDam/BitDam.yml
Packs/BluelivThreatContext/Integrations/BluelivThreatContext/BluelivThreatContext.yml
Packs/Bonusly/Integrations/Bonusly/Bonusly.yml
Packs/Bonusly/Scripts/IncOwnerToBonuslyUser/IncOwnerToBonuslyUser.yml
Packs/CaseManagement-Generic/Scripts/AddUserToIncidentTeam/AddUserToIncidentTeam.yml
Packs/CaseManagement-Generic/Scripts/CaseMgmtAnalystTools/CaseMgmtAnalystTools.yml
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #1/19

Packs/HealthCheck/Scripts/HealthCheckReadConf/HealthCheckReadConf.yml, Packs/HealthCheck/Scripts/HealthCheckReadTemeletryLog/HealthCheckReadTemeletryLog.yml, Packs/HealthCheck/Scripts/HealthCheckReadVC/HealthCheckReadVC.yml, Packs/HealthCheck/Scripts/HealthCheckServerLog/HealthCheckServerLog.yml, Packs/HealthCheck/Scripts/HealthCheckUnpack/HealthCheckUnpack.yml, Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.yml, Packs/IP-API/Integrations/IPAPI/IPAPI.yml, Packs/Ja3er/Integrations/Ja3er/Ja3er.yml, Packs/LINENotify/Integrations/LINENotify/LINENotify.yml, Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.yml
Packs/HealthCheck/Scripts/HealthCheckReadConf/HealthCheckReadConf.yml
Packs/HealthCheck/Scripts/HealthCheckReadTemeletryLog/HealthCheckReadTemeletryLog.yml
Packs/HealthCheck/Scripts/HealthCheckReadVC/HealthCheckReadVC.yml
Packs/HealthCheck/Scripts/HealthCheckServerLog/HealthCheckServerLog.yml
Packs/HealthCheck/Scripts/HealthCheckUnpack/HealthCheckUnpack.yml
Packs/HelloWorld/Integrations/FeedHelloWorld/FeedHelloWorld.yml
Packs/IP-API/Integrations/IPAPI/IPAPI.yml
Packs/Ja3er/Integrations/Ja3er/Ja3er.yml
Packs/LINENotify/Integrations/LINENotify/LINENotify.yml
Packs/MicroFocusSMAX/Integrations/MicroFocusSMAX/MicroFocusSMAX.yml
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #9/19

Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.yml, Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml, Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml, Packs/HealthCheck/Scripts/HealthCheckNumberOfEngines/HealthCheckNumberOfEngines.yml, Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIOIncidents/HealthCheckNumberOfLargeIOIncidents.yml, Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIncidents/HealthCheckNumberOfLargeIncidents.yml, Packs/HealthCheck/Scripts/HealthCheckNumberOfPartitions/HealthCheckNumberOfPartitions.yml, Packs/HealthCheck/Scripts/HealthCheckOutdatedPacks/HealthCheckOutdatedPacks.yml, Packs/HealthCheck/Scripts/HealthCheckPacksInstalled/HealthCheckPacksInstalled.yml, Packs/HealthCheck/Scripts/HealthCheckPanicLog/HealthCheckPanicLog.yml
Packs/HealthCheck/Scripts/HealthCheckFileSystem/HealthCheckFileSystem.yml
Packs/HealthCheck/Scripts/HealthCheckGetLargestInputsAndOutputsInIncidents/HealthCheckGetLargestInputsAndOutputsInIncidents.yml
Packs/HealthCheck/Scripts/HealthCheckLicenseData/HealthCheckLicenseData.yml
Packs/HealthCheck/Scripts/HealthCheckNumberOfEngines/HealthCheckNumberOfEngines.yml
Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIncidents/HealthCheckNumberOfLargeIncidents.yml
Packs/HealthCheck/Scripts/HealthCheckNumberOfLargeIOIncidents/HealthCheckNumberOfLargeIOIncidents.yml
Packs/HealthCheck/Scripts/HealthCheckNumberOfPartitions/HealthCheckNumberOfPartitions.yml
Packs/HealthCheck/Scripts/HealthCheckOutdatedPacks/HealthCheckOutdatedPacks.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #8/19

Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated.yml, Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.yml, Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.yml, Packs/FullHunt/Integrations/FullHunt/FullHunt.yml, Packs/GigamonThreatINSIGHT/Integrations/GigamonThreatINSIGHT/GigamonThreatINSIGHT.yml, Packs/GoogleDorking/Integrations/GoogleDorking/GoogleDorking.yml, Packs/GoogleDorking/Scripts/ExtractUsernames/ExtractUsernames.yml, Packs/Graylog/Integrations/Graylog/Graylog.yml, Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml, Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.yml
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated.yml
Packs/FeedTalos/Integrations/FeedTalos/FeedTalos.yml
Packs/FortiAuthenticator/Integrations/FortiAuthenticator/FortiAuthenticator.yml
Packs/FullHunt/Integrations/FullHunt/FullHunt.yml
Packs/GigamonThreatINSIGHT/Integrations/GigamonThreatINSIGHT/GigamonThreatINSIGHT.yml
Packs/GoogleDorking/Integrations/GoogleDorking/GoogleDorking.yml
Packs/GoogleDorking/Scripts/ExtractUsernames/ExtractUsernames.yml
Packs/Graylog/Integrations/Graylog/Graylog.yml
Packs/HealthCheck/Scripts/HealthCheckDockerLog/HealthCheckDockerLog.yml
Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.yml
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #7/19

Packs/MS-ISAC/Integrations/MSISAC/MSISAC.yml, Packs/MitreCaldera/Scripts/CalderaReadOnlyFields/CalderaReadOnlyFields.yml, Packs/MitreCaldera/Scripts/CalderaStartOperation/CalderaStartOperation.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsA/EntryWidgetNCSCResultsA.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsB/EntryWidgetNCSCResultsB.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsC/EntryWidgetNCSCResultsC.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsD/EntryWidgetNCSCResultsD.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCCalculateQuestionsScore/NCSCCalculateQuestionsScore.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCFieldProtection/NCSCFieldProtection.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCQuestionPopulate/NCSCQuestionPopulate.yml
Packs/MitreCaldera/Scripts/CalderaReadOnlyFields/CalderaReadOnlyFields.yml
Packs/MitreCaldera/Scripts/CalderaStartOperation/CalderaStartOperation.yml
Packs/MS-ISAC/Integrations/MSISAC/MSISAC.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsA/EntryWidgetNCSCResultsA.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsB/EntryWidgetNCSCResultsB.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsC/EntryWidgetNCSCResultsC.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/EntryWidgetNCSCResultsD/EntryWidgetNCSCResultsD.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCCalculateQuestionsScore/NCSCCalculateQuestionsScore.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #11/19

Packs/XSOARContentUpdateNotifications/Scripts/FormatContentData/FormatContentData.yml, Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.yml, Packs/XsoarWebserver/Scripts/EmailSLABreach/EmailSLABreach.yml, Packs/XsoarWebserver/Scripts/XsoarWsParseContext/XsoarWsParseContext.yml, Packs/XsoarWebserver/Scripts/XsoarWsPollStatus/XsoarWsPollStatus.yml
Packs/XSOARContentUpdateNotifications/Scripts/FormatContentData/FormatContentData.yml
Packs/XSOARContentUpdateNotifications/Scripts/GetLatestReleaseNotes/GetLatestReleaseNotes.yml
Packs/XsoarWebserver/Scripts/EmailSLABreach/EmailSLABreach.yml
Packs/XsoarWebserver/Scripts/XsoarWsParseContext/XsoarWsParseContext.yml
Packs/XsoarWebserver/Scripts/XsoarWsPollStatus/XsoarWsPollStatus.yml
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #19/19

Packs/CommunityCommonScripts/Scripts/CreateArrayWithDuplicates/CreateArrayWithDuplicates.yml, Packs/CommunityCommonScripts/Scripts/CreateFileFromPathObject/CreateFileFromPathObject.yml, Packs/CommunityCommonScripts/Scripts/DateTimeToADTime/DateTimeToADTime.yml, Packs/CommunityCommonScripts/Scripts/DeleteExpiredIndicatorWithExlusion/DeleteExpiredIndicatorWithExlusion.yml, Packs/CommunityCommonScripts/Scripts/DisplayIndicatorReputationContent/DisplayIndicatorReputationContent.yml, Packs/CommunityCommonScripts/Scripts/DisplayTaggedWarroomEntries/DisplayTaggedWarroomEntries.yml, Packs/CommunityCommonScripts/Scripts/GetFields/GetFields.yml, Packs/CommunityCommonScripts/Scripts/GetFilePathPreProcessing/GetFilePathPreProcessing.yml, Packs/CommunityCommonScripts/Scripts/IPCalcCheckSubnetCollision/IPCalcCheckSubnetCollision.yml, Packs/CommunityCommonScripts/Scripts/InvertEveryTwoItems/InvertEveryTwoItems.yml
Packs/CommunityCommonScripts/Scripts/CreateArrayWithDuplicates/CreateArrayWithDuplicates.yml
Packs/CommunityCommonScripts/Scripts/CreateFileFromPathObject/CreateFileFromPathObject.yml
Packs/CommunityCommonScripts/Scripts/DateTimeToADTime/DateTimeToADTime.yml
Packs/CommunityCommonScripts/Scripts/DeleteExpiredIndicatorWithExlusion/DeleteExpiredIndicatorWithExlusion.yml
Packs/CommunityCommonScripts/Scripts/DisplayIndicatorReputationContent/DisplayIndicatorReputationContent.yml
Packs/CommunityCommonScripts/Scripts/DisplayTaggedWarroomEntries/DisplayTaggedWarroomEntries.yml
Packs/CommunityCommonScripts/Scripts/GetFields/GetFields.yml
Packs/CommunityCommonScripts/Scripts/GetFilePathPreProcessing/GetFilePathPreProcessing.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #3/19

Packs/CloudShare/Integrations/CloudShare/CloudShare.yml
Packs/CloudShare/Integrations/CloudShare/CloudShare.yml
=> demisto/cloudshare:1.0.0.73056 | 0-100 | PR batch #1/1

Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetails/NCSCReportDetails.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsA/NCSCReportDetailsA.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsB/NCSCReportDetailsB.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsC/NCSCReportDetailsC.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsD/NCSCReportDetailsD.yml, Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportOverview/NCSCReportOverview.yml, Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor.yml, Packs/Nexthink/Integrations/Nexthink/Nexthink.yml, Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.yml, Packs/OracleCloudInfrastructureFeed/Integrations/OracleCloudInfrastructureFeed/OracleCloudInfrastructureFeed.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetails/NCSCReportDetails.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsA/NCSCReportDetailsA.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsB/NCSCReportDetailsB.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsC/NCSCReportDetailsC.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportDetailsD/NCSCReportDetailsD.yml
Packs/NCSCCyberAsssessmentFramework/Scripts/NCSCReportOverview/NCSCReportOverview.yml
Packs/Nexthink/Integrations/Nexthink/Nexthink.yml
Packs/NTT_Cyber_Threat_Sensor/Integrations/NTT_Cyber_Threat_Sensor/NTT_Cyber_Threat_Sensor.yml
Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #12/19

Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetPortBasedRules/EntryWidgetPortBasedRules.yml, Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedApplications/EntryWidgetUnusedApplications.yml, Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedRules/EntryWidgetUnusedRules.yml, Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsScript/RiskIQPassiveTotalComponentsScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsWidgetScript/RiskIQPassiveTotalComponentsWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairChildrenScript/RiskIQPassiveTotalHostPairChildrenScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairParentsScript/RiskIQPassiveTotalHostPairParentsScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsChildrenWidgetScript/RiskIQPassiveTotalHostPairsChildrenWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairsParentsWidgetScript/RiskIQPassiveTotalHostPairsParentsWidgetScript.yml
Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetPortBasedRules/EntryWidgetPortBasedRules.yml
Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedApplications/EntryWidgetUnusedApplications.yml
Packs/PANOSPolicyOptimizer/Scripts/EntryWidgetUnusedRules/EntryWidgetUnusedRules.yml
Packs/PANOStoCDLMonitoring/Scripts/PANOStoCortexDataLakeMonitoring/PANOStoCortexDataLakeMonitoring.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsScript/RiskIQPassiveTotalComponentsScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalComponentsWidgetScript/RiskIQPassiveTotalComponentsWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalHostPairChildrenScript/RiskIQPassiveTotalHostPairChildrenScript.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #13/19

Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSScript/RiskIQPassiveTotalPDNSScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSWidgetScript/RiskIQPassiveTotalPDNSWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLScript/RiskIQPassiveTotalSSLScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLWidgetScript/RiskIQPassiveTotalSSLWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersScript/RiskIQPassiveTotalTrackersScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersWidgetScript/RiskIQPassiveTotalTrackersWidgetScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalWhoisScript/RiskIQPassiveTotalWhoisScript.yml, Packs/PassiveTotal/Scripts/RiskIQPassiveTotalWhoisWidgetScript/RiskIQPassiveTotalWhoisWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSScript/RiskIQPassiveTotalPDNSScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalPDNSWidgetScript/RiskIQPassiveTotalPDNSWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript/RiskIQPassiveTotalSSLForIssuerEmailWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript/RiskIQPassiveTotalSSLForSubjectEmailWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLScript/RiskIQPassiveTotalSSLScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalSSLWidgetScript/RiskIQPassiveTotalSSLWidgetScript.yml
Packs/PassiveTotal/Scripts/RiskIQPassiveTotalTrackersScript/RiskIQPassiveTotalTrackersScript.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #14/19

Packs/UltraMSG/Integrations/UltraMSG/UltraMSG.yml, Packs/UnisysStealth/Integrations/UnisysStealth/UnisysStealth.yml, Packs/UpdateEntriesBySearch/Scripts/MarkAsEvidenceBySearch/MarkAsEvidenceBySearch.yml, Packs/UpdateEntriesBySearch/Scripts/MarkAsNoteBySearch/MarkAsNoteBySearch.yml, Packs/UpdateEntriesBySearch/Scripts/SetTagsBySearch/SetTagsBySearch.yml, Packs/Use_Case_Builder/Scripts/CreateUseCaseStepsList/CreateUseCaseStepsList.yml, Packs/Use_Case_Builder/Scripts/CreateXSOARIncidentFlowList/CreateXSOARIncidentFlowList.yml, Packs/Use_Case_Builder/Scripts/DeleteAndExcludeIndicators/DeleteAndExcludeIndicators.yml, Packs/Use_Case_Builder/Scripts/GettingStartedWithXSOAR/GettingStartedWithXSOAR.yml, Packs/Use_Case_Builder/Scripts/PlaybookAutoGeneratorDynamicSectionMessage/PlaybookAutoGeneratorDynamicSectionMessage.yml
Packs/UltraMSG/Integrations/UltraMSG/UltraMSG.yml
Packs/UnisysStealth/Integrations/UnisysStealth/UnisysStealth.yml
Packs/UpdateEntriesBySearch/Scripts/MarkAsEvidenceBySearch/MarkAsEvidenceBySearch.yml
Packs/UpdateEntriesBySearch/Scripts/MarkAsNoteBySearch/MarkAsNoteBySearch.yml
Packs/UpdateEntriesBySearch/Scripts/SetTagsBySearch/SetTagsBySearch.yml
Packs/Use_Case_Builder/Scripts/CreateUseCaseStepsList/CreateUseCaseStepsList.yml
Packs/Use_Case_Builder/Scripts/CreateXSOARIncidentFlowList/CreateXSOARIncidentFlowList.yml
Packs/Use_Case_Builder/Scripts/DeleteAndExcludeIndicators/DeleteAndExcludeIndicators.yml
Packs/Use_Case_Builder/Scripts/GettingStartedWithXSOAR/GettingStartedWithXSOAR.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #17/19

Packs/PostmarkSpamcheck/Integrations/PostmarkSpamcheck/PostmarkSpamcheck.yml, Packs/Pulsedive/Integrations/Pulsedive/Pulsedive.yml, Packs/QRCodeReader/Integrations/QRCodeReaderGoqrMe/QRCodeReaderGoqrMe.yml, Packs/Rapid7InsightVMCloud/Integrations/Rapid7InsightVMCloud/Rapid7InsightVMCloud.yml, Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml, Packs/SalesforceV2/Integrations/SalesforceV2/SalesforceV2.yml, Packs/SalesforceV2/Scripts/SalesforceCaseStatus/SalesforceCaseStatus.yml, Packs/SalesforceV2/Scripts/SalesforceCaseStatusPicklist/SalesforceCaseStatusPicklist.yml, Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails.yml, Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/AssignToNextShift.yml
Packs/PostmarkSpamcheck/Integrations/PostmarkSpamcheck/PostmarkSpamcheck.yml
Packs/Pulsedive/Integrations/Pulsedive/Pulsedive.yml
Packs/QRCodeReader/Integrations/QRCodeReaderGoqrMe/QRCodeReaderGoqrMe.yml
Packs/Rapid7InsightVMCloud/Integrations/Rapid7InsightVMCloud/Rapid7InsightVMCloud.yml
Packs/SalesforceIndicators/Integrations/SalesforceIndicators/SalesforceIndicators.yml
Packs/SalesforceV2/Integrations/SalesforceV2/SalesforceV2.yml
Packs/SalesforceV2/Scripts/SalesforceCaseStatus/SalesforceCaseStatus.yml
Packs/SalesforceV2/Scripts/SalesforceCaseStatusPicklist/SalesforceCaseStatusPicklist.yml
Packs/SecurityTrails/Integrations/SecurityTrails/SecurityTrails.yml
Packs/ShiftManagement-AssignToNextShift/Scripts/AssignToNextShift/AssignTo …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #15/19

Packs/SSLCertificates/Scripts/SSLVerifierV2ParseOutput/SSLVerifierV2ParseOutput.yml, Packs/SimpleDebugger/Scripts/SimpleDebugger/SimpleDebugger.yml, Packs/SnortIPBlocklist/Integrations/FeedSnortIPBlocklist/FeedSnortIPBlocklist.yml, Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.yml, Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml, Packs/StarterPack/Scripts/BaseScript/BaseScript.yml, Packs/TeamManagement/Scripts/EnumerateRoles/EnumerateRoles.yml, Packs/ThousandEyes/Integrations/ThousandEyes/ThousandEyes.yml, Packs/Trello/Integrations/Trello/Trello.yml, Packs/TwitterIOCHunter-FullDailyFeed/Integrations/TwitterIOCHunterFullDailyFeed/TwitterIOCHunterFullDailyFeed.yml
Packs/SimpleDebugger/Scripts/SimpleDebugger/SimpleDebugger.yml
Packs/SnortIPBlocklist/Integrations/FeedSnortIPBlocklist/FeedSnortIPBlocklist.yml
Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.yml
Packs/SSLCertificates/Scripts/SSLVerifierV2ParseOutput/SSLVerifierV2ParseOutput.yml
Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
Packs/TeamManagement/Scripts/EnumerateRoles/EnumerateRoles.yml
Packs/ThousandEyes/Integrations/ThousandEyes/ThousandEyes.yml
Packs/Trello/Integrations/Trello/Trello.yml
Packs/TwitterIOCHunter-FullDailyFeed/Integrations/TwitterIOCHunterFullDailyFeed/TwitterIOCHunterFullDailyFeed.yml
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #16/19

Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/CaseMgmtDisplayLabels.yml, Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.py, Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.yml, Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesDisplay/CaseMgmtIncidentTypesDisplay.yml, Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/CaseMgmtResponseProcess.yml, Packs/CaseManagement-Generic/Scripts/CompleteTaskOnTimerBreach/CompleteTaskOnTimerBreach.yml, Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml, Packs/CentrifyVault/Integrations/CentrifyVault/CentrifyVault.py, Packs/CentrifyVault/Integrations/CentrifyVault/CentrifyVault.yml, Packs/CommunityCommonScripts/Scripts/BatchData/BatchData.py, Packs/CommunityCommonScripts/Scripts/BatchData/BatchData.yml, Packs/CommunityCommonScripts/Scripts/CompareList/CompareList.yml, Packs/CommunityCommonScripts/Scripts/ConvertUTCEpochTimeToTimeStamp/ConvertUTCEpochTimeToTimeStamp.yml
Packs/CaseManagement-Generic/Scripts/CaseMgmtDisplayLabels/CaseMgmtDisplayLabels.yml
Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesByRole/CaseMgmtIncidentTypesByRole.yml
Packs/CaseManagement-Generic/Scripts/CaseMgmtIncidentTypesDisplay/CaseMgmtIncidentTypesDisplay.yml
Packs/CaseManagement-Generic/Scripts/CaseMgmtResponseProcess/CaseMgmtResponseProcess.yml
Packs/CaseManagement-Generic/Scripts/CompleteTaskOnTimerBreach/CompleteTaskOnTimerBreach.yml
Packs/CaseManagement-Generic/Scripts/TimersOnOwnerChange/TimersOnOwnerChange.yml
Packs/CentrifyVault/Integrations/CentrifyVault/CentrifyVault.yml
Packs/CommunityCommonScripts/Scripts/BatchData/BatchData.yml
Packs/CommunityCommonScripts/Scripts/CompareList/CompareList.yml …
=> demisto/python3:3.10.14.100715 | 0-100 | PR batch #2/19

Packs/CommunityCommonScripts/CONTRIBUTORS.json, Packs/CommunityCommonScripts/ReleaseNotes/1_2_2.md, Packs/CommunityCommonScripts/Scripts/Defang/Defang.py, Packs/CommunityCommonScripts/Scripts/Defang/Defang.yml, Packs/CommunityCommonScripts/Scripts/Defang/README.md, Packs/CommunityCommonScripts/pack_metadata.json
Defangs IP, Mail and URL address to prevent them from being recognized.
=> Defang Added

Packs/Imperva_WAF/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-3450)
=> Imperva WAF README Update

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js, Packs/DemistoRESTAPI/ReleaseNotes/1_3_57.md, Packs/DemistoRESTAPI/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-37987
added a log for the case ew tried to get the tenant name but it not exist.
=> DemistoRESTAPI: added logs

Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.py, Packs/GitHub/Integrations/GitHubEventCollector/GitHubEventCollector.yml, Packs/GitHub/ReleaseNotes/2_1_2.md, Packs/GitHub/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-120855)
Updated the parameter **First fetch time interval** to be a hidden parameter, and its default value to be 1 minute.
=> CRTX-120855/ GitHub Event Collector

Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py, Packs/Base/ReleaseNotes/1_34_26.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/pack_metadata.json
=> Demisto class for most

Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2.ps1, Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2_description.md, Packs/MicrosoftExchangeOnline/ReleaseNotes/1_3_17.md, Packs/MicrosoftExchangeOnline/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38788
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38457
The app now no longer requires multi-tenant to be enabled to authenticate.
=> Fix multi-tenant auth issue in S&CV2

Packs/CloudIDS/.pack-ignore, Packs/CloudIDS/README.md, Packs/OpenPhish/.pack-ignore
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-10611
part of https://github.com/demisto/content/pull/34807-  verifying ***Packs/CloudIDS/README.md*** images link updates, not failing build with ignore rm108
=> checking ignore rm108

Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10805)
=> added sort to the verify endpoint id

Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11073)
Increased memory threshold
=> Increased Account Enrichment - Generic v2.1 - Test memory_threshold

Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py, Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.yml, Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3_test.py, Packs/Anomali_ThreatStream/ReleaseNotes/2_2_21.md, Packs/Anomali_ThreatStream/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-38758
- Updated the Authorization flow due to changes on Anomali API side.
=> Anomali bug

Packs/AWS_WAF/Integrations/AWSWAF/AWSWAF.yml, Packs/AWS_WAF/ReleaseNotes/1_0_7.md, Packs/AWS_WAF/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39175
=> Aws waf regions

Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml, Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml, Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml, Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml
Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml
Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml
Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml
=> demisto/powershell:7.4.0.80528 | 0-100 | PR batch #1/1

Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml, Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.yml, Packs/DevSecOps/Integrations/MinIO/MinIO.yml, Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml, Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml, Packs/FeedZeroDayLiveTIFusion/Integrations/FeedZeroDayLiveTIFUSION/FeedZeroDayLiveTIFUSION.yml, Packs/GZip/Scripts/GZipFile/GZipFile.yml, Packs/GZip/Scripts/UnzipGZFile/UnzipGZFile.yml, Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml, Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
Packs/AccentureCTI_Feed/Integrations/ACTIIndicatorFeed/ACTIIndicatorFeed.yml
Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect.yml
Packs/DevSecOps/Integrations/MinIO/MinIO.yml
Packs/FeedIntel471/Integrations/Intel471MalwareIndicator/Intel471MalwareIndicator.yml
Packs/FeedIntel471/Integrations/Intel471WatcherAlerts/Intel471WatcherAlerts.yml
Packs/FeedZeroDayLiveTIFusion/Integrations/FeedZeroDayLiveTIFUSION/FeedZeroDayLiveTIFUSION.yml
Packs/GZip/Scripts/GZipFile/GZipFile.yml
Packs/GZip/Scripts/UnzipGZFile/UnzipGZFile.yml
Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
Packs/SEKOIAIntelligenceCenter/Integrations/SEKOIAIntelligenceCenter/SEKOIAIntelligenceCenter.yml
=> demisto/py3-tools:1.0.0.102774 | 0-100 | PR batch #1/2

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
=> demisto/chromium:126.0.6478.102778 | 0-100 | PR batch #1/1

Packs/CyberX-CentralManager/Integrations/CyberXCentralManager/CyberXCentralManager.yml
Packs/CyberX-CentralManager/Integrations/CyberXCentralManager/CyberXCentralManager.yml
=> demisto/python3-deb:3.11.9.102626 | 0-100 | PR batch #1/1

.github/content_roles.json
Updating the members of the contribution team.
=> update contribution team members.

Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml, Packs/PopularCybersecurityNews/ReleaseNotes/1_0_7.md, Packs/PopularCybersecurityNews/pack_metadata.json
relates: [CIAC-9308](https://jira-dc.paloaltonetworks.com/browse/CIAC-9308)
Staging branch name: `AUD-demisto/auto_update_docker_staging_branch_11`
Updated docker images:
>demisto/bs4
=> [Auto Update Docker] AUD-demisto/auto_update_docker_staging_branch_11

Tests/conf.json
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11079?src=confmacro)
=> increased the memo for EWS Public Folders Test

Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml, Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector_description.md, Packs/Armis/ReleaseNotes/1_1_16.json, Packs/Armis/ReleaseNotes/1_1_16.md, Packs/Armis/pack_metadata.json
fixes:[XSUP-36261](https://jira-dc.paloaltonetworks.com/browse/XSUP-36261)
=> Raise armis event collector default limit

Packs/Cloaken/Integrations/Cloaken/Cloaken.yml, Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml, Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml, Packs/ForcepointSecurityManagementCenter/Integrations/ForcepointSecurityManagementCenter/ForcepointSecurityManagementCenter.yml, Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml, Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml, Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml, Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
Packs/Cloaken/Integrations/Cloaken/Cloaken.yml
Packs/DuoAdminApi/Integrations/DuoAdminApi/DuoAdminApi.yml
Packs/DuoAdminApi/Integrations/DuoEventCollector/DuoEventCollector.yml
Packs/ForcepointSecurityManagementCenter/Integrations/ForcepointSecurityManagementCenter/ForcepointSecurityManagementCenter.yml
Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
Packs/JoeSecurity/Integrations/JoeSecurityV2/JoeSecurityV2.yml
Packs/Kafka/Integrations/KafkaV3/KafkaV3.yml
Packs/TeamCymru/Integrations/TeamCymru/TeamCymru.yml
=> demisto/vendors-sdk:1.0.0.103334 | 0-100 | PR batch #1/1

Packs/CloudIDS/.pack-ignore, Packs/CloudIDS/README.md
=> Revert "checking ignore rm108"

Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml
Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml
=> demisto/googleapi-python3:1.0.0.103410 | 0-100 | PR batch #2/2

Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml, Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml, Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml, Packs/MongoDB/Integrations/MongoDB/MongoDB.yml, Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.yml, Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.yml, Packs/Okta/Scripts/IAMInitOktaUser/IAMInitOktaUser.yml, Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml, Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.yml, Packs/Vertica/Integrations/Vertica/Vertica.yml
Packs/Jira/Integrations/JiraEventCollector/JiraEventCollector.yml
Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
Packs/Mimecast/Integrations/MimecastEventCollector/MimecastEventCollector.yml
Packs/MongoDB/Integrations/MongoDB/MongoDB.yml
Packs/MongoDB/Integrations/MongoDBKeyValueStore/MongoDBKeyValueStore.yml
Packs/MongoDB/Integrations/MongoDBLog/MongoDBLog.yml
Packs/Okta/Scripts/IAMInitOktaUser/IAMInitOktaUser.yml
Packs/OpenLDAP/Integrations/OpenLDAP/OpenLDAP.yml
Packs/ThalesCipherTrustManager/Integrations/ThalesCipherTrustManager/ThalesCipherTrustManager.yml
Packs/Vertica/Integrations/Vertica/Vertica.yml
=> demisto/py3-tools:1.0.0.103307 | 0-100 | PR batch #4/4

Packs/DeveloperTools/Integrations/CreateMockFeed/CreateMockFeed.yml, Packs/DeveloperTools/ReleaseNotes/1_3_19.md, Packs/DeveloperTools/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/CIAC-10561
Create-Mock-Feed-Relationships - Updated the Docker image to: *demisto/feed-performance-test:1.0.103518*.
=> update feed-performance-test docker

Packs/CommonScripts/ReleaseNotes/1_15_30.md, Packs/CommonScripts/ReleaseNotes/1_15_31.md, Packs/CommonScripts/Scripts/LookupCSV/LookupCSV.yml, Packs/CommonScripts/Scripts/LookupCSV/README.md, Packs/CommonScripts/pack_metadata.json
fixes: [CIAC-11129](https://jira-dc.paloaltonetworks.com/browse/CIAC-11129)
Added the output: LookupCSV.Result to the yml
=> Lookup CSV output fix

Packs/Base/ReleaseNotes/1_34_29.md, Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml, Packs/Base/Scripts/DBotFindSimilarIncidentsByIndicators/DBotFindSimilarIncidentsByIndicators.yml, Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml, Packs/Base/Scripts/DBotPreprocessTextData/DBotPreprocessTextData.yml, Packs/Base/Scripts/DBotTrainTextClassifierV2/DBotTrainTextClassifierV2.yml, Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml, Packs/Base/pack_metadata.json, Packs/ML/ReleaseNotes/1_4_12.md, Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml, Packs/ML/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10561)
Updated the demisto/ml docker to content items.
=> Update ml dockers

Packs/AzureSecurityCenter/TestPlaybooks/playbook-AzureSCTestPlaybook.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10996)
Fixed an issue where the TPB would try to get an unexisting id and fail with an exception.
=> fix_azure_sc_tpb

Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.py, Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftDefenderEventCollector/MicrosoftDefenderEventCollector.yml, Packs/MicrosoftCloudAppSecurity/ReleaseNotes/2_2_2.md, Packs/MicrosoftCloudAppSecurity/pack_metadata.json
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39317)
=> bug - MD EC added debug logs

Tests/conf.json
=> Add ThreatCrowd to skipped

Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py, Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml, Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py, Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md, Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_35.md, Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39390)
Fixed a bug in the fetch-incidents command which used to return duplicate alerts.
=> fix fetch-incidents returns duplicates bug

Packs/SplunkPy/Integrations/SplunkPy/README.md, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py, Packs/SplunkPy/ReleaseNotes/3_1_34.md, Packs/SplunkPy/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39496
=> rename splunk host display name

Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml, Packs/AnsibleAzure/ReleaseNotes/1_0_7.md, Packs/AnsibleAzure/pack_metadata.json
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11119)
=> bug - ansible dockerimage revert

Packs/CommonScripts/TestPlaybooks/playbook-Docker_Hardening_Test.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11169)
Changed the docker hardening TPB to run only on xsoar_on_prem
=> Changed the docker hardening TPB to run only on xsoar_on_prem

Packs/BitwardenPasswordManager/Integrations/BitwardenPasswordManager/BitwardenPasswordManager.yml, Packs/BitwardenPasswordManager/ReleaseNotes/1_0_1.md, Packs/BitwardenPasswordManager/pack_metadata.json
fixes: [ticket](https://jira-dc.paloaltonetworks.com/browse/CIAC-10816?filter=-1)
DoD:
- bitwarden Event Collector
- bitwarden Datamodel
- Add XSIAM to the list of SIEMS under "Reporting" in the bitwarden docs
=> downgrade fromversion

Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.py, Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR_test.py, Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_36.md, Packs/CarbonBlackEnterpriseEDR/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39390)
=> fixing an error issue in Carbon Black Enterprise EDR

.github/github_workflow_scripts/handle_external_pr.py, .github/github_workflow_scripts/utils.py, Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js, Packs/DemistoRESTAPI/ReleaseNotes/1_3_58.md, Packs/DemistoRESTAPI/pack_metadata.json
- Fixed an issue in which proxy parameter is incorrectly reference, changed to `useproxy` instead.
=> Farsight DNSDB v2.1.23

Packs/Jira/Integrations/JiraV2/README.md
=> JiraV2 README Deleted extra space in image reference

Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector_description.md, Packs/Dropbox/ReleaseNotes/1_1_2.md, Packs/Dropbox/pack_metadata.json, Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_description.md, Packs/FeedGitHub/ReleaseNotes/1_0_3.md, Packs/FeedGitHub/pack_metadata.json
=> Revert markdowns

poetry.lock, pyproject.toml
Use the Xsiam UI get_data endpoint to get which datasets exists on the machine.
Use the Xsiam UI get_data endpoint to get which datasets exists on the machine.
=> Use the Xsiam UI get_data endpoint to get which datasets exists on the machine.

Packs/CofenseTriage/Integrations/CofenseTriagev2/conftest.py, Packs/Silverfort/Integrations/Silverfort/conftest.py
=> Revert "Deleted conftest from integrations"

Packs/PhishingURL/Scripts/DBotPredictURLPhishing/dbotpredicturlphishing_test.py
Fix dbotpredicturlphishing_test.py
=> Fix dbotpredicturlphishing_test.py

Packs/Microsoft365Defender/Integrations/O365DefenderSafeLinks/O365DefenderSafeLinks.yml, Packs/Microsoft365Defender/ReleaseNotes/4_5_29.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11168)
Improved documentation.
=> O365 documentation change

Packs/FiltersAndTransformers/ReleaseNotes/1_2_75.md, Packs/FiltersAndTransformers/Scripts/ExtractEmailTransformer/ExtractEmailTransformer.yml, Packs/FiltersAndTransformers/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39699)
Fixed an issue where the script was not visible in the UI.
=> [ExtractEmailTransformer] Fixed an issue where the script was not visible in the UI

Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.py, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory_test.py, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_create_reference_list_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_create_reference_list_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_create_reference_list_invalid_lines_content_400.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_get_reference_list_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_get_reference_list_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_list_reference_list_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_list_reference_list_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_list_reference_list_valid_args.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_update_reference_list_command_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_update_reference_list_command_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_update_reference_list_command_response.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_update_reference_list_invalid_lines_content_400.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_all_valid_lines_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_all_valid_lines_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_all_valid_lines_response.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_ec.json, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_hr.md, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/test_data/gcb_verify_reference_list_command_response.json, Packs/GoogleChronicleBackstory/ReleaseNotes/4_0_2.md, Packs/GoogleChronicleBackstory/pack_metadata.json
- Added the new command: ***gcb-verify-reference-list***.
- Updated the following commands for the added **content_type** argument.
- ***gcb-create-reference-list***
- ***gcb-update-reference-list***
=> Google Chronicle Backstory - Release 4.0.2

Packs/CommonScripts/ReleaseNotes/1_15_33.md, Packs/CommonScripts/Scripts/WordTokenizeTest/WordTokenizeTest.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11202)
Deprecate WordTokenizer
=> Deprecate WordTokenizer

Packs/Okta/ParsingRules/Okta/Okta.xif, Packs/Okta/ReleaseNotes/3_2_15.md, Packs/Okta/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39252)
=> Okta SSO Dataset Parsing Update

Packs/qualys/Integrations/Qualys/Qualys.yml, Packs/qualys/ReleaseNotes/3_0_4.md, Packs/qualys/pack_metadata.json
Updated the deprecation message in the documentation regarding the redirection to **Qualys VMDR** integration.
=> Update Qualys Docs

Packs/AWS_SystemManager/ReleaseNotes/1_0_3.md, Packs/AWS_SystemManager/Scripts/AWSPackageUpgrade/AWSPackageUpgrade.py, Packs/AWS_SystemManager/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-10563
Increase OpenSSH version to 9.8p1
=> EXPANDR-10563 Update OpenSSH version to 9.8p1

Packs/Base/ReleaseNotes/1_34_30.md, Packs/Base/Scripts/ValidateContent/README.md, Packs/Base/Scripts/ValidateContent/ValidateContent.yml, Packs/Base/pack_metadata.json
=> Bump xsoar tools

Packs/AnsibleAzure/Integrations/AnsibleAzure/AnsibleAzure.yml, Packs/AnsibleAzure/ReleaseNotes/1_0_8.md, Packs/AnsibleAzure/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11270)
=> Ansible Azure - update docker image

Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice_test.py, Packs/FreshworksFreshservice/ReleaseNotes/1_0_26.md, Packs/FreshworksFreshservice/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-39950
=> [XSUP-39950] FreshService - fix custom_fields argument

Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml, Packs/CommonPlaybooks/Playbooks/playbook-Detonate_URL_-_Generic.yml, Packs/CommonPlaybooks/ReleaseNotes/2_6_36.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: [XSUP-39914](https://jira-dc.paloaltonetworks.com/browse/XSUP-39914)
Updated the 2 playbooks to use the new commands instead of the deprecated ones.
=> Detonate file generic fix

Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml, Packs/ImageOCR/ReleaseNotes/1_1_33.md, Packs/ImageOCR/pack_metadata.json
Updated the Docker image to: *demisto/tesseract:1.0.0.105808*.
=> Image OCR - update docker

Packs/Flashpoint/Integrations/Ignite/README.md
=> Fix ignite README

Packs/GoogleThreatIntelligence/README.md, Packs/VirusTotal/Integrations/VirusTotalV3/README.md, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/README.md, Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.py, Packs/VirusTotal/Integrations/VirusTotal_V3_Premium/VirusTotal_V3_Premium.yml, Packs/VirusTotal/Playbooks/Detonate_Private_File_-_VirusTotal_V3_README.md, Packs/VirusTotal/README.md, Packs/VirusTotal/ReleaseNotes/2_6_23.md, Packs/VirusTotal/TestPlaybooks/playbook-VirusTotal_preferred_vendors_test.yml, Packs/VirusTotal/TestPlaybooks/playbook-virusTotal-test.yml, Packs/VirusTotal/pack_metadata.json, Packs/ctf01/Integrations/OHMYVTCTF/OHMYVTCTF.py
=> [VirusTotal] Update VT docs

Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub.yml, Packs/FeedGitHub/Integrations/FeedGitHub/FeedGitHub_description.md, Packs/FeedGitHub/ReleaseNotes/1_0_4.md, Packs/FeedGitHub/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-10611
FeedGithub description - change to relative file
=> FeedGithub desc- change to relative file

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py, Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_8.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [XSUP-40033](https://jira-dc.paloaltonetworks.com/browse/XSUP-40033)
Added the **tag** argument to **cs-falcon-resolve-detection** command.
=> Add tags to cs resolve detection

Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11392)
=> excluded test-pb

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml, Packs/CofenseTriage/ReleaseNotes/2_1_27.md, Packs/CofenseTriage/pack_metadata.json, Packs/ExpanseV2/ReleaseNotes/1_10_56.md, Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml, Packs/ExpanseV2/pack_metadata.json, Packs/rasterize/Integrations/rasterize/rasterize.yml, Packs/rasterize/ReleaseNotes/2_0_20.md, Packs/rasterize/pack_metadata.json
Updated the Docker image to: *demisto/chromium:127.0.6533.105883*.
=> Updated chromium docker

Packs/Palo_Alto_Networks_WildFire/Playbooks/Detonate_URL_-_WildFire_v2.2_README.md
=> fix for image path in read me file

Packs/CommonScripts/ReleaseNotes/1_15_40.md, Packs/CommonScripts/Scripts/FailedInstances/FailedInstances.js, Packs/CommonScripts/pack_metadata.json, Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40078)
Fix FailedInstances automation to test SNOW CMDB with oauth enabled.
=> Fix FailedInstances automation to test SNOW CMDB with oauth enabled

poetry.lock, pyproject.toml
=> fix pre-commit in GitHub

Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11410)
Exclude XDR TPBs from the nightly run to check if they cause OOMem issues on the NG machines.
=> exclude test-pb

.github/workflows/update-demisto-sdk-version.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10739
related: https://gitlab.xdr.pan.local/xdr/cortex-content/infra/-/merge_requests/390
Removed the `release_changes` from github command, the body is updated in a different place.
=> Stop Interpreting Special Characters

.github/CODEOWNERS
=> Update CODEOWNERS with ML scripts

.github/content_roles.json, .github/github_workflow_scripts/handle_external_pr.py
=> Updated the security reviewers and the logic to select them

Packs/Impartner/Integrations/Impartner/Impartner.yml, Packs/Impartner/ReleaseNotes/1_0_2.md, Packs/Impartner/pack_metadata.json
=> Impartner from version

.github/content_roles.json
=> Change contribution lead.

Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11433)
=> exclude TPB

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml, Packs/CofenseTriage/ReleaseNotes/2_1_29.md, Packs/CofenseTriage/pack_metadata.json, Packs/ExpanseV2/ReleaseNotes/1_10_59.md, Packs/ExpanseV2/Scripts/ExpanseGenerateIssueMapWidgetScript/ExpanseGenerateIssueMapWidgetScript.yml, Packs/ExpanseV2/pack_metadata.json
Updated the Docker image to: *demisto/chromium:127.0.6533.106841*.
=> Update chromium docker

Packs/ContentTesting/ReleaseNotes/2_1_3.md, Packs/ContentTesting/Scripts/UnitTest/UnitTest.yml, Packs/ContentTesting/Scripts/UpgradeCheck/UpgradeCheck.yml, Packs/ContentTesting/pack_metadata.json
related:https://jira-dc.paloaltonetworks.com/browse/CIAC-9784
Upgrade Docker images to bump `ContentTesting` Pack in order to resolve https://github.com/demisto/content/pull/35669.
=> Bump ContentTesting Docker Images

Packs/CommonScripts/ReleaseNotes/1_15_44.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
relevant prs:
https://github.com/demisto/dockerfiles/pull/30558
https://github.com/demisto/parse-emails/pull/89
related:
https://jira-dc.paloaltonetworks.com/browse/XSUP-39649
=> ParseEmailFilesV2: Update docker image 

Packs/CommonScripts/TestPlaybooks/playbook-Test_Delete_Context.yml
added missing fromversion which broke the build.
=> added versions

Tests/docker_native_image_config.json
Ignore `Json2HtmlTable` in native image due to changes made in https://github.com/demisto/dockerfiles/pull/29877.
=> [native-image] Ignore Json2HtmlTable script

Packs/Jira/Integrations/JiraV3/JiraV3.py, Packs/Jira/ReleaseNotes/3_2_3.md, Packs/Jira/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39666)
Fixed an issue where the multi-select custom field is selected with a single value, the mirroring out process fails.
=> JiraV3 Mirror Out

Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py, Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml, Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2_test.py, Packs/CybleEventsV2/Integrations/CybleEventsV2/README.md, Packs/CybleEventsV2/Integrations/CybleEventsV2/test_data/dummy_fetch_iocs.json, Packs/CybleEventsV2/ReleaseNotes/1_0_4.md, Packs/CybleEventsV2/pack_metadata.json
- We have made changes in our IOCs response, this release of Cortex app implements these changes.
- A minor bug fix in Alerts fetching code.
=> Cyble enhancements

Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py, Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.yml, Packs/BmcITSM/Integrations/BmcITSM/BmcITSM_test.py, Packs/BmcITSM/Integrations/BmcITSM/README.md
Fixed a bug in the below commands:
***bmc-itsm-task-create***
***bmc-itsm-task-update***
The argument customer_company was missing in the API request.
=> feat: Fixing but - not has customer company

Packs/HealthCheck/Scripts/HealthCheckFields/HealthCheckFields.py
n/a
Fix instructions and a typo. 
For reviewer, note that I fixed the instuction according to my XSOAR 6.11 deployment ; you may want to check if the steps are the same on XSOAR 8. 
As the string was written 2 years ago I'm not sure it would be describing xsoar8 UX, hence this PR. But kindly double check as I don't have access to an XSOAR8.
=> Fix instructions and a typo

.pre-commit-config_template.yaml
=> Add AUD mode to ruff

Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/README.md
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2347
https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-2346
Add a filter example in the Parameters section.
=> Add Filter example in Readme

Packs/Office365/ParsingRules/Office365/Office365.xif, Packs/Office365/README.md, Packs/Office365/ReleaseNotes/1_0_4.md, Packs/Office365/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-125765)
=> XSUP-39406-o365-parsing-update

Packs/CyberArkEPV/ParsingRules/CyberArkEPV/CyberArkEPV.xif, Packs/CyberArkEPV/ReleaseNotes/1_0_3.md, Packs/CyberArkEPV/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-6777)
=> CyberArkEPV Parsing Update

Packs/Exterro/Integrations/Exterro/Exterro.yml, Packs/Exterro/ReleaseNotes/1_0_12.md, Packs/Exterro/pack_metadata.json
Updated the Docker image to: *demisto/accessdata:1.1.0.108229*.
=> Exterro FTK - update docker

Packs/Druva/ModelingRules/Druva/Druva_schema.json, Packs/Druva/ReleaseNotes/1_2_1.md, Packs/Druva/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-6376
add missing field inSyncDataSourceName to the Schema.
=> Druva Collector - add missing field inSyncDataSourceName to the Schema

.github/content_roles.json
Added:
* @rshunim 
* @adi88d 
Removed:
* @barryyosi-panw 
* @samuelFain
=> Update contributors list (Q3-2 2024)

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml, Packs/GenericSQL/ReleaseNotes/1_3_2.md, Packs/GenericSQL/pack_metadata.json
Updated the Docker image to: *demisto/genericsql:1.1.0.108424*.
=> Generic SQL - update docker

Packs/FeedRecordedFuture/IndicatorFields/indicatorfield-recordedfutureriskscore.json, Packs/FeedRecordedFuture/IndicatorFields/indicatorfield-recordedfutureriskscore_6_10.json, Packs/FeedRecordedFuture/IndicatorFields/indicatorfield-recordedfutureriskscore_6_5_0.json, Packs/FeedRecordedFuture/ReleaseNotes/1_1_5.md, Packs/FeedRecordedFuture/pack_metadata.json
fixes: [XSUP-40598](https://jira-dc.paloaltonetworks.com/browse/XSUP-40598)
Changed the indicator field type to be *number* instead of *shorttext* to help the user compare values.
=> Recoreded future risk score fix

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11520
Add test playbooks to splunk py yml that are missing from "tests:" section.
=> link splunkpy test playbooks to yml

.github/workflows/run-legacy-validate-for-contribution.yml
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11503
[test run](https://github.com/user-attachments/assets/9fbd290a-3f30-41e8-a20c-34a5163ee206): https://github.com/dorschw/content/actions/runs/10389754806/job/28768531274?pr=1
=> Add legacy-validate GHA for contributions

Packs/DeveloperTools/ReleaseNotes/1_3_21.md, Packs/DeveloperTools/Scripts/Hey/Hey.yml, Packs/DeveloperTools/pack_metadata.json
https://github.com/demisto/dockerfiles/pull/31262
Deprecate hey script
=> Deprecate hey script

Packs/DeveloperTools/ReleaseNotes/1_3_21.md, Packs/DeveloperTools/Scripts/Hey/Hey.yml, Packs/DeveloperTools/pack_metadata.json
=> Revert "Deprecate hey script"

Packs/NGINXWebServer/ParsingRules/NGINXWebServerParsingRules/NGINXWebServerParsingRules.xif, Packs/NGINXWebServer/ReleaseNotes/1_0_9.md, Packs/NGINXWebServer/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40677)
=> XSUP_40226_NGINX_Parsing

Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT.yml
fixes: TBD
link PaloAltoNetworks_IoT test playbooks to integration yml
=> link PaloAltoNetworks_IoT test playbooks to yml

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11520
link generic-sql-oracle TPB to genericSQL integration so it will run when the integration is changed.
=> link generic-sql-oracle TPB to genericSQL integration

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.yml
fixes: TBD
Link CoreRestAPI test playbook to integration yml so it will run when integration is changed
=> Link CoreRestAPI test playbook to integration yml

Packs/Office365/ParsingRules/Office365/Office365.xif, Packs/Office365/README.md, Packs/Office365/ReleaseNotes/1_0_5.md, Packs/Office365/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-39406)
=> XSUP_39406_Parsing_Product_Update

Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py, Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.yml, Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2_test.py, Packs/FeedUnit42v2/Integrations/FeedUnit42v2/test_data/feed_data.py, Packs/FeedUnit42v2/ReleaseNotes/1_0_56.md, Packs/FeedUnit42v2/pack_metadata.json, Packs/rasterize/Integrations/rasterize/rasterize.py
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11498)
Adding Parse Malware
=> adding parse malware

Packs/Reco/Integrations/Reco/README.md, Packs/Reco/Integrations/Reco/Reco.py, Packs/Reco/Integrations/Reco/Reco.yml, Packs/Reco/ReleaseNotes/1_5_0.md, Packs/Reco/pack_metadata.json
=> Reco: get-assets by id

.github/content_roles.json
=> change contributions tl

Packs/CiscoSpark/Integrations/CiscoWebexEventCollector/CiscoWebexEventCollector_description.md, Packs/CiscoSpark/ReleaseNotes/1_0_8.md, Packs/CiscoSpark/pack_metadata.json
=> Fix relative paths

Packs/MicrosoftIISWebServer/ReleaseNotes/1_0_10.md
fixes: [CRTX-125833](https://jira-dc.paloaltonetworks.com/browse/CRTX-125833)
In the release notes to version 1.0.10 which were deployed via PR # [35940](https://github.com/demisto/content/pull/35940),  
there was a minor in-accuracy mentioning two fields. 
This PR is for fixing the relevant release note with the correct fields.
=> CRTX-125833 IIS Fix 1.0.10 Release Notes 

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py, Packs/QRadar/ReleaseNotes/2_5_3.md, Packs/QRadar/pack_metadata.json
=> fix a bug with limit_assets

.github/content_roles.json
Contributions team member changes.
=> team members changes

.github/CODEOWNERS, Packs/IdentityRecordedFuture/Integrations/IdentityRecordedFuture/IdentityRecordedFuture_description.md, Packs/IdentityRecordedFuture/ReleaseNotes/2_0_2.md, Packs/IdentityRecordedFuture/pack_metadata.json
=> Test upload rel path

.github/content_roles.json
=> change team

Config/approved_tags.json
Done for Nadav Kanon
Nadav asked.
=> added feed tag

Packs/CoreAlertFields/IncidentFields/incidentfield-Action_Process_Instance_ID.json, Packs/CoreAlertFields/IncidentFields/incidentfield-Actor_Process_Instance_ID.json, Packs/CoreAlertFields/ReleaseNotes/1_0_37.md, Packs/CoreAlertFields/pack_metadata.json
fixes: N.A.
Changed the incident fields' type from `shortText` to `multiSelect`.
=> Fix actor and action process id instance incident fields

Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.py, Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2.yml, Packs/Carbon_Black_Enterprise_Response/Integrations/CarbonBlackResponseV2/CarbonBlackResponseV2_test.py, Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/2_1_48.md, Packs/Carbon_Black_Enterprise_Response/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10508)
```
CarbonBlackResponseV2.py:428: error:
Function "id" could always be true in boolean context [truthy-function]
if id:
```
=> [Carbon Black EDR v2] mypy

Packs/CommonScripts/ReleaseNotes/1_15_55.md, Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11633
`replace` should only occur on strings
=> Fix str replace

Packs/Okta/Integrations/Okta_v2/Okta_v2.py, Packs/Okta/ReleaseNotes/3_3_2.md, Packs/Okta/pack_metadata.json
fixes: [CIAC-11640](https://jira-dc.paloaltonetworks.com/browse/CIAC-11640)
=> Okta get factors fix

Packs/DomainTools_Iris/Scripts/CheckLastEnrichment/CheckLastEnrichment_test.py
=> Added freeze_time to CheckLastEnrichment_test.py

Packs/Illumio/Integrations/IllumioCore/IllumioCore.py, Packs/Illumio/Integrations/IllumioCore/IllumioCore.yml, Packs/Illumio/Integrations/IllumioCore/IllumioCore_test.py, Packs/Illumio/ReleaseNotes/1_0_21.md, Packs/Illumio/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10508)
ignore mypy errors in `IllumioCore.py`
=> [IllumioCore] pre-commit

Packs/MISP/Integrations/MISPV3/MISPV3.py, Packs/MISP/Integrations/MISPV3/MISPV3.yml, Packs/MISP/ReleaseNotes/2_1_45.md, Packs/MISP/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10508)
ignore mypy errors in `MISPV3.py`
=> [MISPV3] mypy ignore

.circleci/is_file_up_to_date.sh
fixes:
As part of reviewing [this contribution CircleCI check failure](https://app.circleci.com/pipelines/github/demisto/content/379113/workflows/46eda44e-3d05-429b-83cf-e273ec14452a/jobs/751431), I noticed that there was a missing new line:
=> Fix missing new line in file up-to-date check

Packs/MicrosoftExchangeOnline/Integrations/EWSO365/EWSO365_description.md, Packs/MicrosoftExchangeOnline/Integrations/EWSO365/README.md, Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_4.md, Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_5.md, Packs/MicrosoftExchangeOnline/pack_metadata.json
added configuration on cortex side instruction
=> ewsO365 - add oproxy to description

.github/content_roles.json
Contribution team member changes.
=> changes to content cont team members.

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_13.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-40819
currently, changes in tags in CS side didn't reflect via mirror in.
=> CrowdStrikeFalcon: fix tag mirroring

Packs/Office365/ModelingRules/Office365/Office365.xif, Packs/Office365/ModelingRules/Office365/Office365_schema.json, Packs/Office365/ParsingRules/Office365/Office365.xif, Packs/Office365/README.md, Packs/Office365/ReleaseNotes/1_0_6.md, Packs/Office365/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-10475?jql=text%20~%20%22Office%20365%22%20and%20status%20%3D%20Done)
=> Office 365 Email Dataset Update

Packs/TeamCymru/.pack-ignore, Packs/TeamCymru/Integrations/TeamCymruScout/README.md, Packs/TeamCymru/Integrations/TeamCymruScout/TeamCymruScout.yml, Packs/TeamCymru/README.md, Packs/TeamCymru/ReleaseNotes/2_0_1.md, Packs/TeamCymru/pack_metadata.json
- Documentation and metadata improvements.
=> Team Cymru Release 201

Config/corepacks_override.json
Bumping CoreAlertFields in the core list to correspond to the [latest changes](https://github.com/demisto/content/pull/36029) pushed by security. Base needs to be bumped as it is a dependency of CoreAlertFields
=> updating corealerts in core

Tests/docker_native_image_config.json
Update candidate image to demisto/py3-native:8.8.0.108569
[pipeline](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/8146573)
=> [Native Image] Update Candidate Image

Packs/AzureStorageContainer/.pack-ignore, Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.py, Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer.yml, Packs/AzureStorageContainer/Integrations/AzureStorageContainer/AzureStorageContainer_test.py, Packs/AzureStorageContainer/Integrations/AzureStorageContainer/README.md, Packs/AzureStorageContainer/ReleaseNotes/1_0_22.md, Packs/AzureStorageContainer/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40794)
Added the argument *account_key* to the ***azure-storage-container-sas-create*** command.
=> AzureStorageContainer] Fix XSUP-40794

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_14.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41144)
Updating the docs to be more clear
=> fix crowdstrike falcon mirror docs

Tests/conf.json
rekated: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11274)
=> returned some tests

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py, Packs/QRadar/Integrations/QRadar_v3/README.md, Packs/QRadar/ReleaseNotes/2_5_4.md, Packs/QRadar/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41035
=> [XSUP-41035] added quiet_mode arg

.github/content_roles.json
=> changes to team

.github/content_roles.json
=> Team changes.

Packs/TaniumThreatResponse/.pack-ignore, Packs/TaniumThreatResponse/Integrations/TaniumThreatResponse/README.md, Packs/TaniumThreatResponse/Integrations/TaniumThreatResponse/TaniumThreatResponse.py, Packs/TaniumThreatResponse/Integrations/TaniumThreatResponse/TaniumThreatResponse.yml, Packs/TaniumThreatResponse/ReleaseNotes/2_2_16.md, Packs/TaniumThreatResponse/pack_metadata.json
Related: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11530) to the issue
Fix error IN136
=> [TaniumThreatResponse]RM102&IN136

Packs/CortexXDR/.pack-ignore, Packs/CortexXDR/Integrations/CortexXDRIR/README.md, Packs/DeepInstinct/.pack-ignore, Packs/GreyNoise/.pack-ignore
Related: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11530) to the issue
=> RM102&IN136 update pack-ignore

Packs/CommonScripts/Scripts/SSDeepSimilarity/SSDeepSimilarity.yml
Packs/CommonScripts/Scripts/SSDeepSimilarity/SSDeepSimilarity.yml
=> demisto/ssdeep:1.0.0.110224 | 0-100 | PR batch #1/1

Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml
Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml
=> demisto/processing-image-file:1.0.0.110217 | 0-100 | PR batch #1/1

Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.yml
Packs/CommonScripts/Scripts/ReadQRCode/ReadQRCode.yml
=> demisto/qrcode:1.0.0.110405 | 0-100 | PR batch #1/1

Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml, Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml, Packs/GoogleCalendar/Integrations/GoogleCalendar/GoogleCalendar.yml, Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml, Packs/GoogleDocs/Integrations/GoogleDocs/GoogleDocs.yml, Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml, Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml, Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.yml, Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.yml, Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
Packs/GSuiteAdmin/Integrations/GSuiteAdmin/GSuiteAdmin.yml
Packs/GSuiteSecurityAlertCenter/Integrations/GSuiteSecurityAlertCenter/GSuiteSecurityAlertCenter.yml
Packs/GoogleCalendar/Integrations/GoogleCalendar/GoogleCalendar.yml
Packs/GoogleCloudCompute/Integrations/GoogleCloudCompute/GoogleCloudCompute.yml
Packs/GoogleDocs/Integrations/GoogleDocs/GoogleDocs.yml
Packs/GoogleDrive/Integrations/GoogleDrive/GoogleDrive.yml
Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
Packs/GoogleResourceManager/Integrations/GoogleResourceManager/GoogleResourceManager.yml
Packs/GoogleSheets/Integrations/GoogleSheets/GoogleSheets.yml
Packs/GoogleVault/Integrations/GoogleVault/GoogleVault.yml
=> demisto/googleapi-python3:1.0.0.110187 | 0-100 | PR batch #1/2

Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
Packs/GsuiteAuditor/Integrations/GsuiteAuditor/GsuiteAuditor.yml
=> demisto/googleapi-python3:1.0.0.110187 | 0-100 | PR batch #2/2

Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
Packs/GoogleBigQuery/Integrations/GoogleBigQuery/GoogleBigQuery.yml
=> demisto/bigquery:1.0.0.110974 | 0-100 | PR batch #1/1

Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
Packs/GoogleKeyManagementService/Integrations/GoogleKeyManagementService/GoogleKeyManagementService.yml
=> demisto/google-kms:1.0.0.110980 | 0-100 | PR batch #1/1

Packs/GoogleCloudTranslate/Integrations/GoogleCloudTranslate/GoogleCloudTranslate.yml
Packs/GoogleCloudTranslate/Integrations/GoogleCloudTranslate/GoogleCloudTranslate.yml
=> demisto/google-cloud-translate:1.0.0.110178 | 0-100 | PR batch #1/1

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/Integrations/CortexCoreIR/README.md, Packs/Core/ReleaseNotes/3_0_61.md, Packs/Core/pack_metadata.json, Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml, Packs/CortexXDR/Integrations/CortexXDRIR/README.md, Packs/CortexXDR/ReleaseNotes/6_1_70.md, Packs/CortexXDR/pack_metadata.json
fixes: [CIAC-11730](https://jira-dc.paloaltonetworks.com/browse/CIAC-11730)
=> Improve core list risky hosts host_id argument documentation

Packs/ServiceNow/Integrations/ServiceNow_CMDB/README.md, Packs/ServiceNow/Integrations/ServiceNow_CMDB/ServiceNow_CMDB_description.md, Packs/ServiceNow/Integrations/ServiceNowv2/README.md, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md, Packs/ServiceNow/ReleaseNotes/2_6_8.md, Packs/ServiceNow/pack_metadata.json
fixes: [XSUP-41327](https://jira-dc.paloaltonetworks.com/browse/XSUP-41327)
Fixed links in documentation.
=> Snow docs fix

Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.py, Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity.yml, Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_description.md, Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/MicrosoftManagementActivity_test.py, Packs/MicrosoftManagementActivity/Integrations/MicrosoftManagementActivity/README.md, Packs/MicrosoftManagementActivity/ReleaseNotes/1_3_45.md, Packs/MicrosoftManagementActivity/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41470)
- Fixed an issue where the test button did not work with the Cortex XSOAR application.
=> Fix Microsoft Management Activity test-module

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI_description.md, Packs/DemistoRESTAPI/ReleaseNotes/1_3_60.md, Packs/DemistoRESTAPI/pack_metadata.json
Related Issues
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41338)
=> Core API Improve Docs

.github/content_roles.json
=> add to oncall devs

Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Path_Rules.yml, Packs/CortexAttackSurfaceManagement/README.md, Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_49.md, Packs/CortexAttackSurfaceManagement/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/EXPANDR-11245
Added the following Attack Surface Rules to Automated Remediation Requirements: 
- TFTP Server
- Libssh
- Insecure Bitvise SSH Server
- Insecure SFTPGo
=> [ASM] Add ASRs EXPANDR-11245

Packs/ApiModules/Scripts/CoreIRApiModule/CoreIRApiModule.py, Packs/Core/ReleaseNotes/3_0_62.md, Packs/Core/pack_metadata.json, Packs/CortexXDR/ReleaseNotes/6_1_71.md, Packs/CortexXDR/pack_metadata.json, Packs/EasyVista/Integrations/EasyVista/EasyVista.py, Packs/EasyVista/ReleaseNotes/1_0_10.md, Packs/EasyVista/pack_metadata.json, Packs/FeedNVDv2/Integrations/FeedNVDv2/FeedNVDv2.py, Packs/FeedNVDv2/ReleaseNotes/1_0_5.md, Packs/FeedNVDv2/pack_metadata.json, Packs/RSANetWitnessEndpoint/Integrations/RSANetWitnessEndpoint/RSANetWitnessEndpoint.py, Packs/RSANetWitnessEndpoint/ReleaseNotes/1_0_13.md, Packs/RSANetWitnessEndpoint/pack_metadata.json, Packs/SpyCloud/Integrations/SpyCloud/SpyCloud.py, Packs/SpyCloud/ReleaseNotes/1_0_5.md, Packs/SpyCloud/pack_metadata.json, Packs/Whois/Integrations/Whois/Whois.py, Packs/Whois/ReleaseNotes/1_5_18.md, Packs/Whois/pack_metadata.json, Packs/XMCO/Integrations/Serenety/Serenety.py, Packs/XMCO/ReleaseNotes/1_0_1.md, Packs/XMCO/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41669)
demisto.debug(e) throws an error since exceptions are not json serializable. calling str works
=> Fix demisto.debug(e)

Packs/DataBee/Integrations/DataBee/DataBee.py, Packs/DataBee/Integrations/DataBee/DataBee_test.py, Packs/DataBee/ReleaseNotes/1_0_1.md, Packs/DataBee/pack_metadata.json
Fixed an issue with authentication to DataBee API.
=> Fixed an issue with authentication to DataBee API

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py, Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_16.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41609
wrong `for` loop when the `resources` are `None`
**new test before fix**:
**after**:
=> CS Falcon: fix wrong code

Packs/CommonTypes/IndicatorFields/indicatorfield-Validity_Not_After.json, Packs/CommonTypes/IndicatorFields/indicatorfield-Validity_Not_Before.json, Packs/CommonTypes/ReleaseNotes/3_5_17.md, Packs/CommonTypes/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-115732
Adding missing descriptions to the Validity fields for X509 certs.
=> Adding descriptions to indicator fields

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py, Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml, Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams_test.py, Packs/MicrosoftTeams/ReleaseNotes/1_4_69.md, Packs/MicrosoftTeams/pack_metadata.json
Internal PR for contribution: https://github.com/demisto/content/pull/35592
Opened this PR to address failed unit tests that couldn't be resolved in the external contribution PR, as the contribution was made via the XSOR UI. This PR serves as an internal PR replacement
=> [Marketplace Contribution] Microsoft Teams - Content Pack Update - Internal PR

Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes_description.md, Packs/Malwarebytes/ReleaseNotes/1_1_18.md, Packs/Malwarebytes/pack_metadata.json
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-10611 
checking change path of description
=> checking description

Packs/Zscaler/Integrations/Zscaler/README.md, Packs/Zscaler/Integrations/Zscaler/Zscaler.py, Packs/Zscaler/ReleaseNotes/1_3_25.md, Packs/Zscaler/pack_metadata.json
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-41803)
Documentation and metadata improvements.
See: 
https://help.zscaler.com/zia/configuring-url-categories-using-api
https://help.zscaler.com/zia/url-format-guidelines
=> [Zscaler] Documentation and metadata improvements

Packs/ServiceNow/Integrations/ServiceNowv2/README.md, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_description.md, Packs/ServiceNow/ReleaseNotes/2_6_9.md, Packs/ServiceNow/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41327
Updated the grant type upon further investigation
=> Update the grant type in docs

Packs/CommonPlaybooks/Playbooks/playbook-Account_Enrichment_-_Generic_v2.2.yml, Packs/CommonPlaybooks/ReleaseNotes/2_6_40.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41927
Updated the 'IAM Get User - Without specifying a domain' condition by adding a transformer (Stringify) to support numeric usernames.
=> Account_enrichment_fix

Packs/MandiantAdvantageThreatIntelligence/.pack-ignore, Packs/MandiantAdvantageThreatIntelligence/Integrations/FeedMandiantThreatIntelligence/FeedMandiantThreatIntelligence.yml, Packs/MandiantAdvantageThreatIntelligence/ReleaseNotes/1_1_1.md, Packs/MandiantAdvantageThreatIntelligence/pack_metadata.json
fixes: [CIAC-11853](https://jira-dc.paloaltonetworks.com/browse/CIAC-11853)
=> Remove 'suddenDeath' option from feed mandiant threat intelligence

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml, Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/README.md, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_38.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Related: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11847)
Rename "Microsoft Defender for Endpoint Event Collector" to "Microsoft Defender for Endpoint Alerts.
=> Rename "Microsoft Defender for Endpoint Event Collector" to "Microsoft Defender for Endpoint Alerts

Packs/Azure-Enrichment-Remediation/Playbooks/playbook-Azure_-_User_Investigation.yml, Packs/Azure-Enrichment-Remediation/ReleaseNotes/1_1_20.md, Packs/Azure-Enrichment-Remediation/pack_metadata.json, Packs/CommonPlaybooks/Playbooks/playbook-SIEM_-_Search_for_Failed_logins.yml, Packs/CommonPlaybooks/ReleaseNotes/2_6_41.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11838
Updated the Azure Log Analytics query to support special characters.
=> SIEM_search_PB_query_fix

Packs/Jira/Integrations/JiraV3/README.md
relates: https://jira-dc.paloaltonetworks.com/browse/CIAC-10611
part of https://github.com/demisto/content/pull/34807, https://github.com/demisto/content/pull/35287- ***Jira integration*** read me images link update
=> chage path Jira

Packs/Jira/Integrations/JiraV3/README.md
=> Remove Jira gifs from the docs files dir in content repo

Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11234)
=> removed the generic webhook from the conf.json

Packs/qualys/Integrations/Qualysv2/Qualysv2.py, Packs/qualys/Integrations/Qualysv2/Qualysv2_test.py, Packs/qualys/ReleaseNotes/3_0_6.md, Packs/qualys/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-40969)
Addition of timeout handling by lowering the limit in the case of time-out.
=> Qualys VMDR: handle timeout error

Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.py, Packs/Cisco-umbrella/ReleaseNotes/2_0_1.md, Packs/Cisco-umbrella/pack_metadata.json
Added human-readable output to ```!domain``` command.
attached screenshots:
=> Adding HR to !domain command

.github/content_roles.json
change contribution team members.
=> change contribution team members.

.github/content_roles.json
=> change on-call team members

.github/content_roles.json
=> add team member.

.github/github_workflow_scripts/skip_conditions.py
fixes: [CIAC-11897](https://jira-dc.paloaltonetworks.com/browse/CIAC-11897)
=> fix autobump timezone

Packs/cisco-ise/ModelingRules/cisco-ise/cisco-ise.yml, Packs/cisco-ise/ParsingRules/cisco-ise/cisco-ise.yml, Packs/cisco-ise/ReleaseNotes/1_0_21.md, Packs/cisco-ise/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42012)
- Updated the modeling rule name and id.
- Updated the parsing rule name and id.
=> Cisco ISE - update modeling and parsing rules

Packs/qualys/Integrations/Qualysv2/Qualysv2.py, Packs/qualys/ReleaseNotes/3_0_7.md, Packs/qualys/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/XSUP-40703
=> Qualys v2: Fixed an issue in check_fetch_duration_time

Packs/GenericSQL/Integrations/GenericSQL/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11934
=> Document Teradata in Generic SQL README

Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11400
Change `dev` to `federal` URL.
=> [CDL] Change Token URL from dev to federal

Packs/GoogleVisionAPI/Integrations/GoogleVisionAPI/GoogleVisionAPI.yml
…tch #1/1 (#36504)
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-10951?filter=-1
=> Aud demisto/auto update docker staging branch 1502

Packs/Whois/Integrations/Whois/Whois.yml, Packs/Whois/ReleaseNotes/1_5_19.md, Packs/Whois/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41388
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11891
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42262
=> upgrade-whois-docker

.hooks/bootstrap
=> redirect poetry install logs

validation_config.toml
Related: [link](https://jira-dc.paloaltonetworks.com/browse/CIAC-11971) to the issue
Move GR107 to warning, this is temporary solution until the ticket is done
=> Move GR107 to Warning

Packs/AHA/Integrations/AHA/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-6417)
=> AHA readme fix

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_description.md, Packs/GenericSQL/ReleaseNotes/1_3_3.md, Packs/GenericSQL/pack_metadata.json
Adding Teradata DB for description.
=> Adding Teradata DB for description

Packs/KeeperSecurity/Integrations/KeeperSecurity/KeeperSecurity.py, Packs/KeeperSecurity/ReleaseNotes/1_0_1.md, Packs/KeeperSecurity/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42535
Added indicative error message when login fails due to SSO redirect.
=> [Keeper Security] Add error message for SSO redirect

Packs/TIM_Processing/ReleaseNotes/1_1_27.md
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42119)
=> Fix RN for TIM Processing 1.1.27

Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py, Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector_test.py, Packs/JamfProtect/ReleaseNotes/1_1_2.md, Packs/JamfProtect/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42504)
Computer variables were accessed before assigned.
=> Fix referenced before assigned computer events

Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py, Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.yml, Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py, Packs/AutoFocus/ReleaseNotes/2_2_5.md, Packs/AutoFocus/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42586)
Add the option for a custom separator in the autofocus V2 url command
=> add the separator option

Packs/PrismaSaasSecurity/Integrations/SaasSecurity/SaasSecurity.py, Packs/PrismaSaasSecurity/ReleaseNotes/2_0_31.md, Packs/PrismaSaasSecurity/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42273
=> SaaS-Security update last run in case no new incidents were fetched

.github/github_workflow_scripts/handle_external_pr.py
Add comment to external PR's about delay in review because of holldays
Add comment to external PR's about delay in review because of holldays
=> Add comment to external PR's about hoildays

Packs/GenericSQL/pack_metadata.json
Edit description in pack_metadata.json file.
=> Generic SQL - Edit description in pack_metadata.json file

.github/content_roles.json
=> change on_call

Packs/EDL/Integrations/EDL/EDL.yml, Packs/EDL/ReleaseNotes/3_3_4.md, Packs/EDL/pack_metadata.json
=> Update docker image to demisto/flask-nginx:1.0.0.113398 in EDL

Packs/Box/Integrations/BoxEventsCollector/BoxEventsCollector.py, Packs/Box/ReleaseNotes/3_2_2.md, Packs/Box/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42662)
=> Box collector fix Url serialize error

Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3.yml, Packs/CommonPlaybooks/Playbooks/playbook-Block_Indicators_-_Generic_v3_README.md, Packs/CommonPlaybooks/ReleaseNotes/2_6_44.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11979
Fixing the 'AutoBlockIndicators' playbook input.
=> Ciac 11979 - Fixing the 'AutoBlockIndicators' playbook input

Packs/Workday/ParsingRules/WorkdayParsingRules/WorkdayParsingRules.xif, Packs/Workday/ReleaseNotes/1_4_13.md, Packs/Workday/pack_metadata.json
fixes: [CRTX-135202](https://jira-dc.paloaltonetworks.com/browse/CRTX-135202)
Added to_string before requestTime due to validation issue.
=> Added to_string for requestTime - Workday

Packs/AutoFocus/.secrets-ignore, Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py, Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py, Packs/AutoFocus/ReleaseNotes/2_2_6.md, Packs/AutoFocus/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42586)
Fixed an issue that non ascii regex parser for url command was not functioning properly.
=> fixed autofocus non ascii parsing for url command

.github/github_workflow_scripts/handle_external_pr.py
Remove holiday message from handle_external_pr
=> Remove holiday message

Packs/Core/.pack-ignore
Remove unnecessary ignore 103. see slack thread for more background https://panw-global.slack.com/archives/G011E63JXPB/p1729599311545729
=> Remove unnecessary ignore 103.

Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/README.md, Packs/MicrosoftExchangeOnline/Integrations/SecurityAndComplianceV2/SecurityAndComplianceV2_description.md, Packs/MicrosoftExchangeOnline/ReleaseNotes/1_5_11.md, Packs/MicrosoftExchangeOnline/pack_metadata.json
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42340)
Updated the documentation to include the required *Exchange.Manage* delegated permission for proper functionality.
=> Security And Compliance - Content Search V2 - update permissions

.pre-commit-config_template.yaml
=> Skip on nightly check large files

Packs/CommunityCommonDashboards/Dashboards/CISOMetrics.json, Packs/CommunityCommonDashboards/ReleaseNotes/2_0_4.md, Packs/CommunityCommonDashboards/pack_metadata.json
=> Change marketplace field in CISOMetrics dashbord

Packs/SophosCentral/README.md
=> Sophos change readme

Packs/CommonPlaybooks/Playbooks/playbook-Endpoint_Investigation_Plan.yml, Packs/CommonPlaybooks/ReleaseNotes/2_6_45.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12053)
Fixed an issue with the 'SearchAlertsV2' query for hunt by host ID.
=> Endpoint investigation plan fix

Packs/BmcITSM/Integrations/BmcITSM/BmcITSM.py, Packs/BmcITSM/ReleaseNotes/1_0_28.md, Packs/BmcITSM/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-42654)
Changed the support company field from  Support Company to Assignee Company.
=> BMC-itsm Fixed task update for assigned support company

Packs/Core/Playbooks/playbook-SSO_Password_Spray.yml, Packs/Core/ReleaseNotes/3_0_83.md, Packs/Core/pack_metadata.json
In the risky user score task I have change from Core.RiskyUser.score to Core.RiskyUser.risk_level
=> fix in Core.RiskyUser

Packs/Zscaler/Integrations/Zscaler/Zscaler.py, Packs/Zscaler/ReleaseNotes/1_3_27.md, Packs/Zscaler/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43228)
Fixed an issue where the **zscaler-logout** and **zscaler-activate-changes** commands did not work properly and returned an error.
=> [Zscaler Internet Access] Fixed an issue where the zscaler-logout and zscaler-activate-changes returned an error

Packs/QRadar/Playbooks/playbook-QRadar_Generic.yml, Packs/QRadar/ReleaseNotes/2_5_6.md, Packs/QRadar/pack_metadata.json
Ready
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43037
Fixed an issue where the username from the QRadar offense was not being enriched due to incorrect context path in playbook `QRadar - Generic` -> task `Entity Enrichment - Generic v3`.
The fix preserves BC and still sets Account.Username if QRadar.Username is empty.
=> QRadar - Generic - fixed issue with username enrichment

Packs/Algosec/Integrations/AlgoSec/AlgoSec.yml, Packs/Algosec/Integrations/AlgoSec/README.md, Packs/Algosec/ReleaseNotes/1_0_14.md, Packs/Algosec/Scripts/AlgosecGetApplications/AlgosecGetApplications.yml, Packs/Algosec/Scripts/AlgosecGetApplications/README.md, Packs/Algosec/pack_metadata.json
Change the product name BusinessFlow to appviz in all algosec pack documentation
=> change businessflow to appviz

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py, Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py, Packs/CrowdStrikeFalcon/ReleaseNotes/2_0_22.md, Packs/CrowdStrikeFalcon/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-43317
Fixed an issue where detections were fetched unsorted in the post-Raptor release.
=> Fix the detection query to sort in ascending order

.github/content_roles.json
=> Update security and doc review

Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py, Packs/JamfProtect/ReleaseNotes/1_1_3.md, Packs/JamfProtect/pack_metadata.json
related: https://jira-dc.paloaltonetworks.com/browse/XSUP-43237
=> JAMF Protect: Log errorneous responses

Packs/UrlScan/Integrations/UrlScan/UrlScan.py, Packs/UrlScan/ReleaseNotes/1_2_16.md, Packs/UrlScan/pack_metadata.json
-
In some cases, when the given URL points to a file, urlscan API does not return all the expected metadata values and the integration fails. This modification fixes the issue.
=> urlscan - file metadata issue fix

Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py, Packs/CybleEventsV2/ReleaseNotes/1_0_5.md, Packs/CybleEventsV2/pack_metadata.json
NA
Sometimes fetched alerts do not have data message field which results in app throwing an error and getting stuck. This PR is to fix this issue.
=> Fixed alerts message reading error

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/Microsoft365DefenderEventCollector/Microsoft365DefenderEventCollector.yml, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_16_42.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
…1 (#37060)
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12112)
=> Updated docker image to demisto/auth-utils:1.0.0.114762. PR batch #1/1

Packs/Armis/Integrations/Armis/Armis.yml, Packs/Armis/ReleaseNotes/1_1_17.md, Packs/Armis/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-42363?filter=-1
=> update armis docker image

Packs/AWS-SNS-Listener/Integrations/AWSSNSListener/AWSSNSListener.yml, Packs/AWS-SNS-Listener/ReleaseNotes/1_0_5.md, Packs/AWS-SNS-Listener/pack_metadata.json, Packs/GenericWebhook/Integrations/GenericWebhook/GenericWebhook.yml, Packs/GenericWebhook/ReleaseNotes/1_1_3.md, Packs/GenericWebhook/pack_metadata.json, Packs/GenericWebhook_FormData/Integrations/GenericWebhookFormData/GenericWebhookFormData.yml, Packs/GenericWebhook_FormData/ReleaseNotes/1_0_1.md, Packs/GenericWebhook_FormData/pack_metadata.json, Packs/GitLab/Integrations/GitLabEventCollector/GitLabEventCollector.yml, Packs/GitLab/ReleaseNotes/2_2_24.md, Packs/GitLab/pack_metadata.json, Packs/Okta/Integrations/OktaEventCollector/OktaEventCollector.yml, Packs/Okta/ReleaseNotes/3_3_6.md, Packs/Okta/pack_metadata.json, Packs/PublishList/Integrations/PublishList/PublishList.yml, Packs/PublishList/ReleaseNotes/1_1_4.md, Packs/PublishList/pack_metadata.json, Packs/SimpleAPIProxy/Integrations/SimpleAPIProxy/SimpleAPIProxy.yml, Packs/SimpleAPIProxy/ReleaseNotes/1_0_4.md, Packs/SimpleAPIProxy/pack_metadata.json, Packs/Zoom/Integrations/Zoom/Zoom.yml, Packs/Zoom/ReleaseNotes/1_6_15.md, Packs/Zoom/Scripts/ZoomAsk/ZoomAsk.yml, Packs/Zoom/pack_metadata.json
… (#37068)
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12115
=> AUD-demisto/auto_update_docker_staging_branch_28

Packs/CommonScripts/ReleaseNotes/1_15_81.md, Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml, Packs/CommonScripts/pack_metadata.json, Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_7.md, Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.yml, Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.yml, Packs/SuspiciousDomainHunting/Scripts/RasterizeImageSuspicious/RasterizeImageSuspicious.yml, Packs/SuspiciousDomainHunting/pack_metadata.json
…R batch #1/1 (#37093)
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12122)
demisto/processing-image-file
=> Aud demisto/auto update docker staging branch 33

Packs/PhishingURL/ReleaseNotes/1_1_21.md, Packs/PhishingURL/Scripts/DBotPredictURLPhishing/DBotPredictURLPhishing.py, Packs/PhishingURL/pack_metadata.json
=> DBotPredictURLPhishing - check mailto_urls value before return the results

Packs/CSCDomainManager/README.md, Packs/CSCDomainManager/ReleaseNotes/1_0_3.md, Packs/CSCDomainManager/pack_metadata.json
fixes: N/A
Completed the adoption process.
=> Partner csc adoption complete

Packs/CommonScripts/ReleaseNotes/1_15_82.md, Packs/CommonScripts/Scripts/Dig/Dig.yml, Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml, Packs/CommonScripts/Scripts/Ping/Ping.yml, Packs/CommonScripts/pack_metadata.json, Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.yml, Packs/FeedPublicDNS/ReleaseNotes/1_0_17.md, Packs/FeedPublicDNS/pack_metadata.json, Packs/FiltersAndTransformers/ReleaseNotes/1_2_80.md, Packs/FiltersAndTransformers/Scripts/IPv4Blacklist/IPv4Blacklist.yml, Packs/FiltersAndTransformers/Scripts/IPv4Whitelist/IPv4Whitelist.yml, Packs/FiltersAndTransformers/Scripts/IsRFC1918Address/IsRFC1918Address.yml, Packs/FiltersAndTransformers/pack_metadata.json, Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml, Packs/Mattermost/ReleaseNotes/2_0_3.md, Packs/Mattermost/pack_metadata.json, Packs/Nmap/Integrations/Nmap/Nmap.yml, Packs/Nmap/ReleaseNotes/1_2_4.md, Packs/Nmap/pack_metadata.json, Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.yml, Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_5.md, Packs/ProofpointEmailSecurity/pack_metadata.json
…(#37108)
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12132
dockerimage: demisto/netutils:1.0.0.115452
=> Aud demisto/auto update docker staging branch 35

Packs/DemistoRESTAPI/ReleaseNotes/1_3_62.md, Packs/DemistoRESTAPI/Scripts/DemistoUploadFile/DemistoUploadFile.yml, Packs/DemistoRESTAPI/pack_metadata.json
=> UploadFile script fix deprecation message

Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.py, Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3.yml, Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/EclecticIQIntelligenceCenterv3_test.py, Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/README.md, Packs/EclecticIQ/Integrations/EclecticIQIntelligenceCenterv3/command_examples.txt, Packs/EclecticIQ/ReleaseNotes/3_0_5.md, Packs/EclecticIQ/pack_metadata.json
Added two new command in EclecticIQ pack
1. `eclecticiq-request-put` to make HTTP PUT request with EclecticIQ
2. `eclecticiq-request-patch` to make HTTP PATCH request with EclecticIQ
=> added new command support in EclecticIQ pack

Packs/Phishing/ReleaseNotes/3_6_25.md, Packs/Phishing/Scripts/LinkToPhishingCampaign/LinkToPhishingCampaign.py, Packs/Phishing/Scripts/LinkToPhishingCampaign/README.md, Packs/Phishing/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43631)
Fixed the incident links in the script result.
=> [Xsup 43700] LinkToPhishingCampaign  -Fixed the incident links

Packs/Armis/Integrations/ArmisEventCollector/ArmisEventCollector.yml, Packs/Armis/ReleaseNotes/1_1_18.md, Packs/Armis/pack_metadata.json, Packs/BitwardenPasswordManager/Integrations/BitwardenPasswordManager/BitwardenPasswordManager.yml, Packs/BitwardenPasswordManager/ReleaseNotes/1_0_2.md, Packs/BitwardenPasswordManager/pack_metadata.json, Packs/CarbonBlackDefense/Integrations/CarbonBlackEndpointStandardV3/CarbonBlackEndpointStandardV3.yml, Packs/CarbonBlackDefense/ReleaseNotes/4_0_4.md, Packs/CarbonBlackDefense/pack_metadata.json, Packs/DNSDB/Integrations/DNSDB_v2/DNSDB_v2.yml, Packs/DNSDB/ReleaseNotes/2_1_24.md, Packs/DNSDB/pack_metadata.json, Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_5_27.md, Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRenderRelated/CyrenThreatInDepthRenderRelated.yml, Packs/FeedCyrenThreatInDepth/pack_metadata.json, Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml, Packs/FeedRecordedFuture/ReleaseNotes/1_1_6.md, Packs/FeedRecordedFuture/pack_metadata.json, Packs/IntSight/Integrations/Rapid7ThreatCommand/Rapid7ThreatCommand.yml, Packs/IntSight/ReleaseNotes/3_1_5.md, Packs/IntSight/pack_metadata.json, Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.yml, Packs/Rapid7AppSec/ReleaseNotes/1_0_5.md, Packs/Rapid7AppSec/pack_metadata.json, Packs/Respond/Integrations/RespondAnalyst/RespondAnalyst.yml, Packs/Respond/ReleaseNotes/1_0_9.md, Packs/Respond/pack_metadata.json, Packs/ThreatConnect/Integrations/ThreatConnectV3/ThreatConnectV3.yml, Packs/ThreatConnect/ReleaseNotes/3_1_9.md, Packs/ThreatConnect/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-43312)
demisto/python3:3.11.10.115186
=> Bump image tags to latest in requested packs XSUP-44312

Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.py, Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.yml, Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2_test.py, Packs/GuardiCore/ReleaseNotes/2_0_13.md, Packs/GuardiCore/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43323
Changed bearer to Bearer, as new versions of Guardicore require.
=> changed bearer to Bearer

Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII.yml, Packs/FeedTAXII/Integrations/FeedTAXII/FeedTAXII_description.md, Packs/FeedTAXII/Integrations/FeedTAXII/README.md, Packs/FeedTAXII/ReleaseNotes/1_2_21.md, Packs/FeedTAXII/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12171
https://github.com/demisto/content-docs/issues/1654
=> Bug fix/CIAC-12171/update discovery url in TAXII feed

Packs/TAXIIServer/Integrations/TAXIIServer/README.md
- Cleaned up formatting
- Added For Cortex XSOAR 8 On-prem, you need to add the `ext-` FQDN DNS record
- Added set up authentication using custom certificates for OPP
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3801
=> Update TAXII Service integration README.md

Packs/TAXIIServer/Integrations/TAXII2Server/README.md
- Cleaned up formatting
- Updated for XSOAR 8 OPP, including set up authentication using custom certificates for OPP
- Added For Cortex XSOAR 8 On-prem, you need to add the ext- FQDN DNS record and the api-FQDN DNS record
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3801
=> Update the TAXII2 Server Integration README.md

Packs/WebFileRepository/Integrations/WebFileRepository/README.md
- Minor formatting cleanup
- added for Cortex XSOAR 8 On-prem, you need to add the ext- FQDN DNS record
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3801
=> Update Web File Repository Integration README.md

Packs/TAXIIServer/Integrations/TAXII2Server/README.md
Fixed headings, removed the note to add the api- FQDN for OPP
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTXDOC-3801
=> Update TAXII2 Integration README.md

Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md, Packs/Akamai_SIEM/ReleaseNotes/1_1_6.md, Packs/Akamai_SIEM/ReleaseNotes/1_1_7.md, Packs/Akamai_SIEM/pack_metadata.json
fixes: [XSUP-43176](https://jira-dc.paloaltonetworks.com/browse/XSUP-43176)
[XSUP-43913](https://jira-dc.paloaltonetworks.com/browse/XSUP-43913)
=> Akamai - fix docker timeout due to integration context not json serializable

.github/content_roles.json
=> replace-on-call

Packs/CommonScripts/ReleaseNotes/1_15_89.md, Packs/CommonScripts/Scripts/ConvertXmlFileToJson/ConvertXmlFileToJson.yml, Packs/CommonScripts/pack_metadata.json, Packs/FeedDHS/Integrations/DHS_Feed/DHS_Feed.yml, Packs/FeedDHS/ReleaseNotes/2_0_44.md, Packs/FeedDHS/pack_metadata.json, Packs/GenetecSecurityCenter/Integrations/GenetecSecurityCenterEventCollector/GenetecSecurityCenterEventCollector.yml, Packs/GenetecSecurityCenter/ReleaseNotes/1_0_1.md, Packs/GenetecSecurityCenter/pack_metadata.json, Packs/PaloAltoNetworksAutomaticSLR_Community/Integrations/PaloAltoNetworksAutomaticSLRCommunity/PaloAltoNetworksAutomaticSLRCommunity.yml, Packs/PaloAltoNetworksAutomaticSLR_Community/ReleaseNotes/1_0_4.md, Packs/PaloAltoNetworksAutomaticSLR_Community/pack_metadata.json
…(#37222)
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12179)
demisto/xml-feed:1.0.0.116765
=> Aud demisto/auto update docker staging branch 46

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml, Packs/CofenseTriage/ReleaseNotes/2_1_30.md, Packs/CofenseTriage/pack_metadata.json
* Updated docker image to demisto/chromium:131.0.6778.116585. PR batch #1/1
* Update rasterize.yml
---------
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12178)
demisto/chromium:131.0.6778.116585
=> Aud demisto/auto update docker staging branch 45

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py, Packs/SplunkPy/ReleaseNotes/3_1_46.md, Packs/SplunkPy/pack_metadata.json
Add docs and change the name of valid_json_format function because of costumers' confusion.
See slack conversation: https://panw-global.slack.com/archives/C011E5T5K17/p1732069979731629
=> ys splunk docs improvement

Packs/Slack/ReleaseNotes/3_5_3.md, Packs/Slack/Scripts/SlackBlockBuilder/README.md, Packs/Slack/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43998
=> Add Note to SlackBlockBuilder README

Packs/CyCognito/Integrations/CyCognito/CyCognito.yml, Packs/CyCognito/ReleaseNotes/1_0_24.md, Packs/CyCognito/Scripts/ThreeDigitAlphaCountryCodeToCountryName/ThreeDigitAlphaCountryCodeToCountryName.yml, Packs/CyCognito/pack_metadata.json, Packs/Cybersixgill-ActionableAlerts/Integrations/CybersixgillActionableAlerts/CybersixgillActionableAlerts.yml, Packs/Cybersixgill-ActionableAlerts/ReleaseNotes/1_2_18.md, Packs/Cybersixgill-ActionableAlerts/Scripts/CybersixgillActionableAlertStatusUpdate/CybersixgillActionableAlertStatusUpdate.yml, Packs/Cybersixgill-ActionableAlerts/pack_metadata.json, Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEEnrichment/CybersixgillDVEEnrichment.yml, Packs/Cybersixgill-DVE/Integrations/CybersixgillDVEFeed/CybersixgillDVEFeed.yml, Packs/Cybersixgill-DVE/ReleaseNotes/1_0_7.md, Packs/Cybersixgill-DVE/pack_metadata.json, Packs/FeedCyCognito/Integrations/FeedCyCognito/FeedCyCognito.yml, Packs/FeedCyCognito/ReleaseNotes/1_0_24.md, Packs/FeedCyCognito/pack_metadata.json, Packs/Infocyte/Integrations/Infocyte/Infocyte.yml, Packs/Infocyte/ReleaseNotes/1_0_6.md, Packs/Infocyte/pack_metadata.json, Packs/OTRS/Integrations/OTRS/OTRS.yml, Packs/OTRS/ReleaseNotes/1_1_1.md, Packs/OTRS/pack_metadata.json, Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed/Sixgill_Darkfeed.yml, Packs/Sixgill-Darkfeed/Integrations/Sixgill_Darkfeed_Enrichment/Sixgill_Darkfeed_Enrichment.yml, Packs/Sixgill-Darkfeed/ReleaseNotes/2_2_23.md, Packs/Sixgill-Darkfeed/pack_metadata.json, Packs/XsoarWebserver/Integrations/XSOARWebServer/XSOARWebServer.yml, Packs/XsoarWebserver/ReleaseNotes/1_0_4.md, Packs/XsoarWebserver/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12226)
=> Aud demisto/auto update docker staging branch 55

Packs/Reco/Integrations/Reco/Reco.py, Packs/Reco/Integrations/Reco/Reco.yml, Packs/Reco/Integrations/Reco/Reco_test.py, Packs/Reco/ReleaseNotes/1_5_1.md, Packs/Reco/pack_metadata.json
=> Reco: add identities support

Utils/download_packs_and_docker_images.py, contribution/utils/download_packs_and_docker_images.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43576
Added handling for Packs with no ContentItems
=> [download_packs_and_docker_images.py] Add Handling for Packs with no ContentItems

Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Emails_Indicators_Hunt.yml, Packs/Microsoft365Defender/Playbooks/playbook-Microsoft_365_Defender_-_Get_Email_URL_Clicks.yml, Packs/Microsoft365Defender/ReleaseNotes/4_5_37.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43793
Fixed an issue where URLs with special characters broke 365 email hunting playbooks.
=> 365 hunting playbook url fix

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py, Packs/SplunkPy/ReleaseNotes/3_1_47.md, Packs/SplunkPy/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44190
- Fixed an issue where **splunk-submit-event-hec** command failed when event included a single quotation mark.
=> XSUP-44190/SplunkPy

Packs/Palo_Alto_Networks_Enterprise_DLP/Classifiers/classifier-Data_Loss_Prevention.json, Packs/Palo_Alto_Networks_Enterprise_DLP/ReleaseNotes/2_0_12.md, Packs/Palo_Alto_Networks_Enterprise_DLP/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-43630
Added "Severity" field to the mapper.
=> DLP mapper severity fix

Packs/AquatoneDiscover/ReleaseNotes/1_0_2.md, Packs/AquatoneDiscover/Scripts/script-AquatoneDiscover.yml, Packs/AquatoneDiscover/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-142151
Added deprecation description.
=> Aquatone discover deprecation note

Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.py, Packs/ImageOCR/Integrations/ImageOCR/ImageOCR.yml, Packs/ImageOCR/Integrations/ImageOCR/ImageOCR_test.py, Packs/ImageOCR/Integrations/ImageOCR/README.md, Packs/ImageOCR/ReleaseNotes/1_1_35.md, Packs/ImageOCR/pack_metadata.json
fixes: [link to the issue
](https://jira-dc.paloaltonetworks.com/browse/XSUP-44052)
=> Add Verbose arg to oce image-ocr-extract-text

Packs/HealthCheck/ReleaseNotes/3_0_1.md, Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.py, Packs/HealthCheck/Scripts/HealthCheckExportSummary/HealthCheckExportSummary.yml, Packs/HealthCheck/pack_metadata.json
=> Fixing export button

Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.yml, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/README.md, Packs/Akamai_SIEM/ReleaseNotes/1_1_9.md, Packs/Akamai_SIEM/pack_metadata.json
=> commit files - akamai increase rate

Packs/EDL/Integrations/EDL/EDL.yml, Packs/EDL/ReleaseNotes/3_3_5.md, Packs/EDL/pack_metadata.json
related: https://jira-dc.paloaltonetworks.com/browse/XSUP-44305#
Fixed an issue where port param was hidden in xsiam marketplace.
=> Edl port bug

Packs/CommonScripts/ReleaseNotes/1_15_95.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44173)
=> Parse email files update docker image

Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif, Packs/MicrosoftEntraID/ReleaseNotes/1_0_2.md, Packs/MicrosoftEntraID/pack_metadata.json
fixes: [CRTX-142434](https://jira-dc.paloaltonetworks.com/browse/CRTX-142434)
Removed spaces and hyphens from key values in the parsed_fields field, so the parsing rule would be able to handle them.
=> Modified parsing rule for msft_azure_ad_audit_raw - Azure Logs

.github/content_roles.json
=> Update usernames in content bot

Packs/Dropbox/Integrations/DropboxEventCollector/DropboxEventCollector.py, Packs/Dropbox/ReleaseNotes/1_1_5.md, Packs/Dropbox/pack_metadata.json
fixes:[ link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44343)
Added some logs to dropbox event collector
=> Debug log dropbox event collector

Packs/AccessInvestigation/ReleaseNotes/1_2_10.md, Packs/AccessInvestigation/pack_metadata.json
=> bump version for AccessInvestigation pack

Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.yml, Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Packs/CommonScripts/Scripts/PDFUnlocker/PDFUnlocker.yml
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
=> demisto/readpdf:1.0.0.117518 | 0-100 | PR batch #1/1

Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.yml, Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.yml, Packs/McAfee_DXL/Integrations/McAfee_DXL/McAfee_DXL.yml
Packs/McAfee-MAR/Integrations/McAfee-MAR/McAfee-MAR.yml
Packs/McAfee-TIE/Integrations/McAfeeTIEV2/McAfeeTIEV2.yml
Packs/McAfee_DXL/Integrations/McAfee_DXL/McAfee_DXL.yml
=> demisto/dxl:1.0.0.116949 | 0-100 | PR batch #1/1

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py, Packs/Elasticsearch/ReleaseNotes/1_3_24.md, Packs/Elasticsearch/pack_metadata.json, Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py, Packs/SplunkPy/ReleaseNotes/3_1_48.md, Packs/SplunkPy/pack_metadata.json
=> dbot mirror id only if not empty

Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.py, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.yml, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2_test.py, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/README.md, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/command-examples.txt, Packs/IronPort/ReleaseNotes/2_1_0.md, Packs/IronPort/TestPlaybooks/CiscoESA_dictionary_commands_tpb.yml, Packs/IronPort/pack_metadata.json, Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9903)
Add new commands to integrate Dictionary APIs for CiscoEmailSecurityApplianceIronPortV2 integration in IronPort pack.
=> CISCO ESA dictionary api commands

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml, Packs/rasterize/Integrations/rasterize/rasterize.yml
Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2.yml
Packs/rasterize/Integrations/rasterize/rasterize.yml
=> demisto/chromium:131.0.6778.117810 | 0-100 | PR batch #1/1

Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
Packs/SMIME_Messaging/Integrations/SMIME_Messaging/SMIME_Messaging.yml
=> demisto/m2crypto:1.0.0.117200 | 0-100 | PR batch #1/1

Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
Packs/GoogleKubernetesEngine/Integrations/GoogleKubernetesEngine/GoogleKubernetesEngine.yml
=> demisto/google-k8s-engine:1.0.0.117480 | 0-100 | PR batch #1/1

Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml, Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
Packs/Syslog/Integrations/SyslogSender/SyslogSender.yml
Packs/Syslog/Integrations/Syslogv2/Syslogv2.yml
=> demisto/syslog:1.0.0.117331 | 0-100 | PR batch #1/1

Packs/Reco/Integrations/Reco/Reco.py, Packs/Reco/Integrations/Reco/Reco_test.py, Packs/Reco/ReleaseNotes/1_5_2.md, Packs/Reco/pack_metadata.json
=> reco: change EP for optimization

Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstoryStreamingAPI/GoogleChronicleBackstoryStreamingAPI.py, Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_1.md, Packs/GoogleChronicleBackstory/pack_metadata.json
- Added the functionality to ignore integration parameters having null values.
=> Chronicle Release 4.1.1

Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py, Packs/CybleEventsV2/ReleaseNotes/1_0_6.md, Packs/CybleEventsV2/pack_metadata.json
NA
Sometimes fetched alerts do not have data message field which results in app throwing an error and getting stuck. This PR is to fix this issue.
=> Bug fix/data message

Packs/CyberChef/Integrations/CyberChef/CyberChef.yml, Packs/CyberChef/ReleaseNotes/1_0_9.md, Packs/CyberChef/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12346)
=> Update cyberchef tag

Packs/CommvaultSecurityIQ/Integrations/CommvaultSecurityIQ/CommvaultSecurityIQ.yml, Packs/CommvaultSecurityIQ/ReleaseNotes/1_1_2.md, Packs/CommvaultSecurityIQ/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12345)
=> update commvault docker image tag

Packs/CommonScripts/ReleaseNotes/1_17_2.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44516)
=> Parse emails update docker image

Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml, Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml, Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml, Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml, Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
Packs/CommunityCommonScripts/Scripts/MarkdownToHTML/MarkdownToHTML.yml
Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
Packs/Symantec_Messaging_Gateway/Integrations/SymantecMessagingGateway/SymantecMessagingGateway.yml
Packs/Use_Case_Builder/Scripts/UseCaseBuilderMarkdownToHTML/UseCaseBuilderMarkdownToHTML.yml
Packs/WebScraper/Scripts/WebScraper/WebScraper.yml
=> demisto/bs4-py3:1.0.0.117152 | 0-100 | PR batch #1/1

Packs/CloudIncidentResponse/Scripts/ExtractIndicatorsCloudLogging/ExtractIndicatorsCloudLogging.yml, Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
Packs/CloudIncidentResponse/Scripts/ExtractIndicatorsCloudLogging/ExtractIndicatorsCloudLogging.yml
Packs/CommonScripts/Scripts/ParseHTMLIndicators/ParseHTMLIndicators.yml
=> demisto/bs4-tld:1.0.0.117606 | 0-100 | PR batch #1/1

Packs/CortexAttackSurfaceManagement/Playbooks/Cortex_ASM_-_Remediation_Guidance.yml, Packs/CortexAttackSurfaceManagement/ReleaseNotes/1_7_61.md, Packs/CortexAttackSurfaceManagement/pack_metadata.json
[external pull request](https://github.com/demisto/content/pull/37244)
@BigEasyJ
[EXPANDR-11761](https://jira-dc.paloaltonetworks.com/browse/EXPANDR-11761)
Update playbook to set priority, rule description, and category fields even if remediation guidance is not provided from API endpoint.
=> [ASM] EXPANDR-11761 - Update Remediation Guidance

Packs/Securonix/Classifiers/classifier-Securonix_Incident_-_Incoming_Mapper.json, Packs/Securonix/IncidentFields/incidentfield-Securonix-Policy-Stages.json, Packs/Securonix/Integrations/Securonix/README.md, Packs/Securonix/Integrations/Securonix/Securonix.py, Packs/Securonix/Integrations/Securonix/Securonix.yml, Packs/Securonix/Integrations/Securonix/Securonix_test.py, Packs/Securonix/Integrations/Securonix/test_data/response_constants.py, Packs/Securonix/Integrations/Securonix/test_data/result_constants.py, Packs/Securonix/Layouts/layoutscontainer-Securonix_Incident_information.json, Packs/Securonix/ReleaseNotes/2_0_23.md, Packs/Securonix/pack_metadata.json
[external pull request](https://github.com/demisto/content/pull/37554)
@scnx-knathani
- Added support for the "Policy Stages" field for the fetch Securonix Incident.
- Updated the compatibility. Securonix XSOAR integration version 2.0.23 is compatible with 6.4_Nov2024_R2 onwards.
=> Securonix Release 2.0.23

.github/content_roles.json
=> Updae contribution reviewers

Packs/Zoom/Integrations/Zoom/README.md, Packs/Zoom/ReleaseNotes/1_6_18.md, Packs/Zoom/pack_metadata.json
n/a
There were some big issues with the formatting for the app setup instructions, and some typos. And one incorrect instruction where we said a certain option is required on X8, which it is not, so I removed that. I think this doc needs a bigger update of its content due to changes in the Zoom app marketplace, but this is a start to at least fix the formatting and make it easier to understand.
=> Fix README formatting/typos

Packs/CommonScripts/ReleaseNotes/1_17_7.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44005)
Updated the docker image to the latest tag `demisto/parse-emails:1.0.0.1791788` to fix html parsing issue from EML file.
=> ParseEmailFilesV2 - update docker

Packs/VMware/Integrations/VMware/VMware.yml, Packs/VMware/ReleaseNotes/1_2_11.md, Packs/VMware/pack_metadata.json, Packs/WindowsForensics/ReleaseNotes/1_0_8.md, Packs/WindowsForensics/Scripts/Etl2Pcap/Etl2Pcap.yml, Packs/WindowsForensics/pack_metadata.json, Packs/dnstwist/Integrations/dnstwist/dnstwist.yml, Packs/dnstwist/ReleaseNotes/1_1_14.md, Packs/dnstwist/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12380)
=> Aud demisto/auto update docker staging branch 81

validation_config.toml
=> add RN107 to warnings

Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.py, Packs/FeedThreatConnect/ReleaseNotes/2_1_25.md, Packs/FeedThreatConnect/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-44847)
=> ThreatConnect Feed - Fix Authorization header generation

Packs/Slack/.pack-ignore, Packs/Slack/Integrations/SlackV3/README.md, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/ReleaseNotes/3_5_4.md, Packs/Slack/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12316)
=> Deprecate permitted_notifications in SlackV3

Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.py, Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel.yml, Packs/CybleThreatIntel/Integrations/CybleThreatIntel/CybleThreatIntel_test.py, Packs/CybleThreatIntel/ReleaseNotes/2_0_24.md, Packs/CybleThreatIntel/pack_metadata.json
Sometimes, the server takes long to respond or gives unexpected response, so we have implemented a fix through that.
=> Connection timeout fix

.github/content_roles.json
=> Update the security reviewer

Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE.py, Packs/PrismaAccess/Integrations/PrismaSASE/PrismaSASE_test.py, Packs/PrismaAccess/ReleaseNotes/2_1_12.md, Packs/PrismaAccess/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12117)
=> Added a fix to the source_user parsing

Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_1_15.md, Packs/CrowdStrikeFalconStreamingV2/Scripts/CrowdStrikeStreamingPreProcessing/CrowdStrikeStreamingPreProcessing.yml, Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json, Packs/CyrenInboxSecurity/ReleaseNotes/1_1_16.md, Packs/CyrenInboxSecurity/Scripts/CyrenFindSimilarIncidents/CyrenFindSimilarIncidents.yml, Packs/CyrenInboxSecurity/Scripts/CyrenShowThreatIndicators/CyrenShowThreatIndicators.yml, Packs/CyrenInboxSecurity/pack_metadata.json, Packs/GroupIB_ThreatIntelligenceAttribution/ReleaseNotes/1_4_6.md, Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdate/GIBIncidentUpdate.yml, Packs/GroupIB_ThreatIntelligenceAttribution/Scripts/GIBIncidentUpdateIncludingClosed/GIBIncidentUpdateIncludingClosed.yml, Packs/GroupIB_ThreatIntelligenceAttribution/pack_metadata.json, Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_25.md, Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.yml, Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.yml, Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
=> revert docker image

Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.py, Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks_test.py, Packs/NozomiNetworks/ReleaseNotes/1_0_13.md, Packs/NozomiNetworks/pack_metadata.json
=> Nozomi fix broken proxy2

Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py, Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml, Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub_test.py, Packs/GooglePubSub/ReleaseNotes/1_1_5.md, Packs/GooglePubSub/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-140737
Removed message filter when ACK is enabled.
=> [Google PubSub] For ACK dont skip older messages

Tests/docker_native_image_config.json
=> ignore native image Darktrace

Packs/RsaNetWitnessPacketsAndLogs/ReleaseNotes/1_0_9.md, Packs/RsaNetWitnessPacketsAndLogs/pack_metadata.json
update the netwitness support
update support from xsoar to partner
=> Change netwitness support to partner

Packs/cyberark_AIM/README.md, Packs/cyberark_AIM/ReleaseNotes/1_0_21.md, Packs/cyberark_AIM/pack_metadata.json
Remove html tags from cyberark readme and convert to markdown
=> Remove html tags from cyberark readme and convert to markdown

Packs/RedCanary/Integrations/RedCanary/README.md, Packs/RedCanary/Integrations/RedCanary/RedCanary.py, Packs/RedCanary/ReleaseNotes/1_1_23.md, Packs/RedCanary/pack_metadata.json, Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45059
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-44428
The request was sent with data instead of params causing http requests to intermediately fail.
=> XSUP-44428 Red Canary - HTTP issue

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py, Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/Integrations/CortexCoreIR/README.md, Packs/Core/ReleaseNotes/3_2_10.md, Packs/Core/pack_metadata.json
fixes: None
Fixing terminate commands description.
=> fix description of terminate commands

Packs/CommonTypes/.pack-ignore, Packs/CommonTypes/Layouts/layoutscontainer-Tactic.json, Packs/CommonTypes/ReleaseNotes/3_8_1.md, Packs/CommonTypes/pack_metadata.json, Packs/Phishing/.pack-ignore
Just added an ignore to LO107.
=> Ignore_error

Packs/Base/ReleaseNotes/1_39_5.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json
https://github.com/demisto/dockerfiles/pull/34826
fixes: [CRTX-147336](https://jira-dc.paloaltonetworks.com/browse/CRTX-147336)
=> Release new base pack version

.github/content_roles.json
Update content_roles with new on call team.
=> Update content_roles with new on call team

.github/content_roles.json
Update the reviewers list with the correct users.
=> Update the reviewers list with the correct users

Packs/SymantecEndpointProtection/ParsingRules/SymantecEndpointProtection/SymantecEndpointProtection.xif, Packs/SymantecEndpointProtection/README.md, Packs/SymantecEndpointProtection/ReleaseNotes/1_1_15.md, Packs/SymantecEndpointProtection/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-148238)
=> XSUP-45343 - symantec ep parsing fix

Packs/KeeperSecurity/Integrations/KeeperSecurity/README.md, Packs/KeeperSecurity/ReleaseNotes/1_0_3.md, Packs/KeeperSecurity/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12535)
Changing the marketplace for keeper as there are no content items in xsoar.
=> Crtx 131860 keeper marketplace change

.github/content_roles.json
=> remove the lazy guy from the team

.github/CODEOWNERS
=> Change code owner for xdr

Packs/Veeam/.secrets-ignore, Packs/Veeam/Integrations/VeeamONERESTAPI/VeeamONERESTAPI.py, Packs/Veeam/Integrations/VeeamONERESTAPI/VeeamONERESTAPI_test.py, Packs/Veeam/ReleaseNotes/1_0_7.md, Packs/Veeam/pack_metadata.json
=> Veeam: Code functionality improvements

Packs/CommonScripts/ReleaseNotes/1_19_4.md, Packs/CommonScripts/Scripts/SetGridField/SetGridField.py, Packs/CommonScripts/pack_metadata.json
=> [SetGridField] MyPy In Docker

Packs/Mattermost/Integrations/MattermostV2/MattermostV2.py, Packs/Mattermost/Integrations/MattermostV2/MattermostV2.yml, Packs/Mattermost/ReleaseNotes/2_0_6.md, Packs/Mattermost/pack_metadata.json
=> [MattermostV2] MyPy In Docker

Packs/Lumu/Integrations/Lumu/Lumu.py, Packs/Lumu/Integrations/Lumu/Lumu.yml, Packs/Lumu/ReleaseNotes/1_0_24.md, Packs/Lumu/pack_metadata.json
=> [Lumu] MyPy In Docker

Packs/ReversingLabs_A1000/ReleaseNotes/2_4_2.md, Packs/ReversingLabs_A1000/Scripts/A1000FinalClassification/A1000FinalClassification.py, Packs/ReversingLabs_A1000/Scripts/A1000FinalClassification/A1000FinalClassification.yml, Packs/ReversingLabs_A1000/pack_metadata.json
=> [ReversingLabs_A1000] MyPy In Docker

Packs/QueryAI/Integrations/QueryAI/QueryAI.py, Packs/QueryAI/Integrations/QueryAI/QueryAI.yml, Packs/QueryAI/ReleaseNotes/1_0_13.md, Packs/QueryAI/pack_metadata.json
=> [QueryAI] MyPy In Docker

Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.py, Packs/FortinetFortiwebVM/Integrations/FortinetFortiwebVM/FortinetFortiwebVM.yml, Packs/FortinetFortiwebVM/ReleaseNotes/2_0_9.md, Packs/FortinetFortiwebVM/pack_metadata.json
=> [Fortiweb VM] MyPy In Docker

Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.py, Packs/FortiSIEM/Integrations/FortiSIEMV2/FortiSIEMV2.yml, Packs/FortiSIEM/ReleaseNotes/2_0_40.md, Packs/FortiSIEM/pack_metadata.json
=> [FortiSIEMV2] MyPy In Docker

Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py, Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.yml, Packs/FreshDesk/ReleaseNotes/1_0_16.md, Packs/FreshDesk/pack_metadata.json
=> [FreshDesk] MyPy In Docker

Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.py, Packs/ApiModules/Scripts/CoreXQLApiModule/CoreXQLApiModule.yml, Packs/Core/ReleaseNotes/3_2_18.md, Packs/Core/pack_metadata.json, Packs/CortexXDR/ReleaseNotes/6_2_5.md, Packs/CortexXDR/pack_metadata.json
=> [CoreXQLApiModule] MyPy In Docker 

Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py, Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml, Packs/RubrikPolaris/ReleaseNotes/1_4_2.md, Packs/RubrikPolaris/pack_metadata.json
=> RubrikPolaris

Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.py, Packs/SafeBreach/Integrations/SafeBreach/SafeBreach.yml, Packs/SafeBreach/ReleaseNotes/1_4_5.md, Packs/SafeBreach/pack_metadata.json
=> [SafeBreach] MyPy In Docker

Packs/CommunityCommonScripts/ReleaseNotes/1_3_10.md, Packs/CommunityCommonScripts/Scripts/CreatePlbkDoc/CreatePlbkDoc.py, Packs/CommunityCommonScripts/pack_metadata.json
=> [CreatePlbkDoc] MyPy In Docker

Packs/VMware/Integrations/VMware/VMware.py, Packs/VMware/ReleaseNotes/1_2_12.md, Packs/VMware/pack_metadata.json
=> [VMware] MyPy In Docker

Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/README.md, Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/ReliaQuestGreyMatterDRPEventCollector.py, Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/ReliaQuestGreyMatterDRPEventCollector.yml, Packs/DigitalShadows/Integrations/ReliaQuestGreyMatterDRPEventCollector/command_examples, Packs/DigitalShadows/ReleaseNotes/2_0_5.md, Packs/DigitalShadows/pack_metadata.json
=> [ReliaQuestGreyMatterDRPEventCollector] MyPy In Docker

Packs/qualys/Integrations/Qualysv2/Qualysv2.py, Packs/qualys/Integrations/Qualysv2/Qualysv2.yml, Packs/qualys/ReleaseNotes/3_1_4.md, Packs/qualys/pack_metadata.json
=> [Qualysv2] MyPy In Docker

Packs/AccentureCTI/Playbooks/playbook-ACTI_Vulnerability_Enrichment_README.md
=> AccentureCTI fixed image path

Packs/FeedCognyteLuminar/Integrations/CognyteLuminar/CognyteLuminar.py, Packs/FeedCognyteLuminar/Integrations/CognyteLuminar/CognyteLuminar.yml, Packs/FeedCognyteLuminar/ReleaseNotes/1_0_7.md, Packs/FeedCognyteLuminar/pack_metadata.json, Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.py, Packs/FidelisEndpoint/Integrations/FidelisEndpoint/FidelisEndpoint.yml, Packs/FidelisEndpoint/ReleaseNotes/1_0_8.md, Packs/FidelisEndpoint/pack_metadata.json, Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.py, Packs/FireEyeHX/Integrations/FireEyeHXv2/FireEyeHXv2.yml, Packs/FireEyeHX/ReleaseNotes/2_3_17.md, Packs/FireEyeHX/pack_metadata.json, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml, Packs/FreshworksFreshservice/ReleaseNotes/1_0_28.md, Packs/FreshworksFreshservice/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Fix Pylint errors in F packs
=> Fix Pylint errors in F packs

Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.py, Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml, Packs/IBMResilientSystems/ReleaseNotes/1_2_1.md, Packs/IBMResilientSystems/pack_metadata.json, Packs/Infoblox/Integrations/Infoblox/Infoblox.py, Packs/Infoblox/ReleaseNotes/1_1_5.md, Packs/Infoblox/pack_metadata.json, Packs/IronDefense/Integrations/IronDefense/IronDefense.py, Packs/IronDefense/Integrations/IronDefense/IronDefense.yml, Packs/IronDefense/ReleaseNotes/1_1_32.md, Packs/IronDefense/pack_metadata.json, Packs/IronPort/Integrations/CiscoEmailSecurityApplianceIronPortV2/CiscoEmailSecurityApplianceIronPortV2.py, Packs/IronPort/ReleaseNotes/2_1_1.md, Packs/IronPort/pack_metadata.json, Packs/Jira/Integrations/JiraV3/JiraV3.py, Packs/Jira/Integrations/JiraV3/JiraV3.yml, Packs/Jira/ReleaseNotes/3_2_12.md, Packs/Jira/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Fix Pylint errors in I + J packs
=> Fix Pylint errors in I + J packs

Packs/ML/ReleaseNotes/1_4_19.md, Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.py, Packs/ML/Scripts/HashIncidentsFields/HashIncidentsFields.yml, Packs/ML/pack_metadata.json, Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.py, Packs/Malwarebytes/Integrations/Malwarebytes/Malwarebytes.yml, Packs/Malwarebytes/ReleaseNotes/1_1_20.md, Packs/Malwarebytes/pack_metadata.json, Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.py, Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense.yml, Packs/McAfee_Advanced_Threat_Defense/Integrations/McAfee_Advanced_Threat_Defense/McAfee_Advanced_Threat_Defense_test.py, Packs/McAfee_Advanced_Threat_Defense/ReleaseNotes/1_0_30.md, Packs/McAfee_Advanced_Threat_Defense/pack_metadata.json, Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.py, Packs/MinervaLabsAntiEvasionPlatform/Integrations/MinervaLabsAntiEvasionPlatform/MinervaLabsAntiEvasionPlatform.yml, Packs/MinervaLabsAntiEvasionPlatform/ReleaseNotes/1_0_12.md, Packs/MinervaLabsAntiEvasionPlatform/pack_metadata.json, Packs/MitreCaldera/ReleaseNotes/1_0_8.md, Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.py, Packs/MitreCaldera/Scripts/CalderaPopulateAgents/CalderaPopulateAgents.yml, Packs/MitreCaldera/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Fix Pylint errors in M packs.
=> Fix Pylint errors in M packs

Tests/conf.json
Adding tpbs that are waiting for credentials or to be fixed to the skip section in conf.json
=> Adding tpbs to skip

Packs/Okta/Integrations/Okta_IAM/Okta_IAM.py, Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml, Packs/Okta/ReleaseNotes/3_3_10.md, Packs/Okta/pack_metadata.json, Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.py, Packs/OpenSourceVulnerabilities/Integrations/OSV/OSV.yml, Packs/OpenSourceVulnerabilities/ReleaseNotes/1_0_4.md, Packs/OpenSourceVulnerabilities/pack_metadata.json, Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM.py, Packs/Oracle_IAM/Integrations/OracleIAM/OracleIAM.yml, Packs/Oracle_IAM/ReleaseNotes/1_0_26.md, Packs/Oracle_IAM/pack_metadata.json, Tests/conf.json
relates: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-11651)
Fix Pylint errors in O packs
=> Fix Pylint errors in O packs

Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector.py, Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponseEventCollector/ProofpointThreatResponseEventCollector_test.py, Packs/ProofpointThreatResponse/ReleaseNotes/2_0_20.md, Packs/ProofpointThreatResponse/pack_metadata.json
fixed: https://jira-dc.paloaltonetworks.com/browse/XSUP-44715
Fixed an issue where some events was fetched multiple times.
=> ProofpointThreatResponseEventCollector: fixed bug in fetch events

Packs/Core/Playbooks/playbook-Ransomware_Advanced_Analysis_README.md, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Block_File_README.md, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Run_script_README.md, Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_disconnected_endpoints_README.md, Packs/CortexXDR/Playbooks/playbook-JOB_-_Cortex_XDR_query_endpoint_device_control_violations_README.md, Packs/CortexXDR/README.md
=> Change all paths in Readme and Description file- core packs

Packs/RemoteAccess/Integrations/RemoteAccessv2/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12582
Improved documentation.
=>  Fix remote-access documentation

.pre-commit-config_template.yaml, nightly_ruff.toml, pyproject.toml
=> Revert "Update ruff version to 0.8.0"

Packs/CrowdStrikeFalcon/Layouts/layoutscontainer-CrowdStrike_Falcon_Layout.json, Packs/CrowdStrikeFalcon/Playbooks/playbook-Command_and_Scripting_Interpreter.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_6.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: N.A.
- Fixed a bug with the conditional task that responsible for the creation of a new incident.
- Added endpoint information to the layout under the Investigaiton tab.
=> Fix-cs-t1059-playbook

Packs/Troubleshoot/ReleaseNotes/2_1_7.md, Packs/Troubleshoot/Scripts/TroubleshootExecutePlaybookByAlertQuery/TroubleshootExecutePlaybookByAlertQuery.py, Packs/Troubleshoot/pack_metadata.json
Fix additional ruff error that was found during a gitlab [nightly](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/1987165) run with the branch "fix_ruff_warnings" ([pr](https://github.com/demisto/content/pull/38143)).
=> Fix additional ruff errors

Packs/NIST/README.md
relates: [CIAC-10611](https://jira-dc.paloaltonetworks.com/browse/CIAC-10611)
=> 10611 finshes part 3 1

Packs/Campaign/ReleaseNotes/3_4_16.md, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py, Packs/Campaign/pack_metadata.json
=> [FindEmailCampaign] MyPy In Docker

Packs/OnboardingIntegration/Playbooks/playbook-PhishingDemo-Onboarding_README.md, Packs/OpenCTI/Playbooks/OpenCTI_-_Create_Indicator_README.md
relates: [CIAC-10611](https://jira-dc.paloaltonetworks.com/browse/CIAC-10611)
=> 10611 finshes part 3_3

Packs/ProtectWise/Integrations/ProtectWise/README.md
=> Fix protectwise uploaded file README image

Packs/Microsoft365Defender/Classifiers/classifier-Microsoft_365_Defender_-_Incoming_Mapper.json, Packs/Microsoft365Defender/ReleaseNotes/4_5_40.json, Packs/Microsoft365Defender/ReleaseNotes/4_5_40.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45575
Fixing an issue where the `severity` incident field was not correctly mapped.
=> Fix Microsoft Defender incoming mapper / XSUP-45575

Packs/Nmap/Integrations/Nmap/Nmap.yml, Packs/Nmap/ReleaseNotes/1_2_6.md, Packs/Nmap/pack_metadata.json
=> AUD-demisto/auto_update_docker_staging_branch_91

Packs/CofenseTriage/Integrations/CofenseTriagev2/CofenseTriagev2_test.py, Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_29.md, Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py, Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
=> Fix a ruff error

Packs/Axonius/Integrations/Axonius/Axonius.yml, Packs/Axonius/ReleaseNotes/1_2_6.md, Packs/Axonius/pack_metadata.json
Axonius image update to 1.1.0.1993107
=> Axonius image update

Packs/Campaign/ReleaseNotes/3_4_18.md, Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.yml, Packs/Campaign/pack_metadata.json, Packs/Phishing/ReleaseNotes/3_6_33.md, Packs/Phishing/Scripts/FindDuplicateEmailIncidents/FindDuplicateEmailIncidents.yml, Packs/Phishing/pack_metadata.json
=> Update sklearn image tags

Tests/conf.json
=> Reduce_testpb_timeout

Packs/CommonScripts/ReleaseNotes/1_19_11.md, Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.js, Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.yml, Packs/CommonScripts/Scripts/EmailAskUserResponse/README.md, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45386
Add a prefix argument to remove known prefix in messages.
=> [EmailAskUserResponse] Add Prefix arg

.github/content_roles.json
=> Revert "remove the lazy guy from the team"

Packs/Venafi/TestPlaybooks/VenafiV2_Test.yml, Tests/conf.json
=> Fix VenafiV2_Test

Packs/Campaign/Scripts/FindEmailCampaign/FindEmailCampaign.py, Tests/conf.json
Related: https://jira-dc.paloaltonetworks.com/browse/CIAC-11720
The `Detect & Manage Phishing Campaigns - Test` TPB failed with an error "Missing script SearchIncidentsV2 for Task Search for a campaign incident",  add this script to the conf.
=> missing-script-fix

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py, Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/ReleaseNotes/3_2_23.md, Packs/Core/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/UVEM-1321
Underlying API was changed, see more information in the ticket
=> [CORE] Fix Underlying API

Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection.yml, Packs/PANWComprehensiveInvestigation/Playbooks/Palo_Alto_Networks_-_Hunting_And_Threat_Detection_README.md, Packs/PANWComprehensiveInvestigation/ReleaseNotes/1_3_27.md, Packs/PANWComprehensiveInvestigation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45706
Added a fix so that the query in Prisma will support multiple IP's.
=> Fix for query in Palo Alto Networks - Hunting And Threat Detection playbook

Packs/CommonScripts/ReleaseNotes/1_19_15.md, Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.js, Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.yml, Packs/CommonScripts/Scripts/EmailAskUserResponse/README.md, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45386
Added a suffix argument to remove known terms from the response.
=> [EmailAskUserResponse] Add Suffix arg

Packs/FeedMISPThreatActors/pack_metadata.json, Packs/FreeFeeds/ReleaseNotes/1_0_1.md, Packs/FreeFeeds/pack_metadata.json
1. Added the "Plug & Fetch" tag.
2. Added the pack to the "Free Feeds" pack.
=> TIM - Feed MISP Threat Actors - Added tag

Packs/XQLDSHelper/pack_metadata.json
=> Fix description for xqld packmetadata

Tests/conf.json
Due to [CRTX-149225](https://jira-dc.paloaltonetworks.com/browse/CRTX-149225) and the upcoming of Exabeam Data Lake EOL https://community.exabeam.com/s/article/End-of-Life#:~:text=July%2031%2C%202021-,July%2031%2C%202026%C2%A0,-%E2%80%AF%C2%A0 , I am moving the test playbook to the skipped section.
=> Skip ExabeamDataLake-test in conf.json

Packs/Whois/Integrations/Whois/Whois.py, Packs/Whois/ReleaseNotes/1_5_23.md, Packs/Whois/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46042)
=> whois: fix ip command country_code in response

Packs/CyberArkEPV/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-6777)
=> CyberArkEPV README Update

Packs/Salesforce/ParsingRules/SalesforceParsingRules/SalesforceParsingRules.xif, Packs/Salesforce/ReleaseNotes/2_1_3.md, Packs/Salesforce/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-153264)
=> Salesforce Parsing Update

Packs/AnythingLLM/README.md
=> fixed parsing error in readme

Packs/AMP/Integrations/AMPv2/AMPv2.yml, Packs/AMP/ReleaseNotes/2_1_7.md, Packs/AMP/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-46124
Editing the file command's docs for supporting only SHA256
=> Cisco AMPv2 - edit 'file' command's description

Packs/Slack/Integrations/SlackV3/SlackV3.py, Packs/Slack/Integrations/SlackV3/SlackV3.yml, Packs/Slack/ReleaseNotes/3_5_9.md, Packs/Slack/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45179
Edit regex of the user ID, and the description in get-user-details.
=> Slack V3 - edit regex and description in get-user-details

Packs/Zoom/Integrations/Zoom/README.md, Packs/Zoom/Scripts/ZoomAsk/README.md
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12379
Fixes.
=> CIAC-12379_2

Packs/Squid/ModelingRules/Squid/Squid.yml, Packs/Squid/ParsingRules/Squid/Squid.yml, Packs/Squid/ReleaseNotes/1_0_5.md, Packs/Squid/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12402)
=> YML Correction PR

validation_config.toml
=> revert rm108

Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.py, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/FreshworksFreshservice.yml, Packs/FreshworksFreshservice/Integrations/FreshworksFreshservice/README.md, Packs/FreshworksFreshservice/ReleaseNotes/1_0_29.md, Packs/FreshworksFreshservice/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46022)
=> Freshservice: add description fetch

Packs/NozomiNetworks/Integrations/NozomiNetworks/NozomiNetworks.yml, Packs/NozomiNetworks/README.md, Packs/NozomiNetworks/ReleaseNotes/1_0_16.md, Packs/NozomiNetworks/pack_metadata.json
In this PR we extend  the app description and improve the README after making the app compatible also with Nozomi Networks Vanatge product
no issues related
In this PR we extend  the app description and improve the README after making the app compatible also with Nozomi Networks Vanatge product
=> Nozomi improve app description and README for Vantage

Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/GoogleChronicleBackstory.yml, Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md, Packs/GoogleChronicleBackstory/ReleaseNotes/4_1_3.md, Packs/GoogleChronicleBackstory/pack_metadata.json
- Updated documentation for the "gcb-udm-search" command for the API rate limit.
=> Chronicle Release 4.1.3

Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12581
add timeout from 160 (default) to 170.
=> add timeout - CIAC-12581

Packs/LinuxEventsCollection/ParsingRules/LinuxEventsCollectionParsingRules/LinuxEventsCollectionParsingRules.xif, Packs/LinuxEventsCollection/ReleaseNotes/1_0_15.md, Packs/LinuxEventsCollection/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46487)
=> XSUP-46487 - Linux Parsing Rule Update

Packs/CommonScripts/ReleaseNotes/1_19_19.md, Packs/CommonScripts/Scripts/EmailAskUserResponse/EmailAskUserResponse.js, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-46494
fixed a syntax error in the script.
=> [EmailsAskUserReponse] Fix arg.suffix

Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py, Packs/AlibabaActionTrail/ReleaseNotes/1_1_4.md, Packs/AlibabaActionTrail/pack_metadata.json
relates: [XSUP-45571](https://jira-dc.paloaltonetworks.com/browse/XSUP-45571).
Added a detailed debug log message for error occurrences.
=> Alibaba Cloud Trail Event Collector - Added debug log in case of an error

Packs/CommonScripts/ReleaseNotes/1_19_20.md, Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml, Packs/CommonScripts/pack_metadata.json
fixes:[link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46320)
=> ParseEmailFilesV2: Fixed an issue where some EML files were incorrectly decoded.

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml, Packs/QRadar/ReleaseNotes/2_5_10.md, Packs/QRadar/ReleaseNotes/2_5_11.md, Packs/QRadar/pack_metadata.json
Reverts demisto/content#38242
fixes: [XSUP-45854](https://jira-dc.paloaltonetworks.com/browse/XSUP-45854)
=> Revert "add encode to filter arg to qradar-domain-list"

Packs/SecurityScorecard/Integrations/SecurityScorecard/README.md, Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.py, Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard.yml, Packs/SecurityScorecard/Integrations/SecurityScorecard/SecurityScorecard_test.py, Packs/SecurityScorecard/Integrations/SecurityScorecard/command_examples.txt, Packs/SecurityScorecard/Integrations/SecurityScorecard/test_data/data.json, Packs/SecurityScorecard/ReleaseNotes/1_0_11.md, Packs/SecurityScorecard/pack_metadata.json
Adds a new command !securityscorecard-alert-rules-list
Updates alerts list table columns for portfolio filtered list
=> Add new command securityscorecard-alert-rules-list

Packs/SolarWinds/Integrations/SolarWinds/SolarWinds.py, Packs/SolarWinds/Integrations/SolarWinds/SolarWinds.yml, Packs/SolarWinds/Integrations/SolarWinds/SolarWinds_test.py, Packs/SolarWinds/ReleaseNotes/1_0_18.md, Packs/SolarWinds/pack_metadata.json
fixes: [XSUP-46564](https://jira-dc.paloaltonetworks.com/browse/XSUP-46564)
Add `Port` parameter to the `SolarWinds` integration, replacing hard-coded port defined in the integration's code-base.
=> [SolarWinds] Add `Port` parameter

Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.py, Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector.yml, Packs/PrismaSaasSecurity/Integrations/SaasSecurityEventCollector/SaasSecurityEventCollector_test.py, Packs/PrismaSaasSecurity/ReleaseNotes/2_0_37.md, Packs/PrismaSaasSecurity/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46676)
=> XSUP 46676/fixed error message 400

Packs/Base/ReleaseNotes/1_39_19.md, Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.yml, Packs/Base/pack_metadata.json, Packs/CommonScripts/ReleaseNotes/1_19_23.md, Packs/CommonScripts/Scripts/AquatoneDiscoverV2/AquatoneDiscoverV2.yml, Packs/CommonScripts/Scripts/VerifyJSON/VerifyJSON.yml, Packs/CommonScripts/pack_metadata.json, Packs/CommunityCommonScripts/ReleaseNotes/1_3_15.md, Packs/CommunityCommonScripts/Scripts/CalculateTimeSpan/CalculateTimeSpan.yml, Packs/CommunityCommonScripts/Scripts/VersionEqualTo/VersionEqualTo.yml, Packs/CommunityCommonScripts/Scripts/VersionGreaterThan/VersionGreaterThan.yml, Packs/CommunityCommonScripts/Scripts/VersionLessThan/VersionLessThan.yml, Packs/CommunityCommonScripts/pack_metadata.json, Packs/Infocyte/Integrations/Infocyte/Infocyte.yml, Packs/Infocyte/ReleaseNotes/1_0_7.md, Packs/Infocyte/pack_metadata.json, Packs/Snowflake/Integrations/Snowflake/Snowflake.yml, Packs/Snowflake/ReleaseNotes/1_0_7.md, Packs/Snowflake/pack_metadata.json
=> Aud demisto/auto update docker staging branch 97

Packs/Phishing/ReleaseNotes/3_6_36.md, Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.py, Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.yml, Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity_test.py, Packs/Phishing/pack_metadata.json
fixes: [XSUP-46252](https://jira-dc.paloaltonetworks.com/browse/XSUP-46252)
=> Updated check email authenticity script to handle spf formats

Packs/CiscoISR/ParsingRules/CiscoISR/CiscoISR.xif, Packs/CiscoISR/ReleaseNotes/1_0_6.md, Packs/CiscoISR/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-155798)
=> CISCO ISR Parsing Update

.hooks/bootstrap, .hooks/install.python-poetry.py, Tests/secrets_white_list.json
=> Fix poetry install

.github/content_roles.json
=> Contrib assignees

Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.py, Packs/TAXIIServer/ReleaseNotes/2_1_4.md, Packs/TAXIIServer/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46766)
=> bug - TAXII server errors are spamming the fetch history

Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Password_Spray.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_11.md, Packs/CortexResponseAndRemediation/pack_metadata.json
=> added continue on error

Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py, Packs/ProofpointThreatResponse/ReleaseNotes/2_0_23.md, Packs/ProofpointThreatResponse/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45837
Improved performance of fetching alerts in the **proofpoint-tr-verify-quarantine** command.
=> Improved performance of fetching alerts in the **proofpoint-tr-verify-quarantine** command.

Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py, Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_2.md, Packs/SymantecEndpointSecurity/pack_metadata.json
=> Improve symantec ses event collector

Packs/PowershellRemoting/Integrations/PowerShellRemoting/PowerShellRemoting.yml, Packs/PowershellRemoting/Integrations/PowerShellRemoting/README.md, Packs/PowershellRemoting/ReleaseNotes/1_0_7.md, Packs/PowershellRemoting/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-45928
=> Update documentation for Pwsh Remoting

Config/core_packs_platform_list.json
Adding `FiltersAndTransformers`to platform corepacks list as it is required pack by other corepacks
=> Add FiltersAndTransformers to platform corepacks list

Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py, Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_3.md, Packs/SymantecEndpointSecurity/pack_metadata.json
=> fix symantec ses delimiter bug

Packs/Sigma/ReleaseNotes/1_0_2.md, Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.py, Packs/Sigma/Scripts/ImportSigmaRulesFromZIP/ImportSigmaRulesFromZIP.yml, Packs/Sigma/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-46987)
=> bug - problem with parsing the timeout value in the script .yml

Packs/PAN-OS/Integrations/Panorama/Panorama.py, Packs/PAN-OS/Integrations/Panorama/Panorama.yml, Packs/PAN-OS/Integrations/Panorama/Panorama_test.py, Packs/PAN-OS/ReleaseNotes/2_3_5.md, Packs/PAN-OS/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47170
=> Fix panorama get jobs command

Packs/CTIX/Integrations/CTIXv3/CTIXv3.py, Packs/CTIX/Integrations/CTIXv3/CTIXv3.yml, Packs/CTIX/Integrations/CTIXv3/CTIXv3_test.py, Packs/CTIX/ReleaseNotes/2_2_18.md, Packs/CTIX/pack_metadata.json
* Fix: :Remove tags from indicator
* lint check fix
* fixing release note suggestion
* adding section order
* adding release notes
* fixing pre-checks
* updating with suggested release note
=> Fix:Remove tags from indicator (#38698)

Packs/VirusTotal/Integrations/VirusTotalV3/README.md, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py, Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_url.json, Packs/VirusTotal/Integrations/VirusTotalV3/test_data/private_url_results.json, Packs/VirusTotal/ReleaseNotes/2_7_0.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Private URL scanning

Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py, Packs/Akamai_SIEM/ReleaseNotes/1_2_3.md, Packs/Akamai_SIEM/pack_metadata.json
fixes: [XSUP-47403](https://jira-dc.paloaltonetworks.com/browse/XSUP-47403)
=> fixed an issue where auto offset reset didnt work for Akamai_SIEM

Packs/FeedRSS/.pack-ignore, Packs/FeedRSS/Playbooks/RSS_Create_Indicators_From_Report_README.md, Packs/FeedRSS/ReleaseNotes/1_0_17.md, Packs/FeedRSS/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47121
Enhanced documentation and provided workaround for XSIAM users.
=> Add tag info to Feed RSS playbook docs

Packs/CortexResponseAndRemediation/Playbooks/playbook-Successful_guest_user_invitation.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_16.md, Packs/CortexResponseAndRemediation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-12966
Updated the closing reasons and notes to align with playbook evidence and actions.
=> Guest playbook close reason fix

Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.py, Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.yml, Packs/Darktrace/ReleaseNotes/3_0_15.md, Packs/Darktrace/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-46743
=> Ip-add-proxy-support-to-send_events_to_xsiam

Packs/PrismaAccess/README.md
Fixed the Prisma Access README pack
Before fix:
After fix:
=> Fixed Prisma Access README pack

Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector.py, Packs/ProofpointEmailSecurity/Integrations/ProofpointEmailSecurityEventCollector/ProofpointEmailSecurityEventCollector_test.py, Packs/ProofpointEmailSecurity/ReleaseNotes/1_0_9.md, Packs/ProofpointEmailSecurity/pack_metadata.json
=> fix get-last-run-results command

Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py, Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml, Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md, Packs/CrowdStrikeFalconX/ReleaseNotes/1_2_40.md, Packs/CrowdStrikeFalconX/pack_metadata.json, Tests/conf.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47626
CrowdStrike removed the Ubuntu 16 image and are now telling customers to use the Ubuntu 20 image. Changed the prefilled list of options to use the new image.
=> Remove Deprecated Env ID from CS FalconX

Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif, Packs/MicrosoftEntraID/ReleaseNotes/1_0_9.md, Packs/MicrosoftEntraID/pack_metadata.json
Support all non-alphanumeric or underscore characters) in the 'parsed_fields'.
=> Azure AD Audit - 'parsed_fields' enhancement

.github/workflows/close_jira_issue_by_pr_merge.yml, .github/workflows/link_edited_pr_to_jira_issue.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13019)
Updated deprecated action/cache from using v2 to using v4 to allow jira pr linking
=> changed the actions/cache from deprecated version to v4

Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.py, Packs/Rapid7AppSec/Integrations/Rapid7AppSec/Rapid7AppSec.yml, Packs/Rapid7AppSec/ReleaseNotes/1_0_6.md, Packs/Rapid7AppSec/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-47058)
Before change:
After change:
=> bug - Incorrect .yml file type 9 hidden field

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml, Packs/SplunkPy/ReleaseNotes/3_2_4.md, Packs/SplunkPy/pack_metadata.json
fixes: [XSUP-46047](https://jira-dc.paloaltonetworks.com/browse/XSUP-46047).
Splunkpy -  improved the description of the timezone parameter.
=> Splunkpy -  improved the description of the timezone parameter

Packs/ForcepointDLP/ParsingRules/ForcepointDLP/ForcepointDLP.xif, Packs/ForcepointDLP/ReleaseNotes/1_0_11.json, Packs/ForcepointDLP/ReleaseNotes/1_0_11.md, Packs/ForcepointDLP/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47557
fixing the parsing rule target dataset
=> Fix focepoint dlp dataset

Packs/CortexResponseAndRemediation/Playbooks/playbook-Exchange_User_Mailbox_Forwarding.yml, Packs/CortexResponseAndRemediation/Playbooks/playbook-Successful_guest_user_invitation.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Exchange_User_Mailbox_Forwarding_Test.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Successful_guest_user_invitation_Test.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_21.md, Packs/CortexResponseAndRemediation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13026
Adding continue on error for enrichment tasks.
=> Exchange user forwarding + guest user invite fix

Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-CampaignReport.json, Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ExecutiveBriefReport.json, Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-MalwareReport.json, Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ThreatActorReport.json, Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-VulnerabilityReport.json, Packs/ThreatIntelReports/ReleaseNotes/1_0_22.md, Packs/ThreatIntelReports/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-155709
relates: https://jira-dc.paloaltonetworks.com/browse/CRTX-127292
Change Canvas tabs in Threat Intel layouts (Added in https://github.com/demisto/content/pull/36021) to hidden.
=> [CRTX-155709] Change canvas tab in threat intel layouts to hidden

Packs/QRadar/Playbooks/playbook-QRadar_-_Get_Offense_Logs.yml, Packs/QRadar/ReleaseNotes/2_5_12.md, Packs/QRadar/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-45968)
=> QRadar Playbook - Get Offense Logs

Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.py, Packs/JamfProtect/Integrations/JamfProtectEventCollector/JamfProtectEventCollector.yml, Packs/JamfProtect/ReleaseNotes/1_2_1.md, Packs/JamfProtect/pack_metadata.json
fixes: [XSUP-47800](https://jira-dc.paloaltonetworks.com/browse/XSUP-47800)
Fixed an issue causing duplicate entries due to a mismatch in date formatting,
=> Jamf - Fixed audit duplicate entries

Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS_1_3/MicrosoftNPS_1_3.xif, Packs/MicrosoftNPS/ModelingRules/MicrosoftNPS_1_3/MicrosoftNPS_1_3_schema.json, Packs/MicrosoftNPS/ParsingRules/MicrosoftNPSParsingRules/MicrosoftNPSParsingRules.xif, Packs/MicrosoftNPS/ReleaseNotes/1_0_7.json, Packs/MicrosoftNPS/ReleaseNotes/1_0_7.md, Packs/MicrosoftNPS/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-47874
Changed dataset name to "microsoft_nps_raw".
Changed _product to "nps".
=> XSUP-47874-Microsoft-NPS

.github/github_workflow_scripts/run_secrets_detection_get_playbook_status.py
Update investigation URL to lead to Incident Info tab instead of the Work Plan tab.
=> Update Invetigation URL

Packs/OpenCTI/README.md, Packs/OpenCTI/ReleaseNotes/2_0_2.md, Packs/OpenCTI/pack_metadata.json
Start adoption of the OpenCTI pack by Filigran partner
=> Partner OpenCTI adoption

.github/content_roles.json
Added auto update docker image PRs reviewer
=> Add reviewer for AUD PRs

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml, Packs/MicrosoftGraphMail/ReleaseNotes/1_6_24.md, Packs/MicrosoftGraphMail/pack_metadata.json
Fixed the description of the importance argument in send-mail command- default is low.
=> Fix importance arg description

.github/workflows/pre-commit-reuse.yml, .github/workflows/pre-commit.yml
fixes: on-call issue
docker hub username/password fix
=> docker hub username/password fix

.github/workflows/protect-files.yml, .github/workflows/protect-infra-directories-contributions.yml, .github/workflows/review-release-notes.yml
fixes: tj-actions/changed-files@v46.0.1
tj-actions/changed-files@v46.0.1
=> tj-actions/changed-files@v46.0.1

Tests/conf.json
=> Ignore AIOps TPB

Packs/ProofpointIsolation/Integrations/ProofpointIsolationEventCollector/ProofpointIsolationEventCollector.py, Packs/ProofpointIsolation/Integrations/ProofpointIsolationEventCollector/ProofpointIsolationEventCollector.yml, Packs/ProofpointIsolation/ReleaseNotes/1_0_2.md, Packs/ProofpointIsolation/pack_metadata.json
Added more logs to integration and added 3 retries to http request.
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-48155)
=> Added logs and timeout to Proofpoint Isolation

Packs/CiscoSMA/README.md
Modified readme of cisco SMA to distinguish between syslog log collection and log collection via the integration itself.
=> Modified readme of CiscoSMA

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_16.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [XSUP-47461](https://jira-dc.paloaltonetworks.com/browse/XSUP-47461)
=> add use legacy API parameter to XSIAM

Packs/CitrixADC/ModelingRules/CitrixADC_1_3/CitrixADC_1_3.xif, Packs/CitrixADC/ReleaseNotes/1_0_5.md, Packs/CitrixADC/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-47986)
=> Citrix ADC Update

Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.py, Packs/HelloWorld/Integrations/HelloWorld/HelloWorld.yml, Packs/HelloWorld/Integrations/HelloWorldEventCollector/HelloWorldEventCollector.yml, Packs/HelloWorld/ReleaseNotes/3_0_17.md, Packs/HelloWorld/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-48515
=> Fix Typo HelloWorld integration

Packs/OktaASA/Integrations/OktaASA/OktaASA.yml, Packs/OktaASA/ReleaseNotes/1_0_1.md, Packs/OktaASA/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-48471
=> XSUP-48471/OktaASA - fix bug label description 

Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity.py, Packs/SymantecEndpointSecurity/Integrations/SymantecEndpointSecurity/SymantecEndpointSecurity_test.py, Packs/SymantecEndpointSecurity/ReleaseNotes/1_0_6.md, Packs/SymantecEndpointSecurity/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-45868
=> Ip-fix_symantec_ses_missing_schema

Config/core_packs_platform_list.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13164
update the Platform core packs, according the new structore
=> update the Platform core packs list

Packs/PAN-OS/Integrations/Panorama/README.md, Packs/PAN-OS/TestPlaybooks/playbook-palo_alto_panorama_test_pb.yml, Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-12340?filter=-1)
Making sure that Content support Panorama and Panorama FW version 11
=> Update Pan-OS playbook for supporting version 11

.github/content_roles.json
=> added itamar

Packs/Box/README.md, Packs/Box/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-3136)
=> Box Quick Update

Packs/CortexResponseAndRemediation/Playbooks/silent-playbook_Intense_SSO_failures_with_suspicious_characteristics.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_26.md, Packs/CortexResponseAndRemediation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13233
Fixed an issue where the Azure Risky Users task was querying data from the past 90 days instead of the intended 1 day.
=> Intense sso failures fix

Packs/EDL/ReleaseNotes/3_3_10.md, Packs/EDL/pack_metadata.json, Packs/FeedMitreAttackv2/ReleaseNotes/1_2_2.md, Packs/FeedMitreAttackv2/pack_metadata.json, Packs/GCP-Enrichment-Remediation/ReleaseNotes/1_1_22.md, Packs/GCP-Enrichment-Remediation/pack_metadata.json, Packs/GCP-IAM/ReleaseNotes/1_0_31.md, Packs/GCP-IAM/pack_metadata.json, Packs/GoogleCloudCompute/ReleaseNotes/1_1_17.md, Packs/GoogleCloudCompute/pack_metadata.json, Packs/HelloWorld/ReleaseNotes/3_0_18.md, Packs/HelloWorld/pack_metadata.json, Packs/Identity/ReleaseNotes/1_0_6.md, Packs/Identity/pack_metadata.json, Packs/Jira/ReleaseNotes/3_2_18.md, Packs/Jira/pack_metadata.json
=> fix corepacks for some packs

Packs/Nmap/Integrations/Nmap/Nmap.py, Packs/Nmap/Integrations/Nmap/Nmap.yml, Packs/Nmap/Integrations/Nmap/README.md, Packs/Nmap/ReleaseNotes/1_2_7.md, Packs/Nmap/pack_metadata.json
Deleted typo "ץ"
https://xsoar.pan.dev/docs/reference/integrations/nmap
=> nmap: typo

Packs/VMware/Integrations/VMware/README.md, Packs/VMware/Integrations/VMware/VMware.py, Packs/VMware/Integrations/VMware/VMware.yml, Packs/VMware/ReleaseNotes/1_2_14.md, Packs/VMware/pack_metadata.json
=> VMware typo

Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream.py, Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream.yml, Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/FeedIoCStream_test.py, Packs/GoogleThreatIntelligence/Integrations/FeedIoCStream/README.md, Packs/GoogleThreatIntelligence/ReleaseNotes/1_3_1.md, Packs/GoogleThreatIntelligence/pack_metadata.json
=> [Google Threat Intelligence] IoCStream cursor

.github/content_roles.json
Change contribution team to @mmhw @MosheEichler @DeanArbel
=> Add dean, menachem, moshe to contribs

Packs/CortexXDR/README.md
https://jira-dc.paloaltonetworks.com/browse/DOCS-7752
Added a note to the Cortex XDR pack that it is also compatible with Cortex XSIAM.
=> Added a note to the Cortex XDR pack

Packs/CommonTypes/IndicatorTypes/reputation-Attack_PatternV2.json, Packs/CommonTypes/ReleaseNotes/3_8_6.md, Packs/CommonTypes/pack_metadata.json
relates: https://jira-dc.paloaltonetworks.com/browse/XSUP-48083
Fixed an issue with capital letters in an indicator condition.
=> Attack pattern

Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM.py, Packs/Akamai_SIEM/Integrations/Akamai_SIEM/Akamai_SIEM_test.py, Packs/Akamai_SIEM/ReleaseNotes/1_2_7.md, Packs/Akamai_SIEM/pack_metadata.json
fixes: [XSUP-37947](https://jira-dc.paloaltonetworks.com/browse/XSUP-37947)
A test that checks whether the ; was encoded into %3B was added, here's a screenshot of the test BEFORE the fix. You can see that the test passes in the build when the pr includes the field.
=> Fix akamai offset url encode issue

.github/content_roles.json
[on-call] Update on-call developers
=> [on-call] Update on-call developers

Packs/Darktrace/Integrations/DarktraceEventCollector/DarktraceEventCollector.py, Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.py, Packs/Darktrace/Integrations/DarktraceMBs/DarktraceMBs.yml, Packs/Darktrace/ReleaseNotes/3_0_17.md, Packs/Darktrace/pack_metadata.json, Packs/Troubleshoot/ReleaseNotes/2_1_9.md, Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.py, Packs/Troubleshoot/Scripts/CertificatesTroubleshoot/CertificatesTroubleshoot.yml, Packs/Troubleshoot/pack_metadata.json, Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.py, Packs/remedy_SR/Integrations/remedy_SR/remedy_SR.yml, Packs/remedy_SR/ReleaseNotes/1_0_17.md, Packs/remedy_SR/pack_metadata.json
related: https://github.com/demisto/content/pull/39023
reverted changing the hash function
=> Revert hash function changes

.markdownlint-cli2.jsonc
=> ciac 11359 rules with 0 errors

Packs/MongoDB/CONTRIBUTORS.json, Packs/MongoDB/Integrations/MongoDB/MongoDB.py, Packs/MongoDB/Integrations/MongoDB/MongoDB.yml, Packs/MongoDB/ReleaseNotes/1_4_0.md, Packs/MongoDB/pack_metadata.json
Add authSource to MongoDB connection params
=> Feature: MongoDB add auth source connection param

Packs/Base/ReleaseNotes/1_39_25.md, Packs/Base/pack_metadata.json, Packs/DemistoRESTAPI/ReleaseNotes/1_3_70.md, Packs/DemistoRESTAPI/pack_metadata.json, Packs/FiltersAndTransformers/ReleaseNotes/1_2_92.md, Packs/FiltersAndTransformers/pack_metadata.json
=> Bump Base,DemistoRESTAPI,FiltersAndTransformers packs

Packs/HelloWorld/Integrations/HelloWorldEventCollector/HelloWorldEventCollector.py, Packs/HelloWorld/ReleaseNotes/3_0_19.md, Packs/HelloWorld/pack_metadata.json
=> HW event collector - adding logs

Packs/CommonReports/ReleaseNotes/1_0_10.md, Packs/CommonReports/pack_metadata.json, Packs/DefaultPlaybook/ReleaseNotes/2_0_13.md, Packs/DefaultPlaybook/pack_metadata.json, Packs/TIM_Processing/ReleaseNotes/1_1_28.md, Packs/TIM_Processing/pack_metadata.json, Packs/TIM_SIEM/ReleaseNotes/1_1_7.md, Packs/TIM_SIEM/pack_metadata.json
Bump version for the following packs:
`Packs/CommonReports,Packs/DefaultPlaybook,Packs/TIM_SIEM,Packs/TIM_Processing`
=> [on-call] bump packs

Packs/GroupIB_ThreatIntelligenceAttribution/.secrets-ignore
Blacklist validation failing on master, adding to secret ignore
https://gitlab.xdr.pan.local/xdr/cortex-content/infra/-/pipelines/3074842
=> Fix secret ignore

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml, Packs/ServiceNow/ReleaseNotes/2_7_13.md, Packs/ServiceNow/pack_metadata.json
[CXFR-77](https://jira-dc.paloaltonetworks.com/browse/CXFR-77)
Add support for a new ServiceNow system timestamp format that was previously unsupported, yyyy-MMM-dd.
=> ServiceNow integration - add support for new timestamp format

.github/github_workflow_scripts/handle_external_pr.py
=> Add a holiday message

Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.py, Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2.yml, Packs/CheckpointFirewall/Integrations/CheckPointFirewallV2/CheckPointFirewallV2_test.py, Packs/CheckpointFirewall/ReleaseNotes/2_3_30.md, Packs/CheckpointFirewall/pack_metadata.json
Fixed an issue in the command **checkpoint-add-host** where the context would have only the information of the last added host and not all the list.
=> CheckPoint Firewall - add-host small fix

Packs/PhishingURL/.secrets-ignore
Fixing https://panw-global.slack.com/archives/C03A9TJ57FT/p1744206385398569
=> Add to secret ignore

Packs/EDL/Integrations/EDL/EDL.py, Packs/EDL/Integrations/EDL/EDL.yml, Packs/EDL/ReleaseNotes/3_3_12.md, Packs/EDL/pack_metadata.json
Removed the log that can overwhelm the log bundle
=> EDL - remove excessive logs

Packs/ArcherRSA/Integrations/ArcherV2/ArcherV2.yml, Packs/ArcherRSA/ReleaseNotes/1_3_4.md, Packs/ArcherRSA/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-49272)
A depth argument was missing in the yml file for the update-record command
=> Xsup 49272

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/README.md, Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOneEventCollector/TrendMicroVisionOneEventCollector.yml, Packs/TrendMicroVisionOne/ReleaseNotes/4_2_3.md, Packs/TrendMicroVisionOne/pack_metadata.json
Updated the README to match the YML for the argument from_time.
=> Trend Micro Vision One - Documentation update

Packs/Core/Layouts/layoutscontainer-Default_platform_issues.json, Packs/Core/ReleaseNotes/3_2_32.md, Packs/Core/pack_metadata.json
fixes: [CRTX-166902](https://jira-dc.paloaltonetworks.com/browse/CRTX-166902)
=> fix default platform layout ID

Packs/CommonScripts/ReleaseNotes/1_19_43.md, Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV.py, Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV.yml, Packs/CommonScripts/Scripts/ExportIncidentsToCSV/ExportIncidentsToCSV_test.py, Packs/CommonScripts/pack_metadata.json
fixes: [XSUP-49148](https://jira-dc.paloaltonetworks.com/browse/XSUP-49148)
fixing the issue when no incidents or limit exceeded of incidents cause error to export data to csv
=> handle no incidents

Packs/DemistoRESTAPI/Integrations/CoreRESTAPI/CoreRESTAPI.js, Packs/DemistoRESTAPI/ReleaseNotes/1_3_71.md, Packs/DemistoRESTAPI/pack_metadata.json, Tests/conf.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-49293)
Updated the debug logs in the integration Core REST API.
=> XSUP-49293: Core Rest API - debug logs updating

Packs/3CXDesktopApp_Supply_Chain_Attack/pack_metadata.json, Packs/APIVoid/pack_metadata.json, Packs/AWS-AccessAnalyzer/pack_metadata.json, Packs/AWS-EKS/pack_metadata.json, Packs/AWS-SNS-Listener/pack_metadata.json, Packs/AWS-SQS/pack_metadata.json, Packs/AWS-SecurityHub/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk1)

Packs/Brandefense/pack_metadata.json, Packs/BreachNotification-US/pack_metadata.json, Packs/BreachRx/pack_metadata.json, Packs/BruteForce/pack_metadata.json, Packs/CTM360-CyberBlindspot/pack_metadata.json, Packs/CVE_2021_40444/pack_metadata.json, Packs/CVE_2021_44228/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk6)

Packs/AWS_ELB/pack_metadata.json, Packs/AWS_SystemManager/pack_metadata.json, Packs/AbnormalSecurity/pack_metadata.json, Packs/AbuseDB/pack_metadata.json, Packs/AcalvioShadowplex/pack_metadata.json, Packs/AccentureCTI_Feed/pack_metadata.json, Packs/ActiveMQ/pack_metadata.json, Packs/Active_Directory_Query/pack_metadata.json, Packs/AgariPhishingDefense/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk2)

Packs/AlienVault_OTX/pack_metadata.json, Packs/AlphaVantage/pack_metadata.json, Packs/AnsibleAlibabaCloud/pack_metadata.json, Packs/AnsibleAzure/pack_metadata.json, Packs/AnsibleCiscoIOS/pack_metadata.json, Packs/AnsibleCiscoNXOS/pack_metadata.json, Packs/AnsibleHetznerCloud/pack_metadata.json, Packs/AnsibleKubernetes/pack_metadata.json, Packs/AnsibleLinux/pack_metadata.json, Packs/AnsibleMicrosoftWindows/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk3)

.github/github_workflow_scripts/handle_external_pr.py
Removed the holiday message from newly created PRs
=> Removed the holiday message from newly created PRs

Packs/Code42/Integrations/Code42/Code42.yml, Packs/Code42/ReleaseNotes/6_0_4.md, Packs/Code42/pack_metadata.json
Updates the Incydr SDK version used by the content pack. Updates to the SDK have fixed some bugs that in rare cases could impact users of the content pack, updating the version will resolve those cases.
=> Update Incydr SDK version

Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService.xif, Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService_schema.json, Packs/AzureAppService/ReleaseNotes/1_0_2.md, Packs/AzureAppService/pack_metadata.json
fixes: [CRTX-169140](https://jira-dc.paloaltonetworks.com/browse/CRTX-169140)
Added casting for field ScStatus.
=> Azure app service modeling modification -  CRTX 169140

Packs/AutoFocus/pack_metadata.json, Packs/Automox/pack_metadata.json, Packs/AzureSecurityCenter/pack_metadata.json, Packs/AzureStorageQueue/pack_metadata.json, Packs/BeyondTrustPrivilegedRemoteAccess/pack_metadata.json, Packs/BeyondTrustRemoteSupport/pack_metadata.json, Packs/BeyondTrust_Password_Safe/pack_metadata.json, Packs/Binalyze/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk5)

Packs/Phishing/Playbooks/Get_Original_Email_-_EWS.yml, Packs/Phishing/ReleaseNotes/3_7_3.md, Packs/Phishing/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13552
Minor correction to the playbook description
=> Playbook description fix get original email

Tests/conf.json
skip tpbs as they blocked by:
https://jira-dc.paloaltonetworks.com/browse/CRTX-169825
https://jira-dc.paloaltonetworks.com/browse/CRTX-169003
=> skipped tpbs due to expired creds

Packs/OTRS/Integrations/OTRS/OTRS.py, Packs/OTRS/Integrations/OTRS/OTRS.yml, Packs/OTRS/Integrations/OTRS/OTRS_test.py, Packs/OTRS/ReleaseNotes/1_1_4.md, Packs/OTRS/pack_metadata.json
fixes: [XSUP-49452](https://jira-dc.paloaltonetworks.com/browse/XSUP-49452)
Fixing a small issue that is a result of enforcing the ruff formatter on the content repo.
=> XSUP-49452: OTRS a small fix

Packs/CommonScripts/ReleaseNotes/1_19_48.md, Packs/CommonScripts/Scripts/PreProcessImage/PreProcessImage.yml, Packs/CommonScripts/pack_metadata.json, Packs/SuspiciousDomainHunting/ReleaseNotes/1_0_13.md, Packs/SuspiciousDomainHunting/Scripts/Imagecompare/Imagecompare.yml, Packs/SuspiciousDomainHunting/Scripts/RasterizeImageOriginal/RasterizeImageOriginal.yml, Packs/SuspiciousDomainHunting/Scripts/RasterizeImageSuspicious/RasterizeImageSuspicious.yml, Packs/SuspiciousDomainHunting/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13562
update the processing-image-file tag in content items
=> processing-image-file: update docker tag

Tests/conf.json
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-13583
skipped open phish tpb as a result of being blocked by api access changes.
=> skipped tpbs due to api change

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/ReleaseNotes/3_2_38.md, Packs/Core/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-170303
=> CoreIR: remove default from `Retrieve File`  Quick Action

Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2.py, Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2.yml, Packs/ExtraHop/Integrations/ExtraHop_v2/ExtraHop_v2_test.py, Packs/ExtraHop/Integrations/ExtraHop_v2/README.md, Packs/ExtraHop/ReleaseNotes/2_3_1.md, Packs/ExtraHop/pack_metadata.json
- Updated the logic to validate the minimum required firmware version for **ExtraHop**.
=> ExtraHop Release 2.3.1

Packs/Lansweeper/.pack-ignore, Packs/Lansweeper/Integrations/Lansweeper/Lansweeper.py, Packs/Lansweeper/Integrations/Lansweeper/Lansweeper.yml, Packs/Lansweeper/Integrations/Lansweeper/test_data/ip_hunt_command_response.json, Packs/Lansweeper/ReleaseNotes/1_0_12.md, Packs/Lansweeper/pack_metadata.json
- Fixed an issue in the "*ls-ip-hunt*" and "*ls-mac-hunt*" commands for missing **"_id"** key in API response.
=> Lansweeper Release 1.0.12

Packs/CortexResponseAndRemediation/Playbooks/playbook-SSO_Authentication_With_Suspicious_Characteristics.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-SSO_Authentication_With_Suspicious_Characteristics_Test.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Suspicious_user_access_to_multiple_resources_via_SSO.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_39.md, Packs/CortexResponseAndRemediation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-13611
Fix the "Check for suspicious evidence" task in the "SSO Authentication With Suspicious Characteristics" playbook.
In addition, fix a small type in a silent playbook.
=> Fix sso with suspicious characterisitcs

Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser.py, Packs/GmailSingleUser/Integrations/GmailSingleUser/GmailSingleUser_test.py, Packs/GmailSingleUser/ReleaseNotes/1_4_13.md, Packs/GmailSingleUser/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-48656)
=> Add Lookback

Tests/conf.json
related: https://jira-dc.paloaltonetworks.com/browse/CIAC-13194
skipped saas security tpb as it's being blocked by SCA-8028.
=> skipped saas security tpb as its being blocked by SCA-8028

Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.py, Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools.yml, Packs/FeedDomainTools/Integrations/FeedDomainTools/FeedDomainTools_test.py, Packs/FeedDomainTools/Integrations/FeedDomainTools/README.md, Packs/FeedDomainTools/Integrations/FeedDomainTools/test_data/feed_mock_response.py, Packs/FeedDomainTools/README.md, Packs/FeedDomainTools/ReleaseNotes/1_0_2.md, Packs/FeedDomainTools/ReleaseNotes/1_0_3.md, Packs/FeedDomainTools/pack_metadata.json
N/A
Implement newly-observed-hostnames(NOH) feeds.
=> FeedDomainTools Release v1.0.3

Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-First_Azure_AD_PowerShell_operation_for_a_user.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_41.md, Packs/CortexResponseAndRemediation/pack_metadata.json
=> fix for REST playbook - First Azure AD PowerShell operation for a user

Tests/conf.json
related: https://jira-dc.paloaltonetworks.com/browse/CRTX-171878
Skipped mail listener tpb as its being blocked by CRTX-171878.
=> skipped mail listener tpb as its being blocked by CRTX-171878

Packs/CommonPlaybooks/Playbooks/playbook-Containment_Plan_-_Isolate_Device.yml, Packs/CommonPlaybooks/ReleaseNotes/2_7_2.md, Packs/CommonPlaybooks/pack_metadata.json
fixes: [link to jira ticket](https://jira-dc.paloaltonetworks.com/browse/CIAC-13469)
Fixed an issue with the yml's view key.
=> Fix-containment-plan-isolate-device

Packs/CloakedUrsaPhishingCampaign/pack_metadata.json, Packs/CloudIncidentResponse/pack_metadata.json, Packs/Code42/pack_metadata.json, Packs/CofenseIntelligenceV2/pack_metadata.json, Packs/CofenseTriage/pack_metadata.json, Packs/CofenseVision/pack_metadata.json, Packs/CohesityHelios/pack_metadata.json
=> Alignment tags, keywords and categories packs (chunk9)

Packs/Absolute/Integrations/Absolute/Absolute.py, Packs/Absolute/Integrations/Absolute/Absolute.yml, Packs/Absolute/Integrations/Absolute/Absolute_test.py, Packs/Absolute/ReleaseNotes/2_0_2.md, Packs/Absolute/pack_metadata.json, Tests/conf.json
fixes: [CIAC-13612](https://jira-dc.paloaltonetworks.com/browse/CIAC-13612)
=> Ciac 13612 fix absolute endpoints

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml, Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py, Packs/QRadar/ReleaseNotes/2_5_17.md, Packs/QRadar/pack_metadata.json
The SDK master was broken due to a particular file not been formatted (ruff)
=> Fix an unformatted file

Config/core_packs_platform_list.json
Adding the `AWS` pack to Platform core-packs list.
=> add AWS pack to platform core packs list

Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif, Packs/MicrosoftEntraID/ReleaseNotes/1_0_15.md, Packs/MicrosoftEntraID/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-50415
Change parsing rule logic.
=> XSUP-50415-msft-azure

Packs/RedCanary/Integrations/RedCanary/RedCanary.py, Packs/RedCanary/Integrations/RedCanary/RedCanary.yml, Packs/RedCanary/Integrations/RedCanary/RedCanary_test.py, Packs/RedCanary/Integrations/RedCanary/TestData/detection.json, Packs/RedCanary/Integrations/RedCanary/TestData/detection_timeline.json, Packs/RedCanary/ReleaseNotes/1_1_25.md, Packs/RedCanary/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-50484
Fixed an issue where in some cases the get-detection command did not return the domain info to context
=> Red canary domain context

Packs/RTIR/Integrations/RTIR/RTIR.py, Packs/RTIR/Integrations/RTIR/RTIR.yml, Packs/RTIR/ReleaseNotes/1_0_26.md, Packs/RTIR/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-50325
Fixed the add-reply command action to the right one
=> Rtir reply action fix

Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices.xif, Packs/AzureKubernetesServices/ModelingRules/AzureKubernetesServices/AzureKubernetesServices_schema.json, Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif, Packs/AzureKubernetesServices/ReleaseNotes/1_2_8.md, Packs/AzureKubernetesServices/pack_metadata.json, Packs/MicrosoftEntraID/ParsingRules/MicrosoftEntraID/MicrosoftEntraID.xif, Packs/MicrosoftEntraID/ReleaseNotes/1_0_16.md, Packs/MicrosoftEntraID/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-50590)
=> XSUP-50590 Azure AKS Fix

Packs/CadoResponse/pack_metadata.json
Update dev contacts for Cado Response pack
=> Update Cado Response pack_metadata.json

Packs/ProofpointThreatResponse/ModelingRules/ProofpointThreatResponseModelingRules_1_3/ProofpointThreatResponseModelingRules_1_3.xif, Packs/ProofpointThreatResponse/README.md, Packs/ProofpointThreatResponse/ReleaseNotes/2_0_26.md, Packs/ProofpointThreatResponse/pack_metadata.json
fixes:[link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-164106)
=> Proofpoint Threat Response update modeling rules

Packs/CommonScripts/ReleaseNotes/1_19_60.md, Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.py, Packs/CommonScripts/Scripts/ScheduleGenericPolling/ScheduleGenericPolling.yml, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13782)
=> Schedule generic polling update docker image

Packs/MicrosoftGraphIdentityandAccess/CONTRIBUTORS.json, Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py, Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.yml, Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess_test.py, Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_2_60.md, Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
The goal of this pull request is to add an option to the MicrosoftGraphIdentityandAccessintegration which allows fetching of risky user alerts instead of risk detections.
=> Add risky user fetching

.github/content_roles.json
=> Update on-call personal

Tests/conf.json
fixes: [link to the issue](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/21610876/raw)
=> Increase MT for a few TPB

Packs/MicrosoftExchangeOnPremise/ReleaseNotes/2_2_4.md, Packs/MicrosoftExchangeOnPremise/Scripts/BuildEWSQuery/BuildEWSQuery.py, Packs/MicrosoftExchangeOnPremise/Scripts/BuildEWSQuery/BuildEWSQuery.yml, Packs/MicrosoftExchangeOnPremise/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13811)
=> Build EWS query update docker image

Packs/GoogleCloudLogging/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-158630
Added keywords to the Google Cloud Logging content pack.
=> CRTX-158630-gcp_flow_logs_keywords

Tests/conf.json
fixes: https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/21811118
=> Test Playbook - Cortex XDR - Endpoint Investigation increase MT

Packs/Jira/Integrations/JiraV3/JiraV3.py, Packs/Jira/Integrations/JiraV3/JiraV3_test.py
=> Add ability to get jira display url from api or interpret from server_url

Packs/ServiceNow/.pack-ignore, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml, Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py, Packs/ServiceNow/ReleaseNotes/2_7_15.md, Packs/ServiceNow/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-169806
Adds the get-remote-data-preview command which will display a preview of the current ticket update
=> SNOW add get-remote-data-preview command

Tests/conf.json
fixes: [link to the issue](https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/jobs/22072268#L866)
=> Increase MT CrowdStrike_FalconX_Test

Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.yml, Packs/CybleEventsV2/ReleaseNotes/1_0_9.md, Packs/CybleEventsV2/pack_metadata.json, Packs/Jira/Integrations/JiraV2/JiraV2.yml, Packs/Jira/ReleaseNotes/3_2_21.md, Packs/Jira/pack_metadata.json, Packs/ServiceNow/Integrations/ServiceNow/ServiceNow.yml, Packs/ServiceNow/ReleaseNotes/2_7_16.md, Packs/ServiceNow/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-174479)
Specifying supported modules for CybleEventV2 pack for deprecated jirav2 and deprecated SNOW
=> Adding specific supported modules.

Packs/Code42/Integrations/Code42/Code42.py, Packs/Code42/Integrations/Code42/Code42.yml, Packs/Code42/Integrations/Code42/test_data/session_response.json, Packs/Code42/Integrations/Code42/test_data/session_response_2.json, Packs/Code42/Integrations/Code42/test_data/session_response_3.json, Packs/Code42/ReleaseNotes/6_0_6.md, Packs/Code42/pack_metadata.json
Updates the Incydr SDK version to 2.3.1, fixing several bugs.
=> bump incydr_python version to 2.3.1

.pre-commit-config_template.yaml
=> Skip mdx-validation

Tests/conf.json
=> Increase timeout playbook-SearchIncidentsV2InsideGenericPollng-Test

Packs/BeyondTrustEPM/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13900)
=> Fix BeyondTrustEPM README

Packs/CommonScripts/ReleaseNotes/1_19_64.md, Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink.py, Packs/CommonScripts/Scripts/GetDataCollectionLink/GetDataCollectionLink_test.py, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-51166)
=> Fix add support for get data collection link in XSIAM

Tests/conf.json
=> Edited docs for timeout var

Packs/Core/Integrations/CortexCoreXQLQueryEngine/README.md
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13775)
=> Documentation improvement

Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13795)
=> changed the context path to lower case

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml, Packs/CrowdStrikeFalcon/ReleaseNotes/2_1_24.md, Packs/CrowdStrikeFalcon/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-13915)
=> CS falcon fix context path in YML file

Packs/FiltersAndTransformers/CONTRIBUTORS.json, Packs/FiltersAndTransformers/ReleaseNotes/1_2_96.md, Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.py, Packs/FiltersAndTransformers/Scripts/JsonToTable/JsonToTable.yml, Packs/FiltersAndTransformers/pack_metadata.json
Add functionality to the JsonToTable script of the Filters And Transformers marketplace content pack that allows for the markdown table to contain values that have clickable URL links.
=> Jsontotable clickable links

Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif, Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_17.md, Packs/MicrosoftWindowsEvents/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-51539)
=> XSUP 51539 Microsoft Windows Update

Packs/Base/ReleaseNotes/1_39_34.md, Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.py, Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents.yml, Packs/Base/Scripts/DBotFindSimilarIncidents/DBotFindSimilarIncidents_test.py, Packs/Base/pack_metadata.json, Packs/DemistoRESTAPI/ReleaseNotes/1_3_74.md, Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile.py, Packs/DemistoRESTAPI/Scripts/UploadFile/UploadFile_test.py, Packs/DemistoRESTAPI/pack_metadata.json
fixes: [XSUP-51422](https://jira-dc.paloaltonetworks.com/browse/XSUP-51422)
[CIAC-13958](https://jira-dc.paloaltonetworks.com/browse/CIAC-13958)
=> Fix xsoar only supporting scripts

Packs/Base/ReleaseNotes/1_39_34.md, Packs/Base/ReleaseNotes/1_39_35.md, Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml, Packs/Base/pack_metadata.json
=> SanePdfReports: update docker tag

Packs/EmailCommunication/ReleaseNotes/2_0_40.md, Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py, Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml, Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply_test.py, Packs/EmailCommunication/pack_metadata.json
fixes: [CIAC-13877](https://jira-dc.paloaltonetworks.com/browse/CIAC-13877)
=> sendemailreply handling error

Packs/ProofpointThreatProtection/Integrations/ProofpointThreatProtection/ProofpointThreatProtection.yml, Packs/ProofpointThreatProtection/Integrations/ProofpointThreatProtection/ProofpointThreatProtection_test.py, Packs/ProofpointThreatProtection/ReleaseNotes/1_0_3.md, Packs/ProofpointThreatProtection/pack_metadata.json
This addresses intermittent failures in the SDK nightly build, such as the one seen in [pipeline #3651340](https://www.google.com/search?q=https://gitlab.xdr.pan.local/xdr/cortex-content/content/-/pipelines/3651340).
The root cause was unit tests attempting to make real network connections to localhost. To resolve this and follow best practices, I have removed the code responsible for these network calls, ensuring the tests are properly isolated.
=> Rewrite Proofpoint Threat Protection unit tests

Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Script_file_added_to_startup-related_Registry_keys.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_59.md, Packs/CortexResponseAndRemediation/pack_metadata.json
Added continue on error in retrieve file tasks
and fix conditional task to check if dbotscore is not empty
=> Script_file_added_to_startup-related_Registry_keys-fix-kpi-breaches

Packs/cisco-meraki/ModelingRules/CiscoMerakiModelingRules_1_3/CiscoMerakiModelingRules_1_3.xif, Packs/cisco-meraki/ReleaseNotes/2_0_3.md, Packs/cisco-meraki/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-51986)
=> XSUP-51986 - Cisco Meraki regex update

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml, Packs/Core/Integrations/CortexPlatformCore/CortexPlatformCore.yml, Packs/Core/ReleaseNotes/3_4_1.md, Packs/Core/pack_metadata.json
=> fix modules

Packs/CommonScripts/ReleaseNotes/1_19_68.md, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.py, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2.yml, Packs/CommonScripts/Scripts/SearchIncidentsV2/SearchIncidentsV2_test.py, Packs/CommonScripts/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-176310)
Add support for unified_platform version.
=> add support for unified platform version.

Packs/SymantecBlueCoatProxySG/ModelingRules/SymantecBlueCoatProxySG/SymantecBlueCoatProxySG.xif, Packs/SymantecBlueCoatProxySG/ReleaseNotes/1_0_6.md, Packs/SymantecBlueCoatProxySG/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-51891)
=> XSUP 51891 symantec_bluecoatproxysg mapping update

Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.py, Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender.yml, Packs/Microsoft365Defender/ReleaseNotes/4_6_5.md, Packs/Microsoft365Defender/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-178569
=> CRTX-178569

Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py, Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.yml, Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_description.md, Packs/AzureWAF/Integrations/AzureWAF/AzureWAF_test.py, Packs/AzureWAF/Integrations/AzureWAF/README.md, Packs/AzureWAF/ReleaseNotes/1_2_15.md, Packs/AzureWAF/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-14072)
Changed the user-code to Authorization code in the Azure WAF in the README and descriptions.
=> Changed the user-code to Authorization code in the Azure WAF

Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-External_Login_Password_Spray_Test.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_66.md, Packs/CortexResponseAndRemediation/pack_metadata.json
Ready
DT fix in saving post login activity to evidence - could result in wrong verdict calculation
=> External login password spray DT fix

Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml, Packs/VirusTotal/ReleaseNotes/2_7_2.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] fix(file): One invalid hash

Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/MicrosoftGraphIdentityandAccess.py, Packs/MicrosoftGraphIdentityandAccess/Integrations/MicrosoftGraphIdentityandAccess/README.md, Packs/MicrosoftGraphIdentityandAccess/ReleaseNotes/1_3_2.md, Packs/MicrosoftGraphIdentityandAccess/pack_metadata.json
fixes: [CIAC-14104](https://jira-dc.paloaltonetworks.com/browse/CIAC-14104)
=> update ms graph identity access permissions

Packs/AzureAppService/ModelingRules/AzureAppService/AzureAppService.xif, Packs/AzureAppService/ReleaseNotes/1_0_3.md, Packs/AzureAppService/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-52384)
=> XSUP 52384 Azure App Service Fix

Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_test.py
Reverting an error from https://github.com/demisto/content/pull/40285
=> Ruff fixes

Packs/TrendMicroVisionOne/ModelingRules/TrendMicroVisionOneModelingRules/TrendMicroVisionOneModelingRules.xif, Packs/TrendMicroVisionOne/ReleaseNotes/4_2_6.md, Packs/TrendMicroVisionOne/pack_metadata.json
=> fix alert.severity

.github/content_roles.json
=> Update content roles AUD to shmuel44

Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py, Packs/VirusTotal/ReleaseNotes/2_7_3.md, Packs/VirusTotal/pack_metadata.json
=> [VirusTotal] Improve error msg

Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence.py, Packs/GoogleThreatIntelligence/Integrations/GoogleThreatIntelligence/GoogleThreatIntelligence_test.py, Packs/GoogleThreatIntelligence/ReleaseNotes/1_3_4.md, Packs/GoogleThreatIntelligence/pack_metadata.json
=> [GoogleThreatIntelligence] Improve error msg

.github/content_roles.json
Contributions: update reviewers
=> Contributions: update reviewers

Packs/CortexResponseAndRemediation/Playbooks/playbook-Event_Log_Was_Cleared.yml, Packs/CortexResponseAndRemediation/Playbooks/playbook-Uncommon_remote_scheduled_task_created.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Event_Log_Was_Cleared_Test.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Uncommon_remote_scheduled_task_created_Test.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_75.md, Packs/CortexResponseAndRemediation/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/ARES-317
https://jira-dc.paloaltonetworks.com/browse/ARES-311
https://jira-dc.paloaltonetworks.com/browse/ARES-314
https://jira-dc.paloaltonetworks.com/browse/ARES-328
Uncommon remote scheduled task created:
- Added 'Continue on error' option in the "Check remote IP reputation" task.
Event Log Was Cleared:
- Updated the task "Get prevalence for the processes in the causality" to remove empty values.
-
=> Playbooks fixes kpi 1.1.68

Packs/CommonScripts/ReleaseNotes/1_19_80.md, Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis.py, Packs/CommonScripts/Scripts/CommandLineAnalysis/CommandLineAnalysis_test.py, Packs/CommonScripts/pack_metadata.json
Fixed the issue of custom patterns not being added to the score.
=> Command Line Analysis - Custom Patterns bug fix

Packs/Exabeam/Integrations/Exabeam/Exabeam_test.py
=> Fix  Exabeam UT

Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/MicrosoftGraphAPI.py, Packs/MicrosoftGraphAPI/ReleaseNotes/1_1_59.md, Packs/MicrosoftGraphAPI/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-53384
Added support to status code 202
=> Xsup 53384 ms graph ok codes

Packs/CybleEventsV2/Integrations/CybleEventsV2/CybleEventsV2.py, Packs/CybleEventsV2/ReleaseNotes/1_1_1.md, Packs/CybleEventsV2/pack_metadata.json
-Minor bug fix in test-module functionality
=> bug fix in test-module and version changed

Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.py, Packs/CortexXpanse/Integrations/FeedXpanse/FeedXpanse.yml, Packs/CortexXpanse/ReleaseNotes/1_2_11.md, Packs/CortexXpanse/pack_metadata.json
https://jira-dc.paloaltonetworks.com/browse/XSUP-53412
Updated the *indicatorTypes* parameter of *Xpanse Feed* integration be optional.  This should resolve the underlying dev to prod issue.
=> [CortexXpanse] XSUP-53412

Packs/AWS_ELB/README.md, Packs/DelineaSS/ReleaseNotes/2_0_1.md, Packs/IBMSecurityVerify/README.md, Packs/JuniperSRX/ReleaseNotes/1_0_6.md, Packs/Office365/README.md
=> fix tags issue

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md, Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md, Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_20_3.md, Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-52925)
Update Microsoft Defender for Endpoint (ATP) integration docs with clearer authentication instructions.
=> Update Microsoft Defender for Endpoint (ATP) integration docs

Packs/InfobloxBloxOne/Integrations/InfobloxBloxOneThreatDefenseEventCollector/InfobloxBloxOneThreatDefenseEventCollector.yml
=> Add needed field to yml file

Packs/AzureNetworkSecurityGroups/Integrations/AzureNetworkSecurityGroups/README.md
Update the Azure Network Security Group README.
=> Update Azure Network Security Group README

Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.py, Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2.yml, Packs/opswat-metadefender/Integrations/OPSWATMetadefenderV2/OPSWATMetadefenderV2_test.py, Packs/opswat-metadefender/ReleaseNotes/1_0_16.md, Packs/opswat-metadefender/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-52472)
According the docs [here](https://www.opswat.com/docs/mdcore/metadefender-core#fileanalysispost) we should use the data attribute in the requests.post method instead of the file attribute
=> Improve Opswat file upload

Config/core_packs_platform_list.json, Packs/AWS/ReleaseNotes/2_0_3.md, Packs/AWS/pack_metadata.json, Packs/Azure/ReleaseNotes/1_0_4.md, Packs/Azure/pack_metadata.json, Packs/GCP/ReleaseNotes/1_0_2.md, Packs/GCP/pack_metadata.json
related: [CRTX-188008](https://jira-dc.paloaltonetworks.com/browse/CRTX-188008) 
GCP, AWS and Azure should be supported on cloud_posture addon
=> Add cloud posture supported module

Packs/ServiceNow/ReleaseNotes/2_8_6.md, Packs/ServiceNow/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-185393
=> SNOW bump version

.github/content_roles.json
=> Updating contrib team

Packs/GenericWebhook/ReleaseNotes/1_1_10.md
=> Fixed XSIAM tag in Generic Web hook RN

Packs/RecordedFutureV3/Integrations/RecordedFutureAlerts/README.md
=> [Pack][RecordedFutureV3] Update integration readme: add link to migration guide.

Packs/SAPCloudForCustomerC4C/ReleaseNotes/1_0_1.md, Packs/SAPCloudForCustomerC4C/pack_metadata.json
[https://github.com/demisto/content/pull/40424](url)
Added "platform" to the existing "marketplaces" array.
Added the following module identifiers to the "supportedModules" array:
"X1", "X3", "X5", "ENT_PLUS", "agentix"
=> Sap C4C pack metadata fixes

Packs/CortexResponseAndRemediation/Playbooks/playbook-Unprivileged_process_opened_a_registry_hive.yml, Packs/CortexResponseAndRemediation/Playbooks/silent-playbook-Unprivileged_process_opened_a_registry_hive_Test.yml, Packs/CortexResponseAndRemediation/ReleaseNotes/1_1_98.md, Packs/CortexResponseAndRemediation/pack_metadata.json
Updated the related alert search query to filter out the alert 'Unprivileged process opened a registry hive'.
=> Refactoring_Unprivileged_process_opened_a_registry_hive

Packs/SentinelOne/ReleaseNotes/3_2_46.md, Packs/SentinelOne/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-191703)
=> Fix CRTX-191703

Packs/Uptycs/Integrations/Uptycs/Uptycs.py, Packs/Uptycs/Integrations/Uptycs/Uptycs.yml, Packs/Uptycs/ReleaseNotes/1_0_20.md, Packs/Uptycs/pack_metadata.json
line 908 OnCall
fix `TypeError: 'module' object is not callable. Did you mean: 'signal.signal(...)'?`
=> [uptycs] Fix Import

Packs/AggregatedScripts/ReleaseNotes/1_0_16.md, Packs/AggregatedScripts/Scripts/GetEndpointData/GetEndpointData.py, Packs/AggregatedScripts/pack_metadata.json
=> Fix getendpointdata enum issue

Packs/AWS-Lambda/Integrations/AWS_Lambda/AWS_Lambda.yml, Packs/AWS-Lambda/Integrations/AWS_Lambda/README.md, Packs/AWS-Lambda/ReleaseNotes/1_3_14.md, Packs/AWS-Lambda/pack_metadata.json
=> AWS Lambda: fix readme

Packs/AggregatedScripts/ReleaseNotes/1_0_17.md, Packs/AggregatedScripts/Scripts/GetUserData/GetUserData.py, Packs/AggregatedScripts/Scripts/GetUserData/GetUserData_test.py, Packs/AggregatedScripts/pack_metadata.json
=> [GetUserData] fix manger not appearing for MS Graph

Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.py, Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture.yml, Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_test.py, Packs/FeedRecordedFuture/ReleaseNotes/1_2_2.md, Packs/FeedRecordedFuture/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-14493)
Fixed an issue where the `performance` parameter was always set to `false` regardless of the instance configuration.
=> Recorded Future fixed an issue with the performance parameter

Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif, Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_19.md, Packs/MicrosoftWindowsEvents/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CRTX-183528)
=> [CRTX-183528] Microsoft Windows Events Enhancement

Packs/AzureAppService/ParsingRules/AzureAppService/AzureAppService.xif, Packs/AzureAppService/ReleaseNotes/1_0_5.md, Packs/AzureAppService/pack_metadata.json
fixes: [CRTX-190014](https://jira-dc.paloaltonetworks.com/browse/CRTX-190014)
Added support for two additional time formats
- YYYY-MM-DDTHH:mm:ss
- YYYY-MM-DD HH:mm:ss
=> Azure App Service - Parsing Rule Enhancement 2 - CRTX-190014

Packs/SentinelOne/ReleaseNotes/3_2_47.md, Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents.py, Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents.yml, Packs/SentinelOne/Scripts/SentinelOneListAgents/SentinelOneListAgents_test.py, Packs/SentinelOne/pack_metadata.json
=> Fix externalIp handling

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
Adding supportedModules to Cortex - CoreIR commands
=> Core core ir supported modules

Packs/CofenseTriage/Integrations/CofenseTriagev3/test_data/input_data.py
CofenseTriagev3 UT failed due to an update in argToBoolean.
=> CofenseTriagev3 fix UT

Packs/Anomali_ThreatStream/Integrations/AnomaliThreatStreamv3/AnomaliThreatStreamv3.py, Packs/Anomali_ThreatStream/Integrations/Anomali_ThreatStream_v2/Anomali_ThreatStream_v2.py, Packs/Anomali_ThreatStream/ReleaseNotes/2_2_32.md, Packs/Anomali_ThreatStream/pack_metadata.json, Packs/Base/ReleaseNotes/1_41_19.md, Packs/Base/Scripts/CommonServerPython/CommonServerPython.py, Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py, Packs/Base/pack_metadata.json, Packs/Flashpoint/Integrations/Ignite/Ignite.py, Packs/Flashpoint/Integrations/Ignite/Ignite_test.py, Packs/Flashpoint/ReleaseNotes/2_1_3.md, Packs/Flashpoint/pack_metadata.json, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py, Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3_test.py, Packs/VirusTotal/ReleaseNotes/2_7_6.md, Packs/VirusTotal/pack_metadata.json
Rename the ***is_ip_internal*** function to ***is_ip_address_internal***.
=> Rename is_ip_internal function

Packs/CortexXDR/ReleaseNotes/6_2_35.md, Packs/CortexXDR/pack_metadata.json
=> [Cortex XDR - IR] Remove from Platform marketplace

Packs/TigeraCalico/README.md
Fixed parsing error in the docs build.
=> Tigera Calico fix the README file

Packs/Cisco-umbrella-cloud-security/CONTRIBUTORS.json, Packs/Cisco-umbrella-cloud-security/Integrations/Cisco-umbrella-cloud-security/Cisco-umbrella-cloud-security.yml, Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2.py, Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2.yml, Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2_description.md, Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/CiscoUmbrellaCloudSecurityv2_test.py, Packs/Cisco-umbrella-cloud-security/Integrations/CiscoUmbrellaCloudSecurityv2/README.md, Packs/Cisco-umbrella-cloud-security/ReleaseNotes/2_0_13.md, Packs/Cisco-umbrella-cloud-security/pack_metadata.json
N/a no issue known.
Adds a new integration parameter similar to the other Cisco Umbrella Integrations, which allows this integration to work with the Cisco SSE product as well.
=> Add new integration parameter to support alt api endpoint

Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif, Packs/AzureKubernetesServices/ReleaseNotes/1_2_14.md, Packs/AzureKubernetesServices/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-55817)
=> XSUP-55817 Azure AKS Update

Packs/AggregatedScripts/ReleaseNotes/1_1_11.md, Packs/AggregatedScripts/Scripts/IsolateEndpoint/IsolateEndpoint.py, Packs/AggregatedScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-14767
Fixed the result message to success for already isolated endpoint.
=> Ciac 14767 fix alreay isolated message

Packs/CortexXDR/ReleaseNotes/6_2_36.md, Packs/CortexXDR/pack_metadata.json
fixes: [ticket](https://jira-dc.paloaltonetworks.com/browse/XSUP-55641)
Reverted the [PR](https://github.com/demisto/content/pull/41091/files)
=> Revert 41091

Packs/AzureKubernetesServices/ParsingRules/AzureKubernetesServices/AzureKubernetesServices.xif, Packs/AzureKubernetesServices/README.md, Packs/AzureKubernetesServices/ReleaseNotes/1_2_15.md, Packs/AzureKubernetesServices/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-55817)
=> XSUP 55817 Azure AKS Update2

Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3.py, Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3.yml, Packs/OpenAI/Integrations/OpenAiChatGPTV3/OpenAiChatGPTV3_test.py, Packs/OpenAI/ReleaseNotes/2_0_4.md, Packs/OpenAI/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-55982)
Casting top_p temerature and num of tokens to numerical types.
=> Open aigpt params

Packs/Whois/Integrations/Whois/Whois_test.py
link: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-8779)
=> Whois - remove flakily failing UT

Packs/MicrosoftWindowsEvents/ModelingRules/MicrosoftWindowsEvents_1_3/MicrosoftWindowsEvents_1_3.xif, Packs/MicrosoftWindowsEvents/ReleaseNotes/1_1_20.md, Packs/MicrosoftWindowsEvents/pack_metadata.json
=> XSUP-55372 - microsoft_windows_raw - enhance regex extraction

Packs/BloodHoundEnterprise/Integrations/BloodHoundEnterprise/BloodHoundEnterprise.yml, Packs/BloodHoundEnterprise/Integrations/BloodHoundEnterprise/BloodHoundEnterprise_test.py, Packs/BloodHoundEnterprise/ReleaseNotes/1_0_5.md, Packs/BloodHoundEnterprise/pack_metadata.json
fixed an issue where the integration failed a validation in the nightly due to changing the support level of the pack from xsoar to partner
=> added missing supportlevelheader key to the integration

Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.py, Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/GoogleCloudStorage.yml, Packs/GoogleCloudStorage/Integrations/GoogleCloudStorage/README.md, Packs/GoogleCloudStorage/ReleaseNotes/1_0_17.md, Packs/GoogleCloudStorage/pack_metadata.json
n/a
Add support for a command to delete a file from Google Cloud Storage.
=> Add command gcs-delete-file

Packs/CommonScripts/ReleaseNotes/1_20_18.md, Packs/CommonScripts/ReleaseNotes/1_20_19.md, Packs/CommonScripts/Scripts/SearchIndicatorAgentix/SearchIndicatorAgentix.py, Packs/CommonScripts/Scripts/SearchIndicatorAgentix/SearchIndicatorAgentix_test.py, Packs/CommonScripts/pack_metadata.json
fixes: https://jira-dc.paloaltonetworks.com/browse/CRTX-199438
=> SearchIndicatorAgentix - updated score to verdict

Packs/CheckpointFirewall/ModelingRules/CheckpointFirewall_1_3/CheckpointFirewall_1_3.xif, Packs/CheckpointFirewall/ReleaseNotes/2_3_34.md, Packs/CheckpointFirewall/pack_metadata.json
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/XSUP-56878)
=> XSUP 56878 CP-FW Update
