demisto/content

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/16909
removed McAfee ATD from skipped tests

McAfee-ATD removed from skipped tests

---

Packs/AutoFocus/Integrations/FeedAutofocus/README.md

Seems that a missing newline was causing formatting issue at the bottom of the page:

autofocus doc: fix formatting (missing new line)

---

.circleci/config.yml
Tests/scripts/install_content_and_test_integrations.sh
Tests/scripts/run_tests.sh

fixes: https://github.com/demisto/etc/issues/29259
* For each server job added a step that collects the instance role and checks if the instance was created. This step passes that information on to next steps with environment variables.
* Separated the installation step from the playbook tests step
https://app.circleci.com/pipelines/github/demisto/content/42321/workflows/201b6c89-e501-433e-90e8-35bf3cf873cb

Separated the installation step from the playbook tests step

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/ReleaseNotes/1_0_5.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30527
Modified the API request to filter user by display name/mail/UPN instead of getting all users and iterating them

Microsoft Teams - modify API query to filter user by given entity

---

Tests/Marketplace/Tests/search_and_install_packs_test.py
Tests/Marketplace/search_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Tests/instance_notifier.py
Tests/private_build/configure_and_test_integration_instances_private.py
Tests/private_build/run_content_tests_private.py
Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Tests/scripts/utils/log_util.py
Tests/test_content.py
Tests/test_integration.py
Tests/tools.py
Tests/update_content_data.py

Related: https://github.com/demisto/etc/issues/30511
* Implemented logging in `Install Content And Configure Integrations On Server`
* Removed `printsManager` from where possible (All functions that are not being used in `Run Tests` step too)
* Added a `install_simple_logging` function that only configures the success logging level, the colors and the log format (message only) so that when replacing it with print_error, print_warning etc. will behave the same for the common functions with  `Run Tests`.
* It appears the sdk validator imports a package that calls logging basicConfig method before the log_util function.
Therefore, the `install_logging` method is executed before the sdk Validator is imported to enforce the correct logging configurations.
* Added debug logs and modified info …

Added logs for content installation

---

Tests/Marketplace/configure_and_install_packs.py

Deleted the `prints_manager` arg from the `install_all_content_packs` call.

configure_and_install_packs bugfix

---

Tests/Marketplace/copy_and_upload_packs.py
Tests/scripts/slack_notifier.py

Fixed two issues in upload-flow:
- Slack notifier now notifies on successful packs, see Screenshot1
- verify copy uses pack names instead of pack object and therefore not failing the build, see Screenshot2 (before) and Screenshot3 (after)
Screenshot1:
Screenshot2:
Screenshot3:

Upload flow fixes

---

Tests/test_content.py

I'd hate to point out names, but it seems like someone forgot to send the thread_index to the `run_test_logic` method when running unmockable integrations.
Which messed up the prints in the nightly build because all threads used the same thread index (0) during their execution

Using thread index when running mocked integrations

---

Tests/timestamp_replacer.py

Updates the `timestamp_replacement.py` script to use `dateparser`, whose `parse` method is more robust than that of the one currently in use from `dateutil.parser`. Need to wait to merge this PR until the AMIs are updated - see https://github.com/demisto/content-test-conf/pull/1035.

Modify Timestamp Replacer for more Robust Detection

---

Tests/scripts/utils/log_util.py
Tests/scripts/utils/tests/log_utils_test.py

This PR is about the implementation of the `ParallelLoggingManager`.
The `ParallelLoggingManager` is meant to be used when using logging with multithreading and some thread logs
should be grouped together in the log file for better readability.
This class replaces the `ParallelPrintsManager`.
This class should be created only once in every process exceution.
```
>>> logging_manager = ParallelLoggingManager('debug_file.log')
>>> logging_manager.debug('debug message')
>>> logging_manager.info('info message')
>>> logging_manager.warning('warning message')
>>> logging_manager.error('error message')
>>> logging_manager.critical('critical message')
>>> logging_manager.success('success message')
>>> logging_manager.exception('exception message')
```
```
>>> logging_manager.execute_logs()
```
``` …
```

Implemented Parallel logging manager

---

Tests/conf.json

Removed SNow integration from skipped tests.
fixes: https://github.com/demisto/etc/issues/30581
fixes: https://github.com/demisto/etc/issues/30586
fixes: https://github.com/demisto/etc/issues/30587
fixes: https://github.com/demisto/etc/issues/30588

Removing ServiceNow from Skipped Tests

---

Packs/Rundeck/Integrations/Rundeck/Rundeck_test.py

The method `calc_run_at_time` return aware date.
The unittest should do the same or it will generate different date.

Use aware datetime object in unittests

---

Packs/AlphaSOC_Network_Behavior_Analytics/Integrations/integration-AlphaSOC_Network_Behavior_Analytics.yml
Packs/AlphaSOC_Network_Behavior_Analytics/ReleaseNotes/1_0_1.md
Packs/AlphaSOC_Network_Behavior_Analytics/pack_metadata.json

This PR changes the default minimum severity of incidents to retrieve. Certain user environments may generate significant amount of low or medium severity incidents which are then unnecessarily fetched by default.
fixes: https://github.com/demisto/etc/issues/30283

AlphaSOC NBA - Adjust default incident severity from 3 to 4

---

.circleci/config.yml

wait until server 6.0 is ready instead of server master.

fixed 6.0 'wait until server ready' step in upload packs flow

---

Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_1.md
Packs/CarbonBlackEnterpriseEDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30871
removed 2 invalid values to sort by and replaced the default value with valid one

Carbon Black EDR - rm severity and target_value as optional values for the sort_field arg

---

Packs/CortexDataLake/.secrets-ignore
Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.py
Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml
Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake_test.py
Packs/CortexDataLake/Integrations/CortexDataLake/README.md
Packs/CortexDataLake/Integrations/CortexDataLake/test_data/test_query_logs_command_transform_results_original.json
Packs/CortexDataLake/Integrations/CortexDataLake/test_data/test_query_logs_command_transform_results_xformed.json
Packs/CortexDataLake/ReleaseNotes/1_2_9.md
Packs/CortexDataLake/pack_metadata.json

Current implementation of `cdl-query-logs` command automatically maps results from CDL API into a context common to all Log types. See [here](https://github.com/demisto/content/blob/master/Packs/CortexDataLake/Integrations/CortexDataLake/README.md#context-example) for an example.
This mapping is fine as long as no special CDL query functions are used that could modify the results fields. When the results field are modified via the query, the context mapping does not collect fields falling outside common mapping.
Example:
The query: 
```
SELECT source_ip.value AS src_ip,log_source_id,vsys,COUNT(*) AS count FROM `firewall.traffic` WHERE dest_ip.value="54.240.251.124" AND source_user is NULL AND action.id=0 AND log_time > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY) AND …
```

Add transform_results arg to cdl-query-logs

---

Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
Packs/AutoFocus/Integrations/AutofocusV2/README.md
Packs/AutoFocus/Integrations/FeedAutofocusDaily/README.md
Packs/AutoFocus/ReleaseNotes/1_1_11.md
Packs/AutoFocus/TestPlaybooks/playbook-AutoFocus_V2_test.yml
Packs/AutoFocus/pack_metadata.json

- fixed the indicator type to be `filehash` in the api query for the file command according to https://docs.paloaltonetworks.com/autofocus/autofocus-api/perform-direct-searches/get-threat-intelligence-card-summary.html
- fixed commad name in daily feed in the feed doc
- removed redundant `**` in the af v2 integration doc

AutoFocus v2 - fix indicator type for the file cmd

---

Tests/scripts/infrastructure_tests/release_notes_generator_test.py
Utils/release_notes_generator.py

fixes: https://github.com/demisto/etc/issues/28079
When creating release notes, packs that are "Community Contributed" will now have (Community Contributed) tag in the title, after the version number.

[Dev-Task] add "(Community Contributed)" to release notes

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/Integrations/Panorama/README.md
Packs/PAN-OS/Playbooks/playbook-Panorama_Query_Logs.yml
Packs/PAN-OS/Playbooks/playbook-Panorama_Query_Logs_README.md
Packs/PAN-OS/ReleaseNotes/1_6_8.md
Packs/PAN-OS/pack_metadata.json

*No open issue*
With the current version of the PAN-OS integration the *vsys* of PAN-OS/Panorama logs is not exported by panorama-get-logs and Panorama Query Logs subplaybook.
With this PR the *vsys* field from PAN-OS/Panorama logs is correctly exported by panorama-get-logs command and by Panorama Query Logs subplaybook.

Adds support for Vsys to panorama-get-logs and Panorama Query Logs

---

Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.py
Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
Packs/McAfee_ESM/ReleaseNotes/1_1_2.md
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_-_Test.yml
Packs/McAfee_ESM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30986
- cast timeout to int
- handle 400 status code as result ready
see failing test in https://app.circleci.com/pipelines/github/demisto/content/46986/workflows/079ca85b-cc66-4c49-b996-72e08cc3d312/jobs/201393

McAfee ESM v2 - handle search timeout

---

.circleci/config.yml
Tests/Marketplace/Tests/copy_and_upload_packs_test.py
Tests/Marketplace/Tests/search_and_install_packs_test.py
Tests/Marketplace/copy_and_upload_packs.py
Tests/Marketplace/search_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Tests/scripts/install_content_and_test_integrations.sh

fixes: https://github.com/demisto/etc/issues/30824
- Nightly is now running against the production bucket and not against origin/master when retrieving the latest version of each pack. 
- Refactored the latest pack regex to also catch pack names that consist of a dot.

nightly running against bucket

---

.circleci/config.yml
Tests/Marketplace/upload_packs.py
Tests/private_build/upload_packs_private.py
Tests/scripts/prepare_content_packs_for_testing.sh
Utils/trigger_force_upload_pack_to_production.sh

- Now, when force uploading, we don't update the index with the commit of the upload, we leave it as it is.
- Deleted all the logic related to `force_commit_hash` as it has no effect.

not updating index on force upload flow

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/1_3_12.md
Packs/ServiceNow/pack_metadata.json

related: https://github.com/demisto/etc/issues/30696
Server requires for mirroring integrations to raise an exception for un-implemented commands.

ServiceNow raise error on non implemented command

---

Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.py
Packs/ArcSightESM/ReleaseNotes/1_0_7.md
Packs/ArcSightESM/pack_metadata.json

In case invalid viewer query ID was given as parameter for the fetch, the wrong query (cases query viewer id) was returned in the error message

Arcsight ESM v2 - fix wrong query returned in invalid viewer query id error message

---

Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
Packs/AbuseDB/ReleaseNotes/1_0_1.md
Packs/AbuseDB/TestPlaybooks/playbook-AbuseIPDB-test.yml
Packs/AbuseDB/pack_metadata.json
Tests/conf.json

the IP address 103.99.110.181 returns the following category IDs in its analysis report: 0, 5, 15
the problematic category ID is 0, which is not in the list of [known categories](https://www.abuseipdb.com/categories)
removing it from the set of categories to count for the given report

AbuseIPDB - fix analysis report categories sum

---

Documentation/common_server_docs.py
Tests/Marketplace/configure_and_install_packs.py
Tests/Marketplace/copy_and_upload_packs.py
Tests/Marketplace/normalize_gcs_paths.py
Tests/Marketplace/packs_dependencies.py
Tests/Marketplace/private_build_prepare_for_testing.py
Tests/Marketplace/upload_packs.py
Tests/Marketplace/zip_packs.py
Tests/configure_and_test_integration_instances.py
Tests/instance_notifier.py
Tests/mock_server.py
Tests/private_build/configure_and_test_integration_instances_private.py
Tests/private_build/run_content_tests_private.py
Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/slack_notifier.py
Tests/scripts/update_conf_json.py
Tests/scripts/utils/log_util.py
Tests/scripts/wait_until_server_ready.py
Tests/test_content.py
Tests/test_integration.py
Tests/tests/test_integration_test.py
Tests/tools.py
Utils/release_notes_generator.py

fixes: https://github.com/demisto/etc/issues/29261
This PR is about removing the ParallelPrintsManager and the different print methods from the build's steps (`print_error`, `print_warning` etc.)
In addition:
- Moved all the docker limit logs to debug file
- Moved most of the proxy prints to the debug file and added the stdout of the process.
- Since the test playbook step in private builds has one thread only - replaced the PrintsManager with logging (instead of loggingManager) 
- added logging to the slack notifier step
- Replaced as many `.format` strings with f-string
1. what logs should be visible on the console and what logs should appear in the file only:
- Should the locking logs appear?
- Should the proxy logs appear?
Open the `Run Tests.log` file from artifacts to see the …

killing prints manager

---

Packs/Mimecast/TestPlaybooks/playbook-Mimecast_Test.yml

fixes: https://github.com/demisto/etc/issues/26906
The test tried to list message and then validate that a specific message is there while this message seems to have been deleted.
The validation will now look for another message that is currently there

Fixing mimecast test

---

Tests/timestamp_replacer.py

Added an attempt to json.loads content in which literal_eval failed on.

Add json loads in case literal_eval fails

---

Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.py
Packs/Akamai_WAF/Integrations/Akamai_WAF/Akamai_WAF.yml
Packs/Akamai_WAF/Integrations/Akamai_WAF/README.md
Packs/Akamai_WAF/ReleaseNotes/1_0_2.md
Packs/Akamai_WAF/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30729
Added `extended` and `include_elements` flags to the list networks command

Akamai WAF - add extended and include_elements args to networks list

---

Tests/mock_server.py

RSA key exists in the servers from the AMI build, no need to write it during the circle build +. it breaks the build

RSA key is in the server from the AMI

---

.circleci/config.yml

In case of a nightly build, set the `INSTANCE_WAS_CREATED` variable to `true`

set INSTANCE_WAS_CREATED to true in nightly

---

Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2.py
Packs/CheckpointFirewall/Integrations/CheckPointFirewall_v2/CheckPointFirewall_v2_test.py
Packs/CheckpointFirewall/ReleaseNotes/2_0_4.md
Packs/CheckpointFirewall/pack_metadata.json

fixed an issue where only the second char in the host id would be passed to the request func

Checkpoint Firewall v2 - pass the host id to the request properly in the delete-host cmd

---

.circleci/config.yml
Tests/mock_server.py
Tests/test_content.py

https://github.com/demisto/etc/issues/30765
https://github.com/demisto/content-test-conf/pull/1041
* ### Supporting mitmdump service
- Before starting the service creates a file named `/home/ec2-user/mitmdump_rc` which will be used by the service's start.
- using `start` and `stop` commands to start and stop the service
* ### Added polling mechanism 
- with timeout that waits until the mitmdump is ready and gets last in case it failed to start using `systemctl status mitmdump` command
* ### Copying the `timestamp_replacer.py` script only once in the `MITMProxy` init.

Support mitmdump service

---

Tests/Marketplace/search_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Tests/private_build/configure_and_test_integration_instances_private.py
Tests/private_build/run_content_tests_private.py
Tests/test_content.py
Tests/tests/configure_and_test_integration_instances_test.py

- refactored the main method of `Tests/configure_and_test_integration_instances.py` to be more readable (no logic change there, just separating the code to smaller functions)
- Moved the disabling of the integrations from the beginning of the test playbooks step to the end of the content installation and configuration
- Removed the 45 seconds sleep in the beginning of `Tests/test_content.py` as it seems the related issue is solved
https://github.com/demisto/etc/issues/30511
https://github.com/demisto/etc/issues/30292

Some build refractoring

---

Tests/timestamp_replacer.py

Some requests include an encoded file in the content.
Those requests cannot be decoded because some of the bytes aren't in the ascii charset.

safely decode raw content in the timestamp replacer

---

Packs/AlphaSOC_Network_Behavior_Analytics/Integrations/integration-AlphaSOC_Network_Behavior_Analytics.yml
Packs/AlphaSOC_Network_Behavior_Analytics/ReleaseNotes/1_0_2.md
Packs/AlphaSOC_Network_Behavior_Analytics/pack_metadata.json

The AlphaSOC API now supports an optional `minSeverity` parameter which allows to reduce the number of retrieved threats. This PR updates the integration so that it uses that parameter.

AlphaSOC NBA - Pass minSeverity parameter to API

---

Packs/Base/ReleaseNotes/1_3_43.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

- Changed how CommandResults.to_context() handles empty lists provided as **outputs**: now it doesn't return any EntryContext, instead of returning an empty lists that gets visualized as **null** in the UI context.
- Fixed tuples in Common.CertificateExtension.EntryTypes for SignedCertificateTimestamp extensions

CommonServerPython improvements

---

Packs/Base/ReleaseNotes/1_4_2.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31308
Removed timezone from the global space

removed problematic call to timezone

---

Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.py
Packs/SentinelOne/Integrations/SentinelOne-V2/SentinelOne-V2.yml
Packs/SentinelOne/ReleaseNotes/1_0_5.md
Packs/SentinelOne/pack_metadata.json

if error object did not contain the `detail` key, then `TypeError: can only concatenate str (not "NoneType") to str` would be raised
fixes: https://github.com/demisto/etc/issues/31409

SentinelOne v2 - use f-strings instead of concat in error processing

---

Tests/scripts/utils/log_util.py

The use of `basicConfig` with the `force` flag is not supported in python3.7.
Since the sdk build uses some files that uses this logging feature - its best to modify the root logger directly and thus support both 3.7 and 3.8 python versions.

Removing the use of basic_config to support python3.7

---

Tests/scripts/collect_tests_and_content_packs.py

fixes: https://github.com/demisto/etc/issues/31064
We should not collect tests based on changes for the metadata file, only for changes in relevant files like py/yml/etc...
Delete the part of the code that added all Pack's tests after a change in metadata file.
**Before** my fix in collect tests, the build looks like this: (with a minor change in CommonScripts/AddKeyToList.py):
https://app.circleci.com/pipelines/github/demisto/content/50016/workflows/44eca69c-16b2-44cf-b109-94132b1e1d61/jobs/212942
**After** my fix in collect tests , the build looks like this: (with a minor change in CommonScripts/AddKeyToList.py):
https://app.circleci.com/pipelines/github/demisto/content/50017/workflows/5f5dfe24-f6ae-4857-9a37-d829ff0bc83a/jobs/212945
So, seems like only relevant tests …

Collect tests only in relevant files

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/ReleaseNotes/1_2_6.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31548
if a notable event raw field was provided in the `extractFields` integration parameter wrapped in double quotes, and the field does not exist in the event, then splunk returns it anyway with the value equals the key
added iteration over the event keys to check for that, and replace value with empty string in that case

Splunk - handle notable raw fields where key equals value

---

Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
Packs/ExportIndicators/ReleaseNotes/1_0_1.md
Packs/ExportIndicators/pack_metadata.json

Fixes https://github.com/demisto/etc/issues/31588
in the indicator object does not have the `value` field, a `KeyError` would be raised:
```
Traceback (most recent call last):
File "<string>", line 5938, in route_list_values
File "<string>", line 5780, in get_outbound_ioc_values
File "<string>", line 5362, in refresh_outbound_context
File "<string>", line 5697, in create_values_for_returned_dict
File "<string>", line 5601, in create_json_out_format
File "<string>", line 5611, in json_format_single_indicator
KeyError: 'value'
```
changed the `del` to `pop` with `None` as default value to avoid the `KeyError`

Export Indicators - pop instead of del indicator value

---

.circleci/config.yml
Tests/scripts/is_file_up_to_date.sh

Validating requirements files are updated.
Used the same validation we currently have for the config.yml to avoid a situation where the sdk version has changed with some validations but builds that are not updated with it can still pass and then potentially fail master builds.
fixes: https://github.com/demisto/etc/issues/29249

Validating requirements files are updated

---

Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/31463
- Fixed rasterize test playbook - now scanning google instead of github
- Removed rasterize test from skipped

Rasterize test failure fix

---

Tests/conf.json

Test playbook uses random string to create a policy and there is no command to delete a policy so there is no way to test create a policy without a random uuid.

Unmocking integration with random uuid

---

Tests/mock_server.py
Tests/test_content.py

https://github.com/demisto/etc/issues/31693
This is a preparation PR for using proxy in installation step.
This implements the following changes:
- Implementing a proxy context manager
- using this context manager in the current build flow
- Renaming **playbook_id** parameter in the mock_server.py to  **playbook_or_integration_id**
This PR does not have any actual changes to the build - it's mostly refactoring.
This affects nightly build mostly and therefore attaching a nightly build that achieved pretty much the same results as today's nightly - https://app.circleci.com/pipelines/github/demisto/content/52233/workflows/06d72ac6-7101-4aa2-8b01-979b94192d2e/jobs/220537

Adding proxy context manager

---

Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/31741
Due to regression, the encryption of private packs was not working as expected.
This issue is now fixed.

fixing the encryption of private packs

---

Tests/timestamp_replacer.py

As can be seen from the attached photo - there are integration who can send the same request with different order in the params which will cause the proxy to miss the request
This PR should solve it.

Sorting query data to get the same request

---

Packs/PagerDuty/Integrations/PagerDuty/PageDuty_test.py
Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
Packs/PagerDuty/ReleaseNotes/1_0_2.md
Packs/PagerDuty/TestPlaybooks/playbook-PagerDuty_Test.yml
Packs/PagerDuty/pack_metadata.json

in version 1.0.1 of the pack, the global params assign was moved to the main func
because the command functions are called with `**demisto.args()` and the `ServiceKey` param as default value, what happened is commands that use the service key now got an empty string and failed

PagerDuty - revert global params assign

---

.circleci/config.yml

https://github.com/demisto/content/pull/9992
Bucket validations should be executed right after uploading to the bucket

Moving premium packs validation to after the upload

---

Tests/Marketplace/Tests/search_and_install_packs_test.py
Tests/Marketplace/search_and_install_packs.py

* In case all packs installation fails - log and raise the original error instead of raising a new one in `find_malformed_pack_id` method.
* Before running max on server versions returned from bucket - validate there are versions to avoid unclear exception and continue installing packs without that pack
* Added some logs

Improved nightly packs installation error handling

---

Tests/mock_server.py

Attempting to push to repo content-test-data during the build fails with the error:
```
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
```
This PR resets the repo before attempting to rebase in order to overcome this.

Clean repo before attempting to rebase

---

Tests/conf.json

The correlation playbook cannot be run under mock for multiple branches.

Unmocking Qradar integrations

---

Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX_test.py
Packs/FireEyeHX/ReleaseNotes/1_0_8.md
Packs/FireEyeHX/pack_metadata.json
Tests/conf.json

fixes https://github.com/demisto/etc/issues/31972
fixes https://github.com/demisto/etc/issues/24935
handle the case where `event_values ` property in the alert object is a list
see failing test at https://app.circleci.com/pipelines/github/demisto/content/54054/workflows/cd44cfae-b6da-46a6-8d9d-62343b05b480/jobs/227246

FireEye HX - handle alert parse with event_values as list

---

Tests/conf.json

Ready
fixes: https://github.com/demisto/etc/issues/26784
fixes: https://github.com/demisto/etc/issues/26783
Added `pid_threshold` to try and prevent phishing tests from randomly failing with the error that the integration instances are disabled, following ItayK's suggestion https://panw-global.slack.com/archives/G011E63JXPB/p1606639527468400

Added pid_threshold to phishing tests in conf.json

---

Packs/CrowdStrikeFalconSandbox/.secrets-ignore
Packs/CrowdStrikeFalconSandbox/TestPlaybooks/playbook-Detonate_URL_-_Crowdstrike_Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/30879
I changed google.com because it failed and it's a crowdstrike bug because it also failed in the UI

Fixed [Test-Failure] Test-Detonate URL - Crowdstrike

---

Packs/FireEyeHX/TestPlaybooks/playbook-FireEyeHX_Test.yml

fixes: https://github.com/demisto/etc/issues/24935

FireEye HX Test - use uri_name in append indicators only for custom category indicators

---

Tests/conf.json

Ready
fixes: demisto/etc#26784
fixes: demisto/etc#26783
Increased `pid_threshold` to 60 which is above 57 as suggested in the failed build:
https://app.circleci.com/pipelines/github/demisto/content/55041/workflows/dbb478cc-9d66-43c3-9c25-72c6f6d85ff5/jobs/231331

Increased phishing tests threshold

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_11.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32072
in case of 403, `http_request` was called again with `headers` passed to `files` which led to `415 - Unsupported Media Type`

CrowdStrike Falcon - call http_request args positional in case of 403

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
Packs/UrlScan/Integrations/UrlScan/Urlscan_test.py
Packs/UrlScan/Integrations/UrlScan/test_data/capitalne.json
Packs/UrlScan/ReleaseNotes/1_0_6.md
Packs/UrlScan/pack_metadata.json
Tests/conf.json

fixes https://github.com/demisto/etc/issues/31551
This PR fixes the urlscan bug:
- Removes two endless loops
- Uses api-key in all requests to enjoy the extended rate limit
- Added logs for better debugging

Fixing urlscan bug

---

Packs/CrowdStrikeFalconStreamingV2/Integrations/CrowdStrikeFalconStreamingV2/CrowdStrikeFalconStreamingV2.py
Packs/CrowdStrikeFalconStreamingV2/ReleaseNotes/1_0_15.md
Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32102
storing sample events only if the obj size is no more than 1mb

CS Streaming v2 - verify stored event object is no more than 1 mb

---

Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_13.md
Packs/MicrosoftCloudAppSecurity/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32013
since we use `date gte` filter, added `1` to last fetch timestamp in case incidents were fetched to avoid duplicates in the next fetch since if 2 or more alerts occurred in the same time we would fetch dups

MCAS - add 1 to last fetch if incidents were fetched

---

Tests/configure_and_test_integration_instances.py

Running test-module in record mode after playback mode failure in post-update instead of pre-update

Running a record mode in post update instead of pre update

---

Packs/CortexDataLake/TestPlaybooks/Cortex_Data_Lake_Test.yml

fixes: https://github.com/demisto/etc/issues/24346
The file_data table was queried with expired time filter, removing it allowed it to receive the old records and pass the playbook

Removed date filtering from CDL test playbook

---

Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
Packs/MailListener/ReleaseNotes/1_0_2.md
Packs/MailListener/pack_metadata.json

revert removal of the `last_fetch` attribute from the last run object which stored the last fetch timestamp done in https://github.com/demisto/content/pull/10223
using it only for the first fetch after upgrading (when the last uid is `1`) and after that will use only the uid as criterion to fetch from

Mail Listener v2 - revert removal of last_fetch from last run

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/23795
Removed **VxStream** from skipped and from **Detonate File - Generic Test** requirements.

[tests] Removed VxStream from skipped

---

.circleci/config.yml
dev-requirements-py2.txt
dev-requirements-py3.txt

Updated client version and added env variable with which the client will not cache it's last response
##Related issues:
fixes: https://github.com/demisto/etc/issues/30292

Updating demisto-client to not cache last response

---

Tests/mock_server.py
Tests/test_content.py

fixes: https://github.com/demisto/etc/issues/31887
After a successful record - run another playback run on this new

Add a playback run after record

---

Tests/conf.json

The command: 
```
!hashicorp-enable-engine path="test_1609389451541 " type="kv"
```
sends request to the url 
```
<BASE_URL>/mounts/test_1609389451541%20
```
therefore it is unmockable

unmocking HashiCorp Vault

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27846
add Carbon Black Enterprise Protection V2 to skip list - expired license.

add Carbon Black Enterprise Protection V2 to skip list

---

Documentation/common_server_docs.py
Packs/Base/ReleaseNotes/1_6_2.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json
Packs/DeveloperTools/TestPlaybooks/playbook-TestCommonPython.yml
Packs/DeveloperTools/TestPlaybooks/script-TestPyCommonServer.yml

Handle python warnings. Currently if a library issues a warning it goes to stderr which will create an error entry (see test PB). This PR changes so we log it to `demisto.info`.

CommonServerPython: add handler for py warnings

---

Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.py
Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
Packs/CortexXDR/ReleaseNotes/2_7_3.md
Packs/CortexXDR/pack_metadata.json

When proxy checkbox was not checked out - proxy was still used

Fixed an issue where proxy wasn't ignored when configured

---

Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/Integrations/Slack/Slack_test.py

skipping unstable slack unit test
related: https://github.com/demisto/etc/issues/32385

skip unstable test UT

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26905
I performed the following steps:
1. Cleanup instance from old results (reduce timeout).
2. Removed mock, Has it work as expected (Cleanup didn't performed has expected).
Now the cleanup process occur without any error.

MISP V2 - nightly failure

---

Packs/SumoLogic/Integrations/integration-SumoLogic.yml
Packs/SumoLogic/ReleaseNotes/1_0_4.md
Packs/SumoLogic/pack_metadata.json

https://github.com/demisto/etc/issues/32021
in https://github.com/demisto/content/pull/9208 we modified the last fetch to not be now time
this seem to cause timeouts when fetching aggregate records with big queries

SumoLogic - set last fetch to now time for agg records

---

Packs/Base/ReleaseNotes/1_6_3.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fixes: demisto/etc#32401
The log is filtered in info but not in the Content part.
For more information please look at the issue.

Logs aren't return as we expect from common server python

---

Packs/Slack/Integrations/Slack/Slack_test.py

Removed skip of `test_fail_connect_threads` ut as it passes.
https://github.com/demisto/etc/issues/32385

Slack UT - removed skip 

---

Packs/CommonScripts/Scripts/script-EmailAskUser_README.md

fixes: https://github.com/demisto/content-docs/issues/385
Improvements to email ask user.

Update email ask user readme

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/copy_and_upload_packs.py
Tests/Marketplace/marketplace_services.py
Tests/Marketplace/upload_packs.py
Tests/scripts/slack_notifier.py

Revert "Upload Flow - Reduce API Calls"

---

Tests/instance_notifier.py
Tests/scripts/slack_notifier.py
Tests/test_content.py

In the latest sdk release the slack version was updated to 2.9.3 from 1.x.x which have some breaking changes.
This PR is about updating the usage of slack client to support 2.9.3 version according to this documentation
https://github.com/slackapi/python-slack-sdk/wiki/Migrating-to-2.x

Supporting new slack client

---

Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml

fixes: https://github.com/demisto/etc/issues/26905
After removing all duplicate data form instance, Found the source of the following error:
```
[2021-01-10 01:33:22] - [Thread-5] - [ERROR] - MISP V2 Test failed with error/s
[2021-01-10 01:33:23] - [Thread-5] - [ERROR] - Playbook MISP V2 Test has failed:
[2021-01-10 01:33:23] - [Thread-5] - [ERROR] - - Task ID: 12
[2021-01-10 01:33:23] - [Thread-5] - [ERROR] -   Command: !misp-delete-event event_id="11173"
[2021-01-10 01:33:23] - [Thread-5] - [ERROR] -   Body:
Event ID: 11173 has not found in MISP: 
Error message: {'errors': [(403, {'name': 'Could not delete Event', 'message': 'Could not delete Event', 'url': '/events/delete', 'errors': 'Event was not deleted.'})]}
[2021-01-10 01:33:23] - [Thread-5] - [ERROR] - - Task ID: 12
[2021-01-10 …
```

MISP V2 - Fix test playbook

---

Packs/BPA/TestPlaybooks/playbook-BPA-test.yml

fixes: https://github.com/demisto/etc/issues/28406
Changed the context of the GenericPolling sub-task to be private. This should prevent the generic polling to finish the task before the creation of the BPA request has completed.

BPA Playbook Fix

---

Packs/Whois/TestPlaybooks/playbook-Whois-Test.yml
Tests/conf.json

Apparently, Google renews their domains... who woulda thought?
Fixes: https://github.com/demisto/etc/issues/25648

Fix for Failing Whois Test PB

---

Tests/conf.json

Ansible tower test playbook call Launch Job playbook as sub-playbook with specific parameters. Launch Job playbook was than added to conf.json in order the instance recognize him. This apperently was not needed, only insert the playbookName of the called sub-playbook on the test playbook. Removed Launch Job playbook details from conf.json

Remove Launch job details from conf.json

---

Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.py
Packs/ThreatConnect/Integrations/ThreatConnect_v2/ThreatConnect_v2.yml
Packs/ThreatConnect/ReleaseNotes/2_0_11.md
Packs/ThreatConnect/pack_metadata.json

relates: https://github.com/demisto/etc/issues/32208
- Updated the code in ***tc-create-document-group*** command to use the *security_label* argument correctly.
- Removed the *updatedValues* argument from the ***tc-update-indicator*** since it is not in use and the customer can use the regular args instead.

ThreatConnect v2- Removed and fixed arguments

---

Tests/Marketplace/marketplace_services.py

Fixed the default value of `contentCommitHash` when it does not exist in user_pack_metadata

fix default contentCommitHash

---

Packs/ApiModules/Scripts/HTTPFeedApiModule/HTTPFeedApiModule.py
Packs/FeedBlocklist_de/ReleaseNotes/1_0_3.md
Packs/FeedBlocklist_de/pack_metadata.json
Packs/FeedBruteForceBlocker/ReleaseNotes/1_0_3.md
Packs/FeedBruteForceBlocker/pack_metadata.json
Packs/FeedCloudflare/ReleaseNotes/1_0_3.md
Packs/FeedCloudflare/pack_metadata.json
Packs/FeedDShield/ReleaseNotes/1_0_3.md
Packs/FeedDShield/pack_metadata.json
Packs/FeedFeodoTracker/ReleaseNotes/1_0_5.md
Packs/FeedFeodoTracker/pack_metadata.json
Packs/FeedMalwareDomainList/ReleaseNotes/1_0_3.md
Packs/FeedMalwareDomainList/pack_metadata.json
Packs/FeedPlainText/ReleaseNotes/1_0_4.md
Packs/FeedPlainText/pack_metadata.json
Packs/FeedSpamhaus/ReleaseNotes/1_0_3.md
Packs/FeedSpamhaus/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32934
added a call to `handle_proxy` in the HttpApiModule.
manually tested the following configurations:
* proxy configured:
* used the proxy only when enabled.
* if enabled and MITM didn't run, failed with ProxyError.
* proxy isn't configured:
* never used the proxy

Add handle proxy to http api module

---

Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
Tests/conf.json

- Made Cryptocurrency-Test unmockable
- Added Cryptocurrency integration to parallel integrations
- Increased timeout for Tenable.io test from 900 seconds to 1400 seconds.
- ExpanseV2 has a client which filters the response according the created-at field, Modified the `ExpanseV2 Test` to get the response date for that instead of the incident creation date (which is the current time) in order to make the mocked responses pass this filtering.

Modifying content to support proxy

---

Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.py
Packs/ServiceDeskPlus/Integrations/ServiceDeskPlus/ServiceDeskPlus.yml
Packs/ServiceDeskPlus/ReleaseNotes/1_2_2.md
Packs/ServiceDeskPlus/pack_metadata.json

relates: https://github.com/demisto/etc/issues/32208
- Updated the code to use the *update_reason* argument in the ***service-desk-plus-request-update*** command.
- The *status_change_comments* argument was removed from the ***service-desk-plus-request-update*** command - We don't get it in the response json and are not able to see it updating in the UI.

ServiceDeskPlus - fixed args

---

Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/1_2_7.md
Packs/SplunkPy/TestPlaybooks/playbook-SplunkPy-Test-V2.yml
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31663
Added the **count** argument to **splunk-results** command to control the number of returned results.

added count argument to splunk-results command

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py

Fixed KeyError exception in splunk_edit_notable_event_command in SplunkPy integration
I'm getting a KeyError exception when trying to edit a notable with in the SplunkPy integration. This change will prevent an exception from being raised when the response content is different than what is expected.

SplunkPy Integration - Fixed KeyError exception

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_12.md
Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Packs/CrowdStrikeFalcon/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32072
in case 403 occurred, not all args (`files` in this case) were passed on the second call to `http_request`

CrowdStrike Falcon - pass missing args in retry when encountering 403

---

.circleci/config.yml
Tests/scripts/slack_notifier.py

- Triggered both uploads to 11 (AM & PM) to prevent race conditions with nightly.
- Fixed an issue in Slack notifier where failed pack status was the name of the enum and not its value.

Earlier Upload-Flow trigger

---

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
Packs/Elasticsearch/ReleaseNotes/1_1_4.md
Packs/Elasticsearch/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33177
fixed incident labels representation.
in the case of JSON values, we returned `{'is_ok': True}` instead of `{"is_ok": true}`.
screenshots with the fix posted in the issue.

Elasticsearch v2: fixed incident labels representation

---

Packs/SumoLogic/Integrations/integration-SumoLogic.yml
Packs/SumoLogic/ReleaseNotes/1_0_5.md
Packs/SumoLogic/pack_metadata.json

if no records were fetched, we stored the now time
this could led to missing events in case of non synced clocks
modified to store the now time minus 1 minute

SumoLogic - store now - 1 min in case no records were fetched

---

Tests/scripts/collect_tests_and_content_packs.py

related: https://app.circleci.com/pipelines/github/demisto/content/64799/workflows/b561145c-1494-4b87-935e-8595ad971722/jobs/267676
Fix `collect_tests_and_content_packs.py` - Failed because it runs on all ID set, and Packs are in dictionary and not in list.

Fix collect_tests_and_content_packs.py 

---

Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/33340
Handled the case where pack is deprecated while handling RN.
CCI: https://app.circleci.com/pipelines/github/demisto/content/65312/workflows/05506509-c3d8-4692-89d4-44497c1b8da8
Bucket: https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/upload-flow-hidden-rn-bugfix/269737
Server Configuration: https://storage.googleapis.com/marketplace-ci-build/content/builds/upload-flow-hidden-rn-bugfix/269737

Upload flow hidden rn bugfix

---

Packs/ShiftManagement/Dashboards/dashboard-Shift_Management_.json
Packs/ShiftManagement/ReleaseNotes/1_2_2.md
Packs/ShiftManagement/Scripts/GetUsersOOO/GetUsersOOO.py
Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.py
Packs/ShiftManagement/Scripts/GetUsersOnCall/GetUsersOnCall.yml
Packs/ShiftManagement/pack_metadata.json

fixes: https://github.com/demisto/content/pull/10750
Add dashboard to Shift Management.
Fixed GetUsersOnCall and GetUsersOOO scripts message description when there are no team members on call or when no team members out of office.  

Add dashboard to Shift Management

---

Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml

fixes: https://github.com/demisto/etc/issues/33410
clone team action might take some time, increasing the sleep time to allow it to be created successfully

MS Teams Management Test - increase sleep time to alone cloned team to get created

---

Tests/conf.json

This PR implements the following:
1. Adding all tests configurations from the `update_conf_json.py` script
2. Removing the following integrations from the unmockable integrations list:
- QRadar
- DShield Feed
- QRadar_v2
- EWS v2
- jira-v2
- Rundeck
- ServiceDeskPlus
- AWS - EC2
3. Making the following test playbooks unmockable:
- Rundeck_test
- playbook-DshieldFeed_test
- test_Qradar
- pyEWS_Test
- Jira-v2-Test
- EWS Public Folders Test
- test playbook - QRadarCorrelations For V2
- test playbook - QRadarCorrelations
- Service Desk Plus Test

Reverting unmockable integrations and adding all tests

---

Packs/FeedCyjax/pack_metadata.json

Fix author field in pack_metadata to be the vendor name.

fixed author field in pack_metadata.json

---

Tests/conf.json

Ready
fixes: https://github.com/demisto/etc/issues/26784
Increased phishing tests pid threshold to 80 according to recommendation in the failing build (it used to be 60):

Increased phishing tests pid threshold to 80

---

Packs/TaniumThreatResponse/.pack-ignore
Packs/XMatters/.pack-ignore

Adding .pack_ignore in order to pass validation in https://github.com/demisto/demisto-sdk/pull/1077

context validation fix - added pack ignore

---

.circleci/config.yml

Creating the ssh tunnel in the `Upload Packs To Marketplace` job as well.
In the `Upload Packs To Marketplace` job the step - `Validate Premium Packs` sends https requests to the server under the role of `Server Master`.
In order for that to succeed the ssh tunnel needs to be opened in that job as well.
Related issue: https://github.com/demisto/etc/issues/32500

Creating tunnel in Pack upload job

---

Tests/scripts/update_conf_json.py

Since circle has 36 cpu's but only 2 vcpus in the reasource type we use - using cpu_count in the process poll creates overhead of switching processes and drains the RAM.

Create 4 processes instead of cpu_count number

---

.circleci/config.yml

Otherwise the tunnel will not be created.

Making Upload Packs To Marketplace job aware that the instance was created

---

.github/workflows/check-contributor-pack.yml
.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

fixes: https://github.com/demisto/etc/issues/33603
Limited the execution of the project manager workflows to `demisto/content` only.
Also limited execution of `Check contributor packs` workflow to `demisto/content` only.

[Project Manager] Limit workflow execution to demisto/content

---

Tests/scripts/validate.sh

Fixed the script validate.sh. In case the current branch is a contrib's, we change the file path of id_set creation (id_set file will be saved in the other path).
link to a PR includes a validate that works with the change: https://github.com/demisto/content/pull/11339

fix validate.sh for contributions

---

Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_4.md
Packs/Carbon_Black_Enterprise_Response/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32446
adding limit argument to `cb-list-sensors` command

adding limit argument to `cb-list-sensors` command

---

Packs/Slack/Integrations/Slack/README.md
Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/Integrations/Slack/Slack.yml
Packs/Slack/Integrations/Slack/Slack_test.py
Packs/Slack/ReleaseNotes/1_3_14.md
Packs/Slack/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33477
- Improved the 'message' argument description to prevent further issues.
- Added the raw response to the 'Contents' entry in the send-notification command.
- 

Slack v2 Improved argument description

---

Tests/conf.json

- Cylance Protect
- WildFire-v2
- carbonblackliveresponse
- ServiceNow v2
- Hybrid Analysis
- VirusTotal - Private API
Unmocking the following playbooks:
- servicenow_test_v2
- Detonate URL - WildFire-v2 - Test
- Carbon Black Live Response Test
- get_file_sample_by_hash_-_cylance_protect_-_test
- Retrieve File from Endpoint - Generic V2 Test
- HybridAnalysis-Test
- Wildfire Test
- test_Qradar_v2
https://github.com/demisto/etc/issues/33414

Mocking the following integrations:

---

Packs/Base/ReleaseNotes/1_7_14.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

Not every mirrored object uses the `id` field to store its unique identifier, e.g. Splunk uses the `event_id` field.

CSP GetRemoteDataResponse Bugfix

---

Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2.py
Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2_test.py
Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/README.md
Packs/ProofpointServerProtection/ReleaseNotes/2_0_3.md
Packs/ProofpointServerProtection/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33754
removed the `:` from the timezone sent in the `to` and `from` params in the smart search api

Proofpoint Protection Server v2 - adjust smart search from and to params to pps on prem v8.14.2

---

Tests/conf.json

Making 'vt-detonate test' unmockable since it uploads a file

Making 'vt-detonate test' unmockable since it uploads a file

---

Packs/SailPointIdentityIQ/README.md

fixes: https://github.com/demisto/etc/issues/33982
fix SailPointIdentityIQ readme links that were not pointing to the file path in the relevant commit, but was pointing to the relative path.

fix SailPointIdentityIQ readme links

---

Packs/FireEyeETP/Integrations/FireEyeETP/FireEyeETP.py
Packs/FireEyeETP/ReleaseNotes/1_0_2.md
Packs/FireEyeETP/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33864
Fixed a bug in the `fireeye-etp-get-alerts` command that was caused due to direct access to the response fields. This caused a `KeyError` exception when some fields were missing in the response.
Couldn't add UTs as we don't have an instance of the product.

FireEye ETP get-alerts Fix

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/EDL.yml
Packs/EDL/Integrations/EDL/README.md
Packs/EDL/ReleaseNotes/1_0_9.md
Packs/EDL/pack_metadata.json

https://github.com/demisto/etc/issues/33437
Added a new parameter **XSOAR Indicator Page Size**. Allows modifying the internal page size used when querying XSOAR for the EDL.

[EDL] Add new parameter page_size

---

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
Packs/GenericSQL/Integrations/GenericSQL/GenericSQL_test.py
Packs/GenericSQL/Integrations/GenericSQL/README.md
Packs/GenericSQL/ReleaseNotes/1_0_9.md
Packs/GenericSQL/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/30431
- Added support for Microsoft SQL Server - MS ODBC Driver
- Replaced the URL creation with the OOTB sqlalchemy URL class.

Added support for the Microsoft SQL Server - MS ODBC Driver

---

Packs/Base/TestPlaybooks/playbook-CheckDockerImageAvailableTest.yml

fixes: https://github.com/demisto/etc/issues/30117
modify the test to work against xsoar-registry.pan.dev due to docker rate limit

CheckDockerImageAvailableTest - modify test to work against xsoar-registry.pan.dev

---

Tests/scripts/destroy_instances.py
Tests/scripts/wait_until_server_ready.py

- Using docker credentials with read only permissions.
- Leaving the instances logged in to docker when build finishes.

docker login with read only creds and leave instances logged in

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/33761
Added a function to remove the contribution details from the integration display name.
**This modification takes place *after* the upload step and affects only the integration top-level entry in the parsed metadata file.**
After changes:

Marketplace: Remove Contrib Suffix

---

Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.py
Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3_test.py
Packs/MailListener_-_POP3/ReleaseNotes/1_0_2.md
Packs/MailListener_-_POP3/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34065
non-utf-8 characters will now be replaced by the u+fffd character filler.
Failing UT before the change: https://app.circleci.com/pipelines/github/demisto/content/69605/workflows/16554cfe-0c29-4fd5-b4d3-cd76acff9036/jobs/287218
Waiting for sample email for PB

Mail Sender pop3 beta - bug fix from contrib

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26465 
fixes: https://github.com/demisto/etc/issues/19205
Unskipping PAN-OS -Create or edit rule and DAG configuration test playbooks 
- [x ] No

Unskipping Test Playbooks for PAN-OS

---

Packs/ServiceDeskPlus/TestPlaybooks/playbook-Service_Desk_Plus.yml

fixes: https://github.com/demisto/etc/issues/29026
Update all tasks UUID as they were duplicated in a new contribution integration.
The test failed because a new contribution of SDP on-prem was added. In this integration, the original SDP TPB was copied resulting in two playbooks with identical task UUIDs. Therefore, when testing the original SDP test PB, it tried to access the on-prem instance and failed.

SDP TPB fix

---

Tests/configure_and_test_integration_instances.py

The failure of the pre-update content installation should not fail the build if the post update installation was successful.

Don't fail the build in case pre-update installation fails

---

Tests/conf.json

Since powershell images takes more resources than the python images - we need to update the thresholds.

update docker threshold for powershell images

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/ReleaseNotes/1_2_12.md
Packs/Jira/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34425
In the HR entry, under project name we should get the project name and not `issueTypeName`
- x] No

Jira fix create ticket HR

---

Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/ReleaseNotes/1_2_13.md
Packs/Jira/pack_metadata.json

Outh 1 flow broken with the new docker image:

bump back jira docker version because Outh1() was broken

---

Packs/MicrosoftGraphAPI/Integrations/MicrosoftGraphAPI/README.md

some graph apis do not support the `top` resource, which is the default value of the `odata` command argument
added a note to the readme how to handle that case

Microsoft Graph API - add note about in case unsupported top resource

---

Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity.py
Packs/JoeSecurity/ReleaseNotes/1_0_4.md
Packs/JoeSecurity/TestPlaybooks/playbook-JoeSecurityTestDetonation.yml
Packs/JoeSecurity/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34605

Joe Security - non english chars

---

.github/workflows/check-contributor-pack.yml
.github/workflows/handle-new-external-pr.yml

fixes: https://github.com/demisto/etc/issues/34742
This fix should avoid triggering github workflows for PRs created during test_integration run.

Avoid test contrib PR to trigger gh workflows

---

Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.yml
Packs/MailListener/ReleaseNotes/1_0_3.md
Packs/MailListener/pack_metadata.json

fixed an issue where the `first_fetch_time` was only respected in the first fetch interval, and then from the second fetch interval the fetch was by uid
this led to emails that were received before the `first_fetch_time` to be ingested as incidents
fixed by passing the `first_fetch_time`  or the `last_fetch` (for bc) in every fetch iteration and modify the condition to verify both mail date and mail uid

Mail Listener v2 - improve handling of first fetch time

---

Packs/MicrosoftTeams/TestPlaybooks/Microsoft_Teams_Management_-_Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/33410
in the test, after we add a member to the cloned team, we list the team members and then make that user the team owner
the issue was that the member was not listed in the team members because it could take some time for the member to be added, so added a sleep to wait a bit

MS Teams MGMT - add sleep after adding user to cloned team

---

Packs/Tidy/Integrations/Tidy/README.md

Usually, the main bottleneck in an on-boarding process is the installations that needs to be done on the new recruit's computer.
Whether if it's a developer, customer success or product, it takes about three days to make everything up and running and usually help is required from other colleagues as well.
The **Tidy** pack enables you to reduce the on-boarding process time of a new recruit to matter of minutes.
The **Tidy** pack uses **Ansible** to connect to the new recruit's laptop over ssh and executing predefined commands.
With the **Tidy** pack you can create a role based playbook that will execute all installations a new recruit needs.
- Install languages with specific versions (currently python, node and go are supported).
- Creating a github ssh key and cloning all the relevant …

Adding a README to the tidy pack

---

.circleci/config.yml
dev-requirements-py3.txt

- Changing LB port from 22 (default) to 43567.
- Changing LB ssh user from `ec2-user` to `content-build`
- Temporarily replaced the LB address, once this configuration can be merged into master - we will change it back to `content-build-lb.demisto.works` as the routing to the specific lb is done via route53 configuration.
fixes: https://github.com/demisto/etc/issues/33859

Supporting build hardening

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_services.py
Tests/scripts/slack_notifier.py

fixes: https://github.com/demisto/etc/issues/34430
The server minimum version of a pack will be **lowest** fromversion of the pack's content items.
Note:
1. All packs server minimum version is being computed during runtime (of upload-flow), so we expect some packs to change their min version.
2. If a pack was released as 6.0.0 (lowest fromversion is 6.0) and a 5.0 integration was added then the pack min server ver will change to 5.0.0.
- [Successful trigger test upload](https://app.circleci.com/pipelines/github/demisto/content/75057/workflows/9c5910b3-9aea-448e-a9fd-12aeffbde3f5)
- Base's server min version was changed from 5.5.0 to 5.0.0:
- Slack msg:

Server min version bugfix

---

Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Tests/scripts/utils/collect_helpers.py
Tests/scripts/utils/get_modified_files_for_testing.py
Tests/scripts/utils/tests/content_packs_util_test.py
Tests/scripts/utils/tests/test_get_modified_files_for_testing.py

fixes: https://github.com/demisto/etc/issues/34750
Added a method `get_packs_from_landing_page`, that parses the diff of the landing page sections file into modified packs.
These will be added to the packs that should be installed and in the `Prepare Content Packs For Testing` it's metadata will be updated with the newest and the packs will be installed on the server instances.
In addition -  modified the `get_modified_files_for_testing` method to return a class instead of tuple to make refactoring of that method a bit easier (no need to update all the places this method is called if there is a need to edit its output.
Most of this PR is about modifying the unittests to support this change.

Updating index and metadata of packs with changed tags

---

Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.ps1
Packs/EWS/ReleaseNotes/1_8_8.md
Packs/EWS/pack_metadata.json

ews search and compliance: return info file entry

---

Tests/Marketplace/download_private_id_set.py

Part of https://github.com/demisto/etc/issues/33958
Adding the option to set a storage base path for downloading the private id set

download_private_id_set storage_base_path arg

---

.circleci/config.yml

removed the individual pack zips from the artifacts.
now, there will be a single zip containing all those zip files.
if it fails to zip them, it will not fail the build (and will keep the individual zip files in the artifacts)
before:
after:

Remove individual "uploadable_packs" zips

---

Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/Integrations/Slack/Slack.yml
Packs/Slack/ReleaseNotes/1_3_17.md
Packs/Slack/pack_metadata.json

When adding a list of users to channel, we shouldn't fail an invite because the user is already part of the channel.
fixes: no issue opened
Update the slack integration so if it's attempting to add a list of users to channel, and a user is already in the channel, it doesn't cause the rest of the list to fail.

Slack: Don't fail invite if user in channel

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/approved_tags.json
Tests/Marketplace/landingPage_sections.json
Tests/Marketplace/marketplace_services.py
Tests/Marketplace/upload_packs.py

fixes: https://github.com/demisto/etc/issues/34762
Added a method that queries the db for the top downloaded packs in last 14 days, and updates the 'Trending' tag with it on run time.
This way - since there is already an implementation for the landing page sections that adds the tags to the packs metadata - there is nothing else to be done.

Add support for trending packs

---

Packs/GitHub/Integrations/GitHub/GitHub.yml
Packs/GitHub/ReleaseNotes/1_1_10.md
Packs/GitHub/pack_metadata.json

https://github.com/demisto/etc/issues/33818
no code changes are required since the `algorithm` to use in the encoding is mentioned in line 53: 
```py
jwt_token = jwt.encode(payload, private_key, algorithm='RS256')
```

GitHub - bump docker image

---

Packs/EWS/Integrations/EWSv2/README.md

fixes: https://github.com/demisto/etc/issues/33461
https://github.com/demisto/etc/issues/33461#issuecomment-814899844
added a recommendation to not use the following commands in environments with more than 1M mailboxes.
- ews-get-searchable-mailboxes
- ews-search-mailbox (unless using the `mailbox-search-scope` argument)

adding limitation to the docs

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/2_0_1.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35835
fixed the human-readable header parsing to support headers with spaces
before the fix:

SplunkPy: fixed human readable header parsing

---

Packs/DBotTruthBombs/README.md
Tests/Marketplace/marketplace_services.py

1. remove search rank increment for DBot Truth Bombs pack
2. added note in DBot Truth Bombs pack that it was "Published as part of April fool's"
Prefer not to release a new version if possible

revert DBot Truth Bombs search rank exception

---

Tests/Marketplace/copy_and_upload_packs.py

fixed an issue where the `index.zip` was copied to be `index.json` due to using the `index.zip` blob
created a new blob for the `index.json` to copy from

Copy and upload - copy index.json from dedicated blob

---

Tests/scripts/utils/get_modified_files_for_testing.py

Moving FileType extention from content repo to the sdk in order to support python 3.9
https://github.com/demisto/demisto-sdk/pull/1219

Moving FileType extention from content repo to the sdk

---

Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job.yml

Playbook opens an incident type "CDL - FW logging - action required" while this incident type does not exist anymore. It should call the new incident type instead "PAN-OS logging to Cortex Data Lake - Action Required"

Playbook was not calling the proper incident type

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
Packs/CortexXDR/ReleaseNotes/3_0_6.md
Packs/CortexXDR/ReleaseNotes/3_0_7.md
Packs/CortexXDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35860
Added milliseconds calculation since the last_mirrored_in_time was not calculated correctly caused incidents to not update from XDR in the incoming mirroring

XDR - added milliseconds to time calculation

---

Packs/Base/ReleaseNotes/1_10_3.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

related: https://github.com/demisto/etc/issues/33050
In the last run in searching indicator an unnecessary error was raised.

Fixing an error that was raised in Search Indicators

---

Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.py
Packs/FeedIntel471/ReleaseNotes/1_1_3.md
Packs/FeedIntel471/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36170
changed the default indicator_type from "Threat Actor" to "STIX Threat Actor" because there isn't a "Threat Actor" indicator type in our system.

Fixed an issue when fetch-indicators command had a wrong default value for "indicator type"

---

Tests/Marketplace/remove_existing_pack_from_private_id_set.py

When using the script `remove_existing_pack_from_private_id_set.py` it saves the json file without indent, added `indent=4` solved it.
before:
after:

Add indent when saving json file

---

Tests/configure_and_test_integration_instances.py

Adding `--network=host` on podman containers to solve the latest podman issue with the proxy.
Build example: https://app.circleci.com/pipelines/github/demisto/content/82083/workflows/c2837755-91c8-4258-a83b-84b6fdc17e3e/jobs/339270 (Follow `Thread-10` in the logs)

Running with --network=host on RHEL instances

---

Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
Packs/TAXIIServer/ReleaseNotes/1_0_3.md
Packs/TAXIIServer/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32567
New docker image causes failures.
Downgraded.
Needs force merge.

Taxii Server - docker image update + TPB

---

Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_5_2.md
Packs/FeedCyrenThreatInDepth/pack_metadata.json

N/A
Replaced `meilke` Github user with new list of users in Cyren TID pack metadata.
N/A

Cyren Threat InDepth: replaced githubUser list

---

.circleci/config.yml

In the new env - GCS keys are files, not strings.

Supporting zipping content packs from GCS on master branch

---

Tests/conf.json

remove Cylance Protect from the tests because it’s deprecated.

remove Cylance Protect from unmockable list

---

Packs/Intezer/Integrations/IntezerV2/IntezerV2.py
Packs/Intezer/Integrations/IntezerV2/IntezerV2.yml
Packs/Intezer/Integrations/IntezerV2/IntezerV2_description.md
Packs/Intezer/Integrations/IntezerV2/README.md
Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_Uploaded_file.yml
Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_Uploaded_file_README.md
Packs/Intezer/Playbooks/playbook-Intezer_-_Analyze_by_hash.yml
Packs/Intezer/README.md
Packs/Intezer/ReleaseNotes/1_1_0.md
Packs/Intezer/pack_metadata.json

Add get the latest available report of a file instead of analyzing it)

feat(intezer): add latest report command

---

Tests/Marketplace/marketplace_services.py

Currently, packs are being shown as "Coming Soon" due to a small bug in pack metadata parsing, specifically the handling of the `previewOnly` metadata label.
This issue is now fixed.

fixing handling of premium packs' pack metadata

---

Packs/MISP/Integrations/MISP_V2/MISP_V2.py
Packs/MISP/ReleaseNotes/1_0_7.md
Packs/MISP/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36547
fixed an issue where the max_attribute conversion to int failed after upgrading the pack from version 1.0.4 (instance was configured on a version without that parameter).
a workaround for the bug is to open the instance configuration and save it.

MISP v2: fixed an issue with max attribute parameter after upgrade

---

.gitlab/ci/on-push.yml
Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py

Supporting release branches
No need to create and run server 6.0 and server Master builds in case of release branch.
fixes: https://github.com/demisto/etc/issues/34303

Adding support in release branches

---

.gitlab/ci/on-push.yml

When test playbook part fails (in nightly for example), the gitlab job stops execution and skips the instance destruction, and slack notification.

Allowing server scripts to continue when one of the step fails

---

Packs/Base/ReleaseNotes/1_10_25.md
Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.yml
Packs/Base/pack_metadata.json

Due to servers change when no results now null is returned instead of empty list, added a protection on our end.

Search relationships fix

---

.gitlab/ci/global.yml
.gitlab/helper_functions.sh

Enables the use of `section_start` and `section_end` bash functions for collapsible sections in GitLab job logs as detailed [here](https://docs.gitlab.com/ee/ci/jobs/index.html#custom-collapsible-sections).

Add section_start and section_end helper functions

---

Tests/scripts/validate_premium_packs.py

Not validating that `HelloWorldPremium` is on the premium server packs page. 
It isn't there, by design (for now) since we reduced its price to 0.

fixing validation

---

Tests/scripts/should_lint_all.sh

fixes: https://app.circleci.com/pipelines/github/demisto/content/85585/workflows/1d119463-a1a5-4c85-a359-abfbabfce1d2/jobs/353678/parallel-runs/0/steps/0-108
Our CircleCI builds would not compute the diff correctly because there was a typo. Therefore we would get an error like the following.
```
./Tests/scripts/should_lint_all.sh: line 37: origin/master...${$CI_COMMIT_BRANCH}: bad substitution
fatal: bad revision ''
fatal: bad revision ''
fatal: bad revision ''
fatal: bad revision ''
fatal: bad revision ''
```

Fix Typo in should_lint_all.sh

---

Packs/CommonScripts/ReleaseNotes/1_3_47.md
Packs/CommonScripts/Scripts/script-EmailAskUserResponse.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37030
in case image is embedded in the email, it will return as file entry from the server but will still contain the answer, so it is ok to consider it as valid entry type to parse

EmailAskUserResponse  - consider file entry as valid entry type to parse

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/ReleaseNotes/1_1_8.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36924
move the integration context get call to the try-except block to better handle failures in the call

Microsoft Teams - improve error handling in the channel mirror loop

---

Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/37026
All packs are essentially marked as `legacy: true` at the moment.
After this change, premium packs will be excluded from that logic, and will be `legacy: false`.

fixing private packs legacy

---

.circleci/build-requirements.txt

fixes: https://code.pan.run/xsoar/content/-/jobs/5650895
GitLab containers are using python 3.9.1 whereas the CircleCI containers are using python 3.8.5. We had set `pyspellchecker==0.5.2` in `.circleci/build-requirements.txt` to maintain compatibility with python2 but we only install these dependencies for python3 in our build so it should be fine to upgrade to the latest version. Running the `spell_checker.py` with python 3.9.1 with `pyspellchecker==0.5.2` results in an error since python 3.9 is not supported by that `pyspellchecker` version. Upgrading to the latest version resolves the issue. Additionally, there are dependency conflicts with using `pyspellchecker==0.5.2` and the `demisto-sdk` which requires a version greater than 0.6.0, as shown in the attached screenshot.

Upgrade pyspellchecker

---

.gitlab/ci/sdk-nightly.yml

The `dmst-content-team` slack channel received this [message](https://panw-global.slack.com/archives/G011E63JXPB/p1621805925116800) about the `SDK Nightly Unit Tests`. But as you can see in the GitLab [pipeline](https://code.pan.run/xsoar/content/-/pipelines/1170205) it links to, this was actually a scheduled run for the `NIGHTLY` build (check the build parameters section of the [create-instances job](https://code.pan.run/xsoar/content/-/jobs/5705693). I removed the env variable from the `demisto_sdk_nightly` jobs that was causing the `Demisto SDK Nightly`-related jobs to run on every scheduled run (nightly, instance-testing, etc.). Now the `DEMISTO_SDK_NIGHTLY` environment variable isn't set by the `Demisto SDK Nightly`-related job configurations but rather only by it being passed via …

Remove DEMISTO_SDK_NIGHTLY env var

---

Packs/ipinfo/Integrations/ipinfo_v2/README.md
Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.yml
Packs/ipinfo/ReleaseNotes/2_0_1.md
Packs/ipinfo/pack_metadata.json

the `Base URL` field is now marked as required. 

Ipinfo v2 base_url is required

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/ReleaseNotes/2_0_6.md
Packs/QRadar/pack_metadata.json

related: https://github.com/demisto/etc/issues/37360
The mirroring depends on a specific param that was added from a specific qradar server version:
https://www.ibm.com/support/pages/release-qradar-v733-fix-pack-3-sfs-733-qradar-qrsiem-20200409085709 

Qradar V3 adding clarification for the needed version for mirroring 

---

.gitlab-ci.yml
.gitlab/ci/sdk-nightly.yml
Tests/scripts/slack_notifier.py
Tests/scripts/slack_notifier.sh
Tests/scripts/utils/log_util.py

Slack notification was incorrect when triggered from GitLab *Demisto SDK Nightly*-related jobs. Updated the slack notifications scripts to accommodate the GitLab architecture.
- Revert the change that was made to the logging utility that disincluded info-level logs from being output to the GitLab CI console.
- Remove environment variables from the GitLab configuration file that had been added to test enabling color outputs in the GitLab CI console.

Change Slack Notification Scripts for GitLab CI

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/ReleaseNotes/2_1_2.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35176
Incident labels were not properly processed when the word message was in the raw data.
Introduced a fix for it.

Splunk raw labels fix

---

.gitlab/ci/global.yml

Can see an example of the validations not running in this `demisto-sdk` nightly GitLab run (where they should have) - https://code.pan.run/xsoar/content/-/jobs/5807340#queue-placeholder/containers/0
The `.run-validation` configuration which job configurations in various workflows inherit from contains an incorrect condition causing validations to not run. The condition prevented the validations from running during the current overlap period where we have the bucket upload flow in GitLab uploading to a test bucket.
> example of the validations not running in the `Demisto SDK Nightly` flow in GitLab (where they should have run).

Fix condition to only apply during bucket upload flow

---

Packs/Threat_Crowd/ReleaseNotes/2_0_1.md
Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/37577
When a change in pack has been made that doesn't requires the addition of an RN file (for example Pack README change) we now get the release notes from the bucket as it might have been aggregated.
1. https://app.circleci.com/pipelines/github/demisto/content/89423/workflows/ca874b45-c2d6-469c-8adb-c68e6c63d71b
2. (Only the create step) https://app.circleci.com/pipelines/github/demisto/content/89490/workflows/7ca59092-8cb4-4d41-92e6-8ce4f1a5f8a4/jobs/370613

Upload flow rn bugfix

---

Packs/Base/Scripts/CommonServerPython/CommonServerPython.py

changed several function arguments from 'keyword' to 'param' in order to stand in convention and too look good on xsoar.pan.dev
see this:

Fixed naming to correspond to convention

---

.gitlab/ci/on-push.yml

Reorganizes the `.gitlab/ci/on-push.yml` file.
- Two empty lines between configuration sections
- Use `section_start` and `section_end` helper functions in the `create-instances` job
- Move execution of the upload of artifacts from the `after_script` section of the `create-instances` job to the `script` section

Reorg and Tweaks for on-push GitLab Config File

---

Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
Packs/ProofpointThreatResponse/ReleaseNotes/1_0_4.md
Packs/ProofpointThreatResponse/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37757
in https://github.com/demisto/content/pull/12042 we added the first fetch param
integration instances that were configured before that change now fail with:
```
File "<string>", line 19, in <module>
File "<string>", line 6314, in parse_date_range
AttributeError: 'NoneType' object has no attribute 'strip'
```
thats because the param exist in the params dict, but with value of `None` 
setting the default by using the `or` operator
setting default to `12 hours` according to the default in the yml file

Proofpoint Threat Response - set first fetch param default value by or operator

---

Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub_test.py
Packs/AWS-SecurityHub/ReleaseNotes/1_1_2.md
Packs/AWS-SecurityHub/pack_metadata.json

in case findings were fetched, we took the latest one and stored it in the last run
on the next fetch, we used it in the filter, and then the latest one was fetched again as the filter is inclusive 
added 1ms to the date stored in the last run in case finding was fetched

AWS Security Hub - increase fetch time by 1 ms in case findings were fetched

---

Tests/Marketplace/core_packs_list.json

fixes: https://github.com/demisto/etc/issues/37776
add packs to core packs: 
- ThreatIntelligenceManagement
- ipinfo
- FeedMitreAttackv2
- FeedUnit42v2

add packs to core packs 6.2

---

Packs/DevSecOps/Integrations/GitLab/README.md
Packs/DevSecOps/README.md

Changed to use absolute urls as documented here: https://xsoar.pan.dev/docs/documentation/pack-docs#images . The images are not displaying in the marketplace.

DevSecOps: pack readme: images to absolute links

---

Packs/CommonScripts/.secrets-ignore
Packs/CommonScripts/ReleaseNotes/1_3_56.md
Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.py
Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.yml
Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting_test.py
Packs/CommonScripts/pack_metadata.json
Packs/CommonTypes/IndicatorTypes/reputation-email.json
Packs/CommonTypes/ReleaseNotes/3_0_6.md
Packs/CommonTypes/pack_metadata.json

related: https://github.com/demisto/etc/issues/26601
fixed the regex to include all the allowed characters according to the [IETF standard](https://datatracker.ietf.org/doc/html/rfc3696#section-3)

ExtractEmailV2: fixed local-part detection

---

.circleci/config.yml
.gitlab/ci/global.yml

Removes from the CircleCI commit workflow the testing against live cortex XSOAR instances (because that now runs in GitLab).
Fix a problem with the hidden GitLab jobs `.run-unittests-and-lint` and `.run-validations` (which jobs in different pipeline configurations extend) so that artifacts are stored even if the job fails.

Remove the instance testing from the commit circle workflow

---

Tests/scripts/prepare_content_packs_for_testing.sh

fixes: https://github.com/demisto/etc/issues/37075
Changed the name,  from "Prepare Content Packs For Testing.log" to "Prepare Content Packs For Testing gsutil.log"

changed name from "Prepare Content Packs For Testing.log" to "Prepare Content Packs For Testing gsutil.log

---

Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.py
Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener.yml
Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_test.py
Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/README.md
Packs/MicrosoftGraphListener/ReleaseNotes/1_0_16.md
Packs/MicrosoftGraphListener/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37983

MS Graph Mail Single User - set the contentId attribute in the attachment object

---

.gitlab/ci/bucket-upload.yml
.gitlab/ci/on-push.yml
.gitlab/ci/sdk-nightly.yml
.gitlab/ci/slack-notify.yml

- https://github.com/demisto/etc/issues/37789
Implements the following fixes and tweaks:
- Removes the job rules condition from the slack-notification child pipeline workflow. This is because any job in the parent pipeline that triggers the slack notification child pipeline should have the proper rule conditions for running. Therefore we can remove the rule conditions from the child.
- Adds a `when: always` field to rules of jobs that should run even when previous jobs failed. Used in the various `<trigger-slack-notification>` jobs and the jobs whose artifacts the trigger jobs depend upon. This way, these jobs won't be skipped if previous jobs in the pipeline fail (which should prevent the slack notification to the `dmst-content-team` channel from not occurring).
- Explicitly pass the …

GitLab Flows Tweaks and Fixes

---

Tests/conf.json
Tests/scripts/collect_tests_and_content_packs.py

fixes: https://github.com/demisto/etc/issues/37860
fixes: https://github.com/demisto/etc/issues/32512
Added an option of specifying private tests, that will not be run on nightly.
This possibility will allow us to specify timeout values for private tests.

remove private tests from nightly

---

Packs/ElasticsearchMonitoring/Dashboards/elasticsearch_monitoring.json
Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchCPUCurrentUsage.json
Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchDiskCurrentUsage.json
Packs/ElasticsearchMonitoring/Widgets/widget-ElasticSearchJVMCurrentUsage.json

Fix Elasticsearch monitoring pack's widget duplicate id with Common Widgets pack

fix widget duplicate id in Elasticsearch Monitoring

---

.gitlab/ci/bucket-upload.yml
.gitlab/ci/on-push.yml
.gitlab/ci/sdk-nightly.yml

Our scheduled pipelines passed the string literal `$SLACK_CHANNEL` instead of the environment variable's value. See this [pipeline](https://code.pan.run/xsoar/content/-/pipelines/1250578) for an example.
Change the `upload-packs-to-marketplace` job to always run during the bucket-upload flow even if previous jobs failed.

Fix passing SLACK_CHANNEL env var value

---

Packs/CommonScripts/ReleaseNotes/1_3_59.md
Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.py
Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator.yml
Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py
Packs/CommonScripts/pack_metadata.json

should return empty string in case we want to drop the indicator and not an empty array

VerifyIPv6Indicator - return empty string instead of empty list

---

Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
Packs/FireEyeHX/ReleaseNotes/1_0_15.md
Packs/FireEyeHX/pack_metadata.json

fixes https://github.com/demisto/etc/issues/28360
fixed an issue where the check if api v3 is used was wrong as it was missing checking if api is v3

FireEye HX - fix api version check for host-containment

---

.gitlab/ci/on-push.yml
.gitlab/ci/sdk-nightly.yml

fixes: https://code.pan.run/xsoar/content/-/jobs/6074172
In the job artifacts of the link above, the [packs-release-notes.md file](https://code.pan.run/xsoar/content/-/jobs/6074172/artifacts/file/artifacts/packs-release-notes.md) which was created (and which we use when creating a content release) didn't detect and add the release notes since the last release. This is because we were passing the current branch's ref instead of the `$GIT_SHA1` env variable stored value from `.circleci/content_release_vars.sh` which contains the sha ref of the last release.
Added the creation of the release notes file and content descriptor file to the `on-push` flow (to only execute on master or release branches).

Fix release notes creation in sdk-nightly & on push flows

---

.gitlab/ci/on-push.yml

fixes: https://code.pan.run/xsoar/content/-/jobs/6159487
Reverting putting the execution of `Utils/release_notes_generator.py` under a condition checking whether we were on the `master` or a release branch. That script also generates the `content-descriptor.json` file which is used in updating the content on an xsoar instance.

Fix copy of content-descriptor.json to artifacts

---

Utils/checkout_contribution.sh

in case the contributor used the `master` branch (or any other branch that already exists locally, the script fails to switch to the contributed branch.
running `./Utils/checkout_contribution.sh yaakovi:master`
before:
after:

improved "checkout_contribution.sh" script to handle existing branches

---

.gitlab/ci/.gitlab-ci.yml
.gitlab/ci/bucket-upload.yml
.gitlab/ci/global.yml
.gitlab/ci/on-push.yml
.gitlab/ci/sdk-nightly.yml
.gitlab/ci/slack-notify.yml

- Adds a `fan-in` stage
- Adds a `fan-in` job to the following flows
- nightly
- bucket-upload
- sdk-nightly
- Changes the bucket-upload flow so that the `upload-packs-to-marketplace` job will not be run if previous jobs failed
- Adds retry to the slack-notify job
- Makes the slack notification trigger job's status dependent on the child pipeline's status, i.e. it will fail if the slack-notify job fails
Should prevent such cases as in the attached screenshot where the packs were uploaded despite installation of those packs on a server instance failing
- [x ] No

Some Improvements to GitLab Flows

---

Tests/scripts/slack_notifier.py

Fixes the failed tests not being detailed in the slack notification about the `Content Nightly` run from GitLab as shown in the attached screenshot below.

Fix Path to failed_tests.txt File

---

Tests/demistomock/demistomock.py

clarify how custom fields are returned from the `demisto.incident()` func

Demisto Class - add note about custom fields returned from the incident method

---

.circleci/config.yml
.gitlab/ci/.gitlab-ci.yml
.gitlab/ci/global.yml
Utils/trigger_nightly_sdk_build.sh

fixes: https://github.com/demisto/etc/issues/32647
Added the option to give a specific demisto-sdk branch that will be used by trigger_nightly_sdk_build

Added flag to specify branch for SDK nightly build

---

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_test.py
Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/README.md
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_3_8.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/38763
added the reliability para. added its usage to the cmds: !file, get-verdict, get-verdicts, whenever the dbotscore object is returned.

WildFire v2 - Added support for the *Source Reliability* param

---

Packs/ServerLogs/ReleaseNotes/1_0_1.md
Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.py
Packs/ServerLogs/Scripts/ServerLogs/ServerLogs.yml
Packs/ServerLogs/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/38812
Added required dependency of `RemoteAccess` for CLI usage, and improved error message for `widget` usage.

Add to ServerLogs dependency of RemoteAccess

---

.gitlab/ci/global.yml

fixes: https://code.pan.run/xsoar/content/-/pipelines/1312732
We clone the repo in every job and `checkout` the `$CI_COMMIT_BRANCH` - if the HEAD has changed between subsequent jobs in a Pipeline (AKA if we are working against the `master` branch, if someone merged to master between the time job1 ran and job2 ran, then you have a situation where job1 and job2 are at two different commits in the branch history) causes a problem where the jobs are at different commits in the branch history.
With the current solution as implemented... the repo will probably be in a `detached HEAD` state which may have implications at various times in the build... might be better to have a job run in the `.pre` stage in which we create a temporary branch that the rest of the jobs will checkout from (and which …

Checkout commit sha instead of branch (whose head could change)

---

Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
Packs/AlienVault_OTX/ReleaseNotes/1_1_4.md
Packs/AlienVault_OTX/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39006
fixes: https://github.com/demisto/etc/issues/38868
Added a support for multiple IPs in the ip command + Fixed an issue where if an ip was not found (got 404 from server) then it would crush.

Alienvault_OTX_v2 bug fixed- support for multiple ips

---

README.md
Tests/secrets_white_list.json

Adds a badge to the `content` repo README to open the repository in vs code as described [here](https://code.visualstudio.com/updates/v1_58#_open-in-vs-code-badge). Also adds the URL used in the badge to the whitelisted URLs group.

Add badge to open the repo in vs code

---

Packs/Devo/Integrations/Devo_v2/Devo_v2.py
Packs/Devo/Integrations/Devo_v2/Devo_v2.yml
Packs/Devo/Integrations/Devo_v2/Devo_v2_description.md
Packs/Devo/Integrations/Devo_v2/Devo_v2_test.py
Packs/Devo/Integrations/Devo_v2/README.md
Packs/Devo/README.md
Packs/Devo/ReleaseNotes/1_1_0.md
Packs/Devo/pack_metadata.json

This is an update to the Devo_v2 Integration in the Devo packs.
More detailed breakdown of changes can be found in the changelog documented here:
Packs/Devo/ReleaseNotes/1_1_0.md
Main key takeaways are using updated devo-sdk underlying package with updated docker.
Added 2 new arguments to a few commands which are linkLinqBase and queryTimeout which will override default global values in the plugin.
Bumped version to 1.1.0

Updates to the Devo_v2 plugin

---

.gitlab/ci/on-push.yml

fixes: the nightlys testing different amount of tests
For GitLab, because the updated `conf.json` doesn't persist at `Tests/conf.json` between jobs, we need to copy the updated `conf.json` file from the artifacts directory to `Tests/conf.json` path before the `run_tests.sh` step since that script is configured to look there. Otherwise, the ordinary `conf.json` is used from when the repo is cloned at the start of the job. Resulting

Copy the updated conf to Tests/conf.json before running tests

---

Tests/Marketplace/configure_and_install_packs.py
Tests/Marketplace/install_packs.sh
Tests/Marketplace/marketplace_constants.py
Tests/Marketplace/marketplace_services.py
Tests/Marketplace/search_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Utils/gitlab_triggers/trigger_upload_flow_build.sh

When trying to install **all packs** the current script is iterating over the content repo and checking the `serverMinVersion` for each pack. This field is usually populated in the upload-flow (and minorly exists in the repo) we end up installing packs with fromversion > 6.0 on a 6.0 server. This is causing the installation to fail.
Now iterating over the build bucket that was configured in a pre-job to the installation job.
https://app.circleci.com/pipelines/github/demisto/content/99975/workflows/b6f99c3b-3f36-4027-a3b1-bfa6e8a6f447
https://code.pan.run/xsoar/content/-/pipelines/1371791

Upload-Flow installation bug fix

---

.circleci/config.yml
Utils/trigger_content_nightly_build.sh
Utils/trigger_nightly_sdk_build.sh

- Removes the `Create Instances` and `Server Master` jobs from the CircleCI nightly workflow jobs - AKA removes running the test playbooks against XSOAR instances (since this runs in GitLab).
- Adds a `legacy_nightly` pipeline parameter which will trigger a nightly build in CircleCI *as it used to be - aka how it ran before these changes*.
- Updates the CircleCI nightly trigger script
- to use option flag inputs
- an option to trigger a legacy nightly build
Tweaked the syntax in `Utils/trigger_nightly_sdk_build.sh` (removed spaces) so that VS Code linter doesn't complain.

Update Circle Nightly to only Run Validations and Lint & Unit Tests

---

Packs/CommonTypes/IncidentFields/incidentfield-Manager_Email_Address.json
Packs/CommonTypes/ReleaseNotes/3_1_7.md
Packs/CommonTypes/pack_metadata.json

Ready
Related to: https://github.com/demisto/etc/issues/34214
Found a bug where the Manager Email Address was not associated to the `IAM - AD User Activation` incident type. This caused the welcome email for newly activated users to not be sent to the manager.

Manager email address field association

---

Packs/IntSight/Integrations/IntSight/IntSight.py
Packs/IntSight/Integrations/IntSight/IntSight.yml
Packs/IntSight/Integrations/IntSight/IntSight_test.py
Packs/IntSight/ReleaseNotes/1_0_7.md
Packs/IntSight/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39229
Fixed an issue where non-ascii characters were causing the `fetch-incidents` and `intsights-get-alerts` commands to fail.

insight get-alerts fix

---

Packs/EDL/Playbooks/playbook-PAN-OS_EDL_Service_Configuration_README.md

- [ x] Ready
Fixed formatting in the Playbook Inputs section of the PAN-OS EDL Service Configuration README. Info should be in a table, but the table formatting was not correct.
See https://xsoar.pan.dev/docs/reference/playbooks/pan-os-edl-service-configuration for the incorrect formatting.

Fixed formatting in EDL README

---

Packs/GreyNoise/.pack-ignore

As a part of this ticket
I have received a validation failure
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/10825/workflows/5a597842-78f0-4535-9710-74f803898981/jobs/52224
After conversation with @Itay4, he told me containing Community name was allowed for this specific failing integration, therefore adding ignore to the newly added validation

Add Validation Ignore For The New Validation Of Pack/Integration/Script Name To Be Added

---

Tests/scripts/gitlab_slack_notifier.py

If certain words are in the workflow name _or_ in the failed jobs' names, then include the failed unit tests in the slack message output. This is so that if a failed content nightly included failed unit tests (and not just failed test playbooks) the failed unit tests will be listed in the slack message to the `dmst-content-team` channel.

Check failed jobs's names to determine slack msg

---

.gitlab/ci/global.yml

So that we see `run-unittests-and-lint-upload-flow` and `run-validations-upload-flow` jobs actually run the relevant `demisto-sdk` commands in the GitLab Upload Flow (even though we are running there against a test bucket) unlike what you see in the attached screenshots and what happens in the bucket upload flow [here](https://code.pan.run/xsoar/content/-/pipelines/1397925). So we can verify that it is working properly.

Run validation and unit tests and lint even against test bucket

---

Packs/TaniumThreatResponse/TestPlaybooks/playbook-Tanium_Threat_Response_Test.yml

fixes: https://github.com/demisto/etc/issues/33974
https://github.com/demisto/etc/issues/34111
https://github.com/demisto/etc/issues/33685
Remove the following commands from the test playbook:
- tanium-tr-list-connections
- tanium-tr-list-snapshots-by-connection
- tanium-tr-list-local-snapshots-by-connection
- tanium-tr-get-connection-by-name
- tanium-tr-get-evidence-by-id
since tanium updated the API endpoints, those commands are failed with status:
`Error in Tanium Threat Response Integration: Error in API call [502] - Bad Gateway
502 Bad Gateway`
should be updated in …

Tanium Threat Response - Remove connection and evidence related tasks

---

Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.py
Packs/FeedElasticsearch/Integrations/FeedElasticsearch/FeedElasticsearch.yml
Packs/FeedElasticsearch/ReleaseNotes/1_0_9.md
Packs/FeedElasticsearch/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39361
Changed the timestamp to a `13 digit` timestamp (mili seconds) rather than `16 digits` (microseconds).

[Elasticsearch Feed] Fix lastTime timestamp in wrong format

---

.gitlab/ci/global.yml

To allow people to test their upload changes without waiting two hours / editing infra code not related to their work, I've added a check for branch name. For master runs we will perform the UT, Lint & Validate, for other branches not.

Revert 13767 run lint and validation on test bucket

---

Packs/ipinfo/TestPlaybooks/playbook-IPinfo_v2_Test.yml

The IP command in TPB trigerred this test to be collected when it shouldn't have. @ChanochShayner Correct me if i am wrong. As can be seen in this PR
https://github.com/demisto/content/pull/13838

binded the ip command to ipinfo_v2 brand

---

Packs/CommonScripts/ReleaseNotes/1_4_11.md
Packs/CommonScripts/Scripts/GetlistRow/GetListRow.py
Packs/CommonScripts/Scripts/GetlistRow/GetListRow.yml
Packs/CommonScripts/Scripts/GetlistRow/GetListRow_test.py
Packs/CommonScripts/Scripts/GetlistRow/README.md
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39652
Add a separator argument (the default is `,` )
with default sep:
on the list:
with custom sep:
on the list:

GetListRaw - added list separator arg

---

Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.py
Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API_test.py
Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/test_data/get_url_report_no_resultion.json
Packs/VirusTotal-Private_API/ReleaseNotes/1_0_10.md
Packs/VirusTotal-Private_API/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39587
wrong indent, would try to access non existent list in some cases.
Successful now

VirusTotal - Private API - Fixed an issue where the vt-private-get-url-report command would fail on certain urls.

---

Packs/CommonScripts/ReleaseNotes/1_4_12.md
Packs/CommonScripts/Scripts/ExtractDomainAndFQDNFromUrlAndEmail/ExtractDomainAndFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.py
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat.yml
Packs/CommonScripts/Scripts/ExtractDomainFromUrlFormat/ExtractDomainFromUrlFormat_test.py
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.py
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail.yml
Packs/CommonScripts/Scripts/ExtractFQDNFromUrlAndEmail/ExtractFQDNFromUrlAndEmail_test.py
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39676
updating scripts to use the latest demisto/tld docker image
note that `ExtractFQDNFromUrlAndEmail` and `ExtractDomainFromUrlAndEmail` are upgraded in this PR from python2 to python3.
I found that they were marked falsely in the yml as python3 scripts, but the original docker image actually run python2.

Update tld docker

---

.gitlab/ci/.gitlab-ci.yml
.gitlab/ci/global.yml
Tests/secrets_white_list.json

fixes: https://jira-hq.paloaltonetworks.local/browse/EP-1336
Changes the git strategy to the default method of `fetch` instead of `clone`. Also changes the depth to 1 so that the git request made by GitLab will be as minimal as possible. Moves full "fetching" from the remote to the `before_script` wherein the git fetch request seems to complete without any problems.

Fix GitLab Job Failures

---

.gitlab/ci/global.yml
Tests/scripts/collect_tests_and_content_packs.py
Utils/gitlab_triggers/trigger_content_nightly_build.sh

fixes: https://code.pan.run/xsoar/content/-/jobs/6865777 (hopefully)
Implements a couple of modifications.
- Simplifies the `git` commands run in `collect_tests_and_content_packs.py` to retrieve the `git diff` between the previous and current commits.
- Improves the GitLab nightly trigger script's usability.
- Set the `fetch` command to explicitly fetch from the `origin` remote.
Linked [here](https://code.pan.run/xsoar/content/-/pipelines/1468557) is the bucket upload flow triggered against this branch.

Fix a git diff cmd

---

Packs/Base/ReleaseNotes/1_13_11.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39311
Add default value for the `iocs` value when using `IndicatorsSearcher`.

Add Default Value for IndicatorsSearcher iocs

---

Packs/Pcysys/Integrations/Pcysys/Pcysys.py
Packs/Pcysys/Integrations/Pcysys/Pcysys.yml
Packs/Pcysys/Integrations/Pcysys/Pcysys_test.py
Packs/Pcysys/ReleaseNotes/1_3_0.md
Packs/Pcysys/pack_metadata.json

Added pentera_test_module_command function for test-module command.
Fixed an issue where the user had to renew the TGT token every 15 minutes.
Fixed an issue where pentera-get-task-run-full-action-report command would fail on "field larger than field limit (131072)".
Fixed an issue where pentera-get-task-run-full-action-report command would fail on "cannot unpack non-iterable NoneType object".

Fix NTLM hash parse and TGT expired issue

---

.gitlab/ci/global.yml

fixes: https://code.pan.run/xsoar/content/-/jobs/6887465 (hopefully)
fixes: https://code.pan.run/xsoar/content/-/jobs/6890070 (hopefully)
Set the `git fetch` depth argument to a large number (arbitrarily chose 100). Also fetches tags.
The bucket upload flow [pipeline](https://code.pan.run/xsoar/content/-/pipelines/1474192) from triggering the flow against this branch.
The nightly flow [pipeline](https://code.pan.run/xsoar/content/-/pipelines/1474409) from triggering the flow against my branch.

Increase fetch depth

---

Packs/Slack/doc_files/SlackV3_app_manifest.yml

fixes: https://github.com/demisto/etc/issues/39925
In the SlackV3 manifest, we are missing the following scopes:
- channels:write
- groups:write
- mpim:write
- im:write
- users:read.email

Update Slack App Manifest to add new scopes

---

Packs/GenericWebhook/Integrations/GenericWebhook/README.md

fixes: https://github.com/demisto/content-docs/issues/738
Clarified that `instance` is _not_ special, unique, or the name of the instance, but just a regular old string.

Clarify Docs for Generic Webhook Endpoints

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/34371
https://code.pan.run/xsoar/content/-/jobs/6956374
```
[2021-08-09 03:18:21] - [Thread-5] - [ERROR] - "palo_alto_panorama_test_pb" failed on timeout
[2021-08-09 03:18:22] - [Thread-5] - [ERROR] - Test failed: playbook: "palo_alto_panorama_test_pb" with integration(s): ["Panorama"]
[2021-08-09 03:18:22] - [Thread-5] - [INFO] - ------ Test playbook: "palo_alto_panorama_test_pb" with integration(s): ["Panorama"] end ------
```

panorama - increase timeout

---

.gitlab/ci/bucket-upload.yml
.gitlab/ci/global.yml
.gitlab/ci/instance-test.yml
.gitlab/ci/on-push.yml
.gitlab/ci/sdk-nightly.yml
.gitlab/ci/slack-notify.yml

Adds the `gke` tag for non docker-in-docker ("dind") related jobs. This applies for all jobs except for the Run Lint & Unit Tests jobs which run `dind` service containers. The `gke` tagged runners are more performant according to the engineering-productivity team.

Add gke runner tag for non-dind related jobs

---

.gitlab/ci/global.yml

reverts part of: https://github.com/demisto/content/pull/14075
Removed the tag gke from the run-validations job, looks like it is related to the `upload packs to market place` build failures, such as https://code.pan.run/xsoar/content/-/jobs/7012694.
@avidan-H FYI

removed the gke tag from run-validations job

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/2_1_9.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/40268
improved regex to catch the proper pattern of the `raw` event to handle possible comma chars in the values

Splunk - handle commas in raw event values

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md

need to use the `raw` ref instead of `blob`

MS Teams Video - replace blob with raw in video link

---

Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/2_1_10.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/40473
see detailed description in the issue

Splunk - remove earliest and latest fetch params

---

Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.py
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse.yml
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/ProofpointThreatResponse_test.py
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/test_data/incident_expand_events_false.json
Packs/ProofpointThreatResponse/Integrations/ProofpointThreatResponse/test_data/raw_response.json
Packs/ProofpointThreatResponse/ReleaseNotes/1_0_6.md
Packs/ProofpointThreatResponse/pack_metadata.json

fixes https://github.com/demisto/etc/issues/40564
- the `expand_events` arg was not implemented for the `proofpoint-tr-get-incident` command in the code
- added `vap` and `attachments` to incident commands outputs

Proofpoint Threat Response - handle expand_events arg in get-incident cmd

---

Tests/conf.json

https://github.com/demisto/etc/issues/38063
skipping ipstack tests

skip tests

---

Packs/Base/ReleaseNotes/1_13_22.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

improved the handling of an edge case where a single-header dict is given with a list as the value:
```python
data = {
'Hello': [
'World',
'Kitty',
'Goodbye',
}
```
the first commit is just for organizing all the function's unit tests.

CSP: tableToMarkdown - fixed single column behavior

---

Packs/CommonScripts/ReleaseNotes/1_4_24.md
Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
Packs/CommonScripts/Scripts/SetGridField/SetGridField_test/expected_list_grid_none_value.json
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/39641
Column names were transformed to `flatcase` (CLI name), although the server allows (see `utils/strings.js/stripToColumnName`). This caused data of columns whose name include underscores to not be shown on the grid. Changing them to lower case (rather than converting to camelCase, which would remove underscores) allows using column names that include underscores.

setGridField: Allow column names to have underscores

---

Packs/Armis/.pack-ignore
Packs/Compliance/.pack-ignore
Packs/CortexXDR/.pack-ignore
Packs/DigitalGuardian/.pack-ignore
Packs/F5Silverline/.pack-ignore
Packs/MicrosoftAdvancedThreatAnalytics/.pack-ignore
Packs/ShiftManagement/.pack-ignore

Ignoring this error at the files that failed here: https://app.circleci.com/pipelines/github/demisto/demisto-sdk/11606/workflows/f4558dc2-eca4-461f-87d6-1d60e7ba7a63/jobs/58567 

Added ignoring errors BA113,BA112 in packs.

---

Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed.py
Packs/FeedCrowdstrikeFalconIntel/Integrations/CrowdStrikeIndicatorFeed/CrowdStrikeIndicatorFeed_test.py
Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/2_0_4.md
Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json

Test module and Fetch indicators fails with error when no first_fetch param entered: 
"Script failed to run: Error:[Traceback (most recent call last): File "<string>", line 473, in <module. File "<string>", line 414 in main File "<string>", line 5469, in arg_to_datetime ValueError: "" is not a valid date] (2604) (2603)

Crowdstrike datetime bug

---

Tests/Marketplace/marketplace_services.py

Fixing a typo in an attribute under the marketplace_constants python file .

Typo fix constnats upload

---

Packs/SplunkPy/Classifiers/classifier-Splunk_-_Notable_Generic_Outgoing_Mapper.json
Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
Packs/SplunkPy/ReleaseNotes/2_1_11.md
Packs/SplunkPy/pack_metadata.json

related: https://github.com/demisto/etc/issues/40851
- Fixed an issue in the outgoing mapper where whitespace in the list of mapped values has caused a wrong output of the transformer.
- Fixed an issue with unicode not having the `get` arg, similar to what have been done in https://github.com/demisto/content/pull/13747.
- Improved the documentation regarding the mirroring
- Added a default outgoing mapper

Splunk Fixes

---

Tests/Marketplace/marketplace_services.py

related: https://github.com/demisto/content/pull/14578
As can be seen in the following [upload](https://code.pan.run/xsoar/content/-/jobs/7335091), packs are not failing but the pack processing is continued (`Screenshot 1`). This should not happen and we should see failure in that Pack method, as can be seen in the same build, packs are not listed as failed to upload. Bug reproduce is showed in `Screenshot 2`.

fix upload-flow bug in collect_content_items

---

Packs/MailListener_-_POP3/Integrations/MailListener_POP3/MailListener_POP3.yml
Packs/MailListener_-_POP3/ReleaseNotes/1_0_5.md
Packs/MailListener_-_POP3/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/40992
Changing the ssl checkbox default value from "'True'" to "true" - this resolves an issue with setting up a new instances.

Pop3 fix ssl default value

---

.gitlab/ci/.gitlab-ci.yml
.gitlab/ci/miscellaneous.yml
Utils/delete_mismatched_branches.py

Our GitLab `content` repository doesn't reflect when branches are deleted in the Github `content` repository from which it is mirrored. This leads to the branches in the GitLab repo ever-increasing and eventually in turn, causing repo cloning failures at the start of GitLab jobs because the repo's size is so great and the request takes so much time that almost always results in connectivity interruptions and failures. Adds a GitLab job that executes a script to delete "excess" branches in GitLab - AKA branches that have already been deleted from the Github `content` repo but still exist in GitLab. I will add a scheduled pipeline that will run once a day to trigger this job once this is merged.

GitLab Job to Delete Branches Already Deleted from Github

---

Packs/Cisco-umbrella/Integrations/Cisco-umbrella-investigate/Cisco-umbrella-investigate.yml
Packs/Cisco-umbrella/ReleaseNotes/1_0_7.md
Packs/Cisco-umbrella/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/41151
fixes: https://github.com/demisto/etc/issues/24338
in https://github.com/demisto/content/pull/14541 i've set the `isArray` flag to the wrong arg

Cisco Umbrella Investigate - fix isarray for domain arg

---

Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
Packs/FeedUnit42v2/ReleaseNotes/1_0_4.md
Packs/FeedUnit42v2/pack_metadata.json

https://github.com/demisto/content/pull/14778
Unable to connect Unit42 server via a web proxy.

Fixed an issue where proxy settings haven't been given in BasicClient.

---

Packs/Base/ReleaseNotes/1_13_31.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython.yml
Packs/Base/pack_metadata.json
Packs/DeveloperTools/TestPlaybooks/playbook-TestCommonPython.yml
Packs/DeveloperTools/TestPlaybooks/script-TestPyCommonServer.yml

fixes: https://github.com/demisto/etc/issues/41215
`BaseClient` failed in `__del__` when used as global

BaseClient - improve if session exist check in del

---

Packs/Ironscales/IncidentFields/incidentfield-Ironscales-Resolver-email-address.json
Packs/Ironscales/ReleaseNotes/1_0_2.md
Packs/Ironscales/pack_metadata.json

related: https://github.com/demisto/etc/issues/39948
Deleted a wrong script id from Packs/Ironscales/IncidentFields/incidentfield-Ironscales-Resolver-email-address.json.
The deleted ID doesn't exist in content repository. 
In addition there aren't any scripts in the partner's original PR. 
According to @ShahafBenYakir the script ID is there by mistake and should be deleted. 

Delete wrong script id from ironscales's incident field to correalte scripts ids new validation

---

Packs/FeedRecordedFuture/Integrations/FeedRecordedFuture/FeedRecordedFuture_description.md
Packs/FeedRecordedFuture/ReleaseNotes/1_0_15.md
Packs/FeedRecordedFuture/pack_metadata.json

While checking the description md file in Pycharm, it seemed as expected.
When I tried to configure an instance of RF Feed, it was not places correctly
Fixing by removing the indents
Is this the expected behaviour? the diff between what is showed in description md in Pycharm to the server?
@dantavori  @Itay4

Fix Recorded Feed Description Recommended Interval Fetch Grid 

---

Packs/Base/Scripts/StixParser/StixParser.py
Packs/CommonScripts/Scripts/CreateIndicatorsFromSTIX/CreateIndicatorsFromSTIX.py

We would like to be able to search on the “Stix Package Id” and “Indicator ID” and populate the details to the layout, which are created when a STIX file is uploaded via the UI or API. I see in the !StixParser we extract this data from the Stix file and add it to the indicator custom fields 
```
entry["CustomFields"] = {"indicatorId": ind_id, "stixPackageId": pkg_id}
```
these are not OOTB indicator fields as far as I can tell.  If I create indicator fields with the same name the Threat Intel page shows them automatically populated, but they are not searchable and do not …

[BugFix] StixParser Custom Fields

---

Packs/CommonScripts/Scripts/VerifyIPv6Indicator/VerifyIPv6Indicator_test.py

related: https://github.com/demisto/etc/issues/41552
skipping the test until it will be stable

VerifyIPv6Indicator - skipped flaky unit test

---

.gitlab/ci/miscellaneous.yml
Utils/delete_mismatched_branches.py

The scheduled pipeline to delete Gitlab branches that exist in the `content` project in Gitlab but do not exist in the GitHub repository (from which the repo is mirrored) was not executing as expected. Background on the issue is that the mirroring of the Github repo does not extend to branch deletion so once a branch is mirrored into Gitlab it is never subsequently deleted. The scheduled pipeline did not execute because the stage was set to `.pre`. I've updated it to use the `fan-in` stage - no stage was exactly appropriate for this cleanup pipeline so my choice was somewhat arbitrary. 
The number of branches in the `content` project in Gitlab prior to manually triggering the pipeline
The number of branches in the `content` project in Gitlab subsequent to running the pipeline - note that …

Fix Gitlab Branch Deletion Scheduled Pipeline

---

Utils/github_workflow_scripts/delete_stale_non_contrib_branches.py

Our maintenance script `delete_stale_non_contrib_branches.py` which deletes stale non-contribution branches will try to create time after time a posterity PR for stale branches which are protected (since it doesn't successfully delete the branch after creating the posterity PR and therefore the branch is collected as stale the next time the script is run). I've updated the script so that it does not consider protected branches.

Exclude protected branches

---

.github/workflows/sync-contribution-base-branch.yml

Only syncs contribution PRs' base branches with updated `master` at night. This should reduce the runner instance load during the day (when people are working) since we don't want any pipeline bottlenecking. See this [slack discussion](https://panw-global.slack.com/archives/C0117K6N5NW/p1633009822195600) for more details.

Only sync contrib base branch with master at night

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/2_2_1.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/40179
Updating the SplunkPy to use the latest docker image of demisto/splunksdk to use tag  1.0.0.24033 that  mitgate CVE-2021-36159 

bump up SplunkPy to use demisto/splunksdk:1.0.0.24033

---

Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket.yml
Packs/ServiceNow/Playbooks/playbook-Create_ServiceNow_Ticket_README.md
Packs/ServiceNow/ReleaseNotes/2_2_7.md
Packs/ServiceNow/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/41703
The playbook "Create ServiceNow Ticket" missing the input Ticket type, As a result of that the playbook only creates incidents.
Added ticket type input to Create ServiceNow Ticket playbook

Add input to create service now ticket playbook

---

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/Elasticsearch/Integrations/Elasticsearch_v2/README.md
Packs/Elasticsearch/ReleaseNotes/1_1_8.md
Packs/Elasticsearch/pack_metadata.json

Added the following description to the Server URL field in light of feedback on dmst-usecases channel:
"Ensure that the URL includes the correct Elasticsearch port. By default this is 9200."

Elasticsearch v2 - update Server URL description

---

Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/MicrosoftGraphUser.yml
Packs/MicrosoftGraphUser/Integrations/MicrosoftGraphUser/README.md
Packs/MicrosoftGraphUser/ReleaseNotes/1_3_13.md
Packs/MicrosoftGraphUser/pack_metadata.json

Changing the Microsoft Graph User Description For Command Because It Was Misleading. As Can Be Seen Here
https://github.com/demisto/etc/issues/41571

Change Microsoft Graph User Terminate Command Description

---

Packs/GenericWebhook/Integrations/GenericWebhook/README.md

The current Generic Webhook documentation shows the URI path to reach the webhook to be `<CORTEX-XSOAR-URL>/instance/execute/<INTEGRATION-INSTANCE-NAME>`. This did not work for me in production, and after looking into the integration code, it actually listens at the root (`<CORTEX-XSOAR-URL>/`). This fixes the documentation to address the discrepancy.

Fixed docs for GenericWebhook

---

Tests/scripts/prepare_content_packs_for_testing.sh

Change the inserted number to the corepack.json from job number to the pipeline number. In the previous PR mistakenly only one out of the two calls for `upload_packs.py` was modified.

core packs build number fix 2

---

.gitlab/ci/global.yml

[Update of the GKE runners](https://panw-global.slack.com/archives/CRKK3S2QY/p1633573509411000?thread_ts=1633551603.378100&cid=CRKK3S2QY) to Gitlab version 14.0 caused the line,
`$(echo $0) --version` in the `.default-before-script` hidden job configuration to reinvoke the shell with the configuration as the shell command argument - this is presumably due to the shell type changing. Caused what looked like looping in the `create-instances` job - see an example [here](https://code.pan.run/xsoar/content/-/jobs/7983956). Removed this line as it was only used for debugging anyways.

Remove Problematic Echoing of Shell Version

---

Packs/CommonDashboards/Dashboards/dashboard-Home.json
Packs/CommonDashboards/ReleaseNotes/1_1_2.md
Packs/CommonDashboards/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/41535
The `my-tasks`, `my-mean-time-to-resolution`, `my-mentions` tasks now use the selected time range, rather than show all data. 
Before
After
5.0.0
- Further details: widgets now only show data from the selected time range, and not all data, as default. This can be changed by customising the dashboard.

Dashboard widgets to use selected time range

---

Packs/ThreatIntel/GenericModules/genericmodule-ThreatIntel.json
Packs/ThreatIntel/ReleaseNotes/1_0_7.md
Packs/ThreatIntel/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/42157

Threat Intel Report - fixed tab name to be in plural

---

Packs/ThreatIntel/GenericModules/genericmodule-ThreatIntel.json
Packs/ThreatIntel/ReleaseNotes/1_0_8.md
Packs/ThreatIntel/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/42001

Threat Intel Report - fix widgets sizes

---

Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2.py
Packs/AutoFocus/ReleaseNotes/1_3_11.md
Packs/AutoFocus/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/42286
Added different handling when IPv6 is provided.

AutoFocusV2 Fixed IPv6 recognized as IPv4

---

Packs/rasterize/Integrations/rasterize/rasterize.yml
Packs/rasterize/ReleaseNotes/1_0_14.md
Packs/rasterize/pack_metadata.json

Updated Pack rasterize to use the latest release for demisto/chromium docker image 1.0.0.24144
fixes: https://github.com/demisto/etc/issues/42713
bumping up the chromium docker image in rasterize pack

Updated Pack rasterize to use the latest release for demisto/chromium docker image 1.0.0.24317

---

Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.py
Packs/cyberark_AIM/ReleaseNotes/1_0_9.md
Packs/cyberark_AIM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43000
The test module does fetch on each credential in the credential_names. When this was not provided, it caused the fetch to end successfully, even if the instance configuration was incorrect.
Added a check- if the credential_names provided, will continue the test, otherwise will try with a dummy credential.

cyberArk fix test

---

Packs/AutoFocus/Integrations/AutoFocusTagsFeed/AutoFocusTagsFeed.yml
Packs/AutoFocus/ReleaseNotes/2_0_1.md
Packs/AutoFocus/TestPlaybooks/playbook-AutoFocusTagsFeed_test.yml
Packs/AutoFocus/pack_metadata.json
Tests/conf.json

Changed defaultEnabled field so server build stop fail

AF Tags Feed defaultEnabled field 

---

.github/workflows/check-contribution-form-filled.yml
.github/workflows/create-internal-pr-from-external.yml
.github/workflows/handle-new-external-pr.yml
.github/workflows/handle-stale-branches.yml
.github/workflows/sync-contribution-base-branch.yml
Utils/github_workflow_scripts/Pipfile
Utils/github_workflow_scripts/Pipfile.lock

The GitHub actions utilizing the `virtualenv` defined by the Pipfile in `content/Utils/github_workflow_scripts` have been failing for the past 2 days on an import error of `urllib3`. Can see these examples, https://github.com/demisto/content/runs/4123002193?check_suite_focus=true, https://github.com/demisto/content/runs/4130131788?check_suite_focus=true. A couple of changes have been made to hopefully address the unexpected error,
- Update the python version of the `virtualenv` from 3.8 to 3.9
- Explicitly list `urllib3` as a package to be installed in the `virtualenv`
- Add the output from running `pip list` in the `virtualenv` to see the actual packages installed in the environment as a measure for debugging should the aforementioned changes not resolve the issue

Fix Failing GitHub Actions

---

Packs/Base/ReleaseNotes/1_14_1.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

_http_request function is using ET.parse() (which take a file as parameter and not a string) instead of using ET.fromstring().

BaseClient class - fixed a bug when choosing xml as resp_type

---

Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py

Prevent `QRadar_v2.DEFAULT_EVENTS_TIMEOUT` changes in some tests affecting other tests.

[QRadar v2] Stabilize Unit Tests

---

Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
Packs/QRadar/ReleaseNotes/2_1_7.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43551
Fixed an issue where `set_to_integration_context_with_retries()` `sync` argument was passed as `object_keys` instead.

[Fix] QRadar v2 2.1.6 fetch duplicates

---

Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic_README.md
Packs/CommonPlaybooks/ReleaseNotes/2_1_1.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43679
added the VMRay context outputs to the `Detonate File - Generic` playbook.

Detonate File - Generic: added VMRay outputs

---

Packs/CommonScripts/ReleaseNotes/1_5_5.md
Packs/CommonScripts/Scripts/ExtractIndicatorsFromTextFile/ExtractIndicatorsFromTextFile.yml
Packs/CommonScripts/Scripts/ExtractIndicatorsFromWordFile/ExtractIndicatorsFromWordFile.yml
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Packs/CommonScripts/pack_metadata.json

Ready
fixes: https://github.com/demisto/etc/issues/43736
Changed the following 3 scripts to run with DBot role as they don't pose a security concern, and also don't work otherwise:
- **ExtractIndicatorsFromTextFile**
- **ExtractIndicatorsFromWordFile**
- **ReadPDFFileV2**
No

Changed file extraction scripts to use DBot role

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2_test.py
Packs/ServiceNow/Integrations/ServiceNowv2/test_data/result_constants.py
Packs/ServiceNow/ReleaseNotes/2_2_14.md
Packs/ServiceNow/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43868 
In servicenow-query-tickets, the 'additional_fields' argument was not supporting nested values.

Servicenow v2 - added support for nested 'additional fields' argument

---

Tests/scripts/collect_tests_and_content_packs.py

In cases of server integrations the `id_set__get_integration_file_path` function returns `None`, which then fails the `tools.get_pack_name(int_path)` function.

Added condition for None path

---

Packs/GenericWebhook/Integrations/GenericWebhook/README.md

fixes: https://github.com/demisto/content-docs/issues/837
Fixed an issue where the described request in the README.md of the integration had a missing header. The given request results an error response, adding the header fixes that.

Generic webhooks curl request headers fix in README.md

---

Tests/scripts/.secrets-ignore
Tests/scripts/download_demisto_conf.sh
Tests/secrets_white_list.json

https://github.com/demisto/etc/issues/40262
As part of the Gitlab migration, we want Content repository to download the updated content-test-conf content from Gitlab instead of Github.

clone content-test-conf repo from Gitlab instead of Github

---

Packs/Base/ReleaseNotes/1_15_7.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

Running arg_to_number on python 2.7 would fail due to mishandling of unicode object, this fix converts the unicode to str when needed.

Fix arg to number python2

---

Packs/CortexXDR/Dashboards/dashboard-Cortex_XDR.json
Packs/CortexXDR/ReleaseNotes/4_2_4.md
Packs/CortexXDR/Widgets/widget-Cortex_XDR_Unassigned_Incidents.json
Packs/CortexXDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43050
fixed the widget query.
this is only relevant for 6.5 so not specifying it in the RN.
before (shows incident 102):
after (incident 102 is filtered):

CortexXDR: fixed the XDR unassigned incidents widget for 6.5

---

Tests/conf.json

added McAfee ESM v2 - Test v11.1.3 to skipped integrations.

added McAfee ESM v2 - Test v11.1.3 to skipped integrations.

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/ReleaseNotes/1_7_5.md
Packs/PAN-OS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43224
the command should fail when attempting to edit an uncommitted rule.
improved the error handling.
before:
after:

Panorama: improved error handling

---

Packs/Base/ReleaseNotes/1_15_9.md
Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
Packs/Base/pack_metadata.json

Release for: https://github.com/demisto/dockerfiles/pull/6552
Release `sane pdf reports` build: `demisto/sane-pdf-reports:1.0.0.24891`. So that will bump *Base Pack* to `1.15.9`

Update Base Pack pdf sane reports script with new docker image

---

Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.py
Packs/HashiCorp-Vault/Integrations/HashiCorpVault/HashiCorpVault.yml
Packs/HashiCorp-Vault/Integrations/HashiCorpVault/README.md
Packs/HashiCorp-Vault/ReleaseNotes/1_0_4.md
Packs/HashiCorp-Vault/pack_metadata.json

added the `Concat username to credential object name` to handle the case there is more than one secret in the folder, which causes to fetch credentials under the same name and then integrations are unable to use them

HashiCorp Vault - add concat username to cred param

---

Packs/FeedMitreAttack/.pack-ignore
Tests/conf.json

related: https://panw-global.slack.com/archives/G011E63JXPB/p1638782192008900
Remove MITRE TPB from the test.conf file as deprecated.

Remove MITRE TPB as deprecated.

---

Packs/CommonPlaybooks/Playbooks/playbook-Block_IP_-_Generic_v3.yml
Packs/CommonPlaybooks/ReleaseNotes/2_1_4.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: [#44505](https://github.com/demisto/etc/issues/44505)
Changed a strange bug caused probably during the format action. 
Seems like the SDK changed the playbook to be with its ID instead with `playbookName` and `Name` variables.
Wrong 🔴 :
Right ✅ :

PB name change in the Block IP Generic V3 playbook

---

Packs/NetscoutAED/TestPlaybooks/NetscoutAED-Test.yml

The command name was mistakenly renamed as part of https://github.com/demisto/content/pull/15858 causing the test-playbook to fail.

fix test-playbook command

---

Tests/conf.json

NetscoutAED testPlaybook was fixed here: https://github.com/demisto/content/pull/16183
Removed it from skipped tests.

remove NetscoutAED-test playbook from skipped

---

Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
Packs/GreyNoise/ReleaseNotes/1_1_1.md
Packs/GreyNoise/pack_metadata.json

- The 1.1.0 version introduced a bug where the pack would no longer work with 6.1 and previous.  I've added a fix to allow it to work as expected on previous versions.

[greynoise-266] Fix bug that broke compatibility with pre-6.1 versions

---

Packs/FeedUnit42v2/Integrations/FeedUnit42v2/FeedUnit42v2.py
Packs/FeedUnit42v2/ReleaseNotes/1_0_6.md
Packs/FeedUnit42v2/pack_metadata.json

fixes: https://panw-global.slack.com/archives/C011E5T5K17/p1638866887083000
Fixed an issue where **unit42-get-indicators** command was not handled **limit** argument properly.

Unit42 ATOMs fix get-indicators command

---

Packs/Campaign/ReleaseNotes/3_1_6.md
Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.py
Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId.yml
Packs/Campaign/Scripts/GetCampaignIndicatorsByIncidentId/GetCampaignIndicatorsByIncidentId_test.py
Packs/Campaign/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/43586
Added associateIndicatorsToIncident so the indicators will be extracted and clickable.

Added associateIndicatorsToIncident ecxecution to GetCampaignIndicatorsByIncidentId script

---

dev-requirements-py2.txt

fixes: the build
lazy-object-proxy bumped versions and dropped support for python 2.7 Since Astroid depends on this package, we freeze it at 1.4.0 to meet the minimum required version for Astroid.

Freeze lazy-object-proxy pip package to 1.4.0

---

Packs/ContentManagement/Playbooks/playbook-Configuration_Setup.yml
Packs/ContentManagement/ReleaseNotes/1_1_0.md
Packs/ContentManagement/pack_metadata.json

This PR updates the ContentManagement packs playbook for users wanting to leverage the simple `!http` command to download custom content packs.
Currently the command uses POST, but this is probably not as common as uses GET for servers hosting un authenticated files. Presumably the end user will host files on an internal webserver which xsoar has access to. I would suspect the client to use a GET method when downloading these files.
Either way the current name pulled back by the `!http` command would be `http-file` by default.  The conditional in …

Update http artifact method to GET request and change naming assumptions

---

Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine.py
Packs/CortexXDR/Integrations/XQLQueryingEngine/XQLQueryingEngine_test.py
Packs/CortexXDR/ReleaseNotes/4_2_11.md
Packs/CortexXDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/44876
Removed the notes validations since the code can run without this validation and cant run regexs in the query without it.

Fix xql note bug

---

Tests/conf.json

Ready
Related to this merge request on GitLab: https://code.pan.run/xsoar/content-test-conf/-/merge_requests/1346
I added a new Demisto Lock instance in the conf.json in test-conf which has a very long timeout (9000).
Now I'm updating the Phishing Campaign test to use the instance with the longer timeout to avoid failures when phishing incidents take long.
6.0.0
No

Changed the Demisto Lock instance in the Phishing Campaign test

---

Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-JOB_-_Integrations_and_Playbooks_Health_Check.yml
Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_3.md
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/44607
Added another check to the condition to see if found failed tests.

Health check add condition

---

Tests/conf.json

Ready
Related to: https://code.pan.run/xsoar/content-test-conf/-/merge_requests/1347
Related to: https://github.com/demisto/content/pull/16533
- Changed existing tests in conf.json to use specific instances in accommodation for added instances in test-conf (see related issues)
- Removed mistakes in conf.json - `Actual Incident` tests were wrongly added by a script that updated conf.json automatically
- Fixed a mistake where "Phishing - Cre" was skipped, instead of "Phishing - Core" test
No

Changed existing tests in conf.json to accommodate for new instances in test-conf

---

Packs/ThreatIntelReports/Layouts/layoutscontainer-ThreatIntelReport-ExecutiveBriefReport.json
Packs/ThreatIntelReports/ReleaseNotes/1_0_5.md
Packs/ThreatIntelReports/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/45082
Set all "Report Body" section headers to hidden.

[TIR] TIR layout fixes dror

---

Packs/Phishing/Playbooks/Phishing_Investigation_-_Generic_v2_-_6_0.yml
Packs/Phishing/ReleaseNotes/2_5_4.md
Packs/Phishing/pack_metadata.json

Ready
Related to: https://github.com/demisto/content/pull/16533
and https://github.com/demisto/etc/issues/44049
- Changed the playbook to authenticate emails by default.
- Phishing prediction model name can now be configured in playbook inputs.
This will be usable for us to later test this model in phishing tests.
6.0.0
No

Added ML model name for phishing type prediction to playbook inputs

---

Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.py
Packs/GreyNoise/Integrations/GreyNoise/GreyNoise.yml
Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.py
Packs/GreyNoise/Integrations/GreyNoise_Community/GreyNoise_Community.yml
Packs/GreyNoise/ReleaseNotes/1_1_2.md
Packs/GreyNoise/pack_metadata.json

fixes: N/A
This is update the Pack to use an updated docker image, which includes an update to the GreyNoise SDK.
The SDK now prevents non-routable IPs from being sent to the GreyNoise API and reports the error to the client:

[greynoise-266] Update dockerfile to support latest GreyNoise SDK

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/ReleaseNotes/1_8_2.md
Packs/PAN-OS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/45101
In case there is error in getting the url category - return CommandResult with detailed info instead of throwing an exception

Panorama grt-url-catagory: return CommandResult instead of raise exception

---

Packs/Campaign/TestPlaybooks/Phishing_Investigation_-_Generic_v2_-_Campaign_Test.yml
Tests/conf.json

Ready
fixes: https://github.com/demisto/etc/issues/44740
An attempt to fix a bug that happens when incidents are created and investigated and their playbook is changed quickly. Added sleeps in between to let incidents settle down.
6.0.0
No

Phishing Campaign test - speculative fix for server "version conflict" error

---

Packs/Campaign/pack_metadata.json
Packs/CommonDashboards/pack_metadata.json
Packs/CommonReports/pack_metadata.json
Packs/CommonWidgets/pack_metadata.json
Packs/CortexXDR/pack_metadata.json
Packs/CrowdStrikeFalconStreamingV2/pack_metadata.json
Packs/ElasticsearchMonitoring/pack_metadata.json
Packs/EmployeeOffboarding/pack_metadata.json
Packs/Expanse/pack_metadata.json
Packs/ExpanseV2/pack_metadata.json
Packs/IAM-SCIM/pack_metadata.json
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json
Packs/MultiTenantPerformance/pack_metadata.json
Packs/ShiftManagement/pack_metadata.json
Packs/TIM_Processing/pack_metadata.json
Packs/TIM_SIEM/pack_metadata.json
Packs/ThreatIntelReports/pack_metadata.json
Packs/Traps/pack_metadata.json

related: https://github.com/demisto/etc/issues/44221
removed the following packs from MPv2:
1. Campaign
2. CommonDashboards
3. CommonReports
4. CommonWidgets
5. CortexXDR
6. CrowdStrikeFalconStreamingV2
7. ElasticsearchMonitoring
8. EmployeeOffboarding
9. Expanse
10. ExpanseV2
11. IAM-SCIM (IAM pack is in a different repo)
12. IntegrationsAndIncidentsHealthCheck
13. MultiTenantPerformance
14. ShiftManagement
15. TIM_Processing
16. TIM - SIEM Integration
17. ThreatIntelReports
18. Traps

remove packs from marketplace v2

---

Packs/AWS-ACM/ReleaseNotes/1_1_5.md
Packs/AWS-ACM/pack_metadata.json
Packs/AWS-CloudWatchLogs/ReleaseNotes/1_2_2.md
Packs/AWS-CloudWatchLogs/pack_metadata.json
Packs/AWS-EC2/ReleaseNotes/1_2_7.md
Packs/AWS-EC2/pack_metadata.json
Packs/AWS-GuardDuty/ReleaseNotes/1_2_2.md
Packs/AWS-GuardDuty/pack_metadata.json
Packs/AWS-IAM/ReleaseNotes/1_1_8.md
Packs/AWS-IAM/pack_metadata.json
Packs/AWS-Lambda/ReleaseNotes/1_2_6.md
Packs/AWS-Lambda/pack_metadata.json
Packs/AWS-S3/ReleaseNotes/1_1_3.md
Packs/AWS-S3/pack_metadata.json
Packs/AWS-SQS/ReleaseNotes/1_2_2.md
Packs/AWS-SQS/pack_metadata.json
Packs/AWS-SecurityHub/ReleaseNotes/1_1_6.md
Packs/AWS-SecurityHub/pack_metadata.json
Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py

fixes: https://github.com/demisto/etc/issues/45557
To prevent similar issues in the future I have decided to fix the AWSApiModule.get_timeout method.
Kept the original code that parse strings to avoid regression issues.

AWS API Module get timeout fix

---

Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/2_3_2.md
Packs/Slack/pack_metadata.json

Didn't create the issue in github, but Slack often times out when querying Channel ID. This should alleviate that problem if actions are coming right after a create.
Add channel ID to context after creating channel to speed up further actions (such as a welcome message, or inviting a large number of additional users)

SlackV3: Add Channel ID when Creating Channel

---

Tests/scripts/validate.sh

fixes: https://github.com/demisto/etc/issues/40489
added the following validation: if the branch name is `demisto/python` or `demisto/python3` then run `demisto-sdk validate` with `--no-conf-json` flag.
opened 3 different branches to test, changed an integration that doesnt have TPB and UT:
- branch name demisto/python: https://github.com/demisto/content/pull/16877
- branch name demisto/python3: https://github.com/demisto/content/pull/16960
- some common branch name: https://github.com/demisto/content/pull/16969
also changed the sdk to run as master in the above PRs, since the current version is not supporting `--no-conf-json` flag

Ignore conf json validation if the branch is one of the docker updates

---

Packs/PrismaCloud/TestPlaybooks/playbook-RedLockTest.yml
Tests/conf.json

- Unskip Redlock TPB after new credentials were added
- Update the TPB to search for alerts within the last week and not the last year since there are many alerts and it causes the query to timeout.

Update TPB and remove test from skipped

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/2_4_1.md
Packs/Slack/pack_metadata.json

fixes: issue identified via slack
I botched a merge while releasing that last version and accidentally reverted this minor change.

Fix for SlackV3 Operand Error on missing Bot ID

---

Packs/CommonPlaybooks/Playbooks/playbook-Email_Address_Enrichment_-_Generic_v2.1.yml
Packs/CommonPlaybooks/ReleaseNotes/2_1_9.md
Packs/CommonPlaybooks/pack_metadata.json

Ready
fixes: https://github.com/demisto/etc/issues/43001
Fixed a bug that caused the domain-squatting check to produce incorrect results.
The bug has been there for a very long time, and happened because of the old change for `WhereFieldEquals` transformer where they changed the "stringify" argument to "true" by default.
Before the fix:
After the fix:
- 5.0.0
No

Phishing domainsquatting fix

---

Packs/RedCanary/Integrations/RedCanary/RedCanary.py
Packs/RedCanary/ReleaseNotes/1_1_5.md
Packs/RedCanary/pack_metadata.json

The API path for the execute playbook functionality of the integration is out of date.
Current API doc from Red Canary:
Error when using the function:
- Further details: Fixes already broken external dependency.

Update playbook api path

---

Packs/MISP/TestPlaybooks/playbook-MISPV3-Test.yml

Fixed MISP test-playbook to use the MISP brand when calling generic commands (IP, Domain, URL etc).

Fix MISP test-playbook

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/ReleaseNotes/2_1_26.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/45981
Enhance the test_module resiliency by:
- Try to retrieve the last successfully retrieved offense
- - Only check the events query, without actually retrieving events

Enhance test_module Resiliency

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/README.md

N/A
Added note that `cs-falcon-run-command` `scope=admin` is required for an RTR `put` command. This seems to be a common use case and I have seen this question from clients a few times. Not sure the best place to put this note; feel free to move it to a different part of the page. Maybe start a FAQ or Troubleshooting section?
N/A

Add note on required input for RTR `put` command

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/ReleaseNotes/1_1_15.md
Packs/UrlScan/pack_metadata.json

The integration recognizes urlscan rejecting a scan submission due to the target being on the service's blacklist by comparing against the HTTP Error message. The message returned by urlscan indicating a blacklisted URL has changed in its wording, so this patch simply reflects that change.

Blacklist fix

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/2_4_4.md
Packs/Slack/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/44744
Fixed an issue where a user's email was not retrieved successfully while responding to a question

SlackV3 user email retrieval was unsuccessful

---

Tests/conf.json

related: [44199#event-5981364193](https://github.com/demisto/etc/issues/44199#event-5981364193).
MailListetner-POP3 Test was failing due to a socket error connection which was fixed.
Unskipping the test. 

Unskipping MailListetner-POP3 Test

---

Tests/Marketplace/core_packs_mpv2_list.json

add CoreAlertFields as core pack in mpv2

MPv2: add CoreAlertFields as core pack in mpv2

---

Packs/Phishing/pack_metadata.json

Adding the Core Alert Fields pack as a dependency to the Phishing pack.

adding core alert fields as a dependency

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/ReleaseNotes/1_4_6.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: [link to the issue](https://github.com/demisto/etc/issues/46351)
Fix NoneType error in CrowdStrikeFalcon `endpoint` command.

Fix NoneType error in CrowdStrikeFalcon `endpoint` command

---

Packs/ApiModules/Scripts/FireEyeApiModule/FireEyeApiModule.py
Packs/FireEyeCM/Integrations/FireEyeCM/FireEyeCM_description.md
Packs/FireEyeCM/Integrations/FireEyeCM/README.md
Packs/FireEyeCM/ReleaseNotes/1_1_8.md
Packs/FireEyeCM/pack_metadata.json
Packs/FireEyeEX/Integrations/FireEyeEX/FireEyeEX_description.md
Packs/FireEyeEX/Integrations/FireEyeEX/README.md
Packs/FireEyeEX/ReleaseNotes/2_0_5.md
Packs/FireEyeEX/pack_metadata.json

fixes: [46273](https://github.com/demisto/etc/issues/46273).
Increased the time buffer of API Key's validity to 10 minutes (it was set to 10 seconds by mistake). 

FireEye - Increasing the validity of the API Key

---

Utils/github_workflow_scripts/github_workflow_scripts_tests/run_docs_review_test.py

Skipping the `test_file_name_includes_apostrophe` until the new version of demisto-sdk will be released and the PR https://github.com/demisto/content/pull/17097 is merged as well.

Skip test - will be unskipped once the changes are merged.

---

Packs/Base/TestPlaybooks/playbook-Autoextract_-_Test.yml

fixes: [45293](https://github.com/demisto/etc/issues/45293)
Fixed tasks related to URLs and Domains extractions according to the updated behavior that was defined by the security team: 
According to @melamedbn:
1. A URL that doesn't start with a schema (such as 'https://', 'hxxps://') is not a URL but a Domain. Therefore the condition that was used to check whether the domain: 'www.thisoneshouldnotexisteither4444.com' was extracted to context as a URL by auto-extract was removed. 
2. Domains will be extracted exactly as they are (including the 'www' prefix). For example …

AutoExtract Test - Fixed tasks related to URLs and Domains extractions according to the updated behavior

---

Packs/EDL/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/46712
Add edl, pan-os keywords to generic export indicators pack

add keywords to generic export indicators

---

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection.py
Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_4_1.md
Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json

fixes :[ link to the issue](https://github.com/demisto/etc/issues/46808)
- Fixed an issue where the ***microsoft-atp-sc-indicator-list*** command did not support FileMd5.

Microsoft Defender For Endpoint - support fileMD5

---

Packs/Base/ReleaseNotes/1_18_10.md
Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.py
Packs/Base/Scripts/DBotBuildPhishingClassifier/DBotBuildPhishingClassifier.yml
Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.py
Packs/Base/Scripts/GetIncidentsByQuery/GetIncidentsByQuery.yml
Packs/Base/pack_metadata.json

After the new change in the ML page, a but occurred when query argument was left empty.
1. Added a verification in DBotBuildPhishingClassifier if query is empty, and in that case treat it as no query was given
2. Fixed a bug in GetIncidentsByQuery, to first check if GetIncidents didn't return an error, and just then access the resukt

Ml bug empty query

---

Packs/ExportIndicators/pack_metadata.json
Packs/FeedProofpoint/pack_metadata.json
Packs/LogRhythm/pack_metadata.json
Packs/ProofpointServerProtection/pack_metadata.json
Packs/ProofpointTAP/pack_metadata.json
Packs/ProofpointThreatResponse/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/46963
fixes: https://github.com/demisto/etc/issues/46962
* deprecate LogRhythm SOAP pack
* remove Proofpoint packs from MPv2
* remove deprecated packs from MPv2

Deprecate LogRhythm SOAP pack and remove from MPv2

---

dev-requirements-py3.txt

Update SDK version to 1.6.1 hotfix - will fix validate timeout due to [SSLError and retries](https://code.pan.run/xsoar/content/-/jobs/11037613).

update SDK version to 1.6.1 hotfix

---

Packs/Campaign/ReleaseNotes/3_2_8.md
Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.py
Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign.yml
Packs/Campaign/Scripts/IsIncidentPartOfCampaign/IsIncidentPartOfCampaign_test.py
Packs/Campaign/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/46483
Fixed an issue where the script isIncidentPartOfCampaign fails on timeout.
Changed the incidents search to be by query and not by type.

Fixed timeout in isIncidentPartOfCampaign script

---

Packs/CTIX/Integrations/CTIX/CTIX.py
Packs/CTIX/Integrations/CTIX/CTIX_test.py
Packs/CTIX/ReleaseNotes/1_1_1.md
Packs/CTIX/pack_metadata.json

Fixes an issue where the context output of the ```ctix-create-intel``` command isn't correct.

CTIX - fix create intel command context output

---

Packs/Phishing/.pack-ignore
Packs/Phishing/ReleaseNotes/3_1_3.md
Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.py
Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity.yml
Packs/Phishing/Scripts/CheckEmailAuthenticity/CheckEmailAuthenticity_test.py
Packs/Phishing/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/46364
Added the argument original_authentication_header: The name of a header which holds the original value of the Authentication-Results header. This can be used when there is an intermediate server which changes the email and holds the original value of the header in a different header.

CheckEmailAuthenticity original header

---

.circleci/config.yml

fixes: https://app.circleci.com/pipelines/github/demisto/content/149599/workflows/3fc30491-9443-4d45-939a-3ae47f8742f4/jobs/491089
increase the time threshold with "no output" in the CircleCI job.

set no output timeout for validate in circleci

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeamsManagement/README.md

N/A
Fixed misleading arg description for `microsoft-teams-member-add` arg `user_id`. We were initially thrown off because the arg description says the value needs to be an ID that can only be retrieved by running a different command where the user is already a member of a team. However, we tested passing the user's email address as the `user_id` and this worked. Perhaps this option was added later on, and just the arg description was not updated. Not sure if the same thing applies to other commands in this integration.
N/A

Fixed misleading arg description

---

Packs/Phishing/Playbooks/Process_Microsoft's_Anti-Spam_Headers.yml
Packs/Phishing/ReleaseNotes/3_1_6.md
Packs/Phishing/pack_metadata.json

fixes: [link to the issue](https://github.com/demisto/etc/issues/47365)
- The task `Set BCL score` was addressed to extract the correct BCL scores (4-9) on the second transformer.

Bcl score fix

---

Packs/PagerDuty/Integrations/PagerDuty/PageDuty_test.py
Packs/PagerDuty/Integrations/PagerDuty/PagerDuty.py
Packs/PagerDuty/ReleaseNotes/1_1_2.md
Packs/PagerDuty/pack_metadata.json

Return original PagerDuty response in *PagerDuty-get-users-on-call-now* and *PagerDuty-get-users-on-call* commands.
It fixes issues with PagerDutyAssignOnCallUser script.

Return raw data in raw-response

---

Packs/Tenable_sc/Integrations/Tenable_sc/Tenable_sc.py
Packs/Tenable_sc/ReleaseNotes/1_0_5.md
Packs/Tenable_sc/pack_metadata.json

Today if you run tenable-sc-get-scan-report or another command followed by tenable-sc-get-vulnerability to get the details for each vulnerability the complete scan context is overwritten.  This fix allows the additional vuln data to be appended to the entries returned from the original scan report.

Fix bug in TenableSC context

---

Packs/qualys/Integrations/Qualysv2/Qualysv2.py
Packs/qualys/Integrations/Qualysv2/Qualysv2.yml
Packs/qualys/ReleaseNotes/1_0_17.md
Packs/qualys/pack_metadata.json

n/a
Add optional arguments to command `qualys-schedule-scan-update` to fix limitation where the command could not be used to update asset groups to include in scheduled scan. Args required for this use case:
- `id`
- `asset_groups`
- `target_from` (newly added in this PR)
- `iscanner_name` (newly added in this PR)
Contact developer for more info/screenshots if needed. (Cannot include in public repo.)

Add optional args to qualys-schedule-scan-update command

---

Packs/Slack/Integrations/SlackV3/SlackV3.yml
Packs/Slack/ReleaseNotes/2_5_4.md
Packs/Slack/pack_metadata.json

https://github.com/demisto/etc/issues/47267
Add value `failedFetchIncidents` to `permitted_notifications` multi-select in instance parameters so users know it exists. `failedFetchIncidents` can be added to receive system notifications via Slack for integration fetch failures.

Add value failedFetchIncidents to permitted_notifications in instance params

---

Packs/AWS-EC2/Integrations/AWS-EC2/README.md

n/a
Fix misleading arg descriptions for command `aws-ec2-revoke-security-group-ingress-rule` args `fromPort` and `toPort`. 
Follow-up to earlier PR https://github.com/demisto/content/pull/18112/, where I accidentally missed a place the descriptions needed changed.
My goal is to remove the part of the arg description highlighted here:
Please advise if something different needs to be changed to make that happen.

Fix lingering misleading arg description

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.yml
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
Packs/AzureSentinel/ReleaseNotes/1_3_4.md
Packs/AzureSentinel/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47457
Update fetch-incidents to support first fetch after upgrading the integration, as I originally did not take into account that the last_run dict will not be empty upon upgrading.

Bug - Azure Sentinel -  Update fetch-incidents to support first fetch after upgrading the integration

---

Packs/Securonix/.pack-ignore
Packs/Securonix/Integrations/Securonix/Securonix.py
Packs/Securonix/Integrations/Securonix/Securonix.yml
Packs/Securonix/ReleaseNotes/1_1_10.md
Packs/Securonix/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47274
Fix the proxy. No need to set self.proxies. The client handles this. By not passing the proxy param to the client it was actually deleting the proxy details from the env as the default is `proxy=False`.

securonix: proxy fix

---

Packs/MISP/Integrations/MISPV3/MISPV3.py
Packs/MISP/ReleaseNotes/2_1_4.md
Packs/MISP/pack_metadata.json

Because `extend` method expects "iterable" as parameter then, when `url_parse.scheme` was provided, string `"scheme"` was added to `url_obj` list ( should be dict `{"scheme": url_parse.scheme}`).
Because string `"scheme"` is not a `dict`, `build_generic_object` function throw error in such case.
Fix ***misp-add-url-object** command

Fix `misp-add-url-object` command

---

Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel.py
Packs/AzureSentinel/Integrations/AzureSentinel/AzureSentinel_test.py
Packs/AzureSentinel/ReleaseNotes/1_3_9.md
Packs/AzureSentinel/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47751
There was a problem in sending correctly the information of the threat indicator, resulting in a problem in the data that was printed in the war room:
3 changes:
1. The pattern entry misses a quotation marks:
2. Indicator type of type ipv4/ipv6 needs to be sent as "ipv4-addr"/"ipv6-addr" instead of "ipv4-address"/"ipv6-address"
3. The entry "patternType" needs to be the indicator type, and not the value of the indicator.
Also, There is no entry called "patternTypes" as seen here in the API documentation: …

bug - azure sentinel - create threat intelligence indicator command small fixes

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama_test.py
Packs/PAN-OS/ReleaseNotes/1_11_1.md
Packs/PAN-OS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47779
fixes: https://github.com/demisto/etc/issues/47780
1) Fixed an issue in which ```pan-os-edit-rule``` command fails on ```KeyError``` when trying to disable a rule in Panorama.
2) Fixed another issue in which ```pan-os-edit-rule``` command always set ```element_value``` argument to 'yes' which makes it impossible to enable a rule from a disabled state

Fix pan-os-edit-rule command bug

---

Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py

replaced a use of a `demisto-sdk.TestSuite` with an equivalent function, as TestSuite will soon no longer be part of the SDK pack.

fix: remove testsuite usage

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/2_3_7.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47523
in  mirror in iteration - currently we return only few fields from the updated notable 
this lead to a bug when classifier is based on a field that missed in the mirror in object 
the classifier will fail to classify the mirrored in object as the key are missed

Return the whole object in mirror in

---

Packs/Elasticsearch/.pack-ignore
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
Packs/Elasticsearch/ReleaseNotes/1_2_8.md
Packs/Elasticsearch/pack_metadata.json

fixes: [link to the issue](https://github.com/demisto/etc/issues/47854)
When the index is a date with a decimal ending ( e.g "2022-04-06T10:23:29.571Z"), the date is not parsed properly.

Elasticsearch v2 incident timestamp fix

---

Packs/MailListener/Integrations/MailListenerV2/README.md

related: https://github.com/demisto/etc/issues/47530
Added to the readme, to explain why some emails may be skipped.

Mail listener v2 - added to the readme

---

Packs/McAfeeWebGateway/Integrations/McAfeeWebGateway/McAfeeWebGateway.js
Packs/McAfeeWebGateway/ReleaseNotes/1_0_2.md
Packs/McAfeeWebGateway/pack_metadata.json

With this change, the command mwg-get-available-lists now shows the internal McAfee ID and also the Name assigned to the List. 
This is very useful when trying to get a specific list ID when you only know the referenced name.
fixes: Nothing 
With this change, the command mwg-get-available-lists now shows the internal McAfee ID and also the Name assigned to the List. 
This is very useful when trying to get a specific list ID when you only know the referenced name.
- [x ] 6.0.0
- [ x] No

Modified the function get_lists to get extended information

---

Packs/rasterize/Integrations/rasterize/rasterize.py

Currently the rasterize_email_command() function does not have any functionality to alter the timeout from the default of 180 set in the rasterize() function. This can be fixed by using the same logic for setting the max_page_load_time found in the rasterize_command() function. This change will help allow clients to alter the timeout for HTML rasterization of larger emails that sometimes fall outside of the 180 second default.
Another option for this fix would be adding an argument to the function within the integration to allow this variable to be set dynamically instead of using the default set in the integration params (which is what this submitted request would end up defaulting to).
Make sure to register your contribution by filling the [contribution registration …

Add timeout functionality to rasterize_email_command

---

Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml
Packs/AWS-SQS/Integrations/AWS-SQS/README.md
Packs/AWS-SQS/ReleaseNotes/1_2_6.md
Packs/AWS-SQS/pack_metadata.json

This adds a new parameter `parse_body_as_json` to the fetch incidents routine. When marked as `True` it will parse the `Body` field of the retrieved SQS message as a JSON string and convert it to a Python dictionary. When the message is then converted back to a JSON string and put into the `incident["rawJSON"]` field the message body will not be double-encoded. This will allow any mapper associated with the integration to not need to use a transform in order to parse the `Body` string.
Since not all SQS message `Body` values are JSON strings this parameter is left as …

add parameter to parse SQS body as json

---

Packs/MergeDictArray/ReleaseNotes/1_0_2.md
Packs/MergeDictArray/Scripts/MergeDictArray/MergeDictArray.js
Packs/MergeDictArray/pack_metadata.json

N/A
- Fixed an issue where the only one value has been left when 2 or more values are matched.
- Supported to combine dictionary values
Supported to combine dictionary values

Fixed an issue where the only one value has been left when 2 or more values are matched.

---

Tests/scripts/is_file_up_to_date.sh

As discussed in [this thread](https://panw-global.slack.com/archives/G011E63JXPB/p1651054031148029?thread_ts=1650878743.581249&cid=G011E63JXPB), we need a better indication that there's an error in the build when a file has changed and needs to be updated.
Removed backticks and replaced with `$(...)` as backticks are deprecated in `bash`. See http://mywiki.wooledge.org/BashFAQ/082.

Add ERROR to indicate file was changed

---

.github/CODEOWNERS
.gitlab/ci/on-push.yml

Improve xsiam build:
- Run xsiam flow only when tests were found. 
- Run after script only if xsiam machine was locked.

Improve xsiam build - Run xsiam flow only when tests were found. 

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
Packs/UrlScan/ReleaseNotes/1_1_20.md
Packs/UrlScan/pack_metadata.json

In v1.1.17, the *scan_visibility* argument was introduced for the ***url*** and ***urlscan-submit*** commands, alongside an integration-wide *scan_visibility* parameter. The argument for the two commands had been configured to have a default value of `public`, and this argument overrides all other settings related to visibility. This meant that all other visibility settings (such as the *public* argument, the *is_public* integration parameter, and the urlscan.io service provider-side default visibility setting) were implicitly rendered ineffectual. …

Visibility fix

---

Packs/CommonPlaybooks/Playbooks/playbook-Search_And_Delete_Emails_-_Generic_-_v2.yml

N/A
Remove newline from playbook input name **O365AllowNotFoundExchangeLocations**. The extra newline in the input name caused the playbook to not work as expected.
Playbook input before change:

Fix newline in input name O365AllowNotFoundExchangeLocations

---

Packs/AzureFirewall/Integrations/AzureFirewall/AzureFirewall.yml

fixes: failing upload
pack contains a single integration with `fromversion: 6.2.0` causing the pack minimum version to be 6.2.0.
when the upload pipeline tried to install it on 6.1, it fails to install and blocks the upload.
**This PR is a workaround and we will fix the upload flow to better handle those cases.**
In addition, it did not fail the branch build since it did not spin a 6.1 machine: https://github.com/demisto/content/pull/18856

update integration fromversion (workaround)

---

Packs/EWSMailSender/.pack-ignore
Packs/EWSMailSender/.secrets-ignore
Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender.py
Packs/EWSMailSender/Integrations/EWSMailSender/EWSMailSender_test.py
Packs/EWSMailSender/ReleaseNotes/1_1_8.md
Packs/EWSMailSender/pack_metadata.json

fixes an issue where the ```replyTo``` argument is being passed as a string while it should be passed as a list of strings.

ews-mail-sender-reply-to-bug

---

Utils/download_packs_and_docker_images.py

When running `download_packs_and_docker_images.py` without the `-p` option, all packs will be collected.

Download Packs and Docker Images - add option to run on all packs

---

Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.yml

The parameter in the yaml file to indicate the SQS body should be parsed as JSON is `parse_body_as_string` but the script is looking for `parse_body_as_json`.

fix parameter reference for sqs parse body as json

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md

A lot of bugs were open because of bad documentation. 
Many customers are not paying attention to using `App Studio` during configuration it is deprecated.
Improved the deprecated note, and wrote to use `Developer portal` instead. 
fixes: https://github.com/demisto/etc/issues/48263

Teams documentation impovment

---

Tests/Marketplace/configure_and_install_packs.py

Upload flow failed when trying to install packs that has fromversion above 6.2
Opened an issue to add filtering. 
https://jira-hq.paloaltonetworks.local/browse/CIAC-2626

Revert to installing all packs in upload flow

---

Packs/AWS-SQS/Integrations/AWS-SQS/AWS-SQS.py
Packs/AWS-SQS/ReleaseNotes/1_2_8.md
Packs/AWS-SQS/pack_metadata.json

The current implementation of the SQS fetch incidents has an error that occurs when the script takes longer than the visibility timeout of the receive message call, currently 5 seconds. Since the messages aren't removed from the queue until after they have been sent as incidents to XSOAR they can reappear during successive iterations of the while loop causing duplicate incidents to be created.
The proposed solution is to create the incidents and delete the queue messages during each iteration of the while loop while also increasing the visibility timeout to 30 seconds.

increase sqs message visibility timeout 

---

Packs/ProofpointTAP/IncidentFields/incidentfield-ProofPointTAP_Subject.json
Packs/ProofpointTAP/ReleaseNotes/1_1_15.md
Packs/ProofpointTAP/Scripts/ProofpointTAPMostAttackedUsers/ProofpointTAPMostAttackedUsers.yml
Packs/ProofpointTAP/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/47347
fixes: https://jira-hq.paloaltonetworks.local/browse/XDRSUP-12565
Changed the type of "Proofpoint Tap Subject" incident field from "shortText" to "longText".

Changed the type of "Proofpoint Tap Subject" incident field

---

Packs/GitHub/ModelingRules/GithubModelingRules/GithubModelingRules.xif
Packs/GitHub/ModelingRules/GithubModelingRules/GithubModelingRules.yml
Packs/GitHub/ReleaseNotes/2_0_2.md
Packs/GitHub/pack_metadata.json

Update `created_at` field type to `datetime`
To convert the field `created_at` to `datetime` I used the functions:
- timestamp_seconds
- to_integer
- divide
Because the value of `created_at` is miliseconds so `1653391014592` converted to `May 24th 2022 14:16:55` by this line:
`timestamp_seconds(to_integer(divide(created_at, 1000)))`

Github - Fix Modeling Rule 

---

Packs/CortexXDR/Playbooks/playbook-Cortex_XDR_-_Block_File.yml
Packs/CortexXDR/ReleaseNotes/4_5_3.md
Packs/CortexXDR/pack_metadata.json

Due to failure in the following [build](https://app.circleci.com/pipelines/github/demisto/demisto-sdk/16565/workflows/ffc543db-93e4-49d5-80be-bf57e47354a6/jobs/103300), changed the usage of a deprecated command to a none-deprecated one as advised by @bziser 

Switch deprecated commands cortex xdr

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_constants.py
Tests/Marketplace/marketplace_services.py

Ciac 604 pr number on rn

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_services.py

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-2974)
Fixed the check for a siem pack by checking if the integration have the `isfetchevents` field under `script` and not in the root file.

Fixed Collection tag for integrations with isfetchevents

---

Packs/IBMResilientSystems/Integrations/IBMResilientSystems/IBMResilientSystems.yml
Packs/IBMResilientSystems/ReleaseNotes/1_0_10.md
Packs/IBMResilientSystems/pack_metadata.json

If you check the code below:
URL = demisto.params()['server'][:-1] if demisto.params()['server'].endswith('/') else demisto.params()['server']
URL = URL.replace('http://', '').replace('https://', '')
SERVER, PORT = URL.rsplit(":", 1)
We will use rsplit to get SERVER and PORT from URL. But the original description of URL will let customers put ip or hostname only and get the following error message: Script failed to run: Error: [Traceback (most recent call last): File "<string>", line 35, in <module> ValueError: need more than 1 value to unpack ] (2604) (2603)
The customers without programming capability will have no idea how to solve it.
**The Pull Request will be …

Little fix for the description of Server URL parameter.

---

Packs/CommonScripts/ReleaseNotes/1_6_71.md
Packs/CommonScripts/Scripts/ParseEmailFiles/ParseEmailFiles.py
Packs/CommonScripts/pack_metadata.json

https://xsoar.ideas.aha.io/ideas/FR-I-2619
Modify conditional to get script to work for particular file type, `MIME entity, ISO-8859 text, with very long lines, with CRLF line terminators`. The conditional was previously checking for string `MIME entity text, ISO-8859 text`, which should have matched but did not, simply because of the extra word `text`.
I realize this script is deprecated, but it is an easy fix and would be useful for the customer. This script is actually easier to fix than `ParseEmailFilesV2`, which also errors on the same file, because …

Fix error to get script to work on particular MIME entity file type

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/ReleaseNotes/2_4_4.md
Packs/SplunkPy/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-12964
Fixed an issue where **splunk-kv-store-collection-search-entry** command failed when limit was provided in *query*.

[Fix] splunk-kv-store-collection-search-entry not working with values containing substring "limit"

---

Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml
Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/README.md
Packs/AWS-GuardDuty/ReleaseNotes/1_2_6.json
Packs/AWS-GuardDuty/ReleaseNotes/1_2_6.md
Packs/AWS-GuardDuty/pack_metadata.json

N/A
Mark defaultRegion param as mandatory because, as customer pointed out, the Test will not pass unless a defaultRegion is specified.
Note: I got validation error `IN116` on this change, but it was unclear from the error message how to fix the error.
- Further details: Possibly: if there is something I am missing where the integration could work without defaultRegion specified. If the reviewer has access to a GuardDuty test environment and could validate, that would be helpful. In the event of backward compatibility concerns, we should at least update the integration …

Mark defaultRegion param as mandatory

---

Packs/CommonScripts/.pack-ignore
Packs/CommonScripts/ReleaseNotes/1_7_0.md
Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry.py
Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry.yml
Packs/CommonScripts/Scripts/GetErrorsFromEntry/GetErrorsFromEntry_test.py
Packs/CommonScripts/Scripts/GetErrorsFromEntry/README.md
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-2953
Adds an automation called `GetErrors` that similarly to the `isError` automation, accepts `${lastCompletedTaskEntries}` as input, checks the entries for errors, and returns the error messages from those entries if they were indeed errors.

Add GetErrors PB Error Handling Utility Script

---

Packs/CommonScripts/ReleaseNotes/1_7_2.md
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13059
- Fixed an issue where some PDF files failed on `Could not find object` error.

ReadPDFFileV2 bug fix

---

Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement.py
Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_18.md
Packs/MicrosoftGraphDeviceManagement/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13316)
Fixed an issue where `msgraph-wipe-device` failed to execute.
Before:
After:

MS graph fix wipe device command

---

Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.py
Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub.yml
Packs/GooglePubSub/Integrations/GooglePubSub/GooglePubSub_test.py
Packs/GooglePubSub/Integrations/GooglePubSub/test_data/commands_outputs.json
Packs/GooglePubSub/Integrations/GooglePubSub/test_data/raw_responses.json
Packs/GooglePubSub/ReleaseNotes/1_0_15.md
Packs/GooglePubSub/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13074
Fixed an issue where messages with backslashes were improperly decoded.

[Google Pub/Sub] Improve Messages Decode

---

Packs/Phishing/Layouts/layoutscontainer-Phishing_v_3.json
Packs/Phishing/ReleaseNotes/3_2_4.md
Packs/Phishing/pack_metadata.json

Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3195
Fixed an issue where the email brand from which emails should be deleted was not available for selection and was not shown in the layout.
6.1.0
No

Fixed a bug with deleting email from the layout

---

Packs/CommonScripts/ReleaseNotes/1_7_4.md
Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.py
Packs/CommonScripts/Scripts/DockerHardeningCheck/DockerHardeningCheck.yml
Packs/CommonScripts/pack_metadata.json

- Added support for cgroups v2
- Fixed support for memory check_type=allocate
- Updated the Docker image to: demisto/python3:3.10.4.30607
When using Ubuntu 22.04 the memory check was failing due to Ubuntu changing to cgroups v2. The file path with the max RAM value was changed to a shared path. This update adds support for cgroups v2 without removing support for cgroups v1.
While adding this support, I noticed the memory_check argument options did not match the code for allocate. I updated the code to use the `allocate` option instead of `allocation`. If a user supplied …

Added cgroups v2 support to DockerHardeningScript

---

Packs/EmailCommunication/README.md

Contributot credits were shown twice because they were added to the contributors.md and the readme.md. removed from readme.

remove double contributor credits

---

Packs/Base/ReleaseNotes/1_31_5.md
Packs/Base/Scripts/ValidateContent/ValidateContent.yml
Packs/Base/pack_metadata.json

updating the ValidateContent to use a hotfixed version of `xsoar-tools`. 
fixes https://jira-hq.paloaltonetworks.local/browse/XSUP-12499
see also https://jira-hq.paloaltonetworks.local/browse/CIAC-3277

xsoar tools hotfix

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/ReleaseNotes/2_0_5.md
Packs/Jira/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13542
When the integration is configured to start fetch and there are more then 50 incidents to fetch, then it will fetch only the latest 50 incident because the original query gets the issues in descending order, and in the next fetch it uses the last issue id to filter, so any older ticket that were expected to be fetched were missed.

Fix Jira first fetch

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/ReleaseNotes/2_0_6.md
Packs/Jira/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13659
application name argument was not checked to be None before added to the request.

Jira fix application name check

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/ReleaseNotes/1_14_5.md
Packs/PAN-OS/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-13902)
This PR fixes an issue where in panorama integration when trying to retrieve threat pcap files, it fails even in cases where those pcaps actually exist in the firewall.

Fix panorama pcap bug

---

Packs/FeedMitreAttackv2/Integrations/FeedMitreAttackv2/FeedMitreAttackv2.py
Packs/FeedMitreAttackv2/ReleaseNotes/1_1_2.md
Packs/FeedMitreAttackv2/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3312
Fixed an issue in the command **attack-pattern** where providing an incorrect *attack_pattern* in a list would skip all subsequent valid attack_patterns.

MITRE ATT&CK v2 handle incorrect attack-pattern 

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_8_8.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-14065)

Falcon get detections bug fix

---

Tests/conf.json

skip firewall test-playbooks due to env issues
will be resolved by [firewall-test-playbooks-failures-issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3459)

skip firewall test playbooks

---

Packs/PhishingURL/Scripts/DBotPredictURLPhishing/README.md

Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3461
Added a security disclaimer as the DBotPredictURLPhishing script uses Rasterize which has a security recommendation for docker network hardening.

Updated DBotPredictURLPhishing readme with security disclaimer

---

Packs/FeedMitreAttack/Integrations/FeedMitreAttack/FeedMitreAttack.yml

Added "no tests" to MITRE v1 (deprecated) integration

---

Packs/TrendMicroVisionOne/Integrations/TrendMicroVisionOne/TrendMicroVisionOne.py
Packs/TrendMicroVisionOne/ReleaseNotes/1_2_1.md
Packs/TrendMicroVisionOne/pack_metadata.json
Tests/known_words.txt

https://github.com/demisto/content/pull/20012
Removed unnecessary `proxy` constructor arg from `BaseClient` subclass in TrendMicro VisionOne integration.

Removed unnecessary proxy constructor arg

---

Packs/CortexXDR/IncidentFields/XDR_Modification_time.json
Packs/CortexXDR/ReleaseNotes/4_8_1.md
Packs/CortexXDR/pack_metadata.json

 Removed the unsupported *fromServerVersion* field from Incident Fields

---

Packs/CommonTypes/ReleaseNotes/3_2_40.md

[link](https://panw-global.slack.com/archives/C011J0AP7J8/p1658175578351409)
Update the release-notes of the `CommonTypes` (3.2.40) so in case as below customers should install the `CommonTypes` anyway

update rn for CommonTypes 3.2.40

---

Packs/EDL/README.md

removed `what does this pack do` section, as we explain it beforehand.

export IOC service - better readme

---

Packs/ServiceNow/Integrations/ServiceNowv2/README.md

Added that you need read access to sys_journal_field for Configuring the ServiceNow Service Account Roles
- [ x] Ready
https://jira-hq.paloaltonetworks.local/browse/XSUP-14797
Added read access to sys_journal_field is required for incoming mirroring in the Configure the ServiceNow Service Account Roles.

SNOW mirroring permissions - Update README.md

---

Packs/PAN-OS/.pack-ignore
Packs/PAN-OS/Integrations/Panorama/Panorama.yml
Packs/PAN-OS/Integrations/Panorama/README.md
Packs/PAN-OS/ReleaseNotes/1_14_12.md
Packs/PAN-OS/pack_metadata.json

There is a typo in the bloc "Panorama - Create custom block rule" for the "where" and "dst" inputs descriptions.
The "dst" input must be filled only if you choose "before" or "after" in the "where" input, but it says "top" or "bottom".

Fix typo in inputs description for pan-os-custom-block-rule

---

Packs/rasterize/Integrations/rasterize/rasterize.py
Packs/rasterize/ReleaseNotes/1_2_2.md
Packs/rasterize/TestPlaybooks/playbook-Rasterize_Test.yml
Packs/rasterize/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-14769)
Fixed an issue in rasterize-email where the output was 'jpeg' type instead of 'png' type.
Before:
After:
Fixed an issue in rasterize-email where the output was 'jpeg' instead of 'png'.

Rasterize - Changed the output to be "png" instead of "jpeg"

---

README.md

Fix "Open in Visual Studio Code" broken shield on README.

Fix VSCode broken SVG shield on README

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
Packs/CortexXDR/Integrations/CortexXDRIR/README.md
Packs/CortexXDR/ReleaseNotes/4_8_5.md
Packs/CortexXDR/pack_metadata.json

Deprecate commands for the XDR IR pack.
https://jira-hq.paloaltonetworks.local/browse/CIAC-2072

Deprecate XDR IR Commands

---

Packs/QRadar/Classifiers/classifier-QRadar_-_Generic_Incoming_Mapper.json
Packs/QRadar/ReleaseNotes/2_2_5.md
Packs/QRadar/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3627

Qradar mapper date bug fix

---

Packs/Base/ReleaseNotes/1_31_14.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fixes: internal
So XSOAR API Metrics actually supports server versions _6.8.0_ and above. Not starting at 7.0.0. In my defense, we weren't sure exactly what version this was going to be and it changed quite a bit. Either way, I will wear my :shame_wizard: badge. @bakatzir Please accept this PR as retribution for my sins against `content`.

CommonServerPython Fix API Metrics Supported Version

---

Packs/AutoFocus/Integrations/FeedAutofocus/README.md

fixes:[ link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-14421)
The daily feed of autofocus is deprecated. added this to the readme as well. There is no available replacement, as this endpoint is not being updated anymore (this was the reason to deprecate the daily feed)

AutoFocus Feed fix

---

Packs/MailListener/Integrations/MailListenerV2/MailListenerV2.py
Packs/MailListener/Integrations/MailListenerV2/README.md
Packs/MailListener/ReleaseNotes/1_0_15.md
Packs/MailListener/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-13841
Fixed an issue where no mails are fetched when the parameter *The maximum number of incidents to fetch each time* is less than all mails received on the day of *First fetch time*.

[Mail Listener] First Fetch not Fetching All Mails in Given Time

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
Packs/QRadar/ReleaseNotes/2_2_8.md
Packs/QRadar/pack_metadata.json
Tests/conf.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14218
Fixed an issue where the search query is deleted from QRadar. We should create a new search in this case and not poll for the same search over and over.

create a new search if polling from qradar fails

---

Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml
Tests/conf.json

Fixed an issue where Microsoft defender test playbook didn't work. the test playbook assumes the first machine is the machine that actually should be an input to the `microsoft-atp-get-machine-users`, fixed that to get the right machine by the start of the prefix of the machine ID.
before:
after:

Fix microsoft defender test pbs

---

Packs/CommonScripts/ReleaseNotes/1_7_17.md
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.py
Packs/CommonScripts/Scripts/ReadPDFFileV2/ReadPDFFileV2.yml
Packs/CommonScripts/pack_metadata.json

When running ReadPDFFileV2 on an NFS/EFS file system (typically found on an HA setup of XSOAR), it will error out with OSError: [Errno 39] Directory not empty: 'ReadPDF'. This error is due to a file handle being left open in the code.
Since a file handle is left open, when the code runs line 520: shutil.rmtree(folder), the files in the folder are deleted but when the OS tries to delete the file with a file handle still open, it renames the files to .nfsXXXX until the file handle is closed. Since the script is holding it open, it won't close until the script ends. But the …

Fixed dangling file reference in ReadPDFFileV2

---

Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/playbook-Microsoft_Defender_Advanced_Threat_Protection-Test.yml

following this [PR](https://github.com/demisto/content/pull/20383)
Fixed an issue where Microsoft defender test playbook sometimes returns that there are logged users on the machines and sometimes not, this causes the test playbook to be flaky, hence will check now only if the 'Get Machine logged on users' will return an error if not, instead of checking whether it has a context output. if it does not return an error, command is working as expected even when there aren't any logged on users in the the environment 
before: 
after:
after running:

fix microsoft defender flaky test playbook

---

Packs/PAN-OS/Integrations/Panorama/Panorama.py
Packs/PAN-OS/ReleaseNotes/1_14_14.md
Packs/PAN-OS/pack_metadata.json

This is a bugfix for some minor issues;
* Commands that were using `get_single_device()` in the topology class would fail if the target was Panorama. This is because the pan-os-python SDK does not populate the device serial number for Panorama instances. This affected the following commands;
* pan-os-platform-reboot
To fix this issue, I've set the topology discovery function `add_device_object` to store the hostname in the relevant dictionaries instead of the serial number - this means the device dicts will always be keyed by Hostname for Panorama devices and Serial Number by firewalls. I've also updated the retrieval functions to reflect this. Previously, this was simply failing and literal `None` was being stored in the dictionary as the key for Panorama devices..
* LogForwardingProfile …

PAN-OS Integration - New Command Bugfixes

---

Packs/CortexXDR/Integrations/XDR_iocs/XDR_iocs.yml
Packs/CortexXDR/ReleaseNotes/4_8_12.md
Packs/CortexXDR/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-15331)

Xdr ioc add critical option

---

Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.py
Packs/HatchingTriage/Integrations/HatchingTriage/HatchingTriage.yml
Packs/HatchingTriage/Integrations/HatchingTriage/README.md
Packs/HatchingTriage/Integrations/HatchingTriage/command_examples.txt
Packs/HatchingTriage/Playbooks/playbook-Detonate_URL_-_Hatching_Triage.yml
Packs/HatchingTriage/ReleaseNotes/1_0_6.md
Packs/HatchingTriage/pack_metadata.json

* Adds the `triage-query-search` command to be able to use Triage search (https://tria.ge/docs/cloud-api/search/).
* The Detonate URL playbook genericpolling did not seem to work properly. It stopped polling after a single poll. It looked like this was caused by the "dt" not returning a sample ID until it had to stop. It now returns a sample ID until the analysis status is 'reported'.

Add search command and change detonate URL playbook for HatchingTriage

---

Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_8.md
Packs/CrowdStrikeOpenAPI/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15283

Crowdstrike open api bug fix

---

Tests/scripts/collect_tests/collect_tests.py
Tests/scripts/collect_tests/utils.py

self._tests was [none if missing](https://code.pan.run/xsoar/content/-/jobs/15412043#L3327), now it's an empty tuple

TestCollection: fix default value

---

Tests/scripts/collect_tests/collect_tests.py
Tests/scripts/collect_tests/id_set.py

- added default `.get` value to avoid cases where the get result would be iterated-on (see [this failure](https://code.pan.run/xsoar/content/-/jobs/15453757#L4152))
- changed some warning to use a string instead str(Path) in `IdSetItem`s

TestCollect: fixed another default value

---

Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.py
Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect.yml
Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test.py
Packs/FeedThreatConnect/Integrations/FeedThreatConnect/FeedThreatConnect_test/parsed_indicator.json
Packs/FeedThreatConnect/ReleaseNotes/1_0_2.md
Packs/FeedThreatConnect/pack_metadata.json

The max value for the DBot Score Convertion has changed from 500 to 1000. I have applied the appropriate changes above as well as updated the link to the ThreatConnect documentation.
Link to documentation: https://training.threatconnect.com/learn/article/threatassess-and-cal-kb-article
To resolve an error in the conversion process preventing the integration from producing accurate DBot scoring.

Update DBot Score Conversion.

---

Tests/scripts/collect_tests/collect_tests.py
Tests/scripts/collect_tests/id_set.py
Tests/scripts/collect_tests/utils.py

`no test` and `no tests` are [equivalent](https://github.com/demisto/content/blob/e883512ae8fa8990f6a0928352263abdd56e89fe/Packs/AWS-GuardDuty/Integrations/AWSGuardDuty/AWSGuardDuty.yml#L1286), now searching for the first.

TestCollect: search for `no test` instead of `no tests`

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/ReleaseNotes/2_4_6.md
Packs/SplunkPy/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14577
if error occurred when run enrichment for fetched notables - ignore exception in order to create the fetched notables as regular incident

SplunkPy: raising exception only if no incident to create

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/2_4_6.md
Packs/SplunkPy/ReleaseNotes/2_4_7.md
Packs/SplunkPy/pack_metadata.json

New docker image with 1.6.4 splunk-sdk version, due to a problem in splunk-sdk 1.7.0 version.

New docker image for Splunk (Splunk-sdk version 1.7.0 -> 1.6.4)

---

Packs/AnsibleLinux/Integrations/AnsibleLinux/AnsibleLinux.yml
Packs/AnsibleLinux/ReleaseNotes/1_0_5.md
Packs/AnsibleLinux/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14132
default search_path cause issue to customer if no search_path is specified
remove it as this default is already are the default by Ansible
see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html#parameter-search_paths

AnsibleLinux: remove the default search_path

---

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2_test.py
Packs/Elasticsearch/ReleaseNotes/1_2_15.md
Packs/Elasticsearch/pack_metadata.json

fixes: [CIAC-3814](https://jira-hq.paloaltonetworks.local/browse/CIAC-3814)
Added the advanced feature fetch-history to the fetch-incident command in Elasticsearch v2 integration.

[Elasticsearch v2] - Added fetch history

---

Tests/scripts/collect_tests/collect_tests.py
Tests/scripts/collect_tests/path_manager.py
Tests/scripts/collect_tests/test_collect_tests.py

- fixed a bug where incorrect files were gathered in `git diff`
- renamed `options` to args for readability
- added logs
- using gitpython `Repo` objects instead of raw git commands

TestCollect: log args, use branch correctly

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/Integrations/JiraV2/JiraV2_test.py
Packs/Jira/ReleaseNotes/2_0_9.md
Packs/Jira/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-14620
When mirror out mapper contain mapping for `incident status` the value in `delta` obj for this are empty 
while the data in the `data` obj are correct
server issue 
but as we can solve it via integration code - this PR contain the fix
@yaakovi need to open ticket for Server team?

JiraV2: use the data value instead delta for mirroring 

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/2_4_9.md
Packs/SplunkPy/pack_metadata.json
Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.py
Packs/SplunkPyPreRelease/Integrations/SplunkPyPreRelease/SplunkPyPreRelease.yml
Packs/SplunkPyPreRelease/ReleaseNotes/1_0_13.md
Packs/SplunkPyPreRelease/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15601
fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15603
When using `basic=true` in the Splunk connection - the token stored in are wrong 
we shouldn't use it in this case in the command like `splunk-notable-event-edit`

Fix Splunk auth issue

---

Packs/MapPattern/ReleaseNotes/1_0_6.md
Packs/MapPattern/Scripts/MapPattern/MapPattern.py
Packs/MapPattern/Scripts/MapPattern/MapPattern.yml
Packs/MapPattern/Scripts/MapPattern/MapPattern_test.py
Packs/MapPattern/Scripts/MapPattern/README.md
Packs/MapPattern/Scripts/MapPattern/test_data/test-1.json
Packs/MapPattern/pack_metadata.json

N/A
Added the `default_value` parameter to return it when unmatched.

Added the `default_value` parameter to return it when unmatched.

---

Packs/HPEArubaClearPass/.pack-ignore
Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.py
Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/HPEArubaClearPass.yml
Packs/HPEArubaClearPass/Integrations/HPEArubaClearPass/README.md
Packs/HPEArubaClearPass/ReleaseNotes/1_0_13.md
Packs/HPEArubaClearPass/pack_metadata.json

fixes: XSUP-15516
When a limit is not specified, the default is 25. Some customers may require more results.

Added the limit argument to the aruba-clearpass-active-sessions-list command

---

Packs/Base/ReleaseNotes/1_31_17.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

Add missing `bytes` and `Element` return types to `_http_request`.

Add missing return types to BaseClient's `_http_request` method

---

Tests/scripts/utils/get_modified_files_for_testing.py

After this PR in the demisto-sdk (https://github.com/demisto/demisto-sdk/pull/2281), all the content path moved to use pathlib instead of relative paths in string.
However, we still parse relative string in content unit tests.
This PR converts the path from the SDK to the relative path related to content, and fixes the unit test.

CONF_PATH converted to relative path

---

Packs/CarbonBlackProtect/Integrations/CarbonBlackProtect/CarbonBlackProtect.py
Packs/CarbonBlackProtect/ReleaseNotes/1_0_27.md
Packs/CarbonBlackProtect/pack_metadata.json
Tests/conf.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-15430)
Carbon Black Protect have a bug in the API where you need to add certain keys in order to update localApproval key. We were not sure which keys are needed, so I added the following workaround:
before updating the computer, I do a GET request to get the computer fields, then I update the given arguments and send the POST request for updating the computer.
Tried it on the customer's environment and it worked fine.

Carbon Black Protect localApproval update bug fix

---

Tests/scripts/destroy_instances.py

avoid an issue where the logs are being written to and `tar` fails

copy server logs before zipping them

---

poetry.lock
pyproject.toml

Release sdk 1.7.3

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md

Removed backslash from Microsoft teams README

Microsoft teams README remove backslash

---

Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.py
Packs/VirusTotal/Integrations/VirusTotalV3/VirusTotalV3.yml
Packs/VirusTotal/ReleaseNotes/2_4_7.md
Packs/VirusTotal/pack_metadata.json

[VirusTotal] Avoid raise an error scanning a url when TLD is invalid

---

Packs/CommonScripts/ReleaseNotes/1_7_26.md
Packs/CommonScripts/Scripts/ParseEmailFilesV2/ParseEmailFilesV2.yml
Packs/CommonScripts/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-3803)
added support to embed images in eml files.
before:
after:

update docker image of ParseEmailFilesV2 script

---

Packs/rasterize/Integrations/rasterize/rasterize.py
Packs/rasterize/ReleaseNotes/1_2_5.md
Packs/rasterize/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15681
The integration will now fall back on Headless CLI when failing to initialize the Chrome Webdriver.

[rasterize] Add Fallback When Chrome Webdriver fails

---

Tests/scripts/collect_tests/collect_tests.py

tests from conf.json are not collected when `tests: no tests` is mentioned in an integration.

TestCollect: improve logs when `tests: no tests` is mentioned

---

Packs/VirusTotal-Private_API/Integrations/VirusTotal-Private_API/VirusTotal-Private_API.yml
Packs/VirusTotal-Private_API/Playbooks/playbook-File_Enrichment_-_Virus_Total_Private_API.yml
Packs/VirusTotal-Private_API/ReleaseNotes/1_0_16.md
Packs/VirusTotal-Private_API/pack_metadata.json

Deprecation action for the VirusTotal-Private_API. Use Packs/VirusTotal pack instead

[VirusTotal] Deprecate outdated VirusTotal-Private_API

---

Packs/VirusTotal/Integrations/VirusTotal/VirusTotal.yml
Packs/VirusTotal/ReleaseNotes/2_4_8.md
Packs/VirusTotal/pack_metadata.json

Deprecation action for the VirusTotal integration. Use VirusTotalV3 instead.

[VirusTotal] Deprecate outdated VirusTotal V2 integration

---

Tests/scripts/destroy_instances.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3971
instead of save only the server.log - download the entire log zip using the REST API

destroy_instances.py - download the entire server log zip

---

Tests/scripts/destroy_instances.py

solved the issue in https://code.pan.run/xsoar/content/-/jobs/16530536
the verify=false was reverted by mistake

destroy_instance - download sever logs - fix ssl issue 

---

Packs/CommonScripts/ReleaseNotes/1_7_57.md
Packs/CommonScripts/Scripts/IfThenElse/IfThenElse.js
Packs/CommonScripts/Scripts/SetAndHandleEmpty/README.md
Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.py
Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty.yml
Packs/CommonScripts/Scripts/SetAndHandleEmpty/SetAndHandleEmpty_test.py
Packs/CommonScripts/pack_metadata.json

Fixed an issue where "None" is set when `stringify` is `true`.
The condition below returns `not equal` in the current behavior, but it should return `equal`.
Fixed an issue where `an empty string == None` is evaluated as False.
Running `SetAndHandleEmpty` with the parameters below shouldn't set value to the key because the value is empty. But it actually sets `None` to the key in the current behavior.

Fixed issues where None is not evaluated properly.

---

Packs/CommonScripts/ReleaseNotes/1_7_57.md
Packs/CommonScripts/Scripts/SetIfEmpty/README.md
Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.py
Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty_test.py
Packs/CommonScripts/pack_metadata.json

N/A
When default value is None, it's converted to "None" in string, not None.
Without any transformers, `None` value comes with: 
The current behavior of setting default value of None is:
You can see that `None` is converted to "None" in string.
The fixed code comes with:

Fixed an issue where default value of None is converted to "None" in string.

---

Tests/conf.json

The `PAN-OS Create Or Edit Rule Test` test-playbook should not be executed on its own, its  a sub-playbook for the `palo_alto_panorama_test_pb` test-playbook which will soon be updated to be executed without this playbook.
This test fails on nightly because of the following error:
```
There are 9 instances of Panorama, please select one of them by using the instance_name argument in conf.json. The options are.....:
```
it also fails in the gitlab build for any pan-os build ([example](https://code.pan.run/xsoar/content/-/jobs/16638505))

[PAN-OS] - remove "PAN-OS Create Or Edit Rule Test" TP

---

Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.py
Packs/Core/Integrations/CortexCoreIR/CortexCoreIR.yml
Packs/Core/ReleaseNotes/1_3_10.md
Packs/Core/pack_metadata.json

- [  In Progress
Fixed an issue where the indicator value was not shown in the war room when using core-prevalence commands
Before fix:
After fix:
FYI @altmannyarden

Core prevalence human readable fix

---

Packs/OktaOAG/pack_metadata.json
Packs/Tableau/README.md

This PR was created to fix Okta OAG name in XSIAM marketplace.

Fixed OktaOAG pack name

---

Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.py
Packs/TaniumThreatResponse/Integrations/TaniumThreatResponseV2/TaniumThreatResponseV2.yml
Packs/TaniumThreatResponse/ReleaseNotes/2_1_1.md
Packs/TaniumThreatResponse/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-15443)

Tanium threat response connection bug

---

Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.py
Packs/AWS-S3/Integrations/AWS-S3/AWS-S3.yml
Packs/AWS-S3/Integrations/AWS-S3/AWS-S3_test.py
Packs/AWS-S3/Integrations/AWS-S3/README.md
Packs/AWS-S3/ReleaseNotes/1_2_3.md
Packs/AWS-S3/TestPlaybooks/playbook-AWS-S3Test.yml
Packs/AWS-S3/pack_metadata.json

Adds a `aws-s3-get-bucket-encryption` command to the AWS S3 integration.

AWS S3 - Add aws-s3-get-bucket-encryption command

---

Packs/CommonScripts/ReleaseNotes/1_7_22.md

Fixed release notes that weren't written as in our templates and therefore didn't generated correctly in the marketplace.

Fix release notes in CommonScripts version 1.7.22

---

poetry.lock
pyproject.toml

For release SDK 1.7.6

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
Packs/CrowdStrikeFalcon/ReleaseNotes/1_9_5.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-17003)
A session with the customer confirmed that the issue was due to a deprecated endpoint. I opened an [issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-64739) for changing other v1 endpoints that should be deprecated in the future.

Crowdstrike deprecated bug fix

---

.gitlab/ci/bucket-upload.yml

Temporarily fix for Zendesk v2 lint failure.
the issue is probably in some python library that isn’t updated.
Passing UT build: https://code.pan.run/xsoar/content/-/jobs/17253176

Temporarily fix for Zendesk v2 lint failure 

---

Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.py
Packs/AlibabaActionTrail/Integrations/AlibabaActionTrailEventCollector/AlibabaActionTrailEventCollector.yml
Packs/AlibabaActionTrail/ReleaseNotes/1_0_2.md
Packs/AlibabaActionTrail/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4296
The AlibabaGetEvents.get_last_run fails when no events are sent to it, this is why the fetch is failing when there are no new events.

Alibaba fix fetch no events

---

Packs/Slack/Integrations/SlackV3/SlackV3.py
Packs/Slack/ReleaseNotes/3_1_6.md
Packs/Slack/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-15577
In some cases when using a custom script, it's possible to force feed the argument a mall formed list. To reduce customer friction, we now pre-format the argument.

Slack malformed users

---

Packs/OctoxLabs/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4341
OctoxLabs Pack currently shows GitHub username as author instead of the company/product name. This PR changes the username to the company name.

Changed author for OctoxLabs Pack

---

Packs/Campaign/ReleaseNotes/3_2_15.md
Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.py
Packs/Campaign/Scripts/ShowCampaignRecipients/ShowCampaignRecipients.yml
Packs/Campaign/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4189
Fixed an issue with the `ShowCampaignRecipients` script, which showed empty strings (empty recipients) in the human readable.

Fix ShowCampaignRecipients Script

---

Packs/WhereIsTheEgg/pack_metadata.json
Tests/Marketplace/core_packs_list.json

fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-61096)
Remove Where is the Egg pack

remove where is the egg from marketplace

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/Integrations/QRadar_v3/README.md
Packs/QRadar/ReleaseNotes/2_3_2.md
Packs/QRadar/pack_metadata.json

fixes: [XSUP-17968](https://jira-hq.paloaltonetworks.local/browse/XSUP-17968)
Added notes related to the close mirrored XSOAR offenses and user query params - close mirrored XSOAR offenses won't work if user query contains "stats=OPEN".

add close mirrored XSOAR offenses and user query params comment

---

Tests/conf.json

Removed "Delete Context Subplaybook Test" from nightly as this playbook should run as a sub-playbook of another playbook.

removed "Delete Context Subplaybook Test" from nightly

---

Packs/CommonTypes/IndicatorFields/indicatorfield-Rank.json
Packs/CommonTypes/ReleaseNotes/3_3_27.md
Packs/CommonTypes/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4490
Adding a new indicator field to save data from ranking systems

Added "Rank" indicator field

---

Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.py
Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid.yml
Packs/ThreatGrid/Integrations/ThreatGrid/ThreatGrid_test.py
Packs/ThreatGrid/ReleaseNotes/1_2_18.md
Packs/ThreatGrid/TestPlaybooks/playbook-Threat_Grid_Test.yml
Packs/ThreatGrid/pack_metadata.json
Tests/conf.json

Contents in demisto.results is expecting a JSON object but a Bytes object was returned from API call causing the error.
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/XSUP-17652)

Threat grid artifacts bug fix

---

Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2.yml
Packs/CommonPlaybooks/Playbooks/playbook-File_Enrichment_-_Generic_v2_README.md
Packs/CommonPlaybooks/ReleaseNotes/2_3_9.md
Packs/CommonPlaybooks/pack_metadata.json
Tests/conf.json

Removed vt step from file enrichment - generic v2 as it's a deprecated playbook.
Also added vt3 instance to replace the vt instance for file enrichment generic v2.

Fix file enrichment v2

---

Tests/conf.json

After consulting @idovandijk, we decided to remove VT configurations from **URL Enrichment - Generic v2 - Test** configurations in conf.json as the integration is deprecated.
we also decided to create a new ticket in Jira to find a proper replacement for the vt task.

remove file enrichment configurations from conf.json

---

Packs/CaseManagement-Generic/ReleaseNotes/1_3_1.md
Packs/CaseManagement-Generic/Reports/report-CaseReport.json
Packs/CaseManagement-Generic/pack_metadata.json
Packs/CommonReports/ReleaseNotes/1_0_2.md
Packs/CommonReports/Reports/report-MTTRbyIncidentType2Quar.json
Packs/CommonReports/Reports/report-MTTRbyOwner2Quar.json
Packs/CommonReports/Reports/report-ShiftSummary.json
Packs/CommonReports/Reports/report-csv-dailyIncidentReport.json
Packs/CommonReports/Reports/report-docx-investigationSummaryReport.json
Packs/CommonReports/Reports/report-investigationSummaryReport.json
Packs/CommonReports/Reports/report-lateIncidentsReport.json
Packs/CommonReports/pack_metadata.json

Related PR: https://github.com/demisto/sane-reports/pull/230
The fix also requires latest sane-reports (at least 1.31.30) pack and the latest client
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CRTX-64873)

CRTX-64873: Display current date instead of N/A in generated reports

---

Packs/DefaultPlaybook/Playbooks/Default_8_0.yml
Packs/DefaultPlaybook/ReleaseNotes/1_1_1.md
Packs/DefaultPlaybook/pack_metadata.json

Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-67675
A new version of the Default playbook was released starting in XSOAR 8.0.0.
However, that playbook conformed to the standard of setting the playbook ID the same as the Name. This caused issues due to server dependencies on the older ID.
Therefore we have to revert it.
@itayronen @shaniacht1 fyi

Reverted the ID of the Default playbook back to playbook0

---

Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.py
Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.yml
Packs/Maltiverse/Integrations/Maltiverse/README.md
Packs/Maltiverse/Integrations/Maltiverse/test_data/response_constants.py
Packs/Maltiverse/Integrations/Maltiverse/test_data/result_constants.py
Packs/Maltiverse/ReleaseNotes/1_0_20.json
Packs/Maltiverse/ReleaseNotes/1_0_20.md
Packs/Maltiverse/pack_metadata.json

The domain command is not returning the resolvedIP anymore in the new API version 1.1
Removed the outputs

Maltiverse fix bc

---

Packs/FiltersAndTransformers/ReleaseNotes/1_1_2.md
Packs/FiltersAndTransformers/Scripts/TimeComponents/TimeComponents.py
Packs/FiltersAndTransformers/pack_metadata.json

N/A
Some code improvement for time formatters

Improved some time formatting codes

---

Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/2_5_0.md
Packs/ServiceNow/pack_metadata.json

Added a new command argument to servicenow-generic-api-call and modified the the generic_api_call_command function to handle the new argument. Sane default value and functionality ensures backwards compatibility.
Enable seding non-JSON formatted data in servicenow-generic-api-call

Enable sending non-JSON formatted data in generic api requests

---

Packs/EWS/Integrations/EWSO365/EWSO365.py
Packs/EWS/Integrations/EWSO365/EWSO365_test.py
Packs/EWS/ReleaseNotes/2_0_1.md
Packs/EWS/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18854
When customer have both - the old `client_secret` and the new `credentials` configured, we should take the new and ignore the old
as the old may be expired and user don't have the simple option to remove it
@MLainer1 FYI :)
failed pytest without fix:
succeeded pytest after fix:

EWSO365: use the new credentials first

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_3_10.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks_test.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/README.md
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

Reverted some of the code that was removed [here](https://github.com/demisto/content/pull/21630). In case the user is using RestAPI in MT env, we should get the tenant name. CS also tested this version and confirmed it was working as expected.

GetFailedTasks get tenant name fix

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/Integrations/UrlScan/UrlScan.yml
Packs/UrlScan/Integrations/UrlScan/UrlScan_test.py
Packs/UrlScan/Integrations/UrlScan/test_data/capitalne.json
Packs/UrlScan/ReleaseNotes/1_2_4.md
Packs/UrlScan/pack_metadata.json

Make the URLScan Integration add the content of hrefs in the HTML of the scanned site to the playbook context when running the "url" automation

Include hrefs provided by API in formatted results

---

Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_AWS.yml
Packs/AWS-Enrichment-Remediation/Playbooks/playbook-Cloud_Response_-_AWS_README.md
Packs/AWS-Enrichment-Remediation/ReleaseNotes/1_0_2.md
Packs/AWS-Enrichment-Remediation/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-69741?filter=-2
This playbook provides response actions to AWS and not Azure as mentioned in the playbook description on YML and README files.

Fixed the description of "playbook-Cloud_Response_-_AWS" playbook.

---

Tests/Marketplace/search_and_uninstall_pack.py

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4814
The uninstall failed on timeout after nightly that installed too much packs.

upgraded sleep time when unistalling packs

---

Packs/CheckPointSandBlast/Integrations/CheckPointSandBlast/CheckPointSandBlast.yml
Packs/CheckPointSandBlast/ReleaseNotes/1_0_3.md
Packs/CheckPointSandBlast/pack_metadata.json

fixes: XSUP-18979
The argument was set but since it isnt in the yml it gets ignored. Adding as deprecated because we want this param to be hidden; it shouldnt ever be manually set. 
Ideally the query function should have been the one with polling, not upload

Add deprecated file_hash

---

Tests/docker_native_image_config.json

Removing the feed mitre attack integration from ignored images for the native-image-config 8.1 as a fix was merged in this PR: https://github.com/demisto/content/pull/22564

remove mitre-attack from docker native image config

---

Packs/Base/.pack-ignore
Packs/Base/ReleaseNotes/1_31_45.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

OpenSSL version 3 and up will not support Legacy renegotiation. 
Added a flag in SSLAdapter to support it. 

Add support to legacy SSL renegotiation

---

Packs/BPA/Integrations/BPA/BPA_description.md
Packs/BPA/ReleaseNotes/1_2_15.md
Packs/BPA/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-19411
Replace the document link from `https://docs.paloaltonetworks.com/documentation` to `https://docs.paloaltonetworks.com/panorama`
Before he fix:
After the fix:

fix the documentation url in panorama README

---

Packs/CommonPlaybooks/Playbooks/playbook-Command-Line_Analysis.yml
Packs/CommonPlaybooks/ReleaseNotes/2_3_20.md
Packs/CommonPlaybooks/pack_metadata.json
Tests/known_words.txt

Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4855
Fixed an issue where the playbook input was mandatory, which caused the playbook to fail. This behavior was undesired in cases where the playbook was used as a subplaybook, and a commandline input was sometimes not provided.
No

Command-Line Analysis - changed playbook input to optional

---

Packs/Axonius/Integrations/Axonius/Axonius.py
Packs/Axonius/Integrations/Axonius/Axonius.yml
Packs/Axonius/ReleaseNotes/1_0_7.md
Packs/Axonius/ReleaseNotes/1_1_0.json
Packs/Axonius/ReleaseNotes/1_1_0.md
Packs/Axonius/pack_metadata.json

Modifying the integration to support pulling an api-key and api-secret from credentials. Bumping the docker version to use our latest api client.
- [x ] Ready
N/A
Modifying the integration to support pulling an api-key and api-secret from credentials.
Bumping the docker version to use our latest api client.
N/A
- [x ] Yes
- Further details: Original fields being used for api-key and api-secret were removed in favor of using a single field to support credentials.

Adding credential support.

---

Tests/Marketplace/marketplace_services.py

fixes: [link to the issue](https://github.com/demisto/content/pull/23014)
The previous PR add the Data Source tag with a prefix marketplacev2:.
We only need the Data Source tag, without the prefix.

remove the prefix of marketplacev2: from the tag

---

Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.py
Packs/CrowdStrikeOpenAPI/Integrations/CrowdStrikeOpenAPI/CrowdStrikeOpenAPI.yml
Packs/CrowdStrikeOpenAPI/ReleaseNotes/1_0_13.md
Packs/CrowdStrikeOpenAPI/pack_metadata.json

Updated cs-devices-ran-on to use the latest API: /devices/entities/devices/v2, as the older API is due to depreciation.

[CrowdStrike OpenAPI] Update cs-devices-ran-on api version

---

Packs/Base/ReleaseNotes/1_31_51.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

when failing to parse a response, include the expected response type, not just `json`

better error when parsing response

---

Packs/Phishing/Playbooks/Phishing_-_Generic_v3.yml
Packs/Phishing/ReleaseNotes/3_3_11.md
Packs/Phishing/pack_metadata.json

Ready
Related to: https://jira-hq.paloaltonetworks.local/browse/CRTX-70287
Changed the task that assigns an analyst to assign a "less-busy-user" instead of the user with the role of Administrator.
No

Changed phishing to assign less-busy-user instead of administrator

---

Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.py
Packs/GuardiCore/Integrations/GuardiCoreV2/GuardiCoreV2.yml
Packs/GuardiCore/Integrations/GuardiCoreV2/README.md
Packs/GuardiCore/ReleaseNotes/2_0_6.md
Packs/GuardiCore/pack_metadata.json

fixes:  https://github.com/demisto/content-docs/issues/1260
https://jira-hq.paloaltonetworks.local/browse/XSUP-12684
Added an example of the URL with the suffix `https://example.com/` => `https://example.com/api/v3.0/`

FuardiCore added an example of the url with the suffix

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.yml
Packs/CrowdStrikeFalcon/ReleaseNotes/1_10_1.md
Packs/CrowdStrikeFalcon/TestPlaybooks/playbook-CrowdStrikeFalcon-Test.yml
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-3986
Fixing the test playbook by changing the value paramter in the command 'cs-falcon-device-count-ioc' to google.com.
There isn't a command to create or get a list with devices.

changing value of cs-falcon-device-count-ioc test playbook command

---

Packs/ML/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CRTX-49601
The ML pack is not supported yet in XSIAM, therefore it is removed from the XSIAM marketplace.

Remove marketplace v2 from ML pack

---

Packs/CommonScripts/ReleaseNotes/1_10_39.md
Packs/CommonScripts/Scripts/ConvertTableToHTML/ConvertTableToHTML.js
Packs/CommonScripts/Scripts/ConvertTableToHTML/ConvertTableToHTML.yml
Packs/CommonScripts/Scripts/ConvertTableToHTML/README.md
Packs/CommonScripts/TestPlaybooks/ConvertTableToHTML_-_TEST.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-4730
added the new argument `context_key` to the `ConvertTableToHTML` script so you can set your own context output key.
default remains `HTMLTable`.

adding `context_key` to the `ConvertTableToHTML` script

---

Packs/DeveloperTools/ReleaseNotes/1_2_30.md
Packs/DeveloperTools/Scripts/WaitAndCompleteTask/WaitAndCompleteTask.yml
Packs/DeveloperTools/pack_metadata.json

In order for nightly to pass after deprecating d2, DeveloperTools should be it's last version in the marketplace-dist bucket (since their dependency was resolved). Because deleting the dependency in pack_metadata.json did not cause a new version, the pack did not update in the marketplace. Therefore any new version of the pack will cause the dependency to be resolved in the marketplace. I updated one of the python dockerimages in the pack in order to complete this.
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4539)

Update DeveloperTools in bucket

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Packs/MicrosoftTeams/ReleaseNotes/1_2_10.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: https://jira-hq.paloaltonetworks.local/browse/XSUP-18583
added a workaround for the problem of not creating a communication when the bot is added to a team.

Teams workaround
