demisto/content

Packs/ShiftManagement-AssignToNextShift/Playbooks/playbook-Assign_Active_Incidents_to_Next_Shift.yml
Packs/ShiftManagement-AssignToNextShift/ReleaseNotes/1_0_1.md
Packs/ShiftManagement-AssignToNextShift/pack_metadata.json

Related: https://github.com/demisto/etc/issues/30564
Playbook: `Assign Active Incidents to Next Shift` had an invalid script id.

Assign Active Incidents to Next Shift: Update proper script id

---

Packs/Cybereason/Integrations/Cybereason/Cybereason.py
Packs/Cybereason/Integrations/Cybereason/Cybereason_test.py
Packs/Cybereason/ReleaseNotes/1_0_5.md
Packs/Cybereason/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30337
improved error handling for authorization failures which raised json decode errors

Cybereason - improve handling for auth failures

---

Packs/ipinfo/Integrations/README.md

fixes: https://github.com/demisto/etc/issues/30702
Added docs for ipinfo integration.

ipinfo docs

---

Tests/conf.json

https://github.com/demisto/etc/issues/30581

skip service now test

---

Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.py
Packs/FeedAzure/Integrations/FeedAzure/FeedAzure.yml
Packs/FeedAzure/ReleaseNotes/1_0_3.md
Packs/FeedAzure/pack_metadata.json

Added support for Azure Service field in indicators

FeedAzure: Added service field in Indicator feed

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26729
Logzio remove from skip.

Logzio remove from skip

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29304

deleted feodo TPB

---

Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
Packs/SymantecMSS/ReleaseNotes/1_0_1.md
Packs/SymantecMSS/pack_metadata.json

fixes:https://github.com/demisto/etc/issues/30649
reverting changes from https://github.com/demisto/content/pull/6068

Symantec MSS - revert to use the pfx_to_pem func

---

Packs/MicrosoftGraphListener/Integrations/MicrosoftGraphListener/MicrosoftGraphListener_description.md
Packs/MicrosoftGraphListener/ReleaseNotes/1_0_10.md
Packs/MicrosoftGraphListener/pack_metadata.json

Fixed detailed description of Microsoft Graph Mail Single user which was wrongly modified in https://github.com/demisto/content/pull/9799/files#diff-d78f8c79150f97d3142e4170ce617372437b1a34bef40f72963fd5ac2bd980a1L1

Microsoft Graph Mail Single User - fix detailed description

---

Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/README.md

PPS README - update required admin role

---

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.yml
Packs/GenericSQL/Integrations/GenericSQL/README.md
Packs/GenericSQL/ReleaseNotes/1_0_8.md
Packs/GenericSQL/pack_metadata.json

fixes: 
Support for empty database name (empty string by default). Useful when using oracle with `service_name`

Generic sql oracle service

---

Packs/IntSight/Integrations/IntSight/IntSight.py
Packs/IntSight/Integrations/IntSight/IntSight.yml
Packs/IntSight/ReleaseNotes/1_0_1.md
Packs/IntSight/pack_metadata.json

https://github.com/demisto/etc/issues/30558
Removed the quotes from the allowed severity values

IntSights - rm double quotes from allowed values

---

Packs/AWS-Athena/.pack-ignore
Packs/Blueliv/.pack-ignore
Packs/MailListener_-_POP3/.pack-ignore
Packs/Telegram/.pack-ignore
Packs/ThreatQ/.pack-ignore
Packs/Traps/.pack-ignore
Packs/TrendMicroDDA/.pack-ignore
Packs/remedy_SR/.pack-ignore

Fixing old beta integration validation failures.
Will be fixed upon next sdk-release

ignoring old beta integration errors

---

Packs/SplunkPy/Integrations/SplunkPy/README.md

fixes: https://github.com/demisto/content-docs/issues/356
Added note about splunk cloud

splunkpy doc: note about splunk cloud

---

Packs/Rundeck/Integrations/Rundeck/Rundeck_test.py

rundeck ut fix

---

Tests/conf.json

it fetches 1m IOCs, so i'm ok with high docker memory. 
fixes: https://github.com/demisto/etc/issues/30931

majestic 250 -> 300

---

Tests/timestamp_replacer.py

https://github.com/demisto/etc/issues/30765
* Implemented logging with format `[%(asctime)s] - [%(funcName)s] - %(message)s'`
* Implemented a method that safely parses a date object, and in case of failure - it logs the problematic value and continue.

Added improvements to timestamp_replacer.py

---

Tests/scripts/infrastructure_tests/release_notes_generator_test.py
Utils/release_notes_generator.py

fixes phrasing from: https://github.com/demisto/content/pull/10130
Changed the phrasing of community-contributed release note title to **Community Contributed**

Change phrasing of community contributed release note title

---

Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.py
Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions.yml
Packs/GoogleCloudFunctions/Integrations/GoogleCloudFunctions/GoogleCloudFunctions_test.py
Packs/GoogleCloudFunctions/ReleaseNotes/1_0_2.md
Packs/GoogleCloudFunctions/pack_metadata.json
Tests/Marketplace/approved_usecases.json

handle the case in which no functions are returned to avoid key error

Google Cloud Functions - handle no funcs found

---

Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
Packs/XMCyber/Playbooks/Endpoint_Enrichment_XM_Cyber.yml
Packs/XMCyber/Playbooks/Endpoint_Enrichment_XM_Cyber_README.md
Packs/XMCyber/Playbooks/IP_Enrichment_XM_Cyber.yml
Packs/XMCyber/README.md
Packs/XMCyber/ReleaseNotes/1_0_1.md
Packs/XMCyber/pack_metadata.json

Small XMCyber fixes
- Further details: Changed the name of a command. As this pack was released today should be ok.

Xmcyber fixes

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27501

unskip panos fw - we got a new urlfiltering lic

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/Integrations/JiraV2/JiraV2_test.py
Packs/Jira/ReleaseNotes/1_2_3.md
Packs/Jira/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30987
modified get remote data func to use `dateparser.parse`
see failing test at https://app.circleci.com/pipelines/github/demisto/content/47032/workflows/7eb76e4f-bf1e-44ee-b61e-7370413eb412/jobs/201612

Jira v2 - improve datetime handling in get remote data

---

Tests/scripts/prepare_content_packs_for_testing.sh

fix prepare content

---

Packs/CommonScripts/ReleaseNotes/1_2_83.md
Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand.py
Packs/CommonScripts/Scripts/RunPollingCommand/RunPollingCommand_test.py
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30996

Added fix for encoding non english strings

---

Tests/conf.json

Increasing timeout for 2 tests that failed on timeout only here https://app.circleci.com/pipelines/github/demisto/content/47983/workflows/7ab7440b-f62a-45ab-a511-5bad8e9a1634/jobs/205589

Increasing timeout for tests

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_8.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30448

GetFailedTasks - handle demisto rest api executeCommand error

---

Packs/CommonScripts/Scripts/SetAndHandleEmpty/.Dockerfile

removing .Dockerfile from SetAndHandleEmpty
fixing lint command failure.

removing .Dockerfile from SetAndHandleEmpty

---

Packs/FireEyeHX/Integrations/FireEyeHX/FireEyeHX.py
Packs/FireEyeHX/ReleaseNotes/1_0_7.md
Packs/FireEyeHX/pack_metadata.json

fixed an issue where there was comparison of string and integer

FireEye HX - cast version to int

---

Packs/Phishing/Playbooks/Phishing_-_Core.yml
Packs/Phishing/ReleaseNotes/1_11_0.md
Packs/Phishing/pack_metadata.json

Ready
fixes: https://github.com/demisto/etc/issues/31037
Updated the email body for the email that gets sent to the user when a conclusion is drawn regarding benign and malicious emails.
5.0.0
No

Updated email body when sending update to the reporting user in Phishing - Core

---

.circleci/config.yml
Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml

adding back BC check in build

---

Packs/Okta/Integrations/Okta_IAM/Okta_IAM.yml
Packs/Okta/ReleaseNotes/2_1_1.md
Packs/Okta/pack_metadata.json

A small update in a parameter and a command argument (allow-enable) default values.

Okta IAM fix

---

.circleci/config.yml
Documentation/common_server_docs.py
Packs/Base/.secrets-ignore
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py

Fixes for Certificate New Class

---

Packs/CortexDataLake/Integrations/CortexDataLake/CortexDataLake.yml

Updates #10114 with new image tag.
Luigi

Bump image tag for #10114

---

Packs/XMatters/README.md

One measly dot. .

---

Packs/XMCyber/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31252
Needed to change support EMail and URL
- [ x] No

XMCyber Pack URL and Email change

---

.circleci/config.yml

fixes: https://github.com/demisto/etc/issues/29258
Triggers now support the new workflows, no need for commit to support instance testing etc.

Cleaning config.yml from unecessery stuff

---

Tests/conf.json

Unmocked integrations that cannot be mocked and increased timeout for integration that failed on nightly.

Unmock integrations with files and increase timeout

---

Tests/conf.json

Changed feed to a lighter one.
fixes: https://github.com/demisto/etc/issues/29859

removed bambenek threshold

---

.circleci/config.yml
Packs/CommonScripts/ReleaseNotes/1_3_0.md
Packs/CommonScripts/Scripts/ConvertDateToUTC/ConvertDateToUTC.py
Packs/CommonScripts/Scripts/ConvertDateToUTC/ConvertDateToUTC.yml
Packs/CommonScripts/Scripts/ConvertDateToUTC/README.md
Packs/CommonScripts/pack_metadata.json

Ready
Related to: https://github.com/demisto/content-premium/pull/8
This script is used in the `IAM - Check If User Should Be Terminated` playbook, in certain scenarios.
5.0.0
No

ConvertDateToUTC Script for ILM pack

---

Tests/conf.json

skipped alienvault OTX

---

Tests/conf.json

Moving integrations to be unmocked.

Unmocking integrations that uses files

---

Packs/FireEyeHX/TestPlaybooks/playbook-FireEyeHX_Test.yml
Packs/RsaNetWitnessPacketsAndLogs/TestPlaybooks/playbook-Test_RSA_PacketsAndLogs.yml

fixes: https://github.com/demisto/etc/issues/31332
fixes: https://github.com/demisto/etc/issues/31333
Changed the following playbooks to be in single branch and thus support the proxy better.
- FireEyeHX Test
- Test RSA Packets And Logs

Making playbooks a single branch

---

Packs/GitHub/Integrations/GitHub_IAM/GitHub_IAM.py
Packs/GitHub/ReleaseNotes/1_1_3.md
Packs/GitHub/pack_metadata.json

fixed an issue where disabling a user caused an error

Github IAM - fixed an issue where disabling a user caused an error

---

Packs/CommonTypes/IncidentFields/incidentfield-applicationid.json
Packs/CommonTypes/IncidentFields/incidentfield-applicationname.json
Packs/CommonTypes/ReleaseNotes/2_6_0.md
Packs/CommonTypes/ReleaseNotes/2_6_0.md~
Packs/CommonTypes/pack_metadata.json

Ready
Related to: https://github.com/demisto/etc/issues/30043
Added the Application Name and Application ID fields to CommonTypes. They will be used in the ILM pack for now.
5.0.0
No

Application fields for ILM (IAM) pack

---

Packs/HatchingTriage/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30921
Update support info

Hatching Triage - support info update

---

.circleci/config.yml

bump 20.12.0

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/31462

Fixed a typo in tpb id in conf.json

---

Packs/ModulesManagement/Scripts/GetInstances/GetInstances.py
Packs/ModulesManagement/Scripts/GetInstances/GetInstances.yml
Packs/ModulesManagement/Scripts/GetInstances/GetInstances_test.py
Packs/ModulesManagement/Scripts/GetInstances/README.md
Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_all_filters.json
Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_brand_filter.json
Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_is_enabled_filter.json
Packs/ModulesManagement/Scripts/GetInstances/test_data/modules_with_system_filter.json
Packs/ModulesManagement/Scripts/GetInstances/test_data/raw_modules.json
Packs/ModulesManagement/pack_metadata.json

contributor request.
the script returns the instances name, brand, state, don't use by default, and category.
also possible filter by the brand (except also an array of brands) and by state (active/ disabled).

New Script GetInstances

---

Packs/CommonScripts/ReleaseNotes/1_3_3.md
Packs/CommonScripts/Scripts/GetDomainDNSDetails/GetDomainDNSDetails.yml
Packs/CommonScripts/Scripts/GetDomainDNSDetails/README.md
Packs/CommonScripts/pack_metadata.json

Fixed output in YML file for `GetDNSDomainDetails` (one output was missing and description was inaccurate)

Output fix in GetDNSDomainDetails

---

Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py
Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon_test.py
Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_9.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31450

CrowdstrikeFalcon - Fixed 404 error message for IOC's 

---

Packs/StarterPack/Scripts/BaseScript/BaseScript.yml

Updated placeholder text

---

Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py

fixes: https://github.com/demisto/etc/issues/31389
fixed the version boundaries of relevant demisto instances using pack metadata
@IkaDemisto FYI

fixed from version boundaries using pack metadata

---

Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-CrowdStrikeFalconDetection.json
Packs/CrowdStrikeFalcon/IncidentTypes/incidenttype-CrowdStrikeFalconIncident.json
Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_10.md
Packs/CrowdStrikeFalcon/pack_metadata.json
Packs/MicrosoftCloudAppSecurity/IncidentTypes/incidenttype-MicrosoftCASAlert.json
Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_12.md
Packs/MicrosoftCloudAppSecurity/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31600
fixes: https://github.com/demisto/etc/issues/31601

Add missing incident types for CrowdStrike Falcon and MCAS

---

.hooks/pre-commit

when picking a commit with `git rebase --interactive` the pre-commit hooks should be skipped.

skip the hooks while git rebase is running

---

Packs/ApiModules/Scripts/CSVFeedApiModule/CSVFeedApiModule.py
Packs/FeedAlienVault/ReleaseNotes/1_0_8.md
Packs/FeedAlienVault/pack_metadata.json
Packs/FeedBambenekConsulting/ReleaseNotes/1_0_5.md
Packs/FeedBambenekConsulting/pack_metadata.json
Packs/FeedCSV/ReleaseNotes/1_0_6.md
Packs/FeedCSV/pack_metadata.json
Packs/FeedMajesticMillion/ReleaseNotes/1_0_1.md
Packs/FeedMajesticMillion/pack_metadata.json
Packs/Feedsslabusech/ReleaseNotes/1_0_5.md
Packs/Feedsslabusech/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31595

CSV Feed API Module - improve condition for credentials provided

---

Packs/CommonTypes/IncidentFields/incidentfield-IncomingMirrorError.json
Packs/CommonTypes/IncidentFields/incidentfield-OutgoingMirrorError.json
Packs/CommonTypes/ReleaseNotes/2_6_1.md
Packs/CommonTypes/pack_metadata.json

rm mirror error fields from the close form

---

Packs/Infoblox/TestPlaybooks/playbook-Infoblox_Test.yml

Making infoblox playbook a single branch to support proxy

Making infoblox playbook a single branch to support proxy

---

Tests/Marketplace/Tests/prepare_private_id_set_for_merge_test.py
Tests/Marketplace/prepare_private_id_set_for_merge.py

Prepare private ID set for merge - script.

Prepare private ID set for merge - script

---

Packs/Remedy-On-Demand/Integrations/integration-Remedy-On-Demand_README.md

migrated missed doc - https://support.demisto.com/hc/en-us/articles/360017594793-BMC-Remedy-OnDemand

Remedy On Demand README

---

Packs/EWS/TestPlaybooks/playbook-EWS_Public_Folders_Test.yml
Packs/cisco-ise/TestPlaybooks/playbook-cisco-ise-test-playbook.yml

Single branch playbook

---

.circleci/config.yml
Tests/Marketplace/configure_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Tests/instance_notifier.py
Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/infrastructure_tests/test_collect_tests_and_content_packs.py
Tests/scripts/infrastructure_tests/tests_data/mock_id_set.json

https://github.com/demisto/etc/issues/31443
Replacing server names with numeric values
https://github.com/demisto/content-test-conf/pull/1055

Replacing server names with numeric values

---

Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md

fixes: https://github.com/demisto/content-docs/issues/402

TrendMicro Apex - update trend micro apex central version

---

Tests/scripts/utils/log_util.py
Tests/test_content.py

The threads in `test_content.py` file are only used in nightly build.
That means that in regular commit - we can log in real time.

In case of non nightly build - logs can be executed in real time

---

dev-requirements-py3.txt

sdk release

---

Packs/TrendMicroApex/Integrations/TrendMicroApex/README.md

Trend Micro Apex - add hotfix to version

---

Packs/NozomiNetworks/pack_metadata.json

Nozomi - set support level to partner and certify

---

Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.py
Packs/Barracuda/Integrations/BarracudaReputationBlockListBRBL/BarracudaReputationBlockListBRBL.yml
Packs/Barracuda/ReleaseNotes/1_0_1.md
Packs/Barracuda/pack_metadata.json

Barracude indicator

---

Packs/Spamcop/Integrations/Spamcop/Spamcop.py
Packs/Spamcop/Integrations/Spamcop/Spamcop.yml
Packs/Spamcop/ReleaseNotes/1_0_1.md
Packs/Spamcop/pack_metadata.json

spamcop ip cmd, indicaotr and outputs

---

Packs/Synapse/Integrations/Synapse/Synapse.py
Packs/Synapse/Integrations/Synapse/Synapse.yml
Packs/Synapse/ReleaseNotes/1_0_1.md
Packs/Synapse/pack_metadata.json

…ed to return multiple entries
- yes, for custom scripts using it.

Synapse - Breaking Change ip, url, domain and file commands multiple indicator and outputs

---

Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2.py
Packs/PhishTank/Integrations/PhishTankV2/PhishTankV2_test.py
Packs/PhishTank/ReleaseNotes/2_0_2.md
Packs/PhishTank/pack_metadata.json

- for custom scripts using the url cmd.

PhishTank v2 url cmd multiple commandresults

---

Packs/Base/ReleaseNotes/1_5_1.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31748
Added handling to an empty list for dictionaries containing empty lists as values

Created failing ut

---

Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_test.py
Packs/XMCyber/ReleaseNotes/1_0_2.md
Packs/XMCyber/pack_metadata.json

- yes, for custom scripts using it.

XMCyber Integration - return multiple entries (entry per indicator) instead of a single entry

---

Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
Packs/QRadar/Integrations/QRadar_v2/QRadar_v2_test.py
Packs/QRadar/ReleaseNotes/1_2_4.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31759

QradarV2: added error to test module

---

Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.py
Packs/Infinipoint/Integrations/Infinipoint/Infinipoint.yml
Packs/Infinipoint/ReleaseNotes/1_0_3.md
Packs/Infinipoint/pack_metadata.json

Infinipoint - changed indicators result to indicator result

---

Packs/Tripwire/Integrations/Tripwire/Tripwire.yml
Packs/Tripwire/ReleaseNotes/1_0_1.md
Packs/Tripwire/pack_metadata.json

tripwire - fixed start arg

---

Packs/CommonScripts/ReleaseNotes/1_3_5.md
Packs/CommonScripts/Scripts/RepopulateFiles/Pipfile
Packs/CommonScripts/Scripts/RepopulateFiles/Pipfile.lock
Packs/CommonScripts/Scripts/RepopulateFiles/RepopulateFiles.py
Packs/CommonScripts/Scripts/RepopulateFiles/RepopulateFiles_test.py
Packs/CommonScripts/pack_metadata.json

Fix populatefiles none iterate

---

Packs/CommonTypes/IndicatorTypes/reputation-file.json
Packs/CommonTypes/ReleaseNotes/2_7_1.md
Packs/CommonTypes/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31797

File Indicator -  fix file layout id

---

Tests/conf.json

skip fe feed

---

Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.py
Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2.yml
Packs/TruSTAR/Integrations/TruSTAR_V2/TruSTAR_V2_test.py
Packs/TruSTAR/ReleaseNotes/2_1_1.md
Packs/TruSTAR/pack_metadata.json

- yes, for custom scripts using it.

TruStar v2 - split indicators creation to multiple entries

---

Tests/scripts/prepare_content_packs_for_testing.sh
Tests/scripts/prepare_private_content_packs_for_testing.sh

fixes: https://github.com/demisto/etc/issues/27616

add update rate config print to the build

---

Packs/Base/ReleaseNotes/1_5_3.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31917
set the demisto handler logger to be int logger

Debug Logger - add demisto formatter to rm sensitive url query params

---

Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection.yml
Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/README.md
Packs/ProofpointServerProtection/ReleaseNotes/1_0_5.md
Packs/ProofpointServerProtection/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31913

Proofpoint Protection Server - improve email id arg desc

---

Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook.yml
Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_0_2.md
Packs/MajorBreachesInvestigationandResponse/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31940
Updated playbook version to 5.5.

Updated SolarStorm / Sunburst playbook version

---

Tests/mock_server.py
Tests/scripts/upload_mocks.sh
Tests/test_content.py

fixes: https://github.com/demisto/etc/issues/31878
* in case non master branch build - don't update the repo
* In case of master branch build - if it's a record run - reset the repo before the test and commit the changes after the test and only in the end of all tests - push and update the repo

Commiting proxy changes after successful test

---

Packs/X509Certificate/TestPlaybooks/playbook-X509Certificate_Test_Playbook.yml

fixes: https://github.com/demisto/etc/issues/31968
added a 30 seconds sleep step before querying for the indicators

X509Certificate TPB fix

---

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2_description.md
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_2_2.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31965
Improved integration description

WildFire - improved integration description

---

Packs/SplunkPy/pack_metadata.json

Splunk - rename Splunk pack name to Splunk

---

Packs/Base/ReleaseNotes/1_5_5.md
Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
Packs/Base/pack_metadata.json

Bump sane pdf report

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26851
Archer v1 is deprecated, no need to run tests on it

Archer v1 is deprecated, no need to run tests on it

---

Packs/Lastline/README.md

fixes: https://github.com/demisto/etc/issues/30269
Added pack documentation

Lastline pack documentation

---

Packs/CommonPlaybooks/Playbooks/playbook-CVE_Enrichment_-_Generic_v2.yml
Packs/CommonPlaybooks/Playbooks/playbook-Search_Endpoint_by_CVE_-_Generic.yml
Packs/CommonPlaybooks/ReleaseNotes/1_8_7.md
Packs/CommonPlaybooks/pack_metadata.json
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook.yml
Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_1_0.md
Packs/MajorBreachesInvestigationandResponse/pack_metadata.json

Expanded IOC coverage for SolarStorm and SUNBURST:
1. Added git sources
2. Added CVE support 
3. Added IOC STIX file
4. XDR related incident search.

Rapid Breach Response pack - Expanded IOC coverage

---

Packs/StarterPack/Integrations/BaseIntegration/README.md

Updated instructional text

---

Packs/StarterPack/Scripts/BaseScript/README.md

Updated instruction text

---

Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration_description.md

Added line of instruction for users

---

Packs/QueryAI/Integrations/QueryAI/QueryAI.py
Packs/QueryAI/Integrations/QueryAI/QueryAI.yml
Packs/QueryAI/Integrations/QueryAI/QueryAI_description.md
Packs/QueryAI/Integrations/QueryAI/QueryAI_test.py
Packs/QueryAI/Integrations/QueryAI/README.md
Packs/QueryAI/ReleaseNotes/1_0_4.md
Packs/QueryAI/pack_metadata.json

Changed Query.AI authentication to API token
Changed Query.AI authentication to API token instead of email/password.

query-ai-3526: Changed Query.AI authentication to API token

---

Tests/test_integration.py
dev-requirements-py3.txt

fixes: https://github.com/demisto/etc/issues/28654
New version of demisto-py doesn't log auth headers

Bumping Demisto-py

---

Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
Packs/StarterPack/Scripts/BaseScript/BaseScript.yml

[Boilerplate PR] bumped dockerimage to latest build

---

Packs/BitDam/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32020
BitDam `partner` -> `community`

Move BitDam to Community Support

---

Packs/SandBlastAppliance/pack_metadata.json
Packs/Sandblast/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32035
Added `checkpoint` keyword to the CheckPoint packs

Add checkpoint keyword to CheckPoint packs

---

Packs/IntegrationsAndIncidentsHealthCheck/README.md
Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_9.md
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

https://github.com/demisto/etc/issues/29954
https://github.com/demisto/content-docs/pull/384
Added to the pack readme the new article reference.

Health Check | Added reference for the new pack article

---

dev-requirements-py3.txt

Changed requirements - revert it.

Revert dev-requirements-py3.txt

---

Packs/Symantec_Advanced_Threat_Protection/Integrations/integration-Symantec_Advanced_Threat_Protection.yml
Packs/Symantec_Advanced_Threat_Protection/README.md
Packs/Symantec_Advanced_Threat_Protection/ReleaseNotes/1_2_0.md
Packs/Symantec_Advanced_Threat_Protection/pack_metadata.json

N/A
Fixed an issue which to get an error  that is `p is not defined`.
Added a query parameter for fetching incidents.

Symantec ATP - Fixed an issue with incidents unable to fetch

---

Packs/X509Certificate/ReleaseNotes/1_0_1.md
Packs/X509Certificate/Scripts/CertificateExtract/CertificateExtract.py
Packs/X509Certificate/pack_metadata.json

https://github.com/demisto/etc/issues/29016

CertificateExtract - Split indicators in to multi indicator command results

---

Packs/NonSupported/pack_metadata.json

Changed the support type to xsoar according to validation.

Changed support type to xsoar in NonSupported pack

---

Tests/conf.json

Related: https://github.com/demisto/etc/issues/20111#
urlscan_malicious_Test remove from skip.

urlscan_malicious_Test remove from skip

---

Packs/Lacework/Integrations/Lacework/Lacework.py
Packs/Lacework/Integrations/Lacework/Lacework.yml
Packs/Lacework/Integrations/Lacework/README.md
Packs/Lacework/ReleaseNotes/1_0_2.md
Packs/Lacework/pack_metadata.json

~~In Hold - Depends on https://github.com/demisto/dockerfiles/pull/3416~~ @bakatzir - I merged it. Eli - You can review.
This commit adds the ability to filter returned compliance data via command rather than in a playbook.

Added Recommendation ID filtering to Compliance data.

---

Packs/Twinwave/Integrations/Twinwave/Twinwave.py
Packs/Twinwave/Integrations/Twinwave/Twinwave.yml
Packs/Twinwave/ReleaseNotes/1_0_1.md
Packs/Twinwave/pack_metadata.json

https://github.com/demisto/etc/issues/29016

Twinwave -  indicators into indicator

---

Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2_test.py
Packs/ExpanseV2/ReleaseNotes/1_0_1.md
Packs/ExpanseV2/pack_metadata.json

https://github.com/demisto/etc/issues/29016

ExpanseV2 - changed indicator to multi indicator

---

Packs/EmailCommunication/ReleaseNotes/1_3_4.md
Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.py
Packs/EmailCommunication/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32024
Cherry picked @omercnet fixes related to [this issue](https://github.com/demisto/etc/issues/32024),  from [this PR](https://github.com/demisto/content/pull/10529)

A fix by Omer

---

Tests/conf.json

Skipping infoblox
related issue: https://github.com/demisto/etc/issues/25651
Seems to fail for instance stability issues

Skipping infoblox

---

Tests/conf.json

https://github.com/demisto/etc/issues/20111
Skipping urlscan until it's resolved

Skipping urlscan

---

Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2_description.md
Packs/AzureCompute/ReleaseNotes/1_0_4.md
Packs/AzureCompute/pack_metadata.json
Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2_description.md
Packs/AzureSecurityCenter/ReleaseNotes/1_1_5.md
Packs/AzureSecurityCenter/pack_metadata.json
Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/MicrosoftDefenderAdvancedThreatProtection_description.md
Packs/MicrosoftDefenderAdvancedThreatProtection/ReleaseNotes/1_2_8.md
Packs/MicrosoftDefenderAdvancedThreatProtection/pack_metadata.json
Packs/MicrosoftGraphCalendar/Integrations/MicrosoftGraphCalendar/MicrosoftGraphCalendar_description.md
Packs/MicrosoftGraphCalendar/ReleaseNotes/1_0_5.md
Packs/MicrosoftGraphCalendar/pack_metadata.json
Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/MicrosoftGraphDeviceManagement_description.md
Packs/MicrosoftGraphDeviceManagement/ReleaseNotes/1_0_5.md
Packs/MicrosoftGraphDeviceManagement/pack_metadata.json
Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/MicrosoftGraphFiles_description.md
Packs/MicrosoftGraphFiles/ReleaseNotes/1_0_4.md
Packs/MicrosoftGraphFiles/pack_metadata.json
Packs/MicrosoftGraphGroups/Integrations/MicrosoftGraphGroups/MicrosoftGraphGroups_description.md
Packs/MicrosoftGraphGroups/ReleaseNotes/1_0_4.md
Packs/MicrosoftGraphGroups/pack_metadata.json
Packs/MicrosoftGraphSecurity/Integrations/MicrosoftGraphSecurity/MicrosoftGraphSecurity_description.md
Packs/MicrosoftGraphSecurity/ReleaseNotes/2_0_7.md
Packs/MicrosoftGraphSecurity/pack_metadata.json

added to all microsoft integrations detailed description our standard note about the 2 auth methods
fixes: https://github.com/demisto/etc/issues/31292

Microsoft integrations - add auth methods to detailed description

---

Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement.yml
Packs/WinRM/Integrations/WindowsRemoteManagement/WindowsRemoteManagement_description.md
Packs/WinRM/ReleaseNotes/1_0_1.md
Packs/WinRM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32146

WinRM - set the integration to beta

---

Tests/configure_and_test_integration_instances.py

proxy logs was not indent correctly

Fix indentation for proxy logs

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
Packs/CortexXDR/ReleaseNotes/2_7_1.md
Packs/CortexXDR/pack_metadata.json

fix a typo in an argument name

Fixed typo in arg name

---

Packs/CortexDataLake/Integrations/CortexDataLake/README.md

CDL - fix integration name in the doc

---

Tests/conf.json

Skipping keylight integration as it's credentials are invalid

Skipping keylight as it's credentials are wrong

---

Tests/scripts/destroy_instances.py
Tests/scripts/wait_until_server_ready.py

Login -in to docker to in the server to avoid docker rate limit violation
fixes: https://github.com/demisto/etc/issues/32162

Loggin in to docker in the server

---

Tests/configure_and_test_integration_instances.py

Removing logs of integration params and logging proxy data only.

Removing integration params from logs

---

Packs/Infoblox/Integrations/Infoblox/Infoblox.py
Packs/Infoblox/Integrations/Infoblox/Infoblox.yml
Packs/Infoblox/ReleaseNotes/1_0_2.md
Packs/Infoblox/pack_metadata.json

https://github.com/demisto/etc/issues/25651
The proxy configuration was not used when set to True in the previous configuration

Fixed an issue where setting the proxy configuration to True was ignored

---

Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
Packs/QRadar/ReleaseNotes/1_2_6.md
Packs/QRadar/pack_metadata.json

QRadar v2 - rm fetch param

---

Packs/Traps/Integrations/PaloAltoNetworks_Traps/PaloAltoNetworks_Traps.yml
Packs/Traps/ReleaseNotes/1_0_3.md
Packs/Traps/pack_metadata.json

Traps - rm fetch param

---

Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.py
Packs/SophosCentral/Integrations/SophosCentral/SophosCentral.yml
Packs/SophosCentral/ReleaseNotes/1_0_1.md
Packs/SophosCentral/pack_metadata.json

Sophos central param

---

Packs/CommonScripts/ReleaseNotes/1_3_8.md
Packs/CommonScripts/Scripts/ZipFile/README.md
Packs/CommonScripts/Scripts/ZipFile/ZipFile.py
Packs/CommonScripts/Scripts/ZipFile/ZipFile.yml
Packs/CommonScripts/TestPlaybooks/playbook-ZipFile-Test.yml
Packs/CommonScripts/pack_metadata.json

related to: https://github.com/demisto/etc/issues/30036
Added the option to pass a list of entryIDs and zip them together.

ZipFile: Added support for multiple file zips

---

Packs/Kenna/Integrations/KennaV2/KennaV2.yml
Packs/Kenna/ReleaseNotes/1_0_4.md
Packs/Kenna/pack_metadata.json

rm unneccessery arg of an old command

---

.circleci/config.yml
Tests/mock_server.py

Cleaning logs from mitmdump data

Cleaning logs

---

Packs/Akamai_WAF/TestPlaybooks/playbook-Akamai_WAF-Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/31900

Akamai WAF Test - set extended and include_elements to false

---

dev-requirements-py3.txt

sdk-1.2.13

---

Packs/JoeSecurity/Integrations/JoeSecurity/JoeSecurity.py
Packs/JoeSecurity/ReleaseNotes/1_0_3.md
Packs/JoeSecurity/TestPlaybooks/playbook-JoeSecurityTest.yml
Packs/JoeSecurity/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32276

JoeSecurity - rm backslashes from filename

---

Packs/Maltiverse/Integrations/Maltiverse/Maltiverse.yml
Packs/Maltiverse/ReleaseNotes/1_0_1.md
Packs/Maltiverse/pack_metadata.json

Maltiverse rm arguments

---

Packs/CloudShare/Integrations/CloudShare/CloudShare.py
Packs/CloudShare/ReleaseNotes/1_0_1.md
Packs/CloudShare/ReleaseNotes/1_0_2.md
Packs/CloudShare/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32128

Cloudshare fixed

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/31900

Akamai WAF - skip test

---

Packs/FeedPublicDNS/Integrations/FeedPublicDNS/FeedPublicDNS.py
Packs/FeedPublicDNS/ReleaseNotes/1_0_2.md
Packs/FeedPublicDNS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32285
Fixed an issue when fetching IP v4 indicators failed.

DNS Feed bug fixes

---

Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
Packs/Uptycs/ReleaseNotes/1_0_3.md
Packs/Uptycs/pack_metadata.json

Uptycs rm argument

---

Tests/scripts/destroy_instances.py
Tests/scripts/wait_until_server_ready.py

fixes: https://github.com/demisto/etc/issues/32162
With [this](https://github.com/demisto/content-test-conf/pull/1082) PR merged - the login to docker will be done using the demisto user

Login to docker on behalf of demisto user

---

Packs/Vertica/Integrations/Vertica/Vertica.py
Packs/Vertica/Integrations/Vertica/Vertica.yml
Packs/Vertica/ReleaseNotes/1_0_1.md
Packs/Vertica/pack_metadata.json

relates: https://github.com/demisto/etc/issues/32208
Fixed the parameter to its correct name in the .py file.

Fixed the 'database' parameter

---

Packs/AutoFocus/Integrations/FeedAutofocus/README.md
Packs/AutoFocus/Integrations/FeedAutofocus/demo_video/AutoFocus_Feed_demo.mp4

For some reason we forgot to migrate this video

Autofocus: readme to use video from content-assets

---

Packs/GitHub/TestPlaybooks/IAM_-_Test_Playbook_Github.yml
Packs/GitHub/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32362
Changing the user-profile input from github user profile to generic user profile.
We had an issue with the nightly and the dependency with IAM-SCIM.

Github IAM - IAM test playbook

---

Packs/Okta/Integrations/Okta_v2/Okta_v2.yml
Packs/Okta/ReleaseNotes/2_1_3.md
Packs/Okta/pack_metadata.json

relates: demisto/etc#32208
- *Breaking changes* - Fixed a typo in the **postalAddress** argument name in the ***okta-update-user*** command.

Oktav2 - Unimplemented argument fix

---

Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/README.md
Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.py
Packs/PaloAltoNetworks_Threat_Vault/Integrations/Threat_Vault/Threat_Vault.yml
Packs/PaloAltoNetworks_Threat_Vault/ReleaseNotes/1_0_2.md
Packs/PaloAltoNetworks_Threat_Vault/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30930

Threat Vault - Handle errors gracefully, add outputs

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/ReleaseNotes/1_0_7.md
Packs/UrlScan/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/31551
fixes: https://github.com/demisto/etc/issues/20111
API-KEY was not added to GET requests which caused the rate limit quota violation

Added api key to get requests to avoid rate limit violation

---

Tests/Marketplace/approved_usecases.json

Added network security use-case

---

Tests/Marketplace/approved_tags.json

New tags for MITRE ATT&CK Courses of Action pack

Added additional tags

---

Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager.py
Packs/BluecatAddressManager/Integrations/BluecatAddressManager/BluecatAddressManager.yml
Packs/BluecatAddressManager/ReleaseNotes/1_0_1.md
Packs/BluecatAddressManager/pack_metadata.json

fixes: demisto/etc#32401
The integration didn't catch all possible exceptions, therefor when a specific exception occurred it was raise from the integration and wasn't passed on to return_error.
Was checked with the new credentials, that are currntly only in centrify.

BluecatAddressManager enhancement- fix exceptions issue

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27239
**The following integrations were skipped due to license expiration:**
- CrowdStrike Falcon Intel v2
- CrowdStrikeMalquery
- CrowdstrikeFalcon

Skip CrowdStrike Integrations

---

Utils/github_workflow_scripts/send_slack_message.py

fixes: https://github.com/demisto/content/runs/1656325251?check_suite_focus=true

Added file format #!/usr/bin/env python3

---

Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
Packs/XMCyber/ReleaseNotes/1_0_3.md
Packs/XMCyber/pack_metadata.json

related to: https://github.com/demisto/etc/issues/32208
fix use of timeId argument

XMCyber timeId argument fix

---

Packs/Cognni/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32502
changed the `Cognni` pack the certified.

change cognni pack to be certified

---

Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/ReleaseNotes/1_3_10.md
Packs/Slack/pack_metadata.json

fixes: https://app.circleci.com/pipelines/github/demisto/content/58585/workflows/e0ef19a4-4de0-4a42-b54f-e6e870116f1f/jobs/244797

slack ignore lines mypy

---

Packs/CarbonBlackProtect/Integrations/CarbonBlackProtect/CarbonBlackProtect.py
Packs/CarbonBlackProtect/Integrations/CarbonBlackProtect/CarbonBlackProtect.yml
Packs/CarbonBlackProtect/ReleaseNotes/1_0_4.md
Packs/CarbonBlackProtect/pack_metadata.json

related to: https://github.com/demisto/etc/issues/32208
parameter wasn't used properly  

Carbon Black Protectmax_incidents_per_fetch fix

---

Packs/BmcHelixRemedyForce/.pack-ignore
Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml
Packs/BmcHelixRemedyForce/ReleaseNotes/1_0_3.md
Packs/BmcHelixRemedyForce/Scripts/BMCHelixRemedyforceCreateIncident/BMCHelixRemedyforceCreateIncident.yml
Packs/BmcHelixRemedyForce/Scripts/BMCHelixRemedyforceCreateServiceRequest/BMCHelixRemedyforceCreateServiceRequest.yml
Packs/BmcHelixRemedyForce/pack_metadata.json
Packs/XMCyber/IncidentTypes/XM_Cyber_Security_Score.json
Packs/XMCyber/ReleaseNotes/1_0_4.md
Packs/XMCyber/pack_metadata.json
dev-requirements-py3.txt

fixes: https://github.com/demisto/etc/issues/32536
Called a non existent PB ID - XM Cyber
Failed to update the id_set - BMCHelix
```
Validating Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml as integration [44.65%]
Validating scheme for Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml
id set validations for: Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml
id_set.json: [ID101] - You have failed to update id_set.json with the data of Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/BMCHelixRemedyforce.yml please run `demisto-sdk create-id-set`
```
relates to: https://github.com/demisto/demisto-sdk/pull/1011

XM Cyber - fix wrong default PB, BmcHelixRemedyForce update DO to re create id_set

---

Packs/Cylance_Protect/TestPlaybooks/playbook-Cylance_Protect_v2_Test.yml

Making 'Cylance Protect v2 Test' playbook single branch

---

Packs/CommonScripts/ReleaseNotes/1_3_10.md
Packs/CommonScripts/Scripts/script-FailedInstances.yml
Packs/CommonScripts/TestPlaybooks/playbook-FailedInstances_-_Test.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32532
added the `testmodule` to the excluded instances list.

FailedInstances: added testmodule to excluded instances

---

Tests/scripts/validate.sh

master is broken due to additional validations.

revert validate.sh: fix master build

---

Packs/BitDam/pack_metadata.json
Packs/HatchingTriage/pack_metadata.json
Packs/MobileIronUEM/pack_metadata.json
Packs/Twinwave/pack_metadata.json
Packs/mnemonicMDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32609
updated certification of partner packs

updated certification of partner packs

---

Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/PaloAltoNetworks_IoT_description.md
Packs/PaloAltoNetworks_IoT/Integrations/PaloAltoNetworks_IoT/README.md
Packs/PaloAltoNetworks_IoT/ReleaseNotes/1_0_2.md
Packs/PaloAltoNetworks_IoT/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32523
updated API configuration link

PANW IoT: updated API configuration link

---

Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_test.yml

Making 'Tenable.io test' a single branch

Making 'Tenable.io test' a single branch

---

Packs/AzureWAF/Integrations/AzureWAF/AzureWAF.py
Packs/AzureWAF/ReleaseNotes/1_0_1.md
Packs/AzureWAF/pack_metadata.json
Tests/conf.json

Unmocking AzureWAF since it uses changing path params.

Unmocking AzureWAF

---

Packs/Gurucul/Integrations/GuruculGRA/GuruculGRA.yml
Packs/Gurucul/ReleaseNotes/1_0_1.md
Packs/Gurucul/pack_metadata.json

Removed the `(Community Contribution)` from the integration name.

Gurucul - Rename integration

---

Packs/ShiftManagement/ReleaseNotes/1_1_4.md
Packs/ShiftManagement/Scripts/AssignallanalystsOOO/AssignallanalystsOOO.py
Packs/ShiftManagement/Scripts/AssignallanalystsOOO/AssignallanalystsOOO.yml
Packs/ShiftManagement/Scripts/AssignallanalystsOOO/Pipfile
Packs/ShiftManagement/Scripts/AssignallanalystsOOO/Pipfile.lock
Packs/ShiftManagement/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32366
Added the automation `AssignallanalystsOOO` to `ShiftManagement ` pack

ShiftManagement - add AssignallanalystsOOO script

---

Packs/ExportIndicators/Integrations/ExportIndicators/README.md

fixing spelling - XSAOR -- > XSOAR

fix spelling

---

Tests/instance_notifier.py

Importing the updated slack version since the old one is no longer in the requirements.

Import the updated slack version

---

Tests/Marketplace/approved_usecases.json

added IT Services to Approved usecases for use in pack_metadata.json. 

Add IT services to Approved usecases

---

Packs/GitHub/Integrations/GitHub/README.md

GitHub readme fix

---

Packs/ShiftManagement/ReleaseNotes/1_1_4.md
Packs/ShiftManagement/Scripts/TimeToNextShift/Pipfile
Packs/ShiftManagement/Scripts/TimeToNextShift/Pipfile.lock
Packs/ShiftManagement/Scripts/TimeToNextShift/TimeToNextShift.py
Packs/ShiftManagement/Scripts/TimeToNextShift/TimeToNextShift.yml
Packs/ShiftManagement/Widgets/widget-ShiftTimeLeft.json
Packs/ShiftManagement/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32156
Added `TimeToNextShift` script and `ShiftTimeLeft` widget to ShiftManagement pack

ShiftManagement - add TimeToNextShift

---

dev-requirements-py3.txt

Using sdk commit hash without mitmdump output logs.

Using sdk commit hash

---

Packs/StarterPack/README.md

update link to be clickable in XSOAR UI.

StarterPack: clickable link

---

Packs/FreshDesk/Integrations/FreshDesk/FreshDesk.py
Packs/FreshDesk/ReleaseNotes/1_0_2.md
Packs/FreshDesk/pack_metadata.json

related: https://github.com/demisto/etc/issues/32529

using handle_proxy function

---

.circleci/config.yml

fixes: https://github.com/demisto/etc/issues/32703
Skip merging ID set step in contrib.

Skip merge ID set step in contrib

---

Packs/FeedCyrenThreatInDepth/pack_metadata.json

Cyren is a partner, and should be certified.
Currently the pack isn't certified, and this PR will fix it.
@mchasepan FYI

adding certification to Cyren

---

Tests/scripts/utils/collect_helpers.py
Tests/scripts/utils/content_packs_util.py
Tests/scripts/utils/get_modified_files_for_testing.py
Tests/scripts/utils/log_util.py
Tests/scripts/utils/tests/content_packs_util_test.py
Tests/scripts/utils/tests/test_get_modified_files_for_testing.py
dev-requirements-py3.txt

updating pipenv requirements

---

Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/32770
Fixed the issue in which partner packs were occasionally not marked as certified.

fixing certification for partner PRs

---

Packs/CommonPlaybooks/Playbooks/playbook-Detonate_File_-_Generic.yml
Packs/CommonPlaybooks/ReleaseNotes/1_8_9.md
Packs/CommonPlaybooks/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32751
re-added two sub-playbooks, fixed overlapping tasks.
also, fixed a few sub-playbook inputs to use the playbook input instead of the general context

Detonate File - Generic: re-added two sub-playbooks, fixed overlapping tasks

---

Tests/conf.json

Unmocking integrations with unique ID and files.

Unmocking integrations

---

Tests/scripts/validate.sh

validate.sh: fixed condition

---

Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v3_README.md

fixes: https://github.com/demisto/content/pull/10888
Contribution fix typo in `playbook-Dedup_-_Generic_v3_README.md `- `IgnoreClosedIncidents` instead of `IgnoreCloseIncidents`.

Contribution fix typo in playbook-Dedup_-_Generic_v3_README.md

---

Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.py
Packs/CVESearch/Integrations/CVESearchV2/CVESearchV2.yml
Packs/CVESearch/ReleaseNotes/1_0_4.md
Packs/CVESearch/TestPlaybooks/playbook-CVE-Search-Test.yml
Packs/CVESearch/TestPlaybooks/playbook-CveReputation_Test.yml
Packs/CVESearch/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32831
Since the server of the integration is very weak we needed to reduce the size of the response on test-module from 30 to 1.

Reducing response sice for test-module and adding retry

---

Packs/CommonScripts/ReleaseNotes/1_3_12.md
Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
Packs/CommonScripts/Scripts/SetGridField/SetGridField.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32684
Added to the error message the fact that it can be caused by incorrect incident type.

SetGridField - Improved error message 

---

Packs/CommonScripts/Scripts/SetGridField/README.md

fixes: https://github.com/demisto/content-docs/issues/419
Fix wrong commands examples.

Set Grid Field - Fix readme

---

Packs/CommonPlaybooks/Playbooks/playbook-Dedup_-_Generic_v3.yml
Packs/CommonPlaybooks/ReleaseNotes/1_8_10.md
Packs/CommonPlaybooks/pack_metadata.json

related: https://github.com/demisto/content/pull/10887
Update IgnoreCloseIncidents to IgnoreClosedIncidents

Update IgnoreCloseIncidents to IgnoreClosedIncidents

---

Packs/QRadar/Integrations/QRadar_v2/README.md

Reference: https://github.com/demisto/etc/issues/32305
I split troubleshooting into performance and fetch sections.

Adding troubleshooting for docker timeout

---

Packs/LogRhythm/TestPlaybooks/playbook-LogRhythm_Test_Playbook.yml

fix LogRhythm-Test-Playbook

---

Packs/ArcSightESM/Integrations/ArcSightESMv2/ArcSightESMv2.yml
Packs/ArcSightESM/ReleaseNotes/1_0_8.md
Packs/ArcSightESM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32821
fixed the output path according to the code.

ArcSight ESM v2: fixed an output path

---

Packs/MailSenderNew/TestPlaybooks/playbook-Email_Sender_Python.yml

fixes: https://github.com/demisto/etc/issues/25602

mail sender new - fix access to context

---

Tests/scripts/collect_tests_and_content_packs.py
Tests/scripts/utils/get_modified_files_for_testing.py

- Collecting tests for beta integrations too
- Remove all the 'no tests' text from the `filter_file.txt`

Collect tests for beta integrations as well

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27890
Unskipped MS Graph Groups TPB

Unskipped MS Graph Groups TPB

---

Utils/github_workflow_scripts/create_internal_pr.py

Removed automatic assignment of @kirbles19 when creating internal PRs from external contribution PRs.

[Contribution Management] Removed automatic assignment of technical writer

---

Packs/SSLVerifier/Scripts/SSLVerifier/Pipfile
Packs/SSLVerifier/Scripts/SSLVerifier/Pipfile.lock
Packs/SSLVerifier/Scripts/SSLVerifier/SSLVerifier.py
Packs/SSLVerifier/Scripts/SSLVerifier/SSLVerifier.yml
Packs/SSLVerifier/pack_metadata.json

Automation to check for validity of SSL certificates and get the time to expiration.

1st commit of SSLVerifier v2

---

Tests/conf.json

The issue number in conf.json was updated to the correct one

Arcsight logger - fixed issue number in conf.json

---

Packs/EWS/TestPlaybooks/playbook-pyEWS_Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/28339
unskipped the test
remove 2 problematic tasks (they weren't connected cause they were inconsistent)

Unskip py ews test

---

Packs/SymantecMSS/Integrations/SymantecMSS/SymantecMSS.py
Packs/SymantecMSS/ReleaseNotes/1_0_2.md
Packs/SymantecMSS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32766
improved parsing of xml.

Symantec MSS: fixed the xml parsing of responses

---

Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.py
Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ.yml
Packs/ActiveMQ/Integrations/ActiveMQ/ActiveMQ_description.md
Packs/ActiveMQ/ReleaseNotes/1_0_1.md
Packs/ActiveMQ/pack_metadata.json
Tests/conf.json

Removing proxy params because it’s not supported.
related: https://github.com/demisto/etc/issues/32529

remove proxy parameter from ActiveMQ

---

Packs/Salesforce/.pack-ignore

Add salesforce classifiers to ignore

---

Packs/FeedCyrenThreatInDepth/README.md

Cyren - changed url path file

---

Packs/AzureLogAnalytics/TestPlaybooks/NonCircleTests/AzureLogAnalyticsTest.yml
Packs/Box/TestPlaybooks/BoxV2_TestPlaybook.yml
Packs/CheckpointFirewall/TestPlaybooks/checkpoint-testplaybook.yml
Packs/CiscoSpark/TestPlaybooks/playbook-CiscoSpark_Test.yml
Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_File.yml
Packs/CrowdStrikeFalconX/TestPlaybooks/CrowdStrike_Falcon_X_-Test-Detonate_URL.yml
Packs/DomainTools/TestPlaybooks/playbook-DomainTools-Test.yml
Packs/FeedAzureADConnectHealth/TestPlaybooks/FeedAzureADConnectHealth_Test.yml
Packs/FeedCofense/TestPlaybooks/playbook-TestCofenseFeed.yml
Packs/Forcepoint/TestPlaybooks/playbook-Forcepoint_test.yml
Packs/Gurucul/TestPlaybooks/TestGraPlayBook.yml
Packs/HPE_Service_Manager/TestPlaybooks/playbook-TestHPServiceManager.yml
Packs/HelloWorld/TestPlaybooks/playbook-HelloWorld-Test.yml
Packs/McAfeeNSM/TestPlaybooks/playbook-McAfeeNSMTest.yml
Packs/Tenable_sc/TestPlaybooks/playbook-tenable.sc_scan_test.yml
Packs/WootCloud/TestPlaybooks/TestWootCloudPlaybook.yml
Packs/XMCyber/TestPlaybooks/XMCyberIntegration-Test.yml

Change taskid fields and id under task field to be from uuid format and with the same value
on all the invalid test playbooks

Test playbook - update uuid on the relevant task id fields 

---

.circleci/config.yml

bump version

---

Packs/CortexXDR/Layouts/layout-details-Cortex_XDR_Incident.json
Packs/CortexXDR/Layouts/layoutscontainer-Cortex_XDR_Incident.json
Packs/CortexXDR/ReleaseNotes/2_7_9.md
Packs/CortexXDR/pack_metadata.json

cortex XDR remove non existing fields from layouts

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32566
The instance is fixed and the test playbook checked.

RSA NetWitness removing test playbook from skipped

---

Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.py
Packs/Lastline/Integrations/Lastline_v2/Lastline_v2.yml
Packs/Lastline/ReleaseNotes/1_0_5.md
Packs/Lastline/pack_metadata.json

related: https://github.com/demisto/etc/issues/32208
added the logic for *threshold* param.

adding threshold to lastline client

---

Packs/AgariPhishingDefense/Classifiers/classifier-Agari_Phishing_Defense_5_9_9.json
Packs/AgariPhishingDefense/Classifiers/classifier-mapper-incoming-Agari_Phishing_Defense.json
Packs/AgariPhishingDefense/Layouts/layout-details-Agari_Phishing_Defense_Policy_Event.json
Packs/AgariPhishingDefense/Layouts/layoutscontainer-Agari_Phishing_Defense_Policy_Event.json
Packs/AgariPhishingDefense/ReleaseNotes/1_0_1.md
Packs/AgariPhishingDefense/pack_metadata.json
Packs/Orca/Classifiers/classifier-Orca_Mapper.json
Packs/Orca/ReleaseNotes/1_0_1.md
Packs/Orca/pack_metadata.json

Orca and Agari had non-existing incident fields in them.
This issue is now fixed.

Fixed incident fields validation for Orca and Agari

---

Packs/IntegrationsAndIncidentsHealthCheck/Playbooks/playbook-Integrations_and_Playbooks_Health_Check_-_Running_Scripts.yml
Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_10.md
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32951
fixed the order of the keys to match the columns in the call to SetGridField.

Incident Health Check: Fix system health layout

---

Packs/MicrosoftDefenderAdvancedThreatProtection/Integrations/MicrosoftDefenderAdvancedThreatProtection/README.md

fixes: https://github.com/demisto/etc/issues/32697
updated integration docs

MS ATP: updated required permissions in docs

---

Packs/Base/ReleaseNotes/1_7_0.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json
Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_queue_details_return_entry.json
Packs/BmcHelixRemedyForce/Integrations/BmcHelixRemedyForce/TestData/get_user_details_return_entry.json
Packs/Polygon/Integrations/Polygon/test_data/results.json
Packs/SecurityIntelligenceServicesFeed/Integrations/SecurityIntelligenceServicesFeed/SecurityIntelligenceServicesFeed_test.py

* Update CommonServerPython.py
Added the "Note" flag to the "CommandResults" class.
Co-authored-by: bachen <bachen@paloaltonetworks.com>
Added the ability to mark an entry as a note for results of the **CommandResults** function by using the **mark_as_note** flag.

Update CommonServerPython.py (#10873)

---

Packs/Netmiko/Integrations/Netmiko/Netmiko.py

fixes: https://github.com/demisto/etc/issues/33001
Fixes a missing input on a client function.

Added required input to function on line 53

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29592
fixes: https://github.com/demisto/etc/issues/27280
fixes: https://github.com/demisto/etc/issues/26783
fixes: https://github.com/demisto/etc/issues/26784
fixes: https://github.com/demisto/etc/issues/32459
unskipped some tests

unskip some tests

---

Packs/HelloWorld/Integrations/HelloWorld/README.md

Fixed HelloWorld readme formatting.

[Documentation] Fixed HelloWorld readme

---

Packs/CheckPhish/.secrets-ignore
Packs/CheckPhish/TestPlaybooks/playbook-CheckPhish-Test.yml

fixes: https://github.com/demisto/etc/issues/29278
Replaced shaky url in thet PB

Replaced shaky url in the test PB - CheckPhish

---

dev-requirements-py3.txt

update demisto sdk to v1.2.17

---

Tests/conf.json

Unmocking 'Trend Micro Apex - Test' because it generates random ip and file

Unmocking 'Trend Micro Apex - Test' because it generates random ip and file

---

Tests/Marketplace/upload_packs.py
Tests/private_build/upload_packs_private.py

fixes: https://github.com/demisto/etc/issues/32349
https://github.com/demisto/etc/issues/32287
When uploading packs we wish to update the metadata in the index in every upload.

Upload will change metadata in every upload

---

Packs/AutoFocus/TestPlaybooks/playbook-AutoFocus_V2_test.yml

fixes: https://github.com/demisto/etc/issues/26464
Single branching the playbook
Build is failing on an actual playbook issue which is not related to the proxy and is not affected by this PR

Single branching 'AutoFocus V2 test' for proxy porpuses

---

Packs/EWS/Integrations/EWSv2/EWSv2.py
Packs/EWS/ReleaseNotes/1_7_3.md
Packs/EWS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32758
fixes: https://github.com/demisto/etc/issues/33017
added a check if the object has an attribute `split`.

fix EWS split header error

---

Packs/CIRCL/TestPlaybooks/playbook-CIRCL.yml

fixes:  https://github.com/demisto/etc/issues/25600
Updates the TPB to run as a single branch instead of parallel.

Circl TPB - single branch instead of parallel branches.

---

Packs/AcalvioShadowplex/pack_metadata.json

Changes pack name from Acalvio Shadowplex to Acalvio ShadowPlex

Acalvio ShadowPlex - Changed name and description

---

Packs/MicrosoftGraphMail/TestPlaybooks/playbook-MicrosoftGraphMail-Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/24445
FMs Graph Mail TPB - get attachments task fix

MsGraph Mail TPB fix

---

Packs/FeedCyrenThreatInDepth/Classifiers/classifier-Cyren_Threat_InDepth_Indicator_Mapper.json
Packs/FeedCyrenThreatInDepth/Dashboards/dashboard-Cyren_Feeds_Stats_Dashboard.json
Packs/FeedCyrenThreatInDepth/IndicatorFields/indicatorfield-Cyren_Industries.json
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.py
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.yml
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_test.py
Packs/FeedCyrenThreatInDepth/Layouts/layoutscontainer-Cyren_Threat_InDepth_Indicator_Template.json
Packs/FeedCyrenThreatInDepth/README.md
Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_2_0.md
Packs/FeedCyrenThreatInDepth/pack_metadata.json

N/A
* indicator statistics dashboard
* moved custom indicator field mappings from Python integration code to dedicated indicator mapper
* wording improvements in documentation

Cyren ThreatInDepth Base Content Pack v1.2.0

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/Integrations/JiraV2/README.md
Packs/Jira/ReleaseNotes/1_2_9.md
Packs/Jira/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32986
Due to changes in the API due to GDPR - replaced the assignee argument to refer to the user's account ID rather than its name

Jira-Create-Issue-Bug-Fix

---

Packs/Gurucul/Integrations/GuruculGRA/README.md

related: https://github.com/demisto/etc/issues/33031
Fix intro of README

Gurucul: update integration README

---

Packs/Cyberint/TestPlaybooks/playbook-Cyberint_Test.yml

Fix playbook-Cyberint_Test.yml TPB taskID and ID

Fix playbook-Cyberint_Test.yml TPB taskID and ID

---

.circleci/config.yml

https://github.com/demisto/etc/issues/32500
Modifying config.yml in order to implement the ssh tunneling more easily.

Supporting circle's 'commands' feature

---

Packs/QRadar/Integrations/QRadar/QRadar.py
Packs/QRadar/ReleaseNotes/1_2_11.md
Packs/QRadar/pack_metadata.json

switched demisto.log to demisto.info in test module  method

switched demisto.log to demisto.info in test module 

---

Packs/GoogleChronicleBackstory/Integrations/GoogleChronicleBackstory/README.md

chronicle readme - fix borken link

---

Packs/IntSight/Integrations/IntSight/IntSight.py
Packs/IntSight/TestPlaybooks/playbook-IntSights_Test.yml
dev-requirements-py3.txt

Test the comments made by Content-Bot for skipped integrations, after applying the changes to the comment post flow.

Testing Comments for Skipped Integrations - After Changes

---

Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md

fixes: https://github.com/demisto/etc/issues/33040
updated the output examples

MS Cloud App Security: filter README examples

---

Packs/Alexa/Integrations/Alexa/Alexa.py
Packs/Alexa/ReleaseNotes/1_1_1.md
Packs/Alexa/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33107
Fixed score calculation

Alexa - Fixed score calculation

---

Packs/Base/ReleaseNotes/1_7_1.md
Packs/Base/Scripts/SanePdfReport/SanePdfReport.yml
Packs/Base/pack_metadata.json

https://github.com/demisto/etc/issues/33071

update SanePdfReport docker image

---

Packs/MicrosoftGraphDeviceManagement/Integrations/MicrosoftGraphDeviceManagement/README.md

fixes: https://github.com/demisto/etc/issues/32878
Added permissions per command to integration docs

MS intune - update docs with permissions per command

---

Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2.py
Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/ProofpointProtectionServerV2.yml
Packs/ProofpointServerProtection/ReleaseNotes/2_0_1.md
Packs/ProofpointServerProtection/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33086

PPS v2 - fix unsecure param handling

---

Packs/Cyberint/Integrations/Cyberint/Cyberint.py
Packs/Cyberint/Integrations/Cyberint/Cyberint.yml
Packs/Cyberint/Integrations/Cyberint/README.md
Packs/Cyberint/ReleaseNotes/1_0_1.md
Packs/Cyberint/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33076
related: https://github.com/demisto/etc/issues/32855

cyberint - default arg fixes

---

Packs/MicrosoftGraphGroups/TestPlaybooks/MicrosoftGraphGroups-Test.yml

fixes: https://github.com/demisto/etc/issues/27890
Added a verification step before adding a member to a group

MSGraphGroupsTPBFix

---

Packs/CommonScripts/ReleaseNotes/1_3_15.md
Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime.py
Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime.yml
Packs/CommonScripts/Scripts/ModifyDateTime/ModifyDateTime_test.py
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33180
- copied the `tzinfo` from input to output.
- added unit-tests

ModifyDateTime: copied the tzinfo from input to output and added unit-tests

---

Packs/ArcSightLogger/Integrations/integration-ArcSightLogger.yml
Packs/ArcSightLogger/ReleaseNotes/1_0_1.md
Packs/ArcSightLogger/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/32711
Improved documentation of the local_search argument in both relevant commands.

Arcsight Logger - Improved documentation of the local_search argument

---

Packs/Slack/Integrations/Slack_IAM/Slack_IAM_test.py

Fixed failed ut in https://app.circleci.com/pipelines/github/demisto/content/64248/workflows/6a878500-6e05-447c-afed-7ca8c39b162f/jobs/265678/steps
according to https://github.com/demisto/content/pull/10980

Slack IAM ut fix

---

Packs/Skyformation/pack_metadata.json

fixes: https://panw-global.slack.com/archives/G011E63JXPB/p1611831518119000
Bumped the version in metadata file to be the latest rn version.

skyformation metadata version bump

---

Tests/demistomock/demistomock.py

demistomock: add internalHttpRequest with doc string

---

Packs/Phishing/Layouts/layout-details-Phishing.json
Packs/Phishing/Layouts/layoutscontainer-Phishing.json
Packs/Phishing/ReleaseNotes/2_2_0.md
Packs/Phishing/pack_metadata.json

Ready
fixes: https://github.com/demisto/etc/issues/33181
Moved the grid to the bottom and stretched it and adjusted other sections to fit nicely.
No

Improved headers grid visibility in phishing layouts

---

Packs/Base/ReleaseNotes/1_7_4.md
Packs/Base/Scripts/CheckDockerImageAvailable/CheckDockerImageAvailable.py
Packs/Base/TestPlaybooks/playbook-CheckDockerImageAvailableTest.yml
Packs/Base/pack_metadata.json

related: https://github.com/demisto/etc/issues/31801
XSOAR registry support. 

check docker: support xsoar-registry

---

Packs/MinervaLabsAntiEvasionPlatform/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33228
changed pack support to community

Minerva: changed pack support to community

---

Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.py
Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist.yml
Packs/FeedFeodoTracker/ReleaseNotes/1_0_6.md
Packs/FeedFeodoTracker/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33241
The ips might be surrounded with `"` - added this option in the indicator extraction.

Feodo - Fixed regex for indicator extraction

---

Packs/Skyformation/pack_metadata.json
Tests/Marketplace/Tests/marketplace_services_test.py
Tests/Marketplace/copy_and_upload_packs.py
Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/33225
fixes: https://github.com/demisto/etc/issues/33226
- Added the latest version entry to successful packs dict in packs_results.json
- Added hidden = True in Skyformation metadata file
- CCI: https://app.circleci.com/pipelines/github/demisto/content/64583/workflows/a260f777-6975-4fbc-a1c7-010339658080
- Bucket: https://console.cloud.google.com/storage/browser/marketplace-ci-build/content/builds/upload-hidden-bugfix/266708
- Server Configuration: https://storage.googleapis.com/marketplace-ci-build/content/builds/upload-hidden-bugfix/266708

Upload hidden bugfix

---

.circleci/config.yml

Bucket hide command output

---

Packs/Slack/Integrations/Slack_IAM/Slack_IAM.yml
Packs/Slack/ReleaseNotes/1_3_13.md
Packs/Slack/pack_metadata.json

related: https://github.com/demisto/etc/issues/30343
Fix parameters display name in slack IAM.

Fix parameters display name in slack IAM

---

Packs/CommonScripts/ReleaseNotes/1_3_16.md
Packs/CommonScripts/Scripts/SetGridField/SetGridField.py
Packs/CommonScripts/Scripts/SetGridField/SetGridField_test.py
Packs/CommonScripts/pack_metadata.json

in cases where the context pack contained complex values (list / dict) the script failed.

SetGridField: fix unhashable type

---

Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection.yml
Packs/ProofpointServerProtection/Integrations/ProofpointServerProtection/ProofpointServerProtection_description.md
Packs/ProofpointServerProtection/ReleaseNotes/2_0_2.md
Packs/ProofpointServerProtection/pack_metadata.json

Improve the deprecated notice.

proofpoint: improve deprecated notice

---

Packs/FeedCyrenThreatInDepth/.secrets-ignore
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.py
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth.yml
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_description.md
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/CyrenThreatInDepth_test.py
Packs/FeedCyrenThreatInDepth/Integrations/CyrenThreatInDepth/README.md
Packs/FeedCyrenThreatInDepth/ReleaseNotes/1_3_0.md
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.py
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt.yml
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/CyrenThreatInDepthRandomHunt_test.py
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRandomHunt/README.md
Packs/FeedCyrenThreatInDepth/Scripts/CyrenThreatInDepthRelatedWidget/CyrenThreatInDepthRelatedWidget.yml
Packs/FeedCyrenThreatInDepth/pack_metadata.json

N/A
- added a script to create a threat hunting incident from a random Cyren indicator
- removed the configurable API URL from the feed ingestion integration

Cyren ThreatInDepth Base Content Pack v1.3.0

---

Packs/ShiftManagement/Scripts/AssignAnalystToIncidentOOO/README.md
Packs/ShiftManagement/Scripts/AssignToNextShiftOOO/README.md
Packs/ShiftManagement/Scripts/CreateChannelWrapper/README.md
Packs/ShiftManagement/Scripts/GetNumberOfUsersOnCall/README.md
Packs/ShiftManagement/Scripts/GetOnCallHoursPerUser/README.md
Packs/ShiftManagement/Scripts/GetRolesPerShift/README.md
Packs/ShiftManagement/Scripts/GetShiftsPerUser/README.md
Packs/ShiftManagement/Scripts/GetUsersOOO/README.md
Packs/ShiftManagement/Scripts/GetUsersOnCall/README.md
Packs/ShiftManagement/Scripts/ManageOOOusers/README.md
Packs/ShiftManagement/Scripts/OutOfOfficeListCleanup/README.md
Packs/ShiftManagement/Scripts/TimeToNextShift/README.md

fixes: https://github.com/demisto/content/pull/10750
Adding Readme files for the pack automations 

Add Readme files to Shift management 

---

Packs/Base/ReleaseNotes/1_7_6.md
Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.py
Packs/Base/Scripts/GetMLModelEvaluation/GetMLModelEvaluation.yml
Packs/Base/pack_metadata.json
Packs/rasterize/Integrations/rasterize/rasterize.py
Packs/rasterize/Integrations/rasterize/rasterize.yml
Packs/rasterize/ReleaseNotes/1_0_6.md
Packs/rasterize/pack_metadata.json
dev-requirements-py3.txt

rasterize
GetMLModelEvaluation

update DO - trigger lints

---

Packs/Humio/Integrations/Humio/README.md

humio readme: fix broken link

---

Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/README.md

Remove a dead link from being clickable.

rst readme: remove dead link

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.yml
Packs/ServiceNow/ReleaseNotes/2_1_10.md
Packs/ServiceNow/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33167
Added a file handling with the getFilePath method in case the file was not found in the context.

ServiceNow V2 - Added a better file handling

---

Tests/Marketplace/search_and_install_packs.py

fixes: https://panw-global.slack.com/archives/G011E63JXPB/p1612220331171100
Added a patch to not install hidden packs on Upload-Flow

Upload-Flow patch for not installing hidden packs

---

Tests/conf.json

This is no longer true and I'm getting spammed now because of it as `content-bot` keeps commenting it on PRs...

Remove tag from conf.json

---

Packs/Gmail/Integrations/Gmail/Gmail.yml
Packs/Gmail/Integrations/Gmail/README.md
Packs/Gmail/ReleaseNotes/1_1_5.md
Packs/Gmail/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33349
The password should contain the entire service account file and not just the private key inside of it.

Gmail: updated param display

---

Tests/Marketplace/marketplace_services.py
Tests/Marketplace/upload_packs.py

Reverts demisto/content#11238
After the bucket changes are done, reverting them.

Revert "Marketplace upload - reverting updated changes"

---

Tests/conf.json

mocking aws integrations that can be mocked.
And making those that uses read only operations run in parallel.

Mocking AWS integrations

---

Packs/AcalvioShadowplex/.pack-ignore
Packs/BluelivThreatContext/.pack-ignore
Packs/BluelivThreatContext/Integrations/BluelivThreatContext/README.md
Packs/EWS/.pack-ignore
Packs/Pcysys/.pack-ignore
Packs/Tufin/Integrations/Tufin/README.md
Packs/XMatters/.pack-ignore
dev-requirements-py3.txt

fixes validation error for this PR: https://github.com/demisto/demisto-sdk/pull/1077 In README and .pack_ignore

fix validation error RM102, IN136

---

dev-requirements-py3.txt

was wrongfully updated.
relateds to: https://github.com/demisto/content/pull/11257

revert sdk update

---

Packs/Axonius/Integrations/Axonius/Axonius.py
Packs/Axonius/ReleaseNotes/1_0_2.md
Packs/Axonius/pack_metadata.json

fix reference to variable name changed in 4.x

---

dev-requirements-py3.txt

Add ref to SDK branch to fix master

---

dev-requirements-py3.txt

add commit hash to ref sdk

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/ReleaseNotes/1_0_7.md
Packs/EDL/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31888
Improved EDL creation time by increasing the page size to 2000 when populating the EDL.

Improved EDL Creation Time

---

Packs/EmailCommunication/ReleaseNotes/1_3_5.md
Packs/EmailCommunication/Scripts/SendEmailReply/SendEmailReply.yml
Packs/EmailCommunication/pack_metadata.json

Changed the mandatory argument "service_mail" to optional

Email Communication | Changed the mandatory argument "service_mail" to optional

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.yml
Packs/CortexXDR/ReleaseNotes/2_8_4.md
Packs/CortexXDR/pack_metadata.json

Added back mirroring configuration accidentally removed in https://github.com/demisto/content/pull/10627/files#diff-2707e061000ea8be0033e324685f9a60cde07cee318eb83b2764ffd79fd8e8b5L1996

XDR - Added back mirroring configuration accidentally removed

---

Packs/APIVoid/Integrations/APIVoid/APIVoid.py

https://live.paloaltonetworks.com/t5/cortex-xsoar-discussions/service-apivoid-test-fails-with-a-success/m-p/383866/highlight/false#M113
Changes a dictionary fetch to a safer method.
NA

Made test_module dict param check safer

---

Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/CarbonBlackEnterpriseEDR.yml
Packs/CarbonBlackEnterpriseEDR/Integrations/CarbonBlackEnterpriseEDR/README.md
Packs/CarbonBlackEnterpriseEDR/ReleaseNotes/1_1_3.md
Packs/CarbonBlackEnterpriseEDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33308
updated argument description according to API docs.

Carbon Black Enterprise EDR: updated argument description

---

Packs/EWS/Integrations/EWSv2/EWSv2.py
Packs/EWS/ReleaseNotes/1_7_4.md
Packs/EWS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33462
fixed "none isn't iterable" error

fixed none is not iterable error

---

Packs/CommonScripts/ReleaseNotes/1_3_18.md
Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.py
Packs/CommonScripts/Scripts/SetIfEmpty/SetIfEmpty.yml
Packs/CommonScripts/TestPlaybooks/SetIfEmptyTest.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33445
improved handling of non-ASCII chars.
tested with playbook as the error is within the demisto class and cannot be tested via unit tests.

SetIfEmpty: Fix set if empty non ascii chars

---

Tests/conf.json

added "SetIfEmpty - non-ascii chars - Test" to conf.json

---

Packs/qualys/Integrations/integration-qualys.yml
Packs/qualys/ReleaseNotes/1_0_3.md
Packs/qualys/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33446
Added the policy_id argument to the command's args list

Added the policy_id argument to the command's args list

---

Tests/conf.json

fixes: demisto/etc#31461
timeout was extended for test playbook 

timeout fix

---

.circleci/config.yml
Tests/Marketplace/configure_and_install_packs.py
Tests/configure_and_test_integration_instances.py
Tests/instance_notifier.py
Tests/private_build/tests/test_configure_and_test_integration_instances_private.py
Tests/scripts/validate_premium_packs.py
Tests/scripts/wait_until_server_ready.py
Tests/secrets_white_list.json
Tests/test_content.py
Tests/tools.py

This PR implements lockdown of the lab:
- Editing the ssh config file with the following:
```
Host 10.0.*
StrictHostKeyChecking no
LogLevel ERROR
ProxyJump ec2-user@content-build-lb.demisto.works
Host content-build-lb.demisto.works
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
LogLevel ERROR
```
- Creating a ssh tunnel through the load-balancer to one of the bastions to the server instance and replacing all https calls to the server's public IP with calls to `localhost:<tunnel port>` using the following script:
```
IPS_AND_PORTS=$(cat ./env_results.json | jq ".[] | select(.Role==\"$INSTANCE_ROLE\")" | jq -r '[.InstanceDNS, .TunnelPort] | @tsv' | sed "s/\"//g")
echo $IPS_AND_PORTS | grep -o -E "[0-9\.]+ [0-9]{4}" | while read IP_AND_PORT;
do
IP=$(echo $IP_AND_PORT | grep -o -E …
```

Implementing the lab lockdown

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/README.md
Packs/EDL/ReleaseNotes/1_0_7.md
Packs/EDL/pack_metadata.json

Add EDL URL arguments to the readme of EDL.

[Documentation] Add to EDL URL args

---

Tests/instance_notifier.py
Tests/private_build/run_content_tests_private.py
Tests/test_content.py
Tests/test_integration.py

Using local host with the tunnel port
related issue: https://github.com/demisto/etc/issues/32500

Fixing an issue with private build

---

.github/workflows/project_manager.yml
.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

Changed the token used to update the board to `CONTENTBOT_BOARD_UPDATE_TOKEN`.

[Contribution Automation] Change Token Used to Update Board

---

.github/workflows/project_manager.yml
.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

Add names to the project manager workflows.

[Project Manager] Add names to the project manager workflows

---

Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_Scan_Test.yml
Packs/Tenable_io/TestPlaybooks/playbook-Tenable.io_test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26727
fixes: https://github.com/demisto/etc/issues/26728
- Replaced the testing scan in tenable.io to a new, stable one (updated the relevant tasks)
- Added 2 retries for tenable.io tasks in TPBs due to 429 error code retrieved once

Tenable.io TPBs update

---

Packs/Cymptom/.pack-ignore

add ignore to pass RM102 validation before merging https://github.com/demisto/demisto-sdk/pull/1077

ignore RM102

---

Tests/conf.json

skipped taxii until next sdk release

---

Tests/conf.json

increased tenable.io scan test timeout due to last nightly failure

increased tenable.io scan test timeout

---

Packs/Arduino/Integrations/Arduino/Arduino_description.md
Packs/Arduino/ReleaseNotes/1_0_1.md
Packs/Arduino/pack_metadata.json
Packs/Cymptom/Integrations/Cymptom/Cymptom_description.md
Packs/Cymptom/Integrations/Cymptom/README.md
Packs/Cymptom/ReleaseNotes/1_0_1.md
Packs/Cymptom/pack_metadata.json
Packs/RSTCloud/Integrations/RSTCloudThreatFeedAPI/RSTCloudThreatFeedAPI_description.md
Packs/RSTCloud/ReleaseNotes/1_0_1.md
Packs/RSTCloud/pack_metadata.json

Small fixes regarding support links and publisher. Fix readme formatting with `&amp`.

cymptom: remove developer details from support/publisher. Fix README formatting

---

Packs/Base/ReleaseNotes/1_7_12.md
Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
Packs/Base/pack_metadata.json

Change ML fetch data to run once

---

Packs/CommonScripts/ReleaseNotes/1_3_19.md
Packs/CommonScripts/Scripts/GetIndicatorDBotScore/GetIndicatorDBotScore.py
Packs/CommonScripts/pack_metadata.json
Packs/Pwned/TestPlaybooks/playbook-EmailReputationTest.yml

fixes: https://github.com/demisto/etc/issues/32761
fixes: https://github.com/demisto/etc/issues/30079
replace the outputs from one dbot score object with a list of values. to list of dbot scores.

fixing GetIndicatorDBotScore script

---

Packs/GreyNoise/.pack-ignore

added ignore of validation of IN136

GreyNoise ignore IN136

---

Tests/scripts/collect_tests_and_content_packs.py

Ignoring server integrations in the tests and packs collection

Don't search for server integrations in id_set

---

Packs/EWS/Integrations/EWSv2/EWSv2.py
Packs/EWS/ReleaseNotes/1_7_6.md
Packs/EWS/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33629
improved error message.

EWS v2: improved error message

---

Packs/Box/Integrations/BoxV2/README.md

box: fix broken links

---

Packs/Orca/README.md
Packs/Orca/ReleaseNotes/1_0_3.md
Packs/Orca/pack_metadata.json

Updated readme.md file
- [] Yes

Orca integration text edits

---

Tests/configure_and_test_integration_instances.py

Avoid validation of docker images during content installation.

Ignoring docker image validation in 5.5 and 5.0

---

Packs/Arduino/pack_metadata.json

Arduino: update pack description

---

Packs/Zscaler/Integrations/Zscaler/Zscaler.py
Packs/Zscaler/ReleaseNotes/1_1_2.md
Packs/Zscaler/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33036
Increased request timeout to 15.

Zscaler - Added timeout to the http request

---

Packs/Cyberint/Integrations/Cyberint/Cyberint.py
Packs/Cyberint/ReleaseNotes/1_0_2.md
Packs/Cyberint/pack_metadata.json

Cyberint: Fixed issue with '<' operator

---

Packs/SafeBreach/Integrations/SafeBreach_v2/README.md

safebreach readme: fix broken link

---

Packs/EDL/Integrations/EDL/EDL.py
Packs/EDL/Integrations/EDL/EDL.yml
Packs/EDL/ReleaseNotes/1_0_8.md
Packs/EDL/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31888
moved the data filtering as part of the batch iterations.

EDL: fixed out of memory error

---

Packs/Base/ReleaseNotes/1_7_13.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/Scripts/CommonServerPython/CommonServerPython_test.py
Packs/Base/pack_metadata.json

Common: mask basic auth

---

Packs/Office365AndAzureAuditLog/Integrations/MicrosoftPolicyAndComplianceAuditLog/README.md

fixed README.md

---

Packs/Slack/Integrations/Slack/Slack.py
Packs/Slack/Integrations/Slack/Slack_test.py
Packs/Slack/ReleaseNotes/1_3_15.md
Packs/Slack/pack_metadata.json
Tests/conf.json

relates: https://github.com/demisto/content/pull/11360
Converted response of type 'SlackResponse' to json.

Slack v2 - Converted response to json

---

Tests/Marketplace/upload_packs.py

Revert "Fix for removing metadata versions"

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/README.md
Packs/MicrosoftTeams/ReleaseNotes/1_1_1.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: https://github.com/demisto/content-docs/issues/491

Microsoft Teams - improve team_member arg description

---

Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.py
Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/CrowdStrikeFalconX.yml
Packs/CrowdStrikeFalconX/ReleaseNotes/1_1_0.md
Packs/CrowdStrikeFalconX/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33748
added base URL parameter

CrowdStrikeFalconX: added base_url parameter

---

Packs/ServiceNow/Integrations/ServiceNowv2/ServiceNowv2.py
Packs/ServiceNow/ReleaseNotes/2_1_13.md
Packs/ServiceNow/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33711
added another validation for the test-module.

ServiceNow v2: added another validation for the test-module

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32830

GoogleCloudTranslate-Test - increase pid to 9

---

Packs/StarterPack/Integrations/BaseIntegration/BaseIntegration.yml
Packs/StarterPack/ReleaseNotes/1_0_1.md
Packs/StarterPack/Scripts/BaseScript/BaseScript.yml
Packs/StarterPack/pack_metadata.json

The name we had didn't look good in the marketplace.

starter pack: update base integration name

---

Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/1_3_0.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/31050
Implemented get-mapping-fields according to Splunk CIM

Splunk CIM mapping fields

---

Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
Packs/Active_Directory_Query/ReleaseNotes/1_1_4.md
Packs/Active_Directory_Query/pack_metadata.json

Fixed grammar issue according to Rasmi's notes

Active directory query v2 grammer bug fix

---

Packs/Slack/Scripts/SlackAsk/README.md

fixes: https://github.com/demisto/content-docs/issues/447
Small doc fix

slackask: update doc about task tag

---

.github/CODEOWNERS

taking ownership on SetGridField

adding myelf as CODEOWNER of SetGridField

---

Packs/IntegrationsAndIncidentsHealthCheck/ReleaseNotes/1_1_13.md
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.py
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/CopyLinkedAnalystNotes/CopyLinkedAnalystNotes.yml
Packs/IntegrationsAndIncidentsHealthCheck/Scripts/GetFailedTasks/GetFailedTasks.py
Packs/IntegrationsAndIncidentsHealthCheck/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33797
fixes: https://github.com/demisto/etc/issues/33796
Fixed an issue when sorting **main_incident_grid** failed due to TypeError. Setting a default value of an empty string solved the problem.

Health Check | CopyLinkedAnalystNotes - fix TypeError 

---

Packs/BPA/Playbooks/playbook-BPA.yml
Packs/BPA/ReleaseNotes/1_2_4.md
Packs/BPA/pack_metadata.json

Changed the context of the generic-polling sub-playbook to be private, in order to solve the test failure of the BPA_Integration_test.

BPA Integration Test Fix

---

Packs/Base/ReleaseNotes/1_7_15.md
Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
Packs/Base/pack_metadata.json

1. Bug fixed that argument "toDate" doesn't have effect on results
2. Improved labels fields candidate finding by filtering using a blacklist of keywords

Dbot ml fetch data - bug fix and improved candidate labels fields finding

---

.circleci/config.yml

bump version 21.2.1

---

Packs/ReversingLabs_A1000/TestPlaybooks/playbook-ReversingLabsA1000Test.yml

fixes: https://github.com/demisto/etc/issues/33842
Playbook fails due to the product archiving of the example file tested. Changed the file tested.

reversing labs a1000 - changed the file checked.

---

Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Incident_Classifier_5_9_9.json
Packs/CrowdStrikeFalcon/Classifiers/classifier-CrowdStrike_Falcon_Mapper.json
Packs/CrowdStrikeFalcon/ReleaseNotes/1_2_13.md
Packs/CrowdStrikeFalcon/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33866
Fixed an issue when the *Device Name* field in the mapper did not work properly.

CSFalcon mappers typo

---

Packs/Base/ReleaseNotes/1_7_15.md

fix base rn 1.7.15 to be not empty

---

Packs/AzureCompute/Integrations/AzureCompute_v2/AzureCompute_v2.yml
Packs/AzureCompute/ReleaseNotes/1_0_5.md
Packs/AzureCompute/pack_metadata.json
Packs/FeedCrowdstrikeFalconIntel/Integrations/FeedCrowdstrikeFalconIntel/FeedCrowdstrikeFalconIntel.yml
Packs/FeedCrowdstrikeFalconIntel/ReleaseNotes/1_0_4.md
Packs/FeedCrowdstrikeFalconIntel/pack_metadata.json
Packs/GitHub/Integrations/GitHub/GitHub.yml
Packs/GitHub/ReleaseNotes/1_1_8.md
Packs/GitHub/pack_metadata.json
Packs/McAfee_ESM/Integrations/McAfee_ESM_v2/McAfee_ESM_v2.yml
Packs/McAfee_ESM/ReleaseNotes/1_1_4.md
Packs/McAfee_ESM/pack_metadata.json
Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.py
Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/MicrosoftCloudAppSecurity.yml
Packs/MicrosoftCloudAppSecurity/Integrations/MicrosoftCloudAppSecurity/README.md
Packs/MicrosoftCloudAppSecurity/ReleaseNotes/1_0_15.md
Packs/MicrosoftCloudAppSecurity/pack_metadata.json
Packs/NutanixHypervisor/Integrations/NutanixHypervisor/NutanixHypervisor.yml
Packs/NutanixHypervisor/ReleaseNotes/1_0_1.md
Packs/NutanixHypervisor/pack_metadata.json
Packs/SumoLogic/Integrations/integration-SumoLogic.yml
Packs/SumoLogic/ReleaseNotes/1_0_6.md
Packs/SumoLogic/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33745
As the tooltips currently don't support markdown format, remove all markdown links from descriptions.

Remove Markdown Links From Descriptions

---

Packs/Active_Directory_Query/Integrations/Active_Directory_Query/README.md

fixes: https://github.com/demisto/etc/issues/33836

Updated docs for AD mapper, ILM use case

---

Packs/PowershellPayloadResponse/pack_metadata.json

The pack name is flawed - this should fix it

Fixing bad pack name for Powershell Payload Response pack

---

.circleci/config.yml
.circleci/content_release_vars.sh

fixes: https://github.com/demisto/etc/issues/31084
move the content release variables to a separate file

moved content release variables to a separated file

---

Packs/Gmail/Integrations/Gmail/README.md

Small doc fixes to links and clarifications.

gmail readme: fix links

---

Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.py
Packs/AWS-SecurityHub/Integrations/AWS_SecurityHub/AWS_SecurityHub.yml
Packs/AWS-SecurityHub/ReleaseNotes/1_0_4.md
Packs/AWS-SecurityHub/TestPlaybooks/AWS_SecurityHub_Test.yml
Packs/AWS-SecurityHub/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29796
* Fixed an issue with pagination where the kwargs in first request are different on the rest of the requests, which led to an error: `Invalid NextToken: Input Query has changed`
* Updated docker image.
* Removed the integration from the parallel integrations since the playbook has a write command which could cause a confict.
* Removed the playbook from skipped playbooks
* Removed the integration from unmockable integrations.
* Minor improvement to the test playbook to use `FirstArrayElement` instead of element at index 0.
* Removed multiple appearances of the argument `date_range_unit` from the yml file (should not affect customer at all)

Fixing pagination issue and playbook

---

Packs/ProofpointServerProtection/Integrations/ProofpointProtectionServerV2/README.md

PPS v2 - fmt example url in readme

---

Packs/Active_Directory_Query/ReleaseNotes/1_1_5.md
Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.py
Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
Packs/Active_Directory_Query/pack_metadata.json

Fixed a bug where an email was sent even though the creation of the user failed.

Fixed a bug with sending mail

---

Packs/CommonWidgets/ReleaseNotes/1_0_7.md
Packs/CommonWidgets/Widgets/widget-MttrByType.json
Packs/CommonWidgets/Widgets/widget-MttrByTypeInMinutes.json
Packs/CommonWidgets/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33938
in referenced issue

Mttr by type mins

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/34035
Extend docker memory threshold due to test failure

iDefense Feed extend memory threshold due to test failure

---

Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.py
Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators.yml
Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_description.md
Packs/ExportIndicators/Integrations/ExportIndicators/ExportIndicators_test.py
Packs/ExportIndicators/Integrations/ExportIndicators/README.md
Packs/ExportIndicators/ReleaseNotes/1_0_3.md
Packs/ExportIndicators/pack_metadata.json

Base contribution branch:
https://github.com/demisto/content/pull/11484
fixes: None
Added the ability to sort exported indicators by field.

ExportIndicators - Added sorting option

---

Packs/AWS-S3/TestPlaybooks/playbook-AWS-S3Test.yml
Tests/conf.json

- Using const file name when uploading
- Removing from unmockable list
https://github.com/demisto/etc/issues/33414

Mocking AWS - S3 integrations and modifying it to work

---

Tests/conf.json

remock playbooks with streaming files

---

Packs/Tidy/Integrations/Tidy/Tidy.yml
Packs/Tidy/ReleaseNotes/1_0_1.md
Packs/Tidy/pack_metadata.json

Related issues: https://github.com/demisto/etc/issues/34005

Tidy - Replacing with demisto registry image

---

Tests/conf.json

The standard test works, the mssp i expired.

unskip intsights

---

Packs/PowershellPayloadResponse/pack_metadata.json

Fixing the description for the Powershell Playbook Response pack.

fixing the description of the Powershell Playbook Response pack

---

Tests/configure_and_test_integration_instances.py

small fix for https://github.com/demisto/content/pull/11488

small fix for no proxy param

---

Packs/FeedDHS/README.md
Packs/FeedDHS/pack_metadata.json

* fixed pack name.
* updated pack description and README with a link to the AIS site.

DHS Feed: updated pack metadata

---

Tests/private_build/upload_packs_private.py

fixed private index using name instead of id.

fix private upload bug: using name as id

---

Packs/EDL/Integrations/EDL/README.md

Fixed a typo in parameters

---

Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.py
Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2.yml
Packs/FeedTAXII/Integrations/FeedTAXII2/FeedTAXII2_test.py
Packs/FeedTAXII/ReleaseNotes/1_0_8.md
Packs/FeedTAXII/pack_metadata.json

https://github.com/demisto/etc/issues/24029
Added an `incrementalFeed` parameter to TAXII 2, since it's incremental feed.

TAXII 2 add incrementalFeed parameter

---

Packs/EWS/README.md

Created content for the pack readme.
- [ x] Ready
Every pack needs a pack README that will appear in Marketplace. This is the EWS pack README.
- [x ] No

Update EWS Pack README.md

---

Utils/trigger_upload_packs_to_production.sh

fix bad json in trigger_upload_packs_to_production.sh

---

Tests/Marketplace/upload_packs.py

index.json creation should not be skipped if no private pack was updated

upload flow - fix condition for private packs

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py

moved to notable class, cr fixes

---

.github/workflows/project_manager_daily.yml
.github/workflows/project_manager_hourly.yml

Add GitHub Automation board management.

Add contribution GitHub Automation board management

---

Packs/GenericSQL/Integrations/GenericSQL/GenericSQL.py
Packs/GenericSQL/ReleaseNotes/1_0_10.md
Packs/GenericSQL/pack_metadata.json

https://github.com/demisto/content/pull/11592
Missing import for `Optional`

GenericSQL - Imported Optional

---

Packs/Orca/Integrations/Orca/Orca.py
Packs/Orca/Integrations/Orca/Orca.yml
Packs/Orca/Integrations/Orca/Orca_test.py
Packs/Orca/ReleaseNotes/1_0_4.md
Packs/Orca/pack_metadata.json

- Added dynamic informational alerts querying
- Fixed timestamp bug

Orca integration dynamic informational alerts

---

Packs/CommonScripts/ReleaseNotes/1_3_23.md
Packs/CommonScripts/Scripts/CheckFieldValue/CheckFieldValue.py
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34298

CheckFieldValue fix

---

Packs/SailPointIdentityIQ/Integrations/SailPointIdentityIQ/README.md

NA
Updated connectivity parameters in README.md file
NA

Updated README.md (Connectivity)

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32567
Unskip TAXII Feed test

Unskip TAXII Feed test

---

Packs/CommonScripts/ReleaseNotes/1_3_24.md
Packs/CommonScripts/Scripts/script-ConvertXmlFileToJson.yml
Packs/CommonScripts/Scripts/script-ConvertXmlToJson.yml
Packs/CommonScripts/Scripts/script-CreateArray.yml
Packs/CommonScripts/Scripts/script-CreateEmailHtmlBody.yml
Packs/CommonScripts/Scripts/script-FileCreateAndUpload.yml
Packs/CommonScripts/Scripts/script-IncidentAddSystem.yml
Packs/CommonScripts/Scripts/script-IsGreaterThan.yml
Packs/CommonScripts/Scripts/script-LessThanPercentage.yml
Packs/CommonScripts/Scripts/script-MathUtil.yml
Packs/CommonScripts/Scripts/script-NotInContextVerification.yml
Packs/CommonScripts/Scripts/script-ParseJSON.yml
Packs/CommonScripts/Scripts/script-UnEscapeIPs.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34103
related: https://github.com/demisto/content/pull/11566
Fixed in some scripts arguments' `description` to start with a capital letter.
This PR fixes only scripts that did not need split-yml

CommonScripts - fixed argument descriptions

---

Packs/ExpanseV2/TestPlaybooks/playbook-ExpanseV2_Test.yml
Packs/GreyNoise/TestPlaybooks/playbook-GreyNoise-test.yml
Packs/XMCyber/TestPlaybooks/XMCyberIntegration-Test.yml
Tests/scripts/collect_tests_and_content_packs.py

fixes: https://github.com/demisto/etc/issues/34305

fix tpb for collect test

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29593

MS ATA - unskip test

---

Tests/conf.json

Related issue: https://github.com/demisto/etc/issues/31779

Temprarily unmocking the playbook until multipart header issue is solved

---

Packs/FeedIntel471/Integrations/Intel471Actors/Intel471Actors.yml
Packs/FeedIntel471/Integrations/Intel471Malware/Intel471Malware.yml
Packs/FeedIntel471/ReleaseNotes/1_1_0.md
Packs/FeedIntel471/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34398
removing duplicated fields from YML.

removed duplicated fields

---

Packs/Campaign/pack_metadata.json

Campaign: Update pack_metadata.json - fix typo in name

---

Tests/Marketplace/upload_packs.py
Tests/scripts/slack_notifier.py
Tests/scripts/validate_index.py
Tests/scripts/validate_premium_packs.py
Tests/scripts/validate_premium_packs.sh

- Sorted packs in Slack message.
- Updated docstrings across the private content handling.
- Improved error handling across the private content handling.
- Added support for the testing flow in the `validate_premium_packs.sh` script.

Upload-Flow Refinement

---

Packs/PaloAltoNetworks_PAN_OS_EDL_Management/Integrations/PaloAltoNetworks_PAN_OS_EDL_Management/PaloAltoNetworks_PAN_OS_EDL_Management.yml
Packs/PaloAltoNetworks_PAN_OS_EDL_Management/ReleaseNotes/1_0_2.md
Packs/PaloAltoNetworks_PAN_OS_EDL_Management/pack_metadata.json
Tests/conf.json

relates to: https://github.com/demisto/etc/issues/34452

Palo Alto Networks PAN-OS EDL Management (Deprecated)

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py

https://github.com/demisto/content/pull/11660
- Migrating https://github.com/demisto/content/pull/11660 to the enrichment mechanism.
- Improving hashing for non-notable use-cases.

Splunk bugfix migration

---

.circleci/config.yml
Utils/get_private_build_status.py
Utils/trigger_private_build.py

https://github.com/demisto/etc/issues/33518
- Added condition to avoid running private build for contributions PRs and for `bucket_upload_trigger` workflow.
- Improve `get_workflow_status` function to check for failure steps.

Trigger private build fixes

---

Tests/Marketplace/marketplace_services.py
Tests/Marketplace/upload_packs.py
Tests/private_build/tests/test_upload_packs_private.py
Tests/private_build/upload_packs_private.py

related: https://github.com/issues/assigned
Removing vendor name as it is a dummy field the got replaced by partnerName

removing vendorName from upload process

---

Packs/Exabeam/Integrations/Exabeam/README.md

[Exabeam doc page](https://xsoar.pan.dev/docs/reference/integrations/exabeam) is malformed because it contains HTML table tags - this PR should resolve this issue.

exabeam doc - html to md

---

.github/CODEOWNERS

We need to protect our landing-page sections file.

Protect landing-page sections file

---

Packs/EWS/TestPlaybooks/O365-EWS-Extension-Powershell-Online-V2-Test.yml

EWS Extenstion Powershell: Fixed removed test

---

Packs/EWS/TestPlaybooks/playbook-EWS-Searchmailbox-Test.yml

Add an integration ID that will execute send-mail command

Add EWSO365 integration id to send-mail task 

---

Packs/GraphQL/Integrations/GraphQL/GraphQL.yml
Packs/GraphQL/ReleaseNotes/1_0_1.md
Packs/GraphQL/pack_metadata.json

https://github.com/demisto/dockerfiles/pull/4371

GraphQL - bump docker image tag

---

Packs/CommonScripts/ReleaseNotes/1_3_28.md
Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address.py
Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address.yml
Packs/CommonScripts/Scripts/IsRFC1918Address/IsRFC1918Address_test.py
Packs/CommonScripts/Scripts/IsRFC1918Address/README.md
Packs/CommonScripts/TestPlaybooks/playbook-IsRFC1918_Test.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34697

IsRFC1918Address - Fixed an issue where the script was not working as a transformer.

---

Tests/conf.json

Related: https://github.com/demisto/etc/issues/30797
The TPB pass locally - remove from skip

unskip Generic Webhook - Test TPB

---

Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.py
Packs/QRadar/Integrations/QRadar_v2/QRadar_v2.yml
Packs/QRadar/ReleaseNotes/1_2_12.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34627
Fixed an issue where the integration returned None instead of displaying the error message.
Removed LOG uses from the integration

Error msgs in QRadar_v2

---

Packs/Gmail/TestPlaybooks/playbook-GmailTest.yml

Add gmail ID to send-mail task on the test playbook

Add gmail id to send-mail command on test playbook

---

Packs/CommonTypes/IncidentFields/incidentfield-Hostnames.json
Packs/CommonTypes/ReleaseNotes/2_8_8.md
Packs/CommonTypes/pack_metadata.json
Packs/Ransomware/README.md

Article link and hostname select value fix. 

Ransomware fixes

---

Tests/Marketplace/landingPage_sections.json

related: https://github.com/demisto/etc/issues/29390
Update landing page to contain content.

landing page: update featured and sections

---

Tests/conf.json

Related: https://github.com/demisto/etc/issues/29279
Added `playbook-Microsoft_ATP_indicators_Test.yml` to skip

add mic-atp Indicators Test to skip

---

Packs/GoogleDrive/Integrations/GoogleDrive/README.md

drive readme: fix example link formatting

---

.circleci/content_release_vars.sh

bump version 21.3.1

---

Packs/FeedMitreAttack/README.md

Create content for the MITRE ATT&CK Feed pack README.
- [x ] Ready
Content for the MITRE ATT&CK Feed pack README that will appear in Marketplace.
- [ x] No

Content for the MITRE ATT&CK Feed pack README

---

Packs/FeedUnit42/README.md

- [x ] Ready
Created content for the FeedUnit42 Pack README.  This content will appear in Marketplace.
- [x ] No

Created content for the FeedUnit42 Pack README

---

Packs/AutoFocus/Integrations/AutofocusV2/AutofocusV2_test.py
Packs/Carbon_Black_Enterprise_Response/.pack-ignore
Packs/Carbon_Black_Enterprise_Response/Integrations/integration-Carbon_Black_Enterprise_Response.yml
Packs/Carbon_Black_Enterprise_Response/ReleaseNotes/1_1_5.md
Packs/Carbon_Black_Enterprise_Response/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34358
Fixed a bug where the API request's body was changed in a newer version of the product therefore not working in current version.

cb-quarantine-device Bug fix

---

Packs/Mimecast/Integrations/MimecastV2/MimecastV2_description.md
Packs/Mimecast/Integrations/MimecastV2/README.md
Packs/Mimecast/ReleaseNotes/1_1_3.md
Packs/Mimecast/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34375
Added a link to the Mimecast documentation that explains how to create a new application, and get all the fields that are required to configure a new instance for the integration in XSOAR.

Added reference to Mimecast documentation

---

Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
Packs/cyberark_AIM/ReleaseNotes/1_0_6.md
Packs/cyberark_AIM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34844

CyberArkAIM params type fix

---

Packs/CiscoStealthwatch/Playbooks/playbook-List_Cisco_Stealthwatch_Security_Events_README.md
Packs/CiscoStealthwatch/Playbooks/playbook-Query_Cisco_Stealthwatch_Flows_README.md

Fix images relative path

---

Packs/cyberark_AIM/Integrations/CyberArkAIM_v2/CyberArkAIM_v2.yml
Packs/cyberark_AIM/ReleaseNotes/1_0_7.md
Packs/cyberark_AIM/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34844

Cyberark fix param encryption 

---

Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
Packs/SplunkPy/ReleaseNotes/1_3_3.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33995
Added support for Splunk token authentication. Based on https://github.com/splunk/splunk-sdk-python/pull/282

Splunk token authentication

---

Packs/Opsgeniev2/pack_metadata.json

Small fix to the pack display name

opsgenie v2: fix pack display name

---

Packs/ServiceNow/Classifiers/classifier-ServiceNow_5_9_9.json
Packs/ServiceNow/Classifiers/classifier-mapper-ServiceNow_Create_Ticket_-_Incoming_Mapper.json
Packs/ServiceNow/Classifiers/classifier-mapper-incoming-ServiceNow.json
Packs/ServiceNow/Integrations/ServiceNowv2/README.md
Packs/ServiceNow/ReleaseNotes/2_1_19.md
Packs/ServiceNow/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34387
Fixed an issue where we saw an incorrect date in the layout.
It seems like the date we get back from SNOW is a European date, that is why I changed the input for `dayfirst` in `DateStringToISOFormat` script to be false.

Fix date in service now mappers

---

Packs/CrowdStrikeFalconX/Integrations/CrowdStrikeFalconX/README.md

CrowdStrike Falcon x - typo in the README

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27942
Unskipped pyews tpb
passed locally in both instances - ewsv2_regular and ewsv2_separate_process

Unskip Pyews_test TPB

---

Packs/MicrosoftGraphSecurity/.pack-ignore
Packs/MicrosoftGraphSecurity/TestPlaybooks/Microsoft_Graph_Security_Test_dev.yml
Packs/MicrosoftGraphSecurity/TestPlaybooks/Microsoft_Graph_Security_Test_prod.yml
Tests/conf.json

mock Microsoft Graph Security Test

mock Microsoft Graph Security Test

---

Packs/MicrosoftGraphCalendar/.pack-ignore
Packs/MicrosoftGraphCalendar/TestPlaybooks/Microsoft_Graph_Calendar_-_Test_dev.yml
Packs/MicrosoftGraphCalendar/TestPlaybooks/Microsoft_Graph_Calendar_-_Test_prod.yml
Tests/conf.json

mock Microsoft Graph Calendar

---

Packs/MicrosoftGraphMail/.pack-ignore
Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_dev.yml
Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_dev_no_oproxy.yml
Packs/MicrosoftGraphMail/TestPlaybooks/MicrosoftGraphMail-Test_prod.yml
Tests/conf.json

mock MicrosoftGraphMail

---

Packs/MicrosoftGraphGroups/.pack-ignore
Packs/MicrosoftGraphGroups/TestPlaybooks/Microsoft_Graph_Groups_-_Test_dev.yml
Packs/MicrosoftGraphGroups/TestPlaybooks/Microsoft_Graph_Groups_-_Test_prod.yml
Tests/conf.json

mock Microsoft Graph Groups

---

Packs/MicrosoftGraphDeviceManagement/.pack-ignore
Packs/MicrosoftGraphDeviceManagement/TestPlaybooks/MSGraph_DeviceManagement_Test_dev.yml
Packs/MicrosoftGraphDeviceManagement/TestPlaybooks/MSGraph_DeviceManagement_Test_prod.yml
Packs/MicrosoftGraphDeviceManagement/TestPlaybooks/MSGraph_DeviceManagement_Test_self_deployed_prod.yml
Tests/conf.json

mock Microsoft Graph Device Management

mock Microsoft Graph Device Management

---

Packs/MicrosoftDefenderAdvancedThreatProtection/.pack-ignore
Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_dev.yml
Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_prod.yml
Packs/MicrosoftDefenderAdvancedThreatProtection/TestPlaybooks/Microsoft_Defender_Advanced_Threat_Protection_-_Test_self_deployed.yml
Tests/conf.json

mock Microsoft Defender Advanced Threat Protection

mock Microsoft Defender Advanced Threat Protection

---

Packs/MicrosoftGraphFiles/.pack-ignore
Packs/MicrosoftGraphFiles/TestPlaybooks/test_MsGraphFiles_dev.yml
Packs/MicrosoftGraphFiles/TestPlaybooks/test_MsGraphFiles_prod.yml
Tests/conf.json

mock Microsoft_Graph_Files

---

Packs/McAfee_ESM/.pack-ignore
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v10.2.0.yml
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v10.3.0.yml
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_Watchlists_-_Test_v11.3.yml
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_-_Test_v10.2.0.yml
Packs/McAfee_ESM/TestPlaybooks/McAfee_ESM_v2_-_Test_v10.3.0.yml
Tests/conf.json

mock McAfee ESM v2

---

Packs/CommonTypes/IncidentFields/incidentfield-Email.json
Packs/CommonTypes/ReleaseNotes/2_8_11.md
Packs/CommonTypes/pack_metadata.json

Related to: https://github.com/demisto/content-premium/pull/33 and https://github.com/demisto/content-private/pull/200
Associated the Email field with the IAM - AD User Activation incident type

Associated the Email field with the IAM - AD User Activation incident type

---

Packs/CommonTypes/ReleaseNotes/2_8_11.md

I accidentally did not merge your suggestion. Updating it here @amshamah419 
Related to: https://github.com/demisto/content/pull/11921

Fixed CommonTypes 2_8_11 RN

---

Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/ReleaseNotes/1_2_15.md
Packs/Jira/pack_metadata.json

Jira v2 - fixed typo in username display

---

.circleci/config.yml
Tests/Marketplace/Tests/validate_landing_page_sections_test.py
Tests/Marketplace/validate_landing_page_sections.py
Tests/scripts/collect_tests_and_content_packs.py
Utils/trigger_private_build.py

https://github.com/demisto/etc/issues/34750
- Validating the file schema and that it contains valid json.
- Validating that all packs that receive a Tag via this file are valid (using latest index.zip file).
- Don't trigger private build when modifying the file.
- Do not run Server tests for 5.5 and 5.0.

Adding validation for landingPage_sections.json file

---

Packs/GuardiCore/Integrations/README.md

https://github.com/demisto/etc/issues/33664

GuardiCore- add readme file

---

Packs/GmailSingleUser/Integrations/GmailSingleUser/README.md

A fix in content for https://github.com/demisto/demisto-sdk/pull/1188
A fix in content for https://github.com/demisto/demisto-sdk/pull/1188

Gmail Single User- fixed readme

---

Packs/PagerDuty/TestPlaybooks/playbook-PagerDuty_Test.yml

fixes: https://github.com/demisto/etc/issues/35115

pager duty more sleep after incident creation

---

Packs/Okta/pack_metadata.json
Packs/SumoLogic/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/30207
Fix content pack names

fix content pack names

---

Packs/PrismaCloud/Integrations/RedLock/README.md

fixes: https://github.com/demisto/content-docs/issues/558
Fixes suggested by @gomesian 

prisma cloud: update readme

---

Packs/QRadar/Playbooks/playbook-QRadar_Indicator_Hunting_V2.yml
Packs/QRadar/ReleaseNotes/1_2_13.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35237

Hash type bug fix

---

.circleci/content_release_vars.sh

bump version 21.3.2

---

Utils/github_workflow_scripts/handle_external_pr.py

I don't really agree with this change but it's up to you. ¯\_(ツ)_/¯

Limit consideration to contribution prs

---

Packs/GoogleDrive/Integrations/GoogleDrive/README.md

google drive readme: fix link formatting

---

Packs/EWS/Integrations/SecurityAndCompliance/README.md
Packs/EWS/Integrations/SecurityAndCompliance/SecurityAndCompliance.yml
Packs/EWS/ReleaseNotes/1_8_10.md
Packs/EWS/pack_metadata.json

Added explanation that no additional result should be shown for purge type action
fixes:https://github.com/demisto/etc/issues/35215

added explanation regarding the command in the desc

---

Tests/conf.json

https://github.com/demisto/etc/issues/35302
https://github.com/demisto/etc/issues/33974
Skip Tanium and Tanium Threat response integrations from nightly build

Skip tanium and tanium tr integrations

---

Packs/D2/.pack-ignore
Packs/Feedsslabusech/pack_metadata.json
Packs/Malwr/pack_metadata.json
Packs/Nmap/pack_metadata.json
Packs/OTRS/.pack-ignore
Packs/Okta/pack_metadata.json
Packs/Palo_Alto_Networks_Enterprise_DLP/.pack-ignore
Packs/StarterPack/.pack-ignore
Packs/UrlScan/pack_metadata.json
Packs/XMatters/.pack-ignore
Packs/dnstwist/pack_metadata.json
Packs/iDefense/.pack-ignore
Packs/ipinfo/pack_metadata.json
Packs/jamf/pack_metadata.json
Packs/mnemonicMDR/.pack-ignore
Packs/mnemonicMDR/pack_metadata.json

https://github.com/demisto/etc/issues/33909
https://github.com/demisto/demisto-sdk/pull/1171
We changed some of the files because they failed in the build after we added new rules to the names of the packs according this issue https://github.com/demisto/etc/issues/33909.
Some of the files we changed their name, and the others we are simply adding an ignore to this error.

Fix the issue with the pack name invalid

---

Packs/Venafi/Integrations/integration-Venafi_README.md

related: https://github.com/demisto/demisto-sdk/pull/1188
fix readme to fix validate in related PR

Venfai readme fix

---

Packs/epo/.pack-ignore

related: https://github.com/demisto/demisto-sdk/pull/1188
Add ignore RM102, for validating related PR

EPO readme ignore error

---

Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.py
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2.yml
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/AlienVault_OTX_v2_test.py
Packs/AlienVault_OTX/Integrations/AlienVault_OTX_v2/README.md
Packs/AlienVault_OTX/ReleaseNotes/1_0_3.md
Packs/AlienVault_OTX/pack_metadata.json

related: demisto/etc#29347
Added reliability

Alien vault otx v2 - Add Reliability

---

Packs/AsanaConnect/Integrations/AsanaConnect/AsanaConnect_description.md
Packs/AsanaConnect/ReleaseNotes/1_0_1.md
Packs/AsanaConnect/pack_metadata.json

Removed unnecessary information from description

Removed description information

---

Packs/AzureSecurityCenter/TestPlaybooks/playbook-AzureSCTestPlaybook.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27391
Added alerts to instance and changed get alert arguments in playbook

Test playbook failure fix

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32688
remove ThreatMiner test from skipped tests.

ThreatMiner - remove test playbook from skipped tests

---

Tests/conf.json

https://github.com/demisto/etc/issues/35302
https://github.com/demisto/etc/issues/33974
Unskip Tanium and Tanium Threat response integrations from nightly build

Unskip Tanium and Tanium TR

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/ReleaseNotes/1_3_1.md
Packs/Jira/pack_metadata.json

fixes: https://github.com/demisto/content/pull/12084

fix issueJson parameter bug in jira-create-issue command

---

Packs/Box/Integrations/BoxV2/BoxV2.py
Packs/Box/Integrations/BoxV2/BoxV2.yml
Packs/Box/ReleaseNotes/2_1_2.md
Packs/Box/pack_metadata.json

https://github.com/demisto/etc/issues/33818

Box v2 - bump docker image

---

.github/CODEOWNERS

Adding myself as code owner on config.yml

Adding myself as code owner on config.yml

---

Packs/FeedOffice365/Integrations/FeedOffice365/README.md

fixes: https://github.com/demisto/content-docs/issues/563

office 365 doc fix

---

dev-requirements-py3.txt

demisto sdk release 1-3-4

---

Packs/Jira/Integrations/JiraV2/README.md

fixes the following issues:
1. backslash in two titles.
2. code block in unnecessary place.
3. wrong indentations.

fix Jira README issues

---

Packs/Jira/Integrations/JiraV2/JiraV2_test.py

fixes: https://github.com/demisto/etc/issues/35527

add unit test for jira issueJson param

---

.circleci/config.yml

unlocks `HelloWorld Feed` in sdk nightly

Update circleci/config.yml - unlock HelloWorld Feed in SDK nightly

---

Packs/Uptycs/Integrations/Uptycs/Uptycs.py
Packs/Uptycs/Integrations/Uptycs/Uptycs.yml
Packs/Uptycs/ReleaseNotes/1_0_5.md
Packs/Uptycs/pack_metadata.json

https://github.com/demisto/etc/issues/33818

Uptycs - bump docker image

---

Packs/Rapid7_Nexpose/README.md

fixes: https://github.com/demisto/etc/issues/35651
Changed relative paths to GitHub raw full path

Rapid7-Nexpose: Updated relative image paths to full.

---

Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
Packs/Active_Directory_Query/ReleaseNotes/1_1_9.md
Packs/Active_Directory_Query/TestPlaybooks/playbook-Active_Directory_Test.yml
Packs/Active_Directory_Query/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/13329

AD - add test for custom attributes

---

Packs/Jira/Integrations/JiraV2/JiraV2.py
Packs/Jira/Integrations/JiraV2/JiraV2.yml
Packs/Jira/Integrations/JiraV2/README.md
Packs/Jira/ReleaseNotes/1_3_2.md
Packs/Jira/TestPlaybooks/playbook-Jira-v2-Test.yml
Packs/Jira/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35587
Added the reporter_id argument and reverted the changes that were made in https://github.com/demisto/content/pull/9870
@abaumgarten - FYI

Jirav2: Issue reporter bug fix

---

.circleci/content_release_vars.sh

bump version 21.4.0

---

Packs/CommonScripts/ReleaseNotes/1_3_34.md
Packs/CommonScripts/Scripts/script-UnEscapeURLs.yml
Packs/CommonScripts/TestPlaybooks/playbook-UnEscapeURLs-Test.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35649
added pp v3 gov cloud prefix

UnEscapeURLs - Added support for Proofpoint gov cloud addresses

---

Packs/nessus/Integrations/integration-nessus.yml
Packs/nessus/ReleaseNotes/1_0_1.md
Packs/nessus/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35225
fixed the command outputs based on the code and customer feedback (couldn't run locally).
will be force-merged since the build will fail on BC due to the output path changes

nessus: fixed outputs

---

Packs/FeedOpenCTI/pack_metadata.json

Name according to feed naming conventions.

opencti: rename pack

---

Packs/Jira/ReleaseNotes/1_3_2.md

Clarify release notes about BC change.

jira: clarify release notes about BC

---

Packs/StringifyArray/README.md
Packs/StringifyArray/ReleaseNotes/1_0_1.md
Packs/StringifyArray/pack_metadata.json

https://github.com/demisto/content/pull/12123
Fixed an incorrect script type in README: python -> javascript #12123

StringifyArray - Fixed an incorrect script type in README

---

Packs/FeedTalos/pack_metadata.json

Update pack name to match Feed naming conventions.

talos feed: update pack name

---

Packs/nessus/Integrations/integration-nessus.yml
Packs/nessus/ReleaseNotes/1_0_2.md
Packs/nessus/pack_metadata.json

fixes: https://app.circleci.com/pipelines/github/demisto/content/79314/workflows/2f070478-0892-4bca-b308-827e0703d9d7/jobs/328100#queue-placeholder/containers/0
Fix typo.

Typo in Nessus

---

Packs/Whois/Integrations/Whois/Whois.py
Packs/Whois/Integrations/Whois/Whois_test.py
Packs/Whois/ReleaseNotes/1_2_2.md
Packs/Whois/pack_metadata.json

Whois - fixed a wrong output

---

Tests/Marketplace/marketplace_services.py

fixes: https://github.com/demisto/etc/issues/35883
Removed the iter type.

Upload-Flow using regular diff

---

Packs/GoogleSafeBrowsing/Integrations/integration-GoogleSafeBrowsing.yml
Packs/GoogleSafeBrowsing/ReleaseNotes/1_0_3.md
Packs/GoogleSafeBrowsing/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35884
change API key parameter to encrypted text

GoogleSafeBrowing: change API key parameter to encrypted text

---

Packs/Cofense-Intelligence/Integrations/README.md
Packs/Cofense-Intelligence/Integrations/example
Packs/Cofense-Intelligence/Integrations/integration-Cofense-Intelligence.yml
Packs/Cofense-Intelligence/ReleaseNotes/1_0_1.md
Packs/Cofense-Intelligence/pack_metadata.json

related: https://github.com/demisto/etc/issues/29347
Added reliability to integration
- Further details: added required parameter

Added reliability- Cofence Intelligence

---

Packs/EWS/Integrations/SecurityAndCompliance/README.md

Add new context to ReadMe SecurityAndCompliance

---

Packs/VirusTotal/README.md

Done.
- [x ] Ready
Updated VirusTotal README with correct information.

Updated VirusTotal README.md

---

Packs/Base/ReleaseNotes/1_8_12.md
Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.py
Packs/Base/Scripts/DBotMLFetchData/DBotMLFetchData.yml
Packs/Base/pack_metadata.json

DbotMLFetchData docker update to support docker hardening configuration

DbotMLFetchData docker update to support docker hardening configuration

---

Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
Packs/RubrikPolaris/ReleaseNotes/1_0_1.md
Packs/RubrikPolaris/pack_metadata.json
Utils/request_contributor_review.py

Modified defaultclassifier and defaultmapper in values in the integration yaml file to match the "id" values from the Classifier and Mapping files. Originally these were set to the "name" values and the Go To links in the integration settings resulted in a "Not Found" error that required us to reselect the classification and mapping in the drop down menu.  Added release notes.

Rubrik polaris

---

Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.py
Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris.yml
Packs/RubrikPolaris/Integrations/RubrikPolaris/RubrikPolaris_test.py
Packs/RubrikPolaris/Layouts/layoutscontainer-Rubrik_Polaris_Radar.json
Packs/RubrikPolaris/ReleaseNotes/1_0_2.md
Packs/RubrikPolaris/pack_metadata.json

The commits in this branch are all layout and name fixes to the actual integration.  The Rubrik Polaris Radar layout contained an extra unwanted "Message" field in the Event Timeline section that we removed.  Also we changed the name of the Integration to "Rubrik Radar" from "Rubrik Polaris" ... as well as introduced a space in the content pack name from "RubrikPolaris" to "Rubrik Polaris".

Rubrik Polaris Layout and Name fixes

---

Packs/PAN-OS/Integrations/Panorama/README.md

Edited and reformatted Palo Alto Networks PAN-OS Integration README

Updated PAN-OS Integration README

---

Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.py
Packs/MicrosoftTeams/Integrations/MicrosoftTeams/MicrosoftTeams.yml
Packs/MicrosoftTeams/ReleaseNotes/1_1_7.md
Packs/MicrosoftTeams/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/33818

Microsoft Teams - bump docker image and adjust to work with latest pyjwt

---

Packs/D2/.pack-ignore
Packs/DefaultPlaybook/.pack-ignore
Packs/LogPoint_SIEM_Integration/.pack-ignore
Packs/OTRS/.pack-ignore
Packs/OnboardingIntegration/.pack-ignore
Packs/Palo_Alto_Networks_Enterprise_DLP/.pack-ignore
Packs/StarterPack/.pack-ignore
Packs/TIM_SIEM/.pack-ignore
Packs/XMatters/.pack-ignore
Packs/iDefense/.pack-ignore
Packs/mnemonicMDR/.pack-ignore

https://github.com/demisto/etc/issues/33909
Related Pull Requests
demisto/demisto-sdk#1171
We add the PA124 Error in ignore is nome packs because they failed in the build after we added new rules to the names of the packs according this issue demisto/etc#33909.

error PA108 to PA124

---

Tests/Marketplace/copy_and_upload_packs.py

fixed index.json build blob path

Copy And Upload - fix index.json build blob path

---

Packs/BitcoinAbuse/Integrations/BitcoinAbuse/BitcoinAbuse.yml
Packs/BitcoinAbuse/Integrations/BitcoinAbuse/test_data/get_indicators_command.json
Packs/BitcoinAbuse/ReleaseNotes/1_0_2.md
Packs/BitcoinAbuse/pack_metadata.json

Bitcoin Abuse Unit Test Fix

---

Packs/PANOStoCDLMonitoring/Playbooks/PANOStoCDLMonitoring-cron_job.yml
Packs/PANOStoCDLMonitoring/ReleaseNotes/1_0_4.md
Packs/PANOStoCDLMonitoring/pack_metadata.json

fix incident type mentioned in PB

---

Packs/ExtFilter/README.md
Packs/ExtFilter/pack_metadata.json

- renamed the pack to be more indicative
- fixed typos in the pack desc and readme
@spearmin10 FYI

ExtFilter - rename pack and fix typos

---

Packs/CortexXDR/Integrations/CortexXDRIR/CortexXDRIR.py
Packs/CortexXDR/ReleaseNotes/3_0_6.md
Packs/CortexXDR/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35324
* Added default values to closing fields when batch closing incidents
* Splitted the if condition in line 2613 to prevent from happening again

Cortex XDR - Added default values to closing fields when batch closing incidents

---

Tests/scripts/upload_artifacts.sh

related: https://github.com/demisto/etc/issues/33657
Store compressible file types with `-z` option

artifacts upload: use -z

---

.github/workflows/check-contributor-pack.yml
Packs/NewPack/pack_metadata.json
Utils/request_contributor_review.py
dev-requirements-py3.txt

Test email darya lastone

---

Tests/configure_and_test_integration_instances.py

In case there is an integration with server keys - those server keys needs to be added to the current configurations, not overwrite them.

Fixing server keys issue

---

.circleci/content_release_vars.sh

bump version to 21.4.1

---

.github/workflows/check-contributor-pack.yml

Added condition not to run on internal

---

Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.py
Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.yml
Packs/PopularCybersecurityNews/ReleaseNotes/1_0_1.md
Packs/PopularCybersecurityNews/pack_metadata.json

fixes: None
not updating context if no news came in.

popular news fix

---

Packs/AutoFocus/README.md

- [x ] Ready
Created a pack readme for Active Directory Query. This content will appear in Marketplace.

Created content for AutoFocus pack README

---

Packs/ExpanseV2/README.md

Done.
11931
Added a sentence that the integration also supports the Services API.

Update Expanse README.md

---

Packs/RSANetWitness_v11_1/Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1.py
Packs/RSANetWitness_v11_1/Integrations/RSANetWitness_v11_1/RSANetWitness_v11_1_test.py
Packs/RSANetWitness_v11_1/ReleaseNotes/1_0_2.md
Packs/RSANetWitness_v11_1/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36262
Break the fetching if the response is empty.
Failing UT: https://app.circleci.com/pipelines/github/demisto/content/82064/workflows/8557323f-6d4c-428d-90a6-4c743ea0c1d3/jobs/339139

RSA Netwitness fetch - solution

---

Packs/FeedFeodoTracker/Integrations/FeedFeodoTrackerIPBlocklist/FeedFeodoTrackerIPBlocklist_description.md
Packs/FeedFeodoTracker/ReleaseNotes/1_1_1.md
Packs/FeedFeodoTracker/pack_metadata.json

added relationship description 

Feed feodo add description

---

Packs/Whois/Integrations/Whois/Whois.py
Packs/Whois/ReleaseNotes/1_2_3.md
Packs/Whois/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36267
fixed an issue where the context was malformed (duplicate DT in DBotScore)

Whois: fixed whois and domain command outputs

---

Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.yml
Packs/QRadar/Integrations/QRadar_v3/QRadar_v3_test.py
Packs/QRadar/ReleaseNotes/2_0_2.md
Packs/QRadar/pack_metadata.json

https://github.com/demisto/etc/issues/36344
Fixed an issue where the LinkToOffense in QRadar added suffix of '/api' when it shouldn't.
Added a seperation between client server and base_url

QRadar v3 offense link bug

---

Packs/CommonScripts/ReleaseNotes/1_3_39.md
Packs/CommonScripts/Scripts/script-DBotAverageScore.yml
Packs/CommonScripts/TestPlaybooks/playbook-DbotAverageScore-Test.yml
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36345
The script did not handle the situation in which there was only one entry.

DbotAveragescore fix

---

Packs/CortexXDR/README.md

- [x ] Ready
Updated Cortex XDR Pack README.  This content will appear in Marketplace.

Updated Cortex XDR Pack README

---

Packs/ServiceNow/README.md

- [x ] Ready
Create content for the ServiceNow Content Pack. This information will appear in Marketplace.

Create ServiceNow Content Pack README.md

---

Packs/Zscaler/Integrations/Zscaler/Zscaler.py
Packs/Zscaler/Integrations/Zscaler/Zscaler.yml
Packs/Zscaler/ReleaseNotes/1_1_3.md
Packs/Zscaler/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36409
fixed a KeyError
release notes were copied from old RN file, adding `docs-approved` label.

Zscalar: Fix key error

---

Packs/URLHaus/Integrations/URLHaus/URLHaus.py
Packs/URLHaus/Integrations/URLHaus/URLHaus.yml
Packs/URLHaus/ReleaseNotes/1_0_3.md
Packs/URLHaus/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36419
fixed an issue where the payload returned from the API was null (line 154).

URLhuas: Fix none type iterable bug

---

Packs/Twinwave/README.md

Updating the README per official guidelines

update README with relevant information

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/33410

Teams Management - unskip test

---

Packs/MicrosoftGraphFiles/Integrations/MicrosoftGraphFiles/README.md

Done.
- [ x] Ready
fixes: link to the issue #35910
Added the required permissions to the Microsoft Graph File Integration README.

Update Microsoft Graph Files Integration README

---

Packs/QRadar/Integrations/QRadar/QRadar.py
Packs/QRadar/ReleaseNotes/2_0_4.md
Packs/QRadar/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36043
Updated the test-module to use the first offense and full-enrich it instead of calling fetch-incidents without any offenses limit to avoid the test-module from timing out. 

QradarV1: Update test-module

---

Packs/RSANetWitness_v11_1/Integrations/RSANetWitness_v11_1/README.md

related: https://github.com/demisto/etc/issues/36262
Added note to the readme.

RSA Netwitness readme note

---

Packs/FeedFeodoTracker/.pack-ignore
Packs/FeedFeodoTracker/TestPlaybooks/playbook-feodotrackeripblock_test_30_days.yml
Packs/FeedFeodoTracker/TestPlaybooks/playbook-feodotrackeripblock_test_currently__active.yml
Tests/conf.json

mock Feodo Tracker IP Blocklist Feed

mock Feodo Tracker IP Blocklist Feed

---

Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.yml
Packs/SplunkPy/ReleaseNotes/2_0_2.md
Packs/SplunkPy/TestPlaybooks/SplunkPy_KV_commands.yml
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/35509
added the ability to use a JSON format list to upload more than one entry at a time.

added an option to batch save to kv store

---

Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.yml
Packs/Active_Directory_Query/Integrations/Active_Directory_Query/connection_test.py
Packs/Active_Directory_Query/ReleaseNotes/1_1_10.md
Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.py
Packs/Active_Directory_Query/Scripts/IAMInitADUser/IAMInitADUser.yml
Packs/Active_Directory_Query/pack_metadata.json
Packs/ApiModules/Scripts/IAMApiModule/IAMApiModule.py
Packs/Attlasian/ReleaseNotes/1_0_1.md
Packs/Attlasian/pack_metadata.json
Packs/GitHub/ReleaseNotes/1_2_3.md
Packs/GitHub/pack_metadata.json
Packs/HelloIAMWorld/ReleaseNotes/1_0_3.md
Packs/HelloIAMWorld/pack_metadata.json
Packs/Okta/ReleaseNotes/2_1_9.md
Packs/Okta/pack_metadata.json
Packs/Salesforce/ReleaseNotes/1_0_6.md
Packs/Salesforce/pack_metadata.json
Packs/ServiceNow/ReleaseNotes/2_1_21.md
Packs/ServiceNow/pack_metadata.json
Packs/Slack/ReleaseNotes/1_3_19.md
Packs/Slack/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/34383
relates: https://github.com/demisto/etc/issues/35721
improved error handling in IAM AD (mainly by clearer error messages).

IAM - AD updates

---

Packs/MapPattern/Scripts/MapPattern/README.md
Packs/MapPattern/pack_metadata.json

Fixed a layout in README that is broken in the web.

Fixed a layout in README that is broken in the web.

---

Packs/QueryAI/README.md

Updated QueryAI pack's README with new format

---

Packs/Cyberint/Layouts/layoutscontainer-Cyberint_Incident_Layout.json
Packs/Cyberint/ReleaseNotes/1_0_6.md
Packs/Cyberint/pack_metadata.json

Add incident attachment files to the layout.

Cyberint - Add section to layout

---

Packs/TAXIIServer/Integrations/TAXIIServer/TAXIIServer.yml
Packs/TAXIIServer/ReleaseNotes/1_0_4.md
Packs/TAXIIServer/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36452

Taxii Server docker image update

---

Packs/AzureSecurityCenter/Integrations/AzureSecurityCenter_v2/AzureSecurityCenter_v2.yml
Packs/AzureSecurityCenter/ReleaseNotes/1_1_9.md
Packs/AzureSecurityCenter/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36538
Added the subscription_id argument to the azure-sc-get-alert command

AzureSecurityCenter: Add subscription_id arg

---

Packs/AbuseDB/Integrations/AbuseDB/AbuseDB.py
dev-requirements-py3.txt

Fixing SDK version in build to check BC.
can be seen here using this change: https://app.circleci.com/pipelines/github/demisto/content/83916/workflows/b2b7defe-4297-4f8e-a9f0-11d124966374/jobs/346175

fixing SDK version in build

---

Packs/Base/ReleaseNotes/1_10_16.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

Relationships typo

---

Packs/BastilleNetworks/README.md

Adds README.md to BastilleNetworks Pack.

Update BastilleNetworks pack README.md

---

Packs/BreachNotification-US/pack_metadata.json
Packs/GDPR/pack_metadata.json
Packs/HIPAA-BreachNotification/pack_metadata.json

fixes: https://github.com/demisto/content/pull/12568
`Packs/Compliance/IncidentFields/incidentfield-Breach_Confirmation.json` e.g in compliance pack is used in all 3 incident types in different packs:
```
"GDPR Data Breach",
"HIPAA Breach Notification",
"US Breach Notification"
```

GDPR, HIPAA, Breach - update deps, fix typos

---

Packs/Tidy/TestPlaybooks/Tidy_-_Test.yml
Tests/conf.json

Skipping Tidy.
Fixed small typo in the playbook name

Skipping Tidy

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/33217

Azure NSG Test Unskip

---

Packs/MicrosoftGraphListener/README.md

- [ x] Ready
Create Content Pack README for MicrosoftGraphListener. This content will appear in Marketplace.

Create Content Pack README for MicrosoftGraphListener

---

Packs/Base/ReleaseNotes/1_10_22.md
Packs/Base/Scripts/CreateIndicatorRelationship/CreateIndicatorRelationship.py
Packs/Base/Scripts/SearchIndicatorRelationships/SearchIndicatorRelationships.py
Packs/Base/pack_metadata.json

Fixed tests from relation to relationships
Fixed tests from relation to relationships

fixed relation to relationships

---

Packs/RubrikPolaris/README.md

n/a
This PR updates the README for the Rubrik Polaris pack.
n/a
n/a
n/a

Update Rubrik Polaris README

---

Packs/GSuiteSecurityAlertCenter/README.md

Fixed readme

---

Packs/Axonius/Integrations/Axonius/Axonius.yml
Packs/Axonius/ReleaseNotes/1_0_3.md
Packs/Axonius/pack_metadata.json

None
Axonius docker version bump 19245
None

Axonius docker version bump 19245

---

Packs/SplunkPy/Integrations/SplunkPy/README.md

Improved the incoming mirroring docs.

Splunk - Add incoming mirroring limitations

---

Packs/AgariPhishingDefense/README.md

Update Agari README.md

---

Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.py
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail.yml
Packs/MicrosoftGraphMail/Integrations/MicrosoftGraphMail/MicrosoftGraphMail_test.py
Packs/MicrosoftGraphMail/ReleaseNotes/1_0_20.md
Packs/MicrosoftGraphMail/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36378
we did a check if the folder id was changed by comparison the current folder path and the previous one. but we should also check if the account has been changed, which will also cause the folder id to be changed.

MicrosoftGraphMail: fix problem when changeing the account

---

Packs/Active_Directory_Query/Integrations/Active_Directory_Query/Active_Directory_Query.py
Packs/Active_Directory_Query/ReleaseNotes/1_1_11.md
Packs/Active_Directory_Query/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36555
fixed an issue where null values were returned when no results are found.

Active Directory Query v2: fixed null outputs

---

.gitlab-ci.yml
.gitlab/ci/nightly.yml
.gitlab/ci/on-push.yml
Tests/configure_and_test_integration_instances.py
Utils/gitlab_triggers/trigger_build_url.sh
Utils/gitlab_triggers/trigger_content_nightly_build.sh

- Added the rules with which the nightly flow will work
- A few adjustments needed for gitlab env.
- A trigger script.
https://github.com/demisto/etc/issues/35765
gitlab-commit: https://code-stage.pan.run/xsoar/content/-/pipelines/202884
gitlab-nightly: https://code-stage.pan.run/xsoar/content/-/pipelines/202885
Circle-nightly: https://app.circleci.com/pipelines/github/demisto/content/83763/workflows/30ddfe8e-6aaf-4bd1-b36d-3f3f2bce5f86

Configuring nightly

---

Packs/RecordedFuture/Integrations/RecordedFuture/README.md
Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.py
Packs/RecordedFuture/Integrations/RecordedFuture/RecordedFuture.yml
Packs/RecordedFuture/ReleaseNotes/1_1_1.md
Packs/RecordedFuture/pack_metadata.json

Added two new fields to CVE intelligence. Related Links and CPE information.
These are both added to the context and markdown (two new tables). 

Recorded Future: Added two new fields to intelligence lookups for CVEs.

---

Packs/Cymulate/README.md

Cymulate Docs Fix

---

dev-requirements-py3.txt

opening PR to see demisto-sdk 1-3-6 passes

SDK release 1-3-6 content branch

---

Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
Packs/ExpanseV2/ReleaseNotes/1_4_1.md
Packs/ExpanseV2/pack_metadata.json

removed duplicate argument definition

Expanse v2: removed duplicate argument definition

---

Packs/CommonTypes/ReleaseNotes/2_8_15.md

fixes: https://github.com/demisto/etc/issues/33806
Fix release notes for common types pack.

fix release notes for common types

---

Packs/RiskSense/README.md

Updated ReadMe.md

---

.circleci/build-requirements.txt

Added new requirement to pygithub

added requirement - pygithub

---

Packs/EWS/Integrations/EWSv2/README.md

Added a link to the new EWS V2 Troubleshooting article.

Add link to EWS V2 Troubleshooting information

---

Packs/PrismaCloud/Integrations/RedLock/README.md

Fix broken links to prisma cloud api docs.

prisma cloud readme: fix broken links

---

Packs/BeyondTrust_Password_Safe/Integrations/BeyondTrust_Password_Safe/README.md

BeyondTrust Password Safe README - change incident to credential

---

Packs/UrlScan/Integrations/UrlScan/UrlScan.py
Packs/UrlScan/ReleaseNotes/1_1_6.md
Packs/UrlScan/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36806
Removed junk relationships

Url scan remove not needed relationships

---

Utils/github_workflow_scripts/handle_external_pr.py

Update contribution team

---

Packs/TIM_Processing/README.md

@David-BMS see my edit. The link you had there is broken. I removed it.

tim processing: removing broken link

---

Packs/SailPointIdentityIQ/.secrets-ignore
Packs/SailPointIdentityNow/.secrets-ignore

add to secrets ignore

---

Packs/Telegram/Integrations/Telegram/Telegram.yml
Packs/Telegram/ReleaseNotes/1_0_2.md
Packs/Telegram/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36763
Added the proxy parameter to the integration

Telegram - Added proxy parameter 

---

Packs/QRadar/Integrations/QRadar_v3/README.md

Adding to README permissions description

Add-To-QRadar-V3-Readme-Permissions-Details

---

Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Domain_Indicators.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Domain_Indicators_README.md
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Hash_Indicators.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Hash_Indicators_README.md
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_IP_Indicators_README.md
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Url_Indicators.yml
Packs/TIM_Processing/Playbooks/playbook-TIM_-_Run_Enrichment_For_Url_Indicators_README.md
Packs/TIM_Processing/ReleaseNotes/1_1_7.md
Packs/TIM_Processing/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37069
Updated the playbooks inputs descriptions to match the condition. 
The playbook works as expected.

Fix input descriptions

---

Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.py
Packs/Palo_Alto_Networks_WildFire/Integrations/Palo_Alto_Networks_WildFire_v2/Palo_Alto_Networks_WildFire_v2.yml
Packs/Palo_Alto_Networks_WildFire/ReleaseNotes/1_3_4.md
Packs/Palo_Alto_Networks_WildFire/pack_metadata.json

N/A
When running !file with, "local variable 'url' referenced before assignment" sometimes occurrs.

Fixed an issue where "local variable 'url' referenced before assignment" occurred.

---

Packs/GoogleSafeBrowsing/.secrets-ignore
Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.py
Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2.yml
Packs/GoogleSafeBrowsing/Integrations/GoogleSafeBrowsingV2/GoogleSafeBrowsingV2_test.py
Packs/GoogleSafeBrowsing/ReleaseNotes/2_0_1.md
Packs/GoogleSafeBrowsing/TestPlaybooks/playbook-Google_Safe_Browsing_V2_Test.yml
Packs/GoogleSafeBrowsing/pack_metadata.json
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/37108
Fixed an issue where the url command returned an error where no results were found.

Google Safe Browsing v2 bug fix

---

Tests/scripts/collect_tests_and_content_packs.py

* improved few log messages
* fixed typo

Collect Tests: improved log messages

---

Tests/conf.json

unmock mcafee esm regular test playbook

unmock mcafee esm regular test playbook

---

Packs/CommonScripts/ReleaseNotes/1_3_48.md
Packs/CommonScripts/ReleaseNotes/1_3_50.md
Packs/CommonScripts/Scripts/ExtractEmailFormatting/ExtractEmailFormatting.yml
Packs/CommonScripts/Scripts/ExtractEmailFormatting/README.md
Packs/CommonScripts/TestPlaybooks/playbook-ExtractEmail-Test.yml
Packs/CommonScripts/pack_metadata.json
Packs/CommonTypes/IndicatorTypes/reputation-email.json
Packs/CommonTypes/ReleaseNotes/2_9_3.md
Packs/CommonTypes/ReleaseNotes/2_9_4.md
Packs/CommonTypes/pack_metadata.json

related: https://github.com/demisto/content/pull/12710
updated the name of the script

ExtractEmail: updated the name of the ExtractEmail script

---

Packs/Base/ReleaseNotes/1_10_28.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

related: https://github.com/demisto/etc/issues/33656, https://github.com/demisto/etc/issues/35560
https://github.com/demisto/content/pull/12499
CSP Add Threat Intel objs.

CSP Add Threat Intel objs

---

Packs/TrendMicroCAS/TestPlaybooks/playbook-playbook_TrendmicroCAS_Test.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/32730

Fixed TrendMicroCAS test

---

Packs/ThinkstCanary/Integrations/ThinkstCanary/README.md

Thinks Canary: fix docs link

---

Tests/conf.json

Making Azure NSG integration unmockable in tests.
fixes: https://github.com/demisto/etc/issues/33217

Moved Azure NSG To Unmockable Integrations

---

Packs/CofenseTriage/README.md

Fix the links at the bottom of the readme.

cofense triage readme: fix links

---

Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule.py
Packs/ApiModules/Scripts/AWSApiModule/AWSApiModule_test.py

AWS api module fixes

---

Tests/Marketplace/mandatory_premium_packs.json

fixes: https://github.com/demisto/etc/issues/35887
Delete PassiveTotalPremium and RiskIQDigitalFootprintPremium packs from ***mandatory_premium_packs.json***

Delete PassiveTotalPremium and RiskIQDigitalFootprintPremium

---

Packs/Base/ReleaseNotes/1_11_2.md
Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
Packs/Base/pack_metadata.json

add field for clustering to output json

add field for clustering to output json

---

Packs/SplunkPy/Integrations/SplunkPy/README.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy.py
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_description.md
Packs/SplunkPy/Integrations/SplunkPy/SplunkPy_test.py
Packs/SplunkPy/ReleaseNotes/2_0_3.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36653
Returning the delta changed and not the whole notable in `get-remote-data` command.

Splunk Mirroring Bugfix

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/33951
Unskipped the test as is seems to be working successfully.

Field polling - unskip test

---

Packs/SlashNextPhishingIncidentResponse/README.md

Signed-off-by: Saadat Abid <saadatabid@gmail.com>

[slashnext-251] Updated README.md to removed extra newline spaces.

---

Packs/SplunkPy/Classifiers/classifier-Splunk_-_Notable_Generic_Outgoing_Mapper.json
Packs/SplunkPy/Playbooks/playbook-Splunk_Generic.yml
Packs/SplunkPy/Playbooks/playbook-Splunk_Generic_README.md
Packs/SplunkPy/ReleaseNotes/2_1_1.md
Packs/SplunkPy/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37361

Splunk content fixes

---

Tests/Marketplace/approved_tags.json

fixes: https://github.com/demisto/etc/issues/33793#issuecomment-828272754
Add a relationship tag to the tags list

Add relationship to tags list

---

dev-requirements-py3.txt

version 1.3.8 for demisto-sdk.

1.3.8 sdk release

---

Packs/FeedBlocklist_de/README.md

- [x ] Ready
Create content for Blocklist.de Feed content pack. This information will appear in Marketplace.

Create content for Blocklist.de Feed content pack

---

Packs/AlienVault_OTX/pack_metadata.json
Packs/AutoFocus/pack_metadata.json
Packs/FeedBambenekConsulting/pack_metadata.json
Packs/FeedFeodoTracker/pack_metadata.json
Packs/Flashpoint/pack_metadata.json
Packs/UrlScan/pack_metadata.json
Packs/VirusTotal/pack_metadata.json
Packs/XForceExchange/pack_metadata.json
Packs/ipinfo/pack_metadata.json
Tests/Marketplace/approved_tags.json

related: https://github.com/demisto/etc/issues/33793#issuecomment-828272754
Add Relationship tag to relevant packs.

Add Relationship tag to relevant packs

---

Packs/MISP/pack_metadata.json

Done.
- [x ] Ready
Updated description in pack.metadata.json.

MISP Update pack_metadata.json

---

Packs/EWSMailSender/README.md

Create EWSMailSender content pack README. This information will appear in Marketplace.

Create EWSMailSender content pack README

---

Packs/XForceExchange/README.md

Done.
- [ x] Ready
Created content for the Pack README for IBM X-Force Exchange.  This content will appear in Marketplace.

Created Pack README for IBM X-Force Exchange

---

Packs/MxToolBox/README.md

Created content pack README for MXToolBox.  This content will appear in Marketplace.

Create Content Pack README for MXToolBox

---

Packs/Threat_Crowd/README.md

- [x ] Ready
Created content for the Threat Crowd content pack README. This content will be displayed in Marketplace.

Content Pack README for Threat Crowd

---

Packs/Palo_Alto_Networks_WildFire/README.md

- [ x] Ready
Create Palo Alto Networks Wildfire Content Pack README

Palo Alto Networks Wildfire Content Pack README

---

Packs/MicrosoftGraphMail/README.md

- [x ] Ready
Created content for Microsoft Graph Mail Pack README.

Microsoft Graph Mail Pack README

---

Packs/UrlScan/README.md

- [x ] Ready
Create content for the URLScan Pack README. This information will appear in Marketplace.

Create content for the URLScan Pack README

---

Packs/Active_Directory_Query/README.md

- [x ] Ready
Created a pack readme for Active Directory Query. This content will appear in Marketplace.

Create a pack readme for Active Directory Query

---

Packs/CaseManagement-Generic/Dashboards/My_Incidents.json
Packs/CaseManagement-Generic/Dashboards/dashboard-Incidents_Overview.json
Packs/CaseManagement-Generic/ReleaseNotes/1_2_0.md
Packs/CaseManagement-Generic/pack_metadata.json

fixes: N/A
Default date range for the Incidents Overview dashboard was All Times.  Set this to 30 days to match the My Incidents dashboard.  Updated Open Incidents by Role widget on Incidents overview as the query had all statuses.
N/A

updating case management dashboards with 30 day date range default

---

Packs/Base/README.md
Packs/Identity/README.md

Fixed packs readme

---

Tests/conf.json

skip atp indicator test

---

Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.py
Packs/Elasticsearch/Integrations/Elasticsearch_v2/Elasticsearch_v2.yml
Packs/Elasticsearch/ReleaseNotes/1_1_5.md
Packs/Elasticsearch/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/36734
a timeout parameter was added to the instance configuration.

ElasticSearch v2: adding the timeout parameter

---

Packs/Base/ReleaseNotes/1_11_3.md
Packs/Base/Scripts/DBotPredictPhishingWords/DBotPredictPhishingWords.yml
Packs/Base/pack_metadata.json
Packs/ML/ReleaseNotes/1_2_9.md
Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.py
Packs/ML/Scripts/DBotPredictOutOfTheBoxV2/DBotPredictOutOfTheBoxV2.yml
Packs/ML/pack_metadata.json

Updated OOB model version (URLS). Continue this pr: https://github.com/demisto/content/pull/12767 

Updated OOB model version (URLS) 

---

Packs/DeprecatedContent/Integrations/PaloAltoNetworksCortex/PaloAltoNetworksCortex_test.py

Uses `freezegun` for time calculation function.

PANW - Stabilize time UT

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29593
unmocking the test as there are 2 branches in it for setting the alert status based on current status and hence cannot be mocked

MS ATA - unskip and unmock test

---

Packs/PagerDuty/TestPlaybooks/playbook-PagerDuty_Test.yml

fixes: https://github.com/demisto/etc/issues/35115

pagerduty update tpb

---

Packs/CommonWidgets/ReleaseNotes/1_0_9.md
Packs/CommonWidgets/Widgets/widget-ImagePlaceholder.json
Packs/CommonWidgets/Widgets/widget-Pagebreak.json
Packs/CommonWidgets/Widgets/widget-TextWidget.json
Packs/CommonWidgets/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37471

Utility Widgets - modify category to utilities

---

Packs/Mimecast/Integrations/MimecastV2/README.md

mimecast: fix link

---

Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/NetscoutArborSightline.yml
Packs/NetscoutArborSightline/Integrations/NetscoutArborSightline/README.md
Packs/NetscoutArborSightline/ReleaseNotes/1_0_1.md
Packs/NetscoutArborSightline/pack_metadata.json

Sightline description

---

Packs/ServiceNow/Integrations/ServiceNowv2/README.md

add note to readme about the integration not working with snow sir

ServiceNow v2 - add note about the integration not working with the sir module

---

Packs/Tanium/.pack-ignore

fixed a duplicate ignore

---

Packs/CommonScripts/ReleaseNotes/1_3_53.md
Packs/CommonScripts/Scripts/script-Set.yml
Packs/CommonScripts/Scripts/script-Set_README.md
Packs/CommonScripts/pack_metadata.json

fixes: https://github.com/demisto/content-docs/issues/655

Set - add array and json examples to value desc

---

.github/workflows/check-contribution-form-filled.yml
Utils/github_workflow_scripts/check_if_needs_to_fill_contribution_form.py
Utils/github_workflow_scripts/utils.py

fixes: https://github.com/demisto/etc/issues/28759
Added status check to verify that `Contribution Form Filled` label exists on external PRs.

Verify contribution form filled label

---

Packs/SumoLogic_Cloud_SIEM/README.md

Updated readme

---

Packs/ipinfo/Integrations/ipinfo_v2/ipinfo_v2.py
Packs/ipinfo/ReleaseNotes/2_0_2.md
Packs/ipinfo/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37064
Recurring test failures due to timeout, see related issue

updated ipinfo timeout to 20s

---

Packs/Base/ReleaseNotes/1_11_8.md
Packs/Base/Scripts/DBotTrainClustering/DBotTrainClustering.py
Packs/Base/Scripts/DBotTrainClustering/dbottrainclustering_test.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37375
Add prefix cluster name in case we have same cluster name

Add prefix cluster name

---

Packs/XSOARLabUpdates/Playbooks/NewPacksNotifier.yml
Packs/XSOARLabUpdates/ReleaseNotes/1_0_1.md
Packs/XSOARLabUpdates/pack_metadata.json

https://github.com/demisto/etc/issues/32263
Added support for sending to multiple channels.

NewPacksNotifier - Support multiple channels

---

dev-requirements-py3.txt

The next SDK version will depend on ruamel version 0.17.4 which will require an update in the content deps:
https://github.com/demisto/content/pull/12936/checks?check_run_id=2710013091

updating ruamel requirements

---

Packs/PopularCybersecurityNews/Integrations/PopularNews/PopularNews.py
Packs/PopularCybersecurityNews/ReleaseNotes/1_0_2.md
Packs/PopularCybersecurityNews/pack_metadata.json

related: https://github.com/demisto/content/pull/11774#discussion_r632034419

Popular News - Improved parsing for Krebs on Security

---

Packs/CommonTypes/IncidentFields/incidentfield-Similar_incidents_Dbot.json
Packs/CommonTypes/ReleaseNotes/3_0_0.md
Packs/CommonTypes/ReleaseNotes/3_0_1.md
Packs/CommonTypes/pack_metadata.json

Removed space in incident field name

Removing space from field name

---

Packs/Threat_Crowd/ReleaseNotes/2_0_1.md

fix rn - threat crowd

---

Packs/ExpanseV2/IncidentFields/incidentfield-Expanse_Cloud_Management_Status.json

Updated fromVersion value to 6.0.0

Expanse v2 - fix expansecloudmanagementstatus field

---

.github/workflows/check-contributor-pack.yml

Adding check if email_api_key global variable exist.

checking if there email_api_key global var

---

README.md

Content README: fix link

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/29055

unskip TPB

---

Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-CVE-2021-22893_-_Pulse_Connect_Secure_RCE.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-Codecov_Breach_-_Bash_Uploader.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_5_5.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-HAFNIUM_-_Exchange_0-day_exploits_6.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-NOBELIUM_-_wide_scale_APT29_spear-phishing.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_5_9_9.yml
Packs/MajorBreachesInvestigationandResponse/Playbooks/playbook-SolarStorm_and_SUNBURST_Hunting_and_Response_Playbook_6.yml
Packs/MajorBreachesInvestigationandResponse/ReleaseNotes/1_6_6.md
Packs/MajorBreachesInvestigationandResponse/pack_metadata.json

Adding Skip if automation / playbook unavailable

Fix rapid breach dependencies

---

Packs/Base/ReleaseNotes/1_12_2.md
Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
Packs/Base/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/37747

CommonServerPython - added service_account to sensitive params

---

Packs/CommonWidgets/ReleaseNotes/1_0_10.md
Packs/CommonWidgets/Widgets/widget-IndicatorBadActivity.json
Packs/CommonWidgets/Widgets/widget-IndicatorBadActivityType.json
Packs/CommonWidgets/Widgets/widget-IndicatorManualNumber.json
Packs/CommonWidgets/Widgets/widget-IndicatorManualUsers.json
Packs/CommonWidgets/pack_metadata.json

related: https://github.com/demisto/etc/issues/30973

Change the names of some of the widgets we have in reports.

---

Tests/conf.json

remock testplaybooks of wildfire integration

---

Packs/RubrikPolaris/Scripts/RubrikCDMClusterConnectionState/README.md
Packs/RubrikPolaris/Scripts/RubrikRadarFilesAdded/README.md
Packs/RubrikPolaris/Scripts/RubrikRadarFilesDeleted/README.md
Packs/RubrikPolaris/Scripts/RubrikRadarFilesModified/README.md
Packs/RubrikPolaris/Scripts/RubrikSonarOpenAccessFiles/README.md
Packs/RubrikPolaris/Scripts/RubrikSonarTotalHits/README.md

Replace Demisto to Cortex XSOAR in RubrikPolaris scripts.

Replace Demisto to Cortex XSOAR

---

Tests/conf.json

fixes https://github.com/demisto/etc/issues/37620

Falcon Intel - remove test

---

.gitignore

related to: https://github.com/demisto/demisto-sdk/pull/1319
added the dir `coverage_report` and any file `.coverage` to gitignore.

coverage changes

---

Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.py
Packs/ExpanseV2/Integrations/ExpanseV2/ExpanseV2.yml
Packs/ExpanseV2/Integrations/ExpanseV2/README.md
Packs/ExpanseV2/ReleaseNotes/1_5_1.md
Packs/ExpanseV2/Scripts/ExpanseRefreshIssueAssets/ExpanseRefreshIssueAssets.py
Packs/ExpanseV2/Scripts/ExpanseRefreshIssueAssets/ExpanseRefreshIssueAssets.yml
Packs/ExpanseV2/pack_metadata.json

N/A
This PR addresses several issues with utilizing the new cloud resource asset type within existing ExpanseV2 pack commands. 
N/A

Xpanse - Cloud resource fixes

---

Tests/Marketplace/upload_packs.py
Tests/private_build/upload_packs_private.py
Tests/scripts/prepare_private_content_packs_for_testing.sh

fixes: https://github.com/demisto/etc/issues/33657
Removed the `upload_id_set` func from `upload_packs` script.
Removed the id_set argument from `upload_packs_private`

Removed id_set from private

---

Packs/Microsoft365Defender/Integrations/Microsoft365Defender/Microsoft365Defender_description.md
Packs/Microsoft365Defender/ReleaseNotes/1_0_1.md
Packs/Microsoft365Defender/pack_metadata.json

update link in the description to xsoar.pan.dev's doc instead of microsoft's

update device code flow link

---

Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml

fixes: https://github.com/demisto/etc/issues/26905

misp v2 - fix TPB

---

Packs/TIM_Processing/README.md

- [ x] Ready
Added 2 bullets to the What does this pack do? section.

Updated TIM_Processing Pack README

---

Packs/Lost_Stolen_Device/README.md

lost stollen device: fix link

---

Packs/EWS/.pack-ignore

The description is referring to the Demisto app hence should be ignored.

ignoring DS107 in EWSO365 description

---

Packs/UrlScan/README.md
Packs/UrlScan/ReleaseNotes/1_1_7.md
Packs/UrlScan/pack_metadata.json

URLScan.io Adoption

---

Packs/ArcSightLogger/Integrations/integration-ArcSightLogger.yml
Packs/ArcSightLogger/ReleaseNotes/1_0_4.md
Packs/ArcSightLogger/pack_metadata.json

Wrong condition on status code check created false "failed logout" result.

Arcsight login fix

---

Packs/EWS/.pack-ignore
Packs/HelloWorld/.pack-ignore

Ignoring readme demisto validation

Ignoring readme demisto validation

---

Packs/MISP/TestPlaybooks/playbook-MISP_V2-Test.yml

fixes: https://github.com/demisto/etc/issues/26905
Because TPB's run 2 times at night the conditions below should be changed.

misp v2 fix tpb

---

Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.py
Packs/Linkshadow/Integrations/Linkshadow/Linkshadow.yml
Packs/Linkshadow/Integrations/Linkshadow/Linkshadow_test.py
Packs/Linkshadow/ReleaseNotes/1_0_2.md
Packs/Linkshadow/pack_metadata.json

…caused typeerror. Test update on resolving the same

Linkshadow: First fetch fix

---

Tests/sdknightly/create_entities_for_nightly_sdk.py

Nightly SDK fix

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/26601
fixed in: https://github.com/demisto/content/pull/13078

removed "Pwned v2 test" from skipped tests

---

.circleci/config.yml
.gitlab/ci/sdk-nightly.yml

config.yml fix for nightly SDK

---

Packs/CortexXDR/TestPlaybooks/Coretx_XDR_-_IOC_-_Test_without_fetch.yml
Tests/conf.json

fixes: https://github.com/demisto/etc/issues/25598
Probably the problem will not appear in case that proxy will be used.

new test for Cortex XDR - IOC integration

---

Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.py
Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration.yml
Packs/XMCyber/Integrations/XMCyberIntegration/XMCyberIntegration_test.py
Packs/XMCyber/ReleaseNotes/1_0_8.md
Packs/XMCyber/pack_metadata.json

fixes: issue with commands using the search_entity api. These are the hostname and ip commands.
Fixes a bug in API call
Before:
After:
- [ X ] 6.0.0
- [ X ] No
- [ X ] Tests
- [ X ] Documentation

fix broken api

---

.circleci/config.yml
.gitlab/ci/sdk-nightly.yml
dev-requirements-py3.txt

SDK nightly - Download files change, validation on download

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/25604
Unskip test to see if it still fails as server seems to be up at this moment

unskip Active Directory - Get User Manager Details - Test

---

Packs/Base/ReleaseNotes/1_12_6.md
Packs/Base/Scripts/script-CommonServer.yml
Packs/Base/pack_metadata.json
Packs/CommonScripts/TestPlaybooks/IsIPInRanges_-_Test.yml

fixes: https://github.com/demisto/etc/issues/38016

CommonServer - handle zero ip address subnet

---

Packs/CommonTypes/.pack-ignore
Packs/FireEyeCommonFields/.pack-ignore

SDK nightly fix: added IF100 to relevant .pack-ignore files

---

Tests/conf.json

fixes: https://github.com/demisto/etc/issues/27942
fixes: https://github.com/demisto/etc/issues/27941
fixed creds.

unskip ews unmockable tests

---

Packs/CommonWidgets/ReleaseNotes/1_1_1.md
Packs/CommonWidgets/Widgets/widget-IndicatorBadActivityType.json
Packs/CommonWidgets/pack_metadata.json

fixes: https://github.com/demisto/etc/issues/38035

Malicious Indicators Activity by Type - add time resolution

---

Packs/ipinfo/TestPlaybooks/playbook-IPinfo_v2_Test.yml

https://github.com/demisto/etc/issues/38060
Changing the IP to be tested on IPinfo's test playbook from `1.1.1.1` to `8.8.8.8`

changed tested ip to one with a hostname
